IgniteUI/igniteui-angular

src/tabs/tab-item.component.ts
src/tabs/tabs.component.spec.ts

Add HostListener for resize to update selector width

---

src/grid/cell.component.ts
src/grid/grid-selection.spec.ts

Cell selection is lost after sorting

---

src/grid/grid-header.component.ts
src/grid/grid.pinning.spec.ts

fix(igxGrid): Filtering dialog overlapping with pinned columns

---

demos/app/app.component.ts
demos/app/app.module.ts
demos/app/app.routing.ts
demos/app/grid-column-pinning/sample.component.html
demos/app/grid-column-resizing/sample.component.css
demos/app/grid-column-resizing/sample.component.html
demos/app/grid-column-resizing/sample.component.ts
demos/app/grid-column-resizing/sample.module.ts
demos/app/grid-performance/sample.component.html
src/grid/column-resizing.spec.ts
src/grid/grid-header.component.ts

Remove column resizing feature from existing demos and add a separate one.

Add a separate demo for column resizing

---

src/tabs/tabs.component.ts

Closes IgniteUI/igniteui-angular-samples#178 .

Bug fix #178

---

src/date-picker/date-picker.component.ts
src/dialog/dialog-content.component.html
src/dialog/dialog.component.spec.ts
src/dialog/dialog.component.ts

[igxDatePicker] set the focus into the dialog when calendar appears

---

src/core/styles/components/grid/_grid-component.scss
src/core/styles/components/grid/_grid-theme.scss
src/grid/grid-header.component.html

refactor(grid): add column resizing themability

---

src/grid/cell.component.ts
src/grid/grid-selection.spec.ts
src/grid/grid.component.ts

Closes #965  .  
This needs unit tests but they seem quite hard to implement cleanly.
@rkaraivanov - please, try this without `setVerticalScrollSubscription` - I don't think it works. There is a sample that you can use in #965.
***TODO:*** - currently not possible to scroll for the test to be useful
~~- [ ] Add a bug test~~

Fix for #965 - adding change detection for ngModel bound templates in igxGrid

---

CHANGELOG.md

Adjust documentation for grid selection in CHANGELOG.md

Edit grid selection section in changelog

---

src/core/styles/components/grid/_grid-theme.scss

fix(grid): remove cursor resize from handle

---

src/grid/grid-selection.spec.ts
src/grid/grid.component.ts

Header checkbox

---

src/tabs/tabs-group.component.ts
src/tabs/tabs.component.ts

Closes IgniteUI/igniteui-angular-samples#216 .

Don't focus the selected tab on init

---

src/grid/README.md
src/grid/grid.component.ts

Expose reflow() method so it can be called publicly.

---

src/core/styles/components/_common/_igx-display-container.scss

fix(grid): grid cells appear on top of overlayed items

---

src/date-picker/date-picker.component.html

fix(datePicker): set readonly on datePicker input Closes: #1098

---

src/grid/README.md

docs(igxGrid): Update Grid Readme.md

---

src/grid/grid.component.spec.ts

Tests for issue 1054

---

CHANGELOG.md
src/core/styles/base/_index.scss
src/core/styles/themes/_core.scss
src/core/styles/themes/_index.scss
src/core/styles/themes/_utilities.scss

feat(themes): add theming utilities

---

src/grid/grid.component.spec.ts

Uncomment test check due to being already fixed in PR #1084.

---

src/core/selection.ts
src/grid/grid.component.ts

Improve Row selection performance

---

demos/app/grid-performance/sample.component.html
src/grid/row.component.ts

Remove duplicate HostBindings

---

CHANGELOG.md
demos/app/date-picker/sample.component.html
demos/app/date-picker/sample.component.ts
src/date-picker/date-picker.component.spec.ts
src/date-picker/date-picker.component.ts

#1121 igx-datepicker expose onClose event 

---

src/core/styles/components/_common/_igx-vhelper.scss
src/core/styles/components/dialog/_dialog-theme.scss

fix(dialog): dialog overlay appears below grid elements

---

src/core/styles/components/_common/_igx-vhelper.scss
src/core/styles/components/dialog/_dialog-theme.scss

Re targeted https://github.com/IgniteUI/igniteui-angular/pull/1113 PR from the same branch to 5.3.x instead

#1111 dialog overlay appears below grid elements

---

README.md

docs(general): Fixing README.md broken inks

---

src/directives/input/input.directive.spec.ts
src/directives/input/input.directive.ts

Mark disabled property as Input

---

src/grid/cell.component.ts

Closes #1100
Adjust how "arrow up" key navigation is handled to mirror "arrow down" key navigation.

Adjust cell navigation on arrow up

---

src/grid/column-resizing.spec.ts
src/grid/grid-header.component.ts
src/grid/grid.component.ts

Fix grid not recalculating its heights when performing actions like resizing.

---

src/grid/README.md

Add onRowSelectionChange event to grid README

---

src/core/styles/components/_common/_igx-display-container.scss

fix(igxForOf): Fix bottom row being cut when the display container is not virtual #1131

---

src/grid/README.md

Add back row selection API to readme

---

src/calendar/calendar.component.spec.ts

test(igxCalendar): prevent spewing up errors from calendar tests

---

src/grid/cell.component.ts
src/grid/cell.spec.ts
src/grid/grid.common.ts
src/tabs/tabs.component.spec.ts

 caret can't be moved in a editing cell

---

src/grid/grid-selection.spec.ts

Remove console log

---

.github/CONTRIBUTING.md

docs(general): Updating CONTRIBUTING.md with some new statuses

---

src/directives/mask/README.md

Update igxMask readme file

---

src/data-operations/filtering-condition.ts
src/grid/grid-filtering-ui.spec.ts
src/grid/grid-filtering.spec.ts

fix(grid): do not match null and undefined when filtering by false #1052

---

src/grid/grid.component.spec.ts
src/grid/grid.component.ts

Preserve the set width in %

---

src/grid/grid-header.component.ts
src/grid/grid.sorting.spec.ts

Valid sorting icon when sorting using the grid API

---

src/grid/grid-header.component.ts
src/grid/grid.sorting.spec.ts

Valid sorting icon when sorting using the grid API (5.3.x)

---

src/grid/grid-summary.spec.ts
src/grid/grid.component.ts

Fix Enabling summaries during runtime when igxGrid doesn't have height specified

---

src/grid/cell.spec.ts

Add tests for keyboard navigtaion.

---

src/grid/grid-filtering.component.ts
src/grid/grid-filtering.spec.ts

Filtering icon highlighting when using the API

---

src/grid/grid.component.ts
src/grid/grid.pinning.spec.ts

fix(pinning): Adding unpinned area min width limitation - master. #1129

---

ROADMAP.md

Adding column moving
Closes # .  

Adding column moving

---

src/directives/for-of/for_of.directive.ts
src/grid/grid-summary.spec.ts

Fix igxForOf startIndex is not being updated before calculating chunk size.

---

CHANGELOG.md
src/dialog/README.md
src/dialog/dialog-content.component.html
src/dialog/dialog.component.spec.ts
src/dialog/dialog.component.ts
src/dialog/dialog.directives.ts

igxDialog - add ability for title and actions customization

---

src/grid/grid-filtering.spec.ts
src/grid/grid.component.spec.ts
src/grid/grid.component.ts

When filter and edit the column that is filtered by the value persists onto the row below

---

src/dialog/dialog-content.component.html

Set type of buttons to be 'button'

---

src/core/styles/components/grid/_grid-component.scss
src/core/styles/components/grid/_grid-theme.scss
src/grid/cell.component.ts
src/grid/cell.spec.ts

fix(igxGridCellComponent): no indication when cell in edit mode

---

src/grid/grid-filtering-ui.spec.ts
src/grid/grid-filtering.component.ts

fix(igxgrid): reset button must be active if filtering is applied #1263

---

CHANGELOG.md

docs(general): Adding fixed bugs in version 5.3.1 to the Changelog

---

CHANGELOG.md

chore(changelog): move dblclick event in the newly created section 6.0.0

---

src/core/styles/components/grid/_grid-component.scss
src/core/styles/components/grid/_grid-theme.scss
src/grid/grid-filtering-ui.spec.ts
src/grid/grid.component.html
src/grid/grid.component.ts

refactor(grid): display empty grid message when no data

---

src/directives/for-of/for_of.directive.ts
src/grid/grid.component.spec.ts

Closes #1283 .
Please re-test https://github.com/IgniteUI/igniteui-angular/issues/1136 with these changes.

 fix(igxGrid): Columns not displayed on screen maximize #1283

---

CHANGELOG.md
src/grid/grid-filtering-ui.spec.ts
src/grid/grid-filtering.component.html
src/grid/grid-filtering.component.ts

Add All option to the filter UI for boolean columns #1286 - master

---

ROADMAP.md

Adding update to Angular 6
Closes # .  

Adding update to Angular 6

---

src/grid/grid-filtering-ui.spec.ts
src/grid/grid-filtering.component.html
src/grid/grid-filtering.component.ts

refactor(grid): focus input after opening the filtering UI #1290

---

src/services/csv/csv-exporter.ts
src/services/excel/excel-exporter.ts
src/services/exporter-common/base-export-service.ts

Remove grid dependency from the exporters

---

demos/package-lock.json
package-lock.json

fix(package-lock): update natives package manually

---

src/date-picker/date-picker.component.spec.ts
src/date-picker/date-picker.component.ts

fix(igxDatePicker): notify ngModel for updated value through API metho

---

src/core/styles/components/grid-filtering/_grid-filtering-theme.scss

fix(themes): button background and text have the same color

---

src/carousel/carousel.component.html
src/carousel/carousel.component.spec.ts
src/carousel/carousel.component.ts

Support for keyboard navigation in carousel

---

src/carousel/carousel.component.html
src/carousel/carousel.component.spec.ts
src/carousel/carousel.component.ts

fix(carousel): support for keyboard navigation #1139

---

src/progressbar/circularbar.component.spec.ts
src/progressbar/linearbar.component.spec.ts
src/progressbar/progressbar.component.ts

fix(progressbar): when accpet string progress should remain the same

---

src/progressbar/circularbar.component.spec.ts
src/progressbar/linearbar.component.spec.ts
src/progressbar/progressbar.component.ts

fix(progressbar): progress works both with string and numeric values

---

ROADMAP.md

Marking update to Angular 6 as Done
Closes # .  

Marking update to Angular 6 as Done

---

projects/igniteui-angular/src/lib/chips/chip.component.html
projects/igniteui-angular/src/lib/chips/chip.component.ts
projects/igniteui-angular/src/lib/chips/chips-area.component.ts
projects/igniteui-angular/src/lib/core/styles/components/grid/_grid-theme.scss
projects/igniteui-angular/src/lib/grid/grid.component.html
projects/igniteui-angular/src/lib/grid/grid.component.ts
projects/igniteui-angular/src/lib/grid/grid.module.ts
src/app/chips/chips.sample.css
src/app/chips/chips.sample.html
src/app/chips/chips.sample.ts
src/app/grid-groupby/grid-groupby.sample.css
src/app/grid-groupby/grid-groupby.sample.ts

Integrate igxChip and igxChip area inside the igxGrid. Fix GroupBy demo lint.

---

projects/igniteui-angular/src/lib/badge/badge.component.ts

docs(igxBadge): Add api docs for igxBadge

---

projects/igniteui-angular/src/lib/date-picker/date-picker.component.spec.ts
projects/igniteui-angular/src/lib/date-picker/date-picker.component.ts

NgModel bind value is not working as expected datepicker

---

projects/igniteui-angular/src/lib/directives/input/input.directive.spec.ts
projects/igniteui-angular/src/lib/directives/input/input.directive.ts

Fixed igxInput label overlapping (6.0.x)

---

projects/igniteui-angular/src/lib/grid/api.service.ts
projects/igniteui-angular/src/lib/grid/grid.component.ts
projects/igniteui-angular/src/lib/grid/grid.groupby.spec.ts
src/app/grid-groupby/grid-groupby.sample.ts

Adding method for clearing Grouping - clearGrouping.

---

projects/igniteui-angular/src/lib/grid/api.service.ts
projects/igniteui-angular/src/lib/grid/grid.component.html
projects/igniteui-angular/src/lib/grid/grid.component.ts
projects/igniteui-angular/src/lib/grid/grid.groupby.spec.ts
projects/igniteui-angular/src/lib/grid/grid.pipes.ts

Renaming groupByDefaultExpanded prop  to groupsExpanded.

---

projects/igniteui-angular/src/lib/grid/grid-summary.component.ts
projects/igniteui-angular/src/lib/grid/grid-summary.spec.ts
projects/igniteui-angular/src/lib/grid/grid.component.ts

when we have column with summary applied and it is outside of the
viewport and we have indentical width per column summary doesn't reflect
on any changes
Closes #1407

fix(igxGridSummary): column with summary outside of viewport not working

---

projects/igniteui-angular/src/lib/grid/grid-filtering-ui.spec.ts
projects/igniteui-angular/src/lib/grid/grid-filtering.component.ts
projects/igniteui-angular/src/lib/grid/grid-filtering.spec.ts
projects/igniteui-angular/src/lib/grid/grid.component.ts

emit filtering done whenever filtering is reset or input was cleared
Closes #1434

fix(igxGrid, igxGridFiltering): emit filteringDone when clear the filtering

---

projects/igniteui-angular/src/lib/calendar/calendar.component.html
projects/igniteui-angular/src/lib/calendar/calendar.component.ts

slide right animation is broken when you select date from the next month
Closes #1414

fix(igxCalendar): slide animaiton is broken

---

projects/igniteui-angular/src/lib/tabs/tabs-group.component.ts

refactor(tabs): fixed misleading css style property

---

.travis.yml
gulpfile.js
package-lock.json
package.json
projects/igniteui-angular/migrations/common/UpdateChanges.spec.ts
projects/igniteui-angular/migrations/common/UpdateChanges.ts
projects/igniteui-angular/migrations/common/filterSourceDirs.ts
projects/igniteui-angular/migrations/common/schema/class.schema.json
projects/igniteui-angular/migrations/common/schema/index.ts
projects/igniteui-angular/migrations/common/schema/output.schema.json
projects/igniteui-angular/migrations/common/schema/selector.schema.json
projects/igniteui-angular/migrations/common/tsUtils.ts
projects/igniteui-angular/migrations/migration-collection.json
projects/igniteui-angular/migrations/tsconfig.json
projects/igniteui-angular/migrations/update-6/changes/selectors.json
projects/igniteui-angular/migrations/update-6/index.spec.ts
projects/igniteui-angular/migrations/update-6/index.ts
projects/igniteui-angular/migrations/update-6_01/changes/selectors.json
projects/igniteui-angular/migrations/update-6_01/index.spec.ts
projects/igniteui-angular/migrations/update-6_01/index.ts
projects/igniteui-angular/migrations/update-6_1/changes/outputs.json
projects/igniteui-angular/migrations/update-6_1/index.spec.ts
projects/igniteui-angular/migrations/update-6_1/index.ts
projects/igniteui-angular/package.json

Closes # .  
Changes from #1463 plus new schematic for current 6.1.x changes

Add ng-update migration schematics

---

projects/igniteui-angular/src/lib/grid/grid.component.ts

fix(grid): use documentElement.clientHeight to get viewport height #1449

---

projects/igniteui-angular/src/lib/grid/grid.component.ts

Use documentElement.clientHeight to get viewport height

---

projects/igniteui-angular/src/lib/grid/grid-filtering.component.ts

input is not visible when try to change from unnary to normal condition
and column is outside of the viewport
Closes #1431

fix(igxGridFiltering): input is not visible when navigate through cond

---

projects/igniteui-angular/src/lib/combo/combo.component.ts

docs(igx-combo): Added documentation and code snippets

---

projects/igniteui-angular/src/lib/grid/api.service.ts
projects/igniteui-angular/src/lib/grid/grid.component.ts
projects/igniteui-angular/src/lib/grid/grid.groupby.spec.ts

Clear expand state when removing or reordering groups

---

projects/igniteui-angular/src/lib/avatar/avatar.component.ts
projects/igniteui-angular/src/lib/carousel/carousel.component.ts

Enhance the IgxAvatarComponent documentation

---

projects/igniteui-angular/src/lib/grid/grid-filtering-ui.spec.ts
projects/igniteui-angular/src/lib/grid/grid-filtering.component.ts

fix(igxGridFiltering): when search with 0 filtering icon should change

---

projects/igniteui-angular/src/lib/date-picker/date-picker.component.html
projects/igniteui-angular/src/lib/date-picker/date-picker.component.spec.ts
projects/igniteui-angular/src/lib/date-picker/date-picker.component.ts

test(igxDatePicker): labelVisibility and label modification

---

projects/igniteui-angular/src/lib/tabbar/tabbar.component.ts

Documenting the IgxBottomNav, IgxTabPanel, IgxTab components.

---

projects/igniteui-angular/src/lib/grid/grid.component.ts
projects/igniteui-angular/src/lib/grid/grid.search.spec.ts

Fix unsearchable column removing the active highlight for other columns on its right

---

projects/igniteui-angular/src/lib/grid/grid.component.ts
projects/igniteui-angular/src/lib/grid/grid.groupby.spec.ts

feat(igxGroupBy): Throw error when grouping by more than 10 columns #856

---

projects/igniteui-angular/src/lib/grid/grid-filtering.component.html
projects/igniteui-angular/src/lib/grid/grid-filtering.component.ts

Automatically focus the filtering input

---

projects/igniteui-angular/src/lib/grid/grid.component.html
projects/igniteui-angular/src/lib/grid/grid.groupby.spec.ts

Groupby chips should display the associated column header text.

---

projects/igniteui-angular/src/lib/calendar/calendar.component.ts

Adding documentation to IgxCalendar component.

---

package-lock.json
package.json
projects/igniteui-angular/migrations/common/filterSourceDirs.ts
projects/igniteui-angular/migrations/common/util.ts
projects/igniteui-angular/migrations/migration-collection.json
projects/igniteui-angular/migrations/update-6_02/index.spec.ts
projects/igniteui-angular/migrations/update-6_02/index.ts

#1582 Add theme import migration

---

projects/igniteui-angular/src/lib/card/card.component.ts
projects/igniteui-angular/src/lib/directives/mask/mask.directive.ts

Adding documentation to IgxMaskDirective

---

projects/igniteui-angular/src/lib/chips/chip.component.ts
projects/igniteui-angular/src/lib/chips/chips-area.component.ts
projects/igniteui-angular/src/lib/grid/grid.component.ts

Fix chip keyboard navigation not working on Edge and IE

---

projects/igniteui-angular/src/lib/grid/README.md

chore(igxGrid): Updating grid's README with new groupby APIs.

---

projects/igniteui-angular/src/lib/directives/text-highlight/text-highlight.directive.spec.ts
projects/igniteui-angular/src/lib/directives/text-highlight/text-highlight.directive.ts

Fix IE compatibility of IgxTextHighlight directive

---

projects/igniteui-angular/src/lib/grid/grid-toolbar.component.ts
projects/igniteui-angular/src/lib/grid/grid-toolbar.spec.ts
projects/igniteui-angular/src/lib/grid/grid.component.ts

OnToolbarExporting event enchancements

---

projects/igniteui-angular/src/lib/core/styles/components/grid/_grid-theme.scss
projects/igniteui-angular/src/lib/directives/for-of/for_of.directive.ts

 refactor(igxForOf): Improve scrolling on mac

---

CHANGELOG.md
package-lock.json
package.json
projects/igniteui-angular/migrations/common/UpdateChanges.spec.ts
projects/igniteui-angular/migrations/common/UpdateChanges.ts
projects/igniteui-angular/migrations/common/filterSourceDirs.ts
projects/igniteui-angular/migrations/common/util.ts
projects/igniteui-angular/migrations/migration-collection.json
projects/igniteui-angular/migrations/update-6/index.ts
projects/igniteui-angular/migrations/update-6_01/index.ts
projects/igniteui-angular/migrations/update-6_02/index.spec.ts
projects/igniteui-angular/migrations/update-6_02/index.ts
projects/igniteui-angular/migrations/update-6_1/index.spec.ts
projects/igniteui-angular/migrations/update-6_1/index.ts

Closes #1582.  
Applying changes from https://github.com/IgniteUI/igniteui-angular/pull/1601, https://github.com/IgniteUI/igniteui-angular/pull/1609

#1582 Add theme import migration to master, filter refactor, changelog 

---

projects/igniteui-angular/src/lib/calendar/calendar.component.ts
projects/igniteui-angular/src/lib/carousel/carousel.component.ts
projects/igniteui-angular/src/lib/tabbar/tabbar.component.ts

Editing documented @Output code snippets.

---

projects/igniteui-angular/src/lib/directives/dragdrop/dragdrop.directive.ts
projects/igniteui-angular/src/lib/grid/grid.component.ts

Fix performance issue in the igxDrag directive in IE related to changes in groupby.

---

projects/igniteui-angular/src/lib/toast/toast.component.ts

Adding documentation to the IgxToast component.

---

projects/igniteui-angular/src/lib/directives/for-of/IForOfState.ts
projects/igniteui-angular/src/lib/directives/for-of/for_of.directive.spec.ts
projects/igniteui-angular/src/lib/directives/for-of/for_of.directive.ts
projects/igniteui-angular/src/lib/grid/grid.component.ts
projects/igniteui-angular/src/lib/grid/grid.initialization.spec.ts
projects/igniteui-angular/src/public_api.ts

Closes #1597 
Adding IForOfState to the public_api.ts

Adding IForOfState to the public_api.ts

---

projects/igniteui-angular/src/lib/directives/button/button.directive.ts

Document the IgxButton directive

---

projects/igniteui-angular/src/lib/grid/grid.component.ts
projects/igniteui-angular/src/lib/grid/grid.pagination.spec.ts

Setting paging should update the grid

---

projects/igniteui-angular/src/lib/calendar/calendar.component.ts

Reverse scrolling of the years

---

projects/igniteui-angular/src/lib/core/styles/components/grid/_grid-theme.scss
projects/igniteui-angular/src/lib/grid/grid.pinning.spec.ts

fix(grid): resolving styling regression in headers #1668

---

projects/igniteui-angular/src/lib/core/styles/components/time-picker/_time-picker-theme.scss

docs(time-picker): Rename two param

---

projects/igniteui-angular/src/lib/chips/chips-area.component.spec.ts

Automation for data binding in chip-area.

---

CHANGELOG.md
projects/igniteui-angular/src/lib/directives/radio/radio-group.directive.spec.ts
projects/igniteui-angular/src/lib/directives/radio/radio-group.directive.ts
projects/igniteui-angular/src/lib/radio/radio.component.ts
projects/igniteui-angular/src/public_api.ts
src/app/app.component.ts
src/app/app.module.ts
src/app/radio/radio.sample.css
src/app/radio/radio.sample.html
src/app/radio/radio.sample.ts
src/app/routing.ts

Related to #1610, #1479, #1166.
Introduce new directive: IgxRadioGroupDirective. It allows better control over its child `IgxRadioComponent` and supports template-driven and reactive forms.

New directive: IgxRadioGroupDirective

---

projects/igniteui-angular/src/lib/core/styles/components/grid/_grid-theme.scss
projects/igniteui-angular/src/lib/grid/grid-filtering.component.html
projects/igniteui-angular/src/lib/grid/grid-filtering.component.ts

Fix filtering dialog to work with overlay

---

projects/igniteui-angular/src/lib/grid/grid.groupby.spec.ts

Fix failing tests for groupby.

---

projects/igniteui-angular/src/lib/combo/combo.component.html
projects/igniteui-angular/src/lib/combo/combo.component.spec.ts
projects/igniteui-angular/src/lib/core/styles/components/combo/_combo-component.scss
projects/igniteui-angular/src/lib/core/styles/components/combo/_combo-theme.scss
src/app/combo/combo.sample.css

Add combo checkbox class

---

projects/igniteui-angular/src/lib/grid/grid.common.ts

Revert the fix as it breaks resizing.

Revert fix for #1723

---

CHANGELOG.md

docs(chips): adding chips to changelog

---

CHANGELOG.md

Closes #749.  
Adding the toolbar and its features to the CHANGELOG.md file.

docs(toolbar): adding the toolbar and its features to the changelog.md

---

CHANGELOG.md

Add description in CHANGELOG.md for IgxDropdown

Add description in CHANGELOG.md for IgxDropdown

---

projects/igniteui-angular/src/lib/services/overlay/overlay.spec.ts
projects/igniteui-angular/src/lib/services/overlay/overlay.ts
projects/igniteui-angular/src/lib/services/overlay/utilities.ts

Closes #1729
If the size of the element is 0/0 we should not set the width and height of the content element

Add check for size before set it to content element, 1729

---

projects/igniteui-angular/src/lib/directives/toggle/toggle.directive.spec.ts
projects/igniteui-angular/src/lib/directives/toggle/toggle.directive.ts

Closes #1733 
Add subscription to the IgxOverlayService closing emit in the IgxToggleDirective

IgxToggle OnClosing emitter when closed from outside click

---

package-lock.json
package.json

chore(*): Update rxjs and devkit versions

---

projects/igniteui-angular/src/lib/services/overlay/overlay.ts
projects/igniteui-angular/src/lib/services/overlay/utilities.ts

Fix hide method of overlay.ts to not create additional overlay div.

Remove remaining overlay divs

---

projects/igniteui-angular/src/lib/grid/grid-filtering.component.html
projects/igniteui-angular/src/lib/grid/grid-filtering.component.ts

#1658 .  
Forbid drag on filter icon and fix issue with opened dialog and horizontal scrolling.

Forbid drag on filter icon

---

projects/igniteui-angular/src/lib/grid/column-chooser-base.ts
projects/igniteui-angular/src/lib/grid/column-hiding.component.html
projects/igniteui-angular/src/lib/grid/column-hiding.spec.ts
projects/igniteui-angular/src/lib/grid/column-pinning.component.html
projects/igniteui-angular/src/lib/grid/column-pinning.spec.ts
projects/igniteui-angular/src/lib/grid/grid-toolbar.spec.ts
projects/igniteui-angular/src/lib/grid/grid.component.spec.ts
projects/igniteui-angular/src/lib/grid/grid.component.ts

Closes #878  .  
#878 Prevent hiding/pinning UIs from showing column groups.

#878 Prevent column hiding/pinning UIs from showing column groups.

---

package-lock.json
package.json

Added web-animations-js to package.json

---

projects/igniteui-angular/src/lib/grid/README.md

Add 'all' operand to README

---

projects/igniteui-angular/src/lib/chips/chips-area.component.ts

docs(IgxChipsArea): add API docs for IgxChipsAreaComponent

---

src/app/grid-cellEditing/grid-cellEditing.component.html
src/app/grid-cellEditing/grid-cellEditing.component.ts

fix(samples): Updating editing sample #1704

---

projects/igniteui-angular/src/lib/services/overlay/overlay.ts

Overlay animation adjustments - allow null animation, modal sync

---

projects/igniteui-angular/src/lib/core/styles/components/dialog/_dialog-theme.scss

fix(dialog): fix date picker size jumping when switching views

---

projects/igniteui-angular/src/lib/grid/cell.component.ts

Error on edit mode

---

projects/igniteui-angular/src/lib/grid/column-chooser-base.ts
projects/igniteui-angular/src/lib/grid/column-hiding.component.ts
projects/igniteui-angular/src/lib/grid/column-hiding.spec.ts

Closes #1830 .  
Modified filtering/searching logic in column hiding UI so it accounts for the group columns and keep parents in view when there is a match in the children.

#1830 Fixed the issues with searching group columns.

---

projects/igniteui-angular/src/lib/core/styles/components/overlay/_overlay-theme.scss
projects/igniteui-angular/src/lib/services/overlay/overlay.spec.ts

fix(igxOverlay): fix modal overlay position in IE - dialog, pickers

---

projects/igniteui-angular/src/lib/services/overlay/overlay.spec.ts
projects/igniteui-angular/src/lib/services/overlay/overlay.ts

Closes #1799 
Add resize handler on window and call overlay.repositionAll method inside.

Overlay elements do not reposition on resize, 1799

---

projects/igniteui-angular/src/lib/core/styles/components/chip/_chip-theme.scss
projects/igniteui-angular/src/lib/core/styles/components/drop-down/_drop-down-theme.scss
src/app/chips/chips.sample.html

Chip theme change

---

projects/igniteui-angular/src/lib/chips/chip.component.html
projects/igniteui-angular/src/lib/chips/chip.component.ts
projects/igniteui-angular/src/lib/directives/dragdrop/dragdrop.directive.ts
projects/igniteui-angular/src/lib/grid/grid.common.ts

Fix drag and drop not interactive on iOS.

---

projects/igniteui-angular/src/lib/combo/combo.component.spec.ts
projects/igniteui-angular/src/lib/combo/combo.component.ts

fix(igx-combo): emit onSearchInput event when search text is empty #1818

---

src/app/grid-performance/grid-performance.sample.ts

Changed grid-performance sample's width of columns and data.

---

projects/igniteui-angular/src/lib/core/styles/components/checkbox/_checkbox-theme.scss
projects/igniteui-angular/src/lib/core/styles/components/radio/_radio-theme.scss
projects/igniteui-angular/src/lib/core/styles/components/switch/_switch-theme.scss

refactor(radio, checkbox, switch): add relative position

---

CHANGELOG.md
projects/igniteui-angular/src/lib/combo/README.md

Fix typos in CHANGELOG and Readme

---

CHANGELOG.md

docs(*): Add column groups to CHANGELOG

---

CHANGELOG.md

Added some info in breaking changes section for igxToggle and igxDialog related to changed parameters open, close and toggle methods accept now.

Update CHANGELOG.md with changes related to fireEvents

---

CHANGELOG.md

Adding information regarding the igxList's igxDataLoading directive in the changelog.
Closes #1680

docs(igxList): info regarding the igxList's igxDataLoading directive

---

projects/igniteui-angular/src/lib/directives/dragdrop/dragdrop.directive.ts

fix(grid): pageXoffset instead of scrollX for IE9 compatibility #1778

---

.github/CONTRIBUTING.md
package-lock.json
projects/igniteui-angular/package.json

fix(package.json): Adding back @types and hammerjs as dependencies #1683

---

projects/igniteui-angular/src/lib/core/styles/components/combo/_combo-theme.scss
projects/igniteui-angular/src/lib/core/styles/themes/presets/igniteui-angular.scss

style(combo): Remove unused colors

---

projects/igniteui-angular/src/lib/grid/grid.component.ts
projects/igniteui-angular/src/lib/grid/grid.search.spec.ts

Fix filtering interactions with the search

---

projects/igniteui-angular/src/lib/services/overlay/overlay.ts

fix(overlay): Don't complete the observer until Escape keydown event

---

projects/igniteui-angular/src/lib/directives/text-highlight/text-highlight.directive.spec.ts
projects/igniteui-angular/src/lib/directives/text-highlight/text-highlight.directive.ts
projects/igniteui-angular/src/lib/grid/cell.component.html

Add a container div to the IgxTextHighlightDirective

---

projects/igniteui-angular/src/lib/core/styles/components/grid/_grid-theme.scss

fix(grid): column group header cut off on drag

---

projects/igniteui-angular/ng-package.json
projects/igniteui-angular/ng-package.prod.json
projects/igniteui-angular/package.json

build(*): Move the whitelist configuration in the `ng-package` files

---

projects/igniteui-angular/src/lib/grid/grid.component.ts
projects/igniteui-angular/src/lib/grid/grid.pagination.spec.ts

fix(paging): adding a check for paginator on contentinit #1867

---

projects/igniteui-angular/src/lib/directives/for-of/for_of.directive.ts

Closes https://github.com/IgniteUI/igniteui-angular-samples/issues/484

fix(igxFor): mouseWheel on non-scrollable grid causes content to not be visible in the view.

---

projects/igniteui-angular/src/lib/grid/api.service.ts
projects/igniteui-angular/src/lib/grid/cell.component.ts
projects/igniteui-angular/src/lib/grid/grid.component.ts
projects/igniteui-angular/src/lib/grid/grid.crud.spec.ts
projects/igniteui-angular/src/lib/grid/row.component.ts

Fix issue Error when delete row which contains cell in edit mode

---

projects/igniteui-angular/src/lib/directives/text-highlight/text-highlight.directive.spec.ts
projects/igniteui-angular/src/lib/directives/text-highlight/text-highlight.directive.ts

Validate IgxTextHighlightDirective's value

---

projects/igniteui-angular/src/lib/combo/combo.component.spec.ts
projects/igniteui-angular/src/lib/core/styles/base/utilities/_mixins.scss

Closes  #1894 (#1917 - duplicate)

 fix(themes): update hide-default mixin in attempt to fix #1917

---

projects/igniteui-angular/src/lib/combo/combo.component.spec.ts
projects/igniteui-angular/src/lib/combo/combo.component.ts

Closes #1899.
checkMatch() is now called on input instead of on set filteredData (which will never be called if filterable = false)
If filtering is off, combo will use data instead of filtered data where needed.

Combo handles AddItem visibility on input

---

projects/igniteui-angular/src/lib/grid/column.component.ts
projects/igniteui-angular/src/lib/grid/grid.component.ts
projects/igniteui-angular/src/lib/grid/grid.search.spec.ts

Fix column moving interaction with the search

---

projects/igniteui-angular/src/lib/combo/combo.component.spec.ts
projects/igniteui-angular/src/lib/combo/combo.component.ts

Scroll combo drop down on search

---

projects/igniteui-angular/src/lib/directives/ripple/ripple.directive.ts

fix(ripple): Changing duration does not affect animation

---

projects/igniteui-angular/src/lib/combo/combo-dropdown.component.ts
projects/igniteui-angular/src/lib/combo/combo.component.spec.ts
projects/igniteui-angular/src/lib/combo/combo.component.ts
projects/igniteui-angular/src/lib/services/overlay/position/connected-positioning-strategy.ts
projects/igniteui-angular/src/lib/services/overlay/position/global-position-strategy.ts

Closes #1927
Set virtual scroll position before the positioning method is fired:
- Expose "updateScrollPosition" in IgxComboDropDownComponent
- Implement custom position strategy for IgxCombo positioning (extends ConnectedPositionStrategy)
- Update call signatures of PositionStrategies to ALL implement document / first call as optional

Combo - Fix virtual scroll flickering on opening

---

projects/igniteui-angular/src/lib/core/styles/components/grid/_grid-theme.scss

style(grouparea): fix height problem

---

projects/igniteui-angular/src/lib/directives/toggle/toggle.directive.ts
projects/igniteui-angular/src/lib/services/overlay/overlay.ts

Closes #1921, fixes IgniteUI/igniteui-angular-samples#488
Would've fixed #1793 but that one is no longer reproducible.

#1921 duplicate handler remove

---

projects/igniteui-angular/src/lib/core/styles/components/grid/_grid-theme.scss
src/styles/igniteui-theme.scss

fix(themes): themes not building with legacy support off

---

projects/igniteui-angular/src/lib/combo/README.md

Combo readme

---

projects/igniteui-angular/src/lib/checkbox/checkbox.component.html
projects/igniteui-angular/src/lib/radio/radio.component.html
projects/igniteui-angular/src/lib/switch/switch.component.html

Update ripple animation duration for the checkbox, radio, and checkbox
controls.
Closes #1905

refactor(selection-controls): update ripple animation duration

---

projects/igniteui-angular/src/lib/combo/combo.component.ts

Closes #1938
Moved checkMatch() to depend on combo filtering enabled/disabled

Combo - Add Item Button show/hide

---

projects/igniteui-angular/src/lib/list/index.ts
projects/igniteui-angular/src/public_api.ts
src/app/drop-down/drop-down.sample.ts

fix(igx-list): Creating an index export file for the list #1939

---

projects/igniteui-angular/src/lib/core/styles/components/drop-down/_drop-down-component.scss
projects/igniteui-angular/src/lib/core/styles/components/drop-down/_drop-down-theme.scss

style(drop-down): add styles for selected and focused item

---

src/grid/cell.component.ts
src/grid/grid.component.html
src/grid/grid.component.ts

fix(igxGrid): fix #1759: Fix for scenarios where focus moves outside the visible cells. Merge to version 5.3.x

---

projects/igniteui-angular/src/lib/grid/cell.component.ts
projects/igniteui-angular/src/lib/grid/grid.component.html
projects/igniteui-angular/src/lib/grid/grid.component.ts

fix(igxGrid): fix #1759: Fix for scenarios where focus moves outside the visible cells. Merge to version 6.0.x

---

projects/igniteui-angular/src/lib/core/styles/components/grid/_grid-theme.scss

fix(themes): grid theme throws error if no content-background

---

.travis.yml

build(npm): update npm deploy token #2002

---

projects/igniteui-angular/src/lib/core/styles/base/_normalize.scss
projects/igniteui-angular/src/lib/core/styles/themes/_core.scss

Only define the normalization styles if igx-core is called. Also don't inherit color for buttons, inputs, optgroup, select, and textarea.

refactor(themes): make normalize a mixin and call it in igx-core

---

CHANGELOG.md
projects/igniteui-angular/src/lib/grid/grid-summary.component.ts
projects/igniteui-angular/src/lib/grid/grid.component.spec.ts
projects/igniteui-angular/src/lib/grid/grid.component.ts
src/app/grid-cellEditing/grid-cellEditing.component.html

Grid Display Density

---

projects/igniteui-angular/src/lib/grid/column-hiding.component.ts

Documenting the ColumnHidingComponent. 

---

projects/igniteui-angular/src/lib/chips/chip.component.ts
projects/igniteui-angular/src/lib/grid/grid.groupby.spec.ts

Fix exception is thrown when hovering a chip with a column header.

---

projects/igniteui-angular/src/lib/chips/chip.component.html
projects/igniteui-angular/src/lib/chips/chip.component.ts
projects/igniteui-angular/src/lib/chips/chip.spec.ts
projects/igniteui-angular/src/lib/core/styles/components/chip/_chip-component.scss
projects/igniteui-angular/src/lib/core/styles/components/chip/_chip-theme.scss
projects/igniteui-angular/src/lib/directives/dragdrop/dragdrop.directive.ts

Fix for chip density not affecting the chip drag ghost.

---

projects/igniteui-angular/src/lib/directives/dragdrop/dragdrop.directive.ts

docs(dragdrop): Add API docs for IgxDragDirective/IgxDropDirective

---

CHANGELOG.md

Add combo remote data fixes to changelog

---

projects/igniteui-angular/src/lib/slider/slider.component.spec.ts
projects/igniteui-angular/src/lib/slider/slider.component.ts

fix(igxSlider): update minValue properly

---

projects/igniteui-angular/src/lib/date-picker/date-picker.component.spec.ts
projects/igniteui-angular/src/lib/dialog/dialog.component.spec.ts
projects/igniteui-angular/src/lib/grid/column-hiding.spec.ts
projects/igniteui-angular/src/lib/grid/grid-filtering-ui.spec.ts
projects/igniteui-angular/src/lib/services/overlay/overlay.spec.ts
projects/igniteui-angular/src/lib/test-utils/helper-utils.spec.ts
projects/igniteui-angular/src/lib/time-picker/time-picker.component.spec.ts

Clear overlays after test execution

---

CHANGELOG.md
projects/igniteui-angular/ng-package.json
projects/igniteui-angular/package.json

Move jszip from the peerdependencies list
Add it to dependencies and whitelist lists
Closes #2043  

Move jszip from the peerdependencies list

---

projects/igniteui-angular/src/lib/grid/column-hiding.spec.ts

Closes #2053 .
Most of the column hiding tests did not need to be asynk or even fakeAsync, so they were changed to be fully synchronous.

Made Column Hiding tests synchronous.

---

projects/igniteui-angular/src/lib/grid/grid-summary.ts

Adding documentation to IgxSummaryOperand/IgxNumberSummaryOperand/IgxDateSummaryOperand.
Closes #2049 .

 Documenting the IgxSummaryOperand. 

---

projects/igniteui-angular/src/lib/grid/grid-toolbar.component.ts

docs(grid-toolbar): Add API docs for IgxGridToolbarComponent

---

projects/igniteui-angular/src/lib/grid/grid.common.ts

docs(grid-common): hide grid.common.ts from API docs

---

projects/igniteui-angular/src/lib/directives/ripple/ripple.directive.ts

Adding documentation to the IgxRippleDirective.

---

projects/igniteui-angular/src/lib/directives/focus/focus.directive.ts
projects/igniteui-angular/src/lib/directives/hint/hint.directive.ts

Adding documentation to IgxHint and IgxFocus directives.

---

projects/igniteui-angular/src/lib/core/utils.ts
projects/igniteui-angular/src/lib/directives/input/input.directive.ts
projects/igniteui-angular/src/lib/grid/api.service.ts

Closes #2065 .  
Documenting the IgxInputDirective.
Hiding the IgxGridAPIService.
Hiding the DisplayDensity, KEYCODES enums and cloneObject(), cloneArray() functions stored in core/utils.ts .

Adding documentation to the IgxInputDirective.

---

projects/igniteui-angular/src/lib/grid/grid.component.html
projects/igniteui-angular/src/lib/grid/grid.component.spec.ts
projects/igniteui-angular/src/lib/grid/grid.component.ts

Add empty grid template

---

projects/igniteui-angular/src/lib/directives/button/button.directive.ts
projects/igniteui-angular/src/lib/directives/focus/focus.directive.ts
projects/igniteui-angular/src/lib/directives/hint/hint.directive.ts
projects/igniteui-angular/src/lib/directives/input/input.directive.ts
projects/igniteui-angular/src/lib/directives/mask/mask.directive.ts
projects/igniteui-angular/src/lib/grid/api.service.ts
projects/igniteui-angular/src/lib/grid/column-chooser-base.ts
projects/igniteui-angular/src/lib/grid/column.component.ts
projects/igniteui-angular/src/lib/grid/grid-summary.ts
projects/igniteui-angular/src/lib/radio/radio.component.ts
projects/igniteui-angular/src/lib/tabbar/tabbar.component.ts

Fixing indentation.

---

projects/igniteui-angular/src/lib/grid/grid.component.ts
projects/igniteui-angular/src/lib/grid/grid.crud.spec.ts
projects/igniteui-angular/src/lib/grid/row.component.ts

Navigate to prev page, when last row of page is deleted

---

projects/igniteui-angular/src/lib/grid/grid.component.html
projects/igniteui-angular/src/lib/grid/grid.component.ts
projects/igniteui-angular/src/lib/grid/grid.groupby.spec.ts

GroupBy drop area can't have its text changed or templated.

---

package.json
tsconfig.json

docs(all): excluce private/protected members from exporting #2120

---

package.json
tsconfig.json

docs(all): exclude private/protected members from exporting #2120

---

.travis.yml

build(npm): update npm deploy token

---

projects/igniteui-angular/src/lib/date-picker/date-picker.component.ts
projects/igniteui-angular/src/lib/services/overlay/overlay.ts
projects/igniteui-angular/src/lib/time-picker/time-picker.component.ts

Add Hostlisteners for IE

---

projects/igniteui-angular/src/lib/tabs/tab-item.component.ts
projects/igniteui-angular/src/lib/tabs/tabs.component.ts

docs(tabs): Add API docs for IgxTabItemComponent and IgxTabsComponent

---

CHANGELOG.md
projects/igniteui-angular/src/lib/combo/combo.component.spec.ts
projects/igniteui-angular/src/lib/combo/combo.component.ts
src/app/combo/combo.sample.html

Combo default width

---

projects/igniteui-angular/src/lib/time-picker/time-picker.component.spec.ts

Fix IgxTimePicker tests

---

CHANGELOG.md
projects/igniteui-angular/src/lib/combo/README.md
projects/igniteui-angular/src/lib/combo/combo.component.html
projects/igniteui-angular/src/lib/combo/combo.component.spec.ts
projects/igniteui-angular/src/lib/combo/combo.component.ts

Change itemsWidth property

---

CHANGELOG.md
projects/igniteui-angular/src/lib/combo/README.md
projects/igniteui-angular/src/lib/combo/combo.component.html
projects/igniteui-angular/src/lib/combo/combo.component.spec.ts
projects/igniteui-angular/src/lib/combo/combo.component.ts

Combo itemsWidth

---

projects/igniteui-angular/src/lib/combo/combo-dropdown.component.ts
projects/igniteui-angular/src/lib/combo/combo.component.spec.ts
projects/igniteui-angular/src/lib/combo/combo.component.ts

Combo runtime change for filterable

---

projects/igniteui-angular/src/lib/combo/combo-dropdown.component.ts
projects/igniteui-angular/src/lib/combo/combo-item.component.ts
projects/igniteui-angular/src/lib/combo/combo.component.ts
projects/igniteui-angular/src/lib/combo/combo.pipes.ts
projects/igniteui-angular/src/lib/drop-down/drop-down-item.component.ts
projects/igniteui-angular/src/lib/drop-down/drop-down.component.ts
projects/igniteui-angular/src/lib/navigation-drawer/navigation-drawer.component.ts
projects/igniteui-angular/src/lib/navigation-drawer/navigation-drawer.directives.ts
projects/igniteui-angular/src/lib/services/index.ts
projects/igniteui-angular/src/lib/services/overlay/overlay.ts
projects/igniteui-angular/src/lib/services/overlay/utilities.ts

fix(docs): Fixing documentation issues #2100

---

projects/igniteui-angular/src/lib/directives/text-highlight/text-highlight.directive.ts
projects/igniteui-angular/src/lib/grid/grid.search.spec.ts

Fix searching when there is a cell in edit mode

---

projects/igniteui-angular/src/lib/combo/README.md

fix(combo): Fixing wrong outputs in documentation #2164

---

projects/igniteui-angular/src/lib/combo/combo.component.html
projects/igniteui-angular/src/lib/combo/combo.component.spec.ts

Combo - Clear - Clear button is now an icon, added title for accessibility

---

projects/igniteui-angular/src/lib/date-picker/date-picker.component.spec.ts
projects/igniteui-angular/src/lib/dialog/dialog.component.spec.ts
projects/igniteui-angular/src/lib/grid/column-hiding.spec.ts
projects/igniteui-angular/src/lib/grid/column-pinning.spec.ts
projects/igniteui-angular/src/lib/grid/grid-filtering-ui.spec.ts
projects/igniteui-angular/src/lib/grid/grid-toolbar.spec.ts
projects/igniteui-angular/src/lib/services/overlay/overlay.spec.ts
projects/igniteui-angular/src/lib/test-utils/grid-functions.spec.ts
projects/igniteui-angular/src/lib/test-utils/helper-utils.spec.ts
projects/igniteui-angular/src/lib/test-utils/ui-interactions.spec.ts
projects/igniteui-angular/src/lib/time-picker/time-picker.component.spec.ts

test(helperUtils): return helperUtils class with common funcs

---

projects/igniteui-angular/src/lib/directives/input/input.directive.spec.ts
projects/igniteui-angular/src/lib/directives/mask/mask.directive.spec.ts
projects/igniteui-angular/src/lib/grid/grid-filtering-ui.spec.ts
projects/igniteui-angular/src/lib/radio/radio.component.spec.ts

Improve tests with fakeAsync

---

projects/igniteui-angular/src/lib/grid/grid.pinning.spec.ts

Refactor pinning test that uses setTimeout.

---

projects/igniteui-angular/src/lib/combo/README.md

fix(combo): Fix wrong outputs in the docs #2164

---

CHANGELOG.md
projects/igniteui-angular/src/lib/data-operations/filtering-condition.ts
projects/igniteui-angular/src/lib/grid/grid-filtering-expression.component.ts
projects/igniteui-angular/src/lib/grid/grid-filtering-ui.spec.ts
projects/igniteui-angular/src/lib/grid/grid-filtering.component.ts
projects/igniteui-angular/src/lib/grid/grid-filtering.spec.ts

Add 'isUnary' property to IFilteringOperation

---

CHANGELOG.md
projects/igniteui-angular/src/lib/dialog/dialog.component.spec.ts
projects/igniteui-angular/src/lib/grid/grid-toolbar.spec.ts

chore(*): Merging master into 6.1.x

---

projects/igniteui-angular/src/lib/carousel/carousel.component.spec.ts
projects/igniteui-angular/src/lib/test-utils/ui-interactions.spec.ts

Update carousel tests to use UIInteractions

---

projects/igniteui-angular/src/lib/grid/cell.component.ts
projects/igniteui-angular/src/lib/grid/grid-header.component.ts
projects/igniteui-angular/src/lib/grid/grid.pinning.spec.ts
projects/igniteui-angular/tsconfig.lib.json

Correctly apply the appropriate CSS classes on cell/header components
Closes #2121

fix(igxGrid): Cell and header style classes

---

projects/igniteui-angular/src/lib/grid/grid.pagination.spec.ts

Update paging tests to use templates from test-utils 

---

projects/igniteui-angular/src/lib/data-operations/filtering-condition.ts

Change 'doesNotEqual' logic

---

CHANGELOG.md
projects/igniteui-angular/src/lib/drop-down/README.md
projects/igniteui-angular/src/lib/drop-down/drop-down.component.ts

Add isSelected setter to igxDropDownItemBase, #2061

---

projects/igniteui-angular/src/lib/grid/grid.sorting.spec.ts

test(grid): changes to the sorting tests describe suit #2230

---

projects/igniteui-angular/src/lib/grid/grid.component.ts

Add a null check for the _moveColumns method

---

src/app/grid-selection/grid-selection.sample.css
src/app/grid-selection/grid-selection.sample.html
src/app/grid-selection/grid-selection.sample.ts
src/app/shared/remote.service.ts

Grid Selection demo - change the remote data URL and trigger change detection

---

projects/igniteui-angular/src/lib/combo/combo.component.spec.ts
projects/igniteui-angular/src/lib/drop-down/drop-down.component.ts

Combo - Add Item - Do not fire on Keydown.Space

---

projects/igniteui-angular/src/lib/combo/README.md

Remove Space key from Keyboard Navigation section in combo README

---

projects/igniteui-angular/src/lib/grid/grid.sorting.spec.ts

test(grid): changes to the sorting tests describe suit

---

projects/igniteui-angular/src/lib/grid/grid-summary.spec.ts
projects/igniteui-angular/src/lib/test-utils/ui-interactions.spec.ts

Grid summaries test enhancements

---

projects/igniteui-angular/src/lib/grid/column-group.spec.ts
projects/igniteui-angular/src/lib/grid/column.spec.ts

Grid column and column group tests refactoring

---

projects/igniteui-angular/src/lib/grid/grid-summary.spec.ts
projects/igniteui-angular/src/lib/test-utils/ui-interactions.spec.ts

Summary Tests enhancements

---

projects/igniteui-angular/src/lib/combo/README.md
projects/igniteui-angular/src/lib/grid/cell.component.ts
projects/igniteui-angular/src/lib/grid/grid-toolbar.component.ts
projects/igniteui-angular/src/lib/grid/grid.component.ts

Closes #2168 .  
Providing the IgxGridCellComponent with documentation.
Adding corrections to the documentation of the IgxGridComponent.
Adding small correction to the documentation of the IgxGridToolbarComponent.
Adding small correction to the README.md.

Adding documentation to IgxGridCellComponent.

---

projects/igniteui-angular/src/lib/data-operations/filtering-expressions-tree.ts
projects/igniteui-angular/src/lib/grid/column-chooser-item-base.ts
projects/igniteui-angular/src/lib/grid/grid-filtering-expression.component.ts
projects/igniteui-angular/src/lib/grid/grid-filtering.component.ts
projects/igniteui-angular/src/lib/grid/grid-header.component.ts
projects/igniteui-angular/src/lib/grid/grid-summary.component.ts
projects/igniteui-angular/src/lib/grid/grid.pipes.ts

Closes #2264 .
Documenting the IgxFilteringExpressionsTree.
Hiding the ItemPropertyValueChanged class.
Hiding the IgxGridFilterExpression component.
Hiding the IgxGridFilter component.
Hiding the IgxGridHeader component.
HIding the IgxGridSummary component.
Hiding all Pipe classes in grid.pipes.ts

Adding documentation to the IgxFilteringExpressionTree

---

CHANGELOG.md
projects/igniteui-angular/src/lib/tabs/tabs-group.component.ts
projects/igniteui-angular/src/lib/tabs/tabs.component.spec.ts
projects/igniteui-angular/src/lib/tabs/tabs.component.ts

Make 'selectedIndex' an Input

---

projects/igniteui-angular/src/lib/grid/groupby-row.component.ts

fix(igxGrid): Fixing keyboard navigation with Grouping.

---

projects/igniteui-angular/src/lib/combo/combo.component.spec.ts
projects/igniteui-angular/src/lib/drop-down/drop-down.component.ts

Combo - Add Item - Do not fire on Keydown.Space - 6.1.x

---

CHANGELOG.md
src/polyfills.ts

Fix for igxGrid not loading in IE.

fix(igxGrid): Adding polyfill for IE for Object.entries.

---

projects/igniteui-angular/src/lib/grid/grid.component.ts
projects/igniteui-angular/src/lib/grid/grid.pagination.spec.ts

Fixed paging to non-existent pages

---

projects/igniteui-angular/src/lib/grid/grid.component.ts

Closes #1185
Adjust scroll amount depending on cell visibility.

Grid - Cell Navigation - Align Top cell to header on KeyUp - 6.1.x

---

projects/igniteui-angular/src/lib/carousel/carousel.component.spec.ts
projects/igniteui-angular/src/lib/carousel/carousel.component.ts

Closes #2182
fixing issue when a slide is shown after it gets removed

fix(carousel): fixing issue when a slide is shown after it gets removed

---

projects/igniteui-angular/src/lib/grid/column-hiding.spec.ts
projects/igniteui-angular/src/lib/grid/column.component.ts
projects/igniteui-angular/src/lib/grid/grid.component.ts
projects/igniteui-angular/src/lib/test-utils/template-strings.spec.ts

Fix column width calculations when there are hidden columns

---

projects/igniteui-angular/src/lib/combo/combo.component.spec.ts

Combo tests refactoring

---

projects/igniteui-angular/src/lib/combo/combo.component.spec.ts
projects/igniteui-angular/src/lib/combo/combo.component.ts

Add getter and setter for combo's data property - 6.1.x

---

projects/igniteui-angular/src/lib/grid/cell.spec.ts

Refactor most of the keyboard navigation tests inside the cell spec to not use setTimeout.

---

ROADMAP.md

Updating the Roadmap with new features

---

projects/igniteui-angular/src/lib/grid/grid-filtering.component.ts

Refactor logic for Boolean filter

---

projects/igniteui-angular/src/lib/progressbar/circularbar.component.spec.ts
projects/igniteui-angular/src/lib/progressbar/common.spec.ts
projects/igniteui-angular/src/lib/progressbar/linearbar.component.spec.ts
projects/igniteui-angular/src/lib/progressbar/progressbar.component.ts

 circular and linear bars - prevent progress exceeding, smooth update when operate with big nums 

---

projects/igniteui-angular/src/lib/progressbar/circularbar.component.spec.ts
projects/igniteui-angular/src/lib/progressbar/common.spec.ts
projects/igniteui-angular/src/lib/progressbar/linearbar.component.spec.ts
projects/igniteui-angular/src/lib/progressbar/progressbar.component.ts

 circular and linear bars - prevent progress exceeding, smooth update when operate with big nums [MASTER]

---

projects/igniteui-angular/src/lib/grid/grid-filtering.spec.ts
projects/igniteui-angular/src/lib/grid/grid.component.ts

Clear summaries later

---

CHANGELOG.md
projects/igniteui-angular/src/lib/progressbar/circularbar.component.spec.ts
projects/igniteui-angular/src/lib/progressbar/progressbar.component.ts
projects/igniteui-angular/src/lib/progressbar/templates/circular-bar.component.html

feat(circularbar): add text to be displayed in the circular bar #2308

---

projects/igniteui-angular/src/lib/list/list-item.component.ts

Closes #2306  
fixing list item's panning speed

fixing list item's panning speed

---

ROADMAP.md

Updating the Roadmap with POC for Hierarchical Grid

---

CHANGELOG.md

update changelog with progressbar step input description

---

projects/igniteui-angular/src/lib/grid/grid.pagination.spec.ts

add new paging tests 6.1.x

---

CHANGELOG.md
projects/igniteui-angular/src/lib/grid/grid.component.spec.ts
projects/igniteui-angular/src/lib/grid/grid.component.ts

Closes #2313 .  
I'll update the grid's spec when I receive thumbs up from a review.

fix(igxGrid): default render target for grids with no height #2313

---

projects/igniteui-angular/src/lib/test-utils/ui-interactions.spec.ts
projects/igniteui-angular/src/lib/time-picker/time-picker.component.spec.ts

Rework some of the flickering tests for IgxTimePickerComponent

---

projects/igniteui-angular/src/lib/slider/slider.component.spec.ts
projects/igniteui-angular/src/lib/test-utils/ui-interactions.spec.ts

slider test enhancements 6.1.x

---

CHANGELOG.md
projects/igniteui-angular/src/lib/buttonGroup/buttonGroup.component.ts
projects/igniteui-angular/src/lib/buttonGroup/buttongroup-content.component.html
projects/igniteui-angular/src/lib/buttonGroup/buttongroup.component.spec.ts
projects/igniteui-angular/src/lib/directives/button/button.directive.ts
src/app/buttonGroup/buttonGroup.sample.html

Add templating functionality to the IgxButtonGroup

---

projects/igniteui-angular/src/lib/directives/dragdrop/dragdrop.directive.spec.ts
projects/igniteui-angular/src/lib/grid/cell.spec.ts
projects/igniteui-angular/src/lib/grid/grid.groupby.spec.ts
projects/igniteui-angular/src/lib/grid/grid.pinning.spec.ts

Remove discardPeriodicTasks() calls inside tests.

---

projects/igniteui-angular/src/lib/grid/cell.spec.ts
projects/igniteui-angular/src/lib/grid/grid.groupby.spec.ts
projects/igniteui-angular/src/lib/test-utils/helper-utils.spec.ts

Refactoring kb navigation tests and reusing code between different specs.

Refactoring kb navigation tests and reusing code between different specs.

---

projects/igniteui-angular/src/lib/combo/combo-dropdown.component.ts
projects/igniteui-angular/src/lib/combo/combo.component.spec.ts

Combo home/end navigation

---

projects/igniteui-angular/src/lib/combo/combo.component.spec.ts

Fixing flickering combo test

---

projects/igniteui-angular/src/lib/core/styles/components/tabs/_tabs-theme.scss

line-height cut-off the letters in some browsers

---

projects/igniteui-angular/src/lib/chips/chips-area.component.ts
projects/igniteui-angular/src/lib/chips/chips-area.spec.ts

Fix rearrange chips is not working correctly.

---

projects/igniteui-angular/src/lib/directives/input/input.directive.ts
projects/igniteui-angular/src/lib/input-group/input-group.directive.spec.ts

Input group disabled

---

projects/igniteui-angular/src/lib/grid/column-chooser-base.ts

fix(ColumnHiding): #2351 Added string values to ColumnDisplayOrder enum values.

---

projects/igniteui-angular/src/lib/chips/chip.component.ts
projects/igniteui-angular/src/lib/chips/chips-area.spec.ts

fix(chip): #2378 Expose an input property to set chip as selected

---

projects/igniteui-angular/src/lib/grid/api.service.ts
projects/igniteui-angular/src/lib/grid/grid.component.ts

Reapply the search upon exiting edit mode

---

projects/igniteui-angular/src/lib/directives/for-of/for_of.directive.spec.ts

Refactor igxForOf tests(6.1.x)

---

projects/igniteui-angular/src/lib/directives/toggle/README.md

IgxToggle - Readme - Fix misaligned API table

---

projects/igniteui-angular/src/lib/directives/for-of/for_of.directive.ts

Fix scrolling using touch on Edge and IE scrolls the page but not the content

---

projects/igniteui-angular/src/lib/directives/for-of/for_of.directive.ts

Fix scrolling using touch on Edge and IE scrolls the page but not the content. 

---

projects/igniteui-angular/src/lib/grid/api.service.ts
projects/igniteui-angular/src/lib/grid/cell.component.ts
projects/igniteui-angular/src/lib/grid/grid.component.ts
projects/igniteui-angular/src/lib/grid/grid.crud.spec.ts
projects/igniteui-angular/src/lib/grid/row.component.ts
src/app/grid-cellEditing/grid-cellEditing.component.html
src/app/grid-cellEditing/grid-cellEditing.component.ts

Update Cell/Row outside the view ---6.1.x

---

ROADMAP.md

Formatting the RoadMap
Closes # .  

Formatting the RoadMap

---

projects/igniteui-angular/src/lib/core/styles/components/grid-summary/_grid-summary-theme.scss

style(summaries): Adding a correct color and explain from where is inherited

---

CHANGELOG.md

Disabled and special dates note

---

projects/igniteui-angular/src/lib/core/styles/components/grid-summary/_grid-summary-theme.scss

style(summary): Adding correct color and explain from where is inherited

---

projects/igniteui-angular/src/lib/grid/cell.component.ts
projects/igniteui-angular/src/lib/grid/cell.spec.ts

Should not throw error when update cell inside column, on which is applied filtering - 6.1

---

projects/igniteui-angular/src/lib/time-picker/time-picker.component.spec.ts
projects/igniteui-angular/src/lib/time-picker/time-picker.component.ts

Make default selected minutes to be 0

---

projects/igniteui-angular/src/lib/data-operations/data-util.ts
projects/igniteui-angular/src/lib/directives/for-of/for_of.directive.ts
projects/igniteui-angular/src/lib/directives/template-outlet/template_outlet.directive.ts
projects/igniteui-angular/src/lib/grid/grid.component.html
projects/igniteui-angular/src/lib/grid/grid.component.ts
projects/igniteui-angular/src/lib/grid/grid.module.ts
projects/igniteui-angular/src/lib/grid/groupby-row.component.html
projects/igniteui-angular/src/lib/grid/groupby-row.component.ts
projects/igniteui-angular/src/lib/grid/row.component.ts
src/app/grid-groupby/grid-groupby.sample.html
src/app/grid-groupby/grid-groupby.sample.ts

Improve performance in scenarios where row template changes on scroll.

---

projects/igniteui-angular/src/lib/directives/scroll-inertia/scroll_inertia.directive.spec.ts
projects/igniteui-angular/src/lib/directives/scroll-inertia/scroll_inertia.directive.ts

Improve code coverage with unit tests for the inertia directive. 

---

projects/igniteui-angular/src/lib/directives/template-outlet/template_outlet.directive.ts

Updating igxTemplateOutlet ngOnChanges with simpler to follow code and adding comments.

---

projects/igniteui-angular/src/lib/chips/chip.component.ts
projects/igniteui-angular/src/lib/chips/chips-area.component.ts
src/app/chips/chips.sample.html

Fix error thrown when using ng serve --prod from chips.

---

projects/igniteui-angular/src/lib/core/styles/components/chip/_chip-theme.scss

Fix for 2467 master

---

CHANGELOG.md
projects/igniteui-angular/src/lib/calendar/calendar.component.spec.ts
projects/igniteui-angular/src/lib/calendar/calendar.component.ts
projects/igniteui-angular/src/lib/date-picker/date-picker.component.spec.ts
projects/igniteui-angular/src/lib/date-picker/date-picker.component.ts
src/app/calendar/calendar.sample.html
src/app/calendar/calendar.sample.ts
src/app/date-picker/date-picker.sample.html
src/app/date-picker/date-picker.sample.ts

Related to #2424.  
Additional information related to this pull request: added to `igxCalendar` and `igxDatePicker`.

Deselect date methods (6.1.x)

---

projects/igniteui-angular/src/lib/tabs/tabs-group.component.html

Keep only selected tab's content in DOM

---

projects/igniteui-angular/src/lib/drop-down/drop-down-item.component.ts
projects/igniteui-angular/src/lib/drop-down/drop-down.component.spec.ts

There are some test which are using fixture when stable -> then
We change this to fake async -> tick now

Move test to fakeAsync

---

gulpfile.js
package-lock.json
package.json

build(typedoc): Expose additional gulp task for typedoc build

---

projects/igniteui-angular/src/lib/calendar/calendar.component.spec.ts

Removed Angular async in favor of TypeScript async in calendar tests (6.1.x)

---

projects/igniteui-angular/src/lib/calendar/calendar.component.spec.ts

Removed Angular async in favor of TypeScript async in calendar tests (6.2.x)

---

projects/igniteui-angular/src/lib/progressbar/circularbar.component.spec.ts
projects/igniteui-angular/src/lib/progressbar/progressbar.common.ts
projects/igniteui-angular/src/lib/progressbar/progressbar.component.ts
projects/igniteui-angular/src/lib/progressbar/templates/circular-bar.component.html
src/app/progressbar/progressbar.sample.html
src/app/progressbar/progressbar.sample.ts

Closes #2370 .  
Add text template to the circular bar to can user manipulate text

Add text template to circular bar 6.1.x

---

projects/igniteui-angular/src/lib/core/selection.spec.ts
projects/igniteui-angular/src/lib/core/selection.ts

Fix - Selection - Undefined values should not be accepted as ids

---

projects/igniteui-angular/package.json

chore(*): Updating some package information

---

projects/igniteui-angular/src/lib/drop-down/drop-down-item.component.ts

fix(drop down): Correcting the code snippet in the doc #2537

---

projects/igniteui-angular/src/lib/grid/grid.component.spec.ts

Fix and enable failing test in azure headless browser.

---

ROADMAP.md

Adding  number-of-records-based rendering for igxGrid

Adding  number-of-records-based rendering for igxGrid

---

projects/igniteui-angular/migrations/update-6_2/changes/inputs.json
projects/igniteui-angular/migrations/update-6_2/index.spec.ts

Add combo height prop migration

---

projects/igniteui-angular/src/lib/chips/chip.component.html
projects/igniteui-angular/src/lib/chips/chip.component.ts
projects/igniteui-angular/src/lib/chips/chip.spec.ts
projects/igniteui-angular/src/lib/chips/chips-area.spec.ts

Fix igxChip raises onSelection when clicking on remove button. 

---

.github/CONTRIBUTING.md

docs(contrib): Add Breaking changes+migration to CONTRIBUTING.md

---

CHANGELOG.md

Adding igxExpansionPanel to 6.2.0 changelog.

chore(igxExpansionPanel): Adding igxExpansionPanel to 6.2.0 changelog.

---

projects/igniteui-angular/src/lib/directives/dragdrop/README.md

Copy editing drag and drop Readme.md

---

.travis.yml

Disable tests on Travis CI for tagged deploy builds

---

projects/igniteui-angular/src/lib/chips/README.md
projects/igniteui-angular/src/lib/chips/chip.component.ts
projects/igniteui-angular/src/lib/chips/chips-area.component.ts
projects/igniteui-angular/src/lib/chips/chips-area.spec.ts

Fix selected chips not being reflected when are initially selected and onSelection is not emitted.

---

projects/igniteui-angular/src/lib/directives/dragdrop/README.md

Copy editing dragdrop/readme.md

---

projects/igniteui-angular/src/lib/core/styles/components/chip/_chip-theme.scss
src/app/chips/chips.sample.css

style(chip) remove chip margin from component and add it to the sample

---

projects/igniteui-angular/src/lib/directives/tooltip/tooltip.directive.ts

Add missing docs for tooltip classes

---

projects/igniteui-angular/src/lib/core/styles/components/input/_input-group-component.scss
projects/igniteui-angular/src/lib/core/styles/components/input/_input-group-theme.scss

Implements the styling related to Issues #2692 and #2426

feat(input-group): make the input group display density sensitive

---

projects/igniteui-angular/src/lib/core/styles/components/navbar/_navbar-theme.scss

style(nav-bar): update left/right margins to match direct children #2688

---

projects/igniteui-angular/src/lib/icon/icon.service.spec.ts
projects/igniteui-angular/src/lib/icon/icon.service.ts

Add support in IgxIconService to cache SVG icons from text

---

projects/igniteui-angular/src/lib/calendar/calendar.component.spec.ts
projects/igniteui-angular/src/lib/calendar/calendar.component.ts
projects/igniteui-angular/src/lib/calendar/calendar.directives.ts
projects/igniteui-angular/src/lib/calendar/calendar.ts
projects/igniteui-angular/src/lib/grid/grid-filtering-ui.spec.ts

replace using of toDateString with getTime in calendar

---

src/app/tooltip/tooltip.sample.html

#1710 
Fix icons in tooltip demo

Fix icons in tooltip demo

---

projects/igniteui-angular/src/lib/calendar/calendar.component.spec.ts
projects/igniteui-angular/src/lib/calendar/calendar.component.ts

Closes #2675 .  
replace toLocaleDateString in calendar with Intl.DateTimeFormat

replace toLocaleDateString in calendar with Intl.DateTimeFormat 

---

.vscode/launch.json
projects/igniteui-angular/migrations/common/UpdateChanges.spec.ts
projects/igniteui-angular/migrations/common/UpdateChanges.ts
projects/igniteui-angular/migrations/common/schema/binding.schema.json
projects/igniteui-angular/migrations/common/schema/index.ts
projects/igniteui-angular/migrations/update-6_2/changes/inputs.json
projects/igniteui-angular/migrations/update-6_2/index.spec.ts
projects/igniteui-angular/migrations/update-6_2/index.ts
projects/igniteui-angular/src/lib/icon/icon.component.html
projects/igniteui-angular/src/lib/icon/icon.component.ts

#2613  
In addition to migrations add an heuristics to detect and support the case when the fontSet is 'material' and the icon name is set using property 'name'. This code will only be kept for one release.

Migrations for IgxIconComponent breaking changes

---

CHANGELOG.md

#2613  
Make the breaking change for the IgxIconComponent more clear.

docs(icon): Update the Changelog (#2613)

---

projects/igniteui-angular/migrations/common/UpdateChanges.ts

Small refactoring for icon migrations

---

projects/igniteui-angular/src/lib/grid/api.service.ts
projects/igniteui-angular/src/lib/grid/grid-selection.spec.ts
projects/igniteui-angular/src/lib/grid/grid.component.ts

Call detectChanges and clear summaries synchronously

---

projects/igniteui-angular/src/lib/grid/grid-filtering-expression.component.ts

Set condition, when reseting filter expression

---

projects/igniteui-angular/src/lib/core/selection.spec.ts
projects/igniteui-angular/src/lib/core/selection.ts

fix(selection): accept 0 as itemID

---

.travis.yml
projects/igniteui-angular/karma.azure.conf.js
projects/igniteui-angular/karma.conf.js

Trying if this would improve the consistency of the tests on travis.

chore(*): Updating node version for travis

---

projects/igniteui-angular/src/lib/chips/chip.component.ts
projects/igniteui-angular/src/lib/chips/chip.spec.ts
projects/igniteui-angular/src/lib/core/displayDensity.ts
projects/igniteui-angular/src/lib/core/utils.ts
projects/igniteui-angular/src/lib/grid/grid-summary.component.ts
projects/igniteui-angular/src/lib/grid/grid-toolbar.component.ts
projects/igniteui-angular/src/lib/grid/grid-toolbar.spec.ts
projects/igniteui-angular/src/lib/grid/grid.component.spec.ts
projects/igniteui-angular/src/lib/grid/grid.component.ts
projects/igniteui-angular/src/lib/input-group/input-group.component.ts
projects/igniteui-angular/src/lib/input-group/input-group.directive.spec.ts
src/app/app.module.ts
src/app/grid-groupby/grid-groupby.sample.html
src/app/grid-groupby/grid-groupby.sample.ts
src/app/grid-toolbar/grid-toolbar.sample.ts
src/app/input-group/input-group-child.sample.html
src/app/input-group/input-group-child.sample.ts
src/app/input-group/input-group.sample.css
src/app/input-group/input-group.sample.html

Closes #2426.  
Use the newly implemented DI token in the input group.

Implement Display Density DI Token

---

projects/igniteui-angular/src/lib/grid/grid.component.ts

Adding type for groupingExpressions

---

projects/igniteui-angular/src/lib/grid/column-group.spec.ts

Closes #2767 .
Now the sorting is set to columns with unique cell values.

Changing the sorting for Multi Column Headers sorting tests

---

projects/igniteui-angular/src/lib/combo/combo.component.spec.ts

Extract dropdown element indexes in a deterministic way

---

projects/igniteui-angular/src/lib/grid/grid.component.spec.ts

chore(*): Fixing a test for grid empty messages

---

gulpfile.js
package.json

chore(gulp): Update gulp in order to build typedoc en local

---

projects/igniteui-angular/src/lib/chips/chips-area.component.ts
projects/igniteui-angular/src/lib/directives/dragdrop/dragdrop.directive.ts
projects/igniteui-angular/src/lib/grid/api.service.ts
projects/igniteui-angular/src/lib/grid/grid.component.html
projects/igniteui-angular/src/lib/grid/grid.component.ts
projects/igniteui-angular/src/lib/grid/grid.groupby.spec.ts

Fix sorting and groupby expression not syncing when there are already sorted columns. 

---

projects/igniteui-angular/src/lib/core/styles/components/button-group/_button-group-theme.scss
projects/igniteui-angular/src/lib/core/styles/components/card/_card-theme.scss
projects/igniteui-angular/src/lib/core/styles/components/carousel/_carousel-component.scss
projects/igniteui-angular/src/lib/core/styles/components/carousel/_carousel-theme.scss
projects/igniteui-angular/src/lib/core/styles/components/dialog/_dialog-theme.scss

refactor(themes): bring roundness to material design spec 

---

projects/igniteui-angular/src/lib/core/styles/components/banner/_banner-theme.scss
projects/igniteui-angular/src/lib/core/styles/themes/_index.scss
projects/igniteui-angular/src/lib/core/styles/themes/presets/dark-green/_components-theme.scss
projects/igniteui-angular/src/lib/core/styles/themes/presets/dark-green/_index.scss

style(dark-green-theme): Adding styles for banner dark green theme

---

CHANGELOG.md

chore(*): Adding bug fixes to the Changelog

---

projects/igniteui-angular/src/lib/calendar/calendar.component.spec.ts
projects/igniteui-angular/src/lib/calendar/calendar.component.ts

Closes #2575 .  
Closes #2617.

Update deselectRange method

---

projects/igniteui-angular/src/lib/grids/cell.component.ts
projects/igniteui-angular/src/lib/grids/grid-base.component.ts
projects/igniteui-angular/src/lib/grids/grid-common.pipes.ts

Grid row editing performance improvements 

---

projects/igniteui-angular/src/lib/grids/grid-base.component.ts

Enable row editing overlay open animation

---

projects/igniteui-angular/src/lib/directives/for-of/display.container.ts
projects/igniteui-angular/src/lib/directives/for-of/for_of.directive.ts
projects/igniteui-angular/src/lib/directives/scroll-inertia/scroll_inertia.directive.spec.ts
projects/igniteui-angular/src/lib/directives/scroll-inertia/scroll_inertia.directive.ts
src/app/grid-performance/grid-performance.sample.html

[Inertia] - adding check for direction so mixed wheel deltas (MAC) work correctly

---

projects/igniteui-angular/src/lib/directives/for-of/display.container.ts
projects/igniteui-angular/src/lib/directives/for-of/for_of.directive.ts
projects/igniteui-angular/src/lib/directives/scroll-inertia/scroll_inertia.directive.spec.ts
projects/igniteui-angular/src/lib/directives/scroll-inertia/scroll_inertia.directive.ts

[Inertia] - adding check for direction so mixed wheel deltas (MAC) work correctly - MASTER

---

projects/igniteui-angular/src/lib/grids/grid/grid.component.html

Change row editing default text

---

projects/igniteui-angular/src/lib/grids/api.service.ts
projects/igniteui-angular/src/lib/grids/cell.component.ts
projects/igniteui-angular/src/lib/grids/grid-base.component.ts
projects/igniteui-angular/src/lib/grids/grid-navigation.service.ts
projects/igniteui-angular/src/lib/grids/grid/cell.spec.ts
projects/igniteui-angular/src/lib/grids/grid/grid.component.spec.ts
projects/igniteui-angular/src/lib/grids/grid/groupby-row.component.ts
projects/igniteui-angular/src/lib/grids/tree-grid/README.md
projects/igniteui-angular/src/lib/grids/tree-grid/tree-cell.component.ts
projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid-api.service.ts
projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid-crud.spec.ts
projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid-keyBoardNav.spec.ts
projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid.component.ts
projects/igniteui-angular/src/lib/test-utils/tree-grid-components.spec.ts
projects/igniteui-angular/src/lib/test-utils/tree-grid-functions.spec.ts

Closes #2890 
Closes #2893
Closes #2904
Closes #2889

Igx Tree Grid  -- Keyboard Navigation

---

projects/igniteui-angular/src/lib/core/styles/components/grid/_grid-theme.scss
projects/igniteui-angular/src/lib/grids/cell.component.html

Grid styling fixes

---

projects/igniteui-angular/src/lib/directives/for-of/for_of.directive.spec.ts
projects/igniteui-angular/src/lib/directives/for-of/for_of.directive.ts

Emit onChunkPreload/onChunkLoad only when startIndex or chunkSize have changed.

---

CHANGELOG.md
projects/igniteui-angular/src/lib/chips/chip.spec.ts
projects/igniteui-angular/src/lib/data-operations/data-util.spec.ts
projects/igniteui-angular/src/lib/data-operations/data-util.ts
projects/igniteui-angular/src/lib/data-operations/groupby-state.interface.ts
projects/igniteui-angular/src/lib/data-operations/groupby-strategy.spec.ts
projects/igniteui-angular/src/lib/data-operations/grouping-expression.interface.ts
projects/igniteui-angular/src/lib/data-operations/grouping-strategy.ts
projects/igniteui-angular/src/lib/data-operations/sorting-strategy.spec.ts
projects/igniteui-angular/src/lib/data-operations/sorting-strategy.ts
projects/igniteui-angular/src/lib/grid/README.md
projects/igniteui-angular/src/lib/grid/column.component.ts
projects/igniteui-angular/src/lib/grid/grid-header.component.ts
projects/igniteui-angular/src/lib/grid/grid.common.ts
projects/igniteui-angular/src/lib/grid/grid.component.ts
projects/igniteui-angular/src/lib/grid/grid.groupby.spec.ts
projects/igniteui-angular/src/lib/grid/grid.pipes.ts
projects/igniteui-angular/src/public_api.ts
src/app/grid-groupby/grid-groupby.sample.ts

fix(grid): applying grouping-related changes for sort strategy #2734

---

projects/igniteui-angular/migrations/update-6_2/changes/outputs.json
projects/igniteui-angular/migrations/update-6_2/index.spec.ts

chore(migration): add cell edit event migration for #2897

---

projects/igniteui-angular/src/lib/grids/api.service.ts
projects/igniteui-angular/src/lib/grids/grid-base.component.ts
projects/igniteui-angular/src/lib/grids/grid-common.pipes.ts
projects/igniteui-angular/src/lib/grids/grid/grid.component.spec.ts
projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid.pipes.ts
projects/igniteui-angular/src/lib/services/transaction/README.md
projects/igniteui-angular/src/lib/services/transaction/base-transaction.ts
projects/igniteui-angular/src/lib/services/transaction/igx-hierarchical-transaction.ts
projects/igniteui-angular/src/lib/services/transaction/igx-transaction.spec.ts
projects/igniteui-angular/src/lib/services/transaction/igx-transaction.ts
projects/igniteui-angular/src/lib/services/transaction/transaction.ts

Small tranaction api refactor

---

projects/igniteui-angular/src/lib/grids/filtering/grid-filtering-row.component.ts

Check for 'condition' instead of 'searchVal'

---

projects/igniteui-angular/src/lib/services/transaction/README.md
projects/igniteui-angular/src/lib/services/transaction/transaction.ts

onStateUpdate event added, and canUndo/canRedo properties.
Update some of the API descriptions

Update igxTransaction README.md with last API changes

---

CHANGELOG.md

docs(changelog): add typography entry

---

ROADMAP.md

Adding Row Edit as Done as well

---

projects/igniteui-angular/src/lib/grids/filtering/grid-filtering.service.ts

Clear filter when value is cleared from input

---

projects/igniteui-angular/src/lib/grids/filtering/grid-filtering-row.component.html
projects/igniteui-angular/src/lib/grids/filtering/grid-filtering-row.component.ts

Open date-picker only if condition is not unary

---

projects/igniteui-angular/src/lib/grids/filtering/grid-filtering-row.component.ts
projects/igniteui-angular/src/lib/grids/grid/grid-filtering-ui.spec.ts

Close filter row on Esc

---

ROADMAP.md
package-lock.json
projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid-keyBoardNav.spec.ts
projects/igniteui-angular/src/lib/test-utils/tree-grid-functions.spec.ts

chore(*): Merging master into 6.2.x

---

.github/PULL_REQUEST_TEMPLATE.md

chore(*): Updating the PR template

---

package-lock.json
package.json

chore(typedoc): update typedoc-plugin version

---

projects/igniteui-angular/src/lib/grids/grid-base.component.ts
projects/igniteui-angular/src/lib/grids/grid/grid.component.spec.ts
src/app/grid-row-edit/grid-row-edit-sample.component.ts

Fix - Grid - End row edit on row delete - Master

---

projects/igniteui-angular/src/lib/grid/grid-selection.spec.ts
projects/igniteui-angular/src/lib/grid/grid.component.html
projects/igniteui-angular/src/lib/grid/grid.component.ts
projects/igniteui-angular/src/lib/grid/row.component.html
projects/igniteui-angular/src/lib/grid/row.component.ts

Hide row selectors when all columns are hidden

---

.github/PULL_REQUEST_TEMPLATE.md

Fix checkboxes in GitHub PR template

---

projects/igniteui-angular/src/lib/core/styles/components/grid/_grid-theme.scss

Closes #2934 
Mirror PR #2948 to `master` branch

style(row-edit): Adding bigger z-index for the marker

---

ROADMAP.md

(Do NOT MERGE) updates pending - roadmap

---

projects/igniteui-angular/src/lib/grids/column.component.ts
projects/igniteui-angular/src/lib/grids/grid/column-group.spec.ts

Fix exception when col width is set as number

---

projects/igniteui-angular/src/lib/tabs/tabs-group.component.ts

Closes #3030
- [] This PR includes unit tests covering all the new code
- [] This PR includes API docs for newly added methods/properties
- [] This PR includes `feature/README.MD` updates for the feature docs
- [] This PR includes general feature table updates in the root `README.MD`
- [] This PR includes `CHANGELOG.MD` updates for newly added functionality
- [] This PR contains breaking changes
- [] This PR includes `ng update` migrations for the breaking changes
- [] This PR includes behavioral changes and the feature specification has been updated with them

fix(tabs): Resizing issue fixed #3030

---

CHANGELOG.md
projects/igniteui-angular/src/lib/combo/README.md

Closes #2410 
Adding `combo.displayDensity` to Changelog.md & ReadMe.md for combo

Docs - Combo - Add `displayDensity` input - 6.2.x

---

CHANGELOG.md
projects/igniteui-angular/src/lib/combo/README.md

Closes #2410 
Adding `combo.displayDensity` to Changelog.md & ReadMe.md for combo

Docs - Combo - Add `displayDensity` input - Master

---

projects/igniteui-angular/src/lib/calendar/calendar.component.ts
projects/igniteui-angular/src/lib/date-picker/date-picker.component.spec.ts
projects/igniteui-angular/src/lib/date-picker/date-picker.component.ts

[Fix] Focus the today date on date picker open

---

projects/igniteui-angular/src/lib/grid/grid.sorting.spec.ts
src/app/grid/grid.sample.ts

Related to this Pull Request: https://github.com/IgniteUI/igniteui-angular/pull/2906

Automated test for a custom sorting strategy #2734 - 6.1.x

---

projects/igniteui-angular/src/lib/grids/filtering/grid-filtering-row.component.html
projects/igniteui-angular/src/lib/grids/filtering/grid-filtering-row.component.ts

Closes #3092, Closes #3093, Closes #3086

Improve UX for boolean and date columns

---

package-lock.json
package.json

chore(*): update sassdoc-plugin version

---

gulpfile.js

build(sass): make the build fail on sass build errors

---

projects/igniteui-angular/src/lib/core/styles/components/grid/_grid-theme.scss

feat(grid): adding bigger z-index to grid outlet

---

extras/docs/themes/sassdoc/assets/js/navigation/igviewer.common.js
extras/docs/themes/sassdoc/assets/js/navigation/igviewer.renderingService.js
extras/docs/themes/sassdoc/assets/js/navigation/nav-initializer.js
extras/docs/themes/sassdoc/index.js
extras/docs/themes/sassdoc/views/index.hbs
extras/docs/themes/sassdoc/views/partials/header.hbs
extras/docs/themes/sassdoc/views/partials/infragistics/infrafoot.ja.hbs
extras/docs/themes/sassdoc/views/partials/infragistics/infranav.ja.hbs
gulpfile.js

Ja header footer switching

---

extras/docs/themes/sassdoc/views/partials/header.hbs
extras/docs/themes/typedoc/src/partials/header.hbs
package-lock.json
package.json

chore(versions): update sass and type doc API versions

---

projects/igniteui-angular/src/lib/core/styles/components/input/_input-group-theme.scss

refactor(themes): don't show spinner for input-group of type number

---

extras/docs/themes/sassdoc/views/partials/header.hbs
extras/docs/themes/typedoc/src/partials/header.hbs

chore(versions): update sassdoc and typedoc api versions

---

CHANGELOG.md

Add 7.0.0 node to changelog, 6.2.1 es6 fix

---

package-lock.json
package.json

chore(package.json): remove gulp-typedoc package

---

CHANGELOG.md

docs(*): update CHANGELOG.md with 6.2.1 changes

---

extras/docs/themes/sassdoc/index.js
extras/docs/themes/sassdoc/views/index.hbs
extras/docs/themes/sassdoc/views/partials/header.hbs
extras/docs/themes/typedoc/src/partials/header.hbs
extras/template/strings/shell-strings.json

fix(api-doc): translate header strings sassdoc/typedoc

---

projects/igniteui-angular/src/lib/grids/cell.component.ts

fix(igxCell): Make sure to exit edit mode before refocus

---

projects/igniteui-angular/src/lib/grids/filtering/grid-filtering-row.component.ts
projects/igniteui-angular/src/lib/grids/grid/grid-filtering-ui.spec.ts

Pop empty item from expressionsList

---

gulpfile.js
package-lock.json
package.json

chore(typedoc): update plugin version and export tags/params

---

extras/docs/themes/sassdoc/views/partials/header.hbs
extras/docs/themes/typedoc/src/partials/header.hbs

chore(themes): update links of sassdoc and typedoc themes

---

extras/docs/themes/sassdoc/assets/css/main.css
extras/docs/themes/sassdoc/index.js
extras/docs/themes/sassdoc/scss/partials/_main.scss
extras/docs/themes/sassdoc/scss/partials/_returns.scss
extras/docs/themes/sassdoc/views/index.hbs
extras/docs/themes/sassdoc/views/partials/return.hbs

docs(sassdoc): add 'returns' template for the produces docs

---

projects/igniteui-angular/src/lib/grids/grid-base.component.ts
projects/igniteui-angular/src/lib/grids/grid/grid-row.component.html
projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid-row.component.html

Disable checkbox animations on grid scroll 

---

extras/docs/themes/sassdoc/assets/css/main.css
extras/docs/themes/sassdoc/index.js
extras/docs/themes/sassdoc/scss/partials/_main.scss
extras/docs/themes/sassdoc/scss/partials/_returns.scss
extras/docs/themes/sassdoc/views/index.hbs
extras/docs/themes/sassdoc/views/partials/return.hbs

Closes #2833
Additional information (check all that apply):
Checklist:

docs(sassdoc): add 'returns' template for the produced docs

---

projects/igniteui-angular/src/lib/grids/grid.common.ts

Bottom top animation, when row editing overlay is shown at top

---

projects/igniteui-angular/src/lib/core/utils.ts
projects/igniteui-angular/src/lib/grids/filtering/grid-filtering-row.component.html
projects/igniteui-angular/src/lib/grids/filtering/grid-filtering-row.component.ts

Open dropdown on Alt+down

---

projects/igniteui-angular/src/lib/calendar/calendar.component.ts

Update range deselection in Calendar

---

projects/igniteui-angular/src/lib/core/styles/components/grid-toolbar/_grid-toolbar-theme.scss
projects/igniteui-angular/src/lib/core/styles/themes/schemas/dark/_grid-toolbar.scss

Fix Export to excel drop down menu background color [master]

---

src/app/grid-row-edit/grid-row-edit-sample.component.ts
src/app/grid-summaries/grid-summaries.sample.html

Chore - DevSamples - Fix DevSamples to properly run with --prod - 7.0.x

---

src/app/grid-row-edit/grid-row-edit-sample.component.ts
src/app/grid-summaries/grid-summaries.sample.html

Chore - DevSamples - Fix DevSamples to properly run with --prod - 6.2.x

---

CHANGELOG.md
projects/igniteui-angular/src/lib/data-operations/sorting-expression.interface.ts
projects/igniteui-angular/src/lib/data-operations/sorting-strategy.ts
projects/igniteui-angular/src/lib/grids/grid/cell.spec.ts
projects/igniteui-angular/src/lib/grids/grid/column-group.spec.ts
projects/igniteui-angular/src/lib/grids/grid/column-moving.spec.ts
projects/igniteui-angular/src/lib/grids/grid/grid-selection.spec.ts
projects/igniteui-angular/src/lib/grids/grid/grid.groupby.spec.ts
projects/igniteui-angular/src/lib/grids/grid/grid.pinning.spec.ts
projects/igniteui-angular/src/lib/grids/grid/grid.search.spec.ts
projects/igniteui-angular/src/lib/grids/grid/grid.sorting.spec.ts
projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid-indentation.spec.ts
projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid-integration.spec.ts
projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid-selection.spec.ts
projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid-sorting.spec.ts
projects/igniteui-angular/src/lib/services/csv/csv-exporter-grid.spec.ts
projects/igniteui-angular/src/lib/services/excel/excel-exporter-grid.spec.ts
src/app/grid-groupby/grid-groupby.sample.ts

feat(sorting): Making the strategy and ignoreCase optional again #2734

---

CHANGELOG.md
projects/igniteui-angular/src/lib/data-operations/sorting-expression.interface.ts
projects/igniteui-angular/src/lib/data-operations/sorting-strategy.ts
projects/igniteui-angular/src/lib/grids/grid/cell.spec.ts
projects/igniteui-angular/src/lib/grids/grid/column-group.spec.ts
projects/igniteui-angular/src/lib/grids/grid/column-moving.spec.ts
projects/igniteui-angular/src/lib/grids/grid/grid-selection.spec.ts
projects/igniteui-angular/src/lib/grids/grid/grid.groupby.spec.ts
projects/igniteui-angular/src/lib/grids/grid/grid.pinning.spec.ts
projects/igniteui-angular/src/lib/grids/grid/grid.search.spec.ts
projects/igniteui-angular/src/lib/grids/grid/grid.sorting.spec.ts
projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid-indentation.spec.ts
projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid-integration.spec.ts
projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid-selection.spec.ts
projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid-sorting.spec.ts
projects/igniteui-angular/src/lib/services/csv/csv-exporter-grid.spec.ts
projects/igniteui-angular/src/lib/services/excel/excel-exporter-grid.spec.ts
src/app/grid-groupby/grid-groupby.sample.ts

feat(sorting): Making the sorting strategy and ignoreCase optional #2734

---

CHANGELOG.md

docs(*): add 6.2.3 missing changes and bug fixes to changelog

---

CHANGELOG.md

docs(*): add 6.2.3/7.0.2 bug fixes to changelog

---

extras/template/strings/shell-strings.json

chore(shell-strings): add some shell strings which should be localized

---

projects/igniteui-angular/package.json
projects/igniteui-angular/schematics/ng-add/index.ts

Move igniteui-cli as a dev dependency

---

projects/igniteui-angular/src/lib/core/styles/components/grid/_grid-theme.scss

fix(grid): column headers not styled uniformly on drag

---

projects/igniteui-angular/src/lib/expansion-panel/README.md
projects/igniteui-angular/src/lib/expansion-panel/expansion-panel-body.component.ts
projects/igniteui-angular/src/lib/expansion-panel/expansion-panel-header.component.ts
projects/igniteui-angular/src/lib/expansion-panel/expansion-panel.component.ts

Docs - Expansion Panel - Add comments and README - 6.2.x

---

projects/igniteui-angular/src/lib/grids/grid-base.component.ts
projects/igniteui-angular/src/lib/grids/grid/grid-filtering-ui.spec.ts

Reset isFilterRowVisible, when changing allowFiltering

---

projects/igniteui-angular/src/lib/combo/combo.component.spec.ts
projects/igniteui-angular/src/lib/drop-down/drop-down.base.ts
projects/igniteui-angular/src/lib/drop-down/drop-down.component.ts

Fix - Combo, Drop Down - Fix TAB Key Nav - Master

---

.github/CONTRIBUTING.md

Update contributing document with localization

---

projects/igniteui-angular/src/lib/expansion-panel/README.md
projects/igniteui-angular/src/lib/expansion-panel/expansion-panel-body.component.ts
projects/igniteui-angular/src/lib/expansion-panel/expansion-panel-header.component.ts
projects/igniteui-angular/src/lib/expansion-panel/expansion-panel.component.ts

Docs - Expansion Panel - Add comments and README - master

---

projects/igniteui-angular/src/lib/combo/combo-dropdown.component.ts
projects/igniteui-angular/src/lib/combo/combo.common.ts
projects/igniteui-angular/src/lib/combo/combo.component.html
projects/igniteui-angular/src/lib/combo/combo.component.spec.ts
projects/igniteui-angular/src/lib/combo/combo.component.ts
src/app/combo/combo.sample.html
src/app/combo/combo.sample.ts

Fix - Combo - Hide Search input when !filterable && !allowCustomValues - 7.0.x

---

projects/igniteui-angular/src/lib/combo/combo-dropdown.component.ts
projects/igniteui-angular/src/lib/combo/combo.common.ts
projects/igniteui-angular/src/lib/combo/combo.component.html
projects/igniteui-angular/src/lib/combo/combo.component.spec.ts
projects/igniteui-angular/src/lib/combo/combo.component.ts
src/app/combo/combo.sample.html
src/app/combo/combo.sample.ts

Fix - Combo - Hide Search input when !filterable && !allowCustomValues - master

---

projects/igniteui-angular/src/lib/grids/column-chooser-base.ts
projects/igniteui-angular/src/lib/grids/grid-base.component.ts
projects/igniteui-angular/src/lib/grids/grid-toolbar.component.html

Fixing column chooser column updating - 6.2.x

---

projects/igniteui-angular/src/lib/grids/grid-base.component.ts
projects/igniteui-angular/src/lib/grids/grid-toolbar.component.html

Fixing column chooser column updating - master

---

projects/igniteui-angular/src/lib/banner/banner.component.spec.ts
projects/igniteui-angular/src/lib/banner/banner.component.ts
src/app/banner/banner.sample.css
src/app/banner/banner.sample.html
src/app/banner/banner.sample.ts

chore(banner) - add banner display to enable basic styling - master

---

extras/template/strings/shell-strings.json

chore(documentation): updating shell-strings.json #3260

---

package-lock.json
package.json

chore(build): Use 1.3.0 plugin version #3288

---

projects/igniteui-angular/src/lib/core/selection.ts
projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid-api.service.ts
projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid-selection.spec.ts
projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid.component.ts

Tree grid selection

---

CHANGELOG.md

Update Changelog with 7.0.3 section

---

CHANGELOG.md

Updating changelog 70x

---

CHANGELOG.md

Remove bug fix from Changelog

---

projects/igniteui-angular/src/lib/core/styles/components/banner/_banner-component.scss

Revert banner CSS class, used by row editing dialog

---

projects/igniteui-angular/src/lib/core/styles/components/grid/_grid-component.scss
projects/igniteui-angular/src/lib/core/styles/components/grid/_grid-theme.scss
projects/igniteui-angular/src/lib/core/styles/themes/schemas/dark/_grid.scss
projects/igniteui-angular/src/lib/core/styles/themes/schemas/light/_grid.scss
projects/igniteui-angular/src/lib/grids/cell.component.ts
projects/igniteui-angular/src/lib/grids/grid-navigation.service.ts
projects/igniteui-angular/src/lib/grids/grid/grid.pinning.spec.ts

Third time's the charm.
Resolved #3195

fix(grid): selected and pinned cells show content under

---

CHANGELOG.md

chore(changelog): Updating changelog #3382

---

projects/igniteui-angular/src/lib/core/styles/base/utilities/_functions.scss

fix(themes): fix stackblitz failing because of get-function

---

projects/igniteui-angular/src/lib/core/styles/components/grid-toolbar/_grid-toolbar-theme.scss

style(toolbar): Fix IE11 toolbar height bug

---

projects/igniteui-angular/src/lib/core/styles/components/grid-toolbar/_grid-toolbar-theme.scss

Fix IE11 bug with toolbar height

---

projects/igniteui-angular/src/lib/grids/README.md
projects/igniteui-angular/src/lib/grids/column.component.ts
projects/igniteui-angular/src/lib/grids/grid-base.component.ts
projects/igniteui-angular/src/lib/grids/summaries/grid-summary.service.ts
src/app/grid-summaries/grid-summaries.sample.ts

Deprecate clearSummaryCache and recalculateSummaries methods

---

ROADMAP.md

Closes #  https://github.com/IgniteUI/igniteui-angular/issues/3421

replacing Advance filtering with excel style filtering

---

extras/docs/themes/sassdoc/scss/partials/_header.scss
extras/docs/themes/sassdoc/views/partials/header.hbs
extras/docs/themes/typedoc/src/partials/header.hbs

The header link in the api docs page should be to the product page

---

projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid-row.component.ts

Closes #3329 
This issue is fixed in `master` with the merge of [TreeGrid batch update PR](https://github.com/IgniteUI/igniteui-angular/pull/2954)
This PR only applies the change to the check used in `tree-grid-row.component.ts` to determine deleted state

Fix - TreeGrid - Adjust tree grid row check for deleted parent - 7.0.x

---

projects/igniteui-angular/src/lib/directives/template-outlet/template_outlet.directive.ts
projects/igniteui-angular/src/lib/grids/grid/grid.search.spec.ts

IgxTemplateOutletDirective -- refactoring

---

projects/igniteui-angular/src/lib/grids/tree-grid/tree-cell.component.html
projects/igniteui-angular/src/lib/grids/tree-grid/tree-cell.component.ts
projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid-api.service.ts

Focus native element on expansion indicator focus

---

projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid-api.service.ts
projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid.component.ts

#3439 `generateRowPath` proper path order, cleanup extra calls

---

package-lock.json
package.json

chore(package.json): update typedoc-plugin-localization version

---

projects/igniteui-angular/src/lib/slider/slider.component.spec.ts

igx-slider max-value defaults to min-value 

---

projects/igniteui-angular/src/lib/grids/grid/grid-filtering-ui.spec.ts
projects/igniteui-angular/src/lib/grids/grid/grid-filtering.spec.ts

Fix the logic calculating test results

---

ROADMAP.md

Adding advanced filtering to the roadmap

Adding advanced Filtering

---

projects/igniteui-angular/src/lib/directives/for-of/for_of.directive.spec.ts
projects/igniteui-angular/src/lib/directives/for-of/for_of.directive.ts

Preventing wrap-around for scrollNext and scrollPrev -- 7.0

---

projects/igniteui-angular/src/lib/grids/cell.component.ts
projects/igniteui-angular/src/lib/grids/column.component.ts
projects/igniteui-angular/src/lib/grids/grid/grid-summary.spec.ts
projects/igniteui-angular/src/lib/grids/summaries/summary-cell.component.ts

Include grid's unpinnedWidth and totalWidth in cell width calculation

---

projects/igniteui-angular/src/lib/grids/grid-base.component.ts
projects/igniteui-angular/src/lib/grids/grid/grid.component.spec.ts

#3047 igxGrid isn't displayed properly in IE11 when in igxTabs 7.1.x

---

projects/igniteui-angular/src/lib/grids/grid-base.component.ts
projects/igniteui-angular/src/lib/grids/grid/grid.component.spec.ts

#3047 igxGrid isn't displayed properly in IE11 when in igxTabs
Closes #3047

#3047 igxGrid isn't displayed properly in IE11 when in igxTabs 6.2.x

---

projects/igniteui-angular/src/lib/grids/grid-base.component.ts
projects/igniteui-angular/src/lib/grids/grid/grid.component.spec.ts

#3047 igxGrid isn't displayed properly in IE11 when in igxTabs 7.0.x

---

projects/igniteui-angular/src/lib/grids/grid-base.component.ts
projects/igniteui-angular/src/lib/grids/grid.common.ts
projects/igniteui-angular/src/lib/grids/grid/grid.component.spec.ts
projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid.component.spec.ts
projects/igniteui-angular/src/lib/test-utils/tree-grid-components.spec.ts

Derive possible heights after markForCheck() is called #3467

---

projects/igniteui-angular/src/lib/grids/grid-base.component.ts
projects/igniteui-angular/src/lib/grids/grid/grid.component.spec.ts
projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid.component.spec.ts
projects/igniteui-angular/src/lib/test-utils/tree-grid-components.spec.ts

fix(grid): derive heights after markForCheck is called #3467

---

CHANGELOG.md

docs(*): updating changelog for 7.0.x #3495

---

projects/igniteui-angular/src/lib/grids/grid/grid-filtering-ui.spec.ts

test(update): Modify firstMonth selector #3508

---

projects/igniteui-angular/src/lib/grids/grid-base.component.ts
projects/igniteui-angular/src/lib/grids/grid/grid.component.spec.ts
projects/igniteui-angular/src/lib/services/transaction/igx-hierarchical-transaction.ts

Fix - Transactions - Gird Transactions + Paging interactions - 6.2.x

---

projects/igniteui-angular/src/lib/grids/cell.component.ts

Fix - ESCAPE on grid cell not in edit - 6.2.x

---

projects/igniteui-angular/src/lib/grids/cell.component.ts
projects/igniteui-angular/src/lib/grids/grid/grid.component.spec.ts

Focus the default inputs when cell enter edit mode -- 6.2.x

---

projects/igniteui-angular/src/lib/grids/api.service.ts
projects/igniteui-angular/src/lib/grids/cell.component.ts
projects/igniteui-angular/src/lib/grids/column.component.ts
projects/igniteui-angular/src/lib/grids/filtering/grid-filtering.service.ts
projects/igniteui-angular/src/lib/grids/grid-base.component.ts
projects/igniteui-angular/src/lib/grids/grid-common.pipes.ts
projects/igniteui-angular/src/lib/grids/grid-header.component.ts
projects/igniteui-angular/src/lib/grids/grid-summary.component.ts
projects/igniteui-angular/src/lib/grids/grid-toolbar.component.ts
projects/igniteui-angular/src/lib/grids/grid/grid.component.html
projects/igniteui-angular/src/lib/grids/grid/grid.component.ts
projects/igniteui-angular/src/lib/grids/grid/grid.pipes.ts
projects/igniteui-angular/src/lib/grids/grid/groupby-row.component.ts
projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.component.html
projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.component.ts
projects/igniteui-angular/src/lib/grids/hierarchical-grid/row-island.component.ts
projects/igniteui-angular/src/lib/grids/row.component.ts
projects/igniteui-angular/src/lib/grids/tree-grid/tree-cell.component.ts
projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid-api.service.ts
projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid.component.html
projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid.component.ts
projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid.filtering.pipe.ts
projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid.pipes.ts
projects/igniteui-angular/src/lib/test-utils/tree-grid-functions.spec.ts

Create Data Bindable interface and move some data related methods to gridAPI.

---

projects/igniteui-angular/src/lib/directives/mask/mask.directive.ts
projects/igniteui-angular/src/lib/time-picker/time-picker.component.html
projects/igniteui-angular/src/lib/time-picker/time-picker.component.spec.ts
projects/igniteui-angular/src/lib/time-picker/time-picker.component.ts

fix(time picker): IE cursor flickering on spinning

---

projects/igniteui-angular/src/lib/drop-down/drop-down.component.ts

Fixing a broken link in typescript docs - 6.2.x

---

projects/igniteui-angular/src/lib/drop-down/drop-down.component.ts

Fixing a broken link in typescript docs - 7.1.x

---

projects/igniteui-angular/src/lib/drop-down/drop-down.component.ts

Fixing a broken link in typescript docs - master

---

projects/igniteui-angular/src/lib/grids/filtering/grid-filtering-row.component.html
projects/igniteui-angular/src/lib/grids/filtering/grid-filtering-row.component.ts
projects/igniteui-angular/src/lib/grids/grid/grid-filtering-ui.spec.ts
projects/igniteui-angular/src/lib/grids/grid/grid-filtering.spec.ts
projects/igniteui-angular/src/lib/test-utils/grid-functions.spec.ts

Add flag for keydown for a corner case in IE

---

projects/igniteui-angular/src/lib/services/transaction/transaction.ts

Fixing comment structure - 6.2.x

---

projects/igniteui-angular/src/lib/services/transaction/transaction.ts

Fixing comment structure - 7.1.x

---

projects/igniteui-angular/src/lib/grids/filtering/grid-filtering-row.component.html
projects/igniteui-angular/src/lib/grids/filtering/grid-filtering-row.component.ts

fix(filtering): prevent improper event firing in IE when typing JP character

---

projects/igniteui-angular/src/lib/combo/combo.component.html

Fix - Combo - Add `autocomplete=off` to combo search input

---

projects/igniteui-angular/src/lib/core/styles/components/navbar/_navbar-theme.scss
projects/igniteui-angular/src/lib/navbar/navbar.component.spec.ts
src/app/navbar/navbar.sample.html

Make content of igx-action-icon vertically-centered.
#3584

Make content of igx-action-icon vertically-centered - 7.1.x

---

projects/igniteui-angular/src/lib/grids/grid-base.component.ts
projects/igniteui-angular/src/lib/grids/grid/grid.component.spec.ts

fix(grid): igxGrid isn't displayed properly in IE11 if in igxTabs #3047

---

projects/igniteui-angular/src/lib/directives/text-highlight/text-highlight.directive.ts
projects/igniteui-angular/src/lib/grids/cell.component.ts
projects/igniteui-angular/src/lib/grids/grid/grid.search.spec.ts

Fix search highlight after entering edit mode

---

projects/igniteui-angular/src/lib/core/styles/components/tabs/_tabs-theme.scss
projects/igniteui-angular/src/lib/tabs/tabs.component.spec.ts
src/app/tabs/tabs.sample.css
src/app/tabs/tabs.sample.html

Refactor tabs master

---

projects/igniteui-angular/src/lib/calendar/calendar.component.ts

refactor(calendar): Corrected import path for utils

---

projects/igniteui-angular/schematics/collection.json
projects/igniteui-angular/schematics/interfaces/options.ts
projects/igniteui-angular/schematics/ng-add/index.spec.ts
projects/igniteui-angular/schematics/ng-add/index.ts
projects/igniteui-angular/schematics/ng-add/schema.json
projects/igniteui-angular/schematics/tsconfig.json
projects/igniteui-angular/schematics/utils/dependency-handler.ts
projects/igniteui-angular/schematics/utils/package-handler.ts

feat(ng-add): Add prompt for polyfills #3528

---

projects/igniteui-angular/src/lib/grids/column.component.ts
projects/igniteui-angular/src/lib/grids/grid-base.component.ts

fix(docs): Adding description for column.pin and column.unpin APIs #3660

---

projects/igniteui-angular/src/lib/date-picker/date-picker.component.html
projects/igniteui-angular/src/lib/date-picker/date-picker.component.spec.ts
projects/igniteui-angular/src/lib/date-picker/date-picker.component.ts
projects/igniteui-angular/src/lib/time-picker/time-picker.component.html
projects/igniteui-angular/src/lib/time-picker/time-picker.component.spec.ts
projects/igniteui-angular/src/lib/time-picker/time-picker.component.ts

#3641 Required inputs shouldn't be validated initially.

---

projects/igniteui-angular/src/lib/grids/grid/grid-summary.spec.ts
projects/igniteui-angular/src/lib/grids/summaries/grid-summary.service.ts
projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid-filtering.spec.ts
projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid-keyBoardNav.spec.ts
projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid-summaries.spec.ts
projects/igniteui-angular/src/lib/test-utils/grid-samples.spec.ts
projects/igniteui-angular/src/lib/test-utils/helper-utils.spec.ts
projects/igniteui-angular/src/lib/test-utils/sample-test-data.spec.ts
projects/igniteui-angular/src/lib/test-utils/template-strings.spec.ts
projects/igniteui-angular/src/lib/test-utils/tree-grid-components.spec.ts

Add summaries tests 7.1.x

---

projects/igniteui-angular/src/lib/grids/hierarchical-grid/child-grid-row.component.ts
projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid-api.service.ts
projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid-base.component.ts
projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.component.html
projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.component.ts
projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.integration.spec.ts
projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.module.ts
projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.pipes.ts
projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-row.component.html
projects/igniteui-angular/src/lib/grids/hierarchical-grid/index.ts
projects/igniteui-angular/src/lib/grids/hierarchical-grid/row-island.component.ts
src/app/hierarchical-grid-updating/hierarchical-grid-updating.sample.ts

Update hierarchical structure for the hierarchical grid with base class.

---

extras/docs/themes/config.json
extras/docs/themes/sassdoc/index.js
extras/docs/themes/sassdoc/views/index.hbs
extras/docs/themes/typedoc/src/assets/js/src/theme.ts
extras/docs/themes/typedoc/src/layouts/default.hbs

Implement google analytics sassdoc/typedoc

---

projects/igniteui-angular/src/lib/time-picker/time-picker.directives.ts

Add typedoc comment for time picker directive

---

CHANGELOG.md

docs(changelog): Updating changelog for 6.2.5

---

CHANGELOG.md

docs(changelog): Updating Changelog for 7.1.2

---

projects/igniteui-angular/src/lib/directives/radio/radio-group.directive.ts

Closes IgniteUI/igniteui-docfx#966

fix(RadioGroup): #966  Fixed documentation link.

---

projects/igniteui-angular/src/lib/directives/text-highlight/text-highlight.directive.ts

Optimize highlight value check for first change - 7.1.x

---

CHANGELOG.md
projects/igniteui-angular/src/lib/combo/combo-item.component.ts
projects/igniteui-angular/src/lib/combo/combo.component.ts
projects/igniteui-angular/src/lib/core/styles/components/drop-down/_drop-down-component.scss
projects/igniteui-angular/src/lib/core/styles/components/drop-down/_drop-down-theme.scss
projects/igniteui-angular/src/lib/drop-down/README.md
projects/igniteui-angular/src/lib/drop-down/drop-down-group.component.ts
projects/igniteui-angular/src/lib/drop-down/drop-down-item.base.ts
projects/igniteui-angular/src/lib/drop-down/drop-down-item.component.ts
projects/igniteui-angular/src/lib/drop-down/drop-down.component.spec.ts
projects/igniteui-angular/src/lib/drop-down/drop-down.component.ts
projects/igniteui-angular/src/lib/drop-down/index.ts
projects/igniteui-angular/src/lib/grids/grid-common.module.ts
src/app/drop-down/drop-down.sample.html
src/app/drop-down/drop-down.sample.ts
src/app/drop-down/foods.ts

Closes #3696
Once PR is merged, wiki will be updated (https://github.com/IgniteUI/igniteui-angular/issues/3720)

feat(drop-down): Add Drop Down Item Group support

---

projects/igniteui-angular/src/lib/grids/grid/grid-filtering-ui.spec.ts

chore(*): Fixing wrong selector PR3728

---

projects/igniteui-angular/src/lib/grids/filtering/grid-filtering.service.ts

Unmap columns that have been removed from grid

---

projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid-expanding.spec.ts

test(igxTreeGrid): finish expand/collapse tests #3733

---

projects/igniteui-angular/src/lib/core/deprecateDecorators.ts

Fix DepracateProperty decorator with class field

---

projects/igniteui-angular/src/lib/grids/cell.component.html
projects/igniteui-angular/src/lib/grids/cell.component.ts

Prevent submit edit value when type in Japanese --7.1.x

---

projects/igniteui-angular/src/lib/grids/cell.component.html
projects/igniteui-angular/src/lib/grids/cell.component.ts

 Prevent submit edit value when type in Japanese --6.2.x

---

projects/igniteui-angular/src/lib/grids/grid-base.component.ts

Blur active cell element on scroll

---

projects/igniteui-angular/src/lib/grids/grid-base.component.ts

Blur active cell element on scroll --7.2.x

---

CHANGELOG.md
projects/igniteui-angular/src/lib/combo/combo.component.html
projects/igniteui-angular/src/lib/combo/combo.component.spec.ts
projects/igniteui-angular/src/lib/core/styles/components/input/_input-group-theme.scss
projects/igniteui-angular/src/lib/input-group/input-group.component.html
src/app/combo/combo.sample.html

feat(combo): add support for hint in igx-combo input group

---

projects/igniteui-angular/src/lib/grids/grid-base.component.ts

fix(Grid): Fix for #3727 : Errors are thrown when igx grid is initialized in IE11.

---

CHANGELOG.md

Removing a change which was added in 7.1.4 version and included in CHANGELOG.md
at this version.
Closes #3636

Update CHANGELOG.md, #3636

---

projects/igniteui-angular/src/lib/combo/combo-dropdown.component.ts
projects/igniteui-angular/src/lib/drop-down/drop-down-navigation.directive.ts
projects/igniteui-angular/src/lib/drop-down/drop-down.base.ts
projects/igniteui-angular/src/lib/drop-down/drop-down.common.ts
projects/igniteui-angular/src/lib/drop-down/drop-down.component.ts

fix(drop-down): fix circular dependency in drop down components

---

projects/igniteui-angular/src/lib/directives/toggle/README.md
projects/igniteui-angular/src/lib/directives/toggle/toggle.directive.spec.ts
projects/igniteui-angular/src/lib/directives/toggle/toggle.directive.ts
projects/igniteui-angular/src/lib/services/overlay/overlay.ts
projects/igniteui-angular/src/lib/services/overlay/scroll/absolute-scroll-strategy.ts

If you add igxToggleAction on some element it will provide the element as target for the position startegy.
Closes #3636

Force toggle action to set target 7.1.x

---

extras/docs/themes/typedoc/src/assets/js/src/versioning/tag-versions.req.js

fix(typedoc-theme): generate dropdown options with corresponding links

---

extras/docs/themes/sassdoc/assets/js/versioning/tag-versions.req.js
extras/docs/themes/typedoc/src/assets/js/src/versioning/tag-versions.req.js

fix(api-dropdown): set latest verison by the default

---

projects/igniteui-angular/src/lib/grids/cell.component.html
projects/igniteui-angular/src/lib/grids/grid-base.component.ts
projects/igniteui-angular/src/lib/grids/grid/grid.search.spec.ts
projects/igniteui-angular/src/lib/grids/tree-grid/tree-cell.component.html

fix(search): Searching at the formatted cell data #3753

---

projects/igniteui-angular/src/lib/grids/tree-grid/tree-cell.component.html
projects/igniteui-angular/src/lib/test-utils/tree-grid-functions.spec.ts

Changing collapse icon for IgxTreeGrid - 6.2.x

---

projects/igniteui-angular/src/lib/grids/grid/grid.search.spec.ts

Closes #3691
The fix is already available in master. The RP only adds the automation test.

refreshSearch when a column is hidden

---

extras/docs/themes/sassdoc/assets/js/versioning/tag-versions.req.js
extras/docs/themes/sassdoc/views/index.hbs
extras/docs/themes/typedoc/src/assets/js/src/versioning/tag-versions.req.js
gulpfile.js

fix(api-dropdown): sass dropdown optimization and version reverse

---

projects/igniteui-angular/src/lib/grids/grid/grid.component.html
projects/igniteui-angular/src/lib/grids/grid/groupby-row.component.html

Changed expand/colapse icons to be same as in the hierarchical grid. (6.2.x)

---

projects/igniteui-angular/src/lib/grids/grid-base.component.ts
projects/igniteui-angular/src/lib/grids/grid/grid.search.spec.ts

Wait until data is changed when scrolling to a different page

---

extras/docs/themes/sassdoc/assets/js/versioning/tag-versions.req.js
extras/docs/themes/typedoc/src/assets/js/src/versioning/tag-versions.req.js

fix(api-dropdown): change option links and diversify the sessionStorage

---

extras/docs/themes/sassdoc/assets/js/versioning/tag-versions.req.js
extras/docs/themes/typedoc/src/assets/js/src/versioning/tag-versions.req.js

Ie dropdown rendering

---

extras/docs/themes/sassdoc/assets/js/versioning/tag-versions.req.js
extras/docs/themes/typedoc/src/assets/js/src/versioning/tag-versions.req.js

IЕ dropdown rendering 6.2.x

---

extras/docs/themes/sassdoc/assets/js/versioning/tag-versions.req.js
extras/docs/themes/typedoc/src/assets/js/src/versioning/tag-versions.req.js

IE dropdown rendering 7.1.x

---

extras/docs/themes/sassdoc/assets/js/versioning/tag-versions.req.js
extras/docs/themes/typedoc/src/assets/js/src/versioning/tag-versions.req.js

IE dropdown rendering 7.0.x

---

projects/igniteui-angular/src/lib/core/styles/components/icon/_icon-component.scss
projects/igniteui-angular/src/lib/core/styles/components/icon/_icon-theme.scss

fix(svg-container): fix missing classes for svg icon container

---

projects/igniteui-angular/src/lib/core/styles/base/utilities/_functions.scss

refactor(functions): remove duplicated functions

---

CHANGELOG.md
projects/igniteui-angular/src/lib/grids/cell.component.ts
projects/igniteui-angular/src/lib/grids/grid/grid-keyBoardNav.spec.ts
projects/igniteui-angular/src/lib/grids/grid/groupby-row.component.ts
projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid-keyBoardNav.spec.ts

Add expand/collapse with Alt + Arrow Up/Down.

---

projects/igniteui-angular/src/lib/core/styles/components/progress/_progress-theme.scss
projects/igniteui-angular/src/lib/progressbar/templates/linear-bar.component.html
src/app/progressbar/progressbar.sample.html
src/app/progressbar/progressbar.sample.ts

1. Fix missing class for text-align center
2. Fix start and end position
3. Fix top and bottom position
Closes #3862

style(linear-bar): Fix text alignment

---

projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-cell.component.ts
projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid-base.component.ts
projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-row.component.ts
projects/igniteui-angular/src/lib/grids/hierarchical-grid/row-island.component.ts

fix(hGrid): Fixing circular dependencies #3880

---

projects/igniteui-angular/src/lib/expansion-panel/expansion-panel-header.component.ts
projects/igniteui-angular/src/lib/expansion-panel/expansion-panel.spec.ts

feat(expansion-panel): ArrowDown/ArrowUp toggle handler on header

---

extras/docs/themes/typedoc/src/assets/js/src/theme.ts
gulpfile.js

Build typedoc doc 7.0.x

---

extras/docs/themes/typedoc/src/assets/js/src/theme.ts
gulpfile.js

Build typedoc doc 6.2.x

---

extras/docs/themes/typedoc/src/assets/js/src/theme.ts
gulpfile.js

Build typedoc doc 7.1.x

---

extras/docs/themes/sassdoc/assets/js/versioning/tag-versions.req.js
extras/docs/themes/typedoc/src/assets/js/src/versioning/tag-versions.req.js

fix(api-docs-dropdown): do the selection based on the current url location

---

projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.integration.spec.ts
projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-row.component.html
projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-row.component.ts
projects/igniteui-angular/src/lib/grids/row.component.ts

Making added rows unexpandable, fixing template #3879

---

extras/docs/themes/config.json

fix(api-docs-dropdown): change prod jp json link which holds the versions

---

CHANGELOG.md
src/app/autocomplete/autocomplete.sample.html

Improve autocomplete description in changelog

---

projects/igniteui-angular/src/lib/grids/grid-base.component.ts

fix(grid): adjust row editing overlay to be properly aligned with row

---

src/app/app.component.ts

fix(IgxSelect): fix select position in navigation  #3923

---

src/app/select/select.sample.html
src/app/select/select.sample.ts

fix(IgxSelect): Remove excess overlaySettings, use ViewChildren. 

---

projects/igniteui-angular/src/lib/core/styles/components/card/_card-theme.scss

refactor(card): apply the content color to any text element

---

projects/igniteui-angular/src/lib/core/styles/components/progress/_progress-theme.scss
projects/igniteui-angular/src/lib/progressbar/templates/linear-bar.component.html
src/app/progressbar/progressbar.sample.html
src/app/progressbar/progressbar.sample.ts

1. Fix missing class for center
2. Fix position for start and end
3. Fix position for top and bottom
(cherry picked from commit 3dbc26b0ac610068b3244d22c381c3d98c77d651)
Closes #3862

style(linear-bar): Fix text aligment

---

projects/igniteui-angular/src/lib/date-picker/date-picker.component.spec.ts
projects/igniteui-angular/src/lib/date-picker/date-picker.component.ts
projects/igniteui-angular/src/lib/directives/input/input.directive.ts
projects/igniteui-angular/src/lib/time-picker/time-picker.component.spec.ts
projects/igniteui-angular/src/lib/time-picker/time-picker.component.ts

fix(Input): #3641 Remove the '' from input value setter.

---

projects/igniteui-angular/src/lib/directives/autocomplete/autocomplete.directive.spec.ts
projects/igniteui-angular/src/lib/directives/autocomplete/autocomplete.directive.ts
projects/igniteui-angular/src/lib/drop-down/drop-down-item.base.ts
projects/igniteui-angular/src/lib/drop-down/drop-down.component.html
projects/igniteui-angular/src/lib/drop-down/drop-down.component.ts
projects/igniteui-angular/src/lib/select/select-item.component.ts
projects/igniteui-angular/src/lib/select/select.component.html
projects/igniteui-angular/src/lib/select/select.component.ts

Move igxSelect list/item ARIA attributes to base igxDropDown

---

projects/igniteui-angular/src/lib/directives/template-outlet/template_outlet.directive.ts
projects/igniteui-angular/src/lib/grids/grid-base.component.ts
projects/igniteui-angular/src/lib/grids/grid/grid.component.html
projects/igniteui-angular/src/lib/grids/grid/grid.component.ts
projects/igniteui-angular/src/lib/grids/grid/grid.groupby.spec.ts

fix(Grid): Update horizontal virtualization state for rows re-inserted from cache. - 6.2.x

---

projects/igniteui-angular/src/lib/date-picker/calendar-container.component.ts
projects/igniteui-angular/src/lib/date-picker/date-picker.component.ts

fix(date-picker): Fixed import and hide function #3034

---

projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid-row.component.html
projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid.component.html
projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid.component.spec.ts

Set igxForSizePropName for the TreeGrid

---

CHANGELOG.md

docs(changelog): Adding bug fixes for 6.2.9 and 6.2.10

---

CHANGELOG.md

docs(changelog): Adding bug fixes for versions 6.2.6 to 6.2.8

---

CHANGELOG.md

docs(changelog): Adding missing version bug fixes from 7.1.x and 6.2.x

---

projects/igniteui-angular/src/lib/drop-down/drop-down.component.ts
projects/igniteui-angular/src/lib/select/select-positioning-strategy.ts

#3921 igxSelect IE positiong of dropdown with scrolled items

---

projects/igniteui-angular/src/lib/core/styles/components/banner/_banner-theme.scss

fix(banner): banner margin resets too much

---

projects/igniteui-angular/src/lib/combo/combo-dropdown.component.ts

fix(combo): patch keyboard nav down

---

projects/igniteui-angular/src/lib/combo/combo.component.ts

fix(combo): detect changes when clearing filter on list w/o scroll

---

projects/igniteui-angular/src/lib/date-picker/date-picker.component.ts

fix(date-picker): Fix for lazy-loading issue #3988

---

projects/igniteui-angular/src/lib/select/select.component.spec.ts
projects/igniteui-angular/src/lib/select/select.component.ts

Implement EditorProvider interface - igxSelect

---

projects/igniteui-angular/src/lib/combo/combo.component.spec.ts
projects/igniteui-angular/src/lib/combo/combo.component.ts

Implement EditorProvider interface - igxCombo. 

---

.travis.yml

Along with `X.X.X-beta.X` versions, also publish `X.X.X-rc.X` under the `igniteui-angular@next` npm package stream.

chore(npm, ci): include rc-marked versions in the `@next` package stream

---

projects/igniteui-angular/src/lib/services/overlay/position/auto-position-strategy.ts
projects/igniteui-angular/src/lib/services/overlay/position/base-fit-position-strategy.ts
projects/igniteui-angular/src/lib/services/overlay/position/connected-positioning-strategy.ts
projects/igniteui-angular/src/lib/services/overlay/position/elastic-position-strategy.ts
projects/igniteui-angular/src/lib/services/overlay/position/global-position-strategy.ts
projects/igniteui-angular/src/lib/services/overlay/scroll/NoOpScrollStrategy.ts
projects/igniteui-angular/src/lib/services/overlay/scroll/absolute-scroll-strategy.ts
projects/igniteui-angular/src/lib/services/overlay/scroll/block-scroll-strategy.ts
projects/igniteui-angular/src/lib/services/overlay/scroll/close-scroll-strategy.ts
projects/igniteui-angular/src/lib/services/overlay/utilities.ts

Update API comments:
- remove unnecessary inheritances;
- set @hidden and @internal in correct order;
- add classes' descriptions where necessary;
- change some methods accessors so they can appear correctly in API docs;
Closes #

Update API comments for IgxOverlay

---

projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-custom-dialog.component.ts
projects/igniteui-angular/src/lib/grids/filtering/excel-style/grid.excel-style-filtering.component.html
projects/igniteui-angular/src/lib/grids/filtering/excel-style/grid.excel-style-filtering.component.ts

Show custom filter item only of there are filters

---

projects/igniteui-angular/src/lib/grids/column.component.ts
projects/igniteui-angular/src/lib/grids/grid/column.spec.ts

fix(grid): DetectChanges when apply column's formatter via code #3819

---

projects/igniteui-angular/src/lib/combo/combo-dropdown.component.ts
projects/igniteui-angular/src/lib/combo/combo-item.component.ts

fix(combo): introduce proper check for navigation in remote data - 7.1.x

---

projects/igniteui-angular/src/lib/chips/chip.component.html
projects/igniteui-angular/src/lib/chips/chip.spec.ts
projects/igniteui-angular/src/lib/chips/chips-area.spec.ts
projects/igniteui-angular/src/lib/grids/grid/grid-filtering-ui.spec.ts
projects/igniteui-angular/src/lib/grids/grid/grid.groupby.spec.ts

fix(igxChip): Fix chip select icon not showing when selected and selectable is false.

---

projects/igniteui-angular/src/lib/chips/chip.component.html
projects/igniteui-angular/src/lib/chips/chip.spec.ts
projects/igniteui-angular/src/lib/chips/chips-area.spec.ts
projects/igniteui-angular/src/lib/grids/grid/grid-filtering-ui.spec.ts
projects/igniteui-angular/src/lib/grids/grid/grid.groupby.spec.ts

fix(igxChip): Fix chip select icon not showing when selected and selectable is false. 

---

projects/igniteui-angular/src/lib/icon/icon.service.ts

Fix icon service exception

---

projects/igniteui-angular/src/lib/grids/grid-toolbar.component.ts

fix(toolbar): fixing drop-down flickering #4045

---

projects/igniteui-angular/src/lib/grids/grid-toolbar.component.ts

fix(toolbar): making IgxGridToolbar API visible #3974

---

projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-default-expression.component.html
projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-default-expression.component.ts

Convert input value to number for number columns

---

projects/igniteui-angular/src/lib/grids/filtering/excel-style/grid.excel-style-filtering.component.ts
src/app/tree-grid/tree-grid.sample.html

Improve excel style multi-column filtering

---

projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-search.component.html
projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-search.component.ts

Blur checkbox to prevent scroll issues

---

projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-column-moving.component.html
projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-column-moving.component.ts

Reorder column in pinned area when using move buttons

---

projects/igniteui-angular/src/lib/core/styles/components/drop-down/_drop-down-theme.scss

fix(dropdown): remove box shadow when the list is empty #3977

---

projects/igniteui-angular/src/lib/grids/grid/grid.directives.ts

fix(grid): Avoid using closest, not supported on IE11 #4078

---

projects/igniteui-angular/src/lib/grids/filtering/excel-style/grid.excel-style-filtering.component.html

Add maxHeight for the sub menu

---

projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid-navigation.service.ts
projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.navigation.spec.ts

Fix navigation in Hierarchical Grid from grid with more columns to grid with less columns.

---

projects/igniteui-angular/src/lib/directives/autocomplete/autocomplete.directive.spec.ts
projects/igniteui-angular/src/lib/directives/autocomplete/autocomplete.directive.ts

Don't open on arrows and using API open method

---

projects/igniteui-angular/src/lib/select/select-navigation.directive.ts
projects/igniteui-angular/src/lib/select/select.component.spec.ts
projects/igniteui-angular/src/lib/select/select.component.ts

igxSelect - clicking selected item does not close the items container

---

projects/igniteui-angular/src/lib/grids/grid.common.ts

Refactor and fix row editing custom positioning strategy

---

ROADMAP.md

Updating the End date of the Milestone and adding igxSelect Component

Updating the End date and adding igxSelect Component

---

projects/igniteui-angular/src/lib/core/styles/components/grid/_grid-theme.scss
projects/igniteui-angular/src/lib/grids/grid.common.ts

fix(grid): 'fixed'->'absolute' to hide row editing when scrolling #4139

---

projects/igniteui-angular/src/lib/directives/for-of/for_of.directive.ts

Setting correct size of cache for remote for-of type.

---

src/app/app.module.ts
src/app/autocomplete/autocomplete.sample.css
src/app/autocomplete/autocomplete.sample.html
src/app/autocomplete/autocomplete.sample.ts
src/app/autocomplete/data.ts

Update autocomplete sample

---

extras/docs/themes/config.json
extras/docs/themes/sassdoc/index.js
extras/docs/themes/sassdoc/views/index.hbs
extras/docs/themes/typedoc/src/assets/js/src/theme.ts
extras/docs/themes/typedoc/src/layouts/default.hbs

feat(api-docs): apply SEO optimizations

---

projects/igniteui-angular/migrations/common/UpdateChanges.spec.ts
projects/igniteui-angular/src/lib/expansion-panel/expansion-panel.spec.ts
projects/igniteui-angular/src/lib/grids/README.md
projects/igniteui-angular/src/lib/grids/grid/cell.spec.ts
projects/igniteui-angular/src/lib/grids/grid/column-group.spec.ts
projects/igniteui-angular/src/lib/grids/grid/column-moving.spec.ts
projects/igniteui-angular/src/lib/grids/grid/column-pinning.spec.ts
projects/igniteui-angular/src/lib/grids/grid/column-resizing.spec.ts
projects/igniteui-angular/src/lib/grids/grid/column.spec.ts
projects/igniteui-angular/src/lib/grids/grid/grid-filtering-ui.spec.ts
projects/igniteui-angular/src/lib/grids/grid/grid-filtering.spec.ts
projects/igniteui-angular/src/lib/grids/grid/grid-keyBoardNav.spec.ts
projects/igniteui-angular/src/lib/grids/grid/grid-selection.spec.ts
projects/igniteui-angular/src/lib/grids/grid/grid-summary.spec.ts
projects/igniteui-angular/src/lib/grids/grid/grid-toolbar.spec.ts
projects/igniteui-angular/src/lib/grids/grid/grid.component.spec.ts
projects/igniteui-angular/src/lib/grids/grid/grid.crud.spec.ts
projects/igniteui-angular/src/lib/grids/grid/grid.groupby.spec.ts
projects/igniteui-angular/src/lib/grids/grid/grid.pagination.spec.ts
projects/igniteui-angular/src/lib/grids/grid/grid.pinning.spec.ts
projects/igniteui-angular/src/lib/grids/grid/grid.search.spec.ts
projects/igniteui-angular/src/lib/grids/grid/grid.sorting.spec.ts
projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.module.ts
projects/igniteui-angular/src/lib/services/csv/csv-exporter-grid.spec.ts
projects/igniteui-angular/src/lib/services/excel/excel-exporter-grid.spec.ts
src/app/app.module.ts

fix(grid): Removing IgxGridModule.forRoot() from the codebase #4174

---

CHANGELOG.md
projects/igniteui-angular/src/lib/core/enums.ts
projects/igniteui-angular/src/lib/date-picker/README.md
projects/igniteui-angular/src/lib/date-picker/calendar-container.component.ts
projects/igniteui-angular/src/lib/date-picker/date-picker.component.spec.ts
projects/igniteui-angular/src/lib/date-picker/date-picker.component.ts
projects/igniteui-angular/src/lib/date-picker/date-picker.utils.ts
projects/igniteui-angular/src/lib/grids/cell.component.html
projects/igniteui-angular/src/lib/time-picker/README.md
projects/igniteui-angular/src/lib/time-picker/time-picker.common.ts
projects/igniteui-angular/src/lib/time-picker/time-picker.component.html
projects/igniteui-angular/src/lib/time-picker/time-picker.component.spec.ts
projects/igniteui-angular/src/lib/time-picker/time-picker.component.ts
projects/igniteui-angular/src/lib/time-picker/time-picker.directives.ts
projects/igniteui-angular/src/public_api.ts
src/app/date-picker/date-picker.sample.html
src/app/time-picker/time-picker.sample.html
src/app/time-picker/time-picker.sample.ts

fix(date-picker): Renaming of mode values #4143

---

.vscode/settings.json
projects/igniteui-angular/src/lib/data-operations/filtering-condition.spec.ts
projects/igniteui-angular/src/lib/data-operations/filtering-expression.interface.ts
projects/igniteui-angular/src/lib/data-operations/filtering-expressions-tree.ts
projects/igniteui-angular/src/lib/data-operations/filtering-strategy.spec.ts
projects/igniteui-angular/src/lib/grids/grid/grid-filtering-ui.spec.ts
projects/igniteui-angular/src/lib/grids/grid/grid-filtering.spec.ts
projects/igniteui-angular/src/lib/grids/grid/grid.component.spec.ts
projects/igniteui-angular/src/lib/grids/grid/grid.pagination.spec.ts
projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid-filtering.spec.ts
projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid.pipes.ts
projects/igniteui-angular/src/lib/navigation-drawer/navigation-drawer.component.spec.ts
projects/igniteui-angular/src/lib/services/exporter-common/test-methods.spec.ts
projects/igniteui-angular/src/lib/test-utils/grid-functions.spec.ts
projects/igniteui-angular/src/lib/test-utils/helper-utils.spec.ts
projects/igniteui-angular/src/lib/test-utils/tree-grid-components.spec.ts
src/app/grid-groupby/grid-groupby.sample.ts

chore(*): Fixing imports to not import from public_api

---

projects/igniteui-angular/src/lib/core/styles/components/grid/_grid-component.scss
projects/igniteui-angular/src/lib/core/styles/components/grid/_grid-theme.scss

fix(grid): fix grid cells are not aligned with the column headers

---

CHANGELOG.md

chore(docs): Updating changelog.md with missing release notes

---

projects/igniteui-angular/src/lib/drop-down/drop-down-group.component.ts
projects/igniteui-angular/src/lib/select/index.ts
projects/igniteui-angular/src/lib/select/select-group.component.ts
projects/igniteui-angular/src/lib/select/select.component.spec.ts
projects/igniteui-angular/src/lib/select/select.component.ts
projects/igniteui-angular/src/lib/select/select.module.ts
projects/igniteui-angular/src/public_api.ts

Export IgxDropDownGroupComponent

---

projects/igniteui-angular/src/lib/core/styles/components/grid/_grid-component.scss
projects/igniteui-angular/src/lib/core/styles/components/grid/_grid-theme.scss
projects/igniteui-angular/src/lib/grids/grid/grid.component.html
projects/igniteui-angular/src/lib/grids/grid/grid.component.ts

Add icon alignment for expand all button in the groupby grid when the filter row is open

---

projects/igniteui-angular/src/lib/grids/grid-base.component.ts

fix(GroupBy): Fix error thrown when expanding a groupby row. 

---

projects/igniteui-angular/src/lib/grids/filtering/grid-filtering.service.ts

Clear filter if expressionstree is empty

---

.travis.yml
projects/igniteui-angular/migrations/common/UpdateChanges.ts
projects/igniteui-angular/migrations/common/filterSourceDirs.ts
projects/igniteui-angular/migrations/common/util.ts
projects/igniteui-angular/migrations/tsconfig.json
projects/igniteui-angular/migrations/update-7_2_0/index.spec.ts
projects/igniteui-angular/migrations/update-7_2_0/index.ts
projects/igniteui-angular/package.json
projects/igniteui-angular/schematics/interfaces/options.ts
projects/igniteui-angular/schematics/ng-add/add-normalize.ts
projects/igniteui-angular/schematics/ng-add/index.spec.ts
projects/igniteui-angular/schematics/ng-add/index.ts
projects/igniteui-angular/schematics/ng-add/schema.json
projects/igniteui-angular/schematics/tsconfig.json

Add normalize package to 7.2.0 migrations/ng add

---

projects/igniteui-angular/src/lib/drop-down/drop-down-item.base.ts
projects/igniteui-angular/src/lib/select/select.component.ts

chore(IgxSelect): Update API descriptions.  #4171

---

projects/igniteui-angular/src/lib/grids/api.service.ts
projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-custom-dialog.component.ts
projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-default-expression.component.ts
projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-sorting.component.ts
projects/igniteui-angular/src/lib/grids/filtering/excel-style/grid.excel-style-filtering.component.ts
projects/igniteui-angular/src/lib/grids/filtering/grid-filtering.service.ts
projects/igniteui-angular/src/lib/grids/grid-header.component.ts
projects/igniteui-angular/src/lib/grids/hierarchical-grid/child-grid-row.component.ts
projects/igniteui-angular/src/lib/select/select.component.ts
src/app/autocomplete/autocomplete.sample.html

#4208 Fix build/runtime errors in AoT builds and JIT es2015+

---

projects/igniteui-angular/src/lib/grids/grid-base.component.ts
projects/igniteui-angular/src/lib/grids/grid/grid.pinning.spec.ts

igx-grid: `pinned` property doesn't work when `width` property is set together 62x

---

projects/igniteui-angular/src/lib/grids/grid-base.component.ts
projects/igniteui-angular/src/lib/grids/grid/grid.pinning.spec.ts

igx-grid: `pinned` property doesn't work when `width` property is set together. #4125

---

projects/igniteui-angular/src/lib/grids/grid-base.component.ts
projects/igniteui-angular/src/lib/grids/grid/grid.pinning.spec.ts

igx-grid: `pinned` property doesn't work when `width` property is set together 72x

---

projects/igniteui-angular/src/lib/select/select-group.component.ts

#4208
Should resolve the build error in https://github.com/IgniteUI/igniteui-angular-samples/pull/1044

#4208 update IgxSelect leftover item group barrel import (AoT build)

---

projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-column-moving.component.html
projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-column-moving.component.ts
projects/igniteui-angular/src/lib/grids/grid-common.module.ts

Closes #4114
Closes #4113 
Closes #4094

Fix for column moving in grouped columns

---

CHANGELOG.md

Fix broken links in changelog 

---

projects/igniteui-angular/src/lib/directives/text-highlight/text-highlight.directive.spec.ts
projects/igniteui-angular/src/lib/directives/text-highlight/text-highlight.directive.ts

Remove bold fontWeight from the TextHighlight directive

---

projects/igniteui-angular/src/lib/directives/tooltip/tooltip.directive.spec.ts
projects/igniteui-angular/src/lib/directives/tooltip/tooltip.directive.ts

Close IgxTooltip when clicking IgxTooltipTarget - 7.1.x

---

projects/igniteui-angular/src/lib/directives/tooltip/tooltip.directive.spec.ts
projects/igniteui-angular/src/lib/directives/tooltip/tooltip.directive.ts

Close IgxTooltip when clicking IgxTooltipTarget - 7.2.x

---

projects/igniteui-angular/src/lib/grids/cell.component.ts
projects/igniteui-angular/src/lib/grids/grid/cell.spec.ts

fix(grid): Fix DoubleClick while in edit mode #3985

---

src/app/autocomplete/autocomplete.sample.ts

The validation will pass only when there is an exact match for country and attraction.

Refactor autocomplete sample

---

package-lock.json
package.json
src/polyfills.ts

fix(progressbar): add classlist polyfill IE11

---

projects/igniteui-angular/src/lib/combo/combo-dropdown.component.ts
projects/igniteui-angular/src/lib/combo/combo-item.component.ts
projects/igniteui-angular/src/lib/drop-down/drop-down-item.base.ts
projects/igniteui-angular/src/lib/drop-down/drop-down.base.ts
projects/igniteui-angular/src/lib/drop-down/drop-down.component.ts
projects/igniteui-angular/src/lib/grids/filtering/grid-filtering-row.component.html

fix(drop-down): remove usage of old focus + selected accessors

---

projects/igniteui-angular/src/lib/grids/row.component.ts

Expose rowID

---

projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-custom-dialog.component.ts
projects/igniteui-angular/src/lib/grids/filtering/excel-style/grid.excel-style-filtering.component.html
projects/igniteui-angular/src/lib/grids/filtering/excel-style/grid.excel-style-filtering.component.ts
projects/igniteui-angular/src/lib/grids/grid-base.component.ts
projects/igniteui-angular/src/lib/grids/grid-header.component.ts

Remove igxToggle directive from ESF menu

---

projects/igniteui-angular/src/lib/grids/grid-base.component.ts

fix(grids): Fix setting data property manually not being detected as a change.

---

projects/igniteui-angular/src/lib/date-picker/date-picker.component.ts

fix(date picker): dropdown mode scroll strategy

---

projects/igniteui-angular/src/lib/grids/grid-base.component.ts

fix(grid): Fix error thrown when scrolling with mouse after closing a dialog on IE11.

---

package-lock.json
package.json
src/polyfills.ts

fix(progressbar): add polyfill for classlist

---

CHANGELOG.md
projects/igniteui-angular/src/lib/grids/column-chooser-base.ts
projects/igniteui-angular/src/lib/grids/column-hiding.component.html
projects/igniteui-angular/src/lib/grids/column-pinning.component.html
projects/igniteui-angular/src/lib/grids/grid/column-hiding.spec.ts
projects/igniteui-angular/src/lib/grids/grid/column-pinning.spec.ts
projects/igniteui-angular/src/lib/test-utils/grid-base-components.spec.ts

fix(ColumnChoosers): #4102 Adding disableFilter input.

---

projects/igniteui-angular/src/lib/grids/grid-base.component.ts
projects/igniteui-angular/src/lib/grids/grid/column-group.spec.ts

fix(grid): forcing calcwidth on pinning init #4278 - 6.2

---

projects/igniteui-angular/src/lib/grids/grid-base.component.ts
projects/igniteui-angular/src/lib/grids/grid/column-group.spec.ts

fix(grid): forcing calcwidth on pinning init #4278 - 7.1

---

projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid-navigation.service.ts
projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.navigation.spec.ts

fix(HierarchicalGrid):  Fix and test for #4176.

---

projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-sorting.component.ts
projects/igniteui-angular/src/lib/grids/grid-base.component.ts
projects/igniteui-angular/src/lib/grids/grid/grid.component.ts

Don't clear sorting if column is grouped

---

projects/igniteui-angular/src/lib/date-picker/date-picker.component.spec.ts
projects/igniteui-angular/src/lib/date-picker/date-picker.component.ts

fix(date-picker): Fixed calendar templates in date-picker #4223

---

CHANGELOG.md
projects/igniteui-angular/src/lib/calendar/calendar-base.ts
projects/igniteui-angular/src/lib/calendar/calendar.component.html
projects/igniteui-angular/src/lib/calendar/calendar.component.ts
projects/igniteui-angular/src/lib/calendar/days-view/days-view.component.ts
projects/igniteui-angular/src/lib/calendar/month-picker-base.ts
projects/igniteui-angular/src/lib/calendar/month-picker/month-picker.component.html
projects/igniteui-angular/src/lib/calendar/months-view/months-view.component.ts
projects/igniteui-angular/src/lib/calendar/years-view/years-view.component.ts
src/app/calendar-views/calendar-views.sample.html
src/app/calendar-views/calendar-views.sample.ts

igxMonthPicker: fix months view KB navigation

---

projects/igniteui-angular/src/lib/core/styles/components/grid/_grid-theme.scss
projects/igniteui-angular/src/lib/grids/column.component.ts
projects/igniteui-angular/src/lib/grids/grid-base.component.ts
projects/igniteui-angular/src/lib/grids/grid-column-resizer.component.html
projects/igniteui-angular/src/lib/grids/grid-column-resizer.component.ts
projects/igniteui-angular/src/lib/grids/grid-column-resizing.service.ts
projects/igniteui-angular/src/lib/grids/grid-common.module.ts
projects/igniteui-angular/src/lib/grids/grid-header-group.component.html
projects/igniteui-angular/src/lib/grids/grid-header-group.component.ts
projects/igniteui-angular/src/lib/grids/grid.common.ts
projects/igniteui-angular/src/lib/grids/grid/column-moving.spec.ts
projects/igniteui-angular/src/lib/grids/grid/column-resizing.spec.ts
projects/igniteui-angular/src/lib/grids/grid/grid-filtering-ui.spec.ts
projects/igniteui-angular/src/lib/grids/grid/grid.component.html
projects/igniteui-angular/src/lib/grids/grid/grid.component.spec.ts
projects/igniteui-angular/src/lib/grids/grid/grid.component.ts
projects/igniteui-angular/src/lib/grids/grid/grid.groupby.spec.ts
projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.component.html
projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.component.ts
projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid-indentation.spec.ts
projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid.component.html
projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid.component.ts
src/app/grid-performance/grid-performance.sample.html
src/app/hierarchical-grid/hierarchical-grid.sample.html

Refactor grid resize line positioning and display

---

projects/igniteui-angular/src/lib/core/i18n/grid-resources.ts
projects/igniteui-angular/src/lib/core/styles/components/checkbox/_checkbox-theme.scss
projects/igniteui-angular/src/lib/core/styles/components/grid/_excel-filtering-component.scss
projects/igniteui-angular/src/lib/core/styles/components/grid/_excel-filtering-theme.scss
projects/igniteui-angular/src/lib/grids/filtering/excel-style/grid.excel-style-filtering.component.html
projects/igniteui-angular/src/lib/grids/filtering/excel-style/grid.excel-style-filtering.component.ts
projects/igniteui-angular/src/lib/grids/filtering/grid-filtering.service.ts

Closes #4248   
Closes #4269
Closes #4305 
Emit `onFilteringDone` event when `Apply` button is pressed in ESF dialog.
Add button to clear the current column's filter.
Close ESF dialog when escape key is pressed.

Emit onFilterDone and add Clear item

---

projects/igniteui-angular/src/lib/grids/grid-base.component.ts

chore(grid): Updating editCell events event snippets

---

projects/igniteui-angular/src/lib/grids/filtering/grid-filtering-cell.component.ts
projects/igniteui-angular/src/lib/grids/filtering/grid-filtering.service.ts
projects/igniteui-angular/src/lib/grids/grid/grid-filtering.spec.ts

Add property that returns if all columns are in view

---

projects/igniteui-angular/src/lib/grids/grid-navigation.service.ts

Don't move focus from first cell for ESF

---

projects/igniteui-angular/src/lib/grids/column-hiding.component.ts
projects/igniteui-angular/src/lib/grids/grid-base.component.ts
projects/igniteui-angular/src/lib/grids/grid/column-hiding.spec.ts
projects/igniteui-angular/src/lib/test-utils/grid-base-components.spec.ts

fix(ColHiding): #4194 Emit onColumnVisibilityChanged for group columns.

---

projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-column-moving.component.ts

Use visible index of the column

---

projects/igniteui-angular/src/lib/grids/grid/grid-summary.spec.ts
projects/igniteui-angular/src/lib/grids/summaries/grid-summary.service.ts

Recalculate summaries when filtering is applied

---

projects/igniteui-angular/src/lib/tabs/tab-item.component.html
projects/igniteui-angular/src/lib/tabs/tab-item.component.ts
projects/igniteui-angular/src/lib/tabs/tabs-group.component.ts
projects/igniteui-angular/src/lib/tabs/tabs.component.spec.ts
projects/igniteui-angular/src/lib/tabs/tabs.component.ts
projects/igniteui-angular/src/lib/tabs/tabs.directives.ts
src/app/tabs/tabs.sample.html

fix(tabs): Fixed selectedIndex run-time change #4245

---

projects/igniteui-angular/src/lib/grids/grid/grid-summary.spec.ts
projects/igniteui-angular/src/lib/grids/summaries/grid-summary.service.ts

Recalculate summaries when filtering is applied and perform CRUD operations

---

projects/igniteui-angular/schematics/ng-add/index.spec.ts
projects/igniteui-angular/schematics/ng-add/index.ts
projects/igniteui-angular/schematics/utils/dependency-handler.ts

Properly enable polyfills for projects generated by Angular CLI v7.3.x

---

projects/igniteui-angular/src/lib/grids/column.component.ts

fix(column.component): make headerGoupClasses visible for API gen DOC

---

CHANGELOG.md

docs(changelog): Adding bug fixes for 7.1.10

---

projects/igniteui-angular/src/lib/grids/column-hiding.component.ts
projects/igniteui-angular/src/lib/grids/grid-base.component.ts
projects/igniteui-angular/src/lib/grids/grid/column-hiding.spec.ts
projects/igniteui-angular/src/lib/test-utils/grid-base-components.spec.ts

#4194 Emit onColumnVisibilityChanged for group columns.
