- projects/igniteui-angular-i18n/src/i18n/BG/input-resources.ts
- projects/igniteui-angular-i18n/src/i18n/CS/input-resources.ts
- projects/igniteui-angular-i18n/src/i18n/DA/input-resources.ts
- projects/igniteui-angular-i18n/src/i18n/DE/input-resources.ts
- projects/igniteui-angular-i18n/src/i18n/ES/input-resources.ts
- projects/igniteui-angular-i18n/src/i18n/FR/input-resources.ts
- projects/igniteui-angular-i18n/src/i18n/HU/input-resources.ts
- projects/igniteui-angular-i18n/src/i18n/IT/input-resources.ts
- projects/igniteui-angular-i18n/src/i18n/JA/input-resources.ts
- projects/igniteui-angular-i18n/src/i18n/KO/input-resources.ts
- projects/igniteui-angular-i18n/src/i18n/NB/input-resources.ts
- projects/igniteui-angular-i18n/src/i18n/NL/input-resources.ts
- projects/igniteui-angular-i18n/src/i18n/PL/input-resources.ts
- projects/igniteui-angular-i18n/src/i18n/PT/input-resources.ts
- projects/igniteui-angular-i18n/src/i18n/RO/input-resources.ts
- projects/igniteui-angular-i18n/src/i18n/SV/input-resources.ts
- projects/igniteui-angular-i18n/src/i18n/TR/input-resources.ts
- projects/igniteui-angular-i18n/src/i18n/ZH-HANS/input-resources.ts
- projects/igniteui-angular-i18n/src/i18n/ZH-HANT/input-resources.ts
- projects/igniteui-angular/src/lib/core/i18n/input-resources.ts
> chore(iput-group): Remove the unsed igx_input_clear_button string #12882

- CHANGELOG.md
> Add entry for range-picker's showWeekNumbers

- projects/igniteui-angular/src/lib/core/styles/components/stepper/_stepper-theme.scss
> fix(stepper): make the stepper stretch to its parent size.

- projects/igniteui-angular/src/lib/drop-down/drop-down.component.spec.ts
- projects/igniteui-angular/src/lib/drop-down/drop-down.component.ts
- projects/igniteui-angular/src/lib/select/select.component.spec.ts
- projects/igniteui-angular/src/lib/select/select.component.ts
> fix(dropdown,select): owner in selectionChanging event args

- projects/igniteui-angular/src/lib/combo/combo.common.ts
- projects/igniteui-angular/src/lib/combo/combo.component.spec.ts
- projects/igniteui-angular/src/lib/simple-combo/simple-combo.component.spec.ts
- src/app/combo/combo.sample.ts
> fix(combo): trim selected text - 14.2 #12782

- projects/igniteui-angular/src/lib/directives/input/input.directive.ts
> fix(input): file name(s) not cleared on form reset

- projects/igniteui-angular/src/lib/checkbox/checkbox.component.spec.ts
- projects/igniteui-angular/src/lib/checkbox/checkbox.component.ts
- projects/igniteui-angular/src/lib/core/styles/components/checkbox/_checkbox-component.scss
- projects/igniteui-angular/src/lib/core/styles/components/checkbox/_checkbox-theme.scss
- projects/igniteui-angular/src/lib/core/styles/components/radio/_radio-theme.scss
- projects/igniteui-angular/src/lib/directives/radio/radio-group.directive.spec.ts
- projects/igniteui-angular/src/lib/directives/radio/radio-group.directive.ts
- projects/igniteui-angular/src/lib/radio/radio.component.spec.ts
- projects/igniteui-angular/src/lib/radio/radio.component.ts
- projects/igniteui-angular/src/lib/switch/switch.component.spec.ts
- projects/igniteui-angular/src/lib/switch/switch.component.ts
> fix(form-controls): unchecked & indeterminate invalid state

- projects/igniteui-angular/src/lib/grids/common/grid.interface.ts
- projects/igniteui-angular/src/lib/grids/grid-base.directive.ts
- projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.component.ts
> refactor(grids): initial cleanup of ctor props left as public

- CHANGELOG.md
- projects/igniteui-angular/src/lib/grids/README.md
- projects/igniteui-angular/src/lib/grids/common/grid.interface.ts
- projects/igniteui-angular/src/lib/grids/common/pipes.ts
- projects/igniteui-angular/src/lib/grids/grid-base.directive.ts
- projects/igniteui-angular/src/lib/grids/grid/column-moving.spec.ts
- projects/igniteui-angular/src/lib/grids/grid/grid-cell-selection.spec.ts
- projects/igniteui-angular/src/lib/grids/grid/grid-row-editing.spec.ts
- projects/igniteui-angular/src/lib/grids/grid/grid-row-pinning.spec.ts
- projects/igniteui-angular/src/lib/grids/grid/grid-row-selection.spec.ts
- projects/igniteui-angular/src/lib/grids/grid/grid.component.spec.ts
- projects/igniteui-angular/src/lib/grids/grid/grid.component.ts
- projects/igniteui-angular/src/lib/grids/grid/grid.groupby.spec.ts
- projects/igniteui-angular/src/lib/grids/grid/grid.master-detail.spec.ts
- projects/igniteui-angular/src/lib/grids/grid/grid.pagination.spec.ts
- projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.component.ts
- projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.integration.spec.ts
- projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.selection.spec.ts
- projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-grid.component.ts
- projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid-integration.spec.ts
- projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid-search.spec.ts
- projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid-selection.spec.ts
- projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid.component.ts
- projects/igniteui-angular/src/lib/test-utils/grid-samples.spec.ts
- src/app/grid-cell-api/grid-cell-api.sample.html
- src/app/grid-cell-api/grid-cell-api.sample.ts
> chore(*): remove deprecated props, fix tests and samples

- projects/igniteui-angular/migrations/update-15_1_0/index.spec.ts
- projects/igniteui-angular/migrations/update-15_1_0/index.ts
> fix(migrations): duplicate card actions migrations

- projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid-add-row-ui.spec.ts
- projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid.component.ts
> fix(tree-grid): correct foreignKey value in rowAdd event args - 14.2.x

- projects/igniteui-angular/src/lib/grids/grid-base.directive.ts
- projects/igniteui-angular/src/lib/grids/grid/grid-filtering-ui.spec.ts
- src/app/grid-column-groups/grid-column-groups.sample.css
- src/app/grid-column-groups/grid-column-groups.sample.html
- src/app/grid-column-groups/grid-column-groups.sample.ts
> fix(grid): Fix filtering row not included correctly into header row size calculation.

- projects/igniteui-angular/package.json
Merge before the official 16.0.0 release
> chore(schematics): put official release version

- projects/igniteui-angular/src/lib/core/styles/components/date-picker/_date-picker-theme.scss
> fix(date-picker): Remove color overrides

- projects/igniteui-angular/src/lib/core/styles/components/avatar/_avatar-theme.scss
- projects/igniteui-angular/src/lib/core/styles/themes/schemas/light/_avatar.scss
> Bringing back deleted avatar size property.

- projects/igniteui-angular/src/lib/grids/grid-base.directive.ts
> chore(*): document clearCellSelection 14.2.x

- projects/igniteui-angular/src/lib/grids/grid-base.directive.ts
> chore(*): document clearCellSelection 15.1.x

- projects/igniteui-angular/src/lib/grids/grid-base.directive.ts
> Document clear cell selection 16.0.x

- projects/igniteui-angular/src/lib/grids/grid/grid-validation.service.ts
- projects/igniteui-angular/src/lib/grids/grid/grid-validation.spec.ts
> fix(validation): add form control for dynamically added columns - 15.1.x

- package-lock.json
- package.json
Closes #https://github.com/IgniteUI/typedoc-plugin-localization/issues/71
> chore(*): Update typedoc plugin and theme

- projects/igniteui-angular/src/lib/core/styles/components/stepper/_stepper-theme.scss
> fix(stepper) stretch the step content to take it's parent size.

- projects/igniteui-angular/src/lib/core/styles/components/stepper/_stepper-theme.scss
> fix(stepper): stretch the step content to take it's parent size.

- projects/igniteui-angular/src/lib/core/styles/components/switch/_switch-component.scss
- projects/igniteui-angular/src/lib/core/styles/components/switch/_switch-theme.scss
- projects/igniteui-angular/src/lib/core/styles/themes/schemas/dark/_switch.scss
- projects/igniteui-angular/src/lib/core/styles/themes/schemas/light/_switch.scss
> fix(switch): wrong colors in invalid state

- projects/igniteui-angular/src/lib/core/styles/themes/generators/_base.scss
Adding an internal callback to allow for customization of the theme name and selector (for now explicitly for Elements, see #12974 for more details). 
Not sure if there are some tests I should update or add, can use some help on that one. Will also try to test if there's any meaningful perf impact.
> refactor(themes): add an internal handler option to transform theme maps

- projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid.component.spec.ts
- projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid.pipes.ts
> Add data null check in the treeGridNormalizeRecord pipe - 15.1

- projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid.component.spec.ts
- projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid.pipes.ts
> Add data null check in the treeGridNormalizeRecord pipe - 14.2

- projects/igniteui-angular/src/lib/services/csv/char-separated-value-data.ts
- projects/igniteui-angular/src/lib/services/csv/csv-exporter-grid.spec.ts
- projects/igniteui-angular/src/lib/services/csv/csv-exporter.ts
- projects/igniteui-angular/src/lib/test-utils/grid-samples.spec.ts
> Download a single file when exporting an empty grid to csv - 15.1.x

- projects/igniteui-angular/src/lib/services/csv/char-separated-value-data.ts
- projects/igniteui-angular/src/lib/services/csv/csv-exporter-grid.spec.ts
- projects/igniteui-angular/src/lib/services/csv/csv-exporter.ts
- projects/igniteui-angular/src/lib/test-utils/grid-samples.spec.ts
> Download a single file when exporting an empty grid to csv - 16.0.x

- projects/igniteui-angular/src/lib/grids/common/grid.interface.ts
> docs(grid): mark GridType perPage and page as hidden internal

- projects/igniteui-angular/src/lib/core/styles/components/grid/_excel-filtering-theme.scss
> fix(grid): advanced-filtering-styling-issues

- projects/igniteui-angular/src/lib/directives/radio/radio-group.directive.spec.ts
- projects/igniteui-angular/src/lib/directives/radio/radio-group.directive.ts
- projects/igniteui-angular/src/lib/radio/radio.component.ts
Closes https://github.com/IgniteUI/igniteui-angular/issues/12897
Closes https://github.com/IgniteUI/igniteui-angular/issues/12944
> fix(radio): buttons with falsy values are initially selected

- projects/igniteui-angular/src/lib/core/styles/components/grid/_grid-theme.scss
Reverts IgniteUI/igniteui-angular#12994
> Revert "fix - Excel style filtering is not shown on top or clipped -- master"

- projects/igniteui-angular/src/lib/core/styles/components/grid/_grid-theme.scss
Reverts IgniteUI/igniteui-angular#13001
> Revert "fix - Excel style filtering is not shown on top or clipped --15.1"

- projects/igniteui-angular/src/lib/core/styles/components/grid/_grid-theme.scss
Reverts IgniteUI/igniteui-angular#12999
> Revert "fix - Excel style filtering is not shown on top or clipped -- 14.2"

- projects/igniteui-angular/src/lib/core/styles/components/banner/_banner-component.scss
- projects/igniteui-angular/src/lib/core/styles/components/banner/_banner-theme.scss
> fix(banner): styling doesn't apply in cosy and compact modes

- package-lock.json
- package.json
- projects/igniteui-angular/package.json
- projects/igniteui-angular/src/lib/core/styles/components/grid/_grid-theme.scss
> fix(grid): cell editing missing property

- projects/igniteui-angular/src/lib/core/styles/components/button/_button-theme.scss
> fix(button): remove icon color override.

- projects/igniteui-angular/src/lib/directives/drag-drop/drag-drop.directive.ts
- projects/igniteui-angular/src/lib/directives/drag-drop/drag-drop.spec.ts
> fix(drag): Add handling for ghostTemplates that have display contents.

- projects/igniteui-angular/src/lib/grids/grid-base.directive.ts
- projects/igniteui-angular/src/lib/grids/grid/grid.component.ts
> fix(grids): unsafe access of content query from other public accessors

- projects/igniteui-angular/src/lib/core/styles/components/combo/_combo-theme.scss
- projects/igniteui-angular/src/lib/core/styles/components/select/_select-theme.scss
- projects/igniteui-angular/src/lib/core/styles/themes/schemas/light/_combo.scss
- projects/igniteui-angular/src/lib/core/styles/themes/schemas/light/_select.scss
> fix(combo, select): incorrect toggle button colors

- projects/igniteui-angular/src/lib/core/styles/components/button-group/_button-group-theme.scss
> fix(button-group): selected item border color

- projects/igniteui-angular/src/lib/grids/grid/grid-mrl-keyboard-nav.spec.ts
> test(mrl): Add debounce time on arrow navigation.

- projects/igniteui-angular/src/lib/core/styles/components/drop-down/_drop-down-component.scss
- projects/igniteui-angular/src/lib/core/styles/components/drop-down/_drop-down-theme.scss
> fix(themes): dropdown doesn't work with --ig-size

- projects/igniteui-angular/src/lib/core/styles/themes/generators/_bootstrap.scss
- projects/igniteui-angular/src/lib/core/styles/themes/generators/_fluent.scss
- projects/igniteui-angular/src/lib/core/styles/themes/generators/_indigo.scss
> fix(themes): set roundness to null for non-material presets

- projects/igniteui-angular/src/lib/core/styles/components/input/_input-group-theme.scss
> fix(label-directive): label position

- projects/igniteui-angular/src/lib/grids/grid-base.directive.ts
> fix(grid): also refresh group area state on columns change

- projects/igniteui-angular/src/lib/core/styles/components/input/_input-group-theme.scss
> fix(input): icons don't respond to size changes

- projects/igniteui-angular/src/lib/combo/combo.common.ts
- projects/igniteui-angular/src/lib/combo/combo.component.spec.ts
- projects/igniteui-angular/src/lib/date-picker/date-picker.component.spec.ts
- projects/igniteui-angular/src/lib/date-picker/date-picker.component.ts
- projects/igniteui-angular/src/lib/date-range-picker/date-range-picker.component.spec.ts
- projects/igniteui-angular/src/lib/date-range-picker/date-range-picker.component.ts
- projects/igniteui-angular/src/lib/directives/input/input.directive.spec.ts
- projects/igniteui-angular/src/lib/directives/input/input.directive.ts
- projects/igniteui-angular/src/lib/select/select.component.spec.ts
- projects/igniteui-angular/src/lib/select/select.component.ts
- projects/igniteui-angular/src/lib/simple-combo/simple-combo.component.spec.ts
- projects/igniteui-angular/src/lib/time-picker/time-picker.component.spec.ts
- projects/igniteui-angular/src/lib/time-picker/time-picker.component.ts
> fix(editors): update validity state sequence - 15.1.x

- projects/igniteui-angular/src/lib/combo/combo.common.ts
- projects/igniteui-angular/src/lib/combo/combo.component.spec.ts
- projects/igniteui-angular/src/lib/date-picker/date-picker.component.spec.ts
- projects/igniteui-angular/src/lib/date-picker/date-picker.component.ts
- projects/igniteui-angular/src/lib/date-range-picker/date-range-picker.component.spec.ts
- projects/igniteui-angular/src/lib/date-range-picker/date-range-picker.component.ts
- projects/igniteui-angular/src/lib/directives/input/input.directive.spec.ts
- projects/igniteui-angular/src/lib/directives/input/input.directive.ts
- projects/igniteui-angular/src/lib/select/select.component.spec.ts
- projects/igniteui-angular/src/lib/select/select.component.ts
- projects/igniteui-angular/src/lib/simple-combo/simple-combo.component.spec.ts
- projects/igniteui-angular/src/lib/time-picker/time-picker.component.spec.ts
- projects/igniteui-angular/src/lib/time-picker/time-picker.component.ts
> fix(editors): update validity state sequence - 14.2.x

- projects/igniteui-angular/src/lib/core/styles/components/button-group/_button-group-theme.scss
> fix(button-group): border radius not working correctly.

- projects/igniteui-angular/src/lib/simple-combo/simple-combo.component.spec.ts
> Fix flickering test in simple combo

- projects/igniteui-angular/src/lib/grids/common/strategy.ts
- projects/igniteui-angular/src/lib/grids/grid/grid.sorting.spec.ts
> fix(grid): Non-destructive datetime sort operation

- projects/igniteui-angular/src/lib/core/styles/components/input/_input-group-component.scss
- projects/igniteui-angular/src/lib/core/styles/components/input/_input-group-theme.scss
> fix(input-group): fluent theme textarea styling in safari.

- projects/igniteui-angular/src/lib/grids/grid-navigation.service.ts
- projects/igniteui-angular/src/lib/grids/grid/grid-filtering-ui.spec.ts
> fix(grid,kb-nav): prevent error on arrow key in filter UI row - 14.2.x

- projects/igniteui-angular/src/lib/grids/grid-navigation.service.ts
- projects/igniteui-angular/src/lib/grids/grid/grid-filtering-ui.spec.ts
> fix(grid,kb-nav): prevent error on arrow key in filter UI row - 15.1.x

- CHANGELOG.md
- projects/igniteui-angular/src/lib/directives/for-of/for_of.directive.spec.ts
- projects/igniteui-angular/src/lib/directives/for-of/for_of.directive.ts
> feat(igxForOf): Add support for template referencing of bound data.

- projects/igniteui-angular/src/lib/core/styles/components/input/_input-group-theme.scss
- src/app/date-range/date-range.sample.ts
> fix(themes): date-range picker doesn't get theme

- projects/igniteui-angular/src/lib/buttonGroup/buttonGroup.component.ts
- projects/igniteui-angular/src/lib/buttonGroup/buttongroup.component.spec.ts
> fix(button-group): firing the selected event only on user interaction

- projects/igniteui-angular/src/lib/grids/grid-base.directive.ts
- projects/igniteui-angular/src/lib/grids/grid/column-resizing.spec.ts
- projects/igniteui-angular/src/lib/grids/resizing/resize-handle.directive.ts
- projects/igniteui-angular/src/lib/grids/resizing/resizing.service.ts
IgniteUI/igniteui-webcomponents/issues/590
> fix(resizing): Set resize cursor initially and not on mouse hover, for not all columns get the inline style on width auto.

- projects/igniteui-angular/src/lib/combo/combo.common.ts
- projects/igniteui-angular/src/lib/combo/combo.component.spec.ts
- projects/igniteui-angular/src/lib/combo/combo.component.ts
- projects/igniteui-angular/src/lib/simple-combo/simple-combo.component.ts
> fix(combo): add selected items to the input when data is loaded - 16.0.x

- projects/igniteui-angular/src/lib/combo/combo.common.ts
- projects/igniteui-angular/src/lib/combo/combo.component.spec.ts
- projects/igniteui-angular/src/lib/combo/combo.component.ts
- projects/igniteui-angular/src/lib/simple-combo/simple-combo.component.ts
> fix(combo): add selected items to the input when data is loaded - 15.1.x

- projects/igniteui-angular/src/lib/combo/combo.common.ts
- projects/igniteui-angular/src/lib/combo/combo.component.spec.ts
- projects/igniteui-angular/src/lib/combo/combo.component.ts
- projects/igniteui-angular/src/lib/simple-combo/simple-combo.component.ts
> fix(combo): add selected items to the input when data is loaded - master

- projects/igniteui-angular/src/lib/core/styles/components/radio/_radio-theme.scss
> fix(radio): unexpected margin when the radio buttons wrap on a second line

- projects/igniteui-angular/src/lib/core/styles/components/button-group/_button-group-theme.scss
> fix(button-group): fix nth-child() usage.

- projects/igniteui-angular/src/lib/directives/radio/radio-group.directive.ts
- projects/igniteui-angular/src/lib/radio/radio.component.ts
> fix(radio-group): wrong dirty state

- projects/igniteui-angular/src/lib/core/styles/components/input/_input-group-component.scss
- projects/igniteui-angular/src/lib/core/styles/components/input/_input-group-theme.scss
> fix(input-group): fluent textarea jumping on focus

- projects/igniteui-angular/src/lib/core/styles/components/grid/_pivot-data-selector-theme.scss
> fix(pivot-selector): cropped box shadow of bootstrap input

- projects/igniteui-angular/src/lib/core/styles/themes/generators/_bootstrap.scss
- projects/igniteui-angular/src/lib/core/styles/themes/generators/_fluent.scss
- projects/igniteui-angular/src/lib/core/styles/themes/generators/_indigo.scss
> fix(themes): generators set roundness to 1

- projects/igniteui-angular/src/lib/core/styles/components/button/_button-theme.scss
- projects/igniteui-angular/src/lib/core/styles/components/chip/_chip-theme.scss
- projects/igniteui-angular/src/lib/core/styles/components/grid/_grid-theme.scss
- projects/igniteui-angular/src/lib/core/styles/components/grid/_pivot-data-selector-theme.scss
> fix(themes): icon sizing discrepancies

- projects/igniteui-angular/src/lib/buttonGroup/buttonGroup.component.ts
- projects/igniteui-angular/src/lib/buttonGroup/buttongroup.component.spec.ts
> fix(button-group): deselected event fired on programmatic deselection

- CHANGELOG.md
- projects/igniteui-angular/src/lib/badge/badge.component.html
- projects/igniteui-angular/src/lib/badge/badge.component.ts
- projects/igniteui-angular/src/lib/core/styles/components/badge/_badge-theme.scss
- src/app/badge/badge.sample.html
- src/app/badge/badge.sample.scss
- src/app/badge/badge.sample.ts
> feat(badge): support material icons extended

- projects/igniteui-angular/src/lib/core/styles/components/avatar/_avatar-theme.scss
- projects/igniteui-angular/src/lib/core/styles/components/badge/_badge-theme.scss
- src/app/avatar/avatar.sample.html
> fix(avatar, badge): shape not working

- projects/igniteui-angular/src/lib/date-range-picker/public_api.ts
This was most likely regressed during the update to standalone components.
(cherry picked from commit cb642c7801b4952cb4db1de472b7c66ca17c9902)
> Export picker toggle component - 16.0.x

- projects/igniteui-angular/src/lib/date-range-picker/public_api.ts
This was most likely regressed during the update to standalone components.
> Export picker toggle component

- CHANGELOG.md
- projects/igniteui-angular/src/lib/combo/combo.component.spec.ts
- projects/igniteui-angular/src/lib/combo/combo.pipes.ts
- projects/igniteui-angular/src/lib/combo/public_api.ts
> feat(combo): Exported filter strategy for non-diacritic filter (#13071)

- CHANGELOG.md
- package-lock.json
- package.json
- projects/igniteui-angular/package.json
- projects/igniteui-angular/src/lib/core/styles/components/_index.scss
- projects/igniteui-angular/src/lib/core/styles/components/input/_input-group-theme.scss
- projects/igniteui-angular/src/lib/core/styles/components/label/_label-component.scss
- projects/igniteui-angular/src/lib/core/styles/components/label/_label-theme.scss
- projects/igniteui-angular/src/lib/core/styles/themes/_core.scss
- projects/igniteui-angular/src/lib/core/styles/themes/generators/_base.scss
> feat(themes): add standalone label theme

- projects/igniteui-angular/src/lib/badge/badge.component.html
- src/app/badge/badge.sample.html
- src/app/badge/badge.sample.ts
> feat(badge): support icon projection

- projects/igniteui-angular/src/lib/combo/combo.common.ts
> Change this.valueKey check to not throw error

- projects/igniteui-angular/src/lib/directives/drag-drop/drag-drop.directive.ts
Apply fix done performed in #12966, but since it became enhancement it was not applied to other versions.
Closes #13302
> fix(drag): Fix drag directive eating up event for children elements.

- projects/igniteui-angular/src/lib/grids/common/events.ts
- projects/igniteui-angular/src/lib/grids/grid-base.directive.ts
> Make IMatchInfoCache internal - master

- package-lock.json
- package.json
- projects/igniteui-angular/package.json
- projects/igniteui-angular/src/lib/core/styles/components/avatar/_avatar-theme.scss
- projects/igniteui-angular/src/lib/core/styles/components/button/_button-theme.scss
- projects/igniteui-angular/src/lib/core/styles/components/chip/_chip-theme.scss
- projects/igniteui-angular/src/lib/core/styles/components/drop-down/_drop-down-theme.scss
- projects/igniteui-angular/src/lib/core/styles/components/grid-toolbar/_grid-toolbar-theme.scss
- projects/igniteui-angular/src/lib/core/styles/components/grid/_grid-theme.scss
- projects/igniteui-angular/src/lib/core/styles/components/icon/_icon-theme.scss
- projects/igniteui-angular/src/lib/core/styles/components/input/_input-group-theme.scss
- projects/igniteui-angular/src/lib/core/styles/components/paginator/_paginator-theme.scss
- projects/igniteui-angular/src/lib/core/styles/components/tree/_tree-component.scss
- projects/igniteui-angular/src/lib/core/styles/components/tree/_tree-theme.scss
- projects/igniteui-angular/src/lib/tree/tree-node/tree-node.component.ts
> refactor(*): consume sizing from schemas

- projects/igniteui-angular/src/lib/core/styles/components/input/_input-group-theme.scss
- projects/igniteui-angular/src/lib/select/select.component.spec.ts
- src/app/input-group/input-group.sample.scss
> fix(input): styling inconsistencies

- projects/igniteui-angular/src/lib/core/styles/components/input/_input-group-component.scss
- projects/igniteui-angular/src/lib/core/styles/components/input/_input-group-theme.scss
> fix(input-group): remove box shadow from bootstrap bundle on focus

- projects/igniteui-angular/src/lib/directives/radio/radio-group.directive.spec.ts
- projects/igniteui-angular/src/lib/directives/radio/radio-group.directive.ts
> fix(radio-group): checkbox matching initial value not selected

- projects/igniteui-angular/src/lib/core/styles/components/calendar/_calendar-theme.scss
- projects/igniteui-angular/src/lib/core/styles/components/date-picker/_date-picker-theme.scss
> fix(date-picker): fix variables scope

- projects/igniteui-angular/src/lib/directives/drag-drop/drag-drop.directive.ts
- src/app/drag-drop/drag-drop.sample.html
- src/app/drag-drop/drag-drop.sample.scss
- src/app/drag-drop/drag-drop.sample.ts
> fix(drag): Fix ghost template not detecting changes automatically. 

- projects/igniteui-angular/src/lib/splitter/splitter-pane/splitter-pane.component.ts
- projects/igniteui-angular/src/lib/splitter/splitter.component.ts
> fix(splitter): improving sizing calculations in percent splitter #13252 - 16.0

- projects/igniteui-angular/src/lib/splitter/splitter-pane/splitter-pane.component.ts
- projects/igniteui-angular/src/lib/splitter/splitter.component.ts
> fix(splitter): improving sizing calculations in percent splitter #13252 - 15.1

- projects/igniteui-angular/src/lib/services/exporter-common/base-export-service.ts
> fix(excel-export): fix pivotGrid column preparing - 15.1.x

- projects/igniteui-angular/src/lib/services/exporter-common/base-export-service.ts
> fix(excel-export): fix pivotGrid column preparing - 16.0.x

- projects/igniteui-angular/src/lib/services/exporter-common/base-export-service.ts
> fix(excel-export): fix pivotGrid column preparing - master

- projects/igniteui-angular/src/lib/core/styles/components/grid/_grid-theme.scss
Closes [#3376](https://github.com/IgniteUI/igniteui-angular-samples/issues/3376)
> fix(grid): updated z-index of row ghost to be above all grid elements

- projects/igniteui-angular/src/lib/core/styles/components/grid/_grid-theme.scss
Closes [#3376](https://github.com/IgniteUI/igniteui-angular-samples/issues/3376)
> fix(grid): updated z-i of ghost to be above all

- projects/igniteui-angular/src/lib/core/styles/components/grid/_grid-theme.scss
Closes [#3376](https://github.com/IgniteUI/igniteui-angular-samples/issues/3376)
> fix(grid): updated z-index of ghost to be above all other elements

- projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid-base.directive.ts
> fix(row-island): columnInit not emitting if autoGenerate=false - 15.1.x

- projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid-base.directive.ts
> fix(row-island): columnInit not emitting if autoGenerate=false - 16.0.x

- projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid-base.directive.ts
- projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.component.ts
> fix(row-island): columnInit not emitting if autoGenerate=false

- projects/igniteui-angular/src/lib/buttonGroup/buttonGroup.component.ts
- projects/igniteui-angular/src/lib/buttonGroup/buttongroup.component.spec.ts
- projects/igniteui-angular/src/lib/directives/button/button.directive.ts
- projects/igniteui-angular/src/lib/navigation-drawer/navigation-drawer.component.spec.ts
- projects/igniteui-angular/src/lib/services/overlay/overlay.ts
- projects/igniteui-angular/src/lib/test-utils/routing-view-components.spec.ts
- projects/igniteui-angular/src/lib/test-utils/tabs-components.spec.ts
> test(*): cleaning up some warnings from tests

- projects/igniteui-angular/package.json
> feat(*): bumping material-icons-extended version

- package-lock.json
- package.json
- projects/igniteui-angular/package.json
> chore(*): bumping material-icons-extended version

- projects/igniteui-angular/src/lib/grids/columns/column.component.ts
- projects/igniteui-angular/src/lib/grids/grid-base.directive.ts
- projects/igniteui-angular/src/lib/grids/grid/grid.pinning.spec.ts
> fix(grid: column-pinning): working pinColumn with indexes for the last position

- CHANGELOG.md
- projects/igniteui-angular/src/lib/buttonGroup/buttonGroup.component.ts
- projects/igniteui-angular/src/lib/buttonGroup/buttongroup.component.spec.ts
> fix(button-group): making selected and deselected events cancellable

- projects/igniteui-angular/src/lib/core/styles/components/icon/_icon-theme.scss
Enhance the specificity of the "igx-icon" styles to avoid the use of "!important" when external classes are incorporated into the component.
Closes #13394
> refactor(icon): Use em for the width and the height of the igx-icon.

- .github/workflows/nodejs.yml
> test(*): rolling back to a working 20.x version

- projects/igniteui-angular/src/lib/grids/common/crud.service.ts
- projects/igniteui-angular/src/lib/grids/grid-base.directive.ts
- projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-grid.component.ts
> fix(grid): add return type and return value to endEdit method

- projects/igniteui-angular/src/lib/grids/columns/column.component.ts
- projects/igniteui-angular/src/lib/grids/grid/column-group.spec.ts
> fix(grid): round column width when set in percentages - 15.1.x

- projects/igniteui-angular/migrations/common/tsUtils.ts
> fix(migrations): member lookup error when constructor is present

- projects/igniteui-angular/src/lib/grids/grid-base.directive.ts
- src/app/grid-selection/grid-selection.sample.html
- src/app/grid-selection/grid-selection.sample.ts
> Fix: IgxGrid: Horizontal scrollbar is displayed when row selection is enabled --16.0.x

- projects/igniteui-angular/src/lib/grids/grid-base.directive.ts
- src/app/grid-selection/grid-selection.sample.html
- src/app/grid-selection/grid-selection.sample.ts
> Fix: IgxGrid: Horizontal scrollbar is displayed when row selection is enabled

- projects/igniteui-angular/src/lib/grids/grid-base.directive.ts
Related to https://infragistics.visualstudio.com/NetAdvantage/_workitems/edit/26416/
> Suppress endEdit only for blazor output.

- projects/igniteui-angular/src/lib/grids/common/grid.interface.ts
Related to https://infragistics.visualstudio.com/NetAdvantage/_workitems/edit/26415/
> Unsuppress row edit action context implicit property. Add type.

- projects/igniteui-angular/src/lib/data-operations/groupby-record.interface.ts
- projects/igniteui-angular/src/lib/grids/common/grid.interface.ts
- projects/igniteui-angular/src/lib/grids/toolbar/grid-toolbar-exporter.component.ts
> tag some objects to not be plain objects for react gen

- package-lock.json
- package.json
- projects/igniteui-angular/package.json
- projects/igniteui-angular/src/lib/core/styles/components/grid/_excel-filtering-theme.scss
- projects/igniteui-angular/src/lib/core/styles/components/grid/_grid-theme.scss
> feat(grid): provide styling properties for ESF

- package-lock.json
- package.json
- projects/igniteui-angular/package.json
- projects/igniteui-angular/src/lib/core/styles/components/checkbox/_checkbox-theme.scss
Closes #13446
depends on  https://github.com/IgniteUI/igniteui-theming/pull/111
> fix(checkbox): fix sub pixel rendering for checkbox border

- projects/igniteui-angular/src/lib/slider/slider.component.spec.ts
- projects/igniteui-angular/src/lib/slider/slider.component.ts
> fix(slider): properly adjusting bounds #13403

- projects/igniteui-angular/src/lib/list/public_api.ts
- add missing `IgxListBaseDirective` export for backward compatibility;
Closes #13484
> chore(list): add missing export

- CHANGELOG.md
- projects/igniteui-angular/migrations/update-16_1_0/index.spec.ts
- projects/igniteui-angular/migrations/update-16_1_0/index.ts
- projects/igniteui-angular/src/lib/buttonGroup/buttonGroup.component.ts
- projects/igniteui-angular/src/lib/buttonGroup/buttongroup.component.spec.ts
- projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-date-expression.component.html
- projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-default-expression.component.html
- projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-moving.component.html
- projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-sorting.component.html
- projects/igniteui-angular/src/lib/query-builder/query-builder.component.html
- src/app/buttonGroup/buttonGroup.sample.html
- src/app/buttonGroup/buttonGroup.sample.ts
- src/app/drop-down/drop-down.sample.html
- src/app/grid-column-selection/grid-column-selection.sample.html
- src/app/grid-external-filtering/grid-external-filtering.sample.html
- src/app/grid-filtering/grid-filtering.sample.html
- src/app/grid-finjs/controllers.component.html
> feat(button-group): adding selectionMode property

- projects/igniteui-angular/src/lib/grids/grid-base.directive.ts
> chore(grid-pinning): add mustSetInCodePlatforms for pinning config

- projects/igniteui-angular/src/lib/data-operations/filtering-condition.ts
- projects/igniteui-angular/src/lib/grids/summaries/grid-summary.ts
Related to: https://infragistics.visualstudio.com/NetAdvantage/_workitems/edit/26401/
> Remove full suppress for summary operands. Suppress only for blazor.

- projects/igniteui-angular/src/lib/tree/public_api.ts
- projects/igniteui-angular/src/lib/tree/tree-navigation.spec.ts
- projects/igniteui-angular/src/lib/tree/tree-node/tree-node.component.ts
- projects/igniteui-angular/src/lib/tree/tree-samples.spec.ts
- src/app/tree/tree.sample.html
- src/app/tree/tree.sample.ts
> fix(tree): expand indicator directive #13502

- projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.component.ts
- projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.spec.ts
> fix(hierarchical-grid): add setter for child grid row data - master

- projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.component.ts
- projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.spec.ts
> fix(hierarchical-grid): add setter for child grid row data - 16.0.x

- projects/igniteui-angular-i18n/package.json
- projects/igniteui-angular/package.json
#13467
The fix comes with a task in the licensed release pipeline, which replaces "igniteui-angular" with "@infragistics/igniteui-angular"
> fix(migrations): remove licensed package from group

- projects/igniteui-angular/src/lib/buttonGroup/buttonGroup.component.ts
> fix(button-group): deprecated multiSelection property

- package-lock.json
- package.json
- projects/igniteui-angular/package.json
- projects/igniteui-angular/src/lib/grids/grid-base.directive.ts
> chore(grids): bump watermark version

- projects/igniteui-angular/src/lib/badge/badge.component.html
> fix(badge): value of 0 is not rendered

- projects/igniteui-angular/src/lib/avatar/avatar.component.spec.ts
- projects/igniteui-angular/src/lib/avatar/avatar.component.ts
- projects/igniteui-angular/src/lib/core/styles/components/avatar/_avatar-component.scss
- projects/igniteui-angular/src/lib/core/styles/components/avatar/_avatar-theme.scss
- src/app/avatar/avatar.sample.html
> fix(avatar): size attribute should be more specific

- projects/igniteui-angular/src/lib/checkbox/checkbox.component.ts
- projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-search.component.ts
- projects/igniteui-angular/src/lib/switch/switch.component.html
- projects/igniteui-angular/src/lib/switch/switch.component.spec.ts
- projects/igniteui-angular/src/lib/switch/switch.component.ts
> refactor(switch): inherit from IgxCheckbox

- projects/igniteui-angular/src/lib/grids/columns/column.component.ts
> Set summaries prop to be treated as ref.

- projects/igniteui-angular/src/lib/grids/common/grid.interface.ts
Resolves https://infragistics.visualstudio.com/NetAdvantage/_workitems/edit/26920/
> Suppress row in CellType only for Blazor.

- SECURITY.md
> chore(*): Create SECURITY.md

- projects/igniteui-angular/src/lib/grids/columns/column-group.component.ts
Related to: https://infragistics.visualstudio.com/NetAdvantage/_workitems/edit/27337
> Unsuppress col group collapsible prop.

- projects/igniteui-angular/src/lib/data-operations/filtering-condition.ts
- projects/igniteui-angular/src/lib/data-operations/filtering-expression.interface.ts
- projects/igniteui-angular/src/lib/data-operations/grouping-expression.interface.ts
- projects/igniteui-angular/src/lib/data-operations/sorting-strategy.ts
- projects/igniteui-angular/src/lib/grids/common/strategy.ts
- projects/igniteui-angular/src/lib/grids/common/types.ts
- projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-grid.interface.ts
- projects/igniteui-angular/src/lib/grids/summaries/grid-summary.ts
> Remove marshal by value for some types can be translated to interfaces.

- CHANGELOG.md
- package-lock.json
- package.json
- projects/igniteui-angular/package.json
- projects/igniteui-angular/src/lib/core/utils.ts
- src/app/drag-drop/shadow-dom-grid/shadow-grid-sample.scss
- src/styles/_demo-theme.scss
- src/styles/styles.scss
> refactor(theming): add option to configure base font-size

- projects/igniteui-angular/src/lib/core/styles/components/snackbar/_snackbar-component.scss
- projects/igniteui-angular/src/lib/core/styles/components/snackbar/_snackbar-theme.scss
- projects/igniteui-angular/src/lib/snackbar/snackbar.component.html
- projects/igniteui-angular/src/lib/snackbar/snackbar.component.spec.ts
- projects/igniteui-angular/src/lib/snackbar/snackbar.component.ts
> fix(snackbar): use igxButton

- projects/igniteui-angular/src/lib/grids/common/strategy.ts
- projects/igniteui-angular/src/lib/grids/grid/grid.component.ts
- projects/igniteui-angular/src/lib/grids/grid/grid.groupby.spec.ts
> Return updated values when groupingDone is emitted

- projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-conditional-filter.component.html
- projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-conditional-filter.component.ts
> fix(esf): conditional filter drop down items focus - 16.1.x

- projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-conditional-filter.component.html
- projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-conditional-filter.component.ts
Closes https://github.com/IgniteUI/igniteui-angular/issues/13522
Closes https://github.com/IgniteUI/igniteui-angular/issues/13531
> fix(esf): conditional filter drop down items focus - master

- projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-conditional-filter.component.html
- projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-conditional-filter.component.ts
Closes https://github.com/IgniteUI/igniteui-angular/issues/13522
Closes https://github.com/IgniteUI/igniteui-angular/issues/13531
> fix(esf): conditional filter drop down items focus - 15.1.x

- projects/igniteui-angular/src/lib/directives/for-of/for_of.directive.ts
Closes #13546  
Closes [#952](https://github.com/IgniteUI/igniteui-webcomponents/issues/952)
Closes [#957](https://github.com/IgniteUI/igniteui-webcomponents/issues/957)
> fix(IgxForOf): Add check in case node is not found in DOM.

- projects/igniteui-angular/src/lib/grids/headers/grid-header-row.component.html
- projects/igniteui-angular/src/lib/grids/headers/grid-header-row.component.ts
> Adjust header scroll position when focused element I scrolled in the view

- projects/igniteui-angular/src/lib/grids/headers/grid-header-row.component.html
- projects/igniteui-angular/src/lib/grids/headers/grid-header-row.component.ts
> Adjust header scroll position when focused element I scrolled in the view --15.1

- projects/igniteui-angular/migrations/common/tsUtils.ts
Test with igniteui-angular-samples, app builder client, bellum gens
> fix(migrations): get full ts, containing comments

- projects/igniteui-angular/migrations/common/tsUtils.ts
- projects/igniteui-angular/migrations/update-17_0_0/index.spec.ts
- projects/igniteui-angular/migrations/update-17_0_0/index.ts
> feat(migrations): move animations to igniteui-angular/animations

- projects/igniteui-angular/src/lib/date-range-picker/date-range-picker.component.spec.ts
- projects/igniteui-angular/src/lib/services/overlay/overlay.ts
> fix(overlay): using injected document for show - 15.1

- CHANGELOG.md
- projects/igniteui-angular/src/lib/buttonGroup/buttonGroup.component.ts
- projects/igniteui-angular/src/lib/buttonGroup/buttongroup.component.spec.ts
> fix(button-group): reverted cancellable on selected and deselected events - 15.1

- projects/igniteui-angular/src/lib/grids/grid-base.directive.ts
- projects/igniteui-angular/src/lib/grids/grid/grid.component.spec.ts
> fix(igxGrid): autosize hidden empty column headers correctly - 15.1.x

- projects/igniteui-angular-i18n/src/i18n/BG/grid-resources.ts
- projects/igniteui-angular-i18n/src/i18n/CS/grid-resources.ts
- projects/igniteui-angular-i18n/src/i18n/DA/grid-resources.ts
- projects/igniteui-angular-i18n/src/i18n/DE/grid-resources.ts
- projects/igniteui-angular-i18n/src/i18n/ES/grid-resources.ts
- projects/igniteui-angular-i18n/src/i18n/FR/grid-resources.ts
- projects/igniteui-angular-i18n/src/i18n/HU/grid-resources.ts
- projects/igniteui-angular-i18n/src/i18n/IT/grid-resources.ts
- projects/igniteui-angular-i18n/src/i18n/JA/grid-resources.ts
- projects/igniteui-angular-i18n/src/i18n/KO/grid-resources.ts
- projects/igniteui-angular-i18n/src/i18n/NB/grid-resources.ts
- projects/igniteui-angular-i18n/src/i18n/NL/grid-resources.ts
- projects/igniteui-angular-i18n/src/i18n/PL/grid-resources.ts
- projects/igniteui-angular-i18n/src/i18n/PT/grid-resources.ts
- projects/igniteui-angular-i18n/src/i18n/RO/grid-resources.ts
- projects/igniteui-angular-i18n/src/i18n/SV/grid-resources.ts
- projects/igniteui-angular-i18n/src/i18n/TR/grid-resources.ts
- projects/igniteui-angular-i18n/src/i18n/ZH-HANS/grid-resources.ts
- projects/igniteui-angular-i18n/src/i18n/ZH-HANT/grid-resources.ts
- projects/igniteui-angular/src/lib/core/i18n/grid-resources.ts
- projects/igniteui-angular/src/lib/core/styles/components/grid/_excel-filtering-component.scss
- projects/igniteui-angular/src/lib/core/styles/components/grid/_excel-filtering-theme.scss
- projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-search.component.html
- projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-search.component.ts
> feat(esf): improve search results accessibility - 15.1.x

- .github/workflows/npm-publish.yml
(cherry picked from commit 9322bf47a9ea87d8af2de43928ec3806a4182b4d)
See #13663
> ci(publish): NODE_OPTIONS emit to GITHUB_ENV is deprecated & not needed

- projects/igniteui-angular/src/lib/core/styles/components/list/_list-component.scss
- projects/igniteui-angular/src/lib/core/styles/components/list/_list-theme.scss
- projects/igniteui-angular/src/lib/grids/filtering/excel-style/common.ts
- projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-search.component.html
- projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-search.component.ts
- projects/igniteui-angular/src/lib/grids/grid/grid-filtering-ui.spec.ts
- projects/igniteui-angular/src/lib/list/list-item.component.ts
- projects/igniteui-angular/src/lib/list/list.component.ts
Closes #13519   
- [xocus] This PR includes unit tests covering all the new code ([test guidelines](https://github.com/IgniteUI/igniteui-angular/wiki/Test-implementation-guidelines-for-Ignite-UI-for-Angular))
> Add support for navigation in the ESF search list [15.1.x]

- projects/igniteui-angular-elements/src/analyzer/config.template.ts
- projects/igniteui-angular-elements/src/analyzer/elements.config.ts
- projects/igniteui-angular-elements/src/app/app.module.ts
- projects/igniteui-angular-elements/src/index.html
- projects/igniteui-angular-elements/src/lib/state.component.ts
- projects/igniteui-angular/src/lib/grids/grid/grid.component.html
- projects/igniteui-angular/src/lib/grids/public_api.ts
- projects/igniteui-angular/src/lib/grids/state.directive.ts
- src/app/grid-state/grid-state.component.html
- src/app/grid-state/grid-state.component.ts
Closes #  
Spec updated at: https://github.com/IgniteUI/igniteui-angular/wiki/Grid-State-Persistence#angular-elements
> Igc-grid-state component

- package-lock.json
- package.json
- projects/igniteui-angular/karma.azure.conf.js
- projects/igniteui-angular/karma.conf.js
> feat(*): adding back puppeteer

- projects/igniteui-angular/src/lib/core/styles/components/chip/_chip-theme.scss
> fix(chip): fix avatar and circular bar inside igx-suffix and igx-prefix directive

- projects/igniteui-angular/src/lib/core/density.ts
- projects/igniteui-angular/src/lib/core/utils.ts
> fix(density): inject DOCUMENT token

- angular.json
- package.json
> chore: fix demos and sassdoc build scripts

- angular.json
- package.json
This PR fixes(conceals) SSR-related errors on HMR/route loading in the Demo App so that component development is not hampered. The resolution of SSR errors should be handled in a separate PR.
Closes #13737
> build(demo-app): use builder browser and built-in hmr

- projects/igniteui-angular-elements/src/lib/state.component.ts
> chore(*): Suppresss due to Blazor not deserializingg object correctly.

- projects/igniteui-angular/src/lib/grids/grid-base.directive.ts
> Recalculate summary sizes when reset caches is called --16.1.x 

- package-lock.json
- package.json
- projects/igniteui-angular/src/lib/core/styles/components/drop-down/_drop-down-theme.scss
Related to IgniteUI/igniteui-webcomponents/issues/994
> fix(dropdown): active items in fluent theme

- projects/igniteui-angular/src/lib/data-operations/filtering-condition.ts
> Switch to alternate type only for Blazor for FilteringCondition interface.

- projects/igniteui-angular/src/lib/grids/grid-base.directive.ts
> Recalculate summary sizes when reset caches is called

- projects/igniteui-angular/src/lib/grids/grid-base.directive.ts
> Recalculate summary sizes when reset caches is called --17.0.x

- projects/igniteui-angular/src/lib/grids/state-base.directive.ts
Closes #  
Fixes issues in React/WC related to the `externalObject`: 
https://github.com/IgniteUI/igniteui-react-examples/pull/393#issuecomment-1849856424
> Add check in case there is no feature for the provided key for state.

- package-lock.json
- package.json
> deps(sassdoc-theme): bump to latest version

- projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid-base.directive.ts
- projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.spec.ts
> fix(hGrid): emit events for child grids with mch - 16.1.x

- projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid-base.directive.ts
- projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.spec.ts
> fix(hGrid): emit events for child grids with mch - 17.0.x

- projects/igniteui-angular/src/lib/core/styles/components/navbar/_navbar-theme.scss
Closes IgniteUI/igniteui-angular#13746
> fix(navbar): icon colors in AppBuilder

- projects/igniteui-angular/src/lib/core/styles/components/navbar/_navbar-theme.scss
> fix(navbar): icons color in AppBuilder

- projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid.component.html
> Enable state persistence for tree grid.

- CHANGELOG.md
- projects/igniteui-angular/src/lib/grids/README.md
- projects/igniteui-angular/src/lib/grids/common/events.ts
- projects/igniteui-angular/src/lib/grids/common/grid.interface.ts
- projects/igniteui-angular/src/lib/grids/grid-base.directive.ts
- projects/igniteui-angular/src/lib/grids/grid/grid.component.spec.ts
- projects/igniteui-angular/src/lib/grids/grid/groupby-row.component.ts
- projects/igniteui-angular/src/lib/grids/row.directive.ts
> feat(grid): implementing rowClick event

- projects/igniteui-angular/src/lib/date-picker/date-picker.component.html
- projects/igniteui-angular/src/lib/simple-combo/simple-combo.component.html
- projects/igniteui-angular/src/lib/time-picker/time-picker.component.html
> fix(*): focus input on label click - 16.1.x

- projects/igniteui-angular/src/lib/date-picker/date-picker.component.html
- projects/igniteui-angular/src/lib/simple-combo/simple-combo.component.html
- projects/igniteui-angular/src/lib/time-picker/time-picker.component.html
> fix(*): focus input on label click - 17.0.x

- projects/igniteui-angular/src/lib/simple-combo/simple-combo.component.html
- projects/igniteui-angular/src/lib/simple-combo/simple-combo.component.spec.ts
> fix(simple-combo): handle paste event - master

- projects/igniteui-angular/src/lib/simple-combo/simple-combo.component.html
- projects/igniteui-angular/src/lib/simple-combo/simple-combo.component.spec.ts
> fix(simple-combo): handle paste event - 16.1.x

- projects/igniteui-angular/src/lib/simple-combo/simple-combo.component.html
- projects/igniteui-angular/src/lib/simple-combo/simple-combo.component.spec.ts
> fix(simple-combo): handle paste event - 17.0.x

- projects/igniteui-angular/src/lib/stepper/step/step.component.ts
> fix(stepper): Prevent throwing an error when an active step is clicked - 16.1.x

- projects/igniteui-angular/src/lib/stepper/step/step.component.ts
> fix(stepper): Prevent throwing an error when an active step is clicked - 17.0.x

- projects/igniteui-angular/src/lib/stepper/step/step.component.ts
> fix(stepper): Prevent throwing an error when an active step is clicked

- projects/igniteui-angular/src/lib/directives/drag-drop/drag-drop.directive.ts
> fix(igxDrag): Restore ghost template when moving drag elements around.

- package-lock.json
- package.json
- projects/igniteui-angular/src/lib/core/styles/components/button-group/_button-group-theme.scss
Related to IgniteUI/igniteui-webcomponents/issues/1034
> refactor(btn-group): update fluent theme styles

- projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid-base.directive.ts
- projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.component.ts
- projects/igniteui-angular/src/lib/grids/hierarchical-grid/row-island.component.ts
> Hgrid: Add tags for proper generation.

- projects/igniteui-angular/src/lib/directives/for-of/for_of.directive.spec.ts
- projects/igniteui-angular/src/lib/directives/for-of/for_of.directive.ts
- projects/igniteui-angular/src/lib/grids/grid-base.directive.ts
- projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.navigation.spec.ts
- projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.virtualization.spec.ts
- projects/igniteui-angular/src/lib/list/list.component.spec.ts
- projects/igniteui-angular/src/lib/test-utils/configure-suite.ts
- projects/igniteui-angular/src/lib/test-utils/helper-utils.spec.ts
- projects/igniteui-angular/src/lib/test-utils/list-components.spec.ts
> Fix resize observer error thrown inside samples in dev mode in wc/react/blazor

- projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid-base.directive.ts
- projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.spec.ts
> Fix rowisland event emitting with MCH

- ROADMAP.md
> chore(*): update-roadmap-01-feb-2024

- projects/igniteui-angular/src/lib/action-strip/action-strip.component.ts
- projects/igniteui-angular/src/lib/action-strip/grid-actions/grid-editing-actions.component.ts
- projects/igniteui-angular/src/lib/action-strip/grid-actions/grid-pinning-actions.component.ts
- projects/igniteui-angular/src/lib/grids/grid-base.directive.ts
- projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.component.ts
- projects/igniteui-angular/src/lib/grids/hierarchical-grid/row-island.component.ts
- projects/igniteui-angular/src/lib/grids/toolbar/common.ts
- projects/igniteui-angular/src/lib/grids/toolbar/grid-toolbar-advanced-filtering.component.ts
- projects/igniteui-angular/src/lib/grids/toolbar/grid-toolbar-exporter.component.ts
- projects/igniteui-angular/src/lib/grids/toolbar/grid-toolbar-hiding.component.ts
- projects/igniteui-angular/src/lib/grids/toolbar/grid-toolbar-pinning.component.ts
- projects/igniteui-angular/src/lib/grids/toolbar/grid-toolbar.component.ts
- projects/igniteui-angular/src/lib/paginator/paginator.component.ts
> Update tags related to match hgrid implementation and api generation.

- projects/igniteui-angular-elements/src/analyzer/elements.config.ts
- projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.component.ts
> [Elements]: fix(hgrid): Fix actionstrip showing in all of the parents of rowisland hierarchy

- projects/igniteui-angular/src/lib/directives/for-of/for_of.directive.spec.ts
- projects/igniteui-angular/src/lib/directives/for-of/for_of.directive.ts
Cherry picking the fix of issue #13688 into blazor-elements so it gets to web component builds.
Closes https://github.com/IgniteUI/igniteui-webcomponents/issues/1052
> fix(igxForOf): not reset startIndex w/ scroll pos

- projects/igniteui-angular/src/lib/core/styles/components/button/_button-theme.scss
Related to IgniteUI/igniteui-webcomponents/issues/1053
> fix(button): icon in button size

- projects/igniteui-angular/src/lib/core/density.ts
> fix(density): resolve NG0100 errors

- .github/workflows/nodejs.yml
- .github/workflows/npm-publish.yml
- azure-pipelines.yml
- package.json
> ci(schematics): build schematics & migrations in the CI

- projects/igniteui-angular/src/lib/core/styles/components/button/_button-theme.scss
- projects/igniteui-angular/src/lib/core/styles/components/grid/_excel-filtering-theme.scss
- projects/igniteui-angular/src/lib/core/styles/components/grid/_grid-theme.scss
> fix(button): redundant margin in bootstrap theme

- projects/igniteui-angular/src/lib/calendar/calendar-base.ts
Closes #  https://github.com/IgniteUI/igniteui-angular/issues/13850
> fix(calendar): no setting of date if same date is already set

- projects/igniteui-angular/migrations/update-10_2_0/changes/inputs.json
- projects/igniteui-angular/migrations/update-11_0_0/changes/inputs.json
- projects/igniteui-angular/migrations/update-11_1_0/changes/inputs.json
- projects/igniteui-angular/migrations/update-12_0_0/changes/inputs.json
- projects/igniteui-angular/migrations/update-12_1_0/changes/inputs.json
- projects/igniteui-angular/migrations/update-13_0_0/changes/inputs.json
- projects/igniteui-angular/migrations/update-13_1_0/changes/inputs.json
- projects/igniteui-angular/migrations/update-15_0_0/changes/inputs.json
- projects/igniteui-angular/migrations/update-15_1_0/changes/inputs.json
- projects/igniteui-angular/migrations/update-9_0_0/changes/inputs.json
- projects/igniteui-angular/migrations/update-9_1_0/changes/inputs.json
> chore(migrations): fix json schema in change files

- projects/igniteui-angular/package.json
> chore(migartions): add "igniteui-angular-extras" to ng update group

- projects/igniteui-angular/src/lib/core/styles/components/dialog/_dialog-theme.scss
- projects/igniteui-angular/src/lib/core/styles/typography/_indigo.scss
> feat(dialog): update indigo dialog paddings

- projects/igniteui-angular/src/lib/core/styles/components/radio/_radio-component.scss
- projects/igniteui-angular/src/lib/core/styles/components/radio/_radio-theme.scss
- projects/igniteui-angular/src/lib/core/styles/typography/_indigo.scss
Related to [this issue](https://github.com/IgniteUI/igniteui-theming/issues/180)
Here's the igniteui-theming [PR](https://github.com/IgniteUI/igniteui-theming/pull/185)
> feat(radio): update radio to fit new indigo ui kit

- CHANGELOG.md
- projects/igniteui-angular/src/lib/grids/common/grid.interface.ts
- projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.integration.spec.ts
- projects/igniteui-angular/src/lib/grids/hierarchical-grid/row-island.component.ts
- projects/igniteui-angular/src/lib/test-utils/hierarchical-grid-components.spec.ts
Related to changes made in #13851
> Add toolbar and paginator template inputs enhancements. Optimize paginator init.

- projects/igniteui-angular/src/lib/combo/combo.common.ts
- projects/igniteui-angular/src/lib/combo/combo.component.spec.ts
- projects/igniteui-angular/src/lib/core/selection.ts
- projects/igniteui-angular/src/lib/drop-down/drop-down.component.spec.ts
- projects/igniteui-angular/src/lib/drop-down/drop-down.component.ts
- projects/igniteui-angular/src/lib/select/select.component.spec.ts
- projects/igniteui-angular/src/lib/select/select.component.ts
- projects/igniteui-angular/src/lib/simple-combo/simple-combo.component.spec.ts
> fix(select): fix memory leak in IgxSelectionAPIService -16.1.x

- projects/igniteui-angular/src/lib/combo/combo.common.ts
- projects/igniteui-angular/src/lib/combo/combo.component.spec.ts
- projects/igniteui-angular/src/lib/core/selection.ts
- projects/igniteui-angular/src/lib/drop-down/drop-down.component.spec.ts
- projects/igniteui-angular/src/lib/drop-down/drop-down.component.ts
- projects/igniteui-angular/src/lib/select/select.component.spec.ts
- projects/igniteui-angular/src/lib/select/select.component.ts
- projects/igniteui-angular/src/lib/simple-combo/simple-combo.component.spec.ts
> fix(select): fix memory leak in IgxSelectionAPIService - 15.1.x

- projects/igniteui-angular/package.json
> chore(schematics): update-official-schematics

- projects/igniteui-angular/src/lib/core/styles/components/banner/_banner-theme.scss
Related to IgniteUI/igniteui-theming/issues/194
> feat(banner): implement indigo design changes

- projects/igniteui-angular/src/lib/core/styles/components/snackbar/_snackbar-theme.scss
Related to IgniteUI/igniteui-theming/issues/193
> feat(snackbar): implement indigo design changes

- package-lock.json
- package.json
- scripts/build-typedoc.mjs
> chore(*): will it fail without the catch

- projects/igniteui-angular/src/lib/directives/button/button.module.ts
> fix(icon-button): add directive into button module

- projects/igniteui-angular/src/lib/grids/hierarchical-grid/row-island.component.ts
> fix(rowIsland): Do no calcualte row island widths, since it does not render element anyway.

- projects/igniteui-angular/src/lib/grids/common/grid.interface.ts
- projects/igniteui-angular/src/lib/grids/grid/grid-filtering-advanced.spec.ts
- projects/igniteui-angular/src/lib/grids/toolbar/grid-toolbar-advanced-filtering.component.html
- projects/igniteui-angular/src/lib/test-utils/grid-samples.spec.ts
> fix(filtering): pass overlay settings in GridType

- projects/igniteui-angular/src/lib/core/styles/components/expansion-panel/_expansion-panel-theme.scss
- projects/igniteui-angular/src/lib/core/styles/typography/_indigo.scss
> feat(expansion-panel): update expansion panel for indigo

- projects/igniteui-angular/src/lib/core/styles/components/stepper/_stepper-theme.scss
> fix(stepper): add clamp function to values to prevent indicator background being cut

- projects/igniteui-angular-elements/src/lib/state.component.ts
- projects/igniteui-angular/src/lib/data-operations/filtering-expressions-tree.ts
- projects/igniteui-angular/src/lib/data-operations/groupby-state.interface.ts
- projects/igniteui-angular/src/lib/data-operations/paging-state.interface.ts
- projects/igniteui-angular/src/lib/grids/common/grid.interface.ts
- projects/igniteui-angular/src/lib/grids/common/types.ts
- projects/igniteui-angular/src/lib/grids/state-base.directive.ts
Related to: https://infragistics.visualstudio.com/NetAdvantage/_git/dev-tools/pullrequest/11464
> Add more tags for blazor state persistence classes.

- projects/igniteui-angular/src/lib/grids/common/crud.service.ts
- projects/igniteui-angular/src/lib/grids/grid/grid-row-editing.spec.ts
> fix(igxGrid): Emit new data for the rowAdd event args.

- projects/igniteui-angular/src/lib/grids/common/crud.service.ts
- projects/igniteui-angular/src/lib/grids/grid/grid-row-editing.spec.ts
> fix(igxGrid): Emit new data for the rowAdd event args. 

- projects/igniteui-angular/src/lib/grids/grid-base.directive.ts
- projects/igniteui-angular/src/lib/grids/grid/grid.component.html
- projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.component.html
- projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.spec.ts
- projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-grid.component.html
- projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid.component.html
Closes #13976 
[Sample](https://stackblitz.com/edit/igx-hierarchical-grid-empty-grid-template-context-test?file=src%2Fapp%2Fhierarchical-grid%2Fhierarchical-grid-column-resizing%2Fhierarchical-grid-resizing.component.html) for verification
> fix(hgrid): expose grid instance in template context  -16.1.x

- projects/igniteui-angular/src/lib/grids/hierarchical-grid/row-island.component.ts
> Temporary disable RowIsland templates for Blazor/React.

- projects/igniteui-angular/src/lib/core/styles/typography/_bootstrap.scss
> fix(radio): fix radio label type style in bootstrap

- package-lock.json
- package.json
- projects/igniteui-angular/package.json
- projects/igniteui-angular/src/lib/core/styles/components/splitter/_splitter-theme.scss
- projects/igniteui-angular/src/lib/splitter/splitter-bar.component.html
- projects/igniteui-angular/src/lib/splitter/splitter.component.html
- projects/igniteui-angular/src/lib/splitter/splitter.component.spec.ts
- projects/igniteui-angular/src/lib/splitter/splitter.component.ts
- src/app/splitter/splitter.sample.html
- src/app/splitter/splitter.sample.scss
- src/app/splitter/splitter.sample.ts
- src/styles/_variables.scss
> feat(splitter): implement indigo splitter changes

- package-lock.json
- package.json
- projects/igniteui-angular/src/lib/core/styles/components/slider/_slider-component.scss
- projects/igniteui-angular/src/lib/core/styles/components/slider/_slider-theme.scss
> feat(slider): implement indigo slider

- projects/igniteui-angular/src/lib/core/styles/components/time-picker/_time-picker-component.scss
- projects/igniteui-angular/src/lib/core/styles/components/time-picker/_time-picker-theme.scss
- projects/igniteui-angular/src/lib/core/styles/typography/_bootstrap.scss
- projects/igniteui-angular/src/lib/core/styles/typography/_indigo.scss
- projects/igniteui-angular/src/lib/time-picker/time-picker.component.html
- projects/igniteui-angular/src/lib/time-picker/time-picker.component.ts
- src/app/time-picker/time-picker.sample.scss
Related to  https://github.com/IgniteUI/igniteui-theming/issues/218
> refactor(themes): update indigo time picker 

- projects/igniteui-angular/src/lib/core/styles/components/tree/_tree-component.scss
- projects/igniteui-angular/src/lib/core/styles/components/tree/_tree-theme.scss
> feat(tree): implement indigo tree changes

- projects/igniteui-angular/src/lib/core/styles/components/input/_input-group-theme.scss
Related to IgniteUI/igniteui-theming/issues/220
> fix(textarea): indigo theme styles

- projects/igniteui-angular/src/lib/slider/slider.component.spec.ts
- projects/igniteui-angular/src/lib/slider/slider.component.ts
> fix(slider): correct behavior of igx-slider in synchronized two-way binding - master

- projects/igniteui-angular/src/lib/core/styles/components/slider/_slider-theme.scss
- projects/igniteui-angular/src/lib/slider/slider.component.spec.ts
- projects/igniteui-angular/src/lib/slider/slider.component.ts
> fix(slider): add pointer move handling; clear old HammerJS pan event.

- projects/igniteui-angular/src/lib/core/styles/components/button-group/_button-group-theme.scss
> fix(btn-group): fluent theme sizing issue

- package-lock.json
- package.json
- projects/igniteui-angular/src/lib/core/styles/components/calendar/_calendar-theme.scss
> fix(calendar): add colors for active month/ year states

- projects/igniteui-angular/src/lib/core/styles/components/chip/_chip-theme.scss
- projects/igniteui-angular/src/lib/core/styles/components/query-builder/_query-builder-theme.scss
> fix(chip/query-builder): fix chip in advanced filtering context

- README.md
> Update release Table with 17.1.0

- projects/igniteui-angular/src/lib/core/styles/typography/_bootstrap.scss
Related to IgniteUI/igniteui-webcomponents/issues/1145
> fix(typography): bootstrap type styles

- projects/igniteui-angular/src/lib/core/styles/components/chip/_chip-theme.scss
- projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-grid.spec.ts
- projects/igniteui-angular/src/lib/test-utils/pivot-grid-samples.spec.ts
Related to https://github.com/IgniteUI/igniteui-webcomponents/issues/1127
> refactor(chip): remove custom icon sizes

- projects/igniteui-angular/src/lib/directives/date-time-editor/date-time-editor.directive.spec.ts
- projects/igniteui-angular/src/lib/directives/date-time-editor/date-time-editor.directive.ts
> fix(date-time-editor): handle iso date string for mask value -17.1.x

- projects/igniteui-angular/src/lib/calendar/calendar-base.ts
- projects/igniteui-angular/src/lib/calendar/calendar.component.spec.ts
- projects/igniteui-angular/src/lib/calendar/calendar.component.ts
> fix(caledar): enable setting ISO format dates

- projects/igniteui-angular/src/lib/core/styles/components/input/_input-group-component.scss
- projects/igniteui-angular/src/lib/core/styles/components/input/_input-group-theme.scss
- src/app/input-group/input-group.sample.html
> refactor(input-group): update drag handle position inside textarea

- projects/igniteui-angular/migrations/update-17_2_0/changes/theme-changes.json
- projects/igniteui-angular/migrations/update-17_2_0/index.spec.ts
- projects/igniteui-angular/src/lib/core/styles/components/bottom-nav/_bottom-nav-theme.scss
- src/app/bottomnav/bottomnav.sample.html
> refactor(bottom-nav): update indigo theme

- projects/igniteui-angular/src/lib/core/styles/components/navdrawer/_navdrawer-theme.scss
- projects/igniteui-angular/src/lib/core/styles/typography/_indigo.scss
- projects/igniteui-angular/src/lib/navigation-drawer/navigation-drawer.component.spec.ts
- projects/igniteui-angular/src/lib/navigation-drawer/navigation-drawer.component.ts
> feat(navdrawer): update indigo navdrawer

- projects/igniteui-angular/src/lib/core/styles/components/switch/_switch-component.scss
- projects/igniteui-angular/src/lib/core/styles/components/switch/_switch-theme.scss
- projects/igniteui-angular/src/lib/core/styles/typography/_indigo.scss
Related to IgniteUI/igniteui-theming/issues/233
> feat(switch): implement indigo theme updates

- projects/igniteui-angular/src/lib/calendar/calendar-base.ts
- projects/igniteui-angular/src/lib/calendar/calendar.component.spec.ts
- projects/igniteui-angular/src/lib/calendar/calendar.component.ts
Closes #https://github.com/IgniteUI/igniteui-angular/issues/14076
> fix(caledar): enable setting ISO format dates 17.1.x

- CHANGELOG.md
- projects/igniteui-angular/src/lib/grids/grid-base.directive.ts
- projects/igniteui-angular/src/lib/grids/grid/grid-filtering-advanced.spec.ts
> feat(advance-filtering): Emit filtering event when use advanced filtering

- projects/igniteui-angular/src/lib/date-picker/date-picker.component.html
- projects/igniteui-angular/src/lib/date-picker/date-picker.component.spec.ts
> fix(date-picker): update toggle icon

- projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-search.component.ts
- projects/igniteui-angular/src/lib/grids/grid/grid-filtering-ui.spec.ts
> fix(esf): reset forOf startIndex on esf columnChange

- projects/igniteui-angular/migrations/update-17_2_0/changes/inputs.json
> fix(migrations): button migrations

- projects/igniteui-angular/src/lib/calendar/months-view/months-view.component.ts
- projects/igniteui-angular/src/lib/calendar/years-view/years-view.component.ts
> fix(calendar): bad type imports

- projects/igniteui-angular/src/lib/directives/date-time-editor/date-time-editor.directive.ts
- projects/igniteui-angular/src/lib/directives/mask/mask.directive.ts
> Use mask's CVA callbacks - 16.1

- projects/igniteui-angular/src/lib/directives/toggle/toggle.directive.ts
> chore(toggle): Adjust event handling examples to utilize the actual events - 17.1.x

- projects/igniteui-angular/src/lib/directives/date-time-editor/date-time-editor.directive.ts
Closes https://github.com/IgniteUI/igniteui-angular/issues/14133
> Allow nullables in date editor value - 16.1

- projects/igniteui-angular/src/lib/directives/date-time-editor/date-time-editor.directive.ts
Closes https://github.com/IgniteUI/igniteui-angular/issues/14133
> Allow nullables in date editor value - 17.1

- projects/igniteui-angular/src/lib/directives/toggle/toggle.directive.ts
> chore(toggle): Adjust event handling examples to utilize the actual events - 16.1.x

- projects/igniteui-angular/src/lib/directives/toggle/toggle.directive.ts
> chore(toggle): Adjust event handling examples to utilize the actual events - master

- projects/igniteui-angular/src/lib/calendar/calendar.component.ts
- projects/igniteui-angular/src/lib/calendar/days-view/days-view.component.ts
- src/app/calendar/calendar.sample.html
- src/app/calendar/calendar.sample.scss
- src/app/calendar/calendar.sample.ts
> fix(calendar): ngModel doesn't update with updateOn: 'blur' set

- projects/igniteui-angular/src/lib/core/styles/components/overlay/_overlay-component.scss
- projects/igniteui-angular/src/lib/core/styles/components/overlay/_overlay-theme.scss
- projects/igniteui-angular/src/lib/core/utils.ts
- projects/igniteui-angular/src/lib/directives/toggle/toggle.directive.ts
> fix(overlay): change how containers are hidden

- package-lock.json
- package.json
- projects/igniteui-angular/package.json
- projects/igniteui-angular/src/lib/core/styles/components/button-group/_button-group-theme.scss
- projects/igniteui-angular/src/lib/core/styles/components/button/_button-component.scss
- projects/igniteui-angular/src/lib/core/styles/components/button/_button-theme.scss
- projects/igniteui-angular/src/lib/core/styles/components/icon-button/_icon-button-theme.scss
- projects/igniteui-angular/src/lib/directives/button/button-base.ts
- projects/igniteui-angular/src/lib/directives/button/button.directive.ts
Related to https://github.com/IgniteUI/igniteui-webcomponents/issues/1107
Related to https://github.com/IgniteUI/igniteui-angular/pull/14006
> refactor(button, button-group): update themes and behavior

- projects/igniteui-angular/src/lib/calendar/month-picker/month-picker.component.html
- projects/igniteui-angular/src/lib/calendar/month-picker/month-picker.component.spec.ts
- projects/igniteui-angular/src/lib/calendar/month-picker/month-picker.component.ts
> refactor(month-picker): rework keyboard nav

- projects/igniteui-angular/src/lib/simple-combo/simple-combo.component.spec.ts
- projects/igniteui-angular/src/lib/simple-combo/simple-combo.component.ts
> Update display value when model changes

- projects/igniteui-angular/src/lib/simple-combo/simple-combo.component.spec.ts
- projects/igniteui-angular/src/lib/simple-combo/simple-combo.component.ts
- src/app/combo/combo.sample.ts
> Update display value when model changes & sync sample with the one in the samples repo

- projects/igniteui-angular/src/lib/simple-combo/simple-combo.component.spec.ts
- projects/igniteui-angular/src/lib/simple-combo/simple-combo.component.ts
- src/app/combo/combo.sample.ts
> fix(simple-combo): update display value when model changes & sync sample

- projects/igniteui-angular/migrations/migration-collection.json
- projects/igniteui-angular/migrations/update-17_2_0/changes/inputs.json
- projects/igniteui-angular/migrations/update-17_2_2/changes/inputs.json
- projects/igniteui-angular/migrations/update-17_2_2/index.spec.ts
- projects/igniteui-angular/migrations/update-17_2_2/index.ts
> refactor(migrations): improve button and card action migrations

- projects/igniteui-angular/src/lib/grids/common/crud.service.ts
- projects/igniteui-angular/src/lib/grids/grid/grid-row-editing.spec.ts
> fix(IgxGrid): Fix event args for rowAdded too. Update test. 

- projects/igniteui-angular/src/lib/core/styles/components/button-group/_button-group-theme.scss
Related to IgniteUI/igniteui-webcomponents/issues/1107
> fix(btn-group): indigo theme padding

- projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.spec.ts
- projects/igniteui-angular/src/lib/grids/hierarchical-grid/row-island.component.ts
> fix(rowIsland): update columns property on column change - 16.1.x

- projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.spec.ts
- projects/igniteui-angular/src/lib/grids/hierarchical-grid/row-island.component.ts
> fix(rowIsland): update columns property on column change - 17.2.x

- projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.spec.ts
- projects/igniteui-angular/src/lib/grids/hierarchical-grid/row-island.component.ts
> fix(rowIsland): update columns property on column change - master

- projects/igniteui-angular/src/lib/buttonGroup/buttonGroup.component.ts
> fix(buttonGroup): Remove the use of the deprecated MutationEvent -17.2.x

- projects/igniteui-angular/src/lib/buttonGroup/buttonGroup.component.ts
Closes #  [14193](https://github.com/IgniteUI/igniteui-angular/issues/14194)
Removed event listener that used deprecated MutationEvent:
https://developer.mozilla.org/en-US/docs/Web/API/MutationEvent
> chore(button-group): Deleted deprecated event listener

- projects/igniteui-angular/src/lib/core/styles/components/button-group/_button-group-theme.scss
- projects/igniteui-angular/src/lib/core/styles/components/button/_button-theme.scss
> fix(button/btn-group): bind icon colors to foreground colors in theme

- package-lock.json
- package.json
- projects/igniteui-angular/migrations/migration-collection.json
- projects/igniteui-angular/migrations/update-17_2_0/changes/theme-changes.json
- projects/igniteui-angular/migrations/update-17_2_0/index.spec.ts
- projects/igniteui-angular/migrations/update-17_2_3/changes/theme-changes.json
- projects/igniteui-angular/migrations/update-17_2_3/index.spec.ts
- projects/igniteui-angular/migrations/update-17_2_3/index.ts
- projects/igniteui-angular/package.json
- projects/igniteui-angular/src/lib/core/styles/components/bottom-nav/_bottom-nav-component.scss
- projects/igniteui-angular/src/lib/core/styles/components/bottom-nav/_bottom-nav-theme.scss
- projects/igniteui-angular/src/lib/core/styles/components/navbar/_navbar-component.scss
- projects/igniteui-angular/src/lib/core/styles/components/navbar/_navbar-theme.scss
- projects/igniteui-angular/src/lib/core/styles/components/navdrawer/_navdrawer-theme.scss
- projects/igniteui-angular/src/lib/core/styles/components/switch/_switch-component.scss
- projects/igniteui-angular/src/lib/core/styles/components/switch/_switch-theme.scss
- projects/igniteui-angular/src/lib/core/styles/typography/_indigo.scss
- projects/igniteui-angular/src/lib/navbar/navbar.component.html
- projects/igniteui-angular/src/lib/navbar/navbar.component.spec.ts
- projects/igniteui-angular/src/lib/navigation-drawer/navigation-drawer.component.spec.ts
- projects/igniteui-angular/src/lib/navigation-drawer/navigation-drawer.component.ts
- src/app/bottomnav/bottomnav.sample.html
- src/app/navbar/navbar.sample.html
- src/app/navbar/navbar.sample.scss
- src/app/navbar/navbar.sample.ts
> Indigo: Add Updates for Navdrawer, Navbar, and Switch

- projects/igniteui-angular/src/lib/core/styles/components/radio/_radio-component.scss
- projects/igniteui-angular/src/lib/core/styles/components/radio/_radio-theme.scss
> feat(radio): implement radio enchancements

- projects/igniteui-angular/src/lib/core/styles/components/checkbox/_checkbox-component.scss
- projects/igniteui-angular/src/lib/core/styles/components/checkbox/_checkbox-theme.scss
- projects/igniteui-angular/src/lib/core/styles/typography/_bootstrap.scss
> feat(checkbox): complete checkbox refinements

- projects/igniteui-angular/src/lib/grids/common/crud.service.ts
> fix(IgxGrid): Add checks in case cell is no longer in view. 

- CHANGELOG.md
- projects/igniteui-angular/src/lib/grids/README.md
- projects/igniteui-angular/src/lib/grids/cell.component.ts
- projects/igniteui-angular/src/lib/grids/common/events.ts
- projects/igniteui-angular/src/lib/grids/common/grid.interface.ts
- projects/igniteui-angular/src/lib/grids/grid-base.directive.ts
- projects/igniteui-angular/src/lib/grids/grid/cell.spec.ts
- projects/igniteui-angular/src/lib/grids/grid/grid.component.spec.ts
- projects/igniteui-angular/src/lib/grids/row.directive.ts
> feat(grid): make contextMenu fire on row area without cells (#13487)

- projects/igniteui-angular/src/lib/navigation-drawer/navigation-drawer.component.spec.ts
- projects/igniteui-angular/src/lib/navigation-drawer/navigation-drawer.component.ts
> fix(navdrawer): pinned mini drawer should work with position fixed

- package-lock.json
- package.json
- projects/igniteui-angular/package.json
- projects/igniteui-angular/src/lib/core/styles/components/navbar/_navbar-theme.scss
> Navbar - Fix button size in context of navbar and add missing border variable

- package-lock.json
- package.json
- projects/igniteui-angular/package.json
- projects/igniteui-angular/src/lib/core/styles/components/navbar/_navbar-theme.scss
> Navbar - Fix button size in context of navbar and add missing border variable 

- projects/igniteui-angular/src/lib/services/exporter-common/base-export-service.ts
> chore(*): Add null check to fix tests.

- projects/igniteui-angular/src/lib/core/styles/components/list/_list-theme.scss
- projects/igniteui-angular/src/lib/core/styles/typography/_indigo.scss
- src/app/list/list.sample.html
closes [249](https://github.com/IgniteUI/igniteui-theming/issues/249)
> Indigo list - implement the latest design from indigo UI kit

- projects/igniteui-angular/src/lib/core/styles/components/switch/_switch-theme.scss
> feat(switch): fix track color

- projects/igniteui-angular/src/lib/card/card.component.ts
> refactor(card): transform elevated input as boolean

- CHANGELOG.md
- package-lock.json
- package.json
- projects/igniteui-angular/package.json
- projects/igniteui-angular/src/lib/core/styles/components/navbar/_navbar-theme.scss
- src/app/navbar/navbar.sample.html
> fix(navbar): update component sizes in the context of the navbar

- package-lock.json
- package.json
- projects/igniteui-angular/package.json
- projects/igniteui-angular/src/lib/core/styles/components/query-builder/_query-builder-theme.scss
> fix(query-builder): size components properly

- projects/igniteui-angular/src/lib/core/styles/components/input/_input-group-component.scss
- projects/igniteui-angular/src/lib/core/styles/components/input/_input-group-theme.scss
> Textarea - fix label position

- projects/igniteui-angular/src/lib/core/styles/components/tree/_tree-theme.scss
> feat(tree): implement tree problem comments

- projects/igniteui-angular/src/lib/core/styles/components/progress/_progress-theme.scss
Related to https://github.com/IgniteUI/igniteui-theming/issues/250
> feat(progress): update indigo theme styles

- projects/igniteui-angular/package.json
> chore(schmeatics): update ig schematics with rc

- projects/igniteui-angular/src/lib/core/styles/components/slider/_slider-theme.scss
> feat(slider): implement indigo slider changes

- projects/igniteui-angular/migrations/update-18_0_0/index.spec.ts
- projects/igniteui-angular/migrations/update-18_0_0/index.ts
> fix(migrations): improve migration to take @use and @forward into acc

- CHANGELOG.md
- projects/igniteui-angular/src/lib/simple-combo/simple-combo.component.spec.ts
- projects/igniteui-angular/src/lib/simple-combo/simple-combo.component.ts
> fix(simple-combo): Update the model value only if selection is changed

- projects/igniteui-angular/src/lib/slider/slider.component.spec.ts
- projects/igniteui-angular/src/lib/slider/slider.component.ts
- projects/igniteui-angular/src/lib/slider/thumb/thumb-slider.component.ts
> fix(slider): respect ngModelOptions.updateOn: blur - 17.2.x

- projects/igniteui-angular/src/lib/slider/slider.component.spec.ts
- projects/igniteui-angular/src/lib/slider/slider.component.ts
- projects/igniteui-angular/src/lib/slider/thumb/thumb-slider.component.ts
> fix(slider): respect ngModelOptions.updateOn: blur - 16.1.x

- projects/igniteui-angular/src/lib/core/styles/components/button/_button-theme.scss
The icon color should change the way the text changes if the $background theme property is updated.
Closes #
> fix(button): idle icon color not updated

- projects/igniteui-angular/src/lib/core/styles/components/grid/_excel-filtering-theme.scss
> fix(ESF): buttons border styles

- projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-grid.component.html
> fix(pivotGrid): Fix data reload for pivot grid not recalculating row height.

- projects/igniteui-angular/migrations/update-18_0_0/changes/inputs.json
- projects/igniteui-angular/migrations/update-18_0_0/index.spec.ts
- projects/igniteui-angular/migrations/update-18_0_0/index.ts
- projects/igniteui-angular/src/lib/combo/combo.common.ts
Reverts migration added in  #14323  because it caused errors and I'm not sure that property is even done right.
Still making the `caseSensitive` optional since it's a false-default bool that can just as easily be omitted when typing other options, just for ease of configuration.
As for the `filterable` option - not really sure it's done right like that. For one, it's pretty odd to have to explicitly set `true` when you're already providing filtering options and it's more/less implied you want filtering. Also, pretty hard to find a use case for it in the [spec](https://github.com/IgniteUI/igniteui-angular/wiki/IgxCombo-(Component)). It's implemented separately at least as `disableFiltering` in WC, though that [spec](https://github.com/IgniteUI/igniteui-angular/wiki/IgxCombo-(Component)) or …
> [Combo] Make  FilteringOptions.caseSensitive optional, revert filterable migration for now

- projects/igniteui-angular/src/lib/directives/tooltip/tooltip-target.directive.ts
- projects/igniteui-angular/src/lib/directives/tooltip/tooltip.directive.spec.ts
- projects/igniteui-angular/src/lib/test-utils/tooltip-components.spec.ts
> Tooltip: correctly set target when defined along with and before igxToggleAction on same host - 17.2.x

- projects/igniteui-angular/src/lib/directives/tooltip/tooltip-target.directive.ts
- projects/igniteui-angular/src/lib/directives/tooltip/tooltip.directive.spec.ts
- projects/igniteui-angular/src/lib/test-utils/tooltip-components.spec.ts
> Tooltip: correctly set target when defined along with and before igxToggleAction on same host - 16.1.x

- projects/igniteui-angular/src/lib/directives/tooltip/tooltip-target.directive.ts
- projects/igniteui-angular/src/lib/directives/tooltip/tooltip.directive.spec.ts
- projects/igniteui-angular/src/lib/test-utils/tooltip-components.spec.ts
> Tooltip: correctly set target when defined along with and before igxToggleAction on same host -18.0.x

- projects/igniteui-angular/migrations/update-18_0_0/index.spec.ts
- projects/igniteui-angular/migrations/update-18_0_0/index.ts
> Update 18 - handle complex file ref configs in workspace schema - 18.0

- projects/igniteui-angular/migrations/update-18_0_0/index.spec.ts
- projects/igniteui-angular/migrations/update-18_0_0/index.ts
> Update 18 - handle complex file ref configs in workspace schema

- projects/igniteui-angular/src/lib/simple-combo/simple-combo.component.spec.ts
- projects/igniteui-angular/src/lib/simple-combo/simple-combo.component.ts
> fix(simple-combo): prevent Enter key default behavior when filtering data - 18.0.x

- projects/igniteui-angular/src/lib/grids/grid/grid-row-selection.spec.ts
- projects/igniteui-angular/src/lib/grids/selection/selection.service.ts
- src/app/grid-remote-paging/grid-remote-paging.sample.ts
- src/app/grid-remote-virtualization/grid-remote-virtualization.sample.ts
> Return the newSelection in the rowSelectionChanging event args in correct order - 16.1

- projects/igniteui-angular/src/lib/core/styles/components/tooltip/_tooltip-component.scss
- projects/igniteui-angular/src/lib/core/styles/components/tooltip/_tooltip-theme.scss
- projects/igniteui-angular/src/lib/core/styles/typography/_indigo.scss
- projects/igniteui-angular/src/lib/directives/tooltip/tooltip.directive.spec.ts
- projects/igniteui-angular/src/lib/directives/tooltip/tooltip.directive.ts
Related to IgniteUI/igniteui-theming/issues/276
> feat(tooltip): implement indigo design changes

- projects/igniteui-angular/src/lib/grids/common/events.ts
- projects/igniteui-angular/src/lib/grids/common/grid.interface.ts
- projects/igniteui-angular/src/lib/grids/common/strategy.ts
- projects/igniteui-angular/src/lib/grids/common/types.ts
> docs(grids): fixing typos on API comments

- projects/igniteui-angular/src/lib/core/styles/components/stepper/_stepper-theme.scss
- projects/igniteui-angular/src/lib/core/styles/typography/_indigo.scss
- src/app/stepper/stepper.sample.html
- src/app/stepper/stepper.sample.scss
Closes https://github.com/IgniteUI/igniteui-theming/issues/277
- fix avatar shape in the sample
- fix badge size in the sample
> Stepper - update indigo stepper to match the latest design from the UI kit

- projects/igniteui-angular/src/lib/core/styles/components/toast/_toast-theme.scss
Related to IgniteUI/igniteui-theming/issues/275
> feat(toast): implement indigo design updates

- projects/igniteui-angular/src/lib/core/density.ts
> docs(density): mark extra api as internal as intended

- projects/igniteui-angular/src/lib/calendar/month-picker/month-picker.component.spec.ts
- projects/igniteui-angular/src/lib/calendar/month-picker/month-picker.component.ts
> fix(month-picker): emit viewDateChanged event on arrow key navigation - 17.2.x

- projects/igniteui-angular/src/lib/calendar/month-picker/month-picker.component.spec.ts
- projects/igniteui-angular/src/lib/calendar/month-picker/month-picker.component.ts
> fix(month-picker): emit viewDateChanged event on arrow key navigation - 18.0.x

- projects/igniteui-angular/src/lib/calendar/month-picker/month-picker.component.spec.ts
- projects/igniteui-angular/src/lib/calendar/month-picker/month-picker.component.ts
> fix(month-picker): emit viewDateChanged event on arrow key navigation - master

- projects/igniteui-angular/migrations/update-18_0_0/index.ts
> fix(update-18): use typeof instead of instanceof - 18.0

- projects/igniteui-angular/migrations/update-18_0_0/index.ts
> fix(update-18): use typeof instead of instanceof

- projects/igniteui-angular/src/lib/simple-combo/simple-combo.component.spec.ts
- projects/igniteui-angular/src/lib/simple-combo/simple-combo.component.ts
> fix(simple-combo): preserved the input value when selectionChanging is canceled - master

- projects/igniteui-angular/src/lib/core/styles/components/icon-button/_icon-button-theme.scss
Related to https://github.com/IgniteUI/igniteui-angular/issues/14409
> fix(icon-button): missing module

- package-lock.json
- package.json
- projects/igniteui-angular/package.json
> build(deps): bump igniteui-theming to 8.2.0

- projects/igniteui-angular/src/lib/grids/common/grid.interface.ts
- projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-grid.component.ts
- projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-row-dimension-header.component.ts
Related to https://github.com/IgniteUI/igniteui-angular/pull/14347#issuecomment-2172874428
> fix(igxPivotGrid): Fix sorting for horizontal row mode.

- projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-grid.spec.ts
> Add horizontal layout test for the pivot.

- projects/igniteui-angular/src/lib/combo/combo.common.ts
- projects/igniteui-angular/src/lib/simple-combo/simple-combo.component.spec.ts
> fix(combo): Handle selection when placed in an IgxGrid cell template and grid is virtualized - 18.0.x

- projects/igniteui-angular/src/lib/core/styles/components/input/_input-group-theme.scss
- projects/igniteui-angular/src/lib/input-group/input-group.component.html
> fix(input-group): incorrect indigo layout

- projects/igniteui-angular/src/lib/drop-down/drop-down.component.spec.ts
- projects/igniteui-angular/src/lib/drop-down/drop-down.component.ts
>  Adding default overlay settings - 18.0.x

- projects/igniteui-angular/src/lib/buttonGroup/buttonGroup.component.ts
- projects/igniteui-angular/src/lib/buttonGroup/buttongroup.component.spec.ts
> fix(button-group): prevent selected event from emitting twice on click - 17.2.x

- projects/igniteui-angular/src/lib/drop-down/drop-down.component.spec.ts
- projects/igniteui-angular/src/lib/drop-down/drop-down.component.ts
> Adding default overlay settings - 17.2.x

- projects/igniteui-angular/src/lib/grids/grid/grid-filtering-ui.spec.ts
- projects/igniteui-angular/src/lib/grids/headers/grid-header-group.component.ts
> fix(grid): Fix filtering UI mousedown event handling - 17.2.x

- projects/igniteui-angular/.eslintrc.json
- projects/igniteui-angular/src/lib/calendar/common/model.spec.ts
- projects/igniteui-angular/src/lib/navigation-drawer/navigation-drawer.component.ts
- projects/igniteui-angular/src/lib/test-utils/grid-functions.spec.ts
> Minor cleanup of console logs, add lint rule

- projects/igniteui-angular/src/lib/grids/toolbar/grid-toolbar-advanced-filtering.component.ts
> docs(grid,toolbar): mark adv. filtering comp ngAfterViewInit hidden

- projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-grid.component.ts
- projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-grid.interface.ts
> Adjust tags for better generation for pivot in react.

- projects/igniteui-angular/src/lib/core/styles/themes/generators/_base.scss
- src/app/input-group/input-group.sample.html
- src/styles/_variables.scss
> refactor(themes): include `--ig-theme` in the generated CSS themes

- CHANGELOG.md
- projects/igniteui-angular/src/lib/grids/columns/column-group.component.ts
- projects/igniteui-angular/src/lib/grids/columns/column.component.ts
- projects/igniteui-angular/src/lib/grids/common/grid.interface.ts
- projects/igniteui-angular/src/lib/grids/grid/column-group.spec.ts
- projects/igniteui-angular/src/lib/grids/grid/column-moving.spec.ts
@hanastasov @dkamburov Might need some help from your teams whether some of the exposed API makes sense or has seen usage in custom samples/cases.
So far I've made the following internal:
- `filterCell`, `headerCell` and `headerGroup` - I can find no usage anywhere outside internals and see little reason - those expose hidden internal structure components (the `IgxGridFilteringCellComponent`  is not even in the public API, though IMO the rest shouldn't be either).
- `defaultMinWidth` - it's hooked into the public `minWidth` input already and ideally will be removed and moved entirely to CSS at some point. Also not even in the `ColumnType` interface
- `gridRowSpan`/`gridColumnSpan` - those are shortcuts to very simple calculations with the `rowStart/End` & `colStart/End` public inputs, …
> docs(column): mark mistakenly left exposed getters as hidden

- projects/igniteui-angular/src/lib/directives/drag-drop/drag-drop.directive.ts
- projects/igniteui-angular/src/lib/splitter/splitter.component.spec.ts
> fix(drag-drop): clear transform style for default position - master

- projects/igniteui-angular/src/lib/directives/drag-drop/drag-drop.directive.ts
- projects/igniteui-angular/src/lib/splitter/splitter.component.spec.ts
> fix(drag-drop): clear transform style for default position - 17.2.x

- projects/igniteui-angular/src/lib/grids/selection/selection.service.ts
- src/app/grid-performance/grid-performance.sample.html
- src/app/grid-performance/grid-performance.sample.ts
> Improve row selection performance when primaryKey is set --18

- projects/igniteui-angular/src/lib/grids/selection/selection.service.ts
- src/app/grid-performance/grid-performance.sample.html
- src/app/grid-performance/grid-performance.sample.ts
> Improve row selection performance when primaryKey is set --17.2

- src/app/overlay/overlay.sample.ts
> fix(overlay-demo): use owner property - master

- src/app/overlay/overlay.sample.ts
> fix(overlay-demo): use owner property - 17.2.x

- src/app/overlay/overlay.sample.ts
> fix(overlay-demo): use owner property - 18.0.x

- projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-row-dimension-header.component.ts
Related to #https://github.com/IgniteUI/igniteui-angular/issues/14281
> build(*): Change pivot row takeUntil import

- projects/igniteui-angular/package.json
Merge just before the official igniteui-angular@18.1.0 release
> chore(schematics): put official schamatics for 18.1

- projects/igniteui-angular/src/lib/navigation-drawer/navigation-drawer.directives.ts
> docs(nav-drawer): show hidden properties

- projects/igniteui-angular/src/lib/grids/grid/grid.multi-row-layout.integration.spec.ts
- projects/igniteui-angular/src/lib/grids/headers/grid-header-group.component.html
> fix(Grid): Fixed duplicate ghosts in MRL

- projects/igniteui-angular/src/lib/grids/grid/grid.component.spec.ts
- projects/igniteui-angular/src/lib/grids/headers/grid-header-group.component.html
> fix(igxGrid): Fix issue with group expanding container.

- ROADMAP.md
> Update README miletone numbering

- projects/igniteui-angular/src/lib/combo/combo.common.ts
- projects/igniteui-angular/src/lib/combo/combo.component.spec.ts
> fix(combo): resolve error in dropdown component by setting id - 18.0.x

- projects/igniteui-angular/src/lib/combo/combo.common.ts
- projects/igniteui-angular/src/lib/combo/combo.component.spec.ts
> fix(combo): resolve error in dropdown component by setting id - 17.2.x

- projects/igniteui-angular/src/lib/combo/combo.common.ts
- projects/igniteui-angular/src/lib/combo/combo.component.spec.ts
> fix(combo): resolve error in dropdown component by setting id - master

- projects/igniteui-angular/src/lib/icon/icon.service.ts
- projects/igniteui-angular/src/lib/icon/reference_table.md
The icon component does not render newly registered icons with addSvgIconFromText when the family is not yet registerd.
Closes #14558
> fix(icon-service): icon not being rendered on addSvgIconFromText

- CHANGELOG.md
- projects/igniteui-angular/src/lib/icon/icon.service.ts
> chore(changelog): add entry related to icon service changes

- projects/igniteui-angular/src/lib/combo/combo.common.ts
- projects/igniteui-angular/src/lib/combo/combo.component.html
- projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid-filtering.spec.ts
- projects/igniteui-angular/src/lib/icon/reference_table.md
- projects/igniteui-angular/src/lib/select/select.component.html
- projects/igniteui-angular/src/lib/select/select.component.ts
- projects/igniteui-angular/src/lib/simple-combo/simple-combo.component.html
- projects/igniteui-angular/src/lib/tree/tree-node/tree-node.component.html
- projects/igniteui-angular/src/lib/tree/tree.component.ts
> refactor(*): update icon reference names for tree, combo and select

- ROADMAP.md
> chore(*): roadmap-update-18.1-release

- projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-grid.interface.ts
Interface has enum values that need additional transformations to work in React.
Related to tfs 32088
> chore(igxPivot): Remove tsPlain due to enum values tranforms.

- projects/igniteui-angular/src/lib/grids/grid-base.directive.ts
> chore(*): Update tags to match model.

- projects/igniteui-angular/src/lib/drop-down/drop-down.base.ts
- projects/igniteui-angular/src/lib/select/select.component.spec.ts
> fix(drop-down): ensure id attribute is set correctly when using bracket syntax - 17.2.x

- README.md
Adding missing brackets
Closes #
> chore(*): update-readme

- ROADMAP.md
adding missing version
Closes #
> chore(*): update-roadmap

- projects/igniteui-angular/src/lib/grids/filtering/base/grid-filtering-row.component.ts
- projects/igniteui-angular/src/lib/grids/grid/grid-filtering-ui.spec.ts
- projects/igniteui-angular/src/lib/test-utils/grid-samples.spec.ts
- projects/igniteui-angular/src/lib/test-utils/sample-test-data.spec.ts
> Allow negative values in filter input - 18.1

- package-lock.json
- package.json
- projects/igniteui-angular/package.json
- projects/igniteui-angular/src/lib/core/styles/components/progress/_progress-theme.scss
- projects/igniteui-angular/src/lib/core/styles/typography/_bootstrap.scss
- projects/igniteui-angular/src/lib/core/styles/typography/_fluent.scss
- projects/igniteui-angular/src/lib/core/styles/typography/_indigo.scss
- projects/igniteui-angular/src/lib/core/styles/typography/_material.scss
> refactor(circular-progress): remove typography

- projects/bundle-test/src/app/app.config.ts
- projects/igniteui-angular/src/lib/services/theme/theme.service.ts
Closes #14612 
So far, couldn't really narrow down as to why the error doesn't cause the entire prerender process to fail on our setup. There are minor diffs in the setup I tried applying back and forth to no effect. Could be route guards (through tried disabling them already) or package versions.
So far the only similar thing I found is https://github.com/angular/angular/issues/47039, so I've taken a similar brute-force error handler that at least seems to ensure a route load failure will fail the SSR/G build.
> SSR error theme service

- projects/igniteui-angular/src/lib/grids/grid/grid-filtering-advanced.spec.ts
- projects/igniteui-angular/src/lib/query-builder/query-builder.component.html
- projects/igniteui-angular/src/lib/query-builder/query-builder.component.ts
- projects/igniteui-angular/src/lib/test-utils/grid-samples.spec.ts
> fix(query-builder): Fix for dateTime's searchValueInput focus -17.2.x

- projects/igniteui-angular/src/lib/input-group/input-group.component.ts
> fix(input-group): theme not read from stylesheet

- projects/igniteui-angular-elements/src/lib/state.component.ts
> fix(state): Add contentParent decorator to grid state

- package-lock.json
- package.json
- projects/igniteui-angular-elements/src/index.html
- projects/igniteui-angular-elements/src/lib/icon.broadcast.service.spec.ts
- projects/igniteui-angular-elements/src/lib/icon.broadcast.service.ts
Assign correct name when name and alias are different.
> fix(elements): broadcast sync assign correct icon name

- projects/igniteui-angular/src/lib/icon/icon.component.ts
- projects/igniteui-angular/src/lib/icon/icon.service.spec.ts
- projects/igniteui-angular/src/lib/icon/icon.service.ts
- src/app/app.component.ts
- src/app/icon/icon.sample.html
- src/app/icon/icon.sample.ts
> fix(icon, icon-service): composite icon families don't work

- projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-grid.interface.ts
Update pivot tags for correct react code exporting.
Related to https://github.com/IgniteUI/igniteui-xplat-examples/pull/689
> chore(*): Mark Pivot interfaces as complex objects.

- projects/igniteui-angular/src/lib/grids/grid/grid-row-selection.spec.ts
- src/app/drop-down/drop-down-virtual/drop-down-virtual.component.ts
- src/app/grid-formatting/grid-formatting.component.ts
- src/app/grid-remote-paging/grid-remote-paging.sample.ts
- src/app/grid-remote-virtualization/grid-remote-virtualization.sample.ts
- src/app/grid-selection/grid-selection.sample.html
- src/app/grid-selection/grid-selection.sample.scss
- src/app/grid-selection/grid-selection.sample.ts
- src/app/hierarchical-grid-remote/hierarchical-grid-remote.sample.ts
- src/app/hierarchical-grid-updating/hierarchical-grid-updating.sample.ts
- src/app/virtual-for-directive/virtual-for.sample.ts
> Test for selected rows after data change & demos fixes

- projects/igniteui-angular/src/lib/core/styles/components/button/_button-theme.scss
- projects/igniteui-angular/src/lib/core/styles/components/input/_input-group-theme.scss
> refactor(themes): fix theme keys in button and input group

- projects/igniteui-angular/src/lib/core/styles/components/progress/_progress-theme.scss
> fix(progress-theme): incorrect scale in indigo theme

- projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-grid-dimensions.ts
- projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-grid.spec.ts
> fix(IgxPivotDateDimension): Add null check.

- projects/igniteui-angular/src/lib/grids/grid/grid.groupby.spec.ts
- projects/igniteui-angular/src/lib/grids/state.directive.ts
- projects/igniteui-angular/src/lib/test-utils/sample-test-data.spec.ts
> Grid groupBy: correctly restore groups expansion state and properly expand/collapse date/time groups after - 17.2.x

- projects/igniteui-angular/src/lib/calendar/days-view/days-view.component.spec.ts
> test(calendar): making tests independent of current calendar date - 18.1

- projects/igniteui-angular/src/lib/calendar/days-view/days-view.component.spec.ts
> test(calendar): making tests independent of current calendar date - 17.2

- projects/igniteui-angular/src/lib/calendar/days-view/days-view.component.spec.ts
> test(calendar): making tests independent of current calendar date - master

- projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-grid-navigation.service.ts
> fix(pivot-grid-navigation): rxjs operators import to support v6

- projects/igniteui-angular/src/lib/core/styles/components/card/_card-theme.scss
- projects/igniteui-angular/src/lib/core/styles/components/list/_list-theme.scss
> refactor(avatar): default size in card and list components

- projects/igniteui-angular/src/lib/services/excel/excel-exporter.spec.ts
- projects/igniteui-angular/src/lib/services/excel/test-data.service.spec.ts
- projects/igniteui-angular/src/lib/services/exporter-common/base-export-service.ts
> fix(excel-export): exportData when columnExporting is canceled - 17.2.x

- projects/igniteui-angular/src/lib/services/excel/excel-exporter.spec.ts
- projects/igniteui-angular/src/lib/services/excel/test-data.service.spec.ts
- projects/igniteui-angular/src/lib/services/exporter-common/base-export-service.ts
> fix(excel-export): exportData when columnExporting is canceled - 18.1.x

- projects/igniteui-angular/src/lib/services/excel/excel-exporter.spec.ts
- projects/igniteui-angular/src/lib/services/excel/test-data.service.spec.ts
- projects/igniteui-angular/src/lib/services/exporter-common/base-export-service.ts
> fix(excel-export): exportData when columnExporting is canceled - master

- projects/igniteui-angular/src/lib/grids/grid-base.directive.ts
Related to #13562, see #14750 for description.
> refactor(grids): move watermark register

- projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-grid-dimensions.ts
- projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-grid.spec.ts
> refactor(pivot): move date dimension enabled set on init

- projects/igniteui-angular/src/lib/grids/grid/grid-filtering-advanced.spec.ts
- projects/igniteui-angular/src/lib/query-builder/query-builder.component.html
> fix(query-builder): prevent aria-hidden error on the edit icon - master

- .github/workflows/codeql-analysis.yml
- SECURITY.md
> ci(security): updating codeql branch versions and security.md

- projects/igniteui-angular/src/lib/grids/grid/grid-filtering-advanced.spec.ts
- projects/igniteui-angular/src/lib/query-builder/query-builder.component.html
> fix(query-builder): prevent aria-hidden error on the edit icon - 18.1.x

- projects/igniteui-angular/src/lib/grids/grid-base.directive.ts
> Add missing blazor attribute for selectedRows prop

- projects/igniteui-angular/src/lib/core/styles/components/navdrawer/_navdrawer-theme.scss
> fix(navdrawer): item size and aside size in mini variant

- projects/igniteui-angular/src/lib/core/styles/components/badge/_badge-theme.scss
> refactor(badge): update padding and display type

- projects/igniteui-angular/src/lib/grids/grid/grid-row-selection.spec.ts
- projects/igniteui-angular/src/lib/grids/selection/selection.service.ts
> Clear selected rows correctly when a row is updated and filtering is applied - 17.2.x

- projects/igniteui-angular/src/lib/grids/grid/grid-row-selection.spec.ts
- projects/igniteui-angular/src/lib/grids/selection/selection.service.ts
> Clear selected rows correctly when a row is updated and filtering is applied - 18.1.x

- .vscode/launch.json
- .vscode/tasks.json
- projects/igniteui-angular/migrations/common/ServerHost.ts
- projects/igniteui-angular/migrations/common/UpdateChanges.ts
- scripts/migrations-sourcemap-shift.mjs
Related to #13712 and picked from #14832 (see for description)
> fix(migrations): fix LS server resolve with schematics encapsulation

- projects/igniteui-angular/src/lib/core/styles/components/navdrawer/_navdrawer-theme.scss
- projects/igniteui-angular/src/lib/navigation-drawer/navigation-drawer.component.spec.ts
> fix(navdrawer): border and transitions

- CHANGELOG.md
- projects/igniteui-angular/migrations/update-18_2_0/changes/theme-changes.json
- projects/igniteui-angular/migrations/update-18_2_0/index.spec.ts
- projects/igniteui-angular/src/lib/badge/badge.component.spec.ts
- projects/igniteui-angular/src/lib/badge/badge.component.ts
- projects/igniteui-angular/src/lib/core/styles/components/badge/_badge-component.scss
- projects/igniteui-angular/src/lib/core/styles/components/badge/_badge-theme.scss
- src/app/badge/badge.sample.html
> feat(badge): implement outlined variant

- projects/igniteui-angular/src/lib/core/styles/components/drop-down/_drop-down-theme.scss
> fix(dropdown): fix icons size in material, bootstrap and fluent themes

- projects/igniteui-angular/src/lib/core/styles/components/tree/_tree-theme.scss
> fix(tree): icon sizes

- projects/igniteui-angular/src/lib/grids/grid/grid-filtering-advanced.spec.ts
- projects/igniteui-angular/src/lib/query-builder/query-builder.component.html
- projects/igniteui-angular/src/lib/test-utils/grid-functions.spec.ts
> Edit and Close buttons now tab indexed properly so that Space/Enter works on them

- projects/igniteui-angular/src/lib/grids/grid/grid-filtering-advanced.spec.ts
- projects/igniteui-angular/src/lib/query-builder/query-builder.component.html
- projects/igniteui-angular/src/lib/test-utils/grid-functions.spec.ts
(cherry picked from commit ab1797b117b1654b899b47f102883af2fee65f9c)
Closes #14861
> fix(query-builder): fix edit/add button event handlers shifted up on parent span

- projects/igniteui-angular-elements/src/lib/icon.broadcast.service.ts
Angular mirror patch of [this](https://github.com/IgniteUI/igniteui-webcomponents/pull/1419).
> refactor(elements): Close icon service broadcast channel on pagehide

- projects/igniteui-angular/src/lib/core/styles/components/chip/_chip-theme.scss
> refactor(chip): fix the selected transition

- projects/igniteui-angular/src/lib/grids/grid/grid.groupby.spec.ts
- projects/igniteui-angular/src/lib/grids/grouping/group-by-area.component.html
> fix(groupby): using pipetrigger for chip titles too

- projects/igniteui-angular/src/lib/core/styles/components/query-builder/_query-builder-theme.scss
- projects/igniteui-angular/src/lib/query-builder/query-builder.component.html
Closes https://github.com/IgniteUI/igniteui-angular/issues/14872
> Fix query builder expression actions

- projects/igniteui-angular/src/lib/core/styles/components/checkbox/_checkbox-theme.scss
- projects/igniteui-angular/src/lib/core/styles/components/column-actions/_column-actions-theme.scss
- projects/igniteui-angular/src/lib/core/styles/components/combo/_combo-theme.scss
- projects/igniteui-angular/src/lib/core/styles/components/grid/_grid-theme.scss
- projects/igniteui-angular/src/lib/core/styles/components/grid/_pivot-data-selector-theme.scss
- projects/igniteui-angular/src/lib/core/styles/components/list/_list-theme.scss
- projects/igniteui-angular/src/lib/core/styles/components/tree/_tree-theme.scss
> fix(checkbox): size and transitions

- projects/igniteui-angular/src/lib/combo/combo.component.ts
> refactor(combo): cleanup unused filtering-related internal props

- projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-grid.component.ts
- projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-grid.spec.ts
> fix(pivot): Fix regresion setting horizontal scrollbar position wrong

- projects/igniteui-angular/src/lib/core/styles/components/grid/_grid-theme.scss
- projects/igniteui-angular/src/lib/grids/grid-base.directive.ts
- projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-grid.component.html
- projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-grid.component.ts
- projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-grid.spec.ts
> fix(pivot): fixed row height to scale with headers

- CHANGELOG.md
> chore(changelog): fix wording and typos regarding theming in 18.2.0

- projects/igniteui-angular/src/lib/calendar/calendar-multi-view.component.spec.ts
- projects/igniteui-angular/src/lib/calendar/calendar.component.spec.ts
- projects/igniteui-angular/src/lib/calendar/calendar.component.ts
- projects/igniteui-angular/src/lib/calendar/days-view/days-view.component.html
- projects/igniteui-angular/src/lib/calendar/days-view/days-view.component.spec.ts
- projects/igniteui-angular/src/lib/date-common/picker-base.directive.ts
- projects/igniteui-angular/src/lib/date-picker/date-picker.component.spec.ts
- projects/igniteui-angular/src/lib/date-picker/date-picker.component.ts
- projects/igniteui-angular/src/lib/date-range-picker/date-range-picker.component.spec.ts
- projects/igniteui-angular/src/lib/date-range-picker/date-range-picker.component.ts
- projects/igniteui-angular/src/lib/grids/filtering/base/grid-filtering-row.component.ts
- projects/igniteui-angular/src/lib/grids/grid/grid-filtering-advanced.spec.ts
- projects/igniteui-angular/src/lib/grids/grid/grid-filtering-ui.spec.ts
- projects/igniteui-angular/src/lib/time-picker/time-picker.component.spec.ts
- projects/igniteui-angular/src/lib/time-picker/time-picker.component.ts
> fix(date-picker): KB nav and calendar focus handling

- projects/igniteui-angular/package.json
> chore(schematics): official @igniteui/angular-schematics

- projects/igniteui-angular/src/lib/core/styles/components/input/_input-group-theme.scss
> fix(textarea): disabled state cursor

- projects/igniteui-angular/src/lib/core/styles/typography/_bootstrap.scss
Related to https://github.com/IgniteUI/igniteui-webcomponents/issues/1401
> fix(expansion-panel): bootstrap typography

- README.md
- ROADMAP.md
> chore(*): roadmap-update-18.2

- package-lock.json
- package.json
- projects/igniteui-angular/src/lib/combo/combo.component.spec.ts
- projects/igniteui-angular/src/lib/grids/grid/grid-filtering-ui.spec.ts
- projects/igniteui-angular/src/lib/grids/grid/grid.search.spec.ts
- projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid-keyBoardNav.spec.ts
This resolves an issue with CI runs failing consistently. See #14971 for more details.
> ci(*): update puppeteer to latest 

- package-lock.json
- package.json
- projects/igniteui-angular/src/lib/combo/combo.component.spec.ts
- projects/igniteui-angular/src/lib/grids/grid/grid-filtering-ui.spec.ts
- projects/igniteui-angular/src/lib/grids/grid/grid.search.spec.ts
- projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid-keyBoardNav.spec.ts
This resolves an issue with CI runs failing consistently from the start of this week:
https://github.com/IgniteUI/igniteui-angular/actions/runs/11553494860/job/32154797381#step:11:2352
```console
28 10 2024 12:07:44.862:ERROR [launcher]: ChromeHeadless crashed.
[2300:2323:1028/120653.689659:ERROR:bus.cc(407)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[2300:2323:1028/120653.689703:ERROR:bus.cc(407)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[2300:2323:1028/120653.693029:ERROR:bus.cc(407)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are …
```
> ci(*): update puppeteer to latest

- projects/igniteui-angular/src/lib/query-builder/query-builder-functions.spec.ts
- projects/igniteui-angular/src/lib/query-builder/query-builder-tree.component.html
- projects/igniteui-angular/src/lib/query-builder/query-builder-tree.component.ts
- projects/igniteui-angular/src/lib/query-builder/query-builder.component.spec.ts
> Query builder simple select from 

- projects/igniteui-angular/src/lib/services/excel/excel-exporter.spec.ts
- projects/igniteui-angular/src/lib/services/excel/test-data.service.spec.ts
- projects/igniteui-angular/src/lib/services/exporter-common/export-utilities.ts
> fix(ExcelExporter): Remove the null char from cell value

- projects/igniteui-angular/src/lib/navigation-drawer/navigation-drawer.component.html
- projects/igniteui-angular/src/lib/navigation-drawer/navigation-drawer.component.spec.ts
- src/app/app.component.html
Change` <aside>` to a simple `<div>,` and remove `role="navigation"` since we're using `<nav>`, which is a semantic tag that doesn’t need to be wrapped in an element with a `role="navigation"`.
Closes https://github.com/IgniteUI/igniteui-angular/issues/14847
> fix(navigation-drawer): fix ARIA role issue warning

- projects/igniteui-angular/src/lib/combo/combo.common.ts
> refactor(combo): only handle selection set in id setter - 17.2.x

- projects/igniteui-angular/src/lib/combo/combo.common.ts
- projects/igniteui-angular/src/lib/combo/combo.component.html
- projects/igniteui-angular/src/lib/combo/combo.component.spec.ts
> fix(combo): update touched property and apply invalid color on blur when required - follow-up - 17.2.x

- projects/igniteui-angular/src/lib/combo/combo.common.ts
- projects/igniteui-angular/src/lib/combo/combo.component.html
- projects/igniteui-angular/src/lib/combo/combo.component.spec.ts
> fix(combo): update touched property and apply invalid color on blur when required - follow-up - 18.2.x

- projects/igniteui-angular/src/lib/grids/grid/grid-filtering-advanced.spec.ts
- projects/igniteui-angular/src/lib/query-builder/query-builder.component.ts
> fix(query-builder): delete empty groups - 17.2.x

- projects/igniteui-angular/src/lib/data-operations/filtering-condition.ts
- projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-filtering.component.ts
- projects/igniteui-angular/src/lib/grids/grid/grid-filtering-ui.spec.ts
- projects/igniteui-angular/src/lib/test-utils/sample-test-data.spec.ts
> Filter grid correctly with case insensitive duplicate records - 17.2

- projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.virtualization.spec.ts
> test(hgrid): fix flicker for scrolling inside hierarchical grid

- projects/igniteui-angular/src/lib/core/styles/components/drop-down/_drop-down-theme.scss
- projects/igniteui-angular/src/lib/core/styles/typography/_bootstrap.scss
- projects/igniteui-angular/src/lib/core/styles/typography/_fluent.scss
- fix unused typography for selected items for all themes
Closes #15004
> fix(dropdown): fix typography for boostrap and fluent themes

- package-lock.json
- package.json
- projects/igniteui-angular/package.json
> deps(theming): bump theming package to version 14.2.0

- projects/igniteui-angular/src/lib/core/styles/components/dialog/_dialog-theme.scss
- projects/igniteui-angular/src/lib/core/styles/typography/_fluent.scss
Closes https://github.com/IgniteUI/igniteui-angular/issues/15002
> fix(dialog): fix dialog discrepancies whit the UI kit

- projects/igniteui-angular/src/lib/slider/slider.component.spec.ts
- projects/igniteui-angular/src/lib/slider/slider.component.ts
> fix(slider): ensure upper thumb reaches maxValue with decimal steps - 17.2.x

- projects/igniteui-angular/src/lib/query-builder/query-builder.component.ts
> fix(query-builder): delete empty groups - 17.2.x 

- projects/igniteui-angular/src/lib/date-picker/date-picker.component.spec.ts
- projects/igniteui-angular/src/lib/date-picker/date-picker.component.ts
> fix(datepicker): fix header title templating

- projects/igniteui-angular/src/lib/date-range-picker/date-range-picker.component.spec.ts
- projects/igniteui-angular/src/lib/date-range-picker/date-range-picker.component.ts
Related to #14918, see #14951 for description.
> fix(date-range): projected input focus restore on consecutive close

- projects/igniteui-angular/src/lib/core/styles/components/list/_list-theme.scss
> refactor(list): item gaps and margins

- projects/igniteui-angular/src/lib/checkbox/checkbox.component.ts
- projects/igniteui-angular/src/lib/core/styles/components/checkbox/_checkbox-component.scss
- projects/igniteui-angular/src/lib/core/styles/components/checkbox/_checkbox-theme.scss
> fix(checkbox): tickmark not rendered correctly in indigo theme

- projects/igniteui-angular/src/lib/core/styles/components/action-strip/_action-strip-component.scss
- projects/igniteui-angular/src/lib/core/styles/components/grid/_grid-component.scss
- projects/igniteui-angular/src/lib/core/styles/components/paginator/_paginator-component.scss
- projects/igniteui-angular/src/lib/core/styles/components/query-builder/_query-builder-component.scss
> fix(themes): add missing igx-icon-button deps

- projects/igniteui-angular/src/lib/directives/drag-drop/drag-drop.directive.ts
- projects/igniteui-angular/src/lib/grids/grid-base.directive.ts
- projects/igniteui-angular/src/lib/grids/moving/moving.drag.directive.ts
- src/app/app.component.ts
- src/app/app.routes.ts
- src/app/grid-re-create/grid-re-create.sample.html
- src/app/grid-re-create/grid-re-create.sample.ts
Closes #13993  
Note: Some elements will still remain detached for the same reasons described here: https://github.com/IgniteUI/igniteui-angular/issues/13994#issuecomment-2419777167
I just noticed some undetached events in the mem. profiler that could be removed, however this will not resolve the issue fully as the core problem for the detached DOM nodes is not on our side.
> fix(moving): Remove some evt listeners and detach subscribers.

- projects/igniteui-angular/src/lib/core/utils.ts
- projects/igniteui-angular/src/lib/directives/for-of/for_of.directive.ts
- projects/igniteui-angular/src/lib/services/animation/angular-animation-player.ts
- projects/igniteui-angular/src/lib/tabs/tabs.directive.ts
- projects/igniteui-angular/src/lib/tabs/tabs/tab-header.component.ts
- projects/igniteui-angular/src/lib/tabs/tabs/tabs.component.ts
> fix(ssr): resize observe and animation player errors 18.2.x

- projects/igniteui-angular/src/lib/core/styles/themes/generators/_base.scss
- projects/igniteui-angular/src/lib/core/styles/themes/generators/_bootstrap.scss
- projects/igniteui-angular/src/lib/core/styles/themes/generators/_fluent.scss
- projects/igniteui-angular/src/lib/core/styles/themes/generators/_indigo.scss
Closes #15092 
Changed colors for indigo themes based on theme specification colors . Now the gray colors are generated in indigo-light and indigo-dark.css files with the correct values - ![image](https://github.com/user-attachments/assets/aaf82bd9-1a1b-4155-9a80-c2938c8eb10c)
Previously these themes were generated with different colors -
> fix(themes): update indigo theme colors

- projects/igniteui-angular/src/lib/core/styles/themes/generators/_base.scss
- projects/igniteui-angular/src/lib/core/styles/themes/generators/_bootstrap.scss
- projects/igniteui-angular/src/lib/core/styles/themes/generators/_fluent.scss
- projects/igniteui-angular/src/lib/core/styles/themes/generators/_indigo.scss
> refactor(themes): update theme preset mixins

- projects/igniteui-angular/src/lib/core/styles/components/dock-manager/_dock-manager-theme.scss
- projects/igniteui-angular/src/lib/core/styles/components/grid/_grid-theme.scss
- projects/igniteui-angular/src/lib/core/styles/components/input/_input-group-theme.scss
- projects/igniteui-angular/src/lib/core/styles/components/list/_list-theme.scss
- projects/igniteui-angular/src/lib/core/styles/components/rating/_rating-theme.scss
- projects/igniteui-angular/src/lib/core/styles/components/scrollbar/scrollbar-theme.scss
- projects/igniteui-angular/src/lib/core/styles/components/tabs/_tabs-theme.scss
- src/app/pageHeading/pageHeading.styles.scss
- src/app/pagination/pagination.styles.scss
- src/app/slider/slider.sample.scss
- src/styles/_demo-theme.scss
> refactor(themes): resolve Sass deprecation warnings

- projects/igniteui-angular/package.json
> chore(schematics): put official version

- projects/igniteui-angular/src/lib/combo/combo.component.html
> fix(combo): move ngIf to search wrapper, not on input group

- ROADMAP.md
> chore(*): update-roadmap-angular-19

- CHANGELOG.md
- projects/igniteui-angular/src/lib/core/styles/themes/generators/_base.scss
- projects/igniteui-angular/src/lib/core/styles/themes/generators/_bootstrap.scss
- projects/igniteui-angular/src/lib/core/styles/themes/generators/_fluent.scss
- projects/igniteui-angular/src/lib/core/styles/themes/generators/_indigo.scss
> fix(themes): wrapping theme mixins don't work with custom palettes

- README.md
> chore(*): readme-update-26-nov-24

- projects/igniteui-angular-i18n/src/i18n/BG/query-builder-resources.ts
- projects/igniteui-angular-i18n/src/i18n/CS/query-builder-resources.ts
- projects/igniteui-angular-i18n/src/i18n/DA/query-builder-resources.ts
- projects/igniteui-angular-i18n/src/i18n/DE/query-builder-resources.ts
- projects/igniteui-angular-i18n/src/i18n/ES/query-builder-resources.ts
- projects/igniteui-angular-i18n/src/i18n/FR/query-builder-resources.ts
- projects/igniteui-angular-i18n/src/i18n/HU/query-builder-resources.ts
- projects/igniteui-angular-i18n/src/i18n/IT/query-builder-resources.ts
- projects/igniteui-angular-i18n/src/i18n/JA/query-builder-resources.ts
- projects/igniteui-angular-i18n/src/i18n/KO/query-builder-resources.ts
- projects/igniteui-angular-i18n/src/i18n/NB/query-builder-resources.ts
- projects/igniteui-angular-i18n/src/i18n/NL/query-builder-resources.ts
- projects/igniteui-angular-i18n/src/i18n/PL/query-builder-resources.ts
- projects/igniteui-angular-i18n/src/i18n/PT/query-builder-resources.ts
- projects/igniteui-angular-i18n/src/i18n/RO/query-builder-resources.ts
- projects/igniteui-angular-i18n/src/i18n/SV/query-builder-resources.ts
- projects/igniteui-angular-i18n/src/i18n/TR/query-builder-resources.ts
- projects/igniteui-angular-i18n/src/i18n/ZH-HANS/query-builder-resources.ts
- projects/igniteui-angular-i18n/src/i18n/ZH-HANT/query-builder-resources.ts
- projects/igniteui-angular/src/lib/core/i18n/query-builder-resources.ts
- projects/igniteui-angular/src/lib/query-builder/query-builder-functions.spec.ts
- projects/igniteui-angular/src/lib/query-builder/query-builder-tree.component.html
- projects/igniteui-angular/src/lib/query-builder/query-builder-tree.component.ts
- projects/igniteui-angular/src/lib/query-builder/query-builder.component.spec.ts
> feat(query-builder): select only one return field in inner query

- projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-conditional-filter.component.ts
- projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-custom-dialog.component.ts
> fix(excel-style-filtering): reset filter value - 18.2.x

- projects/igniteui-angular/src/lib/core/styles/components/tree/_tree-theme.scss
> fix(tree): update checkbox spacing in tree

- projects/igniteui-angular/src/lib/avatar/avatar.component.spec.ts
- projects/igniteui-angular/src/lib/core/utils.ts
- src/app/avatar/avatar.sample.html
> fix(avatar): src with null value throws error

- projects/igniteui-angular/src/lib/card/card.spec.ts
- projects/igniteui-angular/src/lib/core/styles/components/card/_card-theme.scss
> test(card): create test for icon font-family in card content

- projects/igniteui-angular/src/lib/card/card.spec.ts
- projects/igniteui-angular/src/lib/core/styles/components/card/_card-theme.scss
> test(card): add test for icon font-family in card content

- projects/igniteui-angular/src/lib/core/styles/components/avatar/_avatar-theme.scss
> refactor(avatar): remove unused code

- projects/igniteui-angular/src/lib/core/styles/components/combo/_combo-theme.scss
> fix(combo): search input paddings

- projects/igniteui-angular/src/lib/avatar/avatar.component.ts
> fix(avatar): background url broken when scr string contains ( or )

- package-lock.json
- package.json
- projects/igniteui-angular/package.json
- projects/igniteui-angular/src/lib/core/styles/components/checkbox/_checkbox-component.scss
- projects/igniteui-angular/src/lib/core/styles/components/checkbox/_checkbox-theme.scss
Closes #15198 
Related to IgniteUI/igniteui-theming/issues/371
> fix(checkbox): disabled state issues

- projects/igniteui-angular/src/lib/core/styles/base/_mixins.scss
- projects/igniteui-angular/src/lib/core/styles/themes/generators/_base.scss
- projects/igniteui-angular/src/lib/core/styles/themes/generators/_bootstrap.scss
- projects/igniteui-angular/src/lib/core/styles/themes/generators/_fluent.scss
- projects/igniteui-angular/src/lib/core/styles/themes/generators/_indigo.scss
- src/app/styleguide/colors/color.sample.scss
- src/app/styleguide/shadows/shadows.sample.css
- src/styles/_variables.scss
> refactor(themes): update samples and presets

- projects/igniteui-angular/src/lib/core/styles/components/progress/_progress-theme.scss
> fix(linear-progress): fix progress track not changing dir in rtl

- projects/igniteui-angular/src/lib/core/styles/components/checkbox/_checkbox-theme.scss
- projects/igniteui-angular/src/lib/core/styles/components/radio/_radio-theme.scss
- projects/igniteui-angular/src/lib/core/styles/components/switch/_switch-theme.scss
> fix(checkbox/switch/radio): inconsistent cursor

- projects/igniteui-angular/src/lib/core/styles/components/chip/_chip-theme.scss
- projects/igniteui-angular/src/lib/core/styles/components/combo/_combo-theme.scss
- projects/igniteui-angular/src/lib/core/styles/components/grid/_excel-filtering-theme.scss
- projects/igniteui-angular/src/lib/core/styles/components/grid/_grid-theme.scss
> fix(themes): igx-icon gets overridden multiple themes

- projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-custom-dialog.component.ts
- projects/igniteui-angular/src/lib/grids/grid/grid-filtering-ui.spec.ts
> Clear selected condition when clearing the filters #15193

- .github/workflows/codeql-analysis.yml
CodeQL Action v2 is deprecated so updating to v3
https://github.blog/changelog/2024-01-12-code-scanning-deprecation-of-codeql-action-v2/
> ci(*): update to CodeQL Action v3

- projects/igniteui-angular/src/lib/carousel/carousel-base.ts
- projects/igniteui-angular/src/lib/carousel/carousel.component.ts
- projects/igniteui-angular/src/lib/carousel/slide.component.ts
> fix(carousel): inject interface in slide ctor

- projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-custom-dialog.component.html
- projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-custom-dialog.component.ts
- projects/igniteui-angular/src/lib/grids/grid/grid-filtering-ui.spec.ts
> fix(esf): discard filter in esf menu on cancel button click

- projects/igniteui-angular/src/lib/action-strip/action-strip.component.ts
- projects/igniteui-angular/src/lib/action-strip/grid-actions/grid-action-button.component.ts
- projects/igniteui-angular/src/lib/calendar/calendar.component.ts
- projects/igniteui-angular/src/lib/calendar/month-picker/month-picker.component.ts
- projects/igniteui-angular/src/lib/calendar/months-view/months-view.component.ts
- projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-header.component.ts
- projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-row-dimension-header-group.component.ts
- projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-row-dimension-mrl-row.component.ts
- projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-row-header-group.component.ts
- projects/igniteui-angular/src/lib/grids/toolbar/grid-toolbar-advanced-filtering.component.ts
- projects/igniteui-angular/src/lib/grids/toolbar/grid-toolbar-exporter.component.ts
- projects/igniteui-angular/src/lib/icon/icon.component.ts
- projects/igniteui-angular/src/lib/paginator/paginator.component.ts
- tsconfig.json
Picked from #15212
Cleaning up unused standalone imports and setting those those fail compilation if found.
> refactor(*): unused standalone imports cleanup

- projects/igniteui-angular/src/lib/calendar/months-view/months-view.component.html
- projects/igniteui-angular/src/lib/calendar/months-view/months-view.component.ts
- projects/igniteui-angular/src/lib/calendar/years-view/years-view.component.html
- projects/igniteui-angular/src/lib/calendar/years-view/years-view.component.ts
> fix(month-view/year-view): create onMouseDown events

- projects/igniteui-angular/src/lib/core/styles/components/input/_input-group-theme.scss
> fix(input-group): fix helper text spacing in material theme

- projects/igniteui-angular/src/lib/combo/combo-add-item.component.ts
- projects/igniteui-angular/src/lib/core/styles/components/combo/_combo-theme.scss
> fix(combo): update styles of igx-combo-add-item

- projects/igniteui-angular/src/lib/query-builder/query-builder-tree.component.html
- projects/igniteui-angular/src/lib/query-builder/query-builder-tree.component.ts
- projects/igniteui-angular/src/lib/query-builder/query-builder.component.spec.ts
- projects/igniteui-angular/src/lib/query-builder/query-builder.component.ts
> Adding `disableEntityChange` property

- projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-data-selector.component.ts
> chore(pivot): data selector analyzer tag

- projects/igniteui-angular/src/lib/query-builder/query-builder-functions.spec.ts
- projects/igniteui-angular/src/lib/query-builder/query-builder-tree.component.html
- projects/igniteui-angular/src/lib/query-builder/query-builder-tree.component.ts
- projects/igniteui-angular/src/lib/query-builder/query-builder.component.spec.ts
> feat(query-builder): focus last edited expression chip

- projects/igniteui-angular/src/lib/core/styles/components/icon-button/_icon-button-theme.scss
> fix(icon-button): remove z-index to material outlined button

- projects/igniteui-angular/src/lib/checkbox/checkbox.component.ts
- projects/igniteui-angular/src/lib/checkbox/public_api.ts
- projects/igniteui-angular/src/lib/directives/radio/radio-group.directive.ts
- projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-search.component.ts
- projects/igniteui-angular/src/public_api.ts
Closes [15337](https://github.com/IgniteUI/igniteui-angular/issues/15337)
> fix(checkbox): add back LabelPosition to exported members

- projects/igniteui-angular/src/lib/grids/common/crud.service.ts
- projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid-add-row-ui.spec.ts
> fix(igxTreeGrid): Re-eval correct row after collapsing. Add test.

- projects/igniteui-angular/src/lib/badge/badge.component.ts
- projects/igniteui-angular/src/lib/core/styles/themes/generators/_base.scss
- projects/igniteui-angular/src/lib/dialog/dialog.component.scss
- projects/igniteui-angular/src/lib/dialog/dialog.component.ts
- projects/igniteui-angular/src/lib/dialog/themes/_base.scss
- projects/igniteui-angular/src/lib/dialog/themes/dark/_index.scss
- projects/igniteui-angular/src/lib/dialog/themes/dark/_tokens.scss
- projects/igniteui-angular/src/lib/dialog/themes/light/_index.scss
- projects/igniteui-angular/src/lib/dialog/themes/light/_tokens.scss
- projects/igniteui-angular/src/lib/dialog/themes/shared/_index.scss
- projects/igniteui-angular/src/lib/dialog/themes/shared/bootstrap.scss
- projects/igniteui-angular/src/lib/dialog/themes/shared/fluent.scss
- projects/igniteui-angular/src/lib/dialog/themes/shared/indigo.scss
- projects/igniteui-angular/src/lib/dialog/themes/shared/material.scss
> refactor(dialog): bundle styles with component

- projects/igniteui-angular/src/lib/core/styles/themes/generators/_base.scss
- projects/igniteui-angular/src/lib/core/styles/typography/_bootstrap.scss
- projects/igniteui-angular/src/lib/core/styles/typography/_fluent.scss
- projects/igniteui-angular/src/lib/core/styles/typography/_indigo.scss
- projects/igniteui-angular/src/lib/core/styles/typography/_material.scss
- projects/igniteui-angular/src/lib/toast/themes/_base.scss
- projects/igniteui-angular/src/lib/toast/themes/dark/_index.scss
- projects/igniteui-angular/src/lib/toast/themes/dark/_tokens.scss
- projects/igniteui-angular/src/lib/toast/themes/light/_index.scss
- projects/igniteui-angular/src/lib/toast/themes/light/_tokens.scss
- projects/igniteui-angular/src/lib/toast/themes/shared/_bootstrap.scss
- projects/igniteui-angular/src/lib/toast/themes/shared/_fluent.scss
- projects/igniteui-angular/src/lib/toast/themes/shared/_index.scss
- projects/igniteui-angular/src/lib/toast/toast.component.scss
- projects/igniteui-angular/src/lib/toast/toast.component.ts
Closes [#15324](https://github.com/IgniteUI/igniteui-angular/issues/15324)
> refactor(toast): bundle styles with component

- projects/igniteui-angular/src/lib/directives/button/button.directive.ts
- projects/igniteui-angular/src/lib/input-group/input-group.component.ts
> fix(mem-leak): Fix potential memory leaks.

- projects/igniteui-angular/src/lib/query-builder/query-builder-drag.service.ts
- projects/igniteui-angular/src/lib/query-builder/query-builder-tree.component.ts
- projects/igniteui-angular/src/lib/query-builder/query-builder.component.spec.ts
After a successful drag&drop, the subjected chip is focused
> Query-Builder Focus on dropped chip after Drag&Drop

- projects/igniteui-angular/src/lib/core/styles/themes/generators/_base.scss
- projects/igniteui-angular/src/lib/navbar/navbar.component.scss
- projects/igniteui-angular/src/lib/navbar/navbar.component.ts
- projects/igniteui-angular/src/lib/navbar/themes/_base.scss
- projects/igniteui-angular/src/lib/navbar/themes/dark/_index.scss
- projects/igniteui-angular/src/lib/navbar/themes/dark/_tokens.scss
- projects/igniteui-angular/src/lib/navbar/themes/light/_index.scss
- projects/igniteui-angular/src/lib/navbar/themes/light/_tokens.scss
- projects/igniteui-angular/src/lib/navbar/themes/shared/_bootstrap.scss
- projects/igniteui-angular/src/lib/navbar/themes/shared/_fluent.scss
- projects/igniteui-angular/src/lib/navbar/themes/shared/_index.scss
- projects/igniteui-angular/src/lib/navbar/themes/shared/_indigo.scss
- projects/igniteui-angular/src/lib/navbar/themes/shared/_material.scss
> refactor(navbar): bundle styles with component

- projects/igniteui-angular/src/lib/combo/combo.component.html
- projects/igniteui-angular/src/lib/input-group/input-group.component.ts
> fix(combo): fix combo search input theme and type

- projects/igniteui-angular/src/lib/core/styles/themes/generators/_base.scss
- projects/igniteui-angular/src/lib/core/styles/typography/_fluent.scss
- projects/igniteui-angular/src/lib/core/styles/typography/_indigo.scss
- projects/igniteui-angular/src/lib/core/styles/typography/_material.scss
- projects/igniteui-angular/src/lib/snackbar/snackbar.component.scss
- projects/igniteui-angular/src/lib/snackbar/snackbar.component.ts
- projects/igniteui-angular/src/lib/snackbar/themes/_base.scss
- projects/igniteui-angular/src/lib/snackbar/themes/dark/_index.scss
- projects/igniteui-angular/src/lib/snackbar/themes/dark/_tokens.scss
- projects/igniteui-angular/src/lib/snackbar/themes/light/_index.scss
- projects/igniteui-angular/src/lib/snackbar/themes/light/_tokens.scss
- projects/igniteui-angular/src/lib/snackbar/themes/shared/_fluent.scss
- projects/igniteui-angular/src/lib/snackbar/themes/shared/_index.scss
- projects/igniteui-angular/src/lib/snackbar/themes/shared/_indigo.scss
Closes[#15325](https://github.com/IgniteUI/igniteui-angular/issues/15325)
> refactor(snackbar): bundle styles with component

- projects/igniteui-angular-elements/src/themes/light/fluent.scss
> fix(elements): fluent light theme duplication

- projects/igniteui-angular/src/lib/grids/filtering/excel-style/common.ts
- projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-custom-dialog.component.html
- projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-search.component.html
- projects/igniteui-angular/src/lib/grids/grid/grid.multi-row-layout.integration.spec.ts
- projects/igniteui-angular/src/lib/grids/grid/grid.multi-row-layout.spec.ts
- projects/igniteui-angular/src/lib/query-builder/query-builder.component.html
- projects/igniteui-angular/src/lib/query-builder/query-builder.component.ts
- projects/igniteui-angular/src/lib/test-utils/grid-samples.spec.ts
> Resolve control flow warnings in grid and tree grid.

- projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-data-selector.component.html
- projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-grid.component.html
- projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-grid.interface.ts
- projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-header-row.component.html
- projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-row-dimension-mrl-row.component.html
- projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-row-dimension-mrl-row.component.ts
> chore(*): Add better identity tracking in pivot templates.

- projects/igniteui-angular/src/lib/core/styles/components/chip/_chip-theme.scss
> fix(chip): wrong colors

- projects/igniteui-angular/src/lib/time-picker/time-picker.component.spec.ts
- projects/igniteui-angular/src/lib/time-picker/time-picker.component.ts
> fix(time-picker): exclude from SSR toggle events #15135

- projects/igniteui-angular/src/lib/time-picker/time-picker.component.spec.ts
- projects/igniteui-angular/src/lib/time-picker/time-picker.component.ts
Closes #15158
Description in PR https://github.com/IgniteUI/igniteui-angular/pull/15367
> Ensure hours stay clamped within 0-23 when interacting with AM/PM - 19.0.x

- projects/igniteui-angular/src/lib/time-picker/time-picker.component.spec.ts
- projects/igniteui-angular/src/lib/time-picker/time-picker.component.ts
Closes https://github.com/IgniteUI/igniteui-angular/issues/15158
The problem was that during interaction of AM/PM the hours would go over `23` and below `0`, which would result in the JS date looping to the next and previous days respectively. 
This would cause problems in the logic when displaying the spinners. In the first case the `TimeItemPipe` would receive a wrong date (the following day) which would cause the `generateMinutes` method to fail to add the minute elements to the spinner.
Here `time` is calculated by extracting the values from the spinners and inserting them in a date object that is later given to the pipe. So this check would always fail since `time` would be the tomorrow's date (because of the looping that occurs after the interaction with `PM`) and `max` would be the …
> Ensure hours stay clamped within 0-23 when interacting with AM/PM

- projects/igniteui-angular/src/lib/badge/themes/_base.scss
- projects/igniteui-angular/src/lib/core/styles/themes/_core.scss
- projects/igniteui-angular/src/lib/core/styles/themes/generators/_base.scss
- projects/igniteui-angular/src/lib/core/styles/typography/_bootstrap.scss
- projects/igniteui-angular/src/lib/core/styles/typography/_fluent.scss
- projects/igniteui-angular/src/lib/core/styles/typography/_indigo.scss
- projects/igniteui-angular/src/lib/core/styles/typography/_material.scss
- projects/igniteui-angular/src/lib/navigation-drawer/navigation-drawer.component.scss
- projects/igniteui-angular/src/lib/navigation-drawer/navigation-drawer.component.spec.ts
- projects/igniteui-angular/src/lib/navigation-drawer/navigation-drawer.component.ts
- projects/igniteui-angular/src/lib/navigation-drawer/navigation-drawer.directives.ts
- projects/igniteui-angular/src/lib/navigation-drawer/themes/_base.scss
- projects/igniteui-angular/src/lib/navigation-drawer/themes/dark/_index.scss
- projects/igniteui-angular/src/lib/navigation-drawer/themes/dark/_tokens.scss
- projects/igniteui-angular/src/lib/navigation-drawer/themes/light/_index.scss
- projects/igniteui-angular/src/lib/navigation-drawer/themes/light/_tokens.scss
- projects/igniteui-angular/src/lib/navigation-drawer/themes/shared/_bootstrap.scss
- projects/igniteui-angular/src/lib/navigation-drawer/themes/shared/_fluent.scss
- projects/igniteui-angular/src/lib/navigation-drawer/themes/shared/_index.scss
- projects/igniteui-angular/src/lib/navigation-drawer/themes/shared/_indigo.scss
- projects/igniteui-angular/src/lib/navigation-drawer/themes/shared/_material.scss
- src/app/app.component.html
> refactor(navdrawer): bundle styles with component

- projects/igniteui-angular/src/lib/grids/moving/moving.drag.directive.ts
> fix(moving-dir): takeUntil import compatible with rxjs 6

- projects/igniteui-angular/src/lib/grids/moving/moving.drag.directive.ts
> fix(moving-dir): takeUntil import compatible with rxjs 6 - 19.0.x

- projects/igniteui-angular/src/lib/data-operations/expressions-tree-util.spec.ts
- projects/igniteui-angular/src/lib/data-operations/filtering-condition.ts
- projects/igniteui-angular/src/lib/query-builder/query-builder-functions.spec.ts
- projects/igniteui-angular/src/lib/query-builder/query-builder-tree.component.html
- projects/igniteui-angular/src/lib/query-builder/query-builder-tree.component.ts
- projects/igniteui-angular/src/lib/query-builder/query-builder.component.spec.ts
- src/app/query-builder/query-builder.sample.ts
> fix(*): Renamed nested query condtions

- projects/igniteui-angular/src/lib/core/styles/components/combo/_combo-theme.scss
> fix(combo): fix hover state for clear icon in disabled combo

- projects/igniteui-angular/src/lib/checkbox/public_api.ts
> fix(checkbox): export the LabelPosition as constant

- projects/igniteui-angular/src/lib/calendar/days-view/day-item.component.ts
Closes https://github.com/IgniteUI/igniteui-angular/issues/15416
> fix(days-view): Update day-item selection logic to include preview range

- projects/igniteui-angular/package.json
> chore(schematics): update @igniteui/angular-schematics

- SECURITY.md
> docs(*): updating security file

- projects/igniteui-angular/src/lib/banner/banner.component.spec.ts
- projects/igniteui-angular/src/lib/card/card.component.scss
- projects/igniteui-angular/src/lib/card/card.component.ts
- projects/igniteui-angular/src/lib/card/themes/_base.scss
- projects/igniteui-angular/src/lib/card/themes/dark/_index.scss
- projects/igniteui-angular/src/lib/card/themes/dark/_tokens.scss
- projects/igniteui-angular/src/lib/card/themes/light/_index.scss
- projects/igniteui-angular/src/lib/card/themes/light/_tokens.scss
- projects/igniteui-angular/src/lib/card/themes/shared/_bootstrap.scss
- projects/igniteui-angular/src/lib/card/themes/shared/_fluent.scss
- projects/igniteui-angular/src/lib/card/themes/shared/_index.scss
- projects/igniteui-angular/src/lib/card/themes/shared/_indigo.scss
- projects/igniteui-angular/src/lib/card/themes/shared/_material.scss
- projects/igniteui-angular/src/lib/core/styles/themes/generators/_base.scss
- projects/igniteui-angular/src/lib/core/styles/typography/_bootstrap.scss
- projects/igniteui-angular/src/lib/core/styles/typography/_fluent.scss
- projects/igniteui-angular/src/lib/core/styles/typography/_indigo.scss
- projects/igniteui-angular/src/lib/core/styles/typography/_material.scss
- src/app/card/card.sample.html
- src/app/card/card.sample.ts
- src/app/tooltip/tooltip.sample.html
> refactor(card): bundle styles with component

- projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-filtering.component.ts
- projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid-filtering.spec.ts
> fix(esf): prevent error for untyped non-string columns when filtering grid

- projects/igniteui-angular/src/lib/simple-combo/simple-combo.component.spec.ts
- projects/igniteui-angular/src/lib/simple-combo/simple-combo.component.ts
Closes https://github.com/IgniteUI/igniteui-angular/issues/14791
> Fixing tab navigation in simple combo - 19.1

- projects/igniteui-angular/src/lib/core/styles/components/avatar/_avatar-theme.scss
> feat(avatar): improve avatar theme

- projects/igniteui-angular-elements/src/public_api.ts
- projects/igniteui-angular/src/lib/data-operations/filtering-condition.ts
- projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid-base.directive.ts
- projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-grid.component.ts
> API analyzer adjustments

- projects/igniteui-angular/src/lib/banner/banner.component.scss
- projects/igniteui-angular/src/lib/banner/banner.component.ts
- projects/igniteui-angular/src/lib/banner/themes/_base.scss
- projects/igniteui-angular/src/lib/banner/themes/dark/_index.scss
- projects/igniteui-angular/src/lib/banner/themes/dark/_tokens.scss
- projects/igniteui-angular/src/lib/banner/themes/light/_index.scss
- projects/igniteui-angular/src/lib/banner/themes/light/_tokens.scss
- projects/igniteui-angular/src/lib/banner/themes/shared/_fluent.scss
- projects/igniteui-angular/src/lib/banner/themes/shared/_index.scss
- projects/igniteui-angular/src/lib/banner/themes/shared/_indigo.scss
- projects/igniteui-angular/src/lib/core/styles/themes/generators/_base.scss
- projects/igniteui-angular/src/lib/core/styles/typography/_bootstrap.scss
- projects/igniteui-angular/src/lib/core/styles/typography/_fluent.scss
- projects/igniteui-angular/src/lib/core/styles/typography/_indigo.scss
- projects/igniteui-angular/src/lib/core/styles/typography/_material.scss
Closes [15258](https://github.com/IgniteUI/igniteui-angular/issues/15258)
> refactor(banner): bundle styles with component

- projects/igniteui-angular/src/lib/carousel/carousel.component.spec.ts
- projects/igniteui-angular/src/lib/carousel/carousel.component.ts
> fix(carousel): mark for check when active slide change - master

- projects/igniteui-angular/src/lib/core/styles/themes/generators/_base.scss
- projects/igniteui-angular/src/lib/splitter/splitter-bar.component.html
- projects/igniteui-angular/src/lib/splitter/splitter.component.scss
- projects/igniteui-angular/src/lib/splitter/splitter.component.spec.ts
- projects/igniteui-angular/src/lib/splitter/splitter.component.ts
- projects/igniteui-angular/src/lib/splitter/themes/_base.scss
- projects/igniteui-angular/src/lib/splitter/themes/dark/_index.scss
- projects/igniteui-angular/src/lib/splitter/themes/dark/_tokens.scss
- projects/igniteui-angular/src/lib/splitter/themes/light/_index.scss
- projects/igniteui-angular/src/lib/splitter/themes/light/_tokens.scss
- projects/igniteui-angular/src/lib/splitter/themes/shared/_index.scss
- projects/igniteui-angular/src/lib/splitter/themes/shared/indigo.scss
Closes [#15439](https://github.com/IgniteUI/igniteui-angular/issues/15439)
> refactor(splitter): bundle styles with component

- projects/igniteui-angular/src/lib/core/styles/components/grid/_pivot-data-selector-theme.scss
- projects/igniteui-angular/src/lib/core/styles/components/icon-button/_icon-button-theme.scss
- projects/igniteui-angular/src/lib/core/styles/themes/generators/_base.scss
- projects/igniteui-angular/src/lib/core/styles/typography/_bootstrap.scss
- projects/igniteui-angular/src/lib/core/styles/typography/_fluent.scss
- projects/igniteui-angular/src/lib/core/styles/typography/_indigo.scss
- projects/igniteui-angular/src/lib/core/styles/typography/_material.scss
- projects/igniteui-angular/src/lib/expansion-panel/expansion-panel-header.component.html
- projects/igniteui-angular/src/lib/expansion-panel/expansion-panel.component.scss
- projects/igniteui-angular/src/lib/expansion-panel/expansion-panel.component.ts
- projects/igniteui-angular/src/lib/expansion-panel/expansion-panel.spec.ts
- projects/igniteui-angular/src/lib/expansion-panel/themes/_base.scss
- projects/igniteui-angular/src/lib/expansion-panel/themes/dark/_index.scss
- projects/igniteui-angular/src/lib/expansion-panel/themes/dark/_tokens.scss
- projects/igniteui-angular/src/lib/expansion-panel/themes/light/_index.scss
- projects/igniteui-angular/src/lib/expansion-panel/themes/light/_tokens.scss
- projects/igniteui-angular/src/lib/expansion-panel/themes/shared/_index.scss
- projects/igniteui-angular/src/lib/expansion-panel/themes/shared/bootstrap.scss
- projects/igniteui-angular/src/lib/expansion-panel/themes/shared/fluent.scss
- projects/igniteui-angular/src/lib/expansion-panel/themes/shared/indigo.scss
- projects/igniteui-angular/src/lib/expansion-panel/themes/shared/material.scss
- src/app/accordion/accordion.sample.scss
Closes [#15433](https://github.com/IgniteUI/igniteui-angular/issues/15433)
> refactor(expansion-panel): bundle styles with component

- package-lock.json
- package.json
- projects/igniteui-angular/migrations/migration-collection.json
- projects/igniteui-angular/migrations/update-19_1_4/changes/theme-changes.json
- projects/igniteui-angular/migrations/update-19_1_4/index.spec.ts
- projects/igniteui-angular/migrations/update-19_1_4/index.ts
- projects/igniteui-angular/package.json
- projects/igniteui-angular/src/lib/core/styles/components/grid/_grid-theme.scss
> fix(grid-summaries): themes params not fully working

- projects/igniteui-angular/src/lib/data-operations/expressions-tree-util.ts
- projects/igniteui-angular/src/lib/data-operations/filtering-expression.interface.ts
- projects/igniteui-angular/src/lib/data-operations/filtering-expressions-tree.ts
- projects/igniteui-angular/src/lib/grids/grid-base.directive.ts
> Fix filtering expression throwing error with no columns. Related fixes for elements Blazor grid.

- projects/igniteui-angular/src/lib/core/styles/themes/generators/_base.scss
- projects/igniteui-angular/src/lib/core/styles/typography/_bootstrap.scss
- projects/igniteui-angular/src/lib/core/styles/typography/_fluent.scss
- projects/igniteui-angular/src/lib/core/styles/typography/_indigo.scss
- projects/igniteui-angular/src/lib/core/styles/typography/_material.scss
- projects/igniteui-angular/src/lib/slider/slider.component.scss
- projects/igniteui-angular/src/lib/slider/slider.component.spec.ts
- projects/igniteui-angular/src/lib/slider/slider.component.ts
- projects/igniteui-angular/src/lib/slider/themes/_base.scss
- projects/igniteui-angular/src/lib/slider/themes/dark/_index.scss
- projects/igniteui-angular/src/lib/slider/themes/dark/_tokens.scss
- projects/igniteui-angular/src/lib/slider/themes/light/_index.scss
- projects/igniteui-angular/src/lib/slider/themes/light/_tokens.scss
- projects/igniteui-angular/src/lib/slider/themes/shared/_bootstrap.scss
- projects/igniteui-angular/src/lib/slider/themes/shared/_fluent.scss
- projects/igniteui-angular/src/lib/slider/themes/shared/_index.scss
- projects/igniteui-angular/src/lib/slider/themes/shared/_indigo.scss
- projects/igniteui-angular/src/lib/slider/themes/shared/_material.scss
- projects/igniteui-angular/src/lib/slider/ticks/ticks.component.html
- projects/igniteui-angular/src/lib/slider/ticks/ticks.component.ts
> refactor(slider): bundle styles with component

- projects/igniteui-angular/src/lib/core/styles/components/grid/_grid-theme.scss
> [Grid]: fix sorting icon color

- projects/igniteui-angular/src/lib/query-builder/query-builder-functions.spec.ts
- projects/igniteui-angular/src/lib/query-builder/query-builder.component.spec.ts
A long running drag and drop test is broken down in four parts to optimize resource use and running time. Hopefully will fix test disconnecting issues.
> fix(query-builder): refactor drag and drop test - 19.1.x

- projects/igniteui-angular/src/lib/core/styles/components/query-builder/_query-builder-theme.scss
> Query Builder - fix keyboard ghost text color

- projects/igniteui-angular/src/lib/core/styles/components/chip/_chip-theme.scss
> bug(chips): fix progressbar size

- projects/igniteui-angular/src/lib/core/styles/components/tree/_tree-theme.scss
> [tree] - fix igx-circular-bar in context of tree component

- projects/igniteui-angular/src/lib/core/styles/components/rating/_rating-theme.scss
> refactor(rating): bundle styles with component

- package-lock.json
- package.json
- projects/igniteui-angular/migrations/migration-collection.json
- projects/igniteui-angular/migrations/update-19_1_6/changes/theme-changes.json
- projects/igniteui-angular/migrations/update-19_1_6/index.spec.ts
- projects/igniteui-angular/migrations/update-19_1_6/index.ts
- projects/igniteui-angular/package.json
- projects/igniteui-angular/src/lib/core/styles/components/switch/_switch-component.scss
- projects/igniteui-angular/src/lib/core/styles/components/switch/_switch-theme.scss
Related to IgniteUI/igniteui-theming/issues/382
> refactor(switch): remove invalid state properties

- package-lock.json
- package.json
- projects/igniteui-angular/package.json
> deps(theming): bump to latest version

- projects/igniteui-angular/src/lib/data-operations/filtering-expressions-tree.ts
> Additional fix for enabling filtering expressions to generate as classes in React.

- projects/igniteui-angular/src/lib/grids/hierarchical-grid/events.ts
- projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.component.ts
- projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.pipes.ts
- projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.spec.ts
> feat(hierarchical-grid): add parentRowData to IGridCreatedEventArgs

- projects/igniteui-angular/src/lib/core/styles/themes/generators/_base.scss
- projects/igniteui-angular/src/lib/paginator/paginator.component.scss
- projects/igniteui-angular/src/lib/paginator/paginator.component.ts
- projects/igniteui-angular/src/lib/paginator/themes/_base.scss
- projects/igniteui-angular/src/lib/paginator/themes/dark/_index.scss
- projects/igniteui-angular/src/lib/paginator/themes/dark/_tokens.scss
- projects/igniteui-angular/src/lib/paginator/themes/light/_index.scss
- projects/igniteui-angular/src/lib/paginator/themes/light/_tokens.scss
- projects/igniteui-angular/src/lib/paginator/themes/shared/_index.scss
- projects/igniteui-angular/src/lib/paginator/themes/shared/_indigo.scss
> refactor(paginator): bundle styles with component

- projects/igniteui-angular/src/lib/core/styles/components/calendar/_calendar-component.scss
- projects/igniteui-angular/src/lib/core/styles/components/calendar/_calendar-theme.scss
Closes [#15409](https://github.com/IgniteUI/igniteui-angular/issues/15409)
> [calendar]: fix range preview inactive dates text color

- projects/igniteui-angular/src/lib/chips/themes/shared/_bootstrap.scss
> refactor(chip): apply latest bootstrap changes

- projects/igniteui-angular/src/lib/core/styles/components/icon-button/_icon-button-theme.scss
- projects/igniteui-angular/src/lib/navbar/navbar.component.html
- projects/igniteui-angular/src/lib/navbar/navbar.component.ts
- projects/igniteui-angular/src/lib/navbar/themes/_base.scss
- projects/igniteui-angular/src/lib/navbar/themes/shared/_bootstrap.scss
- projects/igniteui-angular/src/lib/navbar/themes/shared/_indigo.scss
Related to https://github.com/IgniteUI/igniteui-angular/issues/13770#issuecomment-2764802566
> fix(navbar): nested components sizes

- src/app/hierarchical-grid-remote-virtualization/hierarchical-grid-remote-virtualization.ts
> fix(hgrid): provide HierarchicalRemoteService to the Remote Virtualization demo

- projects/igniteui-angular/src/lib/core/styles/components/avatar/_avatar-theme.scss
- projects/igniteui-angular/src/lib/core/styles/components/badge/_badge-theme.scss
> feat(badge): improve badge theme

- projects/igniteui-angular/src/lib/core/styles/components/calendar/_calendar-component.scss
- projects/igniteui-angular/src/lib/core/styles/components/calendar/_calendar-theme.scss
Closes #15544
This pr also fixes some minor color inconsistencies in the fluent theme
> fix(calendar): range radius 

- projects/igniteui-angular/src/lib/action-strip/themes/_base.scss
- projects/igniteui-angular/src/lib/card/themes/_base.scss
- src/app/grid/grid.sample.html
- src/app/tooltip/tooltip.sample.html
> fix(card): action-color not working

- projects/igniteui-angular/src/lib/core/styles/components/action-strip/_action-strip-theme.scss
- projects/igniteui-angular/src/lib/core/styles/components/card/_card-theme.scss
> fix(card/action-strip): not working properties

- projects/igniteui-angular/src/lib/splitter/splitter.component.spec.ts
- projects/igniteui-angular/src/lib/splitter/splitter.component.ts
> Sizing panes corectly with minSize and the browser is shrinked - 18.2.x

- projects/igniteui-angular/src/lib/splitter/splitter.component.spec.ts
- projects/igniteui-angular/src/lib/splitter/splitter.component.ts
>  Sizing panes correctly with minSize is used when the browser is shrinked

- package-lock.json
- package.json
- projects/igniteui-angular/package.json
- projects/igniteui-angular/src/lib/core/styles/components/input/_input-group-theme.scss
Related to IgniteUI/igniteui-theming/issues/393
> fix(input-group): fluent theme discrepancies

- projects/igniteui-angular/src/lib/data-operations/filtering-strategy.ts
> fix(15674): ESF to show unique time values

- projects/igniteui-angular/src/lib/core/styles/components/expansion-panel/_expansion-panel-theme.scss
> feat(expansion-panel): improve expansion-panel theme

- projects/igniteui-angular/src/lib/core/styles/components/dialog/_dialog-theme.scss
> feat(dialog): update dialog theme to use adaptive-contrast function

- projects/igniteui-angular/src/lib/core/styles/components/action-strip/_action-strip-theme.scss
> feat(action-strip): update text contrast function

- projects/igniteui-angular/src/lib/core/styles/components/card/_card-theme.scss
> feat(card): improve card theme

- projects/igniteui-angular/src/lib/core/styles/components/bottom-nav/_bottom-nav-theme.scss
> feat(bottom-nav): improve bottom-nav theme

- projects/igniteui-angular/src/lib/core/styles/components/navbar/_navbar-theme.scss
> feat(navbar): improve navbar theme

- projects/igniteui-angular/src/lib/core/styles/components/navdrawer/_navdrawer-theme.scss
> feat(navdrawer): improve navdrawer theme

- projects/igniteui-angular/src/lib/core/styles/components/tree/_tree-theme.scss
> feat(tree): improve tree theme

- projects/igniteui-angular/src/lib/core/styles/components/time-picker/_time-picker-theme.scss
> feat(time-picker): improve time-picker theme

- projects/igniteui-angular/src/lib/core/styles/components/snackbar/_snackbar-theme.scss
> feat(snackbar): improve snackbar theme

- projects/igniteui-angular/src/lib/core/styles/components/splitter/_splitter-theme.scss
> feat(splitter): improve splitter theme

- projects/igniteui-angular/src/lib/core/styles/components/toast/_toast-theme.scss
> feat(toast): improve toast theme

- CHANGELOG.md
> docs(changelog): adding changelog for paging mode change

- projects/igniteui-angular/src/lib/core/styles/components/chip/_chip-theme.scss
> feat(chip): improve chip custom theme functions

- projects/igniteui-angular/src/lib/core/styles/components/icon-button/_icon-button-theme.scss
> feat(icon-button): fix focus styles not showing

- projects/igniteui-angular/src/lib/core/styles/components/grid-summary/_grid-summary-theme.scss
> feat(grid-summary): improve grid-summary theme

- projects/igniteui-angular/src/lib/core/styles/components/grid-toolbar/_grid-toolbar-theme.scss
> feat(grid-toolbar): improve grid-toolbar-theme

- projects/igniteui-angular/src/lib/core/styles/components/list/_list-theme.scss
> feat(list): improve list theme

- projects/igniteui-angular/src/lib/core/styles/components/icon-button/_contained-icon-button-theme.scss
- projects/igniteui-angular/src/lib/core/styles/components/icon-button/_flat-icon-button-theme.scss
- projects/igniteui-angular/src/lib/core/styles/components/icon-button/_icon-button-theme.scss
- projects/igniteui-angular/src/lib/core/styles/components/icon-button/_outlined-icon-button-theme.scss
- projects/igniteui-angular/src/lib/core/styles/themes/generators/_base.scss
> feat(icon-button): improve icon-button themes

- projects/igniteui-angular/src/lib/core/styles/components/select/_select-theme.scss
> feat(select): improve select theme

- projects/igniteui-angular/src/lib/core/styles/components/input/_input-group-theme.scss
> fix(input): label color issue

- .github/workflows/codeql-analysis.yml
> fix(ci): modifying branches for codeql

- README.md
> chore(*)-update-readme-19.2

- projects/igniteui-angular/src/lib/services/csv/char-separated-value-data.ts
- projects/igniteui-angular/src/lib/services/csv/csv-exporter-grid.spec.ts
- projects/igniteui-angular/src/lib/services/csv/csv-exporter.ts
- projects/igniteui-angular/src/lib/services/csv/csv-verification-wrapper.spec.ts
- projects/igniteui-angular/src/lib/services/exporter-common/base-export-service.ts
> Print row dimensions to CSV properly.

- ROADMAP.md
> chore(*): update-roadmap-22-apr-2025

- src/app/chips/chips.sample.html
> fix(chips-sample): unwrap prefix and suffix icons in wc so they're centered

- projects/igniteui-angular/src/lib/directives/text-highlight/text-highlight.directive.spec.ts
- projects/igniteui-angular/src/lib/directives/text-highlight/text-highlight.directive.ts
> fix(Highlight): Check if the highlight group exists before activation.

- projects/igniteui-angular/src/lib/directives/tooltip/tooltip-target.directive.ts
- projects/igniteui-angular/src/lib/directives/tooltip/tooltip.directive.spec.ts
- projects/igniteui-angular/src/lib/test-utils/tooltip-components.spec.ts
> Hide the tooltip on destroying its target.

- projects/igniteui-angular/src/lib/core/styles/themes/generators/_base.scss
- projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-data-selector.component.scss
- projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-data-selector.component.ts
- projects/igniteui-angular/src/lib/grids/pivot-grid/themes/_base.scss
- projects/igniteui-angular/src/lib/grids/pivot-grid/themes/dark/_index.scss
- projects/igniteui-angular/src/lib/grids/pivot-grid/themes/dark/_tokens.scss
- projects/igniteui-angular/src/lib/grids/pivot-grid/themes/light/_index.scss
- projects/igniteui-angular/src/lib/grids/pivot-grid/themes/light/_tokens.scss
- projects/igniteui-angular/src/lib/grids/pivot-grid/themes/shared/_bootstrap.scss
- projects/igniteui-angular/src/lib/grids/pivot-grid/themes/shared/_index.scss
- projects/igniteui-angular/src/lib/grids/pivot-grid/themes/shared/_material.scss
> refactor(pivot-grid): bundle styles with component

- projects/igniteui-angular/src/lib/core/styles/components/stepper/_stepper-theme.scss
> fix(stepper): use text hover properties for the header

- projects/igniteui-angular/src/lib/core/styles/themes/generators/_base.scss
- projects/igniteui-angular/src/lib/core/styles/typography/_bootstrap.scss
- projects/igniteui-angular/src/lib/core/styles/typography/_fluent.scss
- projects/igniteui-angular/src/lib/core/styles/typography/_indigo.scss
- projects/igniteui-angular/src/lib/core/styles/typography/_material.scss
- projects/igniteui-angular/src/lib/grids/column-actions/column-actions.component.scss
- projects/igniteui-angular/src/lib/grids/column-actions/column-actions.component.ts
- projects/igniteui-angular/src/lib/grids/column-actions/themes/_base.scss
- projects/igniteui-angular/src/lib/grids/column-actions/themes/dark/_index.scss
- projects/igniteui-angular/src/lib/grids/column-actions/themes/dark/_tokens.scss
- projects/igniteui-angular/src/lib/grids/column-actions/themes/light/_index.scss
- projects/igniteui-angular/src/lib/grids/column-actions/themes/light/_tokens.scss
- projects/igniteui-angular/src/lib/grids/column-actions/themes/shared/_index.scss
- projects/igniteui-angular/src/lib/grids/column-actions/themes/shared/material.scss
> refactor(column-actions): bundle styles with component

- projects/igniteui-angular/src/lib/core/styles/components/tabs/_tabs-theme.scss
Closes: [#15710](https://github.com/IgniteUI/igniteui-angular/issues/15710)
> fix(tabs): in indigo theme use focus-within instead of :focus-visible

- projects/igniteui-angular/src/lib/core/styles/components/tabs/_tabs-theme.scss
> fix(tabs): fix border in bootstrap theme

- package-lock.json
- package.json
- projects/igniteui-angular/package.json
- projects/igniteui-angular/src/lib/core/styles/components/tabs/_tabs-theme.scss
Closes [#15673](https://github.com/IgniteUI/igniteui-angular/issues/15673)
To test checkout this [themening branch](https://github.com/IgniteUI/igniteui-theming/compare/v14.2.0...mpopov/fix-hover-border-color-in-indigo?expand=1), and make a package
> fix(tabs): border-color--hover not working when creating a custom theme

- projects/igniteui-angular/src/lib/grids/filtering/advanced-filtering/advanced-filtering-dialog.component.ts
- projects/igniteui-angular/src/lib/grids/grid/grid-filtering-advanced.spec.ts
> Fixed AFD to show column headers (when available) instead of the actual field names.

- projects/igniteui-angular/src/lib/grids/common/crud.service.ts
- projects/igniteui-angular/src/lib/grids/common/pipes.ts
- projects/igniteui-angular/src/lib/grids/grid-base.directive.ts
- projects/igniteui-angular/src/lib/grids/grid-public-row.ts
- projects/igniteui-angular/src/lib/grids/grid/grid.component.html
- projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.component.html
- projects/igniteui-angular/src/lib/grids/row.directive.ts
- projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid.component.html
- projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid.pipes.ts
Note: This is related to a bug in WC and React grid
> fix(crud): Change how we differentiate between add and edit row

- projects/igniteui-angular/src/lib/core/styles/components/input/_input-group-component.scss
- projects/igniteui-angular/src/lib/core/styles/components/input/_input-group-theme.scss
> fix(input-group): fix browser autofill issue

- projects/igniteui-angular/src/lib/core/styles/components/grid/_excel-filtering-theme.scss
> refactor(ESF): update move and sort icon sizes

- projects/igniteui-angular/src/lib/directives/tooltip/tooltip-target.directive.ts
- projects/igniteui-angular/src/lib/directives/tooltip/tooltip.directive.spec.ts
- projects/igniteui-angular/src/lib/directives/tooltip/tooltip.directive.ts
- projects/igniteui-angular/src/lib/test-utils/tooltip-components.spec.ts
> fix(tooltip): make touch events passive - 18.2.x

- projects/igniteui-angular/src/lib/core/utils.ts
- projects/igniteui-angular/src/lib/data-operations/filtering-strategy.ts
- projects/igniteui-angular/src/lib/grids/common/pipes.ts
- projects/igniteui-angular/src/lib/grids/common/strategy.ts
- projects/igniteui-angular/src/lib/grids/grid-base.directive.ts
- projects/igniteui-angular/src/lib/grids/grid-public-cell.ts
- projects/igniteui-angular/src/lib/grids/grid/grid-validation.service.ts
- projects/igniteui-angular/src/lib/grids/grid/grid.nested.props.spec.ts
- projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.pipes.ts
- projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-grid.pipes.ts
- projects/igniteui-angular/src/lib/grids/summaries/grid-summary.service.ts
- projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid.filtering.strategy.ts
- projects/igniteui-angular/src/lib/services/exporter-common/base-export-service.ts
* perf(utils): Improved internal utils performance
* fix: resolveNestedPath excel exporter
* perf(grid-filtering): Resolve column formatter state outside of hot path
Closes #
> perf(utils): Improved internal utils performance (#15816)

- projects/igniteui-angular/package.json
> chore(schematics): update official ignite schematics

- projects/igniteui-angular/src/lib/grids/grid/grid-toolbar.spec.ts
- projects/igniteui-angular/src/lib/grids/toolbar/grid-toolbar-exporter.component.ts
> fix(Toolbar): Cancel export should hide the progress indicator.

- projects/igniteui-angular/src/lib/core/styles/components/input/_input-group-theme.scss
> refactor(input-group): label position when placeholder is removed

- projects/igniteui-angular/src/lib/grids/grid/grid-filtering-advanced.spec.ts
- projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.component.ts
- projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.spec.ts
> fix(h-grid): add null checks for child data - 19.2.x

- projects/igniteui-angular/src/lib/core/styles/components/column-actions/_column-actions-theme.scss
> fix(grid): remove column actions input field negative margin

- projects/igniteui-angular/src/lib/combo/combo.common.ts
- projects/igniteui-angular/src/lib/input-group/input-group.component.ts
- projects/igniteui-angular/src/lib/select/select.component.ts
- src/app/input-group-showcase/input-group-showcase.sample.html
> fix(combo/select): remove suffix dynamically

- projects/igniteui-angular/src/lib/core/styles/components/input/_input-group-component.scss
- projects/igniteui-angular/src/lib/core/styles/components/input/_input-group-theme.scss
Closes [#434](https://github.com/IgniteUI/igniteui-theming/issues/434)
The WC components were fixed in this PR: https://github.com/IgniteUI/igniteui-webcomponents/pull/1747
> fix(input-group): bootstrap invalid and success state shadows

- projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-search.component.ts
> fix(esf): use requestAnimationFrame only when in browser environment

- projects/igniteui-angular/src/lib/directives/tooltip/tooltip.directive.ts
> fix(tooltip): use inject document for ssr - 20.0.x

- projects/igniteui-angular/src/lib/calendar/calendar.component.spec.ts
- projects/igniteui-angular/src/lib/calendar/common/model.spec.ts
- projects/igniteui-angular/src/lib/calendar/common/model.ts
- projects/igniteui-angular/src/lib/calendar/days-view/days-view.component.ts
- src/app/calendar/calendar.sample.ts
- src/app/properties-panel/properties-panel.component.html
- src/app/properties-panel/properties-panel.component.ts
- src/app/properties-panel/property-change.service.ts
> fix(calendar): adhere to ISO 8601 when calculating week number if the week starts on Monday

- projects/igniteui-angular/src/lib/grids/common/strategy.ts
- projects/igniteui-angular/src/lib/grids/grid/grid.groupby.spec.ts
> fix(IgxGrid): Don't use spread operator for large collections.

- projects/igniteui-angular/src/lib/core/styles/components/grid/_grid-theme.scss
> fix(grid): fix grid shadows

- projects/igniteui-angular/src/lib/core/styles/components/grid/_grid-theme.scss
- projects/igniteui-angular/src/lib/grids/grid/expandable-cell.component.html
> fix(igxGrid): Adjust expandable cell styles.

- projects/igniteui-angular/src/lib/drop-down/themes/shared/_fluent.scss
> refactor(drop-down): items icon size

- projects/igniteui-angular/src/lib/core/styles/components/query-builder/_query-builder-theme.scss
> refactoring(query-builder): expose the outer padding as a css variable

- projects/igniteui-angular/src/lib/select/select.component.spec.ts
- projects/igniteui-angular/src/lib/select/select.component.ts
> Sync aria-required with required state - 19.2.x

- projects/igniteui-angular/src/lib/grids/grid/grid-filtering-advanced.spec.ts
- projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.component.ts
- projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.spec.ts
> fix(h-grid): add null checks for child data - 20.0.x

- projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-grid.spec.ts
- projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-row.component.ts
> fix(pivotGrid): Column formatter argument not pupulated correctly. 

- projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-default-expression.component.html
- projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-default-expression.component.ts
- projects/igniteui-angular/src/lib/grids/grid/grid-filtering-ui.spec.ts
> fix(excel-style-filtering): allow negative decimal values for numeric columns - 20.0.x

- projects/igniteui-angular/src/lib/grids/column-actions/themes/_base.scss
- projects/igniteui-angular/src/lib/input-group/themes/_base.scss
Applying the fixes from the following PR's: #15799 #15771
> fix(grid & combo): remove grid column actions negative margin & fix combo clear button parameters

- projects/igniteui-angular/src/lib/combo/combo.component.spec.ts
- projects/igniteui-angular/src/lib/directives/radio/radio-group.directive.spec.ts
- projects/igniteui-angular/src/lib/directives/radio/radio-group.directive.ts
- projects/igniteui-angular/src/lib/radio/radio.component.ts
- src/app/radio/radio-group.component.html
- src/app/radio/radio-group.component.ts
- src/app/radio/radio.sample.html
- src/app/radio/radio.sample.scss
- src/app/radio/radio.sample.ts
> fix(radio-group): dynamically added radio buttons do not initialize

- package-lock.json
- package.json
> deps(sassdoc-theme): bump to latest version of sassdoc-theme

- projects/igniteui-angular/src/lib/date-picker/themes/_base.scss
- projects/igniteui-angular/src/lib/date-picker/themes/dark/_index.scss
- projects/igniteui-angular/src/lib/date-picker/themes/dark/_indigo.scss
Related to IgniteUI/igniteui-theming/issues/433
> fix(date-picker): indigo theme elevations

- projects/igniteui-angular/src/lib/grids/cell.component.ts
- projects/igniteui-angular/src/lib/grids/grid/column-group.spec.ts
- projects/igniteui-angular/src/lib/grids/grid/grid.pinning.spec.ts
- projects/igniteui-angular/src/lib/grids/headers/grid-header-group.component.html
- projects/igniteui-angular/src/lib/grids/headers/grid-header-group.component.ts
- projects/igniteui-angular/src/lib/grids/headers/grid-header-row.component.html
- projects/igniteui-angular/src/lib/grids/headers/grid-header-row.component.ts
- projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-header-row.component.html
- projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-header-row.component.ts
Closes #16017 
what NVDA announces for the cells after:
> fix(grid-column-groups, pivot): render a hidden row with headers for accessibility purposes - master

- projects/igniteui-angular/src/lib/grids/cell.component.ts
- projects/igniteui-angular/src/lib/grids/grid/column-group.spec.ts
- projects/igniteui-angular/src/lib/grids/grid/grid.pinning.spec.ts
- projects/igniteui-angular/src/lib/grids/headers/grid-header-group.component.html
- projects/igniteui-angular/src/lib/grids/headers/grid-header-group.component.ts
- projects/igniteui-angular/src/lib/grids/headers/grid-header-row.component.html
- projects/igniteui-angular/src/lib/grids/headers/grid-header-row.component.ts
- projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-header-row.component.html
- projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-header-row.component.ts
Closes #16017 
what NVDA announces for the cells after:
> fix(grid-column-groups, pivot): render a hidden row with headers for accessibility purposes - 19.2.x

- projects/igniteui-angular/src/lib/core/styles/components/grid/_grid-component.scss
- projects/igniteui-angular/src/lib/core/styles/components/grid/_grid-theme.scss
- projects/igniteui-angular/src/lib/grids/common/pipes.ts
- projects/igniteui-angular/src/lib/grids/grid/grid.component.html
- projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.component.html
- projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid.component.html
Fixes issues described here
-  https://github.com/IgniteUI/igniteui-angular/pull/16024#issuecomment-3139963458
- https://github.com/IgniteUI/igniteui-angular/pull/16024#issuecomment-3140250113
> Fix cell merge styling issues.

- package-lock.json
- package.json
- projects/igniteui-angular/package.json
- projects/igniteui-angular/src/lib/core/styles/themes/_core.scss
- projects/igniteui-angular/src/lib/core/styles/themes/generators/_base.scss
Depends on https://github.com/IgniteUI/igniteui-theming/pull/458
> refactor(themes): consume spacing variables from theming

- projects/igniteui-angular/src/lib/grids/grid/column-resizing.spec.ts
- projects/igniteui-angular/src/lib/grids/resizing/resize-handle.directive.ts
- projects/igniteui-angular/src/lib/grids/resizing/resizer.directive.ts
> Fix column resizer position - 19.2.x

- projects/igniteui-angular/src/lib/date-range-picker/date-range-picker.component.html
- projects/igniteui-angular/src/lib/expansion-panel/expansion-panel-header.component.html
- projects/igniteui-angular/src/lib/icon/icon.component.spec.ts
- projects/igniteui-angular/src/lib/icon/icon.component.ts
- projects/igniteui-angular/src/lib/select/select.component.html
> feat(icon): add aria-hidden="true" attribute by default + test - 19.2.x

- projects/igniteui-angular/src/lib/date-range-picker/date-range-picker.component.html
- projects/igniteui-angular/src/lib/expansion-panel/expansion-panel-header.component.html
- projects/igniteui-angular/src/lib/icon/icon.component.spec.ts
- projects/igniteui-angular/src/lib/icon/icon.component.ts
- projects/igniteui-angular/src/lib/select/select.component.html
> feat(icon): add aria-hidden="true" attribute by default + test - master

- .github/workflows/nodejs.yml
> chore(schematics): use node version that works for ts-node (#16147)

- projects/igniteui-angular/src/lib/core/styles/components/combo/_combo-theme.scss
- projects/igniteui-angular/src/lib/core/styles/components/input/_input-group-theme.scss
- projects/igniteui-angular/src/lib/core/styles/components/select/_select-theme.scss
Closes [#1817](https://github.com/IgniteUI/igniteui-webcomponents/issues/1817)
> fix(input-group): prefix & suffix borders in bootstrap

- projects/igniteui-angular/src/lib/grids/common/grid.interface.ts
- projects/igniteui-angular/src/lib/query-builder/query-builder.component.ts
> fix(QB): Updated entities JSDoc. Removed @hidden decorator

- projects/igniteui-angular/src/lib/directives/tooltip/tooltip-target.directive.ts
- projects/igniteui-angular/src/lib/directives/tooltip/tooltip.directive.spec.ts
> fix(tooltip): not show tooltip when target is clicked - 19.2.x

- projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid.component.html
> fix(*): prod build fails internally

- projects/igniteui-angular/src/lib/date-picker/public_api.ts
> Export IDatePickerValidationFailedEventArgs - 19.2.x

- projects/igniteui-angular/src/lib/date-picker/public_api.ts
> Export IDatePickerValidationFailedEventArgs - 20.0.x

- projects/igniteui-angular/migrations/update-19_2_15/index.spec.ts
- projects/igniteui-angular/migrations/update-19_2_15/index.ts
> Replace JSON.Parse to prevent eror when parsing object literal - 19.2.x

- projects/igniteui-angular/src/lib/directives/input/input.directive.spec.ts
- projects/igniteui-angular/src/lib/directives/input/input.directive.ts
> Adding markAsTouched to fix form validation

- .github/workflows/nodejs.yml
Reverts IgniteUI/igniteui-angular#16192
> Revert "chore(schematics): use latest minor node 22 ver"

- projects/igniteui-angular/src/lib/core/styles/components/card/_card-theme.scss
> refactor(themes): set avatar size only in card thumbnail

- projects/igniteui-angular/src/lib/core/styles/components/button-group/_button-group-theme.scss
- We should not remove a border or any schema-connected style from the theme. Rather, we should update the variable in the schema, which in this case is already done.
Closes #16258
> fix(button-group): remove unnecessary bootstrap-specific styles

- projects/igniteui-angular-elements/src/public_api.ts
- projects/igniteui-angular/src/lib/data-operations/merge-strategy.ts
Related to #[this PR](https://github.com/IgniteUI/igniteui-api-analyzer/pull/111)
> refactor(cell-merge): change blazorSuppress to blazorCSSuppress - 20.1.x

- ROADMAP.md
> Update ROADMAP 02 Oct 2025
