demos/app/grid/sample.component.html, demos/app/grid/sample.component.ts, src/grid/column.component.ts, src/grid/grid.component.html, src/grid/grid.component.ts
The columns now are not movable by default but instead controlled through the column `movable` property.
Fixed a few small issues with the grid sample.
=> Grid column movable off by default

src/themes/material/extends/_buttons.scss, src/themes/material/modules/_controls.scss, src/themes/material/modules/_inputs.scss
=> (FIX) Cast block reference to string before using it in children scopes

src/grid/grid.component.spec.ts, src/grid/tests.helper.ts
Closes #397  .  
Scenarios that haven't been covered yet:
- Adding custom sorting strategy (job title sorting)
- Adding custom filtering strategy (using between filtering implementation)
- I bug was found #400 . After the bug is fixed second test should be included again (remove 'x' from 'it')
=> Adding grid scenarios (sorting and filtering)

README.md
Update the JS Blocks repo documentation  with the quickstart app details.
Closes # .  
=> Update the JS Blocks repo documentation

src/core/navigation/directives.ts, src/core/touch.ts, src/navigation-drawer/navigation-drawer.component.spec.ts, src/navigation-drawer/navigation-drawer.component.ts
#447
- Force touch input due to pointers being buggy still in Chrome on android
- Cleanup HammerGesturesManager a bit, make sure drawer can be [un]pinned repeatedly
=> Navdrawer updates for #447

package.json, src/carousel/carousel.component.html, src/carousel/carousel.component.spec.ts, src/carousel/carousel.component.ts, src/carousel/slide.html, src/navigation-drawer/navigation-drawer.component.spec.ts, tslint.json
- Removed the old way touch events were handled.
- Removed redundant imports in the carousel.
- Upgraded to the latest version of TSlint and removed submodule rule for rxjs/angular
Closes #458
=> Carousel swipe not working on mobile

.github/CONTRIBUTING.md, .travis.yml, README.md, ROADMAP.md, demos/package-lock.json, demos/package.json, package-lock.json, package.json, src/animations/README.md, src/animations/fade/README.md, src/animations/flip/README.md, src/animations/misc/README.md, src/animations/rotate/README.md, src/animations/scale/README.md, src/animations/slide/README.md, src/animations/swing/README.md, src/calendar/README.md, src/core/touch.ts, src/date-picker/README.md
Renaming everything from `igniteui-angular2` to `igniteui-angular-wrappers` as outlined in the blog post.
https://www.infragistics.com/community/blogs/b/infragistics/posts/ignite-ui-github-repo-name-changes
=> Replacing the JS Blocks reference occurrences

demos/app/app.component.ts, demos/app/navdrawer/sample.module.ts, src/core/navigation/directives.ts, src/core/navigation/nav-service.ts, src/navigation-drawer/README.md, src/navigation-drawer/navigation-drawer.component.spec.ts, src/navigation-drawer/navigation-drawer.component.ts
Closes #512 .  
⚠️ **BREAKING CHANGES: **
- Renamed `NavigationDrawer` to `IgxNavigationDrawer`
- Renamed `NavigationDrawerModule` to `IgxNavigationDrawerModule`
- Renamed `NavigationService` to `IgxNavigationService`
- Renamed `NavigationToggle` to `IgxNavigationToggle`
- Renamed `NavigationClose` to `IgxNavigationClose`
=> Nav drawer rename, readme update

src/avatar/avatar.component.html, src/avatar/avatar.component.spec.ts, src/avatar/avatar.component.ts, src/themes/material/extends/_avatar.scss
Closes #136  
Only the logic which renders initials is changed. No changes made on the image rendering size as it looks fine now.
=> IgxAvatar - Replace the canvas usage with svg when rendering initials

src/directives/for-of/for_of.directive.ts
=> Fix igxForOf not rendering data due to parentElement of a comment in IE11 being undefined.

src/directives/mask/mask-helper.ts, src/directives/mask/mask.directive.spec.ts
- improve user experience while typing on a literal: instead of skipping the literal and just placing the cursor behind it, the value is now entered on the next available valid position.
- add workaround for the IE 'x' button breaking the mask;
Closes #789.
=> Mask directive improvements

.travis.yml
When the release is tagged as "*beta*" (e.g. 5.5.0-beta.1, used as package version) the respective npm package will now also be tagged as `next`.
Note the default is usually `latest`, hence the 
`npm i package@latest`
so this will make beta releases available only through direct version install and:
`npm i igniteui-angular@next`
@Aleksandyr This will also help with changelog generation if you end up keeping the npm plugin for getting latest release version. Meaning, each beta will keep generating full log from the "latest" rather than the beta before it :)
=> Update npm deploy tag

src/directives/for-of/for_of.directive.spec.ts, src/directives/for-of/for_of.directive.ts
Making sure the igx-display-container--inactive class is applied only when the data in the container is not virtualized (for example when there's no igxForContainerSize or when there's not enought data to display a scrollbar) .
Closes #826  .
=> Fix and test for issue #826 

src/directives/for-of/for_of.directive.spec.ts, src/directives/for-of/for_of.directive.ts
Making sure the igx-display-container--inactive class is applied only when the data in the container is not virtualized (for example when there's no igxForContainerSize or when there's not enought data to display a scrollbar) .
Closes #826  .
=> Fix and test for issue #826

src/directives/for-of/for_of.directive.ts
=> Fix for issue #838 - When setting the igxForContainerSize post init and binding a new array scrolling with the mouse wheel scrolls the page as well.

CHANGELOG.md, src/checkbox/README.md, src/checkbox/checkbox.component.html, src/checkbox/checkbox.component.spec.ts, src/checkbox/checkbox.component.ts
- Improved accessibility via aria-labelledby and aria-label properties.
- Fixes an issue where the click event may be fired twice. 
- Fixes an issue where the change event is not triggered on label click.
- Now fires enhanced change event.
- Adds the ability to programmatically toggle the checked state of the checkbox.
fixes #850, closes #858, fixes #859
=> feat(checkbox): better accessibility, improved event handling

src/services/csv/char-separated-value-data.ts
#987 
Removing redundant **valueDelimiter** and **data** getters and setters from CharSeparatedValueData, since the IgxCsvExporterOptions exposes getter and setter for the **valueDelimeter** and the **data** is used internally by the IgxCsvExporterService.
=> Increasing coverage of Csv exporter

src/tabs/README.md, src/tabs/tabs.component.spec.ts, src/tabs/tabs.component.ts, src/tabs/tabs.directives.ts
Bug fixing, refactoring - selectedTab renamed to selectedTabItem - empty space appears on the left before the first tab when window is resized.
=> Tabs bugfixes

demos/app/list-performance/sample.component.css, demos/app/list-performance/sample.component.html, src/core/styles/base/_normalize.scss, src/core/styles/components/_common/_igx-display-container.scss, src/core/styles/components/_common/_igx-vhelper.scss, src/core/styles/components/checkbox/_checkbox-theme.scss, src/core/styles/components/grid/_grid-theme.scss, src/core/styles/components/radio/_radio-theme.scss, src/core/styles/components/switch/_switch-theme.scss
=> fix(themes): fixes regression issues in various component themes

src/grid/cell.component.ts
Closes #1063 .  
Key navigation with arrow up was causing the cell selection to sometimes blur and the grid to lose focus. Adjust the arrow up navigation to use code similar to the one for arrow down.
=> Cell Selection on Arrow Up - rework

src/core/styles/components/grid-filtering/_grid-filtering-theme.scss
Because of the way the filtering menu is currently implemented as part
of the header, its visibility is affected by the z-index of the header
itself. So if a column header has a higher z-index than the next
sibling, that sibling will have its filtering UI covered by the previous
header. To avoid that I am pushing the filtering menu below the header
so it doesn't get covered by the headers.
Closes #1078
=> fix(grid-filtering): Push the filtering menu below the grid header

src/directives/for-of/for_of.directive.spec.ts, src/directives/for-of/for_of.directive.ts, src/grid/cell.component.ts, src/tabs/tabs.component.spec.ts
Closes #1016   
Add one additional (non-visible) row in the virtual vertical scroller chunk. This will ensure the smooth experience when scrolling up and down. The additional row is removed when we scroll to the bottom.
=> Ensure smooth vertical scrolling

src/grid/column-resizing.spec.ts, src/grid/column.component.ts, src/grid/grid-header.component.html, src/grid/grid-header.component.ts
Rework column resizing to accommodate the header icon group:
- change minWidth default value and further recalculations;
- sorting and filtering icons are now taken into consideration when auto-resizing on double click;
=> Column resizing rework

CHANGELOG.md
Notes in the changelog were written in 5.2.0 but they should be in 5.3.0 section.
=> Update the changelog to properly target the changes made by renaming IgxTabBarComponent

demos/style/igniteui-theme.scss, src/core/styles/base/utilities/_mixins.scss
It would be useful to provide a way to generate CSS classes from from
the palette colors. The classes can assign the palette color to a CSS property upon generation.
=> feat(themes): add mixins for generating css classes from color palette

src/grid/grid.component.ts
Calculate correctly pinned columns max allowable width when restricting the resizing of pinned columns.
=> Make pinned column resizing works with % width set on grid

src/core/selection.ts, src/grid/grid-selection.spec.ts
Closes #1218.
refactor select_item to not write directly into the selected items collection. All updates to the selected items collection are done via set_selection.
=> onRowSelectionChange cancelable - 1218

src/core/selection.ts, src/grid/grid-selection.spec.ts
Closes #1218  .  
refactor select_item to not write directly into the selected items collection. All updates to the selected items collection are done via set_selection.
=> V slavov/on row selection change cancelable 1218 master

src/grid/grid.component.html, src/grid/row.component.html
Closes #1169.
Issue reproduces only if the column width is set as number (for example width="88"), in which case the existing HostBinding for flex-basis is not applied correctly. Fix adds binding for the scenarios when width is set as number.
=> fix(igGrid): Misalignment when resize a column and then scroll horizontally. #1169 

CHANGELOG.md, src/grid/column.component.ts, src/grid/grid-filtering-ui.spec.ts, src/grid/grid-filtering.component.html, src/grid/grid-filtering.component.ts, src/grid/grid-filtering.spec.ts, src/grid/grid.component.html, src/grid/grid.component.ts
Closes #1224, Closes #1228, Closes #1187, Closes #1263 
NEW:
=> fix(grid): Evaluate the filtering condition before filtering #1224

src/directives/for-of/for_of.directive.ts
Adding setter for ngForTrackBy so that users can defined their own trackby function. If no ngForTrackBy is defined track changes in the horizontal item's width prop by default. 
Closes #1204  .
=> enhancement(igxFor): Adding setter for ngForTrackBy. Track changes in horizontal item’s width prop by default.

demos/app/grid-selection/sample.component.html, demos/app/grid-selection/sample.component.ts, src/grid/grid-selection.spec.ts, src/grid/grid.component.ts
Closes #1298, #1295, #1297 .
Fix selectedRows() to return an empty array if no rows are selected.
Fix selectAllRows() to properly pass the grid primaryKey to the selectionAPI.
FIx checkHeaderChecboxStatus() to properly set the state of the row-selection header checkbox when called programatically.
=> fixes to grid selection

demos/app/input/sample.component.html, src/core/styles/components/checkbox/_checkbox-theme.scss, src/core/styles/components/input/_input-group-theme.scss, src/core/styles/components/radio/_radio-theme.scss, src/core/styles/components/slider/_slider-theme.scss, src/core/styles/components/switch/_switch-theme.scss
Fix label colors for switch, radio, and the checkbox themes. Explose the
variant to the produces theme map for all themes with multiple theme
variants.
Closes #1326
=> fix(themes): wrong colors in light variant themes

src/core/utils.ts, src/services/excel/excel-exporter-grid.spec.ts, src/services/exporter-common/base-export-service.ts, src/services/exporter-common/components-declarations.ts
Closes #1314 Closes #1315 
Clone the grid sort expression in order to prevent changes in it, while exporting, to affect the grid.
=> Fix - Sort icon on a table object is not cleared when exporting second time or later

.travis.yml, gulpfile.js, package-lock.json, package.json, projects/igniteui-angular/migrations/common/UpdateChanges.spec.ts, projects/igniteui-angular/migrations/common/UpdateChanges.ts, projects/igniteui-angular/migrations/common/filterSourceDirs.ts, projects/igniteui-angular/migrations/common/schema/class.schema.json, projects/igniteui-angular/migrations/common/schema/index.ts, projects/igniteui-angular/migrations/common/schema/output.schema.json, projects/igniteui-angular/migrations/common/schema/selector.schema.json, projects/igniteui-angular/migrations/common/tsUtils.ts, projects/igniteui-angular/migrations/migration-collection.json, projects/igniteui-angular/migrations/tsconfig.json, projects/igniteui-angular/migrations/update-6/changes/selectors.json, projects/igniteui-angular/migrations/update-6/index.spec.ts, projects/igniteui-angular/migrations/update-6/index.ts, projects/igniteui-angular/migrations/update-6_01/changes/selectors.json, projects/igniteui-angular/migrations/update-6_01/index.spec.ts, projects/igniteui-angular/migrations/update-6_01/index.ts, projects/igniteui-angular/package.json
Closes # .  
There's base functionality to replace/remove component and directive selector, output (event) names and replace Class names in typescript files. All controlled by describing changes in JSON files.
I left the 6.0.1 submodule import in the schematic as I don't expect future changes really.
=> Add ng-update migration schematics

projects/igniteui-angular/src/lib/grid/api.service.ts
#1355  .  
Remove unnecessary code for advanced filtering. Code was unreachable and code coverage was lowered.
=> Remove unnecessary code for advanced filtering

projects/igniteui-angular/src/lib/services/overlay/overlay.spec.ts, projects/igniteui-angular/src/lib/services/overlay/overlay.ts
Closes #1685.  
Add initially measure width and height to overlay_content to assure that the shown element still wraps width and height if they are set to 100%.
=> test(igxOverlay): add test for component with 100% width / height, #1685

projects/igniteui-angular/src/lib/services/overlay/overlay.spec.ts
Clean leftover elements in body, adjust async and hide overlays that would leave handlers after the test
=> Overlay tests cleaup and async

projects/igniteui-angular/src/lib/grid/column-group.spec.ts, projects/igniteui-angular/src/lib/grid/grid.component.ts
Closes #1775 
2nd Issue: Try to pin a child header into the pinned arera via API - should not be possible
=> fix(grid): deny pinning column to another level area via api #1775

projects/igniteui-angular/src/lib/drop-down/drop-down.component.spec.ts, projects/igniteui-angular/src/lib/drop-down/drop-down.component.ts
Closes #1895  .  
SelectItem was expecting that the drop-down would always be visible (and therefore it would have a focusedItem).
Add check to selectItem function in IgxDropDownComponent
=> Add check for focusedItem in drop-down selectItem

projects/igniteui-angular/src/lib/combo/combo.component.spec.ts, projects/igniteui-angular/src/lib/combo/combo.component.ts, projects/igniteui-angular/src/lib/combo/combo.pipes.ts
Closes #1892 .  
Add the default falllback group of the combo to the object being added to the collection in addItemToCollection() instead of in the grouping pipe.
To verify in the Combo DevSample, first remove the onAddition() handler
=> Combo - Add Item with groupKey properly handle grouping

gulpfile.js
=> fix(git-hooks): throws when git is not initialized

projects/igniteui-angular/src/lib/core/styles/components/card/_card-theme.scss, projects/igniteui-angular/src/lib/core/styles/components/checkbox/_checkbox-theme.scss, projects/igniteui-angular/src/lib/core/styles/components/radio/_radio-theme.scss, projects/igniteui-angular/src/lib/core/styles/components/switch/_switch-theme.scss
When using the igx-radio, igx-checkbox, or igx-switch themes on their own, the ripple Sass compiler complains of a missing igx-ripple-theme dependency. To remedy for that, the before-mentioned component themes now import the igx-ripple-theme and igx-ripple-component dependencies.
=> refactor(themes): import ripple theme in ripple dependent components

projects/igniteui-angular/src/lib/slider/slider.component.spec.ts, projects/igniteui-angular/src/lib/slider/slider.component.ts
Closes #920 .
The fix covers the following scenarios:
1. If upper/lowerBound are undefined on initialization, then upperBound/lowerBound will change whenever maxValue/minValue change.
If upperBound/lowerBound are set from outside however, we stop updating them when maxValue/minValue change.
2. Whenever maxValue/minValue change, we take care that value is updated respectively, so that we avoid thumb flickering on focus.
=> slider - track min/maxValue when lower/upperBound is undefined #920

projects/igniteui-angular/src/lib/navigation-drawer/navigation-drawer.component.spec.ts, projects/igniteui-angular/src/lib/navigation-drawer/navigation-drawer.component.ts
Closes #1981.
Removed logic that took window's height blindly. Styles already apply 100% - that'll correctly take the window size when the drawer is fixed (not pinned) and whatever is the closest block parent's height otherwise, which is entirely up to the app now.
This will allow the drawer to be pinned inside layouts even between headers/footers.
=> #1981 Nav drawer height use only 100% from styles

projects/igniteui-angular/src/lib/grid/grid-filtering-ui.spec.ts, projects/igniteui-angular/src/lib/grid/grid-filtering.component.html, projects/igniteui-angular/src/lib/grid/grid-filtering.component.ts
Closes #2038 .
Refresh filter dialog on 'opening' event instead of on 'opened'. All changes to the refresh() method itself are purely cosmetic. The opened event is still handled only to focus the first input in the filter dialog.
=> Refresh filter dialog on 'opening' event instead of on 'opened' - 6.1.x

projects/igniteui-angular/src/lib/tabs/tabs-group.component.ts, projects/igniteui-angular/src/lib/tabs/tabs.component.spec.ts
Open the following [sample](https://stackblitz.com/edit/angular-zr35pg-zyhd8n), click the button and observe the console log.
Actual result: tabs group `disabled` property returns **undefined**
Expected result: `disabled` property should return **false** when the tabs group is not disabled
=> chore(tabs): Fixed disabled initial value to false

projects/igniteui-angular/src/lib/tabs/tabs.component.ts
Navigate to [selectedIndex](https://staging.infragistics.local/products/ignite-ui-angular/docs/typescript/classes/igxtabscomponent.html#selectedindex) property.
HTML code snippet is not rendered.
=> chore(tabs): Fixed API docs typo

projects/igniteui-angular/src/lib/core/utils.ts, projects/igniteui-angular/src/lib/grid/column-resizing.spec.ts, projects/igniteui-angular/src/lib/grid/column.component.ts, projects/igniteui-angular/src/lib/grid/grid-header.component.html, projects/igniteui-angular/src/lib/grid/grid-header.component.ts, projects/igniteui-angular/src/lib/grid/grid.component.ts, projects/igniteui-angular/src/lib/test-utils/grid-samples.spec.ts, projects/igniteui-angular/src/lib/test-utils/template-strings.spec.ts
Closes #2025 .
1. Expose `autosize()` method on `IgxColumnComponent`.
2. Fix #2025.
3. Expose two helper methods (in utils) for measuring string length: using Range and using Canvas. Current implementation of auto sizing uses the one with Range.
=> 6.1.x - Expose column auto size API feature request

projects/igniteui-angular/src/lib/combo/combo.component.spec.ts, projects/igniteui-angular/src/lib/combo/combo.component.ts
Closes #2440
Array used to create new set during `triggerSelectionChange` can now be properly mutated through the `onSelectionChange` emit
=> IgxCombo - Selection - Override Selection through onSelectionChange emit - 6.1

projects/igniteui-angular/src/lib/combo/combo.component.spec.ts, projects/igniteui-angular/src/lib/combo/combo.component.ts
Closes #2440
Array used to create new set during `triggerSelectionChange` can now be properly mutated through the `onSelectionChange` emit
=> IgxCombo - Selection - Override Selection through onSelectionChange emit - 6.2

projects/igniteui-angular/src/lib/core/navigation/nav.service.ts, projects/igniteui-angular/src/lib/core/touch.ts
Closes  #2524. 
Changes to the description of the IgxNavigationService.
Hiding the HammerGesturesManager class, because it is for internal use and should not be public.
=> Changing class descriptions.

projects/igniteui-angular/src/lib/core/styles/components/chip/_chip-theme.scss
Closes #2467   
Additional information related to this pull request: 
I remove the margin after the text, but if we want to centre the text inside the chip we need to check if there is only text and add some class to make it centre.
This is what happens if I add text-align: center. It happens, because we have min-width on the chip. It's ok when we don't have icons, but if we have, the text should be left aligned, otherwise it looks odd.
https://drive.google.com/file/d/1RWk9QvJ_tyg-vWD8h7jGSBA6PVLCPa2s/view
=> Fix for 2467

projects/igniteui-angular/src/lib/combo/combo.component.spec.ts, projects/igniteui-angular/src/lib/combo/combo.component.ts, projects/igniteui-angular/src/lib/core/styles/components/drop-down/_drop-down-theme.scss
Closes #2504.
Combo items had min-height: 48px set through CSS and itemHeight (style.heigh) set to 32px through HostBinding in component definition. The itemHeight property is used in IgxForOf, but if itemHeight < 48 (min-height), this led to unreachable items in the virtualized combo drop-down list
=> Fix - Combo - itemHeight default change, min-height removed

README.md, azure-pipelines.yml
#2605 
- Deploy code coverage to Coveralls only in case the test run succeeds;
- Deploy test run results regardless whether the test are failing or not;
- Add build status badge in Readme.md
=> Improve Azure Pipelines build

projects/igniteui-angular/src/lib/combo/combo.component.spec.ts, projects/igniteui-angular/src/lib/combo/combo.component.ts
Closes #2620.
The writeValue function that is needed for the combo to act as an ngControl no longer needs the combo to have `valueKey !== ''`. This allows the combo to properly bind to `Array<string | number>`.
=> Fix - Combo - Properly bind to ngModel without valueKey - 6.1.x

projects/igniteui-angular/src/lib/combo/combo.component.spec.ts, projects/igniteui-angular/src/lib/combo/combo.component.ts
Closes #2620.
The writeValue function that is needed for the combo to act as an ngControl no longer needs the combo to have `valueKey !== ''`. This allows the combo to properly bind to `Array<string | number>`.
=> Fix - Combo - Properly bind to ngModel without valueKey

projects/igniteui-angular/src/lib/core/styles/components/grid/_grid-component.scss, projects/igniteui-angular/src/lib/core/styles/components/grid/_grid-theme.scss, projects/igniteui-angular/src/lib/grid/grid.component.html
Closes #2522.  
There already was a calculation in place for the offset needed when `[rowSelectable]="true"`. The offset was placed as a margin and on the `.igx-grid__summaries` row in the `tfoot`. 
After a discussion with @zdrawku , @damyanpetev , @ChronosSF  we decided to go with the following approach:
Add a `div` container with the appropriate styles at the start of the summaries container in case `[rowSelectable]="true"`. This keeps the structure understandable and the container should not interfere with future enhancements.
Another possible fix is adding `overflow-x: hidden` to the `.igx-grid__summaries` class. While this works and does not interfere with virtualization and rendering of the grid, we decided to go against it.
=> Fix - Grid - Summary section was incorrectly displayed when selection is enabled - 6.1.x

projects/igniteui-angular/migrations/common/UpdateChanges.ts
=> chore(ng-update): migration compile error - export type enum

angular.json, gulpfile.js, package-lock.json, package.json, projects/igniteui-angular/src/lib/core/styles/themes/_core.scss, src/app/app.component.ts, src/app/drop-down/drop-down.sample.scss, src/app/overlay/overlay-animation.sample.scss, src/app/pageHeading/pageHeading.styles.scss, src/app/styleguide/colors/color.sample.scss, src/environments/environment.hmr.ts, src/environments/environment.prod.ts, src/environments/environment.ts, src/hmr.ts, src/index.html, src/main.ts, src/styles/igniteui-theme.scss, src/tsconfig.app.json, tsconfig.json
The demos app no longer depends on a production build of IgniteUI for Angular. It instead uses the igniteui-angular project modules directly when compiling the app. This allows for hot module relaod (hmr) of project modules as well as for source mapping  of typescript and sass source files. Also, this eliminates the need for file watchers to trigger production builds, making the project build time a lot faster.
TL;DR
Effectively, to run the demos app you only need to run `npm start` now. No dist folder is needed.
=> [DO NOT MERGE] build(demos): switch to hmr for the demos app

projects/igniteui-angular/src/lib/combo/combo.component.spec.ts
Applies changes made in #2779 to 6.1.x
=> Extract dropdown element indexes in a deterministic way

projects/igniteui-angular/src/lib/directives/toggle/toggle.directive.spec.ts, projects/igniteui-angular/src/lib/directives/toggle/toggle.directive.ts, projects/igniteui-angular/src/lib/services/overlay/overlay.spec.ts, projects/igniteui-angular/src/lib/services/overlay/position/connected-positioning-strategy.ts
Related IgniteUI/igniteui-cli#369
If there are bound `overlaySettings` with `positionStrategy` that doesn't define a target, provide the toggle action element before opening.
This allows the config object to be created for targets that are created dynamically (async, ngIf, etc..).
=> feat(toggle-action): set `overlaySettings` position target if empty

projects/igniteui-angular/src/lib/core/styles/components/overlay/_overlay-theme.scss
This should allow overlay wrappers directly under body to show above most common layout blocks.
Specifically related to #2411 scenario with date picker; also #2307.
**Additional information related to this pull request:**
We moved the filtering dialogs to the grid outlet for the first issue, however that doesn't work with the modal overlays (see #2745) and those remain under the document body. That brings them outside the stacking contexts of the container around the grid and the grid itself and so a picker would show under the grid sample.
Reproducible in the dev demos if you remove the perspective from the `.content` and also adding a sample from @npaunov:
[igx-test-sample.zip](https://github.com/IgniteUI/igniteui-angular/files/2510216/igx-test-sample.zip)
=>  #2411 add default z-index to overlay wrapper

projects/igniteui-angular/src/lib/checkbox/checkbox.component.spec.ts, projects/igniteui-angular/src/lib/checkbox/checkbox.component.ts, projects/igniteui-angular/src/lib/core/edit-provider.ts, projects/igniteui-angular/src/lib/date-picker/date-picker.component.spec.ts, projects/igniteui-angular/src/lib/date-picker/date-picker.component.ts, projects/igniteui-angular/src/lib/directives/focus/focus.directive.spec.ts, projects/igniteui-angular/src/lib/directives/focus/focus.directive.ts, projects/igniteui-angular/src/lib/grids/cell.component.html, projects/igniteui-angular/src/lib/radio/radio.component.spec.ts, projects/igniteui-angular/src/lib/radio/radio.component.ts, projects/igniteui-angular/src/lib/slider/slider.component.spec.ts, projects/igniteui-angular/src/lib/slider/slider.component.ts, projects/igniteui-angular/src/lib/switch/switch.component.spec.ts, projects/igniteui-angular/src/lib/switch/switch.component.ts, projects/igniteui-angular/src/lib/time-picker/time-picker.component.spec.ts, projects/igniteui-angular/src/lib/time-picker/time-picker.component.ts
Closes # .  
Taking advantage of the fact that all composite editors are all provided as `NG_VALUE_ACCESSOR` (needed a common token) and making them optional DI for the `igxFocus` so the directive can receive potential host component and focus its inner field instead.
=> feat(igxFocus): allow igxFocus to work with custom editors #2456

projects/igniteui-angular/src/lib/core/utils.ts, projects/igniteui-angular/src/lib/grids/api.service.ts, projects/igniteui-angular/src/lib/grids/grid/grid.component.spec.ts
Closes #2848.  
When checking if a transaction needs to be added, instead of using `===`, the grid api will check using `isEqual` (new in `utils`) - Currently works only for `Date` objects, checking `date.getTime()` instead of just `===` (and thus avoiding to add new transaction when none are needed)
=> Fix - Transaction - Dates are properly compared when adding transaction

projects/igniteui-angular/src/lib/core/styles/base/utilities/_functions.scss
Closes #2814.
You can find additional information in the issue.
=> Add support for first-class functions for older versions of Sass

projects/igniteui-angular/src/lib/services/transaction/base-transaction.ts, projects/igniteui-angular/src/lib/services/transaction/igx-transaction.spec.ts, projects/igniteui-angular/src/lib/services/transaction/igx-transaction.ts, projects/igniteui-angular/src/lib/services/transaction/transaction.ts
Closes #2869.  
Adding `canRedo` and `canUndo` properties to transaction interface
=> Feat - Transaction - Add canRedo / canUndo properties

CHANGELOG.md, projects/igniteui-angular/src/lib/data-operations/sorting-expression.interface.ts, projects/igniteui-angular/src/lib/data-operations/sorting-strategy.ts, projects/igniteui-angular/src/lib/grid/api.service.ts, projects/igniteui-angular/src/lib/grid/column.component.ts, projects/igniteui-angular/src/lib/grid/grid-header.component.ts, projects/igniteui-angular/src/lib/grid/grid.common.ts, projects/igniteui-angular/src/lib/grid/grid.component.ts, projects/igniteui-angular/src/lib/grid/grid.groupby.spec.ts, projects/igniteui-angular/src/lib/grid/grid.pipes.ts
=> feat(grid): expose input to set sort strategy 6.1.x #2734

projects/igniteui-angular/src/lib/grid/grid.component.ts
#2793
`checkHeaderCheckboxStatus` properly checks if all rows are selected using `filteredData` instead of `data` when filtering is in place
=> Fix - Selection - Selection header properly checks against filteredData - 6.1.x

projects/igniteui-angular/src/lib/grids/cell.component.ts, projects/igniteui-angular/src/lib/grids/grid/grid.component.spec.ts
Closes #2940
Cell dirty state was checking if the row exists in the transaction log and if the value of the cell is present, but the check returned `false` if the value of the cell evaluates to `false` (e.g. `false`, `0`, `''`)
=> Fix - Grid - Dirty state is applied when value of cell is changed to false

projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid-keyBoardNav.spec.ts, projects/igniteui-angular/src/lib/test-utils/tree-grid-functions.spec.ts
=> Update treeGrid Keyboard navigation tests - 6.2.x

projects/igniteui-angular/src/lib/grids/filtering/grid-filtering-cell.component.html, projects/igniteui-angular/src/lib/grids/filtering/grid-filtering-cell.component.ts, projects/igniteui-angular/src/lib/grids/filtering/grid-filtering-row.component.html, projects/igniteui-angular/src/lib/grids/filtering/grid-filtering-row.component.ts, projects/igniteui-angular/src/lib/grids/filtering/grid-filtering.service.ts, projects/igniteui-angular/src/lib/grids/grid-navigation.service.ts, projects/igniteui-angular/src/lib/grids/grid/grid.component.html, projects/igniteui-angular/src/lib/grids/grid/groupby-row.component.ts, projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid.component.html
=> Improve keyboard navigation in filtering

projects/igniteui-angular/src/lib/combo/combo.component.spec.ts, projects/igniteui-angular/src/lib/services/overlay/overlay.ts
Closes #2867
Right after creation of `animationPlayer` we were calling its `init` method. This forces the player to start and then to pause the animation. As a result of this on IE and on Edge the animated element was flickering. Calling of `init` is not necessary as calling `play` calls same internal methods as `init` does.
=> Fix for igxToggle flickers on IE and Edge, #2867

projects/igniteui-angular/migrations/common/UpdateChanges.spec.ts, projects/igniteui-angular/migrations/common/UpdateChanges.ts, projects/igniteui-angular/migrations/common/schema/index.ts, projects/igniteui-angular/migrations/common/schema/theme-props.schema.json, projects/igniteui-angular/migrations/migration-collection.json, projects/igniteui-angular/migrations/update-6_2_1/changes/theme-props.json, projects/igniteui-angular/migrations/update-6_2_1/index.spec.ts, projects/igniteui-angular/migrations/update-6_2_1/index.ts
New option to migrate Sass function properties.
Closes #2994.
Can be configured with `theme-props.json`, can replace or remove props.
Added the two props I saw on the chip. Will be updating with more configuration once a full list of changes is compiled.
=> #2994 Add migration for Sass theme props migration

projects/igniteui-angular/src/lib/calendar/calendar.component.html, projects/igniteui-angular/src/lib/calendar/calendar.component.spec.ts, projects/igniteui-angular/src/lib/core/styles/components/calendar/_calendar-component.scss, projects/igniteui-angular/src/lib/core/styles/components/calendar/_calendar-theme.scss, projects/igniteui-angular/src/lib/grids/grid/grid-filtering-ui.spec.ts, projects/igniteui-angular/src/lib/grids/grid/grid.sorting.spec.ts
=> fix(calendar): make all class names unique

CHANGELOG.md
=> Update 7.0.0 changelog with dark theme and 6.2.1 changes

projects/igniteui-angular/src/lib/grids/filtering/grid-filtering-row.component.ts, projects/igniteui-angular/src/lib/grids/grid/grid-filtering-ui.spec.ts
=> Pop empty item from expressionsList

projects/igniteui-angular/src/lib/core/styles/components/grid/_grid-component.scss, projects/igniteui-angular/src/lib/core/styles/components/grid/_grid-theme.scss, projects/igniteui-angular/src/lib/core/styles/themes/schemas/dark/_grid.scss, projects/igniteui-angular/src/lib/core/styles/themes/schemas/light/_grid.scss, projects/igniteui-angular/src/lib/grids/cell.component.ts, projects/igniteui-angular/src/lib/grids/grid-navigation.service.ts, projects/igniteui-angular/src/lib/grids/grid/grid.pinning.spec.ts
=> fix(themes): pinned and selected cells would show content under

projects/igniteui-angular/src/lib/combo/combo-dropdown.component.ts, projects/igniteui-angular/src/lib/combo/combo.common.ts, projects/igniteui-angular/src/lib/combo/combo.component.html, projects/igniteui-angular/src/lib/combo/combo.component.spec.ts, projects/igniteui-angular/src/lib/combo/combo.component.ts, src/app/combo/combo.sample.html, src/app/combo/combo.sample.ts
=> Fix - Combo - Hide Search input when !filterable && !allowCustomValues - 6.2.x

projects/igniteui-angular/src/lib/core/styles/base/utilities/_functions.scss, projects/igniteui-angular/src/lib/core/styles/themes/_index.scss, projects/igniteui-angular/src/lib/core/styles/themes/_palettes.scss, projects/igniteui-angular/src/lib/core/styles/themes/schemas/dark/_index.scss, projects/igniteui-angular/src/lib/core/styles/themes/schemas/light/_index.scss
We can still resolve the contrast colors for each color in the palette
'just-in-time'. No need to resolve all contrast colors beforehand.
Closes #
=> refactor(themes): don't include contrast colors in the palettes

projects/igniteui-angular/src/lib/grids/grid-base.component.ts, projects/igniteui-angular/src/lib/grids/grid-header-group.component.ts, projects/igniteui-angular/src/lib/grids/grid/column-resizing.spec.ts, projects/igniteui-angular/src/lib/grids/grid/grid.component.html, projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid.component.html
=> fix(grid): set min width to header groups programmatically

projects/igniteui-angular/src/lib/services/transaction/igx-hierarchical-transaction.ts, projects/igniteui-angular/src/lib/services/transaction/igx-transaction.spec.ts, projects/igniteui-angular/src/lib/services/transaction/igx-transaction.ts
Closes #2921 
Fixes next bugs:
- calling endPending(true) does not fire onStateUpdate;
- calling getAggregatedChanges(false) throws error when there are deleted transactions with null recordRef.
=> Treegrid batch update fixes, #2921

projects/igniteui-angular/src/lib/grids/grid/grid-filtering-ui.spec.ts, projects/igniteui-angular/src/lib/grids/grid/grid-filtering.spec.ts
=> Fix the logic calculating test results

projects/igniteui-angular/package.json
Closes #  
Bumping dep version used by `ng add` to install the latest Ignite UI CLI version [v3.2.0](https://github.com/IgniteUI/igniteui-cli/releases/tag/v3.2.0). Affects only the add schematic, so it's a contained change.
=> chore(ng-add): bump Ignite UI CLI version

projects/igniteui-angular/src/lib/directives/for-of/for_of.directive.spec.ts, projects/igniteui-angular/src/lib/directives/for-of/for_of.directive.ts
=> Preventing wrap-around for scrollNext and scrollPrev -- MASTER

projects/igniteui-angular/src/lib/grids/grid-base.component.ts, projects/igniteui-angular/src/lib/grids/grid/grid.component.spec.ts, projects/igniteui-angular/src/lib/services/transaction/igx-hierarchical-transaction.ts
=> Fix - Transactions - Gird Transactions + Paging interactions - Master

CHANGELOG.md
=>  docs(*): updating changelog for 7.1.x #3495

projects/igniteui-angular/src/lib/grids/filtering/grid-filtering-cell.component.ts
=> Scroll filtered column in view

projects/igniteui-angular/src/lib/grids/cell.component.ts, projects/igniteui-angular/src/lib/grids/grid/grid.component.spec.ts
=> Focus the default inputs when cell enter edit mode

projects/igniteui-angular/src/lib/grids/api.service.ts, projects/igniteui-angular/src/lib/grids/grid-base.component.ts, projects/igniteui-angular/src/lib/grids/grid/grid-row.component.html, projects/igniteui-angular/src/lib/grids/grid/grid.component.spec.ts, projects/igniteui-angular/src/lib/grids/row.component.ts, projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid-api.service.ts, projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid-integration.spec.ts, projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid-row.component.html, projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid-row.component.ts
=> Fix - Grid - Cannot select deleted row when transactions are in place - master

.github/CONTRIBUTING.md, projects/igniteui-angular/src/lib/core/deprecateDecorators.ts, projects/igniteui-angular/src/lib/date-picker/README.md, projects/igniteui-angular/src/lib/date-picker/date-picker.component.spec.ts, projects/igniteui-angular/src/lib/date-picker/date-picker.component.ts, projects/igniteui-angular/src/lib/directives/toggle/toggle.directive.ts, projects/igniteui-angular/src/lib/grids/cell.component.html, projects/igniteui-angular/src/lib/grids/filtering/grid-filtering-row.component.html, projects/igniteui-angular/src/lib/grids/grid/cell.spec.ts, projects/igniteui-angular/src/lib/grids/tree-grid/tree-cell.component.html, projects/igniteui-angular/src/lib/tabbar/tabbar.component.ts, src/app/date-picker/date-picker.sample.html
Closes #2915 
Rewrite deprecation decorators.
Update contribution.md.
Remove deprecated date picker selector.
=> Rewrite deprecation decorators

CHANGELOG.md, projects/igniteui-angular/src/lib/grids/column.component.ts, projects/igniteui-angular/src/lib/grids/grid/column.spec.ts
=> feat(igx-grid): Expose column templates as inputs

CHANGELOG.md, projects/igniteui-angular/src/lib/calendar/calendar.component.ts, projects/igniteui-angular/src/lib/date-picker/date-picker.component.ts, projects/igniteui-angular/src/lib/grids/README.md, projects/igniteui-angular/src/lib/grids/grid-base.component.ts
=> Make default locale to be 'en'

projects/igniteui-angular/src/lib/directives/input/input.directive.spec.ts, projects/igniteui-angular/src/lib/directives/input/input.directive.ts
=> fix(igxInput): #3550 Setting required input value updates valid state.

projects/igniteui-angular/src/lib/snackbar/README.md, projects/igniteui-angular/src/lib/snackbar/snackbar.component.html, projects/igniteui-angular/src/lib/snackbar/snackbar.component.spec.ts
=> Adding ng-content to IgxSnackbar - master

projects/igniteui-angular/src/lib/directives/for-of/for_of.directive.ts, projects/igniteui-angular/src/lib/grids/column.component.ts, projects/igniteui-angular/src/lib/grids/grid-base.component.ts, projects/igniteui-angular/src/lib/grids/grid/grid-row.component.html, projects/igniteui-angular/src/lib/grids/grid/grid.component.html, projects/igniteui-angular/src/lib/grids/grid/grid.component.spec.ts, projects/igniteui-angular/src/lib/grids/summaries/summary-row.component.html, src/app/grid-selection/grid-selection.sample.html, src/app/grid-selection/grid-selection.sample.ts
=> fix(Grid): fix and tests for #3513. Adding new prop from which to read actual px width for grid cols and using it in igxForOf calculations.

projects/igniteui-angular/src/lib/date-picker/date-picker.component.ts, projects/igniteui-angular/src/lib/grids/filtering/grid-filtering-row.component.ts
=> Call markForCheck in writeValue method

projects/igniteui-angular/src/lib/directives/input/input.directive.ts
Closes #3550
Unnecessary validation was happening because _hasValidators was used as a property instead of a method.
=> #3550 Fixed an issue with the initial validation fix. 

projects/igniteui-angular/src/lib/list/list.component.html, projects/igniteui-angular/src/lib/list/list.component.spec.ts
Closes #3602 
The loading template would be shown always when isLoading='true' even when list items are present (to allow for using it when loading data in portions, etc.).
=> Allow for showing the loading template even when list items are present.

projects/igniteui-angular/src/lib/directives/input/input.directive.spec.ts, projects/igniteui-angular/src/lib/directives/input/input.directive.ts
Closes #3550 
Unnecessary valid/invalid styles were applied because _hasValidators was used a property instead of a method.
=> #3550 Fixed an issue with the initial validation fix.

projects/igniteui-angular/src/lib/grids/grid-base.component.ts, projects/igniteui-angular/src/lib/grids/grid/grid.component.spec.ts
=> fix(grid): igxGrid isn't displayed properly in IE11 if in igxTabs #3047

projects/igniteui-angular/src/lib/grids/filtering/grid-filtering-row.component.ts
Closes #3599 
Please check #3504 again to make sure we have not regressed it.
=> fix(filtering): chips creation while typing in JP on Edge

projects/igniteui-angular/src/lib/directives/text-highlight/text-highlight.directive.ts, projects/igniteui-angular/src/lib/grids/cell.component.ts, projects/igniteui-angular/src/lib/grids/grid/grid.search.spec.ts
=> Fix search highlight after entering edit mode - 7.1.x

CHANGELOG.md, projects/igniteui-angular/migrations/common/UpdateChanges.spec.ts, projects/igniteui-angular/migrations/common/UpdateChanges.ts, projects/igniteui-angular/migrations/migration-collection.json, projects/igniteui-angular/migrations/update-7_2_0/changes/inputs.json, projects/igniteui-angular/migrations/update-7_2_0/index.spec.ts, projects/igniteui-angular/migrations/update-7_2_0/index.ts, projects/igniteui-angular/src/lib/combo/combo-add-item.component.ts, projects/igniteui-angular/src/lib/combo/combo-dropdown.component.ts, projects/igniteui-angular/src/lib/combo/combo-item.component.html, projects/igniteui-angular/src/lib/combo/combo-item.component.ts, projects/igniteui-angular/src/lib/combo/combo.component.spec.ts, projects/igniteui-angular/src/lib/drop-down/README.md, projects/igniteui-angular/src/lib/drop-down/drop-down-item.base.ts, projects/igniteui-angular/src/lib/drop-down/drop-down-item.component.ts, projects/igniteui-angular/src/lib/drop-down/drop-down.component.spec.ts, projects/igniteui-angular/src/lib/drop-down/drop-down.component.ts, src/app/drop-down/drop-down.sample.html
Closes #3612  
Rename `isSelected` and `isFocused` accessors. Add `selected` and `focused` accessors (with the same functionality)
=> Deprecate IgxDropDownItemBase isSelected && isFocused

projects/igniteui-angular/src/lib/combo/combo.component.ts
Closes #3614 
Combo component now properly provides `NG_VALUE_ACCESSOR` as well as `NG_VALIDATOR`
Added `getEditElement(): HTMLElement` method to be used from the `IgxFocus` directive.
=> refactor(combo): refactor combo ng_value_accessor implementation, #3614

projects/igniteui-angular/src/lib/expansion-panel/expansion-panel.component.ts, projects/igniteui-angular/src/lib/expansion-panel/expansion-panel.spec.ts
Closes #3669 
This prevents an error being thrown when calling `expansionPanel.collapse` or `banner.close` when the component is already collapsed.
=> Fix - Expansion Panel - Do not play collapse animation if panel is already collapsed - 7.1.x

projects/igniteui-angular/src/lib/expansion-panel/expansion-panel.component.ts, projects/igniteui-angular/src/lib/expansion-panel/expansion-panel.spec.ts
Closes #3669 
This prevents an error being thrown when calling `expansionPanel.collapse` or `banner.close` when the component is already collapsed.
=> Fix - Expansion Panel - Do not play collapse animation if panel is already collapsed - 7.2.x

projects/igniteui-angular/src/lib/core/styles/components/grid/_grid-theme.scss
=> fix(grid): remove empty css property warnings in prod builds

projects/igniteui-angular/src/lib/directives/text-highlight/text-highlight.directive.ts, projects/igniteui-angular/src/lib/grids/cell.component.html, projects/igniteui-angular/src/lib/grids/cell.component.ts, projects/igniteui-angular/src/lib/grids/grid-base.component.ts, projects/igniteui-angular/src/lib/grids/grid/grid.search.spec.ts, projects/igniteui-angular/src/lib/grids/tree-grid/tree-cell.component.html, projects/igniteui-angular/src/lib/grids/tree-grid/tree-cell.component.ts, projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid-api.service.ts, projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid.component.ts
Closes #3520
Closes #3653
#3637
#3631
=> Refactor highlight directive applying

projects/igniteui-angular/src/lib/directives/text-highlight/text-highlight.directive.ts, projects/igniteui-angular/src/lib/grids/cell.component.html, projects/igniteui-angular/src/lib/grids/cell.component.ts, projects/igniteui-angular/src/lib/grids/grid-base.component.ts, projects/igniteui-angular/src/lib/grids/grid/grid.search.spec.ts, projects/igniteui-angular/src/lib/grids/tree-grid/tree-cell.component.html
Closes #3520
Closes #3653 
#3637
#3631
=> Refactor highlight directive applying - 7.1.x

projects/igniteui-angular/src/lib/directives/toggle/toggle.directive.spec.ts, projects/igniteui-angular/src/lib/directives/tooltip/tooltip.directive.spec.ts, projects/igniteui-angular/src/lib/services/overlay/overlay.spec.ts, projects/igniteui-angular/src/lib/services/overlay/position/connected-positioning-strategy.ts, projects/igniteui-angular/src/lib/services/overlay/position/elastic-position-strategy.ts
Up to now position strategies have calculated position where we should draw the shown element as fractional numbers, e.g. 158.56376px. Positioning like this lead to the bellow mentioned issue. What we are doing now is before set position we are rounding it to a whole number.
Closes #3820
=> Postion component wrapper on exact pixel location 7.1.x

projects/igniteui-angular/src/lib/grids/grid/grid.component.ts, projects/igniteui-angular/src/lib/grids/grid/grid.groupby.spec.ts
=> fix(Grid): Hide grouped columns after columns have been generated in ngAfterContentInit.

CHANGELOG.md, projects/igniteui-angular/src/lib/services/overlay/README.md, projects/igniteui-angular/src/lib/services/overlay/overlay.spec.ts, projects/igniteui-angular/src/lib/services/overlay/overlay.ts
Attach method accepts now NgModuleRef. If attach is called with NgModuleRef overlay service will use NgModuleRef's ComponentFactoryResolver and Injector.
Closes #3988
=> fix(igxOverlay): add NgModuleRef param to attach, #3988

projects/igniteui-angular/src/lib/directives/autocomplete/autocomplete.directive.spec.ts, projects/igniteui-angular/src/lib/directives/autocomplete/autocomplete.directive.ts
=> Calculate width before opening the drop down 

src/styles/igniteui-theme.scss
Closes #3716  
Closes #3717 
[Autoprefixer](https://github.com/postcss/autoprefixer#does-autoprefixer-polyfill-grid-layout-for-ie) plugin is used to translate modern CSS Grid syntax into IE 11 syntax, it will enable -ms- prefixes for Grid Layout. In order to enable it in our Dev samples I use the second approach `/* autoprefixer grid: autoplace */`, instead of enabling the grid prefixes with `grid: "autoplace"`
=> fix(grid): Enabling grid prefixes for IE 11 #3716

projects/igniteui-angular/src/lib/grids/grid-header.component.html, projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.integration.spec.ts
=> fix(igxHierarchicalGrid): There is no possible way to get row island column reference specific to grid through template.

projects/igniteui-angular/src/lib/grids/grid-base.component.ts, projects/igniteui-angular/src/lib/grids/grid/grid.component.spec.ts
=> fix(grid): Fix calculate height when initially grid has no data #3950

projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.component.html, projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.integration.spec.ts
=> fix(hgrid): Set summary indentation to 0 for leaf childs #4108

projects/igniteui-angular/src/lib/directives/toggle/toggle.directive.ts
In onClick handler we were calling deprecated `closeOnOutsideClick` property. This was logging a deprecation message. Now we are calling directly the inner field and bypassing the property.
Closes #4126
=> Remove calls to closeOnOutsideClick property

projects/igniteui-angular/src/lib/combo/combo.component.spec.ts, projects/igniteui-angular/src/lib/core/selection.ts
Closes #4106
When `add_items` is called with an empty Array, the result would be undefined, even if the selection was not empty.
=> fix(selection): do not clear selection on `add_items` with empty array

projects/igniteui-angular/src/lib/core/styles/typography/_base.scss
=> Adding 16px to the default typography scale for the body-1 rule

projects/igniteui-angular/src/lib/services/excel/excel-exporter-grid.spec.ts, projects/igniteui-angular/src/lib/services/excel/test-data.service.spec.ts, projects/igniteui-angular/src/lib/services/exporter-common/base-export-service.ts, projects/igniteui-angular/src/lib/services/exporter-common/export-utilities.ts
Set 'Column[N]' header to columns without header set when exporting(frequent case for template columns)
Closes #3763
=> fix(excelExporter): Set empty column header when exporting #3763

projects/igniteui-angular/src/lib/core/styles/components/overlay/_overlay-component.scss, projects/igniteui-angular/src/lib/core/styles/components/overlay/_overlay-theme.scss, projects/igniteui-angular/src/lib/services/overlay/position/global-position-strategy.ts
When position strategy is global we are using flex container to position the content. In this case, in order to position content correctly even in IE, we should set content div's position to relative.
Closes #4220
=> Change content div position to relative in flex wrapper

projects/igniteui-angular/src/lib/combo/combo.component.ts
Closes #4303 
Focusing the search input in IE causes Angular's `ngValueChanged` event to be fired (not fired in other browsers). When no change is made to the search value, the `handleSearchInput` method will no longer run.
=> fix(combo): do not run filter + emit if search input value is unchanged

projects/igniteui-angular/src/lib/directives/for-of/for_of.directive.spec.ts, projects/igniteui-angular/src/lib/directives/for-of/for_of.directive.ts
Should fix scenarios when expanding/collapsing in TreeGrid/HierarchicalGrid results in white space when items with large size are added to the view.
=> fix(igxFor): Fixing chunksize calculations so that vertical space is always filled for last chunk.

projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.component.ts
=> fix(HierarchicalGrid):  Making sure correct  pinned width is set when child grid width in % and there is expander.

projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.component.ts
=> calculateGridSizes should not get called in ngAfterContentInit - igxHierarchicalGrid

projects/igniteui-angular/src/lib/core/styles/components/input/_input-group-theme.scss
The text in the input would appear cut-off in Safari. This can happen
when the font-family's font height is slightly larger than the input
height. Substract a pixel from the font-size in compact mode of the
input to allow a bit of leeway.
Closes #4496
=> refactor(input-group): fix visual glitches in safari and firefox

projects/igniteui-angular/src/lib/progressbar/templates/circular-bar.component.html
Remove id attr and #text template reference variable because it is not use anywhere in the progress bar implementation.
Closes #4410
=> fix(circular-bar): Remove id attr and #text template reference variable

projects/igniteui-angular/src/lib/progressbar/templates/circular-bar.component.html
Remove id attr and #text template reference variable because it is not use anywhere in the progress bar implementation.
Closes #4410
=> fix(circular-bar): Remove id attr and  #text template reference variable 

projects/igniteui-angular/src/lib/core/styles/components/button/_button-theme.scss, src/app/button/button.sample.css, src/app/button/button.sample.html
1. set border only for outline buttons to make the height consistent
2. Make the icon size inside a button to correspond to a material spec
Closes #4604
=> Fix buttons with icons to have consistent height:

projects/igniteui-angular/src/lib/data-operations/multi-row-layout.interfaces.ts, projects/igniteui-angular/src/lib/grids/column.component.ts, projects/igniteui-angular/src/lib/grids/grid-base.component.ts, projects/igniteui-angular/src/lib/grids/grid-column-resizing.service.ts, projects/igniteui-angular/src/lib/grids/grid/grid.multi-row-layout.integration.spec.ts
=> Multi-row layout - Resizing feature integration.

projects/igniteui-angular/src/lib/grids/grid-mrl-navigation.service.ts, projects/igniteui-angular/src/lib/grids/grid-navigation.service.ts, projects/igniteui-angular/src/lib/grids/grid.rowEdit.directive.ts, projects/igniteui-angular/src/lib/grids/grid/grid-mrl-keyboard-nav.spec.ts
Following bugs have been resolved: 
1) When navigation with shift+tab and prev cell is not in horizontal virtual view, prev cell is not scrolled in view.
2) When navigating with Shift + Tab when in edit mode of 1st cell focus  goes to previous row.
3) Edit mode is exited when navigating trough a non editable cell
4) When the last column layout is pinned and press Ctr+End or Pres arrow key and error is returned
=> mrl-nav bug fixing

projects/igniteui-angular/src/lib/grids/grid/row-drag.directive.spec.ts, projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.component.ts
=> fix(hgrid): rowDraggable is applied only to row islands where set #4789

projects/igniteui-angular/src/lib/core/touch.ts
upgrade to angular 8 does not work because DOCUMENT does not imports from platform-browser any more
=> refactor: move DOCUMENT imports from platform-browser to common

projects/igniteui-angular/src/lib/directives/filter/filter.directive.ts, projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-search.component.html, projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-search.component.ts, projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-search.pipe.ts, projects/igniteui-angular/src/lib/grids/filtering/excel-style/grid.excel-style-filtering.module.ts
Closes #4862
The reason for this change is that the igxFilterPipe is impure and is evaluated on each change detection (triggered by click or other events) even if the filtering options are not changed. The new pipe is pure and is called only when the search text is changed.
=> Replace the igxFilterPipe with a separate ESF specific pipe

projects/igniteui-angular/src/lib/grids/grid-base.component.ts, projects/igniteui-angular/src/lib/grids/grid/grid.component.spec.ts, projects/igniteui-angular/src/lib/grids/grid/row-drag.directive.spec.ts
Closes #3770
PR adds a warning to the `rowEditable` setter that is logged only when `rowEditable` is set to `true` and there is no `primaryKey`
=> fix(grid): add warning to `rowEditable` in grid w/o primaryKey, #3770

projects/igniteui-angular/src/lib/grids/column.component.ts, projects/igniteui-angular/src/lib/grids/grid-base.component.ts, projects/igniteui-angular/src/lib/grids/grid-mrl-navigation.service.ts, projects/igniteui-angular/src/lib/grids/grid-navigation.service.ts, projects/igniteui-angular/src/lib/grids/grid/grid-mrl-keyboard-nav.spec.ts, src/app/app.component.ts, src/app/app.module.ts, src/app/grid-mrl-custom-navigation/grid-mrl-custom-navigation.sample.html, src/app/grid-mrl-custom-navigation/grid-mrl-custom-navigation.ts, src/app/grid-multi-row-layout/grid-mrl.sample.html, src/app/routing.ts
This PR includes:
1) MRL Custom Navigation 
- Exposing common perfromVerticalScrollToCell/performHorizontalScrollToCell functions in base navigation and mrl navigation service, which can be used for the public navigateTo method.
- Adding custom navigation sample with custom navigation up/down via Enter/Shift+Enter keys.
2) Calculating cell top/left offsets in pixels and using it when scrolling it in view(getVerticalScrollPositions/getChildColumnScrollPositions) as implemented here: https://github.com/IgniteUI/igniteui-angular/pull/4882/
3) Additional refactoring to minimize duplicated code specifically in focusCellUpFromLayout/focusCellDownFromLayout/focusNextCellFromLayout/focusPrevCellFromLayout functions.
=> MRL Custom Navigation + basic refactoring and custom nav sample

projects/igniteui-angular/src/lib/core/styles/components/grid/_grid-theme.scss, src/app/grid-multi-row-layout/grid-mrl.sample.html
When using the grid in MRL mode with row editing enabled, the
indentation border would overwrite the row border.
Closes #4968
=> fix(grid): indentation overwrites border of row in edit mode

CHANGELOG.md, projects/igniteui-angular/src/lib/core/styles/components/slider/_slider-theme.scss, projects/igniteui-angular/src/lib/slider/README.md, projects/igniteui-angular/src/lib/slider/slider.component.html, projects/igniteui-angular/src/lib/slider/slider.component.spec.ts, projects/igniteui-angular/src/lib/slider/slider.component.ts, projects/igniteui-angular/src/lib/slider/thumb/thumb-slider.component.html, projects/igniteui-angular/src/lib/slider/thumb/thumb-slider.component.ts, src/app/slider/slider.sample.html, src/app/slider/slider.sample.scss, src/app/slider/slider.sample.ts
Closes #3449
Closes #4562
Closes #4559 
Closes #2622
=> labels feature and refactoring SLIDER

CHANGELOG.md, projects/igniteui-angular/src/lib/grids/api.service.ts, projects/igniteui-angular/src/lib/grids/filtering/grid-filtering.service.ts, projects/igniteui-angular/src/lib/grids/grid-base.component.ts, projects/igniteui-angular/src/lib/grids/grid/grid-filtering.spec.ts
=> Throw descriptive error when filtering without condition - 7.2.x

projects/igniteui-angular/src/lib/core/grid-selection.ts, projects/igniteui-angular/src/lib/core/utils.ts, projects/igniteui-angular/src/lib/grids/cell.component.ts, projects/igniteui-angular/src/lib/grids/grid/grid-keyBoardNav.spec.ts, projects/igniteui-angular/src/lib/grids/grid/grid-mrl-keyboard-nav.spec.ts, projects/igniteui-angular/src/lib/grids/grid/grid-multi-cell-selection.spec.ts, projects/igniteui-angular/src/lib/grids/grid/grid.component.spec.ts, projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-cell.component.ts, projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid-keyBoardNav.spec.ts, projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid-selection.spec.ts, projects/igniteui-angular/src/lib/test-utils/helper-utils.spec.ts, projects/igniteui-angular/src/lib/test-utils/tree-grid-functions.spec.ts, projects/igniteui-angular/src/lib/test-utils/ui-interactions.spec.ts
=> fix(igx-grid): Preserve selection on non-primary click

CHANGELOG.md, projects/igniteui-angular/src/lib/combo/README.md, projects/igniteui-angular/src/lib/combo/combo-dropdown.component.ts, projects/igniteui-angular/src/lib/combo/combo.component.html, projects/igniteui-angular/src/lib/combo/combo.component.spec.ts, projects/igniteui-angular/src/lib/combo/combo.component.ts, projects/igniteui-angular/src/lib/core/styles/components/drop-down/_drop-down-component.scss, projects/igniteui-angular/src/lib/core/styles/components/drop-down/_drop-down-theme.scss, projects/igniteui-angular/src/lib/drop-down/README.md, projects/igniteui-angular/src/lib/drop-down/drop-down-item.base.ts, projects/igniteui-angular/src/lib/drop-down/drop-down.base.ts, projects/igniteui-angular/src/lib/drop-down/drop-down.common.ts, projects/igniteui-angular/src/lib/drop-down/drop-down.component.spec.ts, projects/igniteui-angular/src/lib/drop-down/drop-down.component.ts, projects/igniteui-angular/src/lib/select/README.md, projects/igniteui-angular/src/lib/select/select-positioning-strategy.ts, projects/igniteui-angular/src/lib/select/select.component.spec.ts, projects/igniteui-angular/src/lib/select/select.component.ts, src/app/app.component.ts, src/app/app.module.ts, src/app/combo/combo.sample.html, src/app/drop-down/display-density/display-density.sample.html, src/app/drop-down/display-density/display-density.sample.scss, src/app/drop-down/display-density/display-density.sample.ts, src/app/drop-down/drop-down.sample.html, src/app/routing.ts
=> style(drop-down): Adding classes for different density types

CHANGELOG.md, projects/igniteui-angular/package.json, projects/igniteui-angular/schematics/ng-add/index.spec.ts, projects/igniteui-angular/schematics/ng-add/index.ts, projects/igniteui-angular/src/lib/grids/grid-common.pipes.ts, projects/igniteui-angular/src/lib/grids/grid-header-group.component.ts, projects/igniteui-angular/src/lib/grids/grid-header.component.ts, src/polyfills.ts
Closes #5136  
I've checked the list of things the poly adds:
- `Object.prototype.__defineGetter__`
- `Object.prototype.__defineSetter__`
- `Object.prototype.__lookupGetter__`
- `Object.prototype.__lookupSetter__`
- `Object.entries`
- `Object.getOwnPropertyDescriptors`
- `Object.values`
Of which we used just the `entries`.
=> Remove usage of ES7 Object.entries and polyfill requirement

projects/igniteui-angular/src/lib/core/grid-selection.ts, projects/igniteui-angular/src/lib/grids/grid/grid-multi-cell-selection.spec.ts
Fixed a possible error with an empty range when restoring the document
selection
Closes #5135
=> fix(igx-grid): getSelectedRanges inside event handler

projects/igniteui-angular/src/lib/core/styles/base/utilities/_mixins.scss
Closes #5152
Also improves igx-palette-vars
=> refactor(themes): igx-css-vars must ignore nested maps

package-lock.json, package.json, projects/igniteui-angular/package.json
New https://github.com/web-animations/web-animations-js/releases/tag/2.3.2 cantaning the fix for angular builds
=> chore(*): bump web-animations-js to new patched version

CHANGELOG.md, projects/igniteui-angular/src/lib/combo/combo.component.spec.ts, projects/igniteui-angular/src/lib/combo/combo.component.ts
=> Fix - IgxCombo - Change combo default height to 40, itemsMaxHeight scales w/ item Height - 7.3.x

CHANGELOG.md, projects/igniteui-angular/src/lib/combo/combo.component.spec.ts, projects/igniteui-angular/src/lib/combo/combo.component.ts
=> Fix - IgxCombo - Change combo default height to 40, itemsMaxHeight scales w/ item Height - 8.0.x

projects/igniteui-angular/src/lib/grids/grid/grid.component.spec.ts
Force test to wait additional 30ms after focus moves from cancel button to the last cell. This allows cell to has time to get focus and to enter in edit mode.
Closes - there is no issue for this fix.
=> Fix grid flickering test

projects/igniteui-angular/src/lib/select/select-positioning-strategy.ts, projects/igniteui-angular/src/lib/services/overlay/overlay.spec.ts, projects/igniteui-angular/src/lib/services/overlay/position/base-fit-position-strategy.ts, projects/igniteui-angular/src/lib/services/overlay/position/connected-positioning-strategy.ts, projects/igniteui-angular/src/lib/services/overlay/position/global-position-strategy.ts, projects/igniteui-angular/src/lib/services/overlay/utilities.ts
We should not use `export function`. The new ES defines exported functions via `definePorperty`. This makes the exported functions as read-only properties. When Jasmine tries to spy on such function it fails and throws an exception.
To solve this put all the functions to a new class as static methods. This is what I am doing in this PR.
Closes #4986
=> Move overlay utilities functions to static class

projects/igniteui-angular/src/lib/grids/grid-base.component.ts, projects/igniteui-angular/src/lib/grids/grid/grid.component.spec.ts, projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid.component.ts
Closes #5214
Entering edit mode creates an internal transaction in a pending state. This prevents the addition of a new row since it has not completed. Now if you are in edit mode and you attempt to add a new row - the previous pending state will be committed.
=> Commit pending transactions on addRow - 7.3.x

projects/igniteui-angular/src/lib/grids/grid-base.component.ts, projects/igniteui-angular/src/lib/grids/grid/grid.component.spec.ts, projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid.component.ts
Closes #5214   
Entering edit mode creates an internal transaction in a pending state. This prevents the addition of a new row since it has not completed. If you attempt to add a new row - the previous pending state(s) will be committed.
=> Commit pending transactions on addRow - master

projects/igniteui-angular/src/lib/grids/grid-base.component.ts, projects/igniteui-angular/src/lib/grids/grid-navigation.service.ts, projects/igniteui-angular/src/lib/grids/grid/grid.component.spec.ts, src/app/grid-row-edit/grid-row-edit-sample.component.html, src/app/select/select.sample.ts
If the last edited cell is not visible grid was not able to focus it. Now, on end edit, we are scrolling to the last edited cell and focus it. This allows user to continue keyboard navigation.
Closes #5181
=> Focus last edited cell on end edit 7.3.x

projects/igniteui-angular/src/lib/grids/grid-base.component.ts, projects/igniteui-angular/src/lib/grids/grid-navigation.service.ts, projects/igniteui-angular/src/lib/grids/grid/grid.component.spec.ts
If the last edited cell is not visible grid was not able to focus it. Now, on end edit, we are scrolling to the last edited cell and focus it. This allows user to continue keyboard navigation.
Closes #5181
=> Focus last edited cell on end edit, master

projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid-integration.spec.ts, projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid.component.ts
Add a check if the parent row has a deleted state. If so do not add child row.
Closes #5237
=> Should not add child row to deleted parent row

projects/igniteui-angular/src/lib/grids/grid-base.component.ts, projects/igniteui-angular/src/lib/grids/grid/grid.component.spec.ts
Row edit should be completed on density change. Otherwise we may go into situation where customer changes the density from compact to comfortable. In this case, if customer is editing the last row, this row will go out of view and we should scroll the grid.
Closes #5261
=> Should exit row edit on display density change 7.3

projects/igniteui-angular/src/lib/grids/grid-base.component.ts, projects/igniteui-angular/src/lib/grids/grid/grid.component.spec.ts
Row edit should be completed on density change. Otherwise we may go into situation where customer changes the density from compact to comfortable. In this case, if customer is editing the last row, this row will go out of view and we should scroll the grid.
Closes #5261
=> Should exit row edit on display density change 8.0

projects/igniteui-angular/src/lib/grids/grid-base.component.ts, projects/igniteui-angular/src/lib/grids/grid/grid.component.spec.ts
Row edit should be completed on density change. Otherwise we may go into situation where customer changes the density from `compact` to `comfortable`. In this case, if customer is editing the last row, this row will go out of view and we should scroll the grid.
Closes #5261
=> Should exit row edit on display density change

projects/igniteui-angular/src/lib/grids/grid-base.component.ts, projects/igniteui-angular/src/lib/grids/grid/grid.component.spec.ts
=> Make sure that if grid is created in detached state and height is in %, then size is recalculated once it is added back in the DOM. 

projects/igniteui-angular/src/lib/grids/grid-base.component.ts, projects/igniteui-angular/src/lib/grids/grid/grid.component.spec.ts
=> Make sure that if grid is created in detached state and height is in %, then size is recalculated once it is added back in the DOM.

projects/igniteui-angular/src/lib/grids/grid-base.component.ts, projects/igniteui-angular/src/lib/grids/grid/cell.spec.ts
First update the grid state then change the `rowEditable`. Finally call `markForCheck` in order to update the grid UI.
Closes #5233
=> End edit on rowEditable change 7.3.x

projects/igniteui-angular/src/lib/grids/grid-base.component.ts, projects/igniteui-angular/src/lib/grids/grid/cell.spec.ts
First update the grid state then change the `rowEditable`. Finally call `markForCheck` in order to update the grid UI.
Closes #5233
=> End edit on rowEditable change

projects/igniteui-angular/src/lib/grids/grid-base.component.ts, projects/igniteui-angular/src/lib/grids/grid/cell.spec.ts
First update the grid state then change the `rowEditable`. Finally call `markForCheck` in order to update the grid UI.
Closes #5233
=> End edit on rowEditable change 8.0.x

projects/igniteui-angular/src/lib/grids/grid-navigation.service.ts, projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid-navigation.service.ts
Closes #4488
Internet explorer doesn't support [preventScroll](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/focus) option. Try this sample [here](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/focus#Focus_prevent_scroll) (Click on the "Click me to focus on the button without scrolling!" in IE).
This is why we should not focus on a child grid but rather on the parent grid in some cases when using keyboard navigation in IE.
Please test the solution for IE with ctr + right, ctr + left, home, end, arrowLeft and arrowRight navigation keys.
=> Focusing on parent grid using keyboard navigation in IE.

projects/igniteui-angular/src/lib/directives/for-of/for_of.directive.ts
… as a result of variable row sizes when scrolled to bottom.
Closes #5371
=> fix(igxFor): Update cached scroll position in case sizes have changed

projects/igniteui-angular/src/lib/grids/column.component.ts, projects/igniteui-angular/src/lib/grids/grid-base.component.ts, projects/igniteui-angular/src/lib/grids/grid/grid.component.spec.ts
Default value of `column.editable` was null. This was not correct. Now default value of inner field is `undefined`. The getter now checks if `editable` is set. If so returns what is set by the developer. If not returns what is set for `rowEditable` (if the column is primary column returns false in this case).
Closes #5022
=> Calculate column editable depending on rowEditable, 7.3.x

projects/igniteui-angular/src/lib/core/grid-selection.ts, projects/igniteui-angular/src/lib/grids/cell.component.ts, projects/igniteui-angular/src/lib/grids/column.component.ts, projects/igniteui-angular/src/lib/grids/grid/grid-mrl-keyboard-nav.spec.ts, projects/igniteui-angular/src/lib/grids/grid/grid-summary.spec.ts, projects/igniteui-angular/src/lib/grids/grid/grid.component.spec.ts
Editing of the primary key column should not be possible for grid with transactions.
Closes #5020
=> Disallow editing or primary column in grid with transactions, 7.3.x

projects/igniteui-angular/src/lib/core/styles/themes/_index.scss
igx-dark-theme and igx-light-theme mixins don't respect custom success,
error, warn, and info colors
Closes #5372
=> fix(themes): light/dark mixins don't respect custom colors

projects/igniteui-angular/src/lib/core/grid-selection.ts, projects/igniteui-angular/src/lib/grids/cell.component.ts
We should check if same row is edited by ID, not by row index. Collapsing/expanding changes the row indexes and this move editable cell to different row.
=> Revert sameRow check to use rowID, 7.3.x

projects/igniteui-angular/src/lib/core/grid-selection.ts, projects/igniteui-angular/src/lib/grids/cell.component.ts
We should check if same row is edited by ID, not by row index. Collapsing/expanding changes the row indexes and this move editable cell to different row.
=> Revert sameRow check to use rowID, 8.0.x

projects/igniteui-angular/src/lib/core/grid-selection.ts, projects/igniteui-angular/src/lib/grids/cell.component.ts
We should check if same row is edited by ID, not by row index. Collapsing/expanding changes the row indexes and this move editable cell to different row.
=> Revert sameRow check to use rowID

projects/igniteui-angular/src/lib/grids/grid/grid-api.service.ts, projects/igniteui-angular/src/lib/grids/grid/grid.component.spec.ts, projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.spec.ts, projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-row.component.ts
When hierarchical/grouped grid expand or collapse its rows we should exit edit mode.
Closes #4761
Closes #5044
=> Exit edit mode on collapse/expand, 7.3.x

projects/igniteui-angular/src/lib/core/utils.ts, projects/igniteui-angular/src/lib/grids/grid/column-resizing.spec.ts, projects/igniteui-angular/src/lib/grids/grid/grid.multi-row-layout.spec.ts
=> Update evaluating of 'grid-template-rows' style to reflect how chrome 76 sets it now. 

projects/igniteui-angular/src/lib/core/touch.ts, projects/igniteui-angular/src/lib/grids/cell.component.ts, projects/igniteui-angular/src/lib/grids/grid/cell.spec.ts, projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-cell.component.ts, projects/igniteui-angular/src/lib/grids/tree-grid/tree-cell.component.ts
Since iOS WebKit doesn't support dblclick and Angular's Hammer plugin doesn't
have doubletap exposed, resorting to our Hammer manager. Also prevented the
double tap to zoom on the cell as it was rather jarring.
Closes #2538
=> fix(grids): handle double tap to allow editing on iOS #2538

CHANGELOG.md, projects/igniteui-angular/src/lib/date-picker/README.md, projects/igniteui-angular/src/lib/date-picker/date-picker.component.spec.ts, projects/igniteui-angular/src/lib/date-picker/date-picker.component.ts, projects/igniteui-angular/src/lib/grids/cell.component.html, projects/igniteui-angular/src/lib/grids/grid/cell.spec.ts, projects/igniteui-angular/src/lib/grids/tree-grid/tree-cell.component.html
=> Add date picker event onValueChanged and use it to update cell value when column type is date

projects/igniteui-angular/src/lib/tabs/tab-item.component.ts, projects/igniteui-angular/src/lib/tabs/tabs-group.component.ts, projects/igniteui-angular/src/lib/tabs/tabs.common.ts, projects/igniteui-angular/src/lib/tabs/tabs.component.spec.ts, projects/igniteui-angular/src/lib/tabs/tabs.component.ts, src/app/tabs-routing/tabs-routing.sample.html, src/app/tabs-routing/tabs-routing.sample.ts
=> fix(Tabs): refactoring tabs selection

projects/igniteui-angular/src/lib/grids/filtering/grid-filtering-row.component.html, projects/igniteui-angular/src/lib/grids/filtering/grid-filtering-row.component.ts, projects/igniteui-angular/src/lib/grids/grid/grid-filtering-ui.spec.ts
=> fix(filtering): Scroll chips before remove #5304

projects/igniteui-angular/src/lib/grids/grid-base.component.ts, projects/igniteui-angular/src/lib/grids/grid/grid-filtering-ui.spec.ts, projects/igniteui-angular/src/lib/grids/grid/grid.component.html, projects/igniteui-angular/src/lib/grids/grid/grid.component.spec.ts, projects/igniteui-angular/src/lib/grids/grid/row-drag.directive.spec.ts, projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.component.html, projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.component.ts, projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid.component.html
=> fix(igxGrid): Grid should render all columns when grid width is set to null. 

.travis.yml, azure-pipelines.yml, projects/igniteui-angular/src/lib/banner/banner.component.ts, projects/igniteui-angular/src/lib/calendar/calendar.component.ts, projects/igniteui-angular/src/lib/combo/combo.component.ts, projects/igniteui-angular/src/lib/date-picker/date-picker.component.ts, projects/igniteui-angular/src/lib/grids/column.component.ts, projects/igniteui-angular/src/lib/grids/grid-base.component.ts, projects/igniteui-angular/src/lib/grids/grid/grid.component.ts, projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid.component.ts, projects/igniteui-angular/src/lib/list/list.component.ts, projects/igniteui-angular/src/lib/navbar/navbar.component.ts, projects/igniteui-angular/src/lib/progressbar/progressbar.component.ts, projects/igniteui-angular/src/lib/select/select.component.ts, projects/igniteui-angular/src/lib/slider/slider.component.ts, projects/igniteui-angular/src/lib/tabbar/tabbar.component.ts, projects/igniteui-angular/src/lib/tabs/tab-item.component.ts, projects/igniteui-angular/src/lib/tabs/tabs-group.component.ts, projects/igniteui-angular/src/lib/time-picker/time-picker.component.ts
=> Change static flag for templates to false - 8.1.x

CHANGELOG.md, projects/igniteui-angular/src/lib/dialog/README.md, projects/igniteui-angular/src/lib/dialog/dialog.component.spec.ts, projects/igniteui-angular/src/lib/dialog/dialog.component.ts, src/app/dialog/dialog.sample.css, src/app/dialog/dialog.sample.html, src/app/dialog/dialog.sample.ts
=> Dialog: Add position settings input 

CHANGELOG.md, projects/igniteui-angular/src/lib/dialog/README.md, projects/igniteui-angular/src/lib/dialog/dialog.component.spec.ts, projects/igniteui-angular/src/lib/dialog/dialog.component.ts, src/app/dialog/dialog.sample.css, src/app/dialog/dialog.sample.html, src/app/dialog/dialog.sample.ts
=> Dialog: Add position settings input

projects/igniteui-angular/src/lib/core/styles/components/_common/_igx-display-container.scss, projects/igniteui-angular/src/lib/grids/grid/grid.component.spec.ts
Disallow display container shrinkage to prevent inner content(cells)
from having different widths when set in fraction values (%).
Closes #3918
=> fix(grid): set flex shrink to 0 for all display containers

projects/igniteui-angular/src/lib/core/styles/components/grid/_grid-theme.scss
Set the grid's z-index to 1 instead of 0. This will allow whatever is shown in overlay through grid's outlets to be shown above elements around the grid.
In case anyone set higher z-index to elements around the grid he should set and appropriate z-index to the grid.
Closes #5674
=> fix(grids): set grids z-index to 1, #5674

projects/igniteui-angular/src/lib/directives/input/input.directive.spec.ts, projects/igniteui-angular/src/lib/directives/input/input.directive.ts
With this fix when ngForm.reset() is called the form will remove all error states from form's inputs.
Closes #5497
=> Allow ngForm to reset form correctly 7.3.x

projects/igniteui-angular/src/lib/directives/input/input.directive.spec.ts, projects/igniteui-angular/src/lib/directives/input/input.directive.ts
With this fix when ngForm.reset() is called the form will remove all error states from form's inputs.
Closes #5497
=> Allow ngForm to reset form correctly 8.1.x

projects/igniteui-angular/src/lib/core/styles/components/slider/_slider-component.scss, projects/igniteui-angular/src/lib/core/styles/components/slider/_slider-theme.scss, projects/igniteui-angular/src/lib/slider/label/thumb-label.component.html, projects/igniteui-angular/src/lib/slider/label/thumb-label.component.ts, projects/igniteui-angular/src/lib/slider/slider.component.html, projects/igniteui-angular/src/lib/slider/slider.component.ts, projects/igniteui-angular/src/lib/slider/thumb/thumb-slider.component.html, projects/igniteui-angular/src/lib/slider/thumb/thumb-slider.component.ts
=> feat(slider): incorrectly positioned label ie11

projects/igniteui-angular/src/lib/core/styles/components/grid/_grid-theme.scss
This will make the z-index of the row drag ghost equal to the one of the grid. This will not fix application scenario where grid is put in stacking container with higher z-index. To fix this drag and drop directive should be able to use outlet where drag ghost should be put in the DOM tree and not as a child of the body.
Closes #5748
=> Set z-index of row drag ghost to 1 same as the grid one

projects/igniteui-angular/src/lib/dialog/dialog.component.spec.ts, projects/igniteui-angular/src/lib/directives/toggle/toggle.directive.spec.ts, projects/igniteui-angular/src/lib/grids/grid/grid-filtering-ui.spec.ts, projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.navigation.spec.ts, projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.spec.ts, projects/igniteui-angular/src/lib/select/select.component.spec.ts, projects/igniteui-angular/src/lib/time-picker/time-picker.component.spec.ts
=> Remove duplicate detectChanges #5810

projects/igniteui-angular/src/lib/core/utils.ts, projects/igniteui-angular/src/lib/grids/cell.component.ts, projects/igniteui-angular/src/lib/grids/grid/cell.spec.ts
Related to changes made in #5462
=> perf(grids): limit cell double tap handler to just iOS

projects/igniteui-angular/src/lib/date-picker/date-picker.component.html, projects/igniteui-angular/src/lib/date-picker/date-picker.component.spec.ts, projects/igniteui-angular/src/lib/date-picker/date-picker.component.ts
=> Add text selection directive for editable input (dropdown mode) scenarios 

projects/igniteui-angular/src/lib/grids/column.component.ts, projects/igniteui-angular/src/lib/grids/grid/column-group.spec.ts
=> Update children collection when add or remove column in column group

projects/igniteui-angular/src/lib/directives/for-of/for_of.directive.ts, projects/igniteui-angular/src/lib/grids/grid/grid.component.spec.ts, src/app/grid-remote-virtualization/grid-remote-virtualization.sample.html, src/app/grid-remote-virtualization/grid-remote-virtualization.sample.ts, src/app/shared/remote.service.ts
=> fix(igxGrid): If set data is null/undefined update views accordingly.

projects/igniteui-angular/src/lib/select/select.component.ts, src/app/select/select.sample.html, src/app/select/select.sample.ts
Remove displayDensity @Input so the component uses the base `DisplayDensityBase` default one.  
Select component now respects a passed DisplayDensityToken.
Add displayDensity sample under dev samples.
Closes #5843
=> Select component now respects a passed DisplayDensityToken and not overriding it.

projects/igniteui-angular/src/lib/directives/drag-drop/drag-drop.directive.ts, projects/igniteui-angular/src/lib/directives/drag-drop/drag-drop.spec.ts
=> Enhance the ghostOffsetX and ghostOffsetY so they can be applied regardless of ghost or not. 

projects/igniteui-angular/src/lib/buttonGroup/buttonGroup.component.ts, projects/igniteui-angular/src/lib/grids/column.component.ts, projects/igniteui-angular/src/lib/grids/grid-base.component.ts, projects/igniteui-angular/src/lib/grids/grid/grid.component.ts
=> docs(*): validating some comments for typedoc export

projects/igniteui-angular/src/lib/core/touch.ts, projects/igniteui-angular/src/lib/core/utils.ts, projects/igniteui-angular/src/lib/grids/cell.component.ts, projects/igniteui-angular/src/lib/grids/grid/cell.spec.ts, projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-cell.component.ts, projects/igniteui-angular/src/lib/grids/tree-grid/tree-cell.component.ts, projects/igniteui-angular/src/lib/navigation-drawer/navigation-drawer.component.spec.ts, projects/igniteui-angular/src/lib/navigation-drawer/navigation-drawer.component.ts
There were some places in `touch.ts` as well as in `IgxNavDrawer` where we were calling browser related things, like `requestAnimationFrame`. Now we are checking if there platform where build runs is browser platform. If not, e.g. server side rendering, we skip calling browsers' methods.
Closes #4426
=> Bypass all calls to browsers' object when not on browser platform

projects/igniteui-angular/src/lib/grids/common/grid.interface.ts, projects/igniteui-angular/src/lib/grids/grid-navigation.service.ts, projects/igniteui-angular/src/lib/grids/grid/groupby-row.component.ts, projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.navigation.spec.ts, projects/igniteui-angular/src/lib/grids/row.component.ts, projects/igniteui-angular/src/lib/grids/summaries/summary-row.component.ts
=> fix(igHierarchicalGrid): Fix navigating down to partially visible cell with index available in previous expanded grid. 

projects/igniteui-angular/src/lib/grids/grid/grid.pagination.spec.ts, projects/igniteui-angular/src/lib/grids/grid/grid.pipes.ts, projects/igniteui-angular/src/lib/test-utils/grid-samples.spec.ts
=> Check if data is undefined in the paging pipe

projects/igniteui-angular/src/lib/core/styles/components/chip/_chip-component.scss, projects/igniteui-angular/src/lib/core/styles/components/chip/_chip-theme.scss
=> fix(chip): Remove CSS "focus-within" since it is NOT supported by IE11 and Edge 18

CHANGELOG.md, projects/igniteui-angular/src/lib/grids/common/grid.interface.ts, projects/igniteui-angular/src/lib/grids/grid-base.component.ts, projects/igniteui-angular/src/lib/grids/grid-mrl-navigation.service.ts, projects/igniteui-angular/src/lib/grids/grid-navigation.service.ts, projects/igniteui-angular/src/lib/grids/grid/grid-cell-selection.spec.ts, projects/igniteui-angular/src/lib/grids/grid/grid-keyBoardNav.spec.ts, projects/igniteui-angular/src/lib/grids/grid/grid-summary.spec.ts, projects/igniteui-angular/src/lib/grids/grid/grid.component.ts, projects/igniteui-angular/src/lib/grids/grid/grid.groupby.spec.ts, projects/igniteui-angular/src/lib/grids/grid/groupby-row.component.ts, projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid-navigation.service.ts, projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.component.ts, projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.integration.spec.ts, projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.navigation.spec.ts, projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.spec.ts, projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.virtualization.spec.ts, projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid-multi-cell-selection.spec.ts, projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid-summaries.spec.ts, projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid.component.ts
=> Exposes verticalScrollContainer.igxForOf in a public method

projects/igniteui-angular/src/lib/grids/grid/grid-summary.spec.ts, projects/igniteui-angular/src/lib/grids/summaries/grid-summary.service.ts, projects/igniteui-angular/src/lib/grids/summaries/grid-summary.ts, projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid-summaries.spec.ts, projects/igniteui-angular/src/lib/test-utils/tree-grid-components.spec.ts, src/app/grid-groupby/grid-groupby.sample.html, src/app/grid-summaries/grid-summaries.sample.html, src/app/grid-summaries/grid-summaries.sample.ts
=> Access all grid data from each summary

CHANGELOG.md
=> docs(*): Add changelog for conditional cell styling

projects/igniteui-angular/package.json, projects/igniteui-angular/schematics/ng-add/index.spec.ts, projects/igniteui-angular/schematics/utils/dependency-handler.ts, projects/igniteui-angular/schematics/utils/package-handler.ts
ng-add schematic definition is being moved [in another packages](https://github.com/IgniteUI/igniteui-cli/pull/569).
Only install `@igniteui/angular-schematics` instead of the whole `cli` on `ng-add`.
Call `@igniteui/angular-schematics:cli-config` on addition (former `igniteui/cli:cli-config`.
Closes #5928
=> refactor(schematics): use @igniteui/angular-schematics on ng-add

projects/igniteui-angular/src/lib/calendar/index.ts
=> fix(calendar): export CalendarView enum

projects/igniteui-angular/src/lib/grids/grid-base.component.ts
=> fix(grid): instantiate observer and tmpOutlets

projects/igniteui-angular/src/lib/grids/api.service.ts, projects/igniteui-angular/src/lib/grids/grid/cell.spec.ts
In `_update_row` method of `GridBaseAPIService` we were committed value over the grid's data. Now we merge the result in new object. This way we do not change the grid's data.
Closes #5779
=> Grid with transactions should not update grid's data when updateRow is called in onCellEdtt

projects/igniteui-angular/src/lib/core/styles/components/progress/_progress-component.scss, projects/igniteui-angular/src/lib/core/styles/components/progress/_progress-theme.scss, projects/igniteui-angular/src/lib/progressbar/circularbar.component.spec.ts, projects/igniteui-angular/src/lib/progressbar/templates/circular-bar.component.html
Change the progress bar to use `*ngIf` instead of `ngClass` as the latter requires a specific polyfill and package in order to work in IE (`classlist.js`).
=> refactor(circular-bar): use *ngIf instead of ngClass in progress bar template - 8.1.x

projects/igniteui-angular/src/lib/core/styles/components/progress/_progress-component.scss, projects/igniteui-angular/src/lib/core/styles/components/progress/_progress-theme.scss, projects/igniteui-angular/src/lib/progressbar/circularbar.component.spec.ts, projects/igniteui-angular/src/lib/progressbar/templates/circular-bar.component.html
Change the progress bar to use `*ngIf` instead of `ngClass` as the latter requires a specific polyfill and package in order to work in IE (`classlist.js`).
=> refactor(circular-bar): use *ngIf instead of ngClass in progress bar template - 8.2.x

projects/igniteui-angular/src/lib/core/styles/components/progress/_progress-component.scss, projects/igniteui-angular/src/lib/core/styles/components/progress/_progress-theme.scss, projects/igniteui-angular/src/lib/progressbar/circularbar.component.spec.ts, projects/igniteui-angular/src/lib/progressbar/templates/circular-bar.component.html
Change the progress bar to use `*ngIf` instead of `ngClass` as the latter requires a specific polyfill and package in order to work in IE (`classlist.js`).
=> refactor(circular-bar): use *ngIf instead of ngClass in progress bar template - 9.0.x

projects/igniteui-angular/schematics/ng-add/index.spec.ts, projects/igniteui-angular/schematics/ng-add/index.ts, projects/igniteui-angular/schematics/utils/dependency-handler.ts
=> fix(schematics): check polyfill in default project #6017

CHANGELOG.md, projects/igniteui-angular/src/lib/grids/common/events.ts, projects/igniteui-angular/src/lib/grids/toolbar/grid-toolbar.component.ts, projects/igniteui-angular/src/lib/services/csv/csv-exporter.ts, projects/igniteui-angular/src/lib/services/excel/excel-exporter.ts, projects/igniteui-angular/src/lib/services/exporter-common/base-export-service.ts, src/app/grid/grid.sample.ts
Closes #6227 
This slipped through the [Angular 9 update](https://github.com/IgniteUI/igniteui-angular/pull/6146). Migrations applied `@Directive` to base classes with any sort of binding and since the `IgxBaseExporter` had emitters decorated with `@Output`, ¯\\_(ツ)_/¯, migrations must've considered it as a component base. Both decorators have been removed.
And since I semi-batch renamed classes with added Directives for lint, I'm rolling back the rename as well. I'll revert docs links if required too.
=> fix(exporter): drop output decorators, revert migration + rename #6227

projects/igniteui-angular/src/lib/directives/radio/radio-group.directive.spec.ts, projects/igniteui-angular/src/lib/directives/radio/radio-group.directive.ts, projects/igniteui-angular/src/lib/radio/radio.component.html, projects/igniteui-angular/src/lib/radio/radio.component.ts, src/app/app.module.ts, src/app/radio/radio.sample.css, src/app/radio/radio.sample.html, src/app/radio/radio.sample.ts
=> fix(igx-radio): Initial selection with falsy values

projects/igniteui-angular/src/lib/services/overlay/overlay.spec.ts, projects/igniteui-angular/src/lib/services/overlay/scroll/block-scroll-strategy.ts
For some reason there was `wheel` event listener in `BlockScrollStrategy`. As we have `scroll` handler I do not think we need the `wheel` one.
However we need to test this thoroughly 
Closes #6226
=> Remove check for wheel listener from block scroll strategy

projects/igniteui-angular/src/lib/services/overlay/overlay.spec.ts, projects/igniteui-angular/src/lib/services/overlay/scroll/block-scroll-strategy.ts
For some reason there was `wheel` event listener in `BlockScrollStrategy`. As we have `scroll` handler I do not think we need the `wheel` one.
However we need to test this thoroughly.
Closes #6226
=> Remove check for wheel listener from block scroll strategy 8.2.x

projects/igniteui-angular/src/lib/core/utils.ts, projects/igniteui-angular/src/lib/slider/slider.component.ts
=> fix(slider): subscribe for resizeObservable cb outside zone

projects/igniteui-angular/src/lib/select/select.component.html, projects/igniteui-angular/src/lib/select/select.component.spec.ts, projects/igniteui-angular/src/lib/select/select.component.ts, src/app/select/select.sample.html, src/app/select/select.sample.ts
=> Select - properly update FormControl touched

projects/igniteui-angular/src/lib/calendar/calendar-helper-utils.ts, projects/igniteui-angular/src/lib/calendar/calendar-multi-view.component.spec.ts, projects/igniteui-angular/src/lib/calendar/calendar.component.spec.ts
=> Refactor Calendar tests

projects/igniteui-angular/src/lib/services/overlay/overlay.spec.ts, projects/igniteui-angular/src/lib/services/overlay/position/auto-position-strategy.ts, projects/igniteui-angular/src/lib/services/overlay/position/base-fit-position-strategy.ts, projects/igniteui-angular/src/lib/services/overlay/position/elastic-position-strategy.ts
We were wrongly calculating the extend of the positioned element according to scrolled view port. With this fix the calculation is made over the view port without including the scrolling.
Closes #6474
=> Position correctly overlay - 8.2.x

projects/igniteui-angular/src/lib/services/overlay/overlay.spec.ts, projects/igniteui-angular/src/lib/services/overlay/position/auto-position-strategy.ts, projects/igniteui-angular/src/lib/services/overlay/position/base-fit-position-strategy.ts, projects/igniteui-angular/src/lib/services/overlay/position/elastic-position-strategy.ts
We were wrongly calculating the extend of the positioned element according to scrolled view port. With this fix the calculation is made over the view port without including the scrolling.
Closes #6474
=> Position correctly overlay - 8.1.x

projects/igniteui-angular/src/lib/tabs/tabs.component.ts
=> fix(ssr): Fix igx-tabs SSR rendering

projects/igniteui-angular/src/lib/navigation-drawer/navigation-drawer.component.spec.ts, projects/igniteui-angular/src/lib/navigation-drawer/navigation-drawer.component.ts
Host binding of the component class is fixed.
Closes #6508
=> Retain classes added through markup in IgxNavDrawer 8.1.x

projects/igniteui-angular/package.json, projects/igniteui-angular/schematics/ng-add/index.spec.ts, projects/igniteui-angular/schematics/utils/dependency-handler.ts
Closes #6646
After beta.7 (ng RC10 update) the newer ng-packager included a change that started [removing `devDependencies` ](https://travis-ci.org/IgniteUI/igniteui-angular/builds/648318135#L358) from the dist package.json. Related to https://github.com/ng-packagr/ng-packagr/pull/1438
Since we used that to carry the version of schematics our `ng-add` would use, moved to a custom meta pror named `igxDevDependencies` instead.
=> fix(ng-add): move schematics version to custom igxDevDependencies #6646

projects/igniteui-angular/src/lib/directives/mask/mask-parsing-service.ts, projects/igniteui-angular/src/lib/directives/mask/mask.directive.ts
Related to https://github.com/IgniteUI/igniteui-angular/issues/6454
=> Turn mask helper to MaskParsingService

projects/igniteui-angular/src/lib/time-picker/time-picker.component.spec.ts, projects/igniteui-angular/src/lib/time-picker/time-picker.component.ts, src/app/time-picker/time-picker.sample.html, src/app/time-picker/time-picker.sample.ts
=> Set displayValue to mask if no value is present

projects/igniteui-angular/src/lib/core/styles/components/drop-down/_drop-down-component.scss, projects/igniteui-angular/src/lib/core/styles/components/drop-down/_drop-down-theme.scss
Set "igx-dropdown" position to absolute in order to force it to be as
big as its content despite its parent element display.
Closes #6733, #6734
=> fix(dropdown): to be as big as its content

projects/igniteui-angular/src/lib/select/select.component.html
Closes #6908  
The input will no longer be focusable. Existing test are available in input-group.directive.spec as well.  The input disabled attribute is checked internally in the input-group and the required styling classes applied as well.
=> fix(select): Move disabled on the Input elem #6908

projects/igniteui-angular/src/lib/grids/grid/grid.component.html, projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.component.html, projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid.component.html
ngIf is applied on content as opposed to the main container used for the overlay target as overlay service cannot detach overlay if target is no longer in DOM (removed as result of ngIf).
Closes #6934
=> fix(igxGrid): Render loading indicator only when needed.

projects/igniteui-angular/src/lib/services/excel/excel-exporter-grid.spec.ts, projects/igniteui-angular/src/lib/services/excel/excel-exporter.ts, projects/igniteui-angular/src/lib/services/excel/excel-files.ts, projects/igniteui-angular/src/lib/services/excel/jszip-verification-wrapper.spec.ts, projects/igniteui-angular/src/lib/services/excel/worksheet-data.ts, projects/igniteui-angular/src/lib/services/exporter-common/base-export-service.ts, projects/igniteui-angular/src/lib/services/exporter-common/test-methods.spec.ts, src/app/grid-row-pinning/grid-row-pinning.sample.html, src/app/grid-row-pinning/grid-row-pinning.sample.ts
=> Row pinning +  export to excel

projects/igniteui-angular/src/lib/grids/filtering/base/grid-filtering-row.component.html, projects/igniteui-angular/src/lib/grids/filtering/base/grid-filtering-row.component.ts, projects/igniteui-angular/src/lib/grids/grid/grid-filtering-ui.spec.ts, projects/igniteui-angular/src/lib/test-utils/grid-functions.spec.ts
=> fix(filter-ui): Fix date filtering and chip commit #6594

CHANGELOG.md, projects/igniteui-angular/migrations/migration-collection.json, projects/igniteui-angular/migrations/update-9_1_0/changes/inputs.json, projects/igniteui-angular/migrations/update-9_1_0/index.spec.ts, projects/igniteui-angular/migrations/update-9_1_0/index.ts, projects/igniteui-angular/src/lib/date-picker/date-picker.component.html, projects/igniteui-angular/src/lib/grids/filtering/advanced-filtering/advanced-filtering-dialog.component.html, projects/igniteui-angular/src/lib/grids/filtering/base/grid-filtering-row.component.html, projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-date-expression.component.html, projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-default-expression.component.html, projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-search.component.html, projects/igniteui-angular/src/lib/input-group/input-group.component.ts, projects/igniteui-angular/src/lib/input-group/input-group.directive.spec.ts, src/app/input-group/input-group.sample.html, src/app/time-picker/time-picker.sample.html
Closes #7032
Renamed `supressInputAutofocus` to `suppressInputAutofocus`.
Deprecate old input.
Update templates.
Add migrations.
Update CHANGELOG.
=> fix(input-group): fix typo in `supressInputAutofocus` input - 9.1.x

projects/igniteui-angular/src/lib/grids/grid-common.module.ts, projects/igniteui-angular/src/lib/grids/grid/grid.module.ts, projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid-integration.spec.ts, projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid-row.component.ts, projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid.component.html, projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid.component.ts, projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid.module.ts, projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid.pipes.ts, src/app/grid-row-pinning/grid-row-pinning.sample.html
Changes include:
- Re-using base grid pinning pipe for tree grid.
- Base grid pinning pipe is now imported in Grid Common module.
- Removed redundant TreeGrid pinning pipes.
- Fix pipe order
- Add a simple pipe that maps the original record to ITreeGridRecord, which is the format the tree grid uses.
- Unify way data context is passed to tree grid row object.
Main difference between base grid and tree grid is that tree grid operates on a special data record type (ITreeGridRecord) hence one additional pipe is added for pinned area that maps the original record to the ITreeGridRecord so that all grid rows can operate on the same data object formats.
=> Refactor tree grid pinning - unify logic between grid and tree grid.

projects/igniteui-angular/src/lib/grids/filtering/base/grid-filtering-row.component.ts, projects/igniteui-angular/src/lib/grids/grid/grid-filtering-ui.spec.ts
Reverts IgniteUI/igniteui-angular#7096
Closes #7159
=> Revert "fix(filtering): Avoid resetting values for number inputs #6973"

projects/igniteui-angular/src/lib/paginator/paginator.component.ts, src/app/app.component.ts, src/app/app.module.ts, src/app/app.routing.ts, src/app/grid-remote-paging/grid-remote-paging.sample.html, src/app/grid-remote-paging/grid-remote-paging.sample.ts, src/app/routing.ts, src/app/shared/remote.service.ts
Closes #7247
Related to #6861
This change contains a fix for showing "0 of n" pages when `totalPages` value is 0. This happens when the remote data is not present in the grid.
=> Pager: Total pages issue "0 of n" on remote paging

projects/igniteui-angular/src/lib/date-range-picker/README.md, projects/igniteui-angular/src/lib/date-range-picker/date-range-picker.component.spec.ts, projects/igniteui-angular/src/lib/date-range-picker/date-range-picker.component.ts
A new @Input `placeholder` is added to `IgxDateRangePicker`. This input allows developer to set `placeholder` for the component when it is in its default read-only single input mode.
Closes #7272
=> Add placeholder to igxDateRangePicker

projects/igniteui-angular/src/lib/directives/for-of/for_of.directive.ts, projects/igniteui-angular/src/lib/grids/grid/grid-filtering-ui.spec.ts
…ht to actual height ration when recalculating vertical offset.
Closes #7234
=> fix(virtualization): Use virtual scroll top which takes virtual heig

projects/igniteui-angular/src/lib/date-range-picker/date-range-picker.component.html
When in flex container the `toggle`, where the calendar is put, gets shrunk. As a result when overlay measures its with it is not correct. To fix this `flex-basis` is added to inline style of the `toggle`.
No test for this as this depends on the screen size and we are planning to move from `toggle` to `igxOverlay` service as soon as possible - when done the issue will gone.
Closes #7354
=> Show correctly calendar in flex container

projects/igniteui-angular/src/lib/date-picker/date-picker.utils.ts, projects/igniteui-angular/src/lib/date-range-picker/date-range-picker.component.spec.ts, projects/igniteui-angular/src/lib/date-range-picker/date-range-picker.component.ts, projects/igniteui-angular/src/lib/directives/date-time-editor/date-time-editor.directive.ts, src/app/date-range/date-range.sample.html, src/app/date-range/date-range.sample.ts
Allow setting of `minValue` and `maxValue` of `IgxDateRantePicker` as stirngs.
Closes #7352
=> fix(date-range): allow mix and min value as string #7352

CHANGELOG.md, projects/igniteui-angular/src/lib/grids/hierarchical-grid/README.md, projects/igniteui-angular/src/lib/grids/hierarchical-grid/child-grid-row.component.ts, projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.integration.spec.ts, projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.spec.ts, projects/igniteui-angular/src/lib/grids/hierarchical-grid/row-island.component.ts
=>  fix(hgrid): Expose onGridInitialized output #6860

projects/igniteui-angular/src/lib/grids/columns/column.component.ts, projects/igniteui-angular/src/lib/grids/grid-base.directive.ts, projects/igniteui-angular/src/lib/grids/grid/column-group.spec.ts
Add handling for moving column groups correctly.
Closes #
=> Calculate insertIndexes based on root level columns only.

projects/igniteui-angular/src/lib/select/select.component.ts
We were calling `notifyOnChanges` packed in a `Promise` in `ngAfterContentInit`. When pinning/unpinning columns in the grid the column containing `igxSelect` could be created and removed several times in order. This leads to very fast creating and destroying of `IgxSelects`. As a result we were calling `notifyOnChanges` after the component was destroyed. Then we subscribe to `changes` and never unsubscribe. This lead to calling `next` on completed subscription. Now we are unsubscribing all subscriptions.
Closes #7006
=> Unsubscribe all subscriptions in IgxSelect, 9.0.x

projects/igniteui-angular/src/lib/date-range-picker/date-range-picker.component.spec.ts, projects/igniteui-angular/src/lib/date-range-picker/date-range-picker.component.ts
=> Update calendar with two filled in inputs - master

projects/igniteui-angular/src/lib/date-picker/date-picker.utils.ts, projects/igniteui-angular/src/lib/date-range-picker/date-range-picker-inputs.common.ts, projects/igniteui-angular/src/lib/date-range-picker/date-range-picker.component.html, projects/igniteui-angular/src/lib/date-range-picker/date-range-picker.component.spec.ts, projects/igniteui-angular/src/lib/date-range-picker/date-range-picker.component.ts, projects/igniteui-angular/src/lib/directives/date-time-editor/date-time-editor.directive.spec.ts, projects/igniteui-angular/src/lib/directives/date-time-editor/date-time-editor.directive.ts, projects/igniteui-angular/src/lib/test-utils/controls-functions.spec.ts
Closes #7477
Authored-by:  Plamena Miteva & Boris Penkov
Some additional enhancements to the `IgxDateRangePickerComponent` are included in this PR:
- The picker will now accumulate all errors and return them as one object during validation.
- Also, in single input mode it will use only `displayFormat` for formatting the input's dates.
- Additionally, the picker's `displayValue` as well as its default `placeholder` (in single input mode) are governed by Angular's `getLocaleDateFormat` and `formatDate`. These two methods can fail if a user has defined a `locale` setting, but has not registered it in their application via the `registerLocaleData` function. In this case the picker will now log warnings and will revert to the browser's locale settings while still adhering to the defined …
=> test(date-range-picker): improve coverage and refactor #5732 (#7647)

projects/igniteui-angular/src/lib/directives/for-of/for_of.directive.spec.ts, projects/igniteui-angular/src/lib/directives/for-of/for_of.directive.ts, projects/igniteui-angular/src/lib/directives/for-of/for_of.sync.service.ts
…IgxForOfDirective. Re-use same instances only when used in a Grid, where a common instance is injected in the Grid itself.
Closes #7698
=> fix(igxGrid): Inject unique instances of the scroll sync service for … 

CHANGELOG.md, projects/igniteui-angular/src/lib/grids/grid-base.directive.ts, projects/igniteui-angular/src/lib/grids/grid/grid-summary.spec.ts, projects/igniteui-angular/src/lib/grids/grid/grid.component.html, projects/igniteui-angular/src/lib/grids/grid/grid.summary.pipe.ts, projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid-summaries.spec.ts, projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid.component.html, projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid.summary.pipe.ts, src/app/grid-groupby/grid-groupby.sample.html, src/app/grid-groupby/grid-groupby.sample.ts, src/app/tree-grid-flat-data/tree-grid-flat-data.sample.html
=> Allow to show/hide summary row when the group/parent row is collapsed

projects/igniteui-angular/src/lib/services/overlay/overlay.ts
Remove `keydown` event listener only when all the overlays were closed.
Closes #7803
=> Correctly close all overlays on escape key

projects/igniteui-angular/src/lib/core/styles/components/drop-down/_drop-down-component.scss, projects/igniteui-angular/src/lib/core/styles/components/drop-down/_drop-down-theme.scss, projects/igniteui-angular/src/lib/drop-down/drop-down.component.html
Closes #7821
Reopens #3977 because there is no way to check content in the dropdown parent container. Autocomplete will handle the problem instead of doing it in the dropdown.
The reverted PR is #7626
=> fix(drop-down): revert fix for bottom shadow #7821 #3977

CHANGELOG.md, projects/igniteui-angular/src/lib/core/styles/components/grid-toolbar/_grid-toolbar-component.scss, projects/igniteui-angular/src/lib/core/styles/components/grid-toolbar/_grid-toolbar-theme.scss, projects/igniteui-angular/src/lib/grids/toolbar/grid-toolbar.component.html, projects/igniteui-angular/src/lib/grids/toolbar/grid-toolbar.component.ts, projects/igniteui-angular/src/lib/services/exporter-common/base-export-service.ts, src/styles/igniteui-theme.scss
=> feat(grid): added export progress visualization in toolbar

projects/igniteui-angular/src/lib/core/styles/components/input/_input-group-theme.scss, src/app/input-group/input-group.sample.html
The prefix/suffix will not render correctly if set as attribute on igx-icon.
=> fix(input-group): prefix/suffix not rendered correctly

CHANGELOG.md, projects/igniteui-angular/src/lib/time-picker/README.md
=> feat(time-picker): Updating the readme and the changelog, #6905

projects/igniteui-angular/src/lib/combo/combo.component.html, projects/igniteui-angular/src/lib/combo/combo.component.spec.ts, projects/igniteui-angular/src/lib/combo/combo.component.ts, src/app/combo/combo.sample.html, src/app/combo/combo.sample.ts
=> Combo model validation fixes 9.1

projects/igniteui-angular/src/lib/directives/toggle/toggle.directive.ts, projects/igniteui-angular/src/lib/grids/grid-base.directive.ts, projects/igniteui-angular/src/lib/grids/grid.common.ts
=> refactor(grid): do not hide editing row on scroll

projects/igniteui-angular/src/lib/time-picker/time-picker.component.html, projects/igniteui-angular/src/lib/time-picker/time-picker.component.spec.ts, projects/igniteui-angular/src/lib/time-picker/time-picker.component.ts
=> Set mask to TimePicker's editor on clear - 9.1.x

projects/igniteui-angular/src/lib/time-picker/time-picker.component.html, projects/igniteui-angular/src/lib/time-picker/time-picker.component.spec.ts, projects/igniteui-angular/src/lib/time-picker/time-picker.component.ts
=> Set mask to TimePicker's editor on clear - 10.1.x

CHANGELOG.md, projects/igniteui-angular/src/lib/expansion-panel/README.md, projects/igniteui-angular/src/lib/expansion-panel/expansion-panel-header.component.ts, projects/igniteui-angular/src/lib/expansion-panel/expansion-panel.common.ts, projects/igniteui-angular/src/lib/expansion-panel/expansion-panel.component.ts, projects/igniteui-angular/src/lib/expansion-panel/expansion-panel.directives.ts, projects/igniteui-angular/src/lib/expansion-panel/expansion-panel.spec.ts, src/app/expansion-panel/expansion-panel-sample.html, src/app/expansion-panel/expansion-panel-sample.ts
Closes #8190 
Make `onInteraction` event cancelable
=> fix(expansion-panel): make header interaction cancelable - master

CHANGELOG.md, projects/igniteui-angular/src/lib/date-range-picker/date-range-picker.component.spec.ts, projects/igniteui-angular/src/lib/date-range-picker/date-range-picker.component.ts, projects/igniteui-angular/src/lib/directives/toggle/README.md, projects/igniteui-angular/src/lib/directives/toggle/toggle.directive.spec.ts, projects/igniteui-angular/src/lib/directives/toggle/toggle.directive.ts
`onOpened` and `onClosed` events will now emit the overlay `id` and owner. In addition to this `onClosing` and `onOpening` will emit and `cancel`.
Closes #8225
=> Toggle should emit correct event arguments

projects/igniteui-angular/src/lib/services/overlay/overlay.spec.ts, projects/igniteui-angular/src/lib/services/overlay/overlay.ts
Before we add listener to the document we are checking now if we are under iOS. If so we change the cursor to `pointer`. This forces the document body to handle click events.
Closes #5853
=> Change cursor in iOS - 10.1.x

projects/igniteui-angular/src/lib/services/overlay/overlay.spec.ts, projects/igniteui-angular/src/lib/services/overlay/overlay.ts
Before we add listener to the document we are checking now if we are under iOS. If so we change the cursor to `pointer`. This forces the document body to handle click events.
Closes #5853
=> Change cursor on iOS - 9.1.x

projects/igniteui-angular/migrations/common/tsUtils.ts, projects/igniteui-angular/migrations/update-10_2_0/changes/members.json, projects/igniteui-angular/migrations/update-10_2_0/index.spec.ts
=> fix(expansion-panel): add migration for deprecated `panel` property in IExpansionPanelEventArgs

projects/igniteui-angular/src/lib/grids/grid/grid-cell-editing.spec.ts, projects/igniteui-angular/src/lib/grids/selection/selection.service.ts
Related #4135
From [this reply](https://github.com/IgniteUI/igniteui-angular/issues/4135#issuecomment-704717291) when preventing `cellEdit` on enter/f2 the cell looses focus (transferred to the grid body) and you have to click again, which is not ideal for KB scenarios. Works works well for outside clicks and tabs after events refactor for #7931, so this brings all in line.
=> fix(grid): keep input focus on canceled edit w/ enter #4135

projects/igniteui-angular/src/lib/combo/combo.component.ts, projects/igniteui-angular/src/lib/date-picker/date-picker.component.ts, projects/igniteui-angular/src/lib/date-range-picker/date-range-picker.module.ts, projects/igniteui-angular/src/lib/select/select.module.ts, projects/igniteui-angular/src/lib/time-picker/time-picker.component.ts
Closes #8586  
Export igxInputGroupModule for igxDatePicker, igxTimePicker, igxDateRangePicker, igxSelect & igxCombo. This will remove the need to import igxInputGroupModule in an application with one of the components above and will allow to project label and other components and will allow templating.
=> fix(date-picker, time-picker): export input group module

projects/igniteui-angular/src/lib/grids/grid-navigation.service.ts, projects/igniteui-angular/src/lib/grids/grid/grid-summary.spec.ts
=> Fix: When summary position is top Ctrl+Home or Ctrl+Arrow up selects the summary cell --9.1.

projects/igniteui-angular/src/lib/services/overlay/overlay.spec.ts, projects/igniteui-angular/src/lib/services/overlay/overlay.ts
When component with encapsulation set to ShadowDom tried to show overlay in an outlet, clicking on 
When clicking on overlay content in overlay with `closeOnOutsideClick` set to true overlay should not close. However, when content is shown in outlet in component with ShadowDom encapsulation the target of click event comes as the component. To fix this and get the actual target we are now getting `composedPath` and its first child.
Closes #8626
=> Close on outside click when in shadow DOM - 10.2.x

projects/igniteui-angular/src/lib/services/overlay/overlay.spec.ts, projects/igniteui-angular/src/lib/services/overlay/overlay.ts
When component with encapsulation set to ShadowDom tried to show overlay in an outlet, clicking on 
When clicking on overlay content in overlay with `closeOnOutsideClick` set to true overlay should not close. However, when content is shown in outlet in component with ShadowDom encapsulation the target of click event comes as the component. To fix this and get the actual target we are now getting `composedPath` and its first child.
Closes #8626
=> Close on outside click when in shadow DOM - 9.1

projects/igniteui-angular/src/lib/select/select-navigation.directive.ts, projects/igniteui-angular/src/lib/select/select.component.spec.ts
Closes #8436   
- Make the component feel more responsive now as if no exact match is found for the current input stream, a next item with the same start letter will be selected (if such an item).
- Behave more like a native HTML select in terms of fast searching through items by 1st character, and yet do not suffer from the negative downside of not matching same second character if holding down or typing fast same char. Native select basically ignores selecting items via the current input stream while the same char is continuously typed as it seems to prioritize fast items iteration by first char instead.
=> Handle keydown and iterate items by first character, if no item matched typed input - master

projects/igniteui-angular/migrations/common/ServerHost.ts, projects/igniteui-angular/migrations/common/UpdateChanges.ts, projects/igniteui-angular/migrations/common/tsUtils.ts, projects/igniteui-angular/migrations/common/util.ts, projects/igniteui-angular/migrations/update-11_1_0/index.ts
This prevents our check from caching the package json result
which will prevent the package from loading correctly after install
Closes #8254
=> fix(migrations): resolve package for checks in seperate process #8254

projects/igniteui-angular/src/lib/services/overlay/overlay.spec.ts, projects/igniteui-angular/src/lib/services/overlay/overlay.ts
=> fix(overlay): remove escape keydown listener when outlet is used, #9115

projects/igniteui-angular/src/lib/grids/cell.component.html, projects/igniteui-angular/src/lib/grids/grid/grid-cell-editing.spec.ts
After the initial change detection when 'swapping' the
current cell template, change detection is skipped which
results in the `checked` getter never being called again
after binding from the `ngModel`.
Additional binding to the `checked` property properly
triggers the getter and applying the style class.
Closes #9223
=> fix(grid): invalid checkbox state in edit mode

projects/igniteui-angular/migrations/common/UpdateChanges.spec.ts, projects/igniteui-angular/migrations/common/tsUtils.ts
=> fix(migrations): resolve property type from definition file path first

projects/igniteui-angular/src/lib/date-common/util/date-time.util.spec.ts, projects/igniteui-angular/src/lib/date-common/util/date-time.util.ts, projects/igniteui-angular/src/lib/directives/date-time-editor/date-time-editor.directive.spec.ts, projects/igniteui-angular/src/lib/directives/date-time-editor/date-time-editor.directive.ts
The problem was with the `IgxDateTimeEditorDirective` which did not update its placeholder when an `inputFormat` was provided. So the issue was reproducible in all components that used the directive.
Closes #9409
=> DateTimeEditor sets placeholder properly

projects/igniteui-angular/migrations/update-12_0_0/index.spec.ts, projects/igniteui-angular/migrations/update-12_0_0/index.ts
Migration for `igx-input-group` `disabled` property was only moving the property to `input` children. it now moves it to `textarea` as well.
=> fix(migrations): move disabled property to textarea, #9339

projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.component.html, projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid.component.html
Closes #9549 
Expose proper bound context in tree grid and hierarchical grid's row template (similar to base grid)
=> fix(grid): bind to grid's API in row edit template, #9549

projects/igniteui-angular/src/lib/core/styles/components/expansion-panel/_expansion-panel-theme.scss, projects/igniteui-angular/src/lib/expansion-panel/expansion-panel-header.component.ts, projects/igniteui-angular/src/lib/expansion-panel/expansion-panel.spec.ts
Closes #9696
header.disabled was incorrectly setting `tabIndex === -1`, which still allows elements to be focused via mouse click.
No tab index makes the element non-focusable and `pointer-events: none` style prevents flickering.
=> fix(expansion-panel): disabled panel header is not focusable w/ click - 10.2.x

projects/igniteui-angular/src/lib/core/styles/components/expansion-panel/_expansion-panel-theme.scss, projects/igniteui-angular/src/lib/expansion-panel/expansion-panel-header.component.ts, projects/igniteui-angular/src/lib/expansion-panel/expansion-panel.spec.ts
Closes #9696
header.disabled was incorrectly setting `tabIndex === -1`, which still allows elements to be focused via mouse click.
No tab index makes the element non-focusable and `pointer-events: none` style prevents flickering.
=> fix(expansion-panel): disabled panel header is not focusable w/ click - 11.1.x

projects/igniteui-angular/src/lib/core/styles/components/expansion-panel/_expansion-panel-theme.scss, projects/igniteui-angular/src/lib/expansion-panel/expansion-panel-header.component.ts, projects/igniteui-angular/src/lib/expansion-panel/expansion-panel.spec.ts
Closes #9696
header.disabled was incorrectly setting `tabIndex === -1`, which still allows elements to be focused via mouse click.
No tab index makes the element non-focusable and `pointer-events: none` style prevents flickering.
=> fix(expansion-panel): disabled panel header is not focusable w/ click - 12.0.x

projects/igniteui-angular/src/lib/core/styles/components/expansion-panel/_expansion-panel-theme.scss, projects/igniteui-angular/src/lib/expansion-panel/expansion-panel-header.component.ts, projects/igniteui-angular/src/lib/expansion-panel/expansion-panel.spec.ts
Closes #9696
header.disabled was incorrectly setting `tabIndex === -1`, which still allows elements to be focused via mouse click.
No tab index makes the element non-focusable and `pointer-events: none` style prevents flickering.
=> fix(expansion-panel): disabled panel header is not focusable w/ click - master

projects/igniteui-angular/src/lib/expansion-panel/expansion-panel.spec.ts, projects/igniteui-angular/src/lib/expansion-panel/toggle-animation-component.spec.ts, projects/igniteui-angular/src/lib/expansion-panel/toggle-animation-component.ts
Closes #9783 
Setting `animationSettings = null` will be handled the same as `animationSettings = { openAnimation: null, closeAnimation: null }`.
Toggling the panel w/ `animationSettings === null` will expand / collapse it instantly, w/o animating.
=> fix(expansion-panel): handle null animation settings - 12.0.x

projects/igniteui-angular/src/lib/expansion-panel/expansion-panel.component.ts, projects/igniteui-angular/src/lib/expansion-panel/expansion-panel.spec.ts
Closes #9783
Setting `animationSettings = null` will be handled the same as `animationSettings = { openAnimation: null, closeAnimation: null }`.
Toggling the panel w/ `animationSettings === null` will expand / collapse it instantly, w/o animating.
=> fix(expansion-panel): handle null animation settings - 11.1.x

projects/igniteui-angular/src/lib/expansion-panel/expansion-panel.component.ts, projects/igniteui-angular/src/lib/expansion-panel/expansion-panel.spec.ts
Closes #9783
Setting `animationSettings = null` will be handled the same as `animationSettings = { openAnimation: null, closeAnimation: null }`.
Toggling the panel w/ `animationSettings === null` will expand / collapse it instantly, w/o animating.
=> fix(expansion-panel): handle null animation settings - 10.2.x

projects/igniteui-angular/src/lib/list/list-item.component.ts, projects/igniteui-angular/src/lib/list/list.component.spec.ts
=> fix(list): reset pan state and list item position on pancancel event - 10.2.x

projects/igniteui-angular/src/lib/list/list-item.component.ts, projects/igniteui-angular/src/lib/list/list.component.spec.ts
=> fix(list): reset pan state and list item position on pancancel event - 11.1.x

projects/igniteui-angular/src/lib/list/list-item.component.ts, projects/igniteui-angular/src/lib/list/list.component.spec.ts
=> fix(list): reset pan state and list item position on pancancel event - 12.0.x

CHANGELOG.md, projects/igniteui-angular/src/lib/grids/cell.component.ts, projects/igniteui-angular/src/lib/grids/columns/column.component.ts, projects/igniteui-angular/src/lib/grids/common/column.interface.ts, projects/igniteui-angular/src/lib/grids/grid/column.spec.ts
=> feat(grid): expose column input for template context

projects/igniteui-angular/src/lib/core/utils.ts, projects/igniteui-angular/src/lib/grids/grid-base.directive.ts, projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid-base.directive.ts, projects/igniteui-angular/src/lib/grids/hierarchical-grid/row-island.component.ts, projects/igniteui-angular/src/lib/grids/selection/selection.service.ts
…hole grid container in FF causes scrollbar to jump.
Closes #9705
=> Fix scrollbar jump in FireFox when grid needs to autosize (100% height of container that has no size).

projects/igniteui-angular/src/lib/services/overlay/overlay.spec.ts
Calling `click` over an element used to be called with `mouseEvent`, but now is called with `pointerEvent`.
Closes #9948
=> Fix failing tests

projects/igniteui-angular/src/lib/grids/grid/grid-keyBoardNav.spec.ts, projects/igniteui-angular/src/lib/grids/grid/grid-row-selection.spec.ts, projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid-selection.spec.ts, projects/igniteui-angular/src/lib/services/overlay/overlay.spec.ts, projects/igniteui-angular/src/lib/test-utils/grid-samples.spec.ts, projects/igniteui-angular/src/lib/test-utils/tree-grid-components.spec.ts
Calling `click` over an element used to be called with `mouseEvent`, but now is called with `pointerEvent`.
Closes #9948
=> Fix failing tests - v10.2

projects/igniteui-angular/src/lib/grids/grid/grid-keyBoardNav.spec.ts, projects/igniteui-angular/src/lib/grids/grid/grid-row-selection.spec.ts, projects/igniteui-angular/src/lib/grids/grid/grid.groupby.spec.ts, projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid-selection.spec.ts, projects/igniteui-angular/src/lib/services/overlay/overlay.spec.ts, projects/igniteui-angular/src/lib/test-utils/grid-samples.spec.ts, projects/igniteui-angular/src/lib/test-utils/tree-grid-components.spec.ts
Calling `click` over an element used to be called with `mouseEvent`, but now is called with `pointerEvent`.
Closes #9948
=> Fix failing tests - v12.0

projects/igniteui-angular/src/lib/grids/grid/grid-keyBoardNav.spec.ts, projects/igniteui-angular/src/lib/grids/grid/grid-row-selection.spec.ts, projects/igniteui-angular/src/lib/grids/grid/grid.groupby.spec.ts, projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid-selection.spec.ts, projects/igniteui-angular/src/lib/services/overlay/overlay.spec.ts, projects/igniteui-angular/src/lib/test-utils/grid-samples.spec.ts, projects/igniteui-angular/src/lib/test-utils/tree-grid-components.spec.ts
Calling `click` over an element used to be called with `mouseEvent`, but now is called with `pointerEvent`.
Closes #9948
=> Fix failing tests - v11.1

projects/igniteui-angular/src/lib/core/styles/components/grid/_grid-theme.scss
Closes #9931 
Notes:
1. I target `igx-input-group__bundle` class directly on purpose. Using the placeholder selector will affect the output CSS selector's length.
2. The !important flags make sense here since selectors like `igx-prefix, igx-input-group__bundle` are used in a lot of combinations that may increase or decrease in the future, we don't want to go back and add new selector combinations here.
=> Fix row jumping in edit mode

projects/igniteui-angular/migrations/common/UpdateChanges.ts, projects/igniteui-angular/migrations/common/tsUtils.ts, projects/igniteui-angular/migrations/update-11_1_0/changes/members.json, projects/igniteui-angular/migrations/update-11_1_0/index.spec.ts, projects/igniteui-angular/migrations/update-11_1_0/index.ts
Related #9927 
Changes to TsServerHost and handling of ngLS introduced in [this PR](https://github.com/IgniteUI/igniteui-angular/pull/9610) force `UpdateChange.getLanguageServiceForFile()` to work only with absolute paths. This breaks the migration for `GridPagingMode` in `11.1.x` (which uses relative paths).
That migration is now moved to the `members.json` (as IvyLS enables it to work).
=> fix(migrations): migrate GridPagingMode via members.json

CHANGELOG.md, projects/igniteui-angular/src/lib/grids/cell.component.html, projects/igniteui-angular/src/lib/grids/cell.component.ts, projects/igniteui-angular/src/lib/grids/columns/column.component.ts, projects/igniteui-angular/src/lib/grids/common/pipes.ts, projects/igniteui-angular/src/lib/grids/filtering/advanced-filtering/advanced-filtering-dialog.component.html, projects/igniteui-angular/src/lib/grids/filtering/excel-style/grid.excel-style-filtering.component.ts, projects/igniteui-angular/src/lib/grids/filtering/grid-filtering.service.ts, projects/igniteui-angular/src/lib/grids/grid-base.directive.ts, projects/igniteui-angular/src/lib/grids/grid/column.spec.ts, projects/igniteui-angular/src/lib/grids/grid/expandable-cell.component.html, projects/igniteui-angular/src/lib/grids/grid/grid-filtering-ui.spec.ts, projects/igniteui-angular/src/lib/grids/tree-grid/tree-cell.component.html, projects/igniteui-angular/src/lib/test-utils/grid-samples.spec.ts
=> feat(grid): Provide row data as argument to column formatter

projects/igniteui-angular/src/lib/directives/notification/notifications.directive.ts, projects/igniteui-angular/src/lib/snackbar/snackbar.component.spec.ts, projects/igniteui-angular/src/lib/snackbar/snackbar.component.ts, projects/igniteui-angular/src/lib/toast/toast.component.spec.ts, projects/igniteui-angular/src/lib/toast/toast.component.ts, src/app/snackbar/snackbar.sample.html, src/app/snackbar/snackbar.sample.ts
=> feat(snackbar): Add input for custom position strategy#10126 - 12.1.x

projects/igniteui-angular/src/lib/data-operations/data-util.spec.ts, projects/igniteui-angular/src/lib/grids/cell.component.html, projects/igniteui-angular/src/lib/grids/grid/column.spec.ts, projects/igniteui-angular/src/lib/grids/grid/expandable-cell.component.html, projects/igniteui-angular/src/lib/grids/tree-grid/tree-cell.component.html, projects/igniteui-angular/src/lib/test-utils/grid-samples.spec.ts, projects/igniteui-angular/src/lib/test-utils/sample-test-data.spec.ts, projects/igniteui-angular/src/lib/test-utils/template-strings.spec.ts, src/app/grid-formatting/grid-formatting.component.html
=> fix(grid): use formattter function for boolean columns #8978

projects/igniteui-angular/src/lib/core/styles/components/navbar/_navbar-theme.scss
=> Use flex display for navbar title content

projects/igniteui-angular/src/lib/grids/common/events.ts, projects/igniteui-angular/src/lib/grids/grid-base.directive.ts, projects/igniteui-angular/src/lib/grids/grid/grid-row-pinning.spec.ts, projects/igniteui-angular/src/lib/grids/row.directive.ts
=> V dyulgerov/cancel pinning unpinning row 11.1.x

projects/igniteui-angular/src/lib/stepper/stepper.common.ts
=> IgxStepper string enums

CHANGELOG.md, projects/igniteui-angular/src/lib/toast/toast.component.spec.ts, projects/igniteui-angular/src/lib/toast/toast.component.ts
=> fix(toast): Adding checks for position settings #10305 - 12.2.x

CHANGELOG.md
=> Update changelog with deprecation in Toast

projects/igniteui-angular-i18n/src/i18n/BG/action-strip-resources.ts, projects/igniteui-angular-i18n/src/i18n/CS/action-strip-resources.ts, projects/igniteui-angular-i18n/src/i18n/DA/action-strip-resources.ts, projects/igniteui-angular-i18n/src/i18n/DE/action-strip-resources.ts, projects/igniteui-angular-i18n/src/i18n/ES/action-strip-resources.ts, projects/igniteui-angular-i18n/src/i18n/FR/action-strip-resources.ts, projects/igniteui-angular-i18n/src/i18n/HU/action-strip-resources.ts, projects/igniteui-angular-i18n/src/i18n/IT/action-strip-resources.ts, projects/igniteui-angular-i18n/src/i18n/JA/action-strip-resources.ts, projects/igniteui-angular-i18n/src/i18n/KO/action-strip-resources.ts, projects/igniteui-angular-i18n/src/i18n/NB/action-strip-resources.ts, projects/igniteui-angular-i18n/src/i18n/NL/action-strip-resources.ts, projects/igniteui-angular-i18n/src/i18n/PL/action-strip-resources.ts, projects/igniteui-angular-i18n/src/i18n/PT/action-strip-resources.ts, projects/igniteui-angular-i18n/src/i18n/RO/action-strip-resources.ts, projects/igniteui-angular-i18n/src/i18n/SV/action-strip-resources.ts, projects/igniteui-angular-i18n/src/i18n/TR/action-strip-resources.ts, projects/igniteui-angular-i18n/src/i18n/ZH-HANS/action-strip-resources.ts, projects/igniteui-angular-i18n/src/i18n/ZH-HANT/action-strip-resources.ts, projects/igniteui-angular/src/lib/action-strip/action-strip.component.html, projects/igniteui-angular/src/lib/action-strip/action-strip.component.ts, projects/igniteui-angular/src/lib/action-strip/grid-actions/grid-action-button.component.html, projects/igniteui-angular/src/lib/action-strip/grid-actions/grid-editing-actions.component.ts, projects/igniteui-angular/src/lib/action-strip/grid-actions/grid-pinning-actions.component.ts, projects/igniteui-angular/src/lib/core/i18n/action-strip-resources.ts, projects/igniteui-angular/src/lib/core/i18n/resources.ts, projects/igniteui-angular/src/public_api.ts
=> feat(action-strip): titles and localization for buttons in action strip - master

projects/igniteui-angular/src/lib/simple-combo/simple-combo.component.ts
=> Combo clean up

CHANGELOG.md, projects/igniteui-angular/migrations/update-13_0_0/changes/members.json, projects/igniteui-angular/migrations/update-13_0_0/changes/outputs.json, projects/igniteui-angular/src/lib/grids/README.md, projects/igniteui-angular/src/lib/grids/common/events.ts, projects/igniteui-angular/src/lib/grids/grid-base.directive.ts, projects/igniteui-angular/src/lib/grids/grid/grid-row-selection.spec.ts, projects/igniteui-angular/src/lib/grids/grid/grid.groupby.spec.ts, projects/igniteui-angular/src/lib/grids/grid/groupby-row.component.ts, projects/igniteui-angular/src/lib/grids/hierarchical-grid/child-grid-row.component.ts, projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.selection.spec.ts, projects/igniteui-angular/src/lib/grids/row.directive.ts, projects/igniteui-angular/src/lib/grids/selection/selection.service.ts, projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid-selection.service.ts, projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid-selection.spec.ts, projects/igniteui-angular/src/lib/test-utils/grid-interfaces.spec.ts, projects/igniteui-angular/src/lib/test-utils/grid-samples.spec.ts, projects/igniteui-angular/src/lib/test-utils/template-strings.spec.ts, src/app/grid-groupby/grid-groupby.sample.html, src/app/grid-groupby/grid-groupby.sample.ts, src/app/grid-selection/grid-selection.sample.html, src/app/grid-updates-test/grid-updates.component.html, src/app/splitter/splitter.sample.html
Closes #9250 
Related to changes in PR #10088; see after screenshot - the bulk of the remaining slow down was caused by the Group selector click handler spamming single selects with event emits for each. Per this https://github.com/IgniteUI/igniteui-angular/issues/9405#issuecomment-881270263, with 30k-ish records in the group selection took a good 20s+ due to that.
Refactored two methods that do essentially the same as the single ones but in bulk and now the selection emits once but is also now decently quick. For comparison w/ the previous PR scenario:
Further, with 30k rows the click handler is in the 115ms range and acceptable 300ms for 100k rows (local dev run w/ profiler running), so it scales more or less linearly. Also being finally profile at higher count, the previously fixed …
=> GroupBy row select emit event once, perf

projects/igniteui-angular/src/lib/accordion/accordion.component.spec.ts, projects/igniteui-angular/src/lib/accordion/accordion.component.ts
=> expand only one panel when SingleBranchExpand is set to true

projects/igniteui-angular/migrations/update-13_0_0/changes/members.json, projects/igniteui-angular/migrations/update-13_0_0/index.spec.ts, projects/igniteui-angular/package.json
Closes https://github.com/IgniteUI/igniteui-angular/issues/10456
=> Adding migrations for rowData and rowID

src/app/grid-column-selection/grid-column-selection.sample.ts, src/app/grid/grid.sample.ts
Closes #10525
This PR fix bug in Grid sample for deleting row and expression error for grid column selection.
=> fix(grid): update delete row function

projects/igniteui-angular/src/lib/core/styles/components/navdrawer/_navdrawer-theme.scss
=> fix(navdrawer): add transparency to background color

CHANGELOG.md, projects/igniteui-angular/src/lib/grids/common/grid.interface.ts, projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-moving.component.ts, projects/igniteui-angular/src/lib/grids/grid-navigation.service.ts, src/app/shared/financialData.ts
Closes (https://github.com/IgniteUI/igniteui-angular/issues/10534)
=> remove toggle from RowType interface, fix FinJsDemo

projects/igniteui-angular/src/lib/grids/toolbar/grid-toolbar.component.ts
=> fix(toolbar): Provide token correctly in DI

projects/igniteui-angular/src/lib/grids/toolbar/grid-toolbar.base.ts
Closes https://github.com/IgniteUI/igniteui-angular/issues/10589
=> fix(grid): set ConnectedPosotionStrategy for toolbar actions

projects/igniteui-angular/src/lib/data-operations/pivot-strategy.ts, projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-grid.pipes.spec.ts, projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-grid.pipes.ts, src/app/pivot-grid/pivot-grid.sample.ts
Closes #10609
Closes #10610  
Previously the column pipe was removing these, but the column pipe just applies aggregations now, so moving that logic to the last pipe (expand/collapse pipe).
=> Remove unnecessary leaf records from pivot data.

projects/igniteui-angular/src/lib/services/overlay/overlay.spec.ts
Fix overlay's block scroll strategy test that didn't setup the test bed correctly and didn't dispatch the event on the correct target
Also properly detach to clear active strategies and dispatch scroll consistently (except for close strategy)
=> test(overlay): fix block strategy tests

projects/igniteui-angular/src/lib/combo/combo-item.component.html, projects/igniteui-angular/src/lib/combo/combo.component.spec.ts
Closes #10838
Putting the `[readonly]=true` is needed because of the following change, where _onCheckboxClick is decorated with HostListener for the click: https://github.com/IgniteUI/igniteui-angular/commit/735619c2eace36bc98c5bfea76e03724896efa96
Other related PR: https://github.com/IgniteUI/igniteui-angular/commit/e784abf15c760075d225733d098d14a1d4276d56
=> fix(combo): disable UI click for checkbox in combo #10838

projects/igniteui-angular/src/lib/core/styles/components/grid/_grid-theme.scss
=> fix(grid): column headers background has transparency on drag.

.github/workflows/nodejs.yml, gulpfile.js, tsconfig.json, tsconfig.typedoc.json
=> fix(typedoc): adding to excluded paths

projects/igniteui-angular/src/lib/data-operations/filtering-expressions-tree.ts, projects/igniteui-angular/src/lib/grids/filtering/grid-filtering.service.ts, projects/igniteui-angular/src/lib/grids/grid/grid-filtering-ui.spec.ts
=> fix(filtering): fix empty expr error

projects/igniteui-angular/src/lib/core/styles/components/input/_input-group-component.scss, projects/igniteui-angular/src/lib/core/styles/components/input/_input-group-theme.scss, projects/igniteui-angular/src/lib/core/styles/themes/schemas/light/_input-group.scss
=> fix:(input-group) fluent theme styles

projects/igniteui-angular/src/lib/services/overlay/overlay.spec.ts, projects/igniteui-angular/src/lib/services/overlay/overlay.ts, src/app/overlay/overlay.sample.html, src/app/overlay/overlay.sample.ts
We should add modal classes when there is no open animation and remove them when there is no close animation.
Closes #10944
=> Fix overlay modal wrapper without animations - 12.3.x

projects/igniteui-angular/src/lib/simple-combo/simple-combo.component.spec.ts, projects/igniteui-angular/src/lib/simple-combo/simple-combo.component.ts
=> Simple combo retains selection on blur

projects/igniteui-angular/src/lib/grids/columns/column.component.ts, projects/igniteui-angular/src/lib/grids/grid/grid.component.ts, projects/igniteui-angular/src/lib/grids/grid/grid.pagination.spec.ts
=> fix(grid): fix row indexes in remote virtualization scenario -  master

projects/igniteui-angular/src/lib/core/styles/components/switch/_switch-theme.scss, projects/igniteui-angular/src/lib/core/styles/themes/schemas/dark/_switch.scss, projects/igniteui-angular/src/lib/core/styles/themes/schemas/light/_switch.scss
=> Update Switch Styles

projects/igniteui-angular/src/lib/grids/toolbar/grid-toolbar.base.ts
=> fix(grid): put actions as parameter

projects/igniteui-angular/src/lib/data-operations/pivot-strategy.ts, projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-grid.component.ts, projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-grid.spec.ts
=> Implement excel-style tree view in pivot grid.

projects/igniteui-angular/src/lib/grids/cell.component.ts, projects/igniteui-angular/src/lib/grids/common/crud.service.ts
=> fix(grid): add addtional check for cellID

projects/igniteui-angular/src/lib/core/styles/components/radio/_radio-theme.scss, projects/igniteui-angular/src/lib/core/styles/themes/schemas/dark/_radio.scss, projects/igniteui-angular/src/lib/core/styles/themes/schemas/light/_radio.scss, projects/igniteui-angular/src/lib/core/styles/themes/schemas/light/_switch.scss
=> style(switch/radio): update switch/radio in fluent theme

projects/igniteui-angular/src/lib/core/styles/components/checkbox/_checkbox-theme.scss, projects/igniteui-angular/src/lib/core/styles/themes/schemas/light/_checkbox.scss
=> style(material): change indeterminate disabled checkbox color

projects/igniteui-angular/src/lib/directives/for-of/for_of.directive.ts, projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-grid.component.html, projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-header-row.component.ts
- use offsetHeight vs clientHeight to prevent style reflows
-  disable variable row height for pivot rows since they are always the same size.
Closes #
=> PivotGrid Minor performance improvements 

projects/igniteui-angular/src/lib/core/styles/themes/schemas/light/_button.scss
=> Fix color inconsistency between wc and angular bootstrap themes

projects/igniteui-angular/src/lib/grids/grid-base.directive.ts, projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid.component.ts
=> fix(igxGrid): Minor fix and refactor for row adding APIs.

projects/igniteui-angular/src/lib/core/styles/base/elevations/_index.scss, projects/igniteui-angular/src/lib/core/styles/themes/_index.scss
=> feat(elevations): add elevation factor css variable

projects/igniteui-angular/src/lib/grids/grid/column-group.spec.ts, projects/igniteui-angular/src/lib/grids/grid/grid.component.ts, projects/igniteui-angular/src/lib/grids/grouping/group-by-area.directive.ts, projects/igniteui-angular/src/lib/test-utils/grid-mch-sample.spec.ts
=> fix(grid): Fix errors thrown when grid is grouped by a column that isn't defined - 13.1.x

projects/igniteui-angular/src/lib/data-operations/filtering-condition.ts, projects/igniteui-angular/src/lib/grids/grid/grid-filtering.spec.ts
=> fix(grid): fixed dateTime filtering - 13.1.x

projects/igniteui-angular/src/lib/grids/common/grid.interface.ts, projects/igniteui-angular/src/lib/grids/grid-base.directive.ts, projects/igniteui-angular/src/lib/grids/state.directive.ts, src/app/grid-master-detail/grid-master-detail.sample.html, src/app/grid-master-detail/grid-master-detail.sample.ts
Note: This is a workaround. It would be best for grid features (like moving and state directive) to not modify collections that are bound to angular's templates as they are changed any time a structural directive like ngIf, ngFor etc. is resolved in any internal template. Hence depending on such a collection to retain state is not ideal.
Closes #11298
=> Workaround for grid features that directly modify the columnsList ContentChildren collection.

projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-data-selector.component.ts, projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-grid.component.ts, projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-grid.spec.ts
=> Fix issues with runtime `pivotConfiguration` changes.

gulpfile.js
=> fix(cd): resolving an issue with typedoc erros being swallowed - 13.1

projects/igniteui-angular/src/lib/core/styles/components/action-strip/_action-strip-theme.scss, projects/igniteui-angular/src/lib/core/styles/components/banner/_banner-theme.scss, projects/igniteui-angular/src/lib/core/styles/components/bottom-nav/_bottom-nav-theme.scss, projects/igniteui-angular/src/lib/core/styles/components/button-group/_button-group-theme.scss, projects/igniteui-angular/src/lib/core/styles/components/navbar/_navbar-theme.scss, projects/igniteui-angular/src/lib/core/styles/components/navdrawer/_navdrawer-theme.scss, projects/igniteui-angular/src/lib/core/styles/components/paginator/_paginator-theme.scss, projects/igniteui-angular/src/lib/core/styles/components/progress/_progress-theme.scss
=> refactor(components): use spacing for margin and padding 

projects/igniteui-angular/src/lib/grids/filtering/excel-style/grid.excel-style-filtering.component.ts
=> fix(esf): solving a date juggling error - 12.3

CHANGELOG.md, projects/igniteui-angular/src/lib/combo/README.md, projects/igniteui-angular/src/lib/combo/combo.common.ts, projects/igniteui-angular/src/lib/combo/combo.component.html, projects/igniteui-angular/src/lib/combo/combo.component.spec.ts, projects/igniteui-angular/src/lib/combo/combo.component.ts, projects/igniteui-angular/src/lib/combo/combo.pipes.ts, projects/igniteui-angular/src/lib/simple-combo/README.md, projects/igniteui-angular/src/lib/simple-combo/simple-combo.component.html, src/app/combo/combo.sample.html, src/app/combo/combo.sample.ts
Closes #9884
Closes #11532
Closes #11810  
Extend the combos' filtering options. Now `filterable` and `filteringKey` could be provided. Also deprecate `IgxComboComponent`'s `filterable` property.
=> Extend combos' filtering options - 14.0

projects/igniteui-angular/src/lib/core/styles/components/tree/_tree-theme.scss, src/app/tree/tree.sample.scss
=> fix(tree): Make the tree scroll automatically when it reaches its parent height.

projects/igniteui-angular/src/lib/directives/radio/radio-group.directive.spec.ts, projects/igniteui-angular/src/lib/directives/radio/radio-group.directive.ts, projects/igniteui-angular/src/lib/radio/radio.component.ts
Closes https://github.com/IgniteUI/igniteui-angular/issues/11849, https://github.com/IgniteUI/igniteui-angular/issues/11942
=> fix(radio): allowing radio group to pick dynamically added radios - 14.0

projects/igniteui-angular/src/lib/simple-combo/simple-combo.component.ts, src/app/combo/combo.sample.html, src/app/combo/combo.sample.ts, src/app/combo/remote-nwind.service.ts
The issue described in https://github.com/IgniteUI/igniteui-angular/issues/11885 is on application level, so we have to update the sample of the remote binding combo. We may also want to consider adding a remote binding sample for the simple combo as well as the components do require somewhat different setup because they operate very differently. However, as I was playing around with both combos I noticed that if you scroll down a simple combo with remote data bound to it and you select an item, after closing and reopening, the combo loses all items in the dropdown. The reason was that we attempt to navigate to the currently selected item upon opening, however, with remote data bound, this triggers the `igxFor`'s `chunkPreload` which occurs on `scroll`. This causes the `igxFor`'s state to …
=> Combo filtering enhancements

projects/igniteui-angular/src/lib/simple-combo/simple-combo.component.spec.ts, projects/igniteui-angular/src/lib/simple-combo/simple-combo.component.ts
Closes #12100 
This PR also fixes an issue where the **closing event** was emitted once when closing the combo via the toggle button, but twice when closing it when clicking outside of it.
**NOTE FOR TESTING** : 
* Verify that the input is cleared when closing the combo via the toggle button and immediately clicking outside of the combo, i.e., the below should **not** be reproducible:
=> [IgxSimpleCombo]: clear input on blur when combo is collapsed - 14.2.x

projects/igniteui-angular/src/lib/simple-combo/simple-combo.component.spec.ts, projects/igniteui-angular/src/lib/simple-combo/simple-combo.component.ts
Closes #12100 
This PR also fixes an issue where the **closing event** was emitted once when closing the combo via the toggle button, but twice when closing it when clicking outside of it.
**NOTE FOR TESTING** : 
* Verify that the input is cleared when closing the combo via the toggle button and immediately clicking outside of the combo, i.e., the below should **not** be reproducible:
=> [IgxSimpleCombo]: clear input on blur when combo is collapsed - 13.2.x

projects/igniteui-angular/src/lib/simple-combo/simple-combo.component.spec.ts, projects/igniteui-angular/src/lib/simple-combo/simple-combo.component.ts
Closes #12100 
This PR also fixes an issue where the **closing event** was emitted once when closing the combo via the toggle button, but twice when closing it when clicking outside of it.
**NOTE FOR TESTING** : 
* Verify that the input is cleared when closing the combo via the toggle button and immediately clicking outside of the combo, i.e., the below should **not** be reproducible:
=> [IgxSimpleCombo]: clear input on blur when combo is collapsed - 12.3.x

projects/igniteui-angular/src/lib/select/select.component.spec.ts, projects/igniteui-angular/src/lib/select/select.component.ts
=> fix(select): Fix oldSelection when the value is undefined on 14.2.x

projects/igniteui-angular/src/lib/action-strip/action-strip.component.ts, projects/igniteui-angular/src/lib/action-strip/grid-actions/grid-editing-actions.component.spec.ts, projects/igniteui-angular/src/lib/grids/row.directive.ts
=> fix(action-strip): Hide action strip on mouse leave event of row 14.2.x

.angulardoc.json, projects/igniteui-angular/src/lib/directives/autocomplete/autocomplete.directive.spec.ts, projects/igniteui-angular/src/lib/directives/autocomplete/autocomplete.directive.ts
=> Autocomplete Japanese input support for Chrome on Mac - 12.3

projects/igniteui-angular/migrations/update-15_0_0/index.spec.ts, projects/igniteui-angular/migrations/update-15_0_0/index.ts
Migrate all custom CSS properties (aka CSS variables) prefix from `--igx-` to `--ig-`. Also migrates if CSS custom property contains `grays` migrate it to `gray`, e.g. `--igx-grays-200` will be migrated to `--ig-gray-200`.
Closes #12389
=> Migrate css custom properties

projects/igniteui-angular/src/lib/action-strip/grid-actions/grid-editing-actions.component.ts, projects/igniteui-angular/src/lib/grids/common/crud.service.ts, projects/igniteui-angular/src/lib/grids/grid/grid-row-editing.spec.ts
=> Don't allow entering edit mode if PrimaryKey is not set - 15.0

projects/igniteui-angular/src/lib/action-strip/grid-actions/grid-editing-actions.component.ts, projects/igniteui-angular/src/lib/grids/common/crud.service.ts, projects/igniteui-angular/src/lib/grids/grid/grid-row-editing.spec.ts
=> Don't allow entering edit mode if PrimaryKey is not set - 14.2

projects/igniteui-angular/src/lib/data-operations/filtering-state.interface.ts
Removing a redundant filteringStateDefaults export. See https://github.com/IgniteUI/igniteui-angular/pull/12639
=> refactor(filtering): remove redundant defaults object export

projects/igniteui-angular/src/lib/date-common/util/date-time.util.spec.ts
Chromium (110 onwards I believe) changed the Intl-returned format for year suffix like bg-BG's `г.` to be separated with Narrow No-Break Space (`&#8239`) instead of regular space (32). This normalizes it for checks
Closes #
=> test(date-util): make format check w/ space more flexible

projects/igniteui-angular/src/lib/grids/public_api.ts
Export missing DropPosition api. #12663.
After this change is merged and deployed [DropPosition link](https://infragistics.com/products/ignite-ui-angular/docs/typescript/latest/enums/dropposition.html) should work.
=> chore(*): Export DropPosition api

projects/igniteui-angular/src/lib/grids/columns/column.component.ts, projects/igniteui-angular/src/lib/grids/common/grid.interface.ts, projects/igniteui-angular/src/lib/grids/grid-base.directive.ts, projects/igniteui-angular/src/lib/grids/grid/grid.component.ts, projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-grid.component.ts, projects/igniteui-angular/src/lib/grids/public_api.ts, projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid.component.ts
Cherry picked changes made for Elements/Blazor in #12229:
- Don't use anonymous object types for contexts as it makes those harder to use for automated analysis
- Exposed one missing and the added types
- Explicitly types as `void` the ones that provide no context whatsoever instead of `any`
=> Grids' template context cleanup

projects/igniteui-angular/src/lib/core/styles/components/input/_input-group-theme.scss
The color inheritance overrides the filled text color.
Related to https://github.com/IgniteUI/igniteui-angular-samples/issues/3270
=> fix(input-group) remove color inherit from the borrder type input

projects/igniteui-angular/src/lib/action-strip/grid-actions/grid-editing-actions.component.spec.ts, projects/igniteui-angular/src/lib/action-strip/grid-actions/grid-pinning-actions.component.ts, projects/igniteui-angular/src/lib/grids/api.service.ts, projects/igniteui-angular/src/lib/grids/common/grid.interface.ts, projects/igniteui-angular/src/lib/grids/grid-base.directive.ts, projects/igniteui-angular/src/lib/grids/grid/grid-row-pinning.spec.ts
=> fix(row-pinning): preserve pinned state on editing primary key -14.2.x

projects/igniteui-angular/src/lib/grids/filtering/base/grid-filtering-row.component.ts, projects/igniteui-angular/src/lib/grids/grid/grid-filtering-ui.spec.ts
=> fix(filtering): reset expression to selected unary condition

projects/igniteui-angular/src/lib/grids/hierarchical-grid/child-grid-row.component.html, projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.component.ts
=> Generate child igx-hierarchical-grids dynamically.

projects/igniteui-angular/src/lib/simple-combo/simple-combo.component.spec.ts, projects/igniteui-angular/src/lib/simple-combo/simple-combo.component.ts
=> fix(simple-combo): set value to empty string when the remote data is not present - 15.1.x

projects/igniteui-angular/src/lib/simple-combo/simple-combo.component.spec.ts, projects/igniteui-angular/src/lib/simple-combo/simple-combo.component.ts
=> fix(simple-combo): set value to empty string when the remote data is not present - 14.2.x

CHANGELOG.md, projects/igniteui-angular/migrations/update-16_0_0/changes/classes.json, projects/igniteui-angular/migrations/update-16_0_0/changes/members.json, projects/igniteui-angular/src/lib/grids/common/grid.interface.ts, projects/igniteui-angular/src/lib/grids/grid-base.directive.ts, projects/igniteui-angular/src/lib/grids/grid/grid.component.ts, projects/igniteui-angular/src/lib/grids/grid/grid.directives.ts, projects/igniteui-angular/src/lib/grids/grid/grid.groupby.spec.ts, projects/igniteui-angular/src/lib/grids/grid/public_api.ts, projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.component.ts, projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.spec.ts, projects/igniteui-angular/src/lib/grids/public_api.ts, src/app/hierarchical-grid/hierarchical-grid.sample.ts
Expose the previously available through directives templates as `@Input`
The breaking change is super minor - The existing directive names are correct and remain the same. I don't see any docs/samples using the directives and I doubt the actual class imports were used or the improperly exposed content query props, but still added the note and migrations just in case.
=> feat(grid,h-grid): expand/collapse indicator template inputs

CHANGELOG.md
=> chore(changelog): move sections, formatting, typo

projects/igniteui-angular/src/lib/core/styles/components/date-picker/_date-picker-theme.scss
=> fix(date-picker): move the colors for special dates on the proper element

projects/igniteui-angular/src/lib/grids/cell.component.ts, projects/igniteui-angular/src/lib/grids/common/grid.interface.ts, projects/igniteui-angular/src/lib/test-utils/grid-validation-samples.spec.ts
Removed recently exposed `defaultErrorTemplate` on `CellType` to resolve a test setup error, since there's an exposed context property for that and that's the only place this template is of any use.
=> chore(CellType): revert unintentionally exposed defaultErrorTemplate

projects/igniteui-angular/src/lib/grids/grid-base.directive.ts
The doc comment says get/sets and it really doesn't make sense to have to have a setter alone on a proper input (not to mention it's not even valid to have a less-accessible getter in general)
=> docs(grid): fix sortingOptions getter description

projects/igniteui-angular/src/lib/grids/columns/column-group.component.ts
`IgxColumnGroupComponent` has hidden and non-functional setter overrides for `bodyTemplate` and `inlineEditorTemplate`, but had the getters left public, which is pretty useless. Hidden those as well as the `selectable` setter, since it only works as getter on the group.
=> docs(col-group): fix body/edit template docs; selectable setter

projects/igniteui-angular/src/lib/grids/grid-base.directive.ts
Removed the hidden `virtualizationState` setter as the property was always intended to work as a get accessor only and therefore there's no usage that I can find in dev demos/samples/docs. Since get/set describe a single property, all the setter did was pollute the intellisense and mess w/ analysis tooling:
=> refactor(grid): remove redundant virtualizationState setter

projects/igniteui-angular/src/lib/grids/grid-base.directive.ts
The [`rowHeight`](https://www.infragistics.com/products/ignite-ui-angular/docs/typescript/latest/classes/IgxGridComponent.html#rowHeight) wasn't typed and so wasn't the backing property, thus a type couldn't be established and resulted in the prop being marked as `any`:
Properly types as number now, but I kept the option to set string to be parsed which required a small refactor in the setter.
=> refactor(grid): establish rowHeight type, keep string set option

projects/igniteui-angular/src/lib/date-picker/date-picker.component.spec.ts, projects/igniteui-angular/src/lib/date-picker/date-picker.component.ts
Closes #13052   
**Note**: When binding the date picker's value to an invalid date, e.g., `new Date('test')`, and opening the calendar, today's date should be focused.
=> fix(date-picker): set calendar view date properly - 14.2.x

projects/igniteui-angular/src/lib/date-picker/date-picker.component.spec.ts, projects/igniteui-angular/src/lib/date-picker/date-picker.component.ts
Closes #13052 
**Note**: When binding the date picker's value to an invalid date, e.g., `new Date('test')`, and opening the calendar, today's date should be focused.
=> fix(date-picker): set calendar view date properly - 15.1.x

projects/igniteui-angular/src/lib/date-picker/date-picker.component.spec.ts, projects/igniteui-angular/src/lib/date-picker/date-picker.component.ts
Closes #13052   
**Note**: When binding the date picker's value to an invalid date, e.g., `new Date('test')`, and opening the calendar, today's date should be focused.
=> fix(date-picker): set calendar view date properly - 16.0.x

projects/igniteui-angular/src/lib/directives/radio/radio-group.directive.ts
Closes #13236
The disabled option of FormControl does nothing for individual radio buttons when used on a radio group.
=> fix(radio-group): FormControl disabled doesn't work

CHANGELOG.md, projects/igniteui-angular/src/lib/core/styles/components/drop-down/_drop-down-theme.scss, projects/igniteui-angular/src/lib/select/select-item.component.html, projects/igniteui-angular/src/lib/select/select-item.component.ts, src/app/drop-down/drop-down.sample.html, src/app/drop-down/drop-down.sample.ts, src/app/select/select.sample.html
=> Select: Adding support for items suffix and prefix

projects/igniteui-angular/src/lib/directives/text-highlight/text-highlight.directive.ts, projects/igniteui-angular/src/lib/grids/cell.component.ts, projects/igniteui-angular/src/lib/grids/common/events.ts, projects/igniteui-angular/src/lib/grids/grid-base.directive.ts, projects/igniteui-angular/src/lib/grids/grid/grid.search.spec.ts, src/app/grid-search-box/grid-search-box.component.html
=> Add lastSearchInfo docs and unify interfaces with highlight directive- master

projects/igniteui-angular/src/lib/core/styles/components/input/_input-group-theme.scss, projects/igniteui-angular/src/lib/select/select.component.spec.ts, src/app/input-group/input-group.sample.scss
=> fix(input): styling inconsistencies

projects/igniteui-angular-i18n/package.json, projects/igniteui-angular/src/lib/buttonGroup/buttongroup.component.spec.ts
(cherry picked from commit 72cf4c66410b6012f17ad2c75617ba8dea4afbca)
Closes #13411
=> fix(i18n): sideEffects flag for tree-shaking

projects/igniteui-angular-i18n/package.json, projects/igniteui-angular/package.json
Closes #13467
Add `igniteui-angular-i18n` & `@igniteui/angular-schematics` to be automatically update along with `igniteui-angular`. Adding the same for the `igniteui-angular-i18n` package.
=> feat(migrations): add i18n and schematics as automatic updates

package-lock.json, package.json, projects/igniteui-angular/src/lib/core/styles/components/action-strip/_action-strip-theme.scss, projects/igniteui-angular/src/lib/core/styles/components/button-group/_button-group-theme.scss, projects/igniteui-angular/src/lib/core/styles/components/button/_button-theme.scss, projects/igniteui-angular/src/lib/core/styles/components/calendar/_calendar-theme.scss, projects/igniteui-angular/src/lib/core/styles/components/card/_card-theme.scss, projects/igniteui-angular/src/lib/core/styles/components/carousel/_carousel-theme.scss, projects/igniteui-angular/src/lib/core/styles/components/checkbox/_checkbox-theme.scss, projects/igniteui-angular/src/lib/core/styles/components/chip/_chip-theme.scss, projects/igniteui-angular/src/lib/core/styles/components/dialog/_dialog-theme.scss, projects/igniteui-angular/src/lib/core/styles/components/drop-down/_drop-down-theme.scss, projects/igniteui-angular/src/lib/core/styles/components/expansion-panel/_expansion-panel-theme.scss, projects/igniteui-angular/src/lib/core/styles/components/grid/_grid-theme.scss, projects/igniteui-angular/src/lib/core/styles/components/input/_input-group-theme.scss, projects/igniteui-angular/src/lib/core/styles/components/list/_list-theme.scss, projects/igniteui-angular/src/lib/core/styles/components/navdrawer/_navdrawer-theme.scss, projects/igniteui-angular/src/lib/core/styles/components/progress/_progress-theme.scss, projects/igniteui-angular/src/lib/core/styles/components/snackbar/_snackbar-theme.scss, projects/igniteui-angular/src/lib/core/styles/components/splitter/_splitter-theme.scss, projects/igniteui-angular/src/lib/core/styles/components/stepper/_stepper-theme.scss, projects/igniteui-angular/src/lib/core/styles/components/switch/_switch-theme.scss, projects/igniteui-angular/src/lib/core/styles/components/tabs/_tabs-theme.scss, projects/igniteui-angular/src/lib/core/styles/components/time-picker/_time-picker-theme.scss, projects/igniteui-angular/src/lib/core/styles/components/toast/_toast-theme.scss, projects/igniteui-angular/src/lib/core/styles/components/tooltip/_tooltip-theme.scss, projects/igniteui-angular/src/lib/core/styles/components/watermark/_watermark-theme.scss
Related https://github.com/IgniteUI/igniteui-theming/pull/113
=> refactor(themes): use already ingested border-radius

projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.component.ts, projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.spec.ts
=> fix(hierarchical-grid): add setter for child grid row data - 15.1.x

projects/igniteui-angular/migrations/common/ServerHost.ts, projects/igniteui-angular/migrations/common/UpdateChanges.ts, projects/igniteui-angular/migrations/common/tsUtils.ts, projects/igniteui-angular/migrations/update-16_1_0/index.spec.ts, projects/igniteui-angular/migrations/update-16_1_0/index.ts
Closes #13476
Migrations that are using language service and trying to update .ts files are not currently working for certain monorepos. The workaround for the moment is to catch such exceptions and skip the migration for such cases.
The way migrations are working now is that they are searching for the `main.ts` file and updating the files in that project. However when some of the logic is put in a separate project under the monorepo (one of the cases is when "projectType": "library"), then the language service doesn't have access to all the files, and an exception is thrown.
=> fix(migrations): main path contains root path

package-lock.json, package.json, projects/igniteui-angular/migrations/common/util.ts, projects/igniteui-angular/migrations/update-12_1_0/index.ts, projects/igniteui-angular/package.json, projects/igniteui-angular/src/lib/grids/grid-base.directive.ts
(cherry picked from commit 38818ac3bfd128c526f4de962066c5ee6c9d7f87)
Closes #
=> chore(grids): bump watermark version

projects/igniteui-angular/src/lib/services/excel/excel-exporter-grid.spec.ts, projects/igniteui-angular/src/lib/services/excel/test-data.service.spec.ts, projects/igniteui-angular/src/lib/services/exporter-common/base-export-service.ts, projects/igniteui-angular/src/lib/test-utils/grid-samples.spec.ts
=> Export formatted column data

projects/igniteui-angular/migrations/common/UpdateChanges.ts
Fix security alert by using regular expression literals https://github.com/IgniteUI/igniteui-angular/security/code-scanning.
Remove unnecessary `\` before `:` and `,`.
=> fix(migrations): use regular expression literals instead of string literals

CHANGELOG.md, projects/igniteui-angular/src/lib/combo/combo.common.ts, projects/igniteui-angular/src/lib/combo/combo.component.spec.ts, projects/igniteui-angular/src/lib/simple-combo/simple-combo.component.spec.ts
The previous type was `IgxComboState` but that was not exported from the public API
and was also identical in values and somewhat redundant, so just switched over to the existing `IgxInputState` it was using underneath anyway.
Closes #
=> fix(combos): change valid property type to exposed IgxInputState

CHANGELOG.md, projects/igniteui-angular/src/lib/combo/combo.common.ts, projects/igniteui-angular/src/lib/simple-combo/README.md, projects/igniteui-angular/src/lib/simple-combo/simple-combo.component.html, projects/igniteui-angular/src/lib/simple-combo/simple-combo.component.spec.ts, projects/igniteui-angular/src/lib/simple-combo/simple-combo.component.ts
Corrects changes made for #13089
=> fix(simple-combo): value & selection correct single type instead array

.github/workflows/npm-publish.yml
Noticed our publish action is erroring on this step: https://github.com/IgniteUI/igniteui-angular/actions/runs/6814787834/job/18532444084#step:7:10
See https://github.blog/changelog/2023-10-05-github-actions-node_options-is-now-restricted-from-github_env/ - which means this has been 'inactive' for a while and is very much a step we can do without.
I checked and:
- based on the current [hosted runners for actions](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources) `ubuntu-latest` should be running about 7 GB RAM and that puts Node since v12 at 2GB
- the heaviest process the publish does is build lib and that from what I see only goes a bit over 1GB, so we can skip this entirely.
=> ci(publish): NODE_OPTIONS emit to GITHUB_ENV is deprecated & not needed

projects/igniteui-angular/src/lib/grids/columns/column.component.ts, projects/igniteui-angular/src/lib/grids/common/grid.interface.ts
We should use `blazorAlternateType` here since we only want the C# output to use these formatter types. The typescript declarations that we generate from the api analyzer should continue using the original function type. This will fix the web components typedoc build.
=> fix(grid): slightly different attr for formatters

projects/igniteui-angular/package.json
Update @igniteui/angular-schematics with version 17.1.1310, which is standalone.
=> chore(migrations): update using standalone schematics

projects/igniteui-angular/src/lib/grids/grid/grid-row-selection.spec.ts, projects/igniteui-angular/src/lib/grids/selection/selection.service.ts
Closes #13757
This PR addresses the issue where shift-click was not functioning correctly in an IgxGrid with grouped rows. The selection logic has been updated to properly handle multi-level group comparisons, ensuring that the shift-click selection is consistent and intuitive in grouped grids.
Additional information:
Checklist:
=> fix(grid): Correct shift-click selection in grouped IgxGrid #13757

projects/bundle-test/src/app/app-routing.module.ts, projects/bundle-test/src/app/grid/grid.component.css, projects/bundle-test/src/app/grid/grid.component.html, projects/bundle-test/src/app/grid/grid.component.ts, projects/igniteui-angular/src/lib/grids/grid-base.directive.ts, projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.component.ts, projects/igniteui-angular/src/lib/paginator/paginator.component.ts, src/app/hierarchical-grid/hierarchical-grid.sample.html
Added a DI alias for the paginator using a lightweight token and swapped the content queries in the grids to use it instead so the component can be tree-shaken when not in use.
Note, it's not a "by-the-book" lightweight token implementation since the `IgxPaginatorComponent` still extends `DisplayDensityBase` and I didn't want to mix that with the token. Instead, left a comment since the density is deprecated and will be dropped eventually. Also, the `paginator` prop on the grids is still part of the public interface (even as hidden) and I left that with just type imports to avoid propagating the change further and will leave that again for later once the public interface is cleaned up.
Results:
Given the app imports just `IgxGridComponent, IgxColumnComponent` before and after:
Small win, …
=> fix(grid,tree-shake): use lightweight token for paginator

projects/igniteui-angular/src/lib/grids/grid-base.directive.ts
Similar to #13896 the toolbar already has the token in place so using that for content query so it can be tree-shaken, though again not directly extended by the component so keeping that as type only.
Given the app imports just `IgxGridComponent, IgxColumnComponent` before and after:
=> fix(grid,tree-shake): use lightweight token for toolbar

projects/igniteui-angular/src/lib/calendar/calendar-base.ts
Closes #  https://github.com/IgniteUI/igniteui-angular/issues/13850
=> fix(calendar): no setting of date if same date is already set

projects/igniteui-angular/src/lib/combo/combo.common.ts, projects/igniteui-angular/src/lib/combo/combo.component.spec.ts, projects/igniteui-angular/src/lib/core/selection.ts, projects/igniteui-angular/src/lib/drop-down/drop-down.component.spec.ts, projects/igniteui-angular/src/lib/drop-down/drop-down.component.ts, projects/igniteui-angular/src/lib/select/select.component.spec.ts, projects/igniteui-angular/src/lib/select/select.component.ts, projects/igniteui-angular/src/lib/simple-combo/simple-combo.component.spec.ts
=> fix(select): fix memory leak in IgxSelectionAPIService - 17.0.x

projects/igniteui-angular/src/lib/buttonGroup/buttonGroup.component.ts
=>  Resolve buttons not selected if initialized after the group

projects/igniteui-angular/src/lib/grids/grid-base.directive.ts, projects/igniteui-angular/src/lib/grids/grid/grid.component.html, projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.component.html, projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.spec.ts, projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-grid.component.html, projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid.component.html
Closes #13976 
[Sample](https://stackblitz.com/edit/igx-hierarchical-grid-empty-grid-template-context-test?file=src%2Fapp%2Fhierarchical-grid%2Fhierarchical-grid-column-resizing%2Fhierarchical-grid-resizing.component.html) for verification
=> fix(hgrid): expose grid instance in template context

projects/igniteui-angular/src/lib/core/styles/components/badge/_badge-theme.scss, projects/igniteui-angular/src/lib/core/styles/components/input/_input-group-theme.scss, projects/igniteui-angular/src/lib/core/styles/typography/_bootstrap.scss, projects/igniteui-angular/src/lib/core/styles/typography/_fluent.scss, projects/igniteui-angular/src/lib/core/styles/typography/_indigo.scss, projects/igniteui-angular/src/lib/core/styles/typography/_material.scss
=> feat(badge): implement typography

projects/igniteui-angular/src/lib/directives/date-time-editor/date-time-editor.directive.spec.ts, projects/igniteui-angular/src/lib/directives/date-time-editor/date-time-editor.directive.ts
=> fix(date-time-editor): handle iso date string for mask value 16.1.x

projects/igniteui-angular/src/lib/core/styles/components/navbar/_navbar-component.scss, projects/igniteui-angular/src/lib/core/styles/components/navbar/_navbar-theme.scss, projects/igniteui-angular/src/lib/core/styles/typography/_indigo.scss, projects/igniteui-angular/src/lib/navbar/navbar.component.html, projects/igniteui-angular/src/lib/navbar/navbar.component.spec.ts, src/app/navbar/navbar.sample.html, src/app/navbar/navbar.sample.scss, src/app/navbar/navbar.sample.ts
Indigo optimizations were prioritized for this refactor. Changes have been made to accommodate a middle section to get closer to the web components implementation, styles now handle empty sections. The navigation bar samples have also been updated to showcase these changes.
=> refactor(navbar): Update the theme to fit the indigo ui design

projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-search.component.ts, projects/igniteui-angular/src/lib/grids/grid/grid-filtering-ui.spec.ts
=> fix(esf): reset forOf startIndex on esf columnChange

projects/igniteui-angular/src/lib/directives/date-time-editor/date-time-editor.directive.ts, projects/igniteui-angular/src/lib/directives/mask/mask.directive.ts
=> Use mask's CVA callbacks - 17.1

projects/igniteui-angular/src/lib/directives/date-time-editor/date-time-editor.directive.ts, projects/igniteui-angular/src/lib/directives/mask/mask.directive.ts
Closes #14110
This was related to the blur handler where the editor specified its own touched callback. This was contradicting with the mask's touched callback and prevented the proper update.
This PR extends the already exting cva callbacks of the mask directive in the date editor.
=> Use mask's CVA callbacks

projects/igniteui-angular/src/lib/directives/date-time-editor/date-time-editor.directive.ts
Closes #14133
This issue was related to the `strictTemplates` option in the Angular compiler options. The editor works fine with `null` or `undefined` passed in as a value, only its type-definition had specified strict `Date | string` . This PR adds `undefined` or `null` as possible values for the `value` setter/getter. I was thinking of creating a `Nullable<T>` type that could set the provided type argument as nullable but this would change what can bee seen when peeking the `value` to `Nullable<Date | string>` which I can't decide if I like or not.
=> Allow nullables in date editor value

package-lock.json, package.json, projects/igniteui-angular/package.json, projects/igniteui-angular/src/lib/core/styles/components/button-group/_button-group-theme.scss, projects/igniteui-angular/src/lib/core/styles/components/button/_button-component.scss, projects/igniteui-angular/src/lib/core/styles/components/button/_button-theme.scss, projects/igniteui-angular/src/lib/core/styles/components/icon-button/_icon-button-theme.scss, projects/igniteui-angular/src/lib/directives/button/button-base.ts, projects/igniteui-angular/src/lib/directives/button/button.directive.ts
Related to IgniteUI/igniteui-webcomponents/issues/1107
[Button Handoff](https://www.figma.com/file/2dnNPqpR7K7tMrWvf3jHpO/Button?type=design&node-id=116-22639&mode=design&t=xsh6UPZPQLvNJN9y-0)
[Button Group Handoff](https://www.figma.com/file/0iCinYLqmAN5sbv305sw0C/branch/Q4Q0fIhkpb02wjrNYwCVTc/Button-Group?type=design&node-id=101-7876&mode=design&t=taVAOZ773Zkhgcw0-0)
=> refactor(button/icon-button/button-group): style updates

projects/igniteui-angular/src/lib/core/styles/components/overlay/_overlay-component.scss, projects/igniteui-angular/src/lib/core/styles/components/overlay/_overlay-theme.scss, projects/igniteui-angular/src/lib/core/utils.ts, projects/igniteui-angular/src/lib/directives/toggle/toggle.directive.ts
=> fix(overlay): change how containers are hidden

projects/igniteui-angular/src/lib/grids/common/crud.service.ts
=> fix(IgxGrid): Add checks in case cell is no longer in view.

projects/igniteui-angular/src/lib/core/styles/components/switch/_switch-component.scss, projects/igniteui-angular/src/lib/core/styles/components/switch/_switch-theme.scss, projects/igniteui-angular/src/lib/switch/switch.component.html
=> feat(switch): refine switch theme

CHANGELOG.md, projects/igniteui-angular/src/lib/simple-combo/simple-combo.component.spec.ts, projects/igniteui-angular/src/lib/simple-combo/simple-combo.component.ts
=> Update the model value only if selection is changed

projects/igniteui-angular/src/lib/core/styles/components/overlay/_overlay-theme.scss
=> fix(grid): On Safari set padding to 0 when hiding the toggle

projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-grid.component.ts
Currently visible in https://www.infragistics.com/products/ignite-ui-angular/docs/typescript/latest/classes/IgxPivotGridComponent.html when it shouldn't be.
=> docs(pivot): mark gridSize override internal

projects/igniteui-angular/src/lib/services/exporter-common/base-export-service.ts
Related to #14017
https://www.infragistics.com/products/ignite-ui-angular/docs/typescript/latest/classes/IgxExcelExporterService.html#addPivotRowHeaders is visible in the public API, when it shouldn't be. Guessing copied over from `addPivotGridColumns` which likely is in he same situation, so marking both `private`.
=> refactor(exporter): mark extra pivot methods private

projects/igniteui-angular/src/lib/combo/combo.common.ts, projects/igniteui-angular/src/lib/simple-combo/simple-combo.component.spec.ts
=> fix(combo): Handle selection when placed in an IgxGrid cell template and grid is virtualized -  master

projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-grid-keyboard-nav.spec.ts, projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-grid-navigation.service.ts
=> feat(pivotGrid): row dimension expand/collapse with kb interaction

projects/igniteui-angular/src/lib/buttonGroup/buttonGroup.component.ts, projects/igniteui-angular/src/lib/buttonGroup/buttongroup.component.spec.ts
=> fix(button-group): prevent selected event from emitting twice on click - 18.0.x

projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-grid-navigation.service.ts
Fixes issue when navigating from pivot row dimension header group to the pivot row header group in the header row when horizontal layout is disabled
=> fix(pivotGrid): row dimension kb nav

CHANGELOG.md, projects/igniteui-angular/migrations/update-18_1_0/changes/members.json, projects/igniteui-angular/migrations/update-18_1_0/index.spec.ts, projects/igniteui-angular/src/lib/grids/columns/column-group.component.ts, projects/igniteui-angular/src/lib/grids/columns/column.component.ts, projects/igniteui-angular/src/lib/grids/common/grid.interface.ts, projects/igniteui-angular/src/lib/grids/grid/column-group.spec.ts, src/app/grid-column-groups/grid-column-groups.sample.ts
The idea is to move the query prop to an internal one.
Partially due to Elements conflicts with the `children` name, but also because it's a `QueryList` that should've never been on the public API and all queries are bound to break if we ever replace them with the signal equivalents. This tries to avoid a direct breaking with the deprecation, though still iffy on the naming and could easily more the query to a separate one and change the `children` to return the array directly and figure some name remapping for Elements.
PS: Yes, this kind of migration works, ran on the samples it did update the 3 with usage:
Used here https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/multi-column-headers#multi-column-header-template
=> refactor(columns): deprecate children and replace with childColumns

CHANGELOG.md, projects/igniteui-angular/migrations/update-18_1_0/changes/members.json, projects/igniteui-angular/migrations/update-18_1_0/index.spec.ts, projects/igniteui-angular/src/lib/paginator/pager.component.html, projects/igniteui-angular/src/lib/paginator/paginator.component.spec.ts, projects/igniteui-angular/src/lib/paginator/paginator.component.ts, src/app/pagination/pagination.template.html
The `isFirstPageDisabled` and `isLastPageDisabled` are just proxies of `isFirstPage` and `isLastPage` already - no reason for them.
The only use I can find outside internal was in a dev demo and the docs actually already instruct to use the latter - see Example under https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/paging#angular-pagination-example
=> refactor(paginator): deprecate isFirstPageDisabled and isLastPageDisabled

projects/igniteui-angular/src/lib/grids/hierarchical-grid/row-island.component.ts
There are probably more API members that make no sense for the Row Island (likely shouldn't inherit the grid base directly).
For now (due to Elements), cleaning up the state getters that can't meaningfully work since the island doesn't have data, view children (thus no data views or virtualization state) and it's not a single grid to report column pinned states and the like.
=> refactor(row-island): disable getters of no use and hide from api docs

projects/igniteui-angular/src/lib/grids/cell.component.ts, projects/igniteui-angular/src/lib/grids/columns/column.component.ts, projects/igniteui-angular/src/lib/grids/common/enums.ts, projects/igniteui-angular/src/lib/grids/common/grid.interface.ts, projects/igniteui-angular/src/lib/grids/grid-base.directive.ts, projects/igniteui-angular/src/lib/grids/grid-public-row.ts, projects/igniteui-angular/src/lib/grids/grid/grid.component.ts, projects/igniteui-angular/src/lib/grids/headers/grid-header-group.component.html, projects/igniteui-angular/src/lib/grids/headers/grid-header.component.ts, projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid-base.directive.ts, projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-grid.component.ts, projects/igniteui-angular/src/lib/grids/row-drag.directive.ts, projects/igniteui-angular/src/lib/grids/selection/selection.service.ts, projects/igniteui-angular/src/lib/grids/summaries/grid-summary.service.ts, projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid.component.ts, projects/igniteui-angular/src/lib/grids/watch-changes.ts, projects/igniteui-angular/src/lib/services/exporter-common/base-export-service.ts
Drop usage of `nativeElement.tagName` to determine what type of grid some logic is dealing with as well as various flags for the pivot only and summary row-specifc.
Bit lame `GridType` is already taken, so went with a simple direct union type and referenced in on overrides to avoid repeating it all over. Kind of works the same, but taking feedback if a name is still required.
Note there's a commit list with reasonably isolated changes for easier review :)
=> refactor(grids): clean up internal types handling

projects/igniteui-angular/src/lib/grids/grid/grid.component.spec.ts, projects/igniteui-angular/src/lib/grids/headers/grid-header-group.component.html
=> fix(igxGrid): Fix issue with group expanding container.

projects/igniteui-angular/src/lib/grids/common/grid.interface.ts, projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.component.ts
`IgxChildGridRowComponent` is [visible in the API docs](https://www.infragistics.com/products/ignite-ui-angular/docs/typescript/latest/classes/IgxChildGridRowComponent.html), yet it's used for two hidden properties of the HGrid and I see no reason for that. I see no usage outside internal service and tests for those.
_Also causes the API analyzer to produce a bogus model class from Elements and I want to get rid of it :)_
Actually, I see 0 usage for the actual `hierarchicalRows` query, even tho the child row**s** are looped, so something is not quite right and @dkamburov you guys might want to have a look at that at some point.
=> docs(h-grid): mark the internal child row class as such

projects/igniteui-angular/src/lib/directives/divider/divider.directive.ts
Related to #14550
The `@Input` sitting with rename on the private backing field causes strict templates to fail type checks:
PS: Could also merge the doc comments
=> fix(divider): correct inset input target

projects/igniteui-angular/src/lib/grids/grid/grid-filtering-advanced.spec.ts, projects/igniteui-angular/src/lib/query-builder/query-builder.component.ts, projects/igniteui-angular/src/lib/test-utils/grid-samples.spec.ts
=> fix(advance-filtering): handle error when columns are dynamically changed - 18.1.x

projects/igniteui-angular/src/lib/drop-down/drop-down.base.ts, projects/igniteui-angular/src/lib/select/select.component.spec.ts
=> fix(drop-down): ensure id attribute is set correctly when using bracket syntax - 18.1.x

projects/igniteui-angular-elements/src/app/app.module.ts, projects/igniteui-angular-elements/src/app/custom-strategy.spec.ts, projects/igniteui-angular-elements/src/lib/state.component.ts
=> fix(elements): inject grid instead of grid api in state component

projects/igniteui-angular/src/lib/core/styles/components/navdrawer/_navdrawer-theme.scss, src/app/app.component.ts
=> Nav drawer - fixing navdrawer item in material theme to work with ripple directive

projects/igniteui-angular/src/lib/grids/grid/grid-filtering-advanced.spec.ts, projects/igniteui-angular/src/lib/query-builder/query-builder.component.html, projects/igniteui-angular/src/lib/test-utils/grid-samples.spec.ts
=> fix(query-builder): Fix for dateTime's searchValueInput focus -18.1.x

projects/igniteui-angular/src/lib/core/styles/components/input/_input-group-theme.scss
Fix icon size when SVG icons are used inside the prefix/suffix of the input group combo and select
Closes https://github.com/IgniteUI/igniteui-angular/issues/14617
=> input-group - fix icons size inside prefix/suffix

projects/igniteui-angular/src/lib/grids/grid-base.directive.ts, projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-grid.component.ts
Related to #14315 
This PR adjusts the deprecation notice for the autoGenerate property, updating the version number from 18.1.0 to 18.2.0 because the deprecation was intended for version 18.2.0.
=> chore(grid, pivot-grid): adjust deprecation notice to version 18.2.0 - master

projects/igniteui-angular/src/lib/grids/grid-base.directive.ts
Related to #13562
While the use of the `@__PURE__` notation is valid on a stand-alone expression call (I imagined it wouldn't be, but see https://github.com/javascript-compiler-hints/compiler-notations-spec/blob/main/pure-notation-spec.md, also https://esbuild.github.io/api/#pure) in this scenario it doesn't quite work.
The register is actually side-effectful to begin with and since this is a top level expression that doesn't have it's supposed return value used or exported the notation basically means permanent tree-shake and deletes the register.
=> refactor(grids): move watermark register

projects/igniteui-angular/src/lib/grids/grid/grid-filtering-advanced.spec.ts, projects/igniteui-angular/src/lib/query-builder/query-builder.component.html
=> fix(query-builder): prevent aria-hidden error on the edit icon - 17.2.x

projects/igniteui-angular/src/lib/core/styles/components/banner/_banner-theme.scss
=> refactor(banner-theme): add support for anchor elements as action items

.vscode/launch.json, .vscode/tasks.json, projects/igniteui-angular/migrations/common/ServerHost.ts, projects/igniteui-angular/migrations/common/UpdateChanges.ts, scripts/migrations-sourcemap-shift.mjs
Related to #13712 
Since the encapsulation runs our source using [vm.runInNewContext](https://nodejs.org/docs/latest-v20.x/api/vm.html#scriptruninnewcontextcontextobject-options) with `customRequire` function https://github.com/angular/angular-cli/blob/e51b9068763a115fa27d06e2dd7988b34a3f677c/packages/angular/cli/src/command-builder/utilities/schematic-engine-host.ts#L233-L236 that's strictly require our module resolve code fails with `TypeError: require.resolve is not a function` but that of course is only visible with log tracing on:
But even if that succeeded, we also have the patch to point the first service init for the Angular compilation into the project entry point and that doesn't support the newer application builders that switched to `browser` and `server` entry points instead …
=> fix(migrations): fix LS server resolve with schematics encapsulation

projects/igniteui-angular/src/lib/grids/grid/grid.groupby.spec.ts, projects/igniteui-angular/src/lib/grids/grouping/group-by-area.component.html
=> fix(groupby): using pipetrigger for chip titles too

projects/igniteui-angular/src/lib/core/styles/components/tabs/_tabs-theme.scss, projects/igniteui-angular/src/lib/core/styles/typography/_fluent.scss, src/app/tabs/tabs.sample.html
=> refactor(tabs): align component with UI kits

projects/igniteui-angular/migrations/common/UpdateChanges.spec.ts, projects/igniteui-angular/migrations/common/setup.spec.ts
This should resolve the migration test flickers:
1. Several of the base tests didn't run - due to unit test tree handling patching workspace `architect` options that weren't there and thus the 'build of undefined' errors. **NB** Something off here, these should've failed permanently instead of occasionally when running first in order, so there might be an issue w/ resetting the test tree still.
2. The single NG LS test would fail if it didn't run first in order or a prior test would properly add a `component.ts` file of the same path and load it correctly. Turns out the ng LS also needs `addMissingFileRoot` to consider/compile the new `component.ts` since we scan the html file first.
=> Migrations test fixes

projects/igniteui-angular/migrations/common/UpdateChanges.spec.ts
Missed two more test workspace (`angular.json`) configs in #14919 that lacked build options and could still fail w/ current test setup depending on execution order
=> test(migrations): fix leftover test workspace configs

projects/igniteui-angular/src/lib/services/excel/excel-exporter.spec.ts, projects/igniteui-angular/src/lib/services/excel/test-data.service.spec.ts, projects/igniteui-angular/src/lib/services/exporter-common/export-utilities.ts
=> fix(ExcelExporter): Remove the null char from cell value

projects/igniteui-angular/src/lib/navigation-drawer/navigation-drawer.component.html, projects/igniteui-angular/src/lib/navigation-drawer/navigation-drawer.component.spec.ts, src/app/app.component.html
Change` <aside>` to a simple `<div>,` and remove `role="navigation"` since we're using `<nav>`, which is a semantic tag that doesn’t need to be wrapped in an element with a `role="navigation"`.
Closes https://github.com/IgniteUI/igniteui-angular/issues/14847
=> fix(navigation-drawer): fix ARIA role issue warning

projects/igniteui-angular/src/lib/data-operations/filtering-expressions-tree.ts
Addition to https://github.com/IgniteUI/igniteui-angular/pull/14815
Make the `IFilteringExpressionsTree` find methods optional as well, otherwise plain objects without those do not satisfy the interface type.
=> fix(grid,filtering): expression tree interface optional find methods

projects/igniteui-angular/src/lib/core/styles/components/tabs/_tabs-theme.scss
Since the scroll buttons of the tabs component have been excluded from the keyboard navigation #14886, some styles regarding their focused state become redundant.
=> refactor(tabs): remove unnecessary styles

projects/igniteui-angular/src/lib/core/styles/components/drop-down/_drop-down-theme.scss, projects/igniteui-angular/src/lib/core/styles/typography/_bootstrap.scss, projects/igniteui-angular/src/lib/core/styles/typography/_fluent.scss
- fix unused typography for selected item for all themes
Closes #15004
=> fix(dropdown): fix typography for boostrap and fluent themes

projects/igniteui-angular/src/lib/grids/grid-base.directive.ts, projects/igniteui-angular/src/lib/grids/grid/grid.component.spec.ts, projects/igniteui-angular/src/lib/grids/grid/grid.component.ts, projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.component.ts, projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.spec.ts, projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid.component.spec.ts, projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid.component.ts
Refactor the approach in https://github.com/IgniteUI/igniteui-angular/pull/14945
Closes https://github.com/IgniteUI/igniteui-angular/issues/14928
=> refactor(grids): check if primaryKey exists as a field in the data instead of in the columns

package-lock.json, package.json, projects/igniteui-angular-elements/src/app/wrapper/template-ref-wrapper.ts, projects/igniteui-angular/ng-package.json, projects/igniteui-angular/ng-package.prod.json, projects/igniteui-angular/package.json, projects/igniteui-angular/schematics/utils/dependency-handler.ts, projects/igniteui-angular/src/lib/grids/grid-base.directive.ts
Related to #8191
Replace the `uuid` package with native [`crypto.randomUUID()` method that's widely available](https://developer.mozilla.org/en-US/docs/Web/API/Crypto/randomUUID) and being [used by the package if possible](https://github.com/uuidjs/uuid/blob/1370497eecb5c4a570da3d76aa1b47b86448470f/src/v4.ts#L9-L10) anyway.
=> refactor(grids): replace uuid dep with native crypto method

projects/igniteui-angular/src/lib/directives/drag-drop/drag-drop.directive.ts, projects/igniteui-angular/src/lib/grids/grid-base.directive.ts, projects/igniteui-angular/src/lib/grids/moving/moving.drag.directive.ts, src/app/app.component.ts, src/app/app.routes.ts, src/app/grid-re-create/grid-re-create.sample.html, src/app/grid-re-create/grid-re-create.sample.ts
Closes #13993  
Note: Some elements will still remain detached for the same reasons described here: https://github.com/IgniteUI/igniteui-angular/issues/13994#issuecomment-2419777167
I just noticed some undetached events in the mem. profiler that could be removed, however this will not resolve the issue fully as the core problem for the detached DOM nodes is not on our side.
=> fix(moving): Remove some evt listeners and detach subscribers.

projects/igniteui-angular/src/lib/core/utils.ts, projects/igniteui-angular/src/lib/directives/for-of/for_of.directive.ts, projects/igniteui-angular/src/lib/services/animation/angular-animation-player.ts, projects/igniteui-angular/src/lib/tabs/tabs.directive.ts, projects/igniteui-angular/src/lib/tabs/tabs/tab-header.component.ts, projects/igniteui-angular/src/lib/tabs/tabs/tabs.component.ts
=> fix(ssr): resize observe and animation player errors 17.2.x

projects/igniteui-angular/src/lib/date-range-picker/date-range-picker.component.html, projects/igniteui-angular/src/lib/expansion-panel/expansion-panel-header.component.html, projects/igniteui-angular/src/lib/icon/icon.component.spec.ts, projects/igniteui-angular/src/lib/icon/icon.component.ts, projects/igniteui-angular/src/lib/query-builder/query-builder.component.html, projects/igniteui-angular/src/lib/select/select.component.html
Closes #15159
Removing the explicit ariaHidden binding set to true on component instantiation. Users should use `[attr.aria-hidden]="true"` to control the `aria-hidden` attribute of the Icon component and achieve the same result.
=> refactor(icon): remove ariaHidden member

projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-custom-dialog.component.html, projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-custom-dialog.component.ts, projects/igniteui-angular/src/lib/grids/grid/grid-filtering-ui.spec.ts
=> fix(esf): discard filter in esf menu on cancel button click

projects/igniteui-angular/src/lib/grids/columns/column-group.component.ts, projects/igniteui-angular/src/lib/grids/columns/column-layout.component.ts, projects/igniteui-angular/src/lib/grids/columns/column.component.ts, projects/igniteui-angular/src/lib/grids/grid-base.directive.ts, projects/igniteui-angular/src/lib/grids/grid/column-group.spec.ts, projects/igniteui-angular/src/lib/grids/grid/grid.multi-row-layout.spec.ts, projects/igniteui-angular/src/lib/grids/headers/pipes.ts, projects/igniteui-angular/src/lib/test-utils/grid-functions.spec.ts
=> fix(columns): Change how column width is parsed 

projects/igniteui-angular/src/lib/core/styles/components/checkbox/_checkbox-theme.scss, projects/igniteui-angular/src/lib/core/styles/components/radio/_radio-theme.scss, projects/igniteui-angular/src/lib/core/styles/components/switch/_switch-theme.scss
=> fix(checkbox/switch/radio): inconsistent cursor

projects/igniteui-angular/src/lib/action-strip/action-strip.component.ts, projects/igniteui-angular/src/lib/action-strip/grid-actions/grid-action-button.component.ts, projects/igniteui-angular/src/lib/calendar/calendar.component.ts, projects/igniteui-angular/src/lib/calendar/month-picker/month-picker.component.ts, projects/igniteui-angular/src/lib/calendar/months-view/months-view.component.ts, projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-header.component.ts, projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-row-dimension-header-group.component.ts, projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-row-dimension-mrl-row.component.ts, projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-row-header-group.component.ts, projects/igniteui-angular/src/lib/grids/toolbar/grid-toolbar-advanced-filtering.component.ts, projects/igniteui-angular/src/lib/grids/toolbar/grid-toolbar-exporter.component.ts, projects/igniteui-angular/src/lib/icon/icon.component.ts, projects/igniteui-angular/src/lib/paginator/paginator.component.ts, tsconfig.json
Picked from #15212
Cleaning up unused standalone imports and setting those those fail compilation if found.
Note: The specific unused imports being removed don't have a diagnostics in 18, but leaving the setting regardless for everything else.
=> refactor(*): unused standalone imports cleanup

projects/igniteui-angular/src/lib/services/overlay/overlay.spec.ts, projects/igniteui-angular/src/lib/services/overlay/overlay.ts, src/app/overlay/overlay-animation.sample.html, src/app/overlay/overlay-animation.sample.scss, src/app/overlay/overlay-animation.sample.ts
Closes #15228
Use passed in `show` method `overlay settings`. We were skipping this and with this PR this should be fixed.
=> Use provided in show method overlay settings - 19.0

projects/igniteui-angular/src/lib/dialog/dialog.component.ts, projects/igniteui-angular/src/lib/drop-down/drop-down.component.spec.ts, projects/igniteui-angular/src/lib/drop-down/drop-down.component.ts
Closes #15137
Correctly merge passed in `toggle` and `open` methods partial overlay settings in `dropdown` and `dialog` components.
=> Use provided in open method partial overlay settings - 18.2

projects/igniteui-angular/src/lib/dialog/dialog.component.ts, projects/igniteui-angular/src/lib/drop-down/drop-down.component.spec.ts, projects/igniteui-angular/src/lib/drop-down/drop-down.component.ts
Closes #15137 
Correctly merge passed in `toggle` and `open` methods partial overlay settings in `dropdown` and `dialog` components.
=> Use provided in open method partial overlay settings

projects/igniteui-angular/src/lib/grids/common/crud.service.ts, projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid-add-row-ui.spec.ts
=> fix(igxTreeGrid): Re-eval correct row after collapsing. Add test.

projects/igniteui-angular/src/lib/directives/button/button.directive.ts, projects/igniteui-angular/src/lib/input-group/input-group.component.ts
=> fix(mem-leak): Fix potential memory leaks.

projects/igniteui-angular/src/lib/time-picker/time-picker.component.spec.ts, projects/igniteui-angular/src/lib/time-picker/time-picker.component.ts
Closes https://github.com/IgniteUI/igniteui-angular/issues/15158
Description in PR https://github.com/IgniteUI/igniteui-angular/pull/15367
=> Ensure hours stay clamped within 0-23 when interacting with AM/PM - 18.2.x

projects/igniteui-angular/src/lib/action-strip/grid-actions/grid-editing-actions.component.spec.ts, projects/igniteui-angular/src/lib/action-strip/grid-actions/grid-pinning-actions.component.spec.ts, projects/igniteui-angular/src/lib/buttonGroup/buttongroup.component.spec.ts, projects/igniteui-angular/src/lib/chips/chip.spec.ts, projects/igniteui-angular/src/lib/chips/chips-area.spec.ts, projects/igniteui-angular/src/lib/directives/filter/filter.directive.spec.ts, projects/igniteui-angular/src/lib/drop-down/drop-down.component.spec.ts, projects/igniteui-angular/src/lib/grids/grid/cell.spec.ts, projects/igniteui-angular/src/lib/grids/grid/grid-mrl-keyboard-nav.spec.ts, projects/igniteui-angular/src/lib/grids/grid/grid-row-pinning.spec.ts, projects/igniteui-angular/src/lib/grids/grid/grid.component.spec.ts, projects/igniteui-angular/src/lib/grids/grid/grid.groupby.spec.ts, projects/igniteui-angular/src/lib/grids/grid/grid.master-detail.spec.ts, projects/igniteui-angular/src/lib/grids/grid/grid.multi-row-layout.integration.spec.ts, projects/igniteui-angular/src/lib/grids/grid/grid.multi-row-layout.spec.ts, projects/igniteui-angular/src/lib/grids/state.directive.spec.ts, projects/igniteui-angular/src/lib/grids/state.hierarchicalgrid.spec.ts, projects/igniteui-angular/src/lib/grids/state.treegrid.spec.ts, projects/igniteui-angular/src/lib/radio/radio.component.spec.ts, projects/igniteui-angular/src/lib/select/select.component.spec.ts, projects/igniteui-angular/src/lib/test-utils/grid-mch-sample.spec.ts, projects/igniteui-angular/src/lib/test-utils/grid-samples.spec.ts, projects/igniteui-angular/src/lib/test-utils/grid-validation-samples.spec.ts, projects/igniteui-angular/src/lib/test-utils/template-strings.spec.ts, projects/igniteui-angular/src/lib/tree/tree-samples.spec.ts, projects/igniteui-angular/src/lib/tree/tree.spec.ts
Applying suggestions from #14864 and more adjustments for #15411
=> test(*): apply control flow suggestions

CHANGELOG.md, package-lock.json, package.json, projects/igniteui-angular/package.json, projects/igniteui-angular/src/lib/core/styles/components/list/_list-component.scss, projects/igniteui-angular/src/lib/core/styles/components/list/_list-theme.scss, projects/igniteui-angular/src/lib/list/list-item.component.ts, projects/igniteui-angular/src/lib/list/list.component.spec.ts, projects/igniteui-angular/src/lib/test-utils/list-components.spec.ts, src/app/list/list.sample.html, src/app/list/list.sample.ts
=> feat(list): add selected property to the list-item component

projects/igniteui-angular/src/lib/core/styles/components/calendar/_calendar-theme.scss
Fix the width/height of the after elements that fill the gap between the date rows of the week-number column
Also, I make sure that the date border-color does not affect the week number boxes
Closes https://github.com/IgniteUI/igniteui-angular/issues/15425
=> fix(calendar): resolve layout issues caused by browser zoom

projects/igniteui-angular-elements/src/public_api.ts, projects/igniteui-angular/src/lib/data-operations/filtering-condition.ts, projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid-base.directive.ts, projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-grid.component.ts
Resolving filter operands method access from https://github.com/IgniteUI/igniteui-angular/pull/14647#discussion_r1963904129  & move navigation overrides from #15201 to existing ctor props so they don't affect the analyzer.
=> API analyzer adjustments 19.1

projects/igniteui-angular/src/lib/grids/columns/column.component.ts, projects/igniteui-angular/src/lib/grids/grid/grid-summary.spec.ts, projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.spec.ts
=> fix(column): Update row island summaries when disabledSummaries changes - 19.1.x

projects/igniteui-angular/src/lib/carousel/carousel.component.spec.ts, projects/igniteui-angular/src/lib/carousel/carousel.component.ts
=> fix(carousel): mark for check when active slide change - 19.1.x

projects/igniteui-angular/src/lib/core/styles/components/input/_input-group-theme.scss, projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-search.component.html
=> fix(input-group): empty prefix/suffix is padded

package-lock.json, package.json, projects/igniteui-angular/migrations/migration-collection.json, projects/igniteui-angular/migrations/update-19_1_4/changes/theme-changes.json, projects/igniteui-angular/migrations/update-19_1_4/index.spec.ts, projects/igniteui-angular/migrations/update-19_1_4/index.ts, projects/igniteui-angular/package.json, projects/igniteui-angular/src/lib/core/styles/components/grid/_grid-theme.scss
Closes https://github.com/IgniteUI/igniteui-angular/issues/15477
=> fix(grid-summaries): themes params not fully working

projects/igniteui-angular/src/lib/data-operations/filtering-strategy.spec.ts, projects/igniteui-angular/src/lib/data-operations/filtering-strategy.ts
=> fix(grid): call condition logic only if exists

projects/igniteui-angular/src/lib/data-operations/expressions-tree-util.ts, projects/igniteui-angular/src/lib/data-operations/filtering-expression.interface.ts, projects/igniteui-angular/src/lib/data-operations/filtering-expressions-tree.ts, projects/igniteui-angular/src/lib/grids/grid-base.directive.ts
=> Fix filtering expression throwing error with no columns. Related fixes for elements Blazor grid.

projects/igniteui-angular/src/lib/query-builder/query-builder-functions.spec.ts, projects/igniteui-angular/src/lib/query-builder/query-builder.component.spec.ts
A long running drag and drop test is broken down in four parts to optimize resource use and running time. Hopefully will fix test disconnecting issues.
=> fix(query-builder): refactor drag and drop test - master

projects/igniteui-angular/src/lib/buttonGroup/buttonGroup.component.ts, projects/igniteui-angular/src/lib/buttonGroup/buttongroup-content.component.html, projects/igniteui-angular/src/lib/buttonGroup/buttongroup-content.component.scss, projects/igniteui-angular/src/lib/buttonGroup/themes/_base.scss, projects/igniteui-angular/src/lib/buttonGroup/themes/dark/_index.scss, projects/igniteui-angular/src/lib/buttonGroup/themes/dark/_tokens.scss, projects/igniteui-angular/src/lib/buttonGroup/themes/light/_index.scss, projects/igniteui-angular/src/lib/buttonGroup/themes/light/_tokens.scss, projects/igniteui-angular/src/lib/buttonGroup/themes/shared/_bootstrap.scss, projects/igniteui-angular/src/lib/buttonGroup/themes/shared/_fluent.scss, projects/igniteui-angular/src/lib/buttonGroup/themes/shared/_index.scss, projects/igniteui-angular/src/lib/buttonGroup/themes/shared/_indigo.scss, projects/igniteui-angular/src/lib/buttonGroup/themes/shared/_material.scss, projects/igniteui-angular/src/lib/core/styles/components/button-group/_button-group-theme.scss, projects/igniteui-angular/src/lib/core/styles/themes/generators/_base.scss, projects/igniteui-angular/src/lib/core/styles/typography/_bootstrap.scss, projects/igniteui-angular/src/lib/core/styles/typography/_fluent.scss, projects/igniteui-angular/src/lib/core/styles/typography/_indigo.scss, projects/igniteui-angular/src/lib/core/styles/typography/_material.scss
=> refactor(btn-group):  bundle styles with component

projects/igniteui-angular/src/lib/query-builder/query-builder-tree.component.ts, projects/igniteui-angular/src/lib/query-builder/query-builder.component.spec.ts
=> fix(query-builder): prevent fields collection change - 19.1.x

projects/igniteui-angular/src/lib/data-operations/filtering-expressions-tree.ts
=> Additional fix for enabling filtering expressions to generate as classes in React.

projects/igniteui-angular/src/lib/grids/hierarchical-grid/events.ts, projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.component.ts, projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.pipes.ts, projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.spec.ts
=> feat(hierarchical-grid): add parentRowData to IGridCreatedEventArgs

projects/igniteui-angular/src/lib/core/styles/themes/generators/_base.scss, projects/igniteui-angular/src/lib/grids/summaries/grid-summary.component.scss, projects/igniteui-angular/src/lib/grids/summaries/summary-cell.component.ts, projects/igniteui-angular/src/lib/grids/summaries/summary-row.component.ts, projects/igniteui-angular/src/lib/grids/summaries/themes/_base.scss, projects/igniteui-angular/src/lib/grids/summaries/themes/dark/_index.scss, projects/igniteui-angular/src/lib/grids/summaries/themes/dark/_tokens.scss, projects/igniteui-angular/src/lib/grids/summaries/themes/light/_index.scss, projects/igniteui-angular/src/lib/grids/summaries/themes/light/_tokens.scss, projects/igniteui-angular/src/lib/grids/summaries/themes/shared/_index.scss, projects/igniteui-angular/src/lib/grids/summaries/themes/shared/_indigo.scss
=> refactor(grid-summaries): bundle styles with component

projects/igniteui-angular/src/lib/core/styles/components/drop-down/_drop-down-theme.scss
=> feat(dropdown): improve dropdown theme

projects/igniteui-angular/src/lib/core/styles/components/grid/_grid-theme.scss
=> feat(grid): improve grid theme

projects/igniteui-angular/src/lib/core/styles/components/stepper/_stepper-theme.scss
=> feat(stepper): improve stepper theme

projects/igniteui-angular/src/lib/services/csv/char-separated-value-data.ts, projects/igniteui-angular/src/lib/services/csv/csv-exporter-grid.spec.ts, projects/igniteui-angular/src/lib/services/csv/csv-exporter.ts, projects/igniteui-angular/src/lib/services/csv/csv-verification-wrapper.spec.ts, projects/igniteui-angular/src/lib/services/exporter-common/base-export-service.ts
=> Print row dimensions to CSV properly.

projects/igniteui-angular-elements/src/analyzer/elements.config.ts, projects/igniteui-angular/src/lib/grids/toolbar/grid-toolbar-advanced-filtering.component.ts, projects/igniteui-angular/src/lib/grids/toolbar/grid-toolbar-exporter.component.ts, projects/igniteui-angular/src/lib/grids/toolbar/grid-toolbar-hiding.component.ts, projects/igniteui-angular/src/lib/grids/toolbar/grid-toolbar-pinning.component.ts
After #15766 caused actions to collect the toolbar itself instead of the toolbar actions as parent, which messes with internal functionality relying on correct parent.
=> fix(elements): toolbar actions correct parents meta

projects/igniteui-angular/src/lib/directives/tooltip/tooltip-target.directive.ts, projects/igniteui-angular/src/lib/directives/tooltip/tooltip.directive.spec.ts, projects/igniteui-angular/src/lib/test-utils/tooltip-components.spec.ts
Closes #15719   
- [] New functionality
=> Hide the tooltip on destroying its target.

projects/igniteui-angular/src/lib/core/styles/components/highlight/highlight-theme.scss, projects/igniteui-angular/src/lib/core/styles/components/label/_label-theme.scss, projects/igniteui-angular/src/lib/core/styles/components/ripple/_ripple-theme.scss, projects/igniteui-angular/src/lib/core/styles/components/tooltip/_tooltip-theme.scss
=> refactor(directives): wrap styles in base layer

package-lock.json, package.json, projects/igniteui-angular/src/lib/core/styles/components/grid-summary/_grid-summary-theme.scss, projects/igniteui-angular/src/lib/grids/summaries/themes/_base.scss
=> refactor(grid-summary): remove redundant code and colors

projects/igniteui-angular/src/lib/calendar/calendar-base.ts, projects/igniteui-angular/src/lib/calendar/month-picker/month-picker.component.html
With ng 20 this produces an error 
> NG02300: Suspicious use of week-based year "Y" in date pattern "YYYY". Did you mean to use calendar year "y" instead?
https://github.com/IgniteUI/igniteui-angular/actions/runs/15328149840/job/43168292297#step:11:544
Technically, on edge weeks the week year can return perv year value instead which isn't expected in this use indeed.
=> fix(month-picker): correct date format for year

CHANGELOG.md, projects/igniteui-angular/src/lib/avatar/avatar.component.ts, projects/igniteui-angular/src/lib/badge/badge.component.ts, projects/igniteui-angular/src/lib/buttonGroup/buttonGroup.component.ts, projects/igniteui-angular/src/lib/calendar/calendar.ts, projects/igniteui-angular/src/lib/card/card.component.ts, projects/igniteui-angular/src/lib/carousel/enums.ts, projects/igniteui-angular/src/lib/checkbox/checkbox-base.directive.ts, projects/igniteui-angular/src/lib/chips/chip.component.ts, projects/igniteui-angular/src/lib/core/utils.ts, projects/igniteui-angular/src/lib/data-operations/data-util.ts, projects/igniteui-angular/src/lib/date-common/types.ts, projects/igniteui-angular/src/lib/directives/button/button-base.ts, projects/igniteui-angular/src/lib/directives/button/button.directive.ts, projects/igniteui-angular/src/lib/directives/divider/divider.directive.ts, projects/igniteui-angular/src/lib/directives/radio/radio-group.directive.ts, projects/igniteui-angular/src/lib/drop-down/drop-down.common.ts, projects/igniteui-angular/src/lib/expansion-panel/expansion-panel-header.component.ts, projects/igniteui-angular/src/lib/grids/common/enums.ts, projects/igniteui-angular/src/lib/input-group/inputGroupType.ts, projects/igniteui-angular/src/lib/progressbar/progressbar.component.ts, projects/igniteui-angular/src/lib/services/theme/theme.token.ts, projects/igniteui-angular/src/lib/slider/slider.common.ts, projects/igniteui-angular/src/lib/tabs/tabs/tabs.component.ts, projects/igniteui-angular/src/lib/tree/common.ts
const assertions have been a thing for a while and do exactly what the `mkenum` function was trying to do - get strict literal object types that be used to construct the main union ones. This should even be a _very_ minor optimization as well.
PS: Listed the minor change on chip variant is the changelog, even though it's not documented in any docs/samples.
=> refactor(*): replace mkenum with const assertion

angular.json, package-lock.json, package.json, projects/igniteui-angular-elements/esbuild.mjs, projects/igniteui-angular-elements/src/app/custom-strategy.spec.ts, projects/igniteui-angular-elements/src/app/wrapper/wrapper.component.spec.ts, projects/igniteui-angular-elements/src/app/wrapper/wrapper.component.ts, projects/igniteui-angular/package.json
This is dedupe lit deps with other packages that might use more than the limited set Elements use form `lit-html` and should allow us to sync versions easier too.
=> refactor(elements): externalize lit instead of just lit-html

projects/igniteui-angular/src/lib/combo/combo.common.ts, projects/igniteui-angular/src/lib/input-group/input-group.component.ts, projects/igniteui-angular/src/lib/select/select.component.ts, src/app/input-group-showcase/input-group-showcase.sample.ts
=> fix(combo/select): remove suffix dynamically

projects/igniteui-angular/src/lib/core/styles/components/input/_input-group-component.scss, projects/igniteui-angular/src/lib/core/styles/components/input/_input-group-theme.scss
Closes [#434](https://github.com/IgniteUI/igniteui-theming/issues/434)
The WC components were fixed in this PR: https://github.com/IgniteUI/igniteui-webcomponents/pull/1747
=> fix(input-group): bootstrap invalid and success state shadows

projects/igniteui-angular/src/lib/grids/common/strategy.ts, projects/igniteui-angular/src/lib/grids/grid/grid.groupby.spec.ts
=> fix(IgxGrid): Don't use spread operator for large collections.

projects/igniteui-angular/src/lib/carousel/carousel-base.ts, projects/igniteui-angular/src/lib/carousel/carousel.component.spec.ts
=> fix(carousel-base): set animation players to null on destroy - 19.2.x

projects/igniteui-angular/src/lib/carousel/carousel-base.ts, projects/igniteui-angular/src/lib/carousel/carousel.component.spec.ts
=> fix(carousel-base): set animation players to null on destroy - 20.0.x

projects/igniteui-angular/src/lib/core/styles/components/query-builder/_query-builder-theme.scss
Closes https://github.com/IgniteUI/igniteui-angular/issues/15529
=> refactoring(query-builder): expose the outer padding as a css variable

projects/igniteui-angular/src/lib/core/styles/components/drop-down/_drop-down-theme.scss, projects/igniteui-angular/src/lib/directives/for-of/base.helper.component.ts, projects/igniteui-angular/src/lib/directives/for-of/horizontal.virtual.helper.component.ts, projects/igniteui-angular/src/lib/directives/for-of/virtual.helper.component.ts
=> fix(vhelper): fix padding only when vhelper scrollbar is visible

projects/igniteui-angular/src/lib/core/styles/components/input/_input-group-theme.scss
Closes [#15781](https://github.com/IgniteUI/igniteui-angular/issues/15781)
=> fix(input-group, textarea): label position

projects/igniteui-angular/src/lib/grids/cell.component.html, projects/igniteui-angular/src/lib/grids/cell.component.ts, projects/igniteui-angular/src/lib/grids/grid/grid-validation.service.ts, projects/igniteui-angular/src/lib/grids/grid/grid-validation.spec.ts
Closes #15932 
Changes:
1. Do not replace . in field names with _ when passing a name for the ngControl, Use the column field name as a name for the native ngControl added
2. When trying to get a control using ngControl.get, wrap the name in an array. This way ngControl.get will treat it as a literal key. Otherwise, default behavior of ngControl,get("address.street") is to look for a control named "address" and then look for a control nested named "street" , which is nested under address.
3. Assign formControl.errors in a let variable in order to be resolved once, not to be resolved once for each usage in the template
=> Handle validation for fields with '.' - 19.2.x

.github/workflows/nodejs.yml, projects/igniteui-angular-performance/src/app/services/data.service.ts, projects/igniteui-angular/src/lib/data-operations/sorting-strategy.ts, projects/igniteui-angular/src/lib/grids/common/strategy.ts
Improvements so far:
- Improved sorting algorithm using Schwartizian tranformation
- Refactor multi-sorting algorithm to be iterative
- making it faster, easier to read and maintain
- Will not use Intl.collator because it gives around 300ms overhead of the algorithm runtime (Tested for 1 million records)
Sorting improvement timings of 1 million records
1. Single column sort [type:string] - from **3.38s** to **0.42s** (87% faster)
2. Single column sort [type:number] - from **1.5s** to **0.31s** (79% faster)
3. Multi column sort of two columns [type:string then type:number] - from **3.88s** to **0.57s** (85% faster)
**NOTE**: 
Currently, multiple sorting takes (numberOfColumns * sortingTime of 1 column) time because each expression/column can have different sorting strategies. Thus, there …
=> perf(sorting): Sorting performance optimizations

projects/igniteui-angular/src/lib/directives/tooltip/tooltip.directive.spec.ts, projects/igniteui-angular/src/lib/directives/tooltip/tooltip.directive.ts, projects/igniteui-angular/src/lib/test-utils/tooltip-components.spec.ts
=> fix(tooltip): prevent adding multiple document touch event listeners - 20.0.x

projects/igniteui-angular/src/lib/grids/grid/column-resizing.spec.ts, projects/igniteui-angular/src/lib/grids/resizing/resize-handle.directive.ts, projects/igniteui-angular/src/lib/grids/resizing/resizer.directive.ts
=> Fix column resizer position - 20.0.x

projects/igniteui-angular/src/lib/grids/common/grid.interface.ts, projects/igniteui-angular/src/lib/query-builder/query-builder.component.ts
=> fix(QB): Updated entities JSDoc. Removed @hidden decorator

projects/igniteui-angular/src/lib/core/styles/components/grid/_grid-theme.scss, projects/igniteui-angular/src/lib/grids/grid-base.directive.ts, projects/igniteui-angular/src/lib/grids/grid/cell-merge.spec.ts, projects/igniteui-angular/src/lib/grids/row.directive.ts
=> fix(merging): add additional handling for grid size change with merge on

projects/igniteui-angular/src/lib/core/styles/components/button-group/_button-group-theme.scss
- We should not remove a border or any schema-connected style from the theme. Rather, we should update the variable in the schema, which in this case is already done.
Closes #16258
=> fix(button-group): remove unnecessary bootstrap-specific styles
