IgniteUI/igniteui-angular

CHANGELOG.md, projects/igniteui-angular/src/lib/grids/column-chooser-base.ts, projects/igniteui-angular/src/lib/grids/column-hiding.component.html, projects/igniteui-angular/src/lib/grids/column-pinning.component.html, projects/igniteui-angular/src/lib/grids/grid/column-hiding.spec.ts, projects/igniteui-angular/src/lib/grids/grid/column-pinning.spec.ts, projects/igniteui-angular/src/lib/test-utils/grid-base-components.spec.ts
=> Adding `disableFilter` property to Column Choosers. #4102

projects/igniteui-angular/schematics/ng-add/index.spec.ts
=> Fix flickering schematics tests

projects/igniteui-angular/src/lib/grids/grid-base.component.ts
=> fix(docs): Cell and row editing docs update #4055

projects/igniteui-angular/src/lib/grids/grid-base.component.ts
=> chore(grid): Updating editCell event snippets

projects/igniteui-angular/src/lib/directives/label/label.directive.ts
=> docs(igxLabel): remove hidden tag, #4237

CHANGELOG.md, projects/igniteui-angular/src/lib/core/styles/base/utilities/_functions.scss, projects/igniteui-angular/src/lib/core/styles/components/badge/_badge-theme.scss, projects/igniteui-angular/src/lib/core/styles/components/bottom-nav/_bottom-nav-theme.scss, projects/igniteui-angular/src/lib/core/styles/components/button-group/_button-group-theme.scss, projects/igniteui-angular/src/lib/core/styles/components/button/_button-theme.scss, projects/igniteui-angular/src/lib/core/styles/components/calendar/_calendar-theme.scss, projects/igniteui-angular/src/lib/core/styles/components/card/_card-theme.scss, projects/igniteui-angular/src/lib/core/styles/components/carousel/_carousel-theme.scss, projects/igniteui-angular/src/lib/core/styles/components/checkbox/_checkbox-theme.scss, projects/igniteui-angular/src/lib/core/styles/components/chip/_chip-theme.scss, projects/igniteui-angular/src/lib/core/styles/components/combo/_combo-theme.scss, projects/igniteui-angular/src/lib/core/styles/components/date-picker/_date-picker-theme.scss, projects/igniteui-angular/src/lib/core/styles/components/dialog/_dialog-theme.scss, projects/igniteui-angular/src/lib/core/styles/components/drop-down/_drop-down-theme.scss, projects/igniteui-angular/src/lib/core/styles/components/expansion-panel/_expansion-panel-theme.scss, projects/igniteui-angular/src/lib/core/styles/components/grid-toolbar/_grid-toolbar-theme.scss, projects/igniteui-angular/src/lib/core/styles/components/grid/_grid-theme.scss, projects/igniteui-angular/src/lib/core/styles/components/input/_input-group-theme.scss, projects/igniteui-angular/src/lib/core/styles/components/list/_list-theme.scss, projects/igniteui-angular/src/lib/core/styles/components/navdrawer/_navdrawer-theme.scss, projects/igniteui-angular/src/lib/core/styles/components/overlay/_overlay-theme.scss, projects/igniteui-angular/src/lib/core/styles/components/radio/_radio-theme.scss, projects/igniteui-angular/src/lib/core/styles/components/switch/_switch-theme.scss, projects/igniteui-angular/src/lib/core/styles/components/tabs/_tabs-theme.scss, projects/igniteui-angular/src/lib/core/styles/components/time-picker/_time-picker-theme.scss, projects/igniteui-angular/src/lib/core/styles/components/toast/_toast-theme.scss, projects/igniteui-angular/src/lib/core/styles/components/tooltip/_tooltip-theme.scss, projects/igniteui-angular/src/lib/services/overlay/overlay.spec.ts
=> Allow gradient/image values as backgrounds in component themes

projects/igniteui-angular/src/lib/grids/api.service.ts, projects/igniteui-angular/src/lib/grids/filtering/grid-filtering-row.component.html, projects/igniteui-angular/src/lib/grids/filtering/grid-filtering-row.component.ts
=> Remove ngModel from datepicker

projects/igniteui-angular/src/lib/date-picker/README.md, projects/igniteui-angular/src/lib/date-picker/date-picker.component.html, projects/igniteui-angular/src/lib/date-picker/date-picker.component.spec.ts, projects/igniteui-angular/src/lib/date-picker/date-picker.component.ts, src/app/date-picker/date-picker.sample.css, src/app/date-picker/date-picker.sample.html, src/app/date-picker/date-picker.sample.ts
=> fix(date-picker): Fix for re-templating dropdown date-picker 

projects/igniteui-angular/src/lib/directives/for-of/for_of.directive.spec.ts
=> test(igxForOf): Disable sporadic igxForOf test. 

projects/igniteui-angular/src/lib/services/overlay/position/connected-positioning-strategy.ts, projects/igniteui-angular/src/lib/services/overlay/position/global-position-strategy.ts
=> Add inheritdoc to position strategies

projects/igniteui-angular/src/lib/grids/filtering/excel-style/grid.excel-style-filtering.component.ts
=> Select sort button only if default template is used

projects/igniteui-angular/src/lib/tabs/tabs-group.component.ts
=> fix(tabs): Fix for applying styles to tabs group #4351

projects/igniteui-angular/src/lib/grids/grid-base.component.ts
=> fix(grid): resolving misalignment for #4387

projects/igniteui-angular/src/lib/grids/grid-column-resizing.service.ts, projects/igniteui-angular/src/lib/grids/grid-common.module.ts, projects/igniteui-angular/src/lib/grids/grid-header-group.component.html, projects/igniteui-angular/src/lib/grids/grid-header-group.component.ts, projects/igniteui-angular/src/lib/grids/grid-header.component.ts, projects/igniteui-angular/src/lib/grids/grid.common.ts, projects/igniteui-angular/src/lib/grids/grid/grid-filtering-ui.spec.ts, projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid-indentation.spec.ts, projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid-integration.spec.ts
=> Resizing: move resize handle logic in a directive

CHANGELOG.md, projects/igniteui-angular/src/lib/grids/README.md, projects/igniteui-angular/src/lib/grids/column.component.ts, projects/igniteui-angular/src/lib/grids/filtering/grid-filtering-cell.component.html, projects/igniteui-angular/src/lib/grids/filtering/grid-filtering-cell.component.ts, projects/igniteui-angular/src/lib/grids/grid-base.component.ts, projects/igniteui-angular/src/lib/grids/grid-common.module.ts, projects/igniteui-angular/src/lib/grids/grid.common.ts, src/app/app.component.ts, src/app/app.module.ts, src/app/grid-filter-template/grid-filter-template.sample.css, src/app/grid-filter-template/grid-filter-template.sample.html, src/app/grid-filter-template/grid-filter-template.sample.ts, src/app/routing.ts
=> Add igxQuickFilterTemplate directive

projects/igniteui-angular/src/lib/directives/for-of/for_of.directive.ts
=> Making sure size cache is not re-calculated each time sum of the heights is retrieved.

projects/igniteui-angular/src/lib/grids/grid-base.component.ts, projects/igniteui-angular/src/lib/grids/grid/grid.component.spec.ts
=> fix(grid): Fixing grid body height when grid is not in the DOM #4329

projects/igniteui-angular/src/lib/time-picker/time-picker.component.html, projects/igniteui-angular/src/lib/time-picker/time-picker.component.ts
Closes IgniteUI/igniteui-angular-samples#1048
=> Time picker - dropdown width calculation

projects/igniteui-angular/src/lib/grids/api.service.ts, projects/igniteui-angular/src/lib/grids/cell.component.ts, projects/igniteui-angular/src/lib/grids/grid/grid-summary.spec.ts, projects/igniteui-angular/src/lib/grids/summaries/grid-summary.service.ts, projects/igniteui-angular/src/lib/grids/summaries/grid-summary.ts, projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid-summaries.spec.ts
Closes #4324 
Closes #4214
Closes #4317
=> Update child summaries correctly when CRUD operations are performed --7.1.x

projects/igniteui-angular/src/lib/grids/api.service.ts, projects/igniteui-angular/src/lib/grids/cell.component.ts, projects/igniteui-angular/src/lib/grids/grid/grid-summary.spec.ts, projects/igniteui-angular/src/lib/grids/summaries/grid-summary.service.ts, projects/igniteui-angular/src/lib/grids/summaries/grid-summary.ts, projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid-summaries.spec.ts
Closes #4324 
Closes #4214 
Closes #4317
=> Update child summaries correctly when CRUD operations are performed

projects/igniteui-angular/src/lib/date-picker/date-picker.component.spec.ts
=> test(date-picker): Fixed date picker failing test #3833

projects/igniteui-angular/src/lib/grids/api.service.ts, projects/igniteui-angular/src/lib/grids/grid-base.component.ts, projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid.component.spec.ts, projects/igniteui-angular/src/lib/test-utils/tree-grid-components.spec.ts
=> Fix auto-generate columns for TreeGrid

projects/igniteui-angular/src/lib/grids/cell.component.html
=> Grid: fix date picker editable input group display in IE

projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.component.ts
=> adding distinct check overlay cache add - 7.2.x

projects/igniteui-angular/src/lib/grids/grid-navigation.service.ts
Closes #4447   
Please test in Grid, HierarchicalGrid, TreeGrid with group rows and/or summary rows.
=> fix(Grid): Fixing navigation in scenarios where there is only 1 visible row in grid.

projects/igniteui-angular/src/lib/directives/for-of/for_of.directive.ts, src/app/virtual-for-directive/virtual-for.sample.html
=> fix(igxFor): Adding correct index when data is remote.

projects/igniteui-angular/src/lib/grids/cell.component.html, projects/igniteui-angular/src/lib/grids/cell.component.ts, projects/igniteui-angular/src/lib/grids/hierarchical-grid/row-island.component.ts
Also fixed a wrong import path that broke the AoT build
Closes #4314 #1780
=> fix(igx-cell): Focus and IME input handlers

src/app/tooltip/tooltip.sample.css, src/app/tooltip/tooltip.sample.html
=> Fix color of icon tooltip target sample - 7.2.x

projects/igniteui-angular/src/lib/grids/tree-grid/tree-cell.component.html
Closes #4457   
- [ x] Bug fix
- [x ] All relevant tags have been applied to this PR
=> Update treeGrid cell to use date picked with mode dropdown

projects/igniteui-angular/src/lib/grids/grid-base.component.ts, projects/igniteui-angular/src/lib/grids/grid/cell.spec.ts, projects/igniteui-angular/src/lib/grids/grid/grid.component.spec.ts, projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.component.html, projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.component.ts, projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid-integration.spec.ts
=> hide Overlays when scroll grid

CHANGELOG.md, projects/igniteui-angular/src/lib/list/README.md, projects/igniteui-angular/src/lib/list/list-item.component.ts, projects/igniteui-angular/src/lib/list/list.component.spec.ts, projects/igniteui-angular/src/lib/list/list.component.ts, projects/igniteui-angular/src/lib/test-utils/list-components.spec.ts
=> feat(list-item): making index input for igxfor #4465

projects/igniteui-angular/src/lib/directives/for-of/for_of.directive.ts
=> fix(forof): sync reset only for vert #4460

projects/igniteui-angular/src/lib/data-operations/data-util.spec.ts, projects/igniteui-angular/src/lib/data-operations/data-util.ts
=> fix(groupby): resolving groupsRecords reset issue #4479

CHANGELOG.md, projects/igniteui-angular/src/lib/grids/grid-base.component.ts
=> docs(changelog): Adding changelog for 7.2.4

projects/igniteui-angular/src/lib/core/styles/components/radio/_radio-component.scss, projects/igniteui-angular/src/lib/directives/radio/radio-group.directive.ts
=> fix(radio-group): display type gets overridden if specified

projects/igniteui-angular/src/lib/core/styles/components/grid/_grid-theme.scss
=> fix(Grid filtering row): fix z-index for cbx selection and header indentation

projects/igniteui-angular/src/lib/tabs/tabs.component.spec.ts, projects/igniteui-angular/src/lib/tabs/tabs.component.ts
=> fix(tabs): Fixed style applying to tabs

CHANGELOG.md, projects/igniteui-angular/src/lib/directives/dragdrop/dragdrop.directive.ts, projects/igniteui-angular/src/lib/directives/dragdrop/dragdrop.spec.ts, projects/igniteui-angular/src/lib/test-utils/ui-interactions.spec.ts
=> Add originalEvent and relative offsets to the event arguments for the igxDrop directive. 

projects/igniteui-angular/src/lib/date-picker/date-picker.component.spec.ts, projects/igniteui-angular/src/lib/date-picker/date-picker.component.ts, projects/igniteui-angular/src/lib/grids/filtering/grid-filtering-row.component.html
=> #4434 Fixed Filter row date pipe error in IE11.

projects/igniteui-angular/src/lib/grids/grid-base.component.ts
=> Fix onColumnMovingEnd event API description

src/app/app.component.ts, src/app/app.module.ts, src/app/grid-multi-row-layout-config/grid-mrl-config.sample.css, src/app/grid-multi-row-layout-config/grid-mrl-config.sample.html, src/app/grid-multi-row-layout-config/grid-mrl-config.sample.ts, src/app/routing.ts
=> Add Multi-row layout sample with configurator for layouts.

projects/igniteui-angular/src/lib/tabs/tabs-group.component.ts, projects/igniteui-angular/src/lib/tabs/tabs.component.spec.ts
=> fix(tabs): Selection indicator size fix - 7.3.x

projects/igniteui-angular/src/lib/grids/filtering/grid-filtering-row.component.ts, projects/igniteui-angular/src/lib/grids/grid/grid-filtering-ui.spec.ts
=> Fix conditions-dropdown flickering for filter-row -- 7.2.x

projects/igniteui-angular/src/lib/grids/filtering/grid-filtering-row.component.ts, projects/igniteui-angular/src/lib/grids/grid/grid-filtering-ui.spec.ts
=> Fix conditions-dropdown flickering for filter-row -- 7.3.x

projects/igniteui-angular/src/lib/grids/api.service.ts, projects/igniteui-angular/src/lib/grids/filtering/grid-filtering.service.ts, projects/igniteui-angular/src/lib/grids/grid-base.component.ts, projects/igniteui-angular/src/lib/grids/grid/grid-filtering.spec.ts
=> Clear filteredData when setting empty filteringExpressionsTree

projects/igniteui-angular/src/lib/date-picker/date-picker.component.html, projects/igniteui-angular/src/lib/date-picker/date-picker.component.ts
=> fix(date-picker): Focus issue fixed

projects/igniteui-angular/src/lib/core/styles/components/list/_list-theme.scss
=> fix(sass-doc): Fix list theme inclusion (master). 

projects/igniteui-angular/src/lib/core/styles/components/list/_list-theme.scss
=> fix(sass-doc): Fix list theme inclusion (72x)

projects/igniteui-angular/src/lib/grids/grid.common.ts, projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid-indentation.spec.ts
=> Grid: hide resize line on single click

projects/igniteui-angular/src/lib/grids/cell.component.ts, projects/igniteui-angular/src/lib/grids/grid/cell.spec.ts
=> fix(igx-cell): Prevent double selection event

projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid.component.html, projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid.component.spec.ts, projects/igniteui-angular/src/lib/test-utils/tree-grid-components.spec.ts
=> Add default loading template for TreeGrid

projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-default-expression.component.ts, projects/igniteui-angular/src/lib/grids/grid/grid-filtering-ui.spec.ts, projects/igniteui-angular/src/lib/grids/grid/grid-filtering.spec.ts, projects/igniteui-angular/src/lib/test-utils/grid-samples.spec.ts, projects/igniteui-angular/src/lib/test-utils/sample-test-data.spec.ts
=> #4525 Fixed condition name in custom dialog.

projects/igniteui-angular/src/lib/directives/for-of/for_of.directive.spec.ts, projects/igniteui-angular/src/lib/test-utils/ui-interactions.spec.ts
=> tests(scroll): Fix scroll wheel tests due to creating wheel event with deltaY sets also wheelDeltaY.

projects/igniteui-angular/src/lib/grids/column.component.ts, projects/igniteui-angular/src/lib/grids/grid-base.component.ts, projects/igniteui-angular/src/lib/grids/grid/grid.multi-row-layout.spec.ts
Closes #4621
**Note:** Please test different configurations with columns that have different width set in pixels, percentages or not set at all + default column width.
=> fix(MRL): Fix columns sizings in multi row layout where there are columns without widths. 

projects/igniteui-angular/src/lib/grids/api.service.ts, projects/igniteui-angular/src/lib/grids/column.component.ts, projects/igniteui-angular/src/lib/grids/grid-base.component.ts, projects/igniteui-angular/src/lib/grids/grid/grid.component.spec.ts
Closes #4313 
Closes #4538 
- [x ] Bug fix
- [ x] All relevant tags have been applied to this PR
=> Update endEdit when sort, filter, search and hide column

projects/igniteui-angular/src/lib/core/styles/components/column-hiding/_column-hiding-theme.scss, projects/igniteui-angular/src/lib/core/styles/components/drop-down/_drop-down-theme.scss, projects/igniteui-angular/src/lib/grids/grid-toolbar.component.html
=> fix(ColPinning): #4503 Set min-width to dropdown.

projects/igniteui-angular/src/lib/grids/grid-toolbar.component.html, projects/igniteui-angular/src/lib/grids/grid/grid-toolbar.spec.ts
=> Adjust displayDensity of buttons in toolbar according to grid

projects/igniteui-angular/src/lib/data-operations/data-util.spec.ts, projects/igniteui-angular/src/lib/data-operations/data-util.ts
=> fix(groupby): fixing postgrp for collapse edge cases - 7.2

projects/igniteui-angular/src/lib/combo/combo-dropdown.component.ts, projects/igniteui-angular/src/lib/drop-down/drop-down-item.component.ts, projects/igniteui-angular/src/lib/drop-down/drop-down.base.ts, projects/igniteui-angular/src/lib/drop-down/drop-down.component.ts
=> refactor(drop-down): change focus state handling

projects/igniteui-angular/src/lib/date-picker/date-picker.component.ts
Closes #4526  
- [x ] Bug fix
- [ x] All relevant tags have been applied to this PR
=> DatePicker set positionStrategy to be  AutoPositionStrategy

azure-pipelines.yml, projects/igniteui-angular/src/lib/data-operations/data-util.spec.ts, projects/igniteui-angular/src/lib/data-operations/data-util.ts
=> fix(groupby): fixing postgrp for collapse edge cases - master

projects/igniteui-angular/src/lib/date-picker/date-picker.component.ts
Closes #4526   
- [x ] Bug fix
- [x ] All relevant tags have been applied to this PR
=> DatePicker set positionStrategy to be AutoPositionStrategy 

extras/docs/themes/config.json
=> fix(docs): Update canonical and hreflang #4674

projects/igniteui-angular/src/lib/grids/filtering/grid-filtering-row.component.html, projects/igniteui-angular/src/lib/grids/filtering/grid-filtering-row.component.ts, projects/igniteui-angular/src/lib/grids/filtering/grid-filtering.service.ts, projects/igniteui-angular/src/lib/grids/grid-base.component.ts, projects/igniteui-angular/src/lib/grids/grid-navigation.service.ts, projects/igniteui-angular/src/lib/grids/grid/grid-filtering-ui.spec.ts, projects/igniteui-angular/src/lib/grids/grid/grid.component.html, projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.component.html, projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid.component.html
=> Fix keyboard navigation between filter row and grid cells

projects/igniteui-angular/src/lib/drop-down/drop-down.component.ts
=> fix(drop-down): remove overlay from Drop Down constructor

projects/igniteui-angular/src/lib/core/styles/components/grid/_grid-theme.scss, projects/igniteui-angular/src/lib/grids/row-drag.directive.ts
=> fix(grid): Refactoring ghost creation + z-index for drag indicator increased #4681

projects/igniteui-angular/src/lib/grids/column.component.ts, projects/igniteui-angular/src/lib/grids/grid/grid.component.ts, projects/igniteui-angular/src/lib/grids/grid/grid.multi-row-layout.integration.spec.ts, src/app/grid-multi-row-layout/grid-mrl.sample.html
=> chore(grid-mrl): Enforce excel style filtering for multi row layout

projects/igniteui-angular/src/lib/grids/api.service.ts, projects/igniteui-angular/src/lib/grids/grid/grid.component.spec.ts
=> Grid - Properly exit pending state when no new value is committed on endEdit

projects/igniteui-angular/src/lib/grids/grid-navigation.service.ts, projects/igniteui-angular/src/lib/grids/grid/grid-summary.spec.ts
=> Navigate to summary cell form filter cell if the grid is empty

projects/igniteui-angular/src/lib/grids/filtering/grid-filtering-row.component.ts, projects/igniteui-angular/src/lib/grids/grid/grid-filtering-ui.spec.ts
=> Commit input and chip after picking date for filtering - 7.2.x

projects/igniteui-angular/src/lib/grids/filtering/grid-filtering-row.component.ts, projects/igniteui-angular/src/lib/grids/grid/grid-filtering-ui.spec.ts
=> Commit input and chip after picking date for filtering - 7.3.x

projects/igniteui-angular/src/lib/grids/grid/grid-row.component.html
=> Fix pinned area z-index (7.3.x)

projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-search.component.html, projects/igniteui-angular/src/lib/grids/grid/grid-filtering-ui.spec.ts, projects/igniteui-angular/src/lib/test-utils/grid-functions.spec.ts
=> Adjust itemSize for ESF search box - 7.2.x

projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-search.component.ts, projects/igniteui-angular/src/lib/grids/grid/grid-filtering-ui.spec.ts
=> Adjust itemSize for ESF search box - 7.3.x

projects/igniteui-angular/src/lib/grids/api.service.ts, projects/igniteui-angular/src/lib/grids/grid/grid.component.spec.ts
=> Grid - Properly exit pending state when no new value is committed on endEdit - 7.3.x

projects/igniteui-angular/src/lib/grids/row-drag.directive.ts
=> Removing the startDrag method that is now obsolete

projects/igniteui-angular/src/lib/grids/grid-base.component.ts, projects/igniteui-angular/src/lib/grids/grid/grid-selection.spec.ts
=> Check column list in setters for row select and row drag

projects/igniteui-angular/src/lib/grids/filtering/grid-filtering-row.component.ts, projects/igniteui-angular/src/lib/grids/grid/grid-filtering-ui.spec.ts
=> Close filter condition dropdownon on tab key pressed

projects/igniteui-angular/src/lib/data-operations/data-util.spec.ts, projects/igniteui-angular/src/lib/data-operations/data-util.ts, projects/igniteui-angular/src/lib/data-operations/groupby-record.interface.ts, projects/igniteui-angular/src/lib/data-operations/groupby-strategy.spec.ts, projects/igniteui-angular/src/lib/data-operations/grouping-strategy.ts, projects/igniteui-angular/src/lib/data-operations/sorting-strategy.ts, projects/igniteui-angular/src/lib/directives/for-of/for_of.directive.ts, projects/igniteui-angular/src/lib/grids/grid/grid.component.ts, projects/igniteui-angular/src/lib/grids/grid/grid.multi-row-layout.integration.spec.ts, projects/igniteui-angular/src/lib/grids/grid/grid.pipes.ts
=> Fix grid not calculating its cache and sizes when MRL is enabled with GroupBy. Add height to group records metadata.

projects/igniteui-angular/src/lib/directives/for-of/for_of.directive.ts, projects/igniteui-angular/src/lib/directives/for-of/for_of.sync.service.ts, projects/igniteui-angular/src/lib/grids/column.component.ts, projects/igniteui-angular/src/lib/grids/grid-base.component.ts, projects/igniteui-angular/src/lib/grids/grid/grid.component.spec.ts
Closes #4568
Closes #4648
Closes #4720 
Closes #4505
=> fix(gridforof): adding master reassignment for scrambled horizontal dirs - 7.2

projects/igniteui-angular/src/lib/grids/grid-navigation.service.ts, projects/igniteui-angular/src/lib/grids/grid/grid-summary.spec.ts
=> Navigate to summary cell from filter cell if the grid is empty

CHANGELOG.md
=> chore(*): Adding info for the Multi Row Layout

projects/igniteui-angular/src/lib/grids/filtering/grid-filtering-row.component.ts
=> #4636 Check value in input event.

projects/igniteui-angular/src/lib/grids/grid/grid-mrl-keyboard-nav.spec.ts
=> Add keyboard navigation test for pinning and scenarios with bigger row/col spans.

projects/igniteui-angular/src/lib/core/styles/components/grid/_grid-component.scss, projects/igniteui-angular/src/lib/core/styles/components/grid/_grid-theme.scss
=> Fix drag icon size and density

projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-search.component.html, projects/igniteui-angular/src/lib/grids/filtering/excel-style/grid.excel-style-filtering.component.ts, projects/igniteui-angular/src/lib/grids/grid/grid-filtering-ui.spec.ts
=> fix(esf): Do not format the SelectAll checkbox #4737

projects/igniteui-angular/src/lib/grids/grid-base.component.ts
=> fix(igx-grid): Run resize logic in ngZone

projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-custom-dialog.component.html, projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-custom-dialog.component.ts, projects/igniteui-angular/src/lib/grids/grid/grid-filtering-ui.spec.ts, projects/igniteui-angular/src/lib/test-utils/grid-functions.spec.ts
=> Scroll excel custom filter dialog to bottom after adding new expression - 7.2.x

projects/igniteui-angular/src/lib/grids/cell.component.ts, projects/igniteui-angular/src/lib/grids/grid-base.component.ts, projects/igniteui-angular/src/lib/grids/grid-navigation.service.ts, projects/igniteui-angular/src/lib/grids/grid/grid-keyBoardNav.spec.ts, projects/igniteui-angular/src/lib/grids/grid/grid.component.spec.ts, projects/igniteui-angular/src/lib/grids/grid/groupby-row.component.ts, projects/igniteui-angular/src/lib/grids/summaries/summary-cell.component.ts, src/app/grid-cellEditing/grid-cellEditing.component.html, src/app/grid-cellEditing/grid-cellEditing.component.ts
=> Extend Grid API to allow custom keyboard navigation - 7.3.x

CHANGELOG.md
=> docs(igxGrid): Updating changelog #4760

projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-custom-dialog.component.html, projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-custom-dialog.component.ts, projects/igniteui-angular/src/lib/grids/grid/grid-filtering-ui.spec.ts, projects/igniteui-angular/src/lib/test-utils/grid-functions.spec.ts
=> Scroll excel custom filter dialog to bottom after adding new expression - 7.3.x

CHANGELOG.md, projects/igniteui-angular/src/lib/grids/grid/grid.component.html, projects/igniteui-angular/src/lib/grids/grid/grid.pagination.spec.ts, projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.component.html, projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid.component.html
=> Hide paginator when there are no records in the grid.

projects/igniteui-angular/src/lib/core/styles/components/grid/_excel-filtering-theme.scss, projects/igniteui-angular/src/lib/core/styles/typography/_typography.scss, projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-column-moving.component.html, projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-sorting.component.html
=> fix(grid-esf): moving and sorting headers should be capitalized

projects/igniteui-angular/src/lib/grids/cell.component.ts, projects/igniteui-angular/src/lib/grids/column.component.ts, projects/igniteui-angular/src/lib/grids/grid-base.component.ts, projects/igniteui-angular/src/lib/grids/grid-mrl-navigation.service.ts, projects/igniteui-angular/src/lib/grids/grid/grid-mrl-keyboard-nav.spec.ts, src/app/grid-multi-row-layout/grid-mrl.sample.html, src/app/grid-multi-row-layout/grid-mrl.sample.ts
The following issues have been resolved and automated:
1. When column is pinned runtime tab navigation does not follow correct tab sequence.
2. When column is moved via API tab navigation does not follow correct tab sequence.
3. Ctrl+Arrow Right/Left does not work in grid with horizontal virtualization.
=> Addition mrl navigation integration scenarios implementation + tests

projects/igniteui-angular/src/lib/core/styles/components/grid/_grid-component.scss, projects/igniteui-angular/src/lib/core/styles/components/grid/_grid-theme.scss, projects/igniteui-angular/src/lib/grids/grid/grid.component.html, projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.component.html
=> Header borders when row drag is enabled

projects/igniteui-angular/src/lib/grids/filtering/grid-filtering-row.component.ts
=> Check if filter row is visible when showHideArrowButtons - 7.2.x

projects/igniteui-angular/src/lib/grids/filtering/grid-filtering-row.component.ts
=> Check if filter row is visible when showHideArrowButtons

projects/igniteui-angular/src/lib/grids/grid/row-drag.directive.spec.ts
=> Row drag tests

projects/igniteui-angular/src/lib/grids/column.component.ts, projects/igniteui-angular/src/lib/grids/grid-base.component.ts, projects/igniteui-angular/src/lib/grids/grid-header-group.component.ts, projects/igniteui-angular/src/lib/grids/grid-mrl-navigation.service.ts, projects/igniteui-angular/src/lib/grids/grid/grid-mrl-keyboard-nav.spec.ts, projects/igniteui-angular/src/lib/grids/grid/grid.multi-row-layout.integration.spec.ts
=> fix(mrl-pinning): Fix pinning width not being calculated correctly when there are multi row layouts.

projects/igniteui-angular/src/lib/grids/grid/row-drag.directive.spec.ts, projects/igniteui-angular/src/lib/grids/row-drag.directive.ts
=> Remove drag ghost when onRowDragStarted is canceled

projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-search.component.ts, projects/igniteui-angular/src/lib/grids/grid/grid-filtering-ui.spec.ts, projects/igniteui-angular/src/lib/test-utils/grid-functions.spec.ts
=> Recalculate igxfor sizes for excel style search list on after view init

projects/igniteui-angular/src/lib/grids/column.component.ts, projects/igniteui-angular/src/lib/grids/grid-mrl-navigation.service.ts, projects/igniteui-angular/src/lib/grids/grid/grid-mrl-keyboard-nav.spec.ts
=> fix(mrl-nav): Fix Multi-Row Layout navigation up/down when pinned columns and unpinned are not in order.

projects/igniteui-angular/src/lib/grids/grid-base.component.ts, projects/igniteui-angular/src/lib/grids/grid/grid.component.spec.ts, projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.spec.ts, projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.virtualization.spec.ts
Closes #3950
Closes #3949
Closes #4745
=> fix(grid): Fix calculate height when initially grid has no data #3950

projects/igniteui-angular/src/lib/directives/filter/filter.directive.ts, projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-search.component.ts, projects/igniteui-angular/src/lib/grids/filtering/excel-style/grid.excel-style-filtering.component.ts, projects/igniteui-angular/src/lib/grids/grid/grid-filtering-ui.spec.ts
=> fix(esf): Do not treat SelectAll as a search result #4020

projects/igniteui-angular/src/lib/data-operations/filtering-condition.ts, projects/igniteui-angular/src/lib/data-operations/filtering-strategy.ts, projects/igniteui-angular/src/lib/grids/filtering/excel-style/grid.excel-style-filtering.component.html, projects/igniteui-angular/src/lib/grids/filtering/excel-style/grid.excel-style-filtering.component.ts, projects/igniteui-angular/src/lib/grids/grid/grid-filtering-ui.spec.ts
=> Add 'in' condition to improve filtering performance

projects/igniteui-angular/src/lib/grids/filtering/excel-style/grid.excel-style-filtering.component.ts, projects/igniteui-angular/src/lib/grids/grid/grid-filtering-ui.spec.ts
=> Emit onColumnVisibilityChanged when hiding a column through ESF UI. #4765

CHANGELOG.md, projects/igniteui-angular/src/lib/grids/grid/grid.component.html, projects/igniteui-angular/src/lib/grids/grid/grid.pagination.spec.ts, projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.component.html, projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid.component.html
=> #4666 Hide pager when there are no records in the grid.

projects/igniteui-angular/src/lib/grids/filtering/grid-filtering-row.component.ts, projects/igniteui-angular/src/lib/grids/grid/grid-filtering-ui.spec.ts
=> Show chip arrows in filterRow if column is filtered - 7.2.x

projects/igniteui-angular/src/lib/grids/filtering/grid-filtering-row.component.ts, projects/igniteui-angular/src/lib/grids/grid/grid-filtering-ui.spec.ts
=> Show chip arrows in filterRow if column is filtered - 7.3.x

projects/igniteui-angular/src/lib/grids/grid-base.component.ts, projects/igniteui-angular/src/lib/grids/grid/grid-summary.spec.ts, projects/igniteui-angular/src/lib/grids/grid/grid.component.spec.ts, projects/igniteui-angular/src/lib/grids/summaries/grid-summary.service.ts, projects/igniteui-angular/src/lib/grids/summaries/summary-cell.component.ts, projects/igniteui-angular/src/lib/grids/summaries/summary-row.component.html, projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid-summaries.spec.ts, projects/igniteui-angular/src/lib/test-utils/helper-utils.spec.ts
=> Condense Grid summaries 

projects/igniteui-angular/src/lib/core/styles/components/grid/_excel-filtering-theme.scss
=> Set display property of esf class to enable animations - 7.2.x

projects/igniteui-angular/src/lib/core/styles/components/grid/_excel-filtering-theme.scss
=> Set display property of esf class to enable animations - 7.3.x

projects/igniteui-angular/src/lib/grids/grid-base.component.ts, projects/igniteui-angular/src/lib/grids/grid/grid-summary.spec.ts, projects/igniteui-angular/src/lib/grids/grid/grid.component.spec.ts, projects/igniteui-angular/src/lib/grids/summaries/grid-summary.service.ts, projects/igniteui-angular/src/lib/grids/summaries/summary-cell.component.ts, projects/igniteui-angular/src/lib/grids/summaries/summary-row.component.html, projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid-summaries.spec.ts, projects/igniteui-angular/src/lib/test-utils/helper-utils.spec.ts
=> Condense Grid summaries --7.2.x

extras/docs/themes/sassdoc/index.js, extras/docs/themes/sassdoc/views/index.hbs, extras/docs/themes/typedoc/src/layouts/default.hbs
=> fix(api-docs): show doc links related to the documentation lang

projects/igniteui-angular/src/lib/grids/cell.component.ts, projects/igniteui-angular/src/lib/grids/column.component.ts, projects/igniteui-angular/src/lib/grids/grid-base.component.ts, projects/igniteui-angular/src/lib/grids/grid-column-resizing.service.ts, projects/igniteui-angular/src/lib/grids/grid-mrl-navigation.service.ts, projects/igniteui-angular/src/lib/grids/grid-navigation.service.ts, projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.component.ts, projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid.component.ts
1) Extracting this.column.parent && this.column.parent.columnLayout check in a getter.
2) Removing incorrect/unused imports.
=> (mrl-nav): Code review changes.

CHANGELOG.md, projects/igniteui-angular/src/lib/buttonGroup/README.md, projects/igniteui-angular/src/lib/buttonGroup/buttonGroup.component.ts, projects/igniteui-angular/src/lib/buttonGroup/buttongroup-content.component.html, projects/igniteui-angular/src/lib/buttonGroup/buttongroup.component.spec.ts, projects/igniteui-angular/src/lib/core/displayDensity.ts, projects/igniteui-angular/src/lib/core/styles/components/button-group/_button-group-theme.scss, src/app/buttonGroup/buttonGroup.sample.html
=> Implement DisplayDensity for IgxButtonGroup

projects/igniteui-angular/src/lib/grids/api.service.ts, projects/igniteui-angular/src/lib/grids/filtering/excel-style/grid.excel-style-filtering.component.ts, projects/igniteui-angular/src/lib/grids/grid/grid-filtering-ui.spec.ts
=> Cascade filter the available filter options of the Excel Style Filtering

projects/igniteui-angular/src/lib/grids/grid/grid-filtering-ui.spec.ts
=> Fix cascade filter test

projects/igniteui-angular/src/lib/core/styles/components/grid/_grid-theme.scss
=> fix(grid): scrolling mask doesn't appear right in IE11

projects/igniteui-angular/src/lib/grids/grid-base.component.ts, projects/igniteui-angular/src/lib/grids/grid/grid.component.ts, projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.component.ts, projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.spec.ts
=> Resolving null height virtualization slowdown - 7.2

projects/igniteui-angular/src/lib/grids/grid-base.component.ts, projects/igniteui-angular/src/lib/grids/grid/grid.component.ts, projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.component.ts, projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.spec.ts
=> Resolving null height virtualization slowdown - 7.3

projects/igniteui-angular/src/lib/grids/grid/grid.directives.ts, projects/igniteui-angular/src/lib/grids/grid/grid.groupby.spec.ts
=> Fix grouping comparer function not taken into account when grouping by dragging a column. 

projects/igniteui-angular/src/lib/grids/grid/grid.directives.ts, projects/igniteui-angular/src/lib/grids/grid/grid.groupby.spec.ts
=> Fix grouping comparer function not taken into account when grouping by dragging a column.

projects/igniteui-angular/src/lib/directives/autocomplete/autocomplete.directive.spec.ts, projects/igniteui-angular/src/lib/directives/toggle/toggle.directive.spec.ts, projects/igniteui-angular/src/lib/grids/grid/grid.component.spec.ts, projects/igniteui-angular/src/lib/services/overlay/overlay.ts
#4470
**NOTE:** Preferable to be tested with the mostly used browsers as well! (Chrome, Firefox, etc.)
=> Manually implement contains for clicking the positionTarget - 7.2.x

projects/igniteui-angular/src/lib/directives/autocomplete/autocomplete.directive.spec.ts, projects/igniteui-angular/src/lib/directives/toggle/toggle.directive.spec.ts, projects/igniteui-angular/src/lib/grids/grid/grid.component.spec.ts, projects/igniteui-angular/src/lib/services/overlay/overlay.ts
#4470
**NOTE:** Preferable to be tested with the mostly used browsers as well! (Chrome, Firefox, etc.)
=> Manually implement contains for clicking the positionTarget - 7.3.x

projects/igniteui-angular/src/lib/grids/column.component.ts, projects/igniteui-angular/src/lib/grids/grid-base.component.ts, projects/igniteui-angular/src/lib/grids/grid/grid-selection.spec.ts, projects/igniteui-angular/src/lib/grids/grid/grid.component.html, projects/igniteui-angular/src/lib/grids/grid/grid.component.ts, projects/igniteui-angular/src/lib/grids/grid/grid.multi-row-layout.integration.spec.ts, projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.component.ts, projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid.component.html
=> Fix errors thrown when pinning blocks when there are columns with width in percentages. 

angularDocsPostDeploy.ps1
Closes #4887
Adding PostDeploy.ps1 file necessary for azure pipeline for angular doc
=> fix(doc): Adding PostDeploy.ps1 file into the repo #4887

projects/igniteui-angular/src/lib/dialog/dialog.component.ts
=> Focus dialog element if there are no buttons 

projects/igniteui-angular/src/lib/core/styles/components/grid/_grid-component.scss, projects/igniteui-angular/src/lib/core/styles/components/grid/_grid-theme.scss, projects/igniteui-angular/src/lib/grids/grid/grid.multi-row-layout.spec.ts, src/app/grid-multi-row-layout/grid-mrl.sample.html
=> fix(grid-mrl): row editing is not correctly applied in MRL mode

projects/igniteui-angular/src/lib/drop-down/drop-down-item.component.ts
=> fix(igxSelect): Prevent igxSelect blur on drop-down-item click  #4724

projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid-base.component.ts, projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.component.ts
=> Add ContentChild decorator to DragIndicatorIconTemplate

projects/igniteui-angular/src/lib/grids/filtering/excel-style/grid.excel-style-filtering.component.ts, projects/igniteui-angular/src/lib/grids/grid/grid-filtering-ui.spec.ts
=> Fix (Blanks) selection for empty string

projects/igniteui-angular/src/lib/grids/grid-header.component.ts, projects/igniteui-angular/src/lib/grids/grid/grid-filtering-ui.spec.ts
=> Change ESF target from column header to column filter icon - 7.3.x

projects/igniteui-angular/src/lib/grids/grid-header.component.ts, projects/igniteui-angular/src/lib/grids/grid/grid-filtering-ui.spec.ts
=> Change ESF target from column header to column filter icon - 7.2.x

CHANGELOG.md, projects/igniteui-angular/src/lib/core/styles/components/grid-summary/_grid-summary-theme.scss, projects/igniteui-angular/src/lib/core/styles/print/_grid-print.scss, projects/igniteui-angular/src/lib/core/styles/print/_index.scss, projects/igniteui-angular/src/lib/core/styles/themes/_core.scss, src/styles/igniteui-theme.scss
=> feat(print-styles): improve Printing Experience

projects/igniteui-angular/src/lib/combo/combo.component.ts
=> fix(combo): fix potential combo memory leak

projects/igniteui-angular/src/lib/grids/grid-base.component.ts, projects/igniteui-angular/src/lib/grids/grid/row-drag.directive.spec.ts, projects/igniteui-angular/src/lib/grids/row-drag.directive.ts
=> Add animations to row drag (when released)

projects/igniteui-angular/src/lib/core/styles/components/input/_input-group-theme.scss, projects/igniteui-angular/src/lib/select/select-positioning-strategy.ts
=> fix(input-group): some japanese symbols don't fit the input box

projects/igniteui-angular/src/lib/grids/cell.component.ts, projects/igniteui-angular/src/lib/grids/grid-mrl-navigation.service.ts, projects/igniteui-angular/src/lib/grids/grid/grid-mrl-keyboard-nav.spec.ts, projects/igniteui-angular/src/lib/test-utils/ui-interactions.spec.ts
=> refactor(grid-mrl): Store starting selected cell and use it for keyboard nav

projects/igniteui-angular/src/lib/core/styles/components/grid/_grid-theme.scss
=> fix(grid): tree grid loading indicator not showing in IE11

angularDocsPostDeploy.ps1
=> fix(main): Adding PostDeploy.ps1 file into the repo #4887

projects/igniteui-angular/src/lib/grids/grid/grid.component.ts, projects/igniteui-angular/src/lib/grids/grid/grid.multi-row-layout.spec.ts
=> fix(Grid): hideGroupedColumns option should have no effect in MRL grid.

projects/igniteui-angular/src/lib/grids/grid-base.component.ts, projects/igniteui-angular/src/lib/grids/grid/grid.search.spec.ts
=> In search check if there is cell in edit mode 

projects/igniteui-angular/src/lib/grids/filtering/grid-filtering-row.component.ts, projects/igniteui-angular/src/lib/grids/grid-base.component.ts, projects/igniteui-angular/src/lib/grids/grid/grid-filtering-ui.spec.ts
=> Reset chips area when resizing the window

projects/igniteui-angular/src/lib/combo/combo.component.ts
=> fix(combo): fix potential combo memory leak, #4928

projects/igniteui-angular/src/lib/grids/filtering/grid-filtering-row.component.ts, projects/igniteui-angular/src/lib/grids/grid-base.component.ts, projects/igniteui-angular/src/lib/grids/grid/grid-filtering-ui.spec.ts
=> Reset chips area when resizing the window 

projects/igniteui-angular/src/lib/select/select.component.html, projects/igniteui-angular/src/lib/select/select.component.ts
=> Ensure there is no initial placeholder value #4236

CHANGELOG.md, projects/igniteui-angular/src/lib/date-picker/README.md, projects/igniteui-angular/src/lib/date-picker/date-picker.component.html, projects/igniteui-angular/src/lib/date-picker/date-picker.component.spec.ts, projects/igniteui-angular/src/lib/date-picker/date-picker.component.ts, projects/igniteui-angular/src/lib/directives/toggle/toggle.directive.ts, projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-date-expression.component.html, projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-date-expression.component.ts, projects/igniteui-angular/src/lib/grids/filtering/grid-filtering-cell.component.ts, projects/igniteui-angular/src/lib/grids/filtering/grid-filtering-row.component.html, projects/igniteui-angular/src/lib/grids/filtering/grid-filtering-row.component.ts, projects/igniteui-angular/src/lib/grids/grid/grid-filtering-ui.spec.ts, projects/igniteui-angular/src/lib/time-picker/README.md, projects/igniteui-angular/src/lib/time-picker/time-picker.component.html, projects/igniteui-angular/src/lib/time-picker/time-picker.component.spec.ts, projects/igniteui-angular/src/lib/time-picker/time-picker.component.ts, src/app/date-picker/date-picker.sample.html, src/app/time-picker/time-picker.sample.html
=> Refactoring time and date pickers a little bit

projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid-integration.spec.ts, projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid-summaries.spec.ts, projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid.component.spec.ts
=> #5005 Fixing TreeGrid tests.

projects/igniteui-angular/src/lib/icon/icon.component.ts, projects/igniteui-angular/src/lib/icon/icon.service.spec.ts, projects/igniteui-angular/src/lib/icon/icon.service.ts, projects/igniteui-angular/src/lib/icon/index.ts
=> fix(icon): HttpClientModule removed from icon service

projects/igniteui-angular/src/lib/directives/button/button.directive.spec.ts, projects/igniteui-angular/src/lib/icon/icon.component.ts, projects/igniteui-angular/src/lib/icon/icon.service.spec.ts, projects/igniteui-angular/src/lib/icon/icon.service.ts, projects/igniteui-angular/src/lib/icon/index.ts
=> fix(icon): HttpClientModule removed from icon service 

projects/igniteui-angular/src/lib/directives/button/button.directive.spec.ts, projects/igniteui-angular/src/lib/grids/grid.common.ts
=> Grid: fix sorting when quick clicking the resizer twice - 7.3.x

projects/igniteui-angular/src/lib/grids/grid.common.ts
=> Grid: fix sorting when quick clicking the resizer twice - 7.2.x

CHANGELOG.md, projects/igniteui-angular/src/lib/core/styles/components/slider/_slider-theme.scss, projects/igniteui-angular/src/lib/slider/README.md, projects/igniteui-angular/src/lib/slider/slider.component.html, projects/igniteui-angular/src/lib/slider/slider.component.spec.ts, projects/igniteui-angular/src/lib/slider/slider.component.ts, projects/igniteui-angular/src/lib/slider/thumb/thumb-slider.component.html, projects/igniteui-angular/src/lib/slider/thumb/thumb-slider.component.ts, src/app/slider/slider.sample.html, src/app/slider/slider.sample.scss, src/app/slider/slider.sample.ts
Closes #3449
Closes #4562
Closes #4559
Closes #2622
=> labels feature and refactoring SLIDER

projects/igniteui-angular/src/lib/grids/grid-header.component.ts, projects/igniteui-angular/src/lib/grids/grid/grid-filtering-ui.spec.ts
=> Change ESF target from column header to column filter icon - master

CHANGELOG.md, projects/igniteui-angular/src/lib/grids/grid-base.component.ts, projects/igniteui-angular/src/lib/grids/grid/grid-summary.spec.ts, projects/igniteui-angular/src/lib/grids/grid/grid.component.spec.ts, projects/igniteui-angular/src/lib/grids/summaries/grid-summary.service.ts
=> Recalculate summaries when row is updated

projects/igniteui-angular/src/lib/core/styles/components/input/_input-group-theme.scss, projects/igniteui-angular/src/lib/select/select-positioning-strategy.ts, src/app/input-group/input-group-child.sample.html
=> fix(input-group): japanese symbols get cut off in input and label

README.md
=> Updated readme to include other components

projects/igniteui-angular/src/lib/grids/column.component.ts
Updated the Column Formatter API doc description to better illustrate the use case in which the formatter should be used.  A short code snippet has also been provided to show customers how they can implement their own formatters.
=> Updated Column Formatter API doc

projects/igniteui-angular/src/lib/select/select.component.html, projects/igniteui-angular/src/lib/select/select.component.ts
=> Ensure there is no initial placeholder value

projects/igniteui-angular/src/lib/grids/grid.common.ts
=> Grid: fix sorting when quick clicking the resizer twice - master

projects/igniteui-angular/src/lib/directives/mask/mask.directive.ts, projects/igniteui-angular/src/lib/time-picker/time-picker.common.ts, projects/igniteui-angular/src/lib/time-picker/time-picker.component.html, projects/igniteui-angular/src/lib/time-picker/time-picker.component.spec.ts, projects/igniteui-angular/src/lib/time-picker/time-picker.component.ts, projects/igniteui-angular/src/lib/time-picker/time-picker.directives.ts, projects/igniteui-angular/src/lib/time-picker/time-picker.pipes.ts, src/app/time-picker/time-picker.sample.html, src/app/time-picker/time-picker.sample.ts
=> Time picker: add hour/minute only mode - master

projects/igniteui-angular/src/lib/core/i18n/grid-resources.ts, projects/igniteui-angular/src/lib/grids/filtering/excel-style/grid.excel-style-filtering.component.html
=> Update reset filter icon and text in ESF - 7.2.x

CHANGELOG.md
=> docs(changelog): Updating changelog with bug fixes for 7.2.12

projects/igniteui-angular/src/lib/core/i18n/grid-resources.ts, projects/igniteui-angular/src/lib/grids/filtering/excel-style/grid.excel-style-filtering.component.html
=> Update reset filter icon and text in ESF - master

CHANGELOG.md
=> docs(changelog): Updating changelog with bug fixes for 7.3.4

projects/igniteui-angular/src/lib/core/styles/components/grid-summary/_grid-summary-component.scss, projects/igniteui-angular/src/lib/core/styles/components/grid-summary/_grid-summary-theme.scss, projects/igniteui-angular/src/lib/core/styles/themes/schemas/light/_grid-summary.scss
=> Remove unused styles

projects/igniteui-angular/src/lib/grids/grid-base.component.ts, projects/igniteui-angular/src/lib/grids/grid/grid-keyBoardNav.spec.ts, projects/igniteui-angular/src/lib/grids/grid/grid.component.html, projects/igniteui-angular/src/lib/grids/grid/grid.component.spec.ts, projects/igniteui-angular/src/lib/grids/grid/grid.groupby.spec.ts, projects/igniteui-angular/src/lib/grids/grid/grid.pagination.spec.ts, projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.component.html, projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.spec.ts, projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.virtualization.spec.ts, projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid.component.html, projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid.component.spec.ts
=> fix(grid): sending proper foritemsize for vertical virt - 7.2

projects/igniteui-angular/src/lib/directives/for-of/for_of.directive.spec.ts, projects/igniteui-angular/src/lib/directives/for-of/for_of.directive.ts, projects/igniteui-angular/src/lib/grids/column.component.ts, projects/igniteui-angular/src/lib/grids/grid-base.component.ts, projects/igniteui-angular/src/lib/grids/grid/grid-row.component.html, projects/igniteui-angular/src/lib/grids/grid/grid.component.html, projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.component.html, projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.spec.ts, projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-row.component.html, projects/igniteui-angular/src/lib/grids/summaries/summary-row.component.html, projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid-row.component.html, projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid.component.html, projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid.component.spec.ts
=> feat(column): caching calcWidth getter for optimized perf 7.2

projects/igniteui-angular/src/lib/grids/api.service.ts, projects/igniteui-angular/src/lib/grids/grid-base.component.ts
=> Remove refreshSearch form the escape_editMode method

CHANGELOG.md
=> Update CHANGELOG.md with pickers new functionality

extras/docs/themes/config.json
=> docs(API) adding the new STG links

CHANGELOG.md, projects/igniteui-angular/src/lib/combo/combo.component.ts, projects/igniteui-angular/src/lib/directives/toggle/README.md, projects/igniteui-angular/src/lib/directives/toggle/toggle.directive.ts, projects/igniteui-angular/src/lib/directives/tooltip/tooltip.directive.ts, src/app/pageHeading/pageHeading.template.html
=> refactor(toggle-action): Removed the deprecated `closeOnOutsideClick` Input

projects/igniteui-angular/src/lib/core/grid-selection.ts, projects/igniteui-angular/src/lib/grids/grid-base.component.ts, projects/igniteui-angular/src/lib/grids/grid/grid.component.spec.ts
=> RowEdit + PrimaryKey warning fix - 7.3.x

projects/igniteui-angular/src/lib/time-picker/time-picker.component.spec.ts, projects/igniteui-angular/src/lib/time-picker/time-picker.component.ts
=> Outlet prop for timepicker dialog mode working correctly

extras/docs/themes/sassdoc/LICENSE, extras/docs/themes/typedoc/src/LICENSE
=> docs(themes): add MIT license for typedoc and sassdoc themes

projects/igniteui-angular/src/lib/slider/index.ts, projects/igniteui-angular/src/lib/slider/slider.common.ts, projects/igniteui-angular/src/lib/slider/slider.component.spec.ts, projects/igniteui-angular/src/lib/slider/slider.component.ts, projects/igniteui-angular/src/lib/slider/thumb/thumb-slider.component.ts, projects/igniteui-angular/src/public_api.ts, src/app/slider/slider.sample.html
=> fix(slider): prevent circular dependencies

projects/igniteui-angular/src/lib/time-picker/time-picker.component.spec.ts, projects/igniteui-angular/src/lib/time-picker/time-picker.component.ts
=> Outlet prop for timepicker dialog mode working correctly - 7.3.x

projects/igniteui-angular/src/lib/core/styles/components/date-picker/_date-picker-theme.scss, projects/igniteui-angular/src/lib/date-picker/calendar-container.component.html
=> fix(date-picker): templated date picker doesn't layout correclty

extras/docs/themes/sassdoc/index.js, package-lock.json, package.json
=> docs(API): build the docs successfuly

extras/docs/themes/typedoc/src/assets/css/elements/_infranav.sass, extras/docs/themes/typedoc/src/assets/css/elements/_search.sass, extras/docs/themes/typedoc/src/assets/css/setup/_typography.sass, projects/igniteui-angular/src/lib/core/styles/components/button/_button-theme.scss, projects/igniteui-angular/src/lib/core/styles/themes/_index.scss, projects/igniteui-angular/src/lib/core/styles/themes/schemas/dark/_snackbar.scss, projects/igniteui-angular/src/lib/core/styles/themes/schemas/light/_button-group.scss, projects/igniteui-angular/src/lib/core/styles/themes/schemas/light/_calendar.scss, projects/igniteui-angular/src/lib/core/styles/themes/schemas/light/_snackbar.scss
=> build(sassdoc): fix linting errors

projects/igniteui-angular/src/lib/grids/grid.common.ts, projects/igniteui-angular/src/lib/grids/grid/column-moving.spec.ts
=> fix(moving): Fix disablePinning input disabling moving in general instead of disabling pinning when moving a column. 

azure-pipelines.yml
=> Increase memory for 7.2.x branch

src/app/app.routing.ts, src/app/bottomnav/bottomnav.sample.html, src/app/bottomnav/bottomnav.sample.ts, src/app/routing.ts
=> fix(bottom-nav): Fixes in bottom nav dev demo - 7.3.x

projects/igniteui-angular/src/lib/grids/grid-header-group.component.html
=> fix(grid): dragGhosthost now outlets in grid header #5137

projects/igniteui-angular/src/lib/date-picker/date-picker.component.html, projects/igniteui-angular/src/lib/date-picker/date-picker.component.spec.ts, projects/igniteui-angular/src/lib/date-picker/date-picker.component.ts, projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-date-expression.component.html, projects/igniteui-angular/src/lib/grids/grid/grid-filtering-ui.spec.ts, projects/igniteui-angular/src/lib/time-picker/time-picker.component.ts
=> fix(date-picker): date picker outlet removed 

projects/igniteui-angular/src/lib/grids/grid-header-group.component.html
=> fix(grid): (master branch) dragGhostHost not outlets in grid head #5137

projects/igniteui-angular/src/lib/slider/slider.component.spec.ts, projects/igniteui-angular/src/lib/slider/slider.component.ts
=> Improve igx-slider tests --7.2.x

extras/docs/themes/sassdoc/index.js, extras/docs/themes/sassdoc/views/index.hbs, extras/docs/themes/typedoc/src/layouts/default.hbs
=> docs(API): exposing correctly the SEO header links

projects/igniteui-angular/src/lib/core/grid-selection.ts
=> fix(igx-grid): Use createRange because IE11

projects/igniteui-angular/src/lib/grids/grid/grid.component.spec.ts
=> test(grid): Adding tests for #1861 and #1858

projects/igniteui-angular/src/lib/grids/grid-base.component.ts, projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid-base.component.ts
=> Reset maxLevelHeaderDepth on initColumns

projects/igniteui-angular/src/lib/grids/grid-base.component.ts, projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid-base.component.ts
=> Reset maxLevelHeaderDepth on initColumns 

projects/igniteui-angular/src/lib/core/styles/components/progress/_progress-theme.scss
=> fix(circular progress): It should support sizes bellow 24px

projects/igniteui-angular/src/lib/grids/grid-base.component.ts
=> Always reinit pinned columns state - 7.2.x #4905

projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-cell.component.ts, projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.integration.spec.ts
=> fix(hgrid): Uncommitted rows can be expanded using Alt + Down/Right.

projects/igniteui-angular/src/lib/date-picker/date-picker.component.ts, src/app/date-picker/date-picker.sample.html, src/app/date-picker/date-picker.sample.ts
=> Date Picker: fix InvalidDate error in IE11 - 7.3.x

projects/igniteui-angular/src/lib/combo/combo.component.ts
=> Fix - IgxCombo - Move input focus handling to `onClosing`

projects/igniteui-angular/src/lib/grids/filtering/grid-filtering-row.component.html, projects/igniteui-angular/src/lib/grids/filtering/grid-filtering-row.component.ts, projects/igniteui-angular/src/lib/grids/grid/grid-filtering-ui.spec.ts, projects/igniteui-angular/src/lib/test-utils/grid-functions.spec.ts
=> fix(grid): Making filter chip toggleable by mouse click #4967

projects/igniteui-angular/src/lib/grids/filtering/grid-filtering-row.component.html, projects/igniteui-angular/src/lib/grids/filtering/grid-filtering-row.component.ts, projects/igniteui-angular/src/lib/grids/grid/grid-filtering-ui.spec.ts, projects/igniteui-angular/src/lib/test-utils/grid-functions.spec.ts
=> fix(grid): Making filter chip toggleable by mouse click 

projects/igniteui-angular/src/lib/date-picker/date-picker.component.ts, projects/igniteui-angular/src/lib/grids/cell.component.ts, projects/igniteui-angular/src/lib/grids/grid-base.component.ts, projects/igniteui-angular/src/lib/grids/grid/grid.component.ts, projects/igniteui-angular/src/lib/grids/grid/groupby-row.component.ts, projects/igniteui-angular/src/lib/time-picker/time-picker.component.ts
=> Fix undesired deprecation warning messages - 7.3.x

projects/igniteui-angular/src/lib/combo/combo.component.ts
=> Fix - IgxCombo - Move input focus handling to `onClosing` - 7.3.x

projects/igniteui-angular/src/lib/grids/grid-base.component.ts
=> Error is thrown when scrolling with rowEditable true

projects/igniteui-angular/src/lib/directives/for-of/for_of.directive.spec.ts, projects/igniteui-angular/src/lib/directives/for-of/for_of.directive.ts, src/app/virtual-for-directive/virtual-for.sample.html, src/app/virtual-for-directive/virtual-for.sample.ts
=> fix(igxForOf): Recalculate chunk size when changing itemSize #5128

projects/igniteui-angular/src/lib/directives/for-of/for_of.directive.ts, projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.navigation.spec.ts
=> fix(forOf): Fix getting scroll position for item when there is nowhere to scroll. 

projects/igniteui-angular/src/lib/core/styles/components/checkbox/_checkbox-theme.scss, projects/igniteui-angular/src/lib/core/styles/components/switch/_switch-theme.scss, projects/igniteui-angular/src/lib/core/styles/themes/schemas/light/_checkbox.scss, projects/igniteui-angular/src/lib/core/styles/themes/schemas/light/_switch.scss, projects/igniteui-angular/src/lib/core/styles/themes/schemas/shape/_checkbox.scss, projects/igniteui-angular/src/lib/core/styles/themes/schemas/shape/_switch.scss
=> style(switch): Adding ripple shape for switch component

projects/igniteui-angular/src/lib/core/styles/components/grid/_grid-component.scss, projects/igniteui-angular/src/lib/core/styles/components/grid/_grid-theme.scss, projects/igniteui-angular/src/lib/grids/grid-base.component.ts, projects/igniteui-angular/src/lib/grids/grid-header.component.ts
=> fix(grid): headers should respond better to change in height

projects/igniteui-angular/src/lib/core/styles/components/expansion-panel/_expansion-panel-theme.scss
=> fix(Expansion Panel): remove flex 1 0 0%  from the title

projects/igniteui-angular/src/lib/grids/grid.rowEdit.directive.ts, projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid-navigation.service.ts, projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.navigation.spec.ts
=> Focus button Cancel when press tab key on the last editable cell in the row -- 7.2.x

projects/igniteui-angular/src/lib/grids/grid.rowEdit.directive.ts, projects/igniteui-angular/src/lib/grids/grid/grid-mrl-keyboard-nav.spec.ts, projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid-navigation.service.ts, projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.navigation.spec.ts
=> Focus button Cancel when press tab key on the last editable cell in the row--7.3.x

projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid-navigation.service.ts, projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.navigation.spec.ts, src/app/hierarchical-grid-updating/hierarchical-grid-updating.sample.html
=> Focus  button Cancel when press tab key on the last editable cell in the row

projects/igniteui-angular/src/lib/grids/filtering/grid-filtering-row.component.ts, projects/igniteui-angular/src/lib/grids/grid/grid-filtering-ui.spec.ts
=> fix(filtering): Deselect all filter chips when changing columns 

CHANGELOG.md
=> docs(list): Update the changelog.

projects/igniteui-angular/src/lib/directives/for-of/for_of.directive.ts, projects/igniteui-angular/src/lib/directives/for-of/for_of.sync.service.ts
=> fix(forof): preventing reflows on scroll - 7.3

projects/igniteui-angular/src/lib/grids/filtering/grid-filtering-row.component.ts, projects/igniteui-angular/src/lib/grids/grid/grid-filtering-ui.spec.ts
=> fix(filtering): Deselect all filter chips when changing columns Astaev/bug5148 8.0.x

projects/igniteui-angular/src/lib/grids/grid.common.ts
=> Check owner in column moving onDragOver event

projects/igniteui-angular/src/lib/directives/for-of/for_of.directive.ts, projects/igniteui-angular/src/lib/directives/for-of/for_of.sync.service.ts
=> fix(forof): preventing reflows on scroll - 7.2

src/app/select/select.sample.ts
=> Cleanup static props in 7.3.x igxSelect samples

projects/igniteui-angular/src/lib/directives/for-of/for_of.directive.ts, projects/igniteui-angular/src/lib/directives/for-of/for_of.sync.service.ts
=> fix(forof): preventing reflows on scroll - 8.0

projects/igniteui-angular/src/lib/grids/grid/grid-filtering-ui.spec.ts, projects/igniteui-angular/src/lib/test-utils/grid-functions.spec.ts, projects/igniteui-angular/src/lib/test-utils/ui-interactions.spec.ts
=> Fixed ESF test for moving columns. #5202

projects/igniteui-angular/src/lib/expansion-panel/expansion-panel.spec.ts
=> Fix excluded test in igxExpansionPanel

projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid-navigation.service.ts, projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.navigation.spec.ts
=> Focus button Cancel when press tab key on the last editable cell in the row --master

projects/igniteui-angular/src/lib/grids/filtering/grid-filtering-row.component.ts, projects/igniteui-angular/src/lib/grids/grid/grid-filtering-ui.spec.ts
=> fix(filtering): Deselect all filter chips when changing columns #5148

projects/igniteui-angular/src/lib/directives/for-of/for_of.directive.ts
=> fix(forof): preventing reflows on scroll - master

projects/igniteui-angular/src/lib/grids/grid/grid-filtering-ui.spec.ts
=> test(filtering): Adding changeDetection in tests for grid filtering #5331

projects/igniteui-angular/src/lib/directives/template-outlet/template_outlet.directive.ts, projects/igniteui-angular/src/lib/grids/column.component.ts, projects/igniteui-angular/src/lib/grids/grid-base.component.ts, projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid-api.service.ts, projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.component.ts, projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.spec.ts, projects/igniteui-angular/src/lib/grids/hierarchical-grid/row-island.component.ts, src/app/hierarchical-grid/hierarchical-grid.sample.html, src/app/hierarchical-grid/hierarchical-grid.sample.ts
=> Adding support for changing row islands in hierarchical grid runtime (as a result of ngIf, ngFor etc.) 

projects/igniteui-angular/src/lib/directives/template-outlet/template_outlet.directive.ts, projects/igniteui-angular/src/lib/grids/column.component.ts, projects/igniteui-angular/src/lib/grids/grid-base.component.ts, projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid-api.service.ts, projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.component.ts, projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.spec.ts, projects/igniteui-angular/src/lib/grids/hierarchical-grid/row-island.component.ts, src/app/hierarchical-grid/hierarchical-grid.sample.html, src/app/hierarchical-grid/hierarchical-grid.sample.ts
=> Adding support for changing row islands in hierarchical grid runtime (as a result of ngIf, ngFor etc.)

projects/igniteui-angular/src/lib/grids/grid/grid-filtering-ui.spec.ts
Adding changeDetection in two tests for grid filtering #5331
Closes #5331
=> test(filtering): Adding changeDetection in two tests for grid filtering #5331

projects/igniteui-angular/src/lib/core/styles/components/slider/_slider-component.scss, projects/igniteui-angular/src/lib/core/styles/components/slider/_slider-theme.scss, projects/igniteui-angular/src/lib/core/styles/themes/schemas/light/_slider.scss, projects/igniteui-angular/src/lib/slider/slider.component.html, projects/igniteui-angular/src/lib/slider/slider.component.spec.ts, projects/igniteui-angular/src/lib/slider/slider.component.ts, projects/igniteui-angular/src/lib/slider/thumb/thumb-slider.component.ts, src/app/slider/slider.sample.html
Closes #4542
Closes #5219
Closes #5229
=> Slider latest spec master

projects/igniteui-angular/src/lib/grids/grid-base.component.ts, projects/igniteui-angular/src/lib/grids/grid/grid.component.ts
=> fix(grid): Move properties related to remote grid virtualization. 

projects/igniteui-angular/src/lib/grids/grid-base.component.ts, projects/igniteui-angular/src/lib/grids/grid/grid.component.ts
=> fix(grid): Move properties related to remote grid virtualization.

projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid-navigation.service.ts, projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.navigation.spec.ts
=> fix(igxHierarchicalGrid): Fix parent grid scrolling too much when pressing Ctrl + Up inside a child. 

projects/igniteui-angular/src/lib/core/styles/components/grid/_grid-component.scss, projects/igniteui-angular/src/lib/core/styles/components/grid/_grid-theme.scss, projects/igniteui-angular/src/lib/core/styles/themes/schemas/light/_grid.scss, src/styles/igniteui-theme.scss
=> Fix filtering transparency

projects/igniteui-angular/src/lib/grids/grid-header-group.component.html, projects/igniteui-angular/src/lib/grids/grid-header-group.component.ts
=> Reverting ie fix for MRL because a better one is present #4825

projects/igniteui-angular/src/lib/grids/column.component.ts, projects/igniteui-angular/src/lib/grids/grid-base.component.ts, projects/igniteui-angular/src/lib/grids/grid/grid.component.spec.ts, projects/igniteui-angular/src/lib/grids/grid/grid.component.ts, projects/igniteui-angular/src/lib/grids/grid/grid.groupby.spec.ts, projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.component.ts, projects/igniteui-angular/src/lib/grids/hierarchical-grid/row-island.component.ts, projects/igniteui-angular/src/lib/grids/watch-changes.ts
=> refactor(igx-grid): Remove rAF calls from dimension setters - master

projects/igniteui-angular/src/lib/core/styles/components/card/_card-theme.scss, projects/igniteui-angular/src/lib/core/styles/components/grid/_grid-theme.scss
=> docs(theme): fix documentation errors

CHANGELOG.md, projects/igniteui-angular/src/lib/combo/README.md, projects/igniteui-angular/src/lib/combo/combo.component.spec.ts, projects/igniteui-angular/src/lib/combo/combo.component.ts, src/app/combo/combo.sample.html, src/app/combo/combo.sample.ts
Expose combo overlay settings and allow users to pass their own
Closes #5134
=> refactor(combo): expose overlay settings

projects/igniteui-angular/src/lib/data-operations/filtering-condition.ts, projects/igniteui-angular/src/lib/grids/filtering/excel-style/grid.excel-style-filtering.component.ts, projects/igniteui-angular/src/lib/grids/grid/grid-filtering-ui.spec.ts
=> Move 'in' condition to the IgxFilteringOperand class

projects/igniteui-angular/src/lib/directives/for-of/for_of.directive.ts
… as a result of variable row sizes when scrolled to bottom.
Closes #5371
=> fix(igxFor): Update cached scroll position in case sizes have changed

projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid-crud.spec.ts, projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid-integration.spec.ts, projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid.component.ts
=> Fix adding child row to a parent with ID=0

projects/igniteui-angular/src/lib/core/styles/components/slider/_slider-theme.scss, projects/igniteui-angular/src/lib/slider/thumb/thumb-slider.component.html, projects/igniteui-angular/src/lib/slider/thumb/thumb-slider.component.ts, src/styles/igniteui-theme.scss
=> fix(slider): can't mouse move slider thumbs in IE11

projects/igniteui-angular/src/lib/combo/combo.component.html
=> fix(combo): remove second combo ripple, #5412

src/app/virtual-for-directive/virtual-for.sample.ts
=> docs(forOf): Remove unused imports in igxForOf sample.

projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid.component.html
=> fix(tree-grid): update tree-grid template to allow custom row-edit - 7.3.x

projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid.component.html
=> fix(tree-grid): update tree-grid template to allow custom row-edit - master

projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid.component.html
=> fix(tree-grid): update tree-grid template to allow custom row-edit - 8.0.x

projects/igniteui-angular/src/lib/core/styles/components/navdrawer/_navdrawer-theme.scss, projects/igniteui-angular/src/lib/core/styles/themes/schemas/light/_navdrawer.scss, projects/igniteui-angular/src/lib/core/styles/themes/schemas/shape/_navdrawer.scss
=> refactor(navdrawer): fix default border radius

projects/igniteui-angular/src/lib/core/styles/components/navdrawer/_navdrawer-theme.scss, projects/igniteui-angular/src/lib/core/styles/themes/schemas/light/_navdrawer.scss, projects/igniteui-angular/src/lib/core/styles/themes/schemas/shape/_navdrawer.scss
=> refactor(navdrawer): fix default border-radius

projects/igniteui-angular/src/lib/grids/grid/grid.component.html, projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.component.html
=> fix(grid): resolving paginator total pages issue #5469

projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-date-expression.component.html, projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-default-expression.component.html, projects/igniteui-angular/src/lib/grids/filtering/excel-style/grid.excel-style-filtering.component.html, projects/igniteui-angular/src/lib/grids/grid/grid-filtering-ui.spec.ts, projects/igniteui-angular/src/lib/test-utils/grid-functions.spec.ts
=> Add display density support for dropdowns in ESF - 7.3.x

projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-date-expression.component.html, projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-default-expression.component.html, projects/igniteui-angular/src/lib/grids/filtering/excel-style/grid.excel-style-filtering.component.html, projects/igniteui-angular/src/lib/grids/grid/grid-filtering-ui.spec.ts, projects/igniteui-angular/src/lib/test-utils/grid-functions.spec.ts
=> Add display density support for dropdowns in ESF - 8.1.x

projects/igniteui-angular/src/lib/core/styles/components/checkbox/_checkbox-theme.scss
=> fix(checkbox): ripple is not positioned correctly

projects/igniteui-angular/src/lib/grids/grid/cell.spec.ts, projects/igniteui-angular/src/lib/grids/grid/column-moving.spec.ts, projects/igniteui-angular/src/lib/grids/grid/column.spec.ts, projects/igniteui-angular/src/lib/grids/grid/grid-multi-cell-selection.spec.ts, projects/igniteui-angular/src/lib/grids/grid/grid-summary.spec.ts, projects/igniteui-angular/src/lib/grids/grid/grid.crud.spec.ts, projects/igniteui-angular/src/lib/grids/grid/grid.groupby.spec.ts, projects/igniteui-angular/src/lib/grids/grid/grid.pagination.spec.ts, projects/igniteui-angular/src/lib/grids/grid/grid.search.spec.ts, projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid-crud.spec.ts, projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid-expanding.spec.ts, projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid-indentation.spec.ts, projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid-integration.spec.ts, projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid-keyBoardNav.spec.ts, projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid-selection.spec.ts, projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid-summaries.spec.ts, src/app/grid-cellEditing/grid-cellEditing.component.ts
=> Update paging test not to throw an error

projects/igniteui-angular/src/lib/grids/grid-base.component.ts, projects/igniteui-angular/src/lib/grids/grid/column-group.spec.ts
=> fix(multi-column-headers): error is thrown when dynamically removing mch

ROADMAP.md
=> chore(*): Updating the roadmap

CHANGELOG.md
=> Updated pagination changes in change log file

projects/igniteui-angular/src/lib/grids/column.component.ts, projects/igniteui-angular/src/lib/grids/grid-base.component.ts, projects/igniteui-angular/src/lib/grids/grid-common.pipes.ts, projects/igniteui-angular/src/lib/grids/grid-pipes.module.ts, projects/igniteui-angular/src/lib/grids/grid/column-hiding.spec.ts, projects/igniteui-angular/src/lib/grids/grid/grid-selection.spec.ts, projects/igniteui-angular/src/lib/grids/grid/grid.component.html, projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.component.html, projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.integration.spec.ts, projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid.component.html, projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid.component.spec.ts
=> Hide all elements in grid's body when all columns are hidden ---7.3.x

src/app/tree-grid-load-on-demand/tree-grid-load-on-demand.sample.ts
=> Fix adding child row in Tree Grid Load on Demand dev demo

projects/igniteui-angular/src/lib/grids/grid-base.component.ts, projects/igniteui-angular/src/lib/grids/grid/row-drag.directive.spec.ts
=> fix(row-drag): un-needed horizontal scroll bar on the grid

projects/igniteui-angular/src/lib/core/styles/components/list/_list-theme.scss
=> fix(List): Allowing users to modify list-item styles by adding a custom CSS class

projects/igniteui-angular/src/lib/core/styles/components/list/_list-theme.scss
=> fix(List): Allow users to change the color of the list item by adding a custom class

projects/igniteui-angular/src/lib/grids/api.service.ts, projects/igniteui-angular/src/lib/grids/filtering/grid-filtering.service.ts, projects/igniteui-angular/src/lib/grids/grid-base.component.ts, projects/igniteui-angular/src/lib/grids/grid/column.spec.ts, projects/igniteui-angular/src/lib/grids/grid/grid.component.html, projects/igniteui-angular/src/lib/grids/grid/grid.component.ts, projects/igniteui-angular/src/lib/grids/grid/groupby-row.component.ts, projects/igniteui-angular/src/lib/test-utils/grid-samples.spec.ts
=> Clear grouping and filtering when remove a column

projects/igniteui-angular/src/lib/grids/api.service.ts, projects/igniteui-angular/src/lib/grids/filtering/grid-filtering.service.ts, projects/igniteui-angular/src/lib/grids/grid-base.component.ts, projects/igniteui-angular/src/lib/grids/grid/column.spec.ts, projects/igniteui-angular/src/lib/grids/grid/grid.component.html, projects/igniteui-angular/src/lib/grids/grid/grid.component.ts, projects/igniteui-angular/src/lib/grids/grid/groupby-row.component.ts, projects/igniteui-angular/src/lib/test-utils/grid-samples.spec.ts
=> Clear grouping and filtering when removing a column

ROADMAP.md
=> chore(calendar): Updating the roadmap

projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-search.pipe.ts, projects/igniteui-angular/src/lib/grids/grid/grid-filtering-ui.spec.ts
=> Fix ESF search pipe to include the 'false' value - 7.3.x

projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-search.pipe.ts, projects/igniteui-angular/src/lib/grids/grid/grid-filtering-ui.spec.ts
=> Fix ESF search pipe to include the 'false' value - 8.1.x

projects/igniteui-angular/src/lib/core/styles/components/grid/_excel-filtering-component.scss, projects/igniteui-angular/src/lib/grids/column.component.ts, projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-column-moving.component.ts, projects/igniteui-angular/src/lib/grids/filtering/excel-style/grid.excel-style-filtering.component.html, projects/igniteui-angular/src/lib/grids/filtering/excel-style/grid.excel-style-filtering.component.ts, projects/igniteui-angular/src/lib/grids/grid/grid-filtering-ui.spec.ts, projects/igniteui-angular/src/lib/test-utils/grid-functions.spec.ts
=> Disable 'pin' and 'move left buttons in ESF when max pin area width is reached - 7.3.x

projects/igniteui-angular/src/lib/core/styles/components/grid/_excel-filtering-component.scss, projects/igniteui-angular/src/lib/grids/column.component.ts, projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-column-moving.component.ts, projects/igniteui-angular/src/lib/grids/filtering/excel-style/grid.excel-style-filtering.component.html, projects/igniteui-angular/src/lib/grids/filtering/excel-style/grid.excel-style-filtering.component.ts, projects/igniteui-angular/src/lib/grids/grid/grid-filtering-ui.spec.ts, projects/igniteui-angular/src/lib/test-utils/grid-functions.spec.ts
=> Disable 'pin' and 'move left buttons in ESF when max pin area width is reached - 8.1.x

projects/igniteui-angular/src/lib/core/utils.ts, projects/igniteui-angular/src/lib/grids/grid/column-resizing.spec.ts, projects/igniteui-angular/src/lib/grids/grid/grid.multi-row-layout.spec.ts
=> Update evaluating of 'grid-template-rows' style to reflect how chrome 76 sets it now.

projects/igniteui-angular/src/lib/core/utils.ts, projects/igniteui-angular/src/lib/grids/grid/column-resizing.spec.ts, projects/igniteui-angular/src/lib/grids/grid/grid.multi-row-layout.spec.ts
=> test(resizing): resolving issues with chrome 76

projects/igniteui-angular/src/lib/core/utils.ts, projects/igniteui-angular/src/lib/grids/grid/column-resizing.spec.ts
=>  test(resizing): resolving issues with chrome 76 

projects/igniteui-angular/src/lib/core/styles/components/grid/_grid-theme.scss, projects/igniteui-angular/src/lib/core/styles/themes/schemas/light/_grid.scss
=> docs(Grid): Fix missing sassdocs @param

projects/igniteui-angular/src/lib/core/styles/components/grid/_grid-theme.scss, projects/igniteui-angular/src/lib/core/styles/themes/schemas/light/_grid.scss
=> docs(Grid): Fix missing @param in sassdocs and remove unnecessary properties in the light schema

CHANGELOG.md, projects/igniteui-angular/src/lib/date-picker/README.md, projects/igniteui-angular/src/lib/date-picker/date-picker.component.spec.ts, projects/igniteui-angular/src/lib/date-picker/date-picker.component.ts, projects/igniteui-angular/src/lib/grids/cell.component.html, projects/igniteui-angular/src/lib/grids/grid/cell.spec.ts, projects/igniteui-angular/src/lib/grids/tree-grid/tree-cell.component.html
=> Add date picker event onValueChanged and use it to update cell value when column type is date 

projects/igniteui-angular/src/lib/directives/button/button.directive.spec.ts, projects/igniteui-angular/src/lib/directives/button/button.directive.ts
=> Fix IgxButton has incorrect CSS class when setting new type - 7.3.x

projects/igniteui-angular/src/lib/grids/filtering/grid-filtering-row.component.ts, projects/igniteui-angular/src/lib/grids/grid/grid-filtering-ui.spec.ts
=> fix(filtering): Scroll chips before remove #5304

projects/igniteui-angular/src/lib/directives/button/button.directive.spec.ts, projects/igniteui-angular/src/lib/directives/button/button.directive.ts
=> Fix IgxButton has incorrect CSS class when setting new type - 8.1.x

projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-search.component.ts, projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-search.pipe.ts, projects/igniteui-angular/src/lib/grids/filtering/excel-style/grid.excel-style-filtering.component.ts, projects/igniteui-angular/src/lib/grids/grid/grid-filtering-ui.spec.ts
=> Disable 'apply' button in ESF when no filter results are present - 7.3.x

projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-search.component.ts, projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-search.pipe.ts, projects/igniteui-angular/src/lib/grids/filtering/excel-style/grid.excel-style-filtering.component.ts, projects/igniteui-angular/src/lib/grids/grid/grid-filtering-ui.spec.ts
=> Disable 'apply' button in ESF when no filter results are present - 8.1.x

projects/igniteui-angular/src/lib/core/styles/components/grid-summary/_grid-summary-theme.scss, projects/igniteui-angular/src/lib/core/styles/components/grid/_grid-theme.scss, projects/igniteui-angular/src/lib/core/styles/themes/schemas/light/_grid-summary.scss
=> fix(grid-summary): fix summary theme

projects/igniteui-angular/src/lib/core/styles/base/utilities/_functions.scss
=> feat(sass functions): fix --var function

.github/CONTRIBUTING.md
=> chore(*): Updating the contributing.md

projects/igniteui-angular/src/lib/grids/column.component.ts, projects/igniteui-angular/src/lib/grids/grid/grid-filtering-ui.spec.ts
=> Column cannot be pinned through ESF if top parent cannot be pinned - 7.3.x

projects/igniteui-angular/src/lib/grids/column.component.ts, projects/igniteui-angular/src/lib/grids/grid/grid-filtering-ui.spec.ts
=> Column cannot be pinned through ESF if top parent cannot be pinned - 8.1.x

CHANGELOG.md, projects/igniteui-angular/src/lib/combo/README.md, projects/igniteui-angular/src/lib/combo/combo.component.spec.ts, projects/igniteui-angular/src/lib/combo/combo.component.ts, projects/igniteui-angular/src/lib/core/utils.ts
=> feat(combo): enhance combo selection event, #5523 - 8.1.x

.travis.yml, azure-pipelines.yml
=> Remove coveralls configs 

.travis.yml, azure-pipelines.yml
=> Fix Coveralls bad response

projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.component.html
=> Removing expansion classes from the last level child

projects/igniteui-angular/src/lib/grids/cell.component.ts
=> Using of type assertion for failing typedoc build

projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-column-moving.component.ts, projects/igniteui-angular/src/lib/grids/grid/grid-filtering-ui.spec.ts
=> Move column's parent instead of column itself in ESF - 8.2.x

projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-column-moving.component.ts, projects/igniteui-angular/src/lib/grids/grid/grid-filtering-ui.spec.ts
=> Move column's parent instead of column itself in ESF - 8.1.x

projects/igniteui-angular/src/lib/grids/cell.component.ts
=> Using of type assertion for failing typedoc build - master

projects/igniteui-angular/src/lib/grids/api.service.ts
=> Update row selection if deselectRows is called onRowEdit

projects/igniteui-angular/src/lib/directives/dragdrop/dragdrop.directive.ts
=> Null reference error in IE11/Edge

projects/igniteui-angular/src/lib/core/styles/components/navdrawer/_navdrawer-theme.scss, projects/igniteui-angular/src/lib/navigation-drawer/navigation-drawer.component.spec.ts, projects/igniteui-angular/src/lib/navigation-drawer/navigation-drawer.component.ts
=> fix(navdrawer): improve the mini variant to center its icons

projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-column-moving.component.ts, projects/igniteui-angular/src/lib/grids/grid/grid-filtering-ui.spec.ts
=> Move column's parent instead of column itself in ESF - 7.3.x

projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.component.ts, projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.spec.ts, src/app/hierarchical-grid/hierarchical-grid.sample.html, src/app/hierarchical-grid/hierarchical-grid.sample.ts
=> fix(igxHierarchicalGrid): Fix for dynamically added parent columns.

projects/igniteui-angular/src/lib/directives/drag-drop/drag-drop.directive.ts
=> fix(IgxDrag/IgxDrop): IE11 and Edge fix #5639

projects/igniteui-angular/src/lib/grids/grid-toolbar.component.ts, projects/igniteui-angular/src/lib/grids/grid/grid-toolbar.spec.ts
=> Fixing grid toolbar buttons type - 7.3.x

projects/igniteui-angular/src/lib/grids/grid-toolbar.component.ts, projects/igniteui-angular/src/lib/grids/grid/grid-toolbar.spec.ts
=> Fixing grid toolbar buttons type - 8.1.x

projects/igniteui-angular/src/lib/grids/grid-toolbar.component.ts, projects/igniteui-angular/src/lib/grids/grid/grid-toolbar.spec.ts
=> Fixing grid toolbar buttons type - 8.2.x

CHANGELOG.md, projects/igniteui-angular/src/lib/dialog/README.md, projects/igniteui-angular/src/lib/dialog/dialog.component.spec.ts, projects/igniteui-angular/src/lib/dialog/dialog.component.ts, src/app/dialog/dialog.sample.css, src/app/dialog/dialog.sample.html, src/app/dialog/dialog.sample.ts
=> Dialog: Add position settings input

projects/igniteui-angular/src/lib/grids/grid/row-drag.directive.spec.ts, projects/igniteui-angular/src/lib/grids/row-drag.directive.ts
=> Deleting the last row throws error

projects/igniteui-angular/src/lib/grids/grid/row-drag.directive.spec.ts, projects/igniteui-angular/src/lib/grids/row-drag.directive.ts
=> fix(row-drag): Deleting the last row throws error

projects/igniteui-angular/src/lib/directives/tooltip/tooltip.directive.ts
=> Remove preventDefault in tooltip's touchStart event - 7.3.x

projects/igniteui-angular/src/lib/directives/tooltip/tooltip.directive.ts
=> Remove preventDefault in tooltip's touchStart event - 8.1.x

projects/igniteui-angular/src/lib/directives/tooltip/tooltip.directive.ts
=> Remove preventDefault in tooltip's touchStart event - 8.2.x

projects/igniteui-angular/src/lib/directives/tooltip/tooltip.directive.ts
=> fix(tooltip): Fixing compilation error #5671

CHANGELOG.md
=> docs(fluent-theme): Update the changelog

projects/igniteui-angular/src/lib/grids/hierarchical-grid/child-grid-row.component.ts, projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.module.ts
=> Fixing the separate imports

src/app/grid-column-moving/grid-column-moving.sample.html, src/app/grid-filter-template/grid-filter-template.sample.html, src/app/tree-grid/tree-grid.sample.html
=> Remove style z-index from grid samples

projects/igniteui-angular/src/lib/core/styles/components/calendar/_calendar-theme.scss, projects/igniteui-angular/src/lib/core/styles/components/navdrawer/_navdrawer-theme.scss, src/app/hierarchical-grid/hierarchical-grid.sample.ts, src/index.html
=> refactor(themes): update typography and a few broken styles

CHANGELOG.md, projects/igniteui-angular/migrations/update-8_2_0/changes/classes.json, projects/igniteui-angular/migrations/update-8_2_0/index.spec.ts, projects/igniteui-angular/src/lib/directives/drag-drop/README.md, projects/igniteui-angular/src/lib/directives/drag-drop/drag-drop.directive.ts
=> Add migrations for renamed interfaces. Move breaking changes for drag/drop in correct version.

projects/igniteui-angular/src/lib/grids/filtering/grid-filtering.service.ts, projects/igniteui-angular/src/lib/grids/grid/grid-filtering-ui.spec.ts
=> fix(fitlering): Close filter row when hide column #5548

projects/igniteui-angular/src/lib/data-operations/filtering-condition.ts, projects/igniteui-angular/src/lib/grids/grid/grid-filtering-ui.spec.ts
=> Should not throw error when you filter data column --7.3.x

projects/igniteui-angular/src/lib/data-operations/filtering-condition.ts, projects/igniteui-angular/src/lib/grids/grid/grid-filtering-ui.spec.ts
=> Should not throw error when you filter data column --8.1.x

projects/igniteui-angular/src/lib/data-operations/filtering-condition.ts, projects/igniteui-angular/src/lib/grids/grid/grid-filtering-ui.spec.ts
=> Should not throw error when you filter data column

projects/igniteui-angular/src/lib/icon/icon.service.ts
=> Fixing icon prerender error 8.1.x

projects/igniteui-angular/src/lib/grids/grid/grid-filtering-ui.spec.ts
=> test(esf): Trying to fix flickering test #5652 

projects/igniteui-angular/src/lib/grids/grid/grid-filtering-ui.spec.ts
=> test(esf): Trying to fix flickering test #5652

.travis.yml
=> ci(travis-ci): Bump Travis env to Ubuntu Xenial

projects/igniteui-angular/src/lib/core/styles/components/chip/_chip-theme.scss
=> docs(Chip): Update the data type for chip component border-radius from Color to String

projects/igniteui-angular/src/lib/buttonGroup/buttonGroup.component.ts, projects/igniteui-angular/src/lib/buttonGroup/buttongroup-content.component.html, projects/igniteui-angular/src/lib/buttonGroup/buttongroup.component.spec.ts, projects/igniteui-angular/src/lib/directives/button/button.directive.ts, src/app/dialog/dialog.sample.ts
=> Fix button group keyboard navigation

projects/igniteui-angular/src/lib/dialog/dialog.component.spec.ts, projects/igniteui-angular/src/lib/directives/toggle/toggle.directive.spec.ts, projects/igniteui-angular/src/lib/grids/grid/grid-filtering-ui.spec.ts, projects/igniteui-angular/src/lib/grids/tree-grid/tree-cell.component.html, projects/igniteui-angular/src/lib/time-picker/time-picker.component.spec.ts
=> Remove duplicate detectChanges

projects/igniteui-angular/src/lib/core/utils.ts, projects/igniteui-angular/src/lib/grids/cell.component.ts, projects/igniteui-angular/src/lib/grids/grid/cell.spec.ts
Related to changes made in #5464
=> perf(grids): limit cell double tap handler to just iOS #2538

projects/igniteui-angular/src/lib/core/styles/components/checkbox/_checkbox-theme.scss, projects/igniteui-angular/src/lib/core/styles/components/grid/_grid-component.scss, projects/igniteui-angular/src/lib/core/styles/components/grid/_grid-theme.scss, projects/igniteui-angular/src/lib/grids/grid/grid-row.component.html, projects/igniteui-angular/src/lib/grids/grid/grid.component.html, projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.component.html, projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-row.component.html, projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid-row.component.html, projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid.component.html
=> Move padding on the default template

projects/igniteui-angular/src/lib/carousel/carousel.component.ts, projects/igniteui-angular/src/lib/chips/chip.component.ts, projects/igniteui-angular/src/lib/drop-down/drop-down-item.base.ts, projects/igniteui-angular/src/lib/expansion-panel/expansion-panel.component.ts, projects/igniteui-angular/src/lib/grids/column.component.ts, projects/igniteui-angular/src/lib/grids/grid-base.component.ts, projects/igniteui-angular/src/lib/grids/grid/grid.component.ts, projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.component.ts, projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid.component.ts, projects/igniteui-angular/src/lib/navigation-drawer/navigation-drawer.component.ts, projects/igniteui-angular/src/lib/tabs/tabs.component.ts, projects/igniteui-angular/src/lib/toast/toast.component.ts
=> docs(*): Adding code snippets for the two-way data binding

projects/igniteui-angular/src/lib/grids/grid-base.component.ts, projects/igniteui-angular/src/lib/services/overlay/overlay.ts
=> Change the type of moduleRef param in attach method

CHANGELOG.md, projects/igniteui-angular/src/lib/chips/chip.component.html, projects/igniteui-angular/src/lib/chips/chip.component.ts, projects/igniteui-angular/src/lib/chips/chip.spec.ts, projects/igniteui-angular/src/lib/grids/filtering/advanced-filtering/advanced-filtering-dialog.component.html, projects/igniteui-angular/src/lib/grids/filtering/advanced-filtering/advanced-filtering-dialog.component.ts, projects/igniteui-angular/src/lib/grids/grid/grid-filtering-advanced.spec.ts
=> feat(IgxChip): Add new event when select animation is ended. Update the advanced filtering to use it instead.

projects/igniteui-angular/src/lib/core/styles/components/input/_input-group-theme.scss
=> fix(input): Fix required field label position in chrome

projects/igniteui-angular/src/lib/slider/slider.component.spec.ts, projects/igniteui-angular/src/lib/slider/slider.component.ts
=> fix slider thumb position and focus

projects/igniteui-angular/src/lib/combo/combo.component.spec.ts, projects/igniteui-angular/src/lib/combo/combo.component.ts
=> refactor(combo): change combo remote selection clear, add tests - 8.2.x

projects/igniteui-angular/src/lib/core/styles/components/grid/_excel-filtering-theme.scss, projects/igniteui-angular/src/lib/grids/filtering/excel-style/grid.excel-style-filtering.component.ts
=> fix(grid): Start using AutoPositionStrategy #5773

projects/igniteui-angular/src/lib/slider/slider.component.html
=> fix(slider): visualizing slider labels values correctly

projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.selection.spec.ts, projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-row.component.html, projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-row.component.ts
=> fix(igxHierarchicalGrid): stopPropagation on expander click.

projects/igniteui-angular/src/lib/directives/for-of/for_of.directive.ts, projects/igniteui-angular/src/lib/grids/grid/grid.component.spec.ts, src/app/grid-remote-virtualization/grid-remote-virtualization.sample.html, src/app/grid-remote-virtualization/grid-remote-virtualization.sample.ts, src/app/shared/remote.service.ts
=> fix(igxGrid): If set data is null/undefined update views accordingly.

projects/igniteui-angular/src/lib/grids/filtering/advanced-filtering/advanced-filtering-dialog.component.html, projects/igniteui-angular/src/lib/grids/filtering/advanced-filtering/advanced-filtering-dialog.component.ts
=> Fix condition select position strategy

projects/igniteui-angular/src/lib/calendar/calendar-base.ts, projects/igniteui-angular/src/lib/calendar/calendar.component.ts
=> Fix issues around calendar selection API #5859

projects/igniteui-angular/src/lib/grids/grid-base.component.ts
=> Fix dynamically changing the columns not being detected by the grid. 

projects/igniteui-angular/src/lib/buttonGroup/buttonGroup.component.ts, projects/igniteui-angular/src/lib/grids/column.component.ts, projects/igniteui-angular/src/lib/grids/grid-base.component.ts, projects/igniteui-angular/src/lib/grids/grid/grid.component.ts
=> docs(*): validating some comments for typedoc export

projects/igniteui-angular/src/lib/grids/cell.component.ts, projects/igniteui-angular/src/lib/grids/grid/cell.spec.ts
=> Update row transaction value check #5855

projects/igniteui-angular/src/lib/combo/combo.component.html, projects/igniteui-angular/src/lib/combo/combo.component.ts
=> fix(combo): correct combo label position when no placeholder is specified

projects/igniteui-angular/src/lib/grids/grid/grid.component.ts, projects/igniteui-angular/src/lib/grids/grid/grid.directives.ts, projects/igniteui-angular/src/lib/grids/grid/grid.groupby.spec.ts, projects/igniteui-angular/src/test.ts
=> Fixes issue with grouping by a column with a blank field

projects/igniteui-angular/src/lib/directives/for-of/for_of.directive.spec.ts, projects/igniteui-angular/src/lib/grids/grid/column-resizing.spec.ts, projects/igniteui-angular/src/lib/grids/grid/grid-cell-selection.spec.ts, projects/igniteui-angular/src/lib/grids/grid/grid-filtering-advanced.spec.ts, projects/igniteui-angular/src/lib/grids/grid/grid-filtering-ui.spec.ts, projects/igniteui-angular/src/lib/grids/grid/grid-summary.spec.ts, projects/igniteui-angular/src/lib/grids/grid/grid.component.spec.ts, projects/igniteui-angular/src/lib/grids/grid/grid.groupby.spec.ts, projects/igniteui-angular/src/lib/grids/grid/grid.pagination.spec.ts, projects/igniteui-angular/src/lib/grids/grid/grid.search.spec.ts, projects/igniteui-angular/src/lib/grids/grid/row-drag.directive.spec.ts, projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.integration.spec.ts, projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.navigation.spec.ts, projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.spec.ts, projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.virtualization.spec.ts, projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid-expanding.spec.ts, projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid-search.spec.ts, projects/igniteui-angular/src/lib/test-utils/configure-suite.ts, projects/igniteui-angular/src/lib/test-utils/helper-utils.spec.ts
=> chore(*): Moving resizeObserverIgnoreError in configureTestSuite.

projects/igniteui-angular/src/lib/tabs/tab-item.component.ts, projects/igniteui-angular/src/lib/tabs/tabs-group.component.ts, projects/igniteui-angular/src/lib/tabs/tabs.common.ts, projects/igniteui-angular/src/lib/tabs/tabs.component.ts
=> Add resize observers for tabs

CHANGELOG.md, projects/igniteui-angular/src/lib/core/styles/components/highlight/highlight-component.scss, projects/igniteui-angular/src/lib/core/styles/components/highlight/highlight-theme.scss, projects/igniteui-angular/src/lib/core/styles/themes/_core.scss, projects/igniteui-angular/src/lib/core/styles/themes/_index.scss, projects/igniteui-angular/src/lib/core/styles/themes/schemas/dark/_highlight.scss, projects/igniteui-angular/src/lib/core/styles/themes/schemas/dark/_index.scss, projects/igniteui-angular/src/lib/core/styles/themes/schemas/light/_highlight.scss, projects/igniteui-angular/src/lib/core/styles/themes/schemas/light/_index.scss, projects/igniteui-angular/src/lib/core/styles/themes/schemas/round-light/_index.scss, projects/igniteui-angular/src/lib/core/styles/themes/schemas/square-light/_index.scss, projects/igniteui-angular/src/lib/directives/text-highlight/text-highlight.directive.spec.ts, projects/igniteui-angular/src/lib/directives/text-highlight/text-highlight.directive.ts, src/styles/igniteui-theme.scss
=> feat(highlight): replace inline styles with theme

projects/igniteui-angular/src/lib/grids/grid/grid.pagination.spec.ts, projects/igniteui-angular/src/lib/grids/grid/grid.pipes.ts, projects/igniteui-angular/src/lib/test-utils/grid-samples.spec.ts
=> Check if data is undefined in the paging pipe

projects/igniteui-angular/src/lib/core/styles/components/grid/_grid-theme.scss
=> fix(grid): edited text in row editing gets cut

projects/igniteui-angular/src/lib/core/styles/themes/schemas/dark/_grid.scss, projects/igniteui-angular/src/lib/core/styles/themes/schemas/light/_grid.scss
=> fix(grid): hovering selected row in dark theme is white

projects/igniteui-angular/src/lib/grids/grid/grid-filtering-ui.spec.ts
=> Simplify filter-row chip scroll test - 8.2.x

projects/igniteui-angular/src/lib/slider/slider.component.html, projects/igniteui-angular/src/lib/slider/slider.component.spec.ts, projects/igniteui-angular/src/lib/slider/slider.component.ts, src/app/slider/slider.sample.html, src/app/slider/slider.sample.scss, src/app/slider/slider.sample.ts
=> feat(slider): allow continuous behavior when labels view enabled

projects/igniteui-angular/src/lib/grids/grid-base.component.ts, projects/igniteui-angular/src/lib/grids/grid/grid-row-selection.spec.ts, projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.selection.spec.ts, projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid-selection.spec.ts
=> Header row selector should be disabled in single selection mode

projects/igniteui-angular/src/lib/core/styles/components/chip/_chip-theme.scss, projects/igniteui-angular/src/lib/core/styles/themes/schemas/light/_chip.scss
Expose two new properties which help to easily change the color of the
remove icon in the chip component
Closes #5689
=> feat(chip): Improve color changing capability

projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid-search.spec.ts
=> Fix Tree Grid search flickering tests - 8.2.x

projects/igniteui-angular/src/lib/grids/grid-base.component.ts, projects/igniteui-angular/src/lib/grids/grid/grid-keyBoardNav.spec.ts
=> Fix navigateTo so that it works when passing both row and column index.

projects/igniteui-angular/src/lib/grids/grid-common.pipes.ts, projects/igniteui-angular/src/lib/grids/grid/grid-summary.spec.ts, projects/igniteui-angular/src/lib/grids/grid/grid.component.ts, projects/igniteui-angular/src/lib/grids/grid/grid.pipes.ts, projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.component.ts, projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid.component.spec.ts, projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid.component.ts, projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid.pipes.ts
=> Check if grid data is undefined

projects/igniteui-angular/migrations/update-8_2_3/changes/theme-props.json, projects/igniteui-angular/migrations/update-8_2_3/index.spec.ts
=> Carousel buttons shadow migrations fix 

projects/igniteui-angular/src/lib/grids/grid-base.component.ts
=> fix(grid): instantiate observer and tmpOutlets

projects/igniteui-angular/src/lib/calendar/days-view/daysview-navigation.service.ts, projects/igniteui-angular/src/lib/calendar/months-view/months-view.component.ts, projects/igniteui-angular/src/lib/core/styles/components/calendar/_calendar-component.scss, projects/igniteui-angular/src/lib/core/styles/components/calendar/_calendar-theme.scss
=> fix(calendar): fix kb navigation IE #5895

projects/igniteui-angular/src/lib/calendar/days-view/daysview-navigation.service.ts, projects/igniteui-angular/src/lib/calendar/months-view/months-view.component.ts, projects/igniteui-angular/src/lib/core/styles/components/calendar/_calendar-component.scss, projects/igniteui-angular/src/lib/core/styles/components/calendar/_calendar-theme.scss
=> Fix calendar  kb navigation IE #5895

CHANGELOG.md, projects/igniteui-angular/src/lib/grids/grid-header-group.component.html, projects/igniteui-angular/src/lib/grids/grid-header.component.html
=> Add title attribute to column header - 8.1.x

projects/igniteui-angular/src/lib/calendar/calendar-base.ts, projects/igniteui-angular/src/lib/calendar/calendar-multi-view.component.spec.ts, projects/igniteui-angular/src/lib/calendar/calendar.component.spec.ts, projects/igniteui-angular/src/lib/calendar/calendar.component.ts
=> fix(calendar): Fix selection with ngModel #6015

CHANGELOG.md
=> Access all grid data from each summary 

CHANGELOG.md
=> Access all grid data from each summary

projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid-navigation.service.ts, projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.navigation.spec.ts
=> fix(igxHierarchicalGrid): Fix navigation with tab is not correct #4780

projects/igniteui-angular/src/lib/grids/grid/grid-mrl-keyboard-nav.spec.ts
Fixing flickering test - navigateTo method should work in multi-row layout grid
=> chore(*): Fixing flickering test.

projects/igniteui-angular/migrations/migration-collection.json, projects/igniteui-angular/migrations/update-8_2_6/index.spec.ts, projects/igniteui-angular/migrations/update-8_2_6/index.ts
=> Add migration for IgxPaginator

projects/igniteui-angular/src/lib/grids/filtering/base/grid-filtering-cell.component.ts, projects/igniteui-angular/src/lib/grids/filtering/base/grid-filtering-row.component.ts, projects/igniteui-angular/src/lib/grids/grid-base.directive.ts, projects/igniteui-angular/src/lib/grids/grid/grid-filtering-ui.spec.ts, src/app/grid-filtering/grid-filtering.sample.ts
=> Should close filter row when setting filterMode to excelStyleFilter - master

projects/igniteui-angular/src/lib/directives/autocomplete/autocomplete.directive.ts, src/app/grid/grid.sample.html
=> fix(autocomplete): fix autocomplete to compile w/ --aot=true, 8.1.x

projects/igniteui-angular/src/lib/directives/autocomplete/autocomplete.directive.ts, src/app/grid/grid.sample.html
=> fix(autocomplete): fix autocomplete to compile w/ --aot=true, 9.0.x

projects/igniteui-angular/src/lib/core/styles/components/switch/_switch-theme.scss
=> fix(switch): incorrect thumb position

projects/igniteui-angular/src/lib/directives/for-of/for_of.directive.ts
=> Fix igxForOf updating heightCache before the views are being updated. 

projects/igniteui-angular/migrations/update-8_2_6/index.spec.ts, projects/igniteui-angular/migrations/update-8_2_6/index.ts
=> Migrate paginator component theme path in import statement

projects/igniteui-angular/src/lib/grids/filtering/excel-style/grid.excel-style-filtering.component.ts
=> Register the filtering svg icons when using external Excel style filtering

CHANGELOG.md, projects/igniteui-angular/src/lib/directives/drag-drop/drag-drop.directive.ts, projects/igniteui-angular/src/lib/grids/grid-base.component.ts, projects/igniteui-angular/src/lib/grids/grid/grid-row.component.html, projects/igniteui-angular/src/lib/grids/grid/row-drag.directive.spec.ts, projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.component.ts, projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-row.component.html, projects/igniteui-angular/src/lib/grids/row-drag.directive.ts, projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid-row.component.html, src/app/grid-row-draggable/grid-row-draggable.sample.html, src/app/hierarchical-grid/hierarchical-grid.sample.html
#6081  
Additional information (check all that apply):
=> feat(row-drag): Adding igxDragCustomGhost directive #6081

projects/igniteui-angular/schematics/ng-add/index.spec.ts, projects/igniteui-angular/schematics/ng-add/index.ts, projects/igniteui-angular/schematics/utils/dependency-handler.ts
=> fix(schematics): check polyfill in default project #6017

projects/igniteui-angular/src/lib/core/styles/components/progress/_progress-component.scss, projects/igniteui-angular/src/lib/core/styles/components/progress/_progress-theme.scss, projects/igniteui-angular/src/lib/progressbar/circularbar.component.spec.ts
=> fix(progress-bar): revert change to progress-bar styles

projects/igniteui-angular/src/lib/date-picker/date-picker.component.ts
=> Remove duplicate call to onChangeCalback in handleSelection

projects/igniteui-angular/src/lib/grids/column.component.ts, projects/igniteui-angular/src/lib/grids/grid/column-group.spec.ts
=> Fix error when delete child column from a column group

projects/igniteui-angular/src/lib/services/overlay/overlay.spec.ts, projects/igniteui-angular/src/lib/services/overlay/scroll/absolute-scroll-strategy.ts
=> Fix overlay absolute scroll strategy unnecessary position calls

projects/igniteui-angular/src/lib/date-picker/date-picker.component.spec.ts, projects/igniteui-angular/src/lib/date-picker/date-picker.component.ts, projects/igniteui-angular/src/lib/select/select.component.spec.ts, projects/igniteui-angular/src/lib/select/select.component.ts, projects/igniteui-angular/src/lib/time-picker/time-picker.component.spec.ts, projects/igniteui-angular/src/lib/time-picker/time-picker.component.ts
=> Implement setDisableState in select, date-picker & time-picker

azure-pipelines.yml
=> chore(*): set node.js to version 11; gulp 3 incompatibility

projects/igniteui-angular/src/lib/directives/for-of/for_of.directive.ts
=> fix(forOf): Updating heightCache after the view is updated. #6058

projects/igniteui-angular/src/lib/grids/columns/column.component.ts, projects/igniteui-angular/src/lib/grids/grid/grid.component.ts, projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.component.ts, projects/igniteui-angular/src/lib/grids/hierarchical-grid/row-island-api.service.ts, projects/igniteui-angular/src/lib/grids/hierarchical-grid/row-island.component.ts, projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid.component.ts, projects/igniteui-angular/src/lib/grids/watch-changes.ts
=> fix(column): Added property decorator for column component to watch for changes in column properties #6004

projects/igniteui-angular/src/lib/carousel/carousel.component.spec.ts, projects/igniteui-angular/src/lib/carousel/carousel.component.ts, src/app/carousel/carousel.sample.html, src/app/carousel/carousel.sample.ts
=> mouseleave should not trigger play when the carousel is paused by code

projects/igniteui-angular/src/lib/core/styles/themes/_index.scss
=> Fix global elevation and roundness for fluent theme

projects/igniteui-angular/src/lib/core/styles/themes/_index.scss
=> fix(fluent-theme): fix global roundness and elevations

projects/igniteui-angular/src/lib/core/styles/components/slider/_slider-theme.scss, projects/igniteui-angular/src/lib/slider/slider.component.spec.ts, projects/igniteui-angular/src/lib/slider/slider.component.ts
=> feat(slider): Fix slider position inside grid cell

src/app/app.module.ts
=> Resolve merge conflict in app.module.ts

projects/igniteui-angular/src/lib/grids/grid/grid-filtering-advanced.spec.ts
=> Fix failing Advanced filtering test

projects/igniteui-angular/src/lib/grids/columns/column.component.ts
=> fix(igxGrid): Add check in case setter is called before grid is init.

projects/igniteui-angular/src/lib/directives/radio/radio-group.directive.spec.ts, projects/igniteui-angular/src/lib/directives/radio/radio-group.directive.ts, projects/igniteui-angular/src/lib/radio/radio.component.html, projects/igniteui-angular/src/lib/radio/radio.component.ts, src/app/radio/radio.sample.css, src/app/radio/radio.sample.html, src/app/radio/radio.sample.ts
=> fix(igx-radio): Initial selection with falsy values

projects/igniteui-angular/src/lib/directives/drag-drop/drag-drop.directive.ts
=> fix(dragDrop): Fix drag directive not positioning/transitioning ghost correctly when the page is scrolled.

projects/igniteui-angular/src/lib/directives/drag-drop/drag-drop.directive.ts
=> fix(dragDrop): Fix drag directive not positioning/transitioning ghost correctly when the page is scrolled. 

projects/igniteui-angular/src/lib/grids/grid-navigation.service.ts
=> fix(igxGrid): If row is in edit mode prevent navigation outside it.

projects/igniteui-angular/src/lib/grids/grid/grid.details.pipe.ts
=> fix(*): resolving issue with imports #6285

projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-cell.component.ts
=> fix(hgrid): Fix cell selection with keyboard navigation #6216

projects/igniteui-angular/src/lib/drop-down/drop-down.component.spec.ts, projects/igniteui-angular/src/lib/drop-down/drop-down.component.ts
=> fix(drop-down): properly overwrite selection w/ onSelection args, #6208

projects/igniteui-angular/src/lib/grids/grid/grid-summary.spec.ts, projects/igniteui-angular/src/lib/grids/summaries/grid-summary.service.ts
=> Fix custom summaries container height

projects/igniteui-angular/src/lib/grids/grid-base.component.ts
=> Reset column width to the default or calculated width

projects/igniteui-angular/src/lib/select/select-item.component.ts
=> Use textContent instead of innerText  #6273

projects/igniteui-angular/src/lib/select/select-item.component.ts
=> Use textContent instead of innerText 

projects/igniteui-angular/src/lib/core/styles/themes/schemas/dark/_highlight.scss, projects/igniteui-angular/src/lib/core/styles/themes/schemas/light/_highlight.scss
=> fix(highlight): resting color is the same as row selected background

projects/igniteui-angular/src/lib/grids/filtering/advanced-filtering/advanced-filtering-dialog.component.ts, projects/igniteui-angular/src/lib/grids/grid-base.component.ts
=> fix(grid): Prevent af dialog from scrolling #6125

projects/igniteui-angular/src/lib/grids/grid-base.directive.ts
=> Handle details views participating in cell selection #6233

projects/igniteui-angular/src/lib/date-picker/date-picker.component.spec.ts, projects/igniteui-angular/src/lib/date-picker/date-picker.component.ts, projects/igniteui-angular/src/lib/services/overlay/overlay.ts, projects/igniteui-angular/src/lib/time-picker/time-picker.common.ts, projects/igniteui-angular/src/lib/time-picker/time-picker.component.spec.ts, projects/igniteui-angular/src/lib/time-picker/time-picker.component.ts
=> Manage input focus on outside click

projects/igniteui-angular/src/lib/grids/grid-base.component.ts, projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.component.ts
=> Fix editRow banner positioning when grid rows are less than 2 v.8.2.x

projects/igniteui-angular/src/lib/grids/grid-base.component.ts, projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.component.ts
=> Fix editRow banner positioning when grid rows are less than 2 v.8.1.x

projects/igniteui-angular/src/lib/services/excel/excel-exporter-grid.spec.ts, projects/igniteui-angular/src/lib/services/excel/excel-exporter.spec.ts, projects/igniteui-angular/src/lib/services/excel/test-data.service.spec.ts, projects/igniteui-angular/src/lib/services/exporter-common/base-export-service.ts
Fixed index of last pinned column. Awaiting async methods.
Closes #6224
=> Fixed index of last pinned column & awaiting async methods

projects/igniteui-angular/src/lib/grids/hierarchical-grid/child-grid-row.component.ts
=> fix(hGrid): Fix deleting a filter chip in a child grid #6268

projects/igniteui-angular/src/lib/carousel/carousel.component.ts, projects/igniteui-angular/src/lib/select/select-item.component.ts
=> fix(ssr): Fix Carousel SSR rendering 

projects/igniteui-angular/src/lib/grids/grid-base.directive.ts, projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.component.ts
Revert a fix for the hierarchical grid that destabilize test execution.
=> fix(grid): revert change parentRowOutlet to return outletDirective #4728

projects/igniteui-angular/src/lib/grids/grid-base.component.ts, projects/igniteui-angular/src/lib/grids/grid/grid.component.ts, projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid-base.component.ts, projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.component.ts, projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid.component.ts
=> Add contentChild decorator to dragIndicatorIconTemplate in HGrid v.8.2

projects/igniteui-angular/src/lib/data-operations/data-util.ts, projects/igniteui-angular/src/lib/grids/filtering/advanced-filtering/advanced-filtering-dialog.component.ts, projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-default-expression.component.ts, projects/igniteui-angular/src/lib/grids/filtering/grid-filtering-row.component.ts, projects/igniteui-angular/src/lib/grids/grid/grid-filtering-advanced.spec.ts
=> fix(adv-filtering): transforming search value based on column type #6257

projects/igniteui-angular/package.json
=> fix(schematics): update devDependency to latest CLI version, #6357

projects/igniteui-angular/src/lib/services/csv/csv-exporter-grid.spec.ts, projects/igniteui-angular/src/lib/services/csv/csv-verification-wrapper.spec.ts, projects/igniteui-angular/src/lib/services/excel/excel-exporter-grid.spec.ts, projects/igniteui-angular/src/lib/services/excel/test-data.service.spec.ts, projects/igniteui-angular/src/lib/services/exporter-common/base-export-service.ts
(cherry picked from commit 113aee596d26b8af97676309cad565379fabbf79)
Closes #6258
=> fix(grid): Export only filtered data #6258

projects/igniteui-angular/src/lib/grids/grid/grid-collapsible-columns.spec.ts, projects/igniteui-angular/src/lib/grids/grid/grid-filtering-ui.spec.ts, projects/igniteui-angular/src/lib/grids/grid/grid.groupby.spec.ts
=> Fix failing tests for dates 

projects/igniteui-angular/src/lib/grids/grid/grid-filtering-ui.spec.ts, projects/igniteui-angular/src/lib/grids/grid/grid.groupby.spec.ts
=> Fix failing tests for dates - 8.2

projects/igniteui-angular/src/lib/grids/grid/grid-filtering-ui.spec.ts, projects/igniteui-angular/src/lib/grids/grid/grid.groupby.spec.ts
=> Fix failing tests for dates - 8.1

projects/igniteui-angular/src/lib/grids/grid-base.directive.ts, projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.component.ts
=> fix(revert): revert change of PR #6376

projects/igniteui-angular/src/lib/core/grid-selection.ts, projects/igniteui-angular/src/lib/grids/grid/grid-row-selection.spec.ts
=> fix(grid): Selecting only filtered rows #6260

projects/igniteui-angular/src/lib/grids/grid-navigation.service.ts, projects/igniteui-angular/src/lib/grids/grid/grid-row-editing.spec.ts, projects/igniteui-angular/src/lib/test-utils/grid-samples.spec.ts
=> Should not throw error when row edit template is empty -- 8.2.x

projects/igniteui-angular/src/lib/grids/row-drag.directive.ts
=> RowDrag ghost is misplaced in HierarchicalGrid - 8.2.x

ROADMAP.md
=> chore(*): Updating Roadmap Milestone 10 Status

projects/igniteui-angular/src/lib/grids/grid-base.component.ts, projects/igniteui-angular/src/lib/grids/grid/grid.component.html, projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.component.html, projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid.component.html
=> Stop propagation when navigating form the grid outlet

projects/igniteui-angular/src/lib/grids/grid-base.component.ts
Related issue #5944
Related PR: #6418
=> Resets Vertical Scroll Position on Page Change - 8.2.x

projects/igniteui-angular/src/lib/directives/for-of/for_of.directive.ts, projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.integration.spec.ts
=> fix(igxGrid): Make throttle emit last value.

projects/igniteui-angular/karma.grid.conf.js, projects/igniteui-angular/karma.hierarchical-grid.conf.js, projects/igniteui-angular/karma.non-grid.conf.js, projects/igniteui-angular/karma.test-perf.conf.js, projects/igniteui-angular/karma.tree-grid.conf.js
=> change Travis to run with ChromeHeadless - 8.2.x

projects/igniteui-angular/karma.grid.conf.js, projects/igniteui-angular/karma.hierarchical-grid.conf.js, projects/igniteui-angular/karma.non-grid.conf.js, projects/igniteui-angular/karma.test-perf.conf.js, projects/igniteui-angular/karma.tree-grid.conf.js
=> change Travis to run with ChromeHeadless

projects/igniteui-angular/src/lib/grids/grid-base.component.ts, projects/igniteui-angular/src/lib/grids/grid/column-hiding.spec.ts
=> fix(grid): set 0px when hiding all columns #6243

projects/igniteui-angular/src/lib/grids/filtering/grid-filtering.service.ts, projects/igniteui-angular/src/lib/grids/grid-base.component.ts, projects/igniteui-angular/src/lib/grids/grid/grid-filtering-advanced.spec.ts, projects/igniteui-angular/src/lib/grids/grid/grid-filtering.spec.ts, projects/igniteui-angular/src/lib/grids/grid/grid-row-selection.spec.ts, projects/igniteui-angular/src/lib/grids/grid/grid.component.html, projects/igniteui-angular/src/lib/grids/grid/grid.pipes.ts, projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.component.html, projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid.component.html, projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid.filtering.pipe.ts, projects/igniteui-angular/src/lib/test-utils/grid-samples.spec.ts
=> Fixed filtering and advanced filtering expression tree bindings

package-lock.json, package.json, projects/igniteui-angular/package.json
=> chore(schematics): update schematics packages #6415

projects/igniteui-angular/src/lib/directives/for-of/for_of.directive.ts
=> Set value to scrollComponent scrollAmount property - 82x

projects/igniteui-angular/src/lib/directives/for-of/for_of.directive.ts
=> Set value to scrollComponent scrollAmount property - master

projects/igniteui-angular/src/lib/grids/grid-base.directive.ts, projects/igniteui-angular/src/lib/grids/grid/grid-filtering-advanced.spec.ts, projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid-keyBoardNav.spec.ts, projects/igniteui-angular/src/lib/test-utils/tree-grid-functions.spec.ts
=> Fix errors in tests treeGrid and HGrid tests

projects/igniteui-angular/src/lib/chips/chip.spec.ts
=> Refactor chip test

.travis.yml
=> Update travis.yml - 8.2.x

.travis.yml, projects/igniteui-angular/karma.conf.js
=> Update travis.yml - 8.1.x

projects/igniteui-angular/src/lib/core/styles/themes/_index.scss
=> refactor(themes): replace 0 with none for disabled elevations

projects/igniteui-angular/src/lib/drop-down/drop-down.component.html, projects/igniteui-angular/src/lib/drop-down/drop-down.component.spec.ts
=> Update dropdown containers styles 

projects/igniteui-angular/src/lib/directives/for-of/for_of.directive.ts, projects/igniteui-angular/src/lib/grids/grid/grid.master-detail.spec.ts, projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.integration.spec.ts
Reverts IgniteUI/igniteui-angular#6404
=> Revert "fix(igxGrid): Make throttle emit last value as well."

projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid-navigation.service.ts
=> fix(igxHGrid): Make sure visibleColumnIndex is not greater than columns length

projects/igniteui-angular/src/lib/chips/chips-area.spec.ts, projects/igniteui-angular/src/lib/test-utils/ui-interactions.spec.ts
=> Refactor Chips Area tests. 

projects/igniteui-angular/src/lib/combo/combo.component.html, projects/igniteui-angular/src/lib/combo/combo.component.spec.ts, projects/igniteui-angular/src/lib/combo/combo.component.ts, src/app/combo/combo.sample.html
=> Combo - properly update FormControl touched

projects/igniteui-angular/src/lib/directives/scroll-inertia/scroll_inertia.directive.spec.ts, projects/igniteui-angular/src/lib/directives/scroll-inertia/scroll_inertia.directive.ts
=> Refactor IgxScrollInertia tests.

projects/igniteui-angular/src/lib/select/select.component.html, projects/igniteui-angular/src/lib/select/select.component.spec.ts, projects/igniteui-angular/src/lib/select/select.component.ts, src/app/select/select.sample.html, src/app/select/select.sample.ts
=> Select - properly update FormControl touched

projects/igniteui-angular/src/lib/grids/grid-base.directive.ts, projects/igniteui-angular/src/lib/grids/grid/grid.component.ts
=> refactor(*): Expose virtualizationState accessor to igxTreeGrid and igxHierarchicalGrid

projects/igniteui-angular/src/lib/data-operations/filtering-expression.interface.ts, projects/igniteui-angular/src/lib/grids/filtering/advanced-filtering/advanced-filtering-dialog.component.html, projects/igniteui-angular/src/lib/grids/filtering/advanced-filtering/advanced-filtering-dialog.component.ts, projects/igniteui-angular/src/lib/grids/grid/grid-filtering-advanced.spec.ts, projects/igniteui-angular/src/lib/test-utils/grid-samples.spec.ts, src/app/grid-filtering/grid-filtering.sample.html, src/app/grid-filtering/grid-filtering.sample.ts
=> fix(adv-filtering): added header name property to filtering expression #5993

projects/igniteui-angular/src/lib/drop-down/drop-down.component.spec.ts, projects/igniteui-angular/src/lib/drop-down/drop-down.component.ts
=> Set child id onChanges

projects/igniteui-angular/src/lib/drop-down/drop-down.component.spec.ts
=> test(drop-down): update virtual for config

projects/igniteui-angular/src/lib/navigation-drawer/navigation-drawer.component.spec.ts, projects/igniteui-angular/src/lib/navigation-drawer/navigation-drawer.component.ts
Host binding of the component class is fixed.
Closes #6508
=> Retain classes added through markup in IgxNavDrawer 8.2.x

projects/igniteui-angular/src/lib/navigation-drawer/navigation-drawer.component.spec.ts, projects/igniteui-angular/src/lib/navigation-drawer/navigation-drawer.component.ts
Host binding of the component class is fixed.
Closes #6508
=> Retain classes added through markup in IgxNavDrawer

projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-search.component.ts, projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-search.pipe.ts, projects/igniteui-angular/src/lib/grids/filtering/excel-style/grid.excel-style-filtering.component.ts, projects/igniteui-angular/src/lib/grids/grid/grid-filtering-ui.spec.ts
=> fix(excel-style-filtering): reverting fix made in PR5601 #6567

projects/igniteui-angular/src/lib/grids/grid/grid.component.ts
=> Only try to hide columns if collumnList contains any columns #6593

projects/igniteui-angular/migrations/common/UpdateChanges.ts, projects/igniteui-angular/migrations/common/util.ts, projects/igniteui-angular/migrations/migration-collection.json
reduce no change updates in logs & don't ignore newer projects with built-in e2e
=> Minor migration updates

ROADMAP.md
=> Chore(*)  Updating Roadmap Milestone 11

projects/igniteui-angular/src/lib/core/styles/base/utilities/_functions.scss
=> fix(themes): app not building with ng build

projects/igniteui-angular/src/lib/grids/filtering/excel-style/grid.excel-style-filtering.component.ts
Closes https://github.com/IgniteUI/igniteui-angular-samples/issues/1703
=> fix(esf): Do not focus searchInput in external filtering #1703

projects/igniteui-angular/src/public_api.ts
=> fix(carousel, paginator): export resource string #6679

CHANGELOG.md, projects/igniteui-angular/migrations/migration-collection.json, projects/igniteui-angular/migrations/update-9_0_1/changes/theme-props.json, projects/igniteui-angular/migrations/update-9_0_1/index.spec.ts, projects/igniteui-angular/migrations/update-9_0_1/index.ts, projects/igniteui-angular/src/lib/core/styles/base/utilities/_functions.scss, projects/igniteui-angular/src/lib/core/styles/themes/_core.scss, projects/igniteui-angular/src/lib/core/styles/themes/_index.scss, projects/igniteui-angular/src/lib/core/styles/typography/README.md, projects/igniteui-angular/src/lib/core/styles/typography/_typography.scss, src/styles/igniteui-theme.scss
BREAKING CHANGE: Remove $base-color from igx-typography
Closes #6695
=> fix(themes): do not set the global text color in igx-core

projects/igniteui-angular/src/lib/time-picker/time-picker.component.spec.ts, projects/igniteui-angular/src/lib/time-picker/time-picker.component.ts, src/app/time-picker/time-picker.sample.html, src/app/time-picker/time-picker.sample.ts
=> Determine initial min-max value 8.2

projects/igniteui-angular/src/lib/badge/badge.component.ts
=> docs(badge): updating igxBadge API docs for new guidelines - master

projects/igniteui-angular/src/lib/icon/icon.component.ts
=> Update docs for the igxIconComponent API

projects/igniteui-angular/src/lib/badge/badge.component.ts
=> docs(badge): updating igxBadge API docs for new guidelines - 9.0.x

projects/igniteui-angular/src/lib/chips/chip.component.ts, projects/igniteui-angular/src/lib/chips/chips-area.component.ts
=> Update docs for IgxChip and IgxChipsArea API

projects/igniteui-angular/src/lib/checkbox/checkbox.component.ts
=> docs(igxCheckbox): Update docs for the igxCheckBoxComponent API

projects/igniteui-angular/src/lib/directives/button/button.directive.ts
=> docs(igxButton): updates API Docs for the igxButton directive - 9.0.x

projects/igniteui-angular/src/lib/directives/button/button.directive.ts
=> docs(igxButton): updates API Docs for the igxButton directive

projects/igniteui-angular/src/lib/switch/switch.component.ts
=> docs(igxSwitch): updates API Docs for the igxSwitch 

projects/igniteui-angular/src/lib/switch/switch.component.ts
=> docs(igxSwitch): updates API Docs for the igxSwitch

projects/igniteui-angular/src/lib/directives/input/input.directive.ts
=> docs(igxInput): updates API Docs for the input directive - 9.0.x

projects/igniteui-angular/src/lib/directives/input/input.directive.ts
=> docs(igxInput): updates API Docs for the input directive

projects/igniteui-angular/src/lib/card/card.component.ts
=> docs(igxCard): Update docs for the igxCardComponent API

projects/igniteui-angular/src/lib/date-picker/date-picker.component.ts
=> chore(docs): Updating date-picker api docs.

projects/igniteui-angular/src/lib/list/list.component.ts
=> docs(igxlist): modifying api docs for new guidelines

projects/igniteui-angular/src/lib/list/list.component.ts
=> docs(igxlist): modifying api docs for new guidelines - 9.0

projects/igniteui-angular/src/lib/grids/grid-base.directive.ts, projects/igniteui-angular/src/lib/grids/grid/grid.component.ts
=> Updating Grid Api docs

projects/igniteui-angular/src/lib/grids/grid-base.directive.ts, projects/igniteui-angular/src/lib/grids/grid/grid.component.ts
=> Updating Grid Api docs 

projects/igniteui-angular/src/lib/grids/grid/cell.spec.ts, projects/igniteui-angular/src/lib/grids/grid/grid-cell-editing.spec.ts, projects/igniteui-angular/src/lib/grids/grid/grid-row-editing.spec.ts, projects/igniteui-angular/src/lib/test-utils/grid-samples.spec.ts
=> Refactor cell test - 9.0

projects/igniteui-angular/src/lib/core/styles/components/carousel/_carousel-theme.scss, src/app/carousel/carousel.sample.html, src/app/carousel/carousel.sample.scss, src/app/carousel/carousel.sample.ts
=> fix(carousel): adding min width and height

projects/igniteui-angular/src/lib/core/styles/components/grid/_grid-theme.scss, projects/igniteui-angular/src/lib/core/styles/themes/schemas/light/_grid.scss
=> fix(grid): Allow users to change the group area color

projects/igniteui-angular/src/lib/core/styles/README.md, projects/igniteui-angular/src/lib/core/styles/themes/schemas/dark/_tooltip.scss
=> update readme file

projects/igniteui-angular/src/lib/directives/radio/radio-group.directive.ts
=> docs(igxRadioGroup): Update API docs for igxRadioGroup directive

projects/igniteui-angular/src/lib/grids/filtering/excel-style/grid.excel-style-filtering.component.ts
Closes IgniteUI/igniteui-angular-samples#1703
=> fix(esf): Do not focus search input in external filtering #1703

projects/igniteui-angular/src/lib/core/styles/README.md, projects/igniteui-angular/src/lib/core/styles/themes/schemas/dark/_tooltip.scss
=> Sivanova/theming docs 9.0.x

projects/igniteui-angular/src/lib/grids/columns/column.component.ts, projects/igniteui-angular/src/lib/grids/grid-base.directive.ts, projects/igniteui-angular/src/lib/grids/grid/grid.component.html, projects/igniteui-angular/src/lib/grids/grid/grid.pinning.spec.ts, src/app/grid-column-pinning/grid-column-pinning.sample.html, src/app/grid-column-pinning/grid-column-pinning.sample.ts
=> Right Pinning + Row Selectors Integration

projects/igniteui-angular/src/lib/directives/autocomplete/autocomplete.directive.spec.ts, projects/igniteui-angular/src/lib/services/overlay/overlay.spec.ts, projects/igniteui-angular/src/lib/time-picker/time-picker.component.spec.ts
=> Fix failing tests with Ivy - P3 - 9.0

projects/igniteui-angular/src/lib/directives/for-of/for_of.directive.spec.ts, projects/igniteui-angular/src/lib/grids/grid/grid-mrl-keyboard-nav.spec.ts, projects/igniteui-angular/src/lib/grids/grid/grid.component.spec.ts, projects/igniteui-angular/src/lib/grids/grid/grid.master-detail.spec.ts, projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.spec.ts, projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid.component.spec.ts
=> Fix tests failing with Ivy - P2

projects/igniteui-angular/src/lib/grids/columns/column.component.ts, projects/igniteui-angular/src/lib/grids/grid/grid.pinning.spec.ts, projects/igniteui-angular/src/lib/grids/headers/grid-header-group.component.html, projects/igniteui-angular/src/lib/grids/headers/grid-header-group.component.ts, src/app/grid-column-groups/grid-column-groups.sample.html
=> feat(Grid): Right Pinning + Column groups.

projects/igniteui-angular/src/lib/grids/grid/column-hiding.spec.ts, projects/igniteui-angular/src/lib/progressbar/circularbar.component.spec.ts, projects/igniteui-angular/src/lib/progressbar/linearbar.component.spec.ts
=> Fix tests failing with Ivy - P4 - 9.0.x

CHANGELOG.md
=> docs(changelog): updating changelog for right pinning #6676

projects/igniteui-angular/src/lib/grids/hierarchical-grid/index.ts
=> fix(grid): Export IgxHierGridCellComponent #6711

projects/igniteui-angular/src/lib/grids/grid/grid-mrl-keyboard-nav.spec.ts, projects/igniteui-angular/src/lib/test-utils/grid-functions.spec.ts, projects/igniteui-angular/src/lib/test-utils/helper-utils.spec.ts
=> Refactor Multi-row Layout navigation tests

projects/igniteui-angular/src/lib/slider/slider.component.spec.ts
=> update slider tests to rum with Ivy true

projects/igniteui-angular/src/lib/grids/grid-base.component.ts
=> docs(grid): Add remark for autoGenerate property

gulpfile.js, package-lock.json, package.json, projects/igniteui-angular/src/lib/calendar/calendar.component.ts
=> chore(package.json): update typedoc-localization plugin version

projects/igniteui-angular/src/lib/drop-down/drop-down.component.spec.ts, projects/igniteui-angular/src/lib/test-utils/ui-interactions.spec.ts
=> IgxDropdownTestRefactoring 9.0.x

projects/igniteui-angular/src/lib/core/styles/themes/schemas/light/_toast.scss
=> fix(toast): text wasn't visible in bootstrap light theme

projects/igniteui-angular/src/lib/grids/grid/grid-filtering-advanced.spec.ts, projects/igniteui-angular/src/lib/test-utils/grid-functions.spec.ts
=> Tests Refactoring: IgxGrid Advanced Filtering - 9.0.x

projects/igniteui-angular/src/lib/directives/autocomplete/autocomplete.directive.spec.ts, projects/igniteui-angular/src/lib/directives/autocomplete/autocomplete.directive.ts, src/app/autocomplete/autocomplete.sample.html, src/app/autocomplete/autocomplete.sample.ts
=> fix(autocomplete): allow autocomplete drop-down width to be adjustable - 8.2.x

CHANGELOG.md, projects/igniteui-angular/src/lib/slider/slider.component.spec.ts, projects/igniteui-angular/src/lib/slider/slider.component.ts
=> Slider ivy input order independence

projects/igniteui-angular/src/lib/directives/for-of/for_of.directive.ts
=> Reset scrollComponent scrollAmount, if scrollbar is hidden - 82x

src/app/app.component.ts, src/app/app.module.ts, src/app/reactive-from/reactive-form-sample.component.html, src/app/reactive-from/reactive-form-sample.component.scss, src/app/reactive-from/reactive-form-sample.component.ts, src/app/routing.ts
Add dev sample with reactive forms
Closes #6471
=> chore(reactive-form): add dev sample for reactive form

projects/igniteui-angular/src/lib/grids/grid-base.component.ts
=> fix(grid): Set onSortingDone to be emitted after pipes trggers (8.2.x).

projects/igniteui-angular/src/lib/grids/grid-base.directive.ts
=> fix(grid): Set onSortingDone to be emitted after pipes trggers. (master)

projects/igniteui-angular/src/lib/grids/grid-base.directive.ts
=> fix(grid): Set onSortingDone to be emitted after pipes trggers. (9.0.x)

projects/igniteui-angular/src/lib/grids/grid-base.directive.ts, projects/igniteui-angular/src/lib/grids/grid/grid.multi-row-layout.spec.ts
=> fix(mrl): fixing validPosition for mrl and right pinning scenarios #6745 - master

projects/igniteui-angular/src/lib/grids/grid-base.directive.ts, projects/igniteui-angular/src/lib/grids/grid/grid.multi-row-layout.spec.ts
=> fix(mrl): fixing validPosition for mrl and right pinning scenarios #6745 - 9.0

projects/igniteui-angular/src/lib/grids/grid-base.component.ts, projects/igniteui-angular/src/lib/grids/grid/grid.multi-row-layout.spec.ts
=> fix(mrl): fixing validPosition for mrl and right pinning scenarios #6745 - 8.2

projects/igniteui-angular/src/lib/core/styles/components/grid/_excel-filtering-theme.scss, projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-position-strategy.ts, projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-search.component.html, projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-search.component.ts, projects/igniteui-angular/src/lib/grids/filtering/excel-style/grid.excel-style-filtering.component.html, projects/igniteui-angular/src/lib/grids/filtering/excel-style/grid.excel-style-filtering.component.ts, projects/igniteui-angular/src/lib/grids/grid/grid-filtering-ui.spec.ts, projects/igniteui-angular/src/lib/grids/headers/grid-header.component.ts, projects/igniteui-angular/src/lib/services/overlay/position/base-fit-position-strategy.ts, src/app/grid-filtering/grid-filtering.sample.html, src/app/grid-filtering/grid-filtering.sample.ts
=> fix(excel-style-filtering): implemented new position strategy for esf only

projects/igniteui-angular/src/lib/core/styles/themes/schemas/dark/_toast.scss
=> fix(toast): text not visible in bootstrap dark theme

projects/igniteui-angular/src/lib/buttonGroup/buttongroup-content.component.html, projects/igniteui-angular/src/lib/core/styles/components/button-group/_button-group-component.scss, projects/igniteui-angular/src/lib/core/styles/components/button-group/_button-group-theme.scss, src/app/buttonGroup/buttonGroup.sample.html
=> fix(button-group): Add ellipsis

CHANGELOG.md
=> docs(row-pinning): Update changelog

projects/igniteui-angular/src/lib/grids/grid-base.directive.ts, projects/igniteui-angular/src/lib/grids/grid/row-pinning.spec.ts
=> feat(igxGrid): Row pinning + Summaries integration

projects/igniteui-angular/src/lib/grids/grid/column-group.spec.ts, projects/igniteui-angular/src/lib/grids/grid/grid-summary.spec.ts, projects/igniteui-angular/src/lib/grids/grid/grid.master-detail.spec.ts, projects/igniteui-angular/src/lib/test-utils/grid-functions.spec.ts
=> Tests Refactoring: IgxGrid - Summaries

projects/igniteui-angular/src/lib/grids/grid-base.directive.ts, projects/igniteui-angular/src/lib/grids/grid/row-pinning.spec.ts
=> fix(igxGrid): Fix and test for pinning row at index.

projects/igniteui-angular/src/lib/select/select.component.html
=> Move disabled on the Input element

projects/igniteui-angular/src/lib/grids/filtering/grid-filtering-row.component.ts, projects/igniteui-angular/src/lib/grids/grid/grid-filtering-ui.spec.ts
=> fix(filtering): Fix issue when switch conditions #6519

projects/igniteui-angular/src/lib/grids/grid/row-pinning.spec.ts, src/app/grid-column-pinning/grid-column-pinning.sample.ts, src/app/grid-row-pinning/grid-row-pinning.sample.html
=> test(row-pinning): Add test for row pinning and hiding #6640

projects/igniteui-angular/src/lib/grids/state.directive.spec.ts, projects/igniteui-angular/src/lib/grids/state.directive.ts, src/app/grid-row-pinning/grid-row-pinning.sample.html, src/app/grid-row-pinning/grid-row-pinning.sample.ts
=> Adding row pinning persistence via igxGridState directive.

projects/igniteui-angular/src/lib/grids/grid-base.directive.ts, projects/igniteui-angular/src/lib/grids/toolbar/grid-toolbar.component.ts
=> fix(*): Apply custom css classes to igxGrid and igxToolbar components

projects/igniteui-angular/src/lib/grids/grid/grid-row-selection.spec.ts, projects/igniteui-angular/src/lib/test-utils/ui-interactions.spec.ts
=> Test refactoring for igx-grid row selection (9.0.x)

projects/igniteui-angular/src/lib/paginator/paginator.component.spec.ts, projects/igniteui-angular/src/lib/paginator/paginator.component.ts
=> Change current page to equal last page, after changing perPage

projects/igniteui-angular/src/lib/core/styles/themes/schemas/light/_time-picker.scss
=> fix(time-picker): dart sass fails to build

projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.selection.spec.ts
=> Refactoring Hierarchical grid selection test suit (master)

package-lock.json, package.json
=> chore(*): update typedoc theme v

CHANGELOG.md, projects/igniteui-angular/src/lib/grids/columns/column.component.ts, projects/igniteui-angular/src/lib/grids/grid/column-group.spec.ts, projects/igniteui-angular/src/lib/grids/grid/column.spec.ts, projects/igniteui-angular/src/lib/grids/headers/grid-header-group.component.html, projects/igniteui-angular/src/lib/grids/headers/grid-header-group.component.ts, projects/igniteui-angular/src/lib/grids/headers/grid-header.component.html, projects/igniteui-angular/src/lib/grids/headers/grid-header.component.ts, src/app/grid-column-groups/grid-column-groups.sample.html
=> feat(grid): add support for column title

projects/igniteui-angular/src/lib/grids/grid/grid.sorting.spec.ts
=> Additional grid sorting test refactoring (master)

projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.navigation.spec.ts
=> tests(HGrid): Refactor Hierarchical Grid navigation tests.

projects/igniteui-angular/src/lib/grids/grid/grid.search.spec.ts
=> Tests Refactoring: IgxGrid - search API - 9.0.x

projects/igniteui-angular/src/lib/directives/for-of/for_of.directive.spec.ts, projects/igniteui-angular/src/lib/directives/for-of/for_of.directive.ts, src/app/list-performance/list-performance.sample.html, src/app/list-performance/list-performance.sample.ts
=> fix(igxForOf): Add check in case scrollComponent is already destroyed.

projects/igniteui-angular/src/lib/grids/filtering/base/grid-filtering-row.component.html, projects/igniteui-angular/src/lib/grids/filtering/base/grid-filtering-row.component.ts, projects/igniteui-angular/src/lib/grids/grid/grid-filtering-ui.spec.ts, projects/igniteui-angular/src/lib/test-utils/grid-functions.spec.ts
=> fix(filter-ui): Fix date filtering and chip commit #6594

projects/igniteui-angular/src/lib/grids/grid/grid-filtering-ui.spec.ts
=> Update failing filtering test

projects/igniteui-angular/src/lib/grids/grid/column-pinning.spec.ts, projects/igniteui-angular/src/lib/grids/pinning/column-pinning.component.html, projects/igniteui-angular/src/lib/grids/pinning/column-pinning.component.ts, projects/igniteui-angular/src/lib/grids/pinning/pinning.directive.ts
=> fix(igxGrid): List only pinnable columns in pinning toolbar #5640

projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.navigation.spec.ts
Disable test related to issue.
=> chore(*): Disable test related to issue.

projects/igniteui-angular/src/lib/core/styles/components/splitter/_splitter-theme.scss, projects/igniteui-angular/src/lib/splitter/splitter-bar/splitter-bar.component.html, projects/igniteui-angular/src/lib/splitter/splitter-bar/splitter-bar.component.ts, projects/igniteui-angular/src/lib/splitter/splitter.component.spec.ts
=> Change cursor depending on whether bar allows resizing.

projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-search.component.html, projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-search.pipe.ts, projects/igniteui-angular/src/lib/grids/filtering/excel-style/grid.excel-style-filtering.component.ts, projects/igniteui-angular/src/lib/grids/grid/grid-filtering-ui.spec.ts
=> fix(ESF): searching text on a date column works properly #6619

projects/igniteui-angular/src/lib/grids/filtering/base/grid-filtering-row.component.ts, projects/igniteui-angular/src/lib/grids/grid/grid-filtering-ui.spec.ts
Reverts IgniteUI/igniteui-angular#7097
Closes #7159
=> Revert "fix(filtering): Avoid resetting values for number inputs #6973"

projects/igniteui-angular/src/lib/core/styles/components/calendar/_calendar-component.scss, projects/igniteui-angular/src/lib/core/styles/components/calendar/_calendar-theme.scss, projects/igniteui-angular/src/lib/core/styles/themes/schemas/light/_calendar.scss
=> fix(calendar): add current hover month text color

projects/igniteui-angular/src/lib/grids/column.component.ts, projects/igniteui-angular/src/lib/grids/filtering/grid-filtering.service.ts, projects/igniteui-angular/src/lib/grids/grid/grid-filtering-ui.spec.ts
=> fix(filter-ui): hide filtering row on column hide #6520

projects/igniteui-angular/src/lib/paginator/paginator.component.ts
=> fix(paginator): Add missing index #7185

projects/igniteui-angular/src/lib/grids/grid/expandable-cell.component.html, projects/igniteui-angular/src/lib/grids/grid/grid-row-pinning.spec.ts, src/app/grid-row-pinning/grid-row-pinning.sample.html
Related to https://github.com/IgniteUI/igniteui-angular/issues/7143
=> fix(igxGrid): Include chip in template for mdv expander cell.

projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid-integration.spec.ts, projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid-row.component.ts
Related to https://github.com/IgniteUI/igniteui-angular/issues/7141
=> fix(igxTreeGrid): Overwrite setter as well as the getter.

projects/igniteui-angular/src/lib/grids/grid/grid-toolbar.spec.ts, projects/igniteui-angular/src/lib/test-utils/grid-functions.spec.ts
=> Tests Refactoring: IgxGrid - Grid Toolbar - 9.0.x

CHANGELOG.md, projects/igniteui-angular/src/lib/grids/filtering/grid-filtering.service.ts, projects/igniteui-angular/src/lib/grids/grid-navigation.service.ts, projects/igniteui-angular/src/lib/grids/grid/expandable-cell.component.html, projects/igniteui-angular/src/lib/grids/headers/grid-header.component.ts, projects/igniteui-angular/src/lib/grids/tree-grid/tree-cell.component.html
=> Keyboard Navigation Changelog update

projects/igniteui-angular/src/lib/core/styles/components/grid-summary/_grid-summary-component.scss, projects/igniteui-angular/src/lib/core/styles/components/grid/_grid-component.scss, projects/igniteui-angular/src/lib/core/styles/components/grid/_grid-theme.scss
=> fix(grid): Adding active styles for summaries, group row and header

.github/PULL_REQUEST_TEMPLATE.md
=> chore(*): update PR template with links to related wiki pages

projects/igniteui-angular/src/lib/grids/grid-navigation.service.ts
Related to https://github.com/IgniteUI/igniteui-angular/issues/7143
=> fix(igxGrid): Allow to select/deselect ghost row with space.

projects/igniteui-angular/src/lib/grids/common/pipes.ts, projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid.component.ts
=> Fixes Wrong Order of Pinned Records in Treegrid

projects/igniteui-angular/migrations/update-9_1_0/changes/inputs.json, projects/igniteui-angular/migrations/update-9_1_0/index.spec.ts, projects/igniteui-angular/src/lib/toast/toast.component.html, projects/igniteui-angular/src/lib/toast/toast.component.ts
=> chore(toast): migrate toast message property to text content

projects/igniteui-angular/src/lib/grids/filtering/grid-filtering-row.component.ts
=> fix(filtering): filter behavior on number type filter #6973

projects/igniteui-angular/src/lib/grids/common/grid.interface.ts, projects/igniteui-angular/src/lib/grids/grid-base.directive.ts, projects/igniteui-angular/src/lib/grids/grid.common.ts, projects/igniteui-angular/src/lib/grids/grid/grid-row-pinning.spec.ts, projects/igniteui-angular/src/lib/grids/grid/grid.pinning.spec.ts, projects/igniteui-angular/src/lib/grids/state.directive.ts, projects/igniteui-angular/src/lib/test-utils/hierarchical-grid-components.spec.ts, src/app/grid-column-pinning/grid-column-pinning.sample.ts, src/app/grid-row-pinning/grid-row-pinning.sample.ts, src/app/grid-summaries/grid-summaries.sample.ts
=> chore(*): adding pinning interface export for lib

azure-pipelines.yml
=> chore(*): trying the speed of npm ci

projects/igniteui-angular/src/lib/core/styles/components/icon/_icon-theme.scss, projects/igniteui-angular/src/lib/core/styles/themes/schemas/light/_action-strip.scss, projects/igniteui-angular/src/lib/core/styles/themes/schemas/light/_button.scss, projects/igniteui-angular/src/lib/core/styles/themes/schemas/light/_chip.scss, projects/igniteui-angular/src/lib/core/styles/themes/schemas/light/_grid-summary.scss, projects/igniteui-angular/src/lib/core/styles/themes/schemas/light/_icon.scss, projects/igniteui-angular/src/lib/core/styles/themes/schemas/light/_list.scss
=> fix currentColor in Edge

projects/igniteui-angular/src/lib/grids/filtering/base/grid-filtering-cell.component.html
=> set tabIndex for filter cell chips

projects/igniteui-angular/src/lib/grids/grid-base.directive.ts, projects/igniteui-angular/src/lib/grids/hierarchical-grid/child-grid-row.component.ts, projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.component.ts, projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.selection.spec.ts, projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.spec.ts, projects/igniteui-angular/src/lib/grids/hierarchical-grid/row-island.component.ts
…ction cycle to circumvent Ivy issue with ContentChilren being re-evaluated when inner template has ngIf.
Closes #7257
=> fix(igxHierarchicalGrid): Moving column change logic in separate dete

projects/igniteui-angular/src/lib/date-picker/date-picker.utils.ts, projects/igniteui-angular/src/lib/date-range-picker/date-range-picker.component.ts, projects/igniteui-angular/src/lib/directives/date-time-editor/date-time-editor.directive.spec.ts, projects/igniteui-angular/src/lib/directives/date-time-editor/date-time-editor.directive.ts, src/app/date-time-editor/date-time-editor.sample.html, src/app/date-time-editor/date-time-editor.sample.ts
=> Update model when input is filled out

projects/igniteui-angular/src/lib/grids/grid-base.directive.ts, projects/igniteui-angular/src/lib/grids/grid-navigation.service.ts, projects/igniteui-angular/src/lib/grids/grid/grid.component.spec.ts
=> fix(igxGrid): Fix trying to perform horizontal scroll when passed index is not valid. 

projects/igniteui-angular/src/lib/date-range-picker/date-range-picker.component.spec.ts
=> Remove selectToday() tests from date-range-picker

projects/igniteui-angular/src/lib/core/styles/components/card/_card-component.scss, projects/igniteui-angular/src/lib/core/styles/components/card/_card-theme.scss, src/app/card/card.sample.html
=> fix(card): spacing for bootstrap theme

projects/igniteui-angular/src/lib/core/styles/components/dialog/_dialog-theme.scss, src/app/dialog/dialog.sample.css, src/app/dialog/dialog.sample.html
=> fix(dialog): incorrect dialog title size

projects/igniteui-angular/src/lib/grids/common/events.ts
=> fix(grid): Export range selection interface

projects/igniteui-angular/src/lib/grids/columns/column.component.ts, projects/igniteui-angular/src/lib/grids/grid/column-resizing.spec.ts, projects/igniteui-angular/src/lib/grids/resizing/resizing.service.ts
=> fix(igxGrid): Parse minWidth property so that can be set correctly

projects/igniteui-angular/src/lib/directives/input/input.directive.spec.ts, projects/igniteui-angular/src/lib/directives/input/input.directive.ts
=> Set igxInput disabled based on form settings

projects/igniteui-angular/src/lib/date-range-picker/README.md
Fix typo:
igx-picker**s**-toggle should be igx-picker-toggle
=> chore(daterange): Fix readme typo

projects/igniteui-angular/schematics/ng-add/add-normalize.ts, projects/igniteui-angular/schematics/ng-add/index.spec.ts, projects/igniteui-angular/schematics/ng-add/index.ts, projects/igniteui-angular/schematics/utils/dependency-handler.ts
Closes #7285 
Add array of explicitly defined dependencies (along w/ dependency target) to avoid adding unnecessary packages to the consuming project.
@types dependencies are now properly added to `devDependencies`.
=> refactor(schematics): explicit def of pckgs to be added to app's deps

projects/igniteui-angular/src/lib/core/styles/components/card/_card-theme.scss
=> fix(card): display block for igx-card-content directive

projects/igniteui-angular/src/lib/grids/filtering/advanced-filtering/advanced-filtering-dialog.component.ts, projects/igniteui-angular/src/lib/grids/grid/grid-keyBoardNav-headers.spec.ts
=> Close advanced filter dialog when escape is pressed

projects/igniteui-angular/src/lib/combo/combo.component.spec.ts, projects/igniteui-angular/src/lib/directives/for-of/for_of.directive.ts
…ht to actual height ration when recalculating vertical offset.
Closes #7234
=> fix(virtualization): Use virtual scroll top which takes virtual heig

projects/igniteui-angular/src/lib/grids/cell.component.ts, projects/igniteui-angular/src/lib/grids/grid-mrl-navigation.service.ts, projects/igniteui-angular/src/lib/grids/grid/grid-keyBoardNav.spec.ts, projects/igniteui-angular/src/lib/test-utils/grid-functions.spec.ts
=> Set navigation.activeNode when call activate method 

projects/igniteui-angular/src/lib/core/styles/components/ripple/_ripple-theme.scss, projects/igniteui-angular/src/lib/directives/ripple/ripple.directive.ts, src/app/app.component.html
=> fix(ripple): reset margin and border to avoid displacement

CHANGELOG.md, projects/igniteui-angular/src/lib/date-range-picker/README.md
=> docs(igx-date-range-picker): fix igxDateRange name

projects/igniteui-angular/migrations/common/UpdateChanges.spec.ts, projects/igniteui-angular/migrations/common/UpdateChanges.ts, projects/igniteui-angular/migrations/common/schema/binding.schema.json, projects/igniteui-angular/migrations/common/schema/index.ts, projects/igniteui-angular/migrations/update-9_1_0/changes/inputs.json, projects/igniteui-angular/migrations/update-9_1_0/index.spec.ts, projects/igniteui-angular/migrations/update-9_1_0/index.ts
=> Migrate deprecated rowSelectable property to rowSelection

projects/igniteui-angular/src/lib/grids/grid-base.directive.ts, projects/igniteui-angular/src/lib/grids/grid/grid-keyBoardNav.spec.ts, projects/igniteui-angular/src/lib/grids/grid/grid-mrl-keyboard-nav.spec.ts, projects/igniteui-angular/src/lib/grids/grid/grid.component.html, projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.component.html, projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid.component.html
=> Focus grid body after closing row editing

projects/igniteui-angular/src/lib/date-range-picker/date-range-picker.module.ts
=> fix(igx-date-range-picker): export IgxDateTimeEditorModule #5732

projects/igniteui-angular/src/lib/core/styles/components/grid/_grid-component.scss, projects/igniteui-angular/src/lib/core/styles/components/grid/_grid-theme.scss
=> Implement support for up to 25 levels #7299

projects/igniteui-angular/src/lib/slider/slider.component.ts
=> fix(slider): two way bound err

projects/igniteui-angular/src/lib/grids/grid-navigation.service.ts
=> Update selection when remote data is used

projects/igniteui-angular/src/lib/grids/grid-base.directive.ts, projects/igniteui-angular/src/lib/paginator/paginator.component.ts
=> docs(grid): Expose paging event emitters

projects/igniteui-angular/src/lib/grids/grid-base.directive.ts, projects/igniteui-angular/src/lib/paginator/paginator.component.ts
=> Expose page change per page change emitters 

projects/igniteui-angular/src/lib/grids/headers/grid-header.component.ts
=> Do not select column when click filter icon 

projects/igniteui-angular/src/lib/core/styles/components/input/_input-group-theme.scss
=> Remove pointer-events setting on disabled input

projects/igniteui-angular/package.json
=> chore(*): update packages & ig schematics

projects/igniteui-angular/src/lib/carousel/carousel.component.ts
=> Reset carousel animation when it  is  playing and change slide

projects/igniteui-angular/src/lib/core/styles/components/date-range-picker/_date-range-picker-theme.scss, projects/igniteui-angular/src/lib/core/styles/components/radio/_radio-theme.scss, projects/igniteui-angular/src/lib/core/styles/themes/schemas/dark/_action-strip.scss, projects/igniteui-angular/src/lib/core/styles/themes/schemas/dark/_watermark.scss, projects/igniteui-angular/src/lib/core/styles/themes/schemas/light/_action-strip.scss, projects/igniteui-angular/src/lib/core/styles/themes/schemas/light/_watermark.scss, src/styles/igniteui-theme.scss
=> docs(sassdoc): fix warnings and errors

projects/igniteui-angular/src/lib/core/styles/components/charts/_gauge-chart-theme.scss, projects/igniteui-angular/src/lib/core/styles/themes/_index.scss, projects/igniteui-angular/src/lib/core/styles/themes/schemas/dark/_gauge-chart.scss, projects/igniteui-angular/src/lib/core/styles/themes/schemas/dark/_index.scss, projects/igniteui-angular/src/lib/core/styles/themes/schemas/light/_gauge-chart.scss, projects/igniteui-angular/src/lib/core/styles/themes/schemas/light/_index.scss
=> feat(gauge-chart): add linear gauge chart theme & schemas

LICENSE, README.md
=> Licensing change

LICENSE, README.md
=> Typo in Readme File

projects/igniteui-angular/src/lib/grids/grid/grid-filtering-ui.spec.ts, projects/igniteui-angular/src/lib/grids/grid/grid-keyBoardNav-headers.spec.ts, projects/igniteui-angular/src/lib/grids/grid/grid-keyBoardNav.spec.ts
=> Fix failing filter tests

projects/igniteui-angular/src/lib/grids/grid/grid-filtering-ui.spec.ts
=> Fix failing filter tests - 90

projects/igniteui-angular/src/lib/date-range-picker/date-range-picker-inputs.common.ts, projects/igniteui-angular/src/lib/date-range-picker/date-range-picker.component.ts, projects/igniteui-angular/src/lib/date-range-picker/date-range-picker.module.ts
=> fix(date-range): Fix barrel import paths

projects/igniteui-angular/src/lib/core/styles/components/charts/_map-chart-theme.scss, projects/igniteui-angular/src/lib/core/styles/themes/_index.scss, projects/igniteui-angular/src/lib/core/styles/themes/schemas/dark/_index.scss, projects/igniteui-angular/src/lib/core/styles/themes/schemas/dark/_map-chart.scss, projects/igniteui-angular/src/lib/core/styles/themes/schemas/light/_index.scss, projects/igniteui-angular/src/lib/core/styles/themes/schemas/light/_map-chart.scss
=> feat(map-chart): add map chart theme and schemas

projects/igniteui-angular/src/lib/grids/filtering/advanced-filtering/advanced-filtering-dialog.component.ts, projects/igniteui-angular/src/lib/grids/grid/grid-cell-editing.spec.ts, projects/igniteui-angular/src/lib/grids/grid/grid-row-editing.spec.ts
=> fix(grid): end grid edit on advanced filtering clear/apply - 8.2.x

projects/igniteui-angular/src/lib/grids/columns/column-group.component.ts, projects/igniteui-angular/src/lib/grids/columns/column.component.ts
=> Update selected property description

projects/igniteui-angular/src/lib/action-strip/grid-actions/grid-editing-actions.component.ts
=> fix(action-strip): Add warning when grid is not editable #7245

projects/igniteui-angular/src/lib/grids/grid/grid-api.service.ts, projects/igniteui-angular/src/lib/grids/grid/grid-summary.spec.ts
=> fix(*): Add a check not to update groupingExpansionState when no expansion states are changed

projects/igniteui-angular/src/lib/progressbar/circularbar.component.spec.ts, projects/igniteui-angular/src/lib/progressbar/linearbar.component.spec.ts, projects/igniteui-angular/src/lib/progressbar/progressbar.component.ts
=> fix(progressbar): decrease the progress when pass lower value

projects/igniteui-angular/karma.azure.conf.js, projects/igniteui-angular/karma.azure.grid.conf.js, projects/igniteui-angular/karma.azure.hierarchical-grid.conf.js, projects/igniteui-angular/karma.azure.non-grid.conf.js, projects/igniteui-angular/karma.azure.tree-grid.conf.js, projects/igniteui-angular/karma.conf.js, projects/igniteui-angular/karma.grid.conf.js, projects/igniteui-angular/karma.hierarchical-grid.conf.js, projects/igniteui-angular/karma.non-grid.conf.js, projects/igniteui-angular/karma.tree-grid.conf.js, projects/igniteui-angular/src/lib/directives/text-selection/text-selection.directive.spec.ts, projects/igniteui-angular/src/lib/grids/grid/column-group.spec.ts, projects/igniteui-angular/src/lib/grids/grid/column-hiding.spec.ts, projects/igniteui-angular/src/lib/grids/grid/column-moving.spec.ts, projects/igniteui-angular/src/lib/grids/grid/column-pinning.spec.ts, projects/igniteui-angular/src/lib/grids/grid/column.spec.ts, projects/igniteui-angular/src/lib/grids/grid/grid-clipboard.spec.ts, projects/igniteui-angular/src/lib/grids/grid/grid-filtering-advanced.spec.ts, projects/igniteui-angular/src/lib/grids/grid/grid-filtering-ui.spec.ts, projects/igniteui-angular/src/lib/grids/grid/grid-filtering.spec.ts, projects/igniteui-angular/src/lib/grids/grid/grid-summary.spec.ts, projects/igniteui-angular/src/lib/grids/grid/grid-toolbar.spec.ts, projects/igniteui-angular/src/lib/grids/grid/grid.component.spec.ts, projects/igniteui-angular/src/lib/grids/grid/grid.groupby.spec.ts, projects/igniteui-angular/src/lib/grids/grid/row-drag.directive.spec.ts, projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid-crud.spec.ts, projects/igniteui-angular/src/lib/test-utils/configure-suite.ts, projects/igniteui-angular/src/test.ts
=> Update for failing tests with Ivy false - 9.0

projects/igniteui-angular/src/lib/grids/api.service.ts, projects/igniteui-angular/src/lib/grids/grid/expandable-cell.component.ts, projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid.component.ts
=> Remove cell focus leftovers

projects/igniteui-angular/src/lib/core/styles/components/charts/_category-chart-theme.scss, projects/igniteui-angular/src/lib/core/styles/themes/schemas/dark/_category-chart.scss, projects/igniteui-angular/src/lib/core/styles/themes/schemas/light/_category-chart.scss
=> style(category-chart): improve light & dark category chart schemas
