IgniteUI/igniteui-angular

projects/igniteui-angular/src/lib/grids/grid-base.directive.ts, src/app/app.component.ts, src/app/app.module.ts, src/app/app.routing.ts, src/app/grid-remote-virtualization-with-scroll/grid-remote-virtualization-scroll.sample.html, src/app/grid-remote-virtualization-with-scroll/grid-remote-virtualization-scroll.sample.ts, src/app/routing.ts, src/app/shared/remote.service - Copy.ts
=> Copy/paste cells in grid with remote virtualization -- 9.0.x

projects/igniteui-angular/src/lib/grids/grid/grid.component.ts, projects/igniteui-angular/src/lib/grids/grid/grid.master-detail.spec.ts
=> update getSelectedData method when grid has details 

projects/igniteui-angular/src/lib/grids/grid/grid.component.ts, projects/igniteui-angular/src/lib/grids/grid/grid.master-detail.spec.ts
=> update getSelectedData method when grid has details  - 9.0.x

projects/igniteui-angular/src/lib/core/styles/base/utilities/_functions.scss
=> refactor(theme): allow setting the grays palette to non-grayscale colors

projects/igniteui-angular/src/lib/calendar/calendar-base.ts
=> Fix not ending while in generateDateRange method 

projects/igniteui-angular/src/lib/calendar/calendar-base.ts, projects/igniteui-angular/src/lib/calendar/calendar.component.spec.ts
=> Fix not ending while in generateDateRange method

projects/igniteui-angular/src/lib/grids/grid-base.directive.ts, projects/igniteui-angular/src/lib/grids/grid/grid.pipes.ts, projects/igniteui-angular/src/lib/grids/grid/grid.search.spec.ts, projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid.pipes.ts
=> Keep edit mode when tabbing and search is applied

projects/igniteui-angular/src/lib/date-range-picker/date-range-picker.component.spec.ts, projects/igniteui-angular/src/lib/date-range-picker/date-range-picker.component.ts
Closes https://github.com/IgniteUI/igniteui-angular/issues/7556
=> Store last focused input and focus it onClosing

projects/igniteui-angular/src/lib/directives/autocomplete/autocomplete.directive.spec.ts, projects/igniteui-angular/src/lib/directives/autocomplete/autocomplete.directive.ts
=> fix(auto-complete): unsubscribe, before subscribing again #7483

projects/igniteui-angular/src/lib/grids/filtering/grid-filtering.service.ts, projects/igniteui-angular/src/lib/grids/grid/grid-filtering-ui.spec.ts
=> fix(filtering): clearing all column filters if no field is provided - 9.0.x

projects/igniteui-angular/src/lib/core/styles/typography/_typography.scss
=> fix(typography): igx-typography doesn't produce selectors correctly

projects/igniteui-angular/src/lib/directives/drag-drop/drag-drop.directive.ts, projects/igniteui-angular/src/lib/directives/drag-drop/drag-drop.spec.ts
=> fix(igxDrag): Add descendants support for igxDragIgnore and igxDragHandle. 

projects/igniteui-angular/src/lib/core/styles/components/grid/_excel-filtering-theme.scss, projects/igniteui-angular/src/lib/grids/filtering/excel-style/grid.excel-style-filtering.component.html
=> Fixed template visualization #6815

CHANGELOG.md, projects/igniteui-angular/src/lib/grids/columns/column.component.ts, projects/igniteui-angular/src/lib/grids/grid-base.directive.ts, projects/igniteui-angular/src/lib/grids/grid/column-group.spec.ts, projects/igniteui-angular/src/lib/grids/grid/grid-cell-selection.spec.ts, projects/igniteui-angular/src/lib/grids/grid/grid-collapsible-columns.spec.ts, projects/igniteui-angular/src/lib/grids/grid/grid-summary.spec.ts, projects/igniteui-angular/src/lib/grids/moving/moving.service.ts, projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid-integration.spec.ts
=> Refactor moveColumn to handle complex column structure correctly and produce same result when called with DropPosition.None

projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.component.ts
=> fix(igxHierarchicalGrid): Add ID setter for igxHGrid #7220

projects/igniteui-angular/src/lib/drop-down/drop-down-item.base.ts
=> fix(igx-drop-down): fix typo in api docs

projects/igniteui-angular/src/lib/date-picker/date-picker.component.html
=> fix(datepicker): Change text selection directive place in datepicker template (9.0.x)

projects/igniteui-angular/src/lib/directives/scroll-inertia/scroll_inertia.directive.ts
=> fix(igxForOf): Fix scrolling too much with trackpad on Firefox MacOS.

.hooks/scripts/templates/default.js, .hooks/scripts/utils/issue-validator.js
=> feat(git-hooks): remove types mondatory issues

projects/igniteui-angular/src/lib/grids/cell.component.ts, projects/igniteui-angular/src/lib/grids/grid/grid-row.component.html, projects/igniteui-angular/src/lib/grids/grid/grid.component.html, projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.component.html, projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-row.component.html, projects/igniteui-angular/src/lib/grids/summaries/summary-row.component.html, projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid-row.component.html, projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid.component.html
=> Interactive elements that are not cells or rows, should not trigger activation - master

projects/igniteui-angular/src/lib/grids/cell.component.ts, projects/igniteui-angular/src/lib/grids/grid/grid-row.component.html, projects/igniteui-angular/src/lib/grids/grid/grid.component.html, projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.component.html, projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-row.component.html, projects/igniteui-angular/src/lib/grids/summaries/summary-row.component.html, projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid-row.component.html, projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid.component.html
=> Interactive elements that are not cells or rows, should not trigger activation

CHANGELOG.md, projects/igniteui-angular/src/lib/grids/README.md, projects/igniteui-angular/src/lib/grids/grid/grid.component.html, projects/igniteui-angular/src/lib/grids/grid/grid.component.ts, src/app/grid-groupby/grid-groupby.sample.html, src/app/grid-groupby/grid-groupby.sample.ts
=> feat(igxGrid): Add an input that enable/disable group area row 

projects/igniteui-angular/src/lib/slider/slider.component.ts
=> Bug fix slider 9.1.x

projects/igniteui-angular/src/lib/slider/slider.component.ts
=> fix(slider): emit onchange callback correctly

CHANGELOG.md, projects/igniteui-angular/src/lib/grids/columns/column.component.ts, projects/igniteui-angular/src/lib/grids/grid-base.directive.ts, projects/igniteui-angular/src/lib/grids/grid/column-group.spec.ts, projects/igniteui-angular/src/lib/grids/grid/grid-cell-selection.spec.ts, projects/igniteui-angular/src/lib/grids/grid/grid-collapsible-columns.spec.ts, projects/igniteui-angular/src/lib/grids/grid/grid-summary.spec.ts, projects/igniteui-angular/src/lib/grids/grid/grid.pinning.spec.ts, projects/igniteui-angular/src/lib/grids/moving/moving.service.ts, projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid-integration.spec.ts, projects/igniteui-angular/src/lib/test-utils/grid-samples.spec.ts, src/app/grid-column-groups/grid-column-groups.sample.html, src/app/grid-column-groups/grid-column-groups.sample.ts, src/app/grid-multi-row-layout/grid-mrl.sample.html, src/app/grid-multi-row-layout/grid-mrl.sample.ts
=> fix(grid): column pinning with MRL wrong order of pinned columns (#7521)

projects/igniteui-angular/src/lib/date-range-picker/date-range-picker.component.spec.ts, projects/igniteui-angular/src/lib/date-range-picker/date-range-picker.component.ts
=> Update calendar with two filled in inputs

projects/igniteui-angular/src/lib/core/styles/themes/schemas/dark/_dock-manager.scss, projects/igniteui-angular/src/lib/core/styles/themes/schemas/light/_dock-manager.scss
=> Bootstrap fluent theme support

projects/igniteui-angular/src/lib/grids/columns/column-layout.component.ts, projects/igniteui-angular/src/lib/grids/grid/grid.multi-row-layout.integration.spec.ts
=> Set column visible index correctly when hide/show MRL block --master

projects/igniteui-angular/src/lib/grids/columns/column-layout.component.ts, projects/igniteui-angular/src/lib/grids/grid/grid.multi-row-layout.integration.spec.ts
=> Set column visible index correctly when hide/show MRL block -9.0.x

projects/igniteui-angular/src/lib/grids/columns/column-layout.component.ts, projects/igniteui-angular/src/lib/grids/grid/grid.multi-row-layout.integration.spec.ts
=> Set column visible index correctly when hide/show MRL block

projects/igniteui-angular/src/lib/services/transaction/igx-hierarchical-transaction.ts, projects/igniteui-angular/src/lib/services/transaction/igx-transaction.spec.ts
=> Fixes issue with hierarchical transaction commit emit count

projects/igniteui-angular/src/lib/services/transaction/igx-hierarchical-transaction.ts, projects/igniteui-angular/src/lib/services/transaction/igx-transaction.spec.ts
=> Fixes issue with hierarchical transaction commit emit count - 9.1

projects/igniteui-angular/src/lib/services/transaction/igx-hierarchical-transaction.ts, projects/igniteui-angular/src/lib/services/transaction/igx-transaction.spec.ts
=> Fixes issue with hierarchical transaction commit emit count - 9.0.x

projects/igniteui-angular/src/lib/core/styles/themes/schemas/dark/_badge.scss, projects/igniteui-angular/src/lib/core/styles/themes/schemas/dark/_index.scss, projects/igniteui-angular/src/lib/core/styles/themes/schemas/light/_badge.scss, projects/igniteui-angular/src/lib/core/styles/themes/schemas/light/_index.scss
=> feat(badge): add badge indigo theme support

projects/igniteui-angular/src/lib/core/styles/themes/schemas/dark/_index.scss, projects/igniteui-angular/src/lib/core/styles/themes/schemas/dark/_navbar.scss, projects/igniteui-angular/src/lib/core/styles/themes/schemas/elevation/_navbar.scss, projects/igniteui-angular/src/lib/core/styles/themes/schemas/light/_index.scss, projects/igniteui-angular/src/lib/core/styles/themes/schemas/light/_navbar.scss
=> feat(navbar): indigo theme support for navbar component

projects/igniteui-angular/src/lib/date-picker/date-picker.component.spec.ts, projects/igniteui-angular/src/lib/date-picker/date-picker.component.ts
=> Fix open & clear in disabled state v.9.1

projects/igniteui-angular/src/lib/date-picker/date-picker.component.spec.ts, projects/igniteui-angular/src/lib/date-picker/date-picker.component.ts
=> Fix open & clear in disabled state 9.0.x

projects/igniteui-angular/src/lib/date-picker/date-picker.component.spec.ts, projects/igniteui-angular/src/lib/date-picker/date-picker.component.ts
=> Fix open & clear in disabled state

projects/igniteui-angular/src/lib/directives/mask/mask.directive.ts
WARN: 'IgxMaskDirective.placeholder: "placeholder" is deprecated, use native placeholder instead.' is removed
=> fix(mask): set default placeholder properly

projects/igniteui-angular/src/lib/grids/grid-navigation.service.ts
=> Should be able to focus header when grid has no data

projects/igniteui-angular/src/lib/grids/grid-navigation.service.ts
=> Should be able to focus header when grid has no data - master

CHANGELOG.md, projects/igniteui-angular/src/lib/core/i18n/list-resources.ts, projects/igniteui-angular/src/lib/core/i18n/resources.ts, projects/igniteui-angular/src/lib/list/list.common.ts, projects/igniteui-angular/src/lib/list/list.component.html, projects/igniteui-angular/src/lib/list/list.component.ts, projects/igniteui-angular/src/public_api.ts
=> Add list localization #5280

projects/igniteui-angular/src/lib/core/styles/components/calendar/_calendar-theme.scss, projects/igniteui-angular/src/lib/core/styles/themes/schemas/dark/_calendar.scss, projects/igniteui-angular/src/lib/core/styles/themes/schemas/dark/_index.scss, projects/igniteui-angular/src/lib/core/styles/themes/schemas/light/_calendar.scss, projects/igniteui-angular/src/lib/core/styles/themes/schemas/light/_index.scss, projects/igniteui-angular/src/lib/core/styles/themes/schemas/shape/_calendar.scss
=> feat(themes): add initial indigo calendar theme

projects/igniteui-angular/src/lib/directives/focus/focus.directive.ts
=> Prevent scroll on focus -master

projects/igniteui-angular/src/lib/directives/focus/focus.directive.ts
=> Prevent scroll on focus -9.1.x

projects/igniteui-angular/src/lib/directives/focus/focus.directive.ts
=> Prevent scroll on focus

projects/igniteui-angular/src/lib/grids/grid/column-resizing.spec.ts, projects/igniteui-angular/src/lib/test-utils/grid-functions.spec.ts, projects/igniteui-angular/src/lib/test-utils/ui-interactions.spec.ts
=> Refactor column resizing test - 9.1

projects/igniteui-angular/src/lib/grids/grid/column-resizing.spec.ts, projects/igniteui-angular/src/lib/test-utils/grid-functions.spec.ts, projects/igniteui-angular/src/lib/test-utils/ui-interactions.spec.ts
=> Refactor column resizing test - 9.0

projects/igniteui-angular/src/lib/core/styles/components/checkbox/_checkbox-theme.scss, projects/igniteui-angular/src/lib/core/styles/themes/schemas/dark/_checkbox.scss, projects/igniteui-angular/src/lib/core/styles/themes/schemas/dark/_index.scss, projects/igniteui-angular/src/lib/core/styles/themes/schemas/light/_checkbox.scss, projects/igniteui-angular/src/lib/core/styles/themes/schemas/light/_index.scss, projects/igniteui-angular/src/lib/core/styles/themes/schemas/shape/_checkbox.scss
=> feat(checkbox): add checkbox to indigo theme

projects/igniteui-angular/package.json
=> chore(*): update schematics and other packages

projects/igniteui-angular/src/lib/grids/selection/selection.service.ts
=> fix(multi-cell-selection): multi cell selection safari

projects/igniteui-angular/src/lib/grids/selection/selection.service.ts
=> Multi cell selection 9.0.x

projects/igniteui-angular/src/lib/core/styles/themes/schemas/dark/_dock-manager.scss, projects/igniteui-angular/src/lib/core/styles/themes/schemas/light/_dock-manager.scss
=> refactor(dock-manager): themes

projects/igniteui-angular/src/lib/core/styles/themes/schemas/dark/_divider.scss, projects/igniteui-angular/src/lib/core/styles/themes/schemas/dark/_index.scss, projects/igniteui-angular/src/lib/core/styles/themes/schemas/light/_divider.scss, projects/igniteui-angular/src/lib/core/styles/themes/schemas/light/_index.scss
=> feat(divider): add divider support for indigo theme

projects/igniteui-angular/src/lib/core/styles/themes/schemas/dark/_index.scss, projects/igniteui-angular/src/lib/core/styles/themes/schemas/dark/_list.scss, projects/igniteui-angular/src/lib/core/styles/themes/schemas/light/_index.scss, projects/igniteui-angular/src/lib/core/styles/themes/schemas/light/_list.scss, projects/igniteui-angular/src/lib/core/styles/themes/schemas/shape/_list.scss
https://xd.adobe.com/view/fc5eb5a4-8a52-45b4-934e-75d8b4b8b29f-a90d/
=> feat(list): add list to indigo theme

projects/igniteui-angular/src/lib/core/styles/themes/schemas/dark/_bottom-nav.scss, projects/igniteui-angular/src/lib/core/styles/themes/schemas/dark/_index.scss, projects/igniteui-angular/src/lib/core/styles/themes/schemas/elevation/_bottom-nav.scss, projects/igniteui-angular/src/lib/core/styles/themes/schemas/light/_bottom-nav.scss, projects/igniteui-angular/src/lib/core/styles/themes/schemas/light/_index.scss
=> feat(bottom-nav): indigo theme support for bottom navigation

projects/igniteui-angular/src/lib/core/styles/components/carousel/_carousel-theme.scss, projects/igniteui-angular/src/lib/core/styles/themes/schemas/dark/_carousel.scss, projects/igniteui-angular/src/lib/core/styles/themes/schemas/dark/_index.scss, projects/igniteui-angular/src/lib/core/styles/themes/schemas/elevation/_carousel.scss, projects/igniteui-angular/src/lib/core/styles/themes/schemas/light/_carousel.scss, projects/igniteui-angular/src/lib/core/styles/themes/schemas/light/_index.scss, projects/igniteui-angular/src/lib/core/styles/themes/schemas/shape/_carousel.scss
=> feat(carousel): add support for carousel component in indigo theme

projects/igniteui-angular/src/lib/core/styles/components/toast/_toast-theme.scss, projects/igniteui-angular/src/lib/core/styles/themes/schemas/dark/_index.scss, projects/igniteui-angular/src/lib/core/styles/themes/schemas/dark/_toast.scss, projects/igniteui-angular/src/lib/core/styles/themes/schemas/light/_index.scss, projects/igniteui-angular/src/lib/core/styles/themes/schemas/light/_toast.scss, projects/igniteui-angular/src/lib/core/styles/themes/schemas/shape/_toast.scss
https://xd.adobe.com/view/261ea49e-e12e-4749-973b-70d57b864bd5-734d/
=> feat(toast): add toast to indigo theme

projects/igniteui-angular/src/lib/core/styles/themes/schemas/dark/_icon.scss, projects/igniteui-angular/src/lib/core/styles/themes/schemas/dark/_index.scss, projects/igniteui-angular/src/lib/core/styles/themes/schemas/light/_icon.scss, projects/igniteui-angular/src/lib/core/styles/themes/schemas/light/_index.scss
=> feat(icon): add indigo theme icon style

projects/igniteui-angular/src/lib/core/styles/components/chip/_chip-theme.scss, projects/igniteui-angular/src/lib/core/styles/themes/schemas/dark/_chip.scss, projects/igniteui-angular/src/lib/core/styles/themes/schemas/dark/_index.scss, projects/igniteui-angular/src/lib/core/styles/themes/schemas/elevation/_chip.scss, projects/igniteui-angular/src/lib/core/styles/themes/schemas/light/_chip.scss, projects/igniteui-angular/src/lib/core/styles/themes/schemas/light/_index.scss, projects/igniteui-angular/src/lib/core/styles/themes/schemas/shape/_chip.scss
=> feat(chip): add chip styles for indigo theme

projects/igniteui-angular/src/lib/directives/for-of/base.helper.component.ts
=> fix(igxForOf): Cache scroll size on initialize and use cached value when scrolling.

projects/igniteui-angular/src/lib/core/styles/themes/schemas/light/_banner.scss
https://xd.adobe.com/view/2c7f5440-ec3e-42ca-a70d-cf8605ed7515-792c/
=> feat(banner): add banner to indigo theme

projects/igniteui-angular/src/lib/core/styles/themes/_index.scss
=> Adding mixins for indigo dark and light variant

CHANGELOG.md, projects/igniteui-angular/src/lib/snackbar/snackbar.component.html, projects/igniteui-angular/src/lib/snackbar/snackbar.component.spec.ts, projects/igniteui-angular/src/lib/snackbar/snackbar.component.ts, projects/igniteui-angular/src/lib/toast/toast.component.html, projects/igniteui-angular/src/lib/toast/toast.component.spec.ts, projects/igniteui-angular/src/lib/toast/toast.component.ts
=> IgxToast `show` method take a message parameter

gulpfile.js
=> fix(typedoc): refer tsconfig to the export/import commands

CHANGELOG.md, projects/igniteui-angular/src/lib/combo/combo.component.ts, src/app/combo/combo.sample.css, src/app/combo/combo.sample.html, src/app/combo/combo.sample.ts
=> Set auto positioning strategy as a default one

angularDocsPostDeploy.ps1
=> Fixing the order of versions in the dropDown

projects/igniteui-angular/src/lib/core/styles/components/drop-down/_drop-down-component.scss, projects/igniteui-angular/src/lib/core/styles/components/drop-down/_drop-down-theme.scss, projects/igniteui-angular/src/lib/drop-down/drop-down.component.html, projects/igniteui-angular/src/lib/drop-down/drop-down.component.ts
=> fix(drop-down): remove shadow when list is empty #3977

projects/igniteui-angular/src/lib/core/styles/themes/schemas/dark/_calendar.scss, projects/igniteui-angular/src/lib/core/styles/themes/schemas/light/_calendar.scss
=> feat(calendar): improve dark indigo calendar

projects/igniteui-angular/src/lib/core/styles/themes/schemas/dark/_index.scss, projects/igniteui-angular/src/lib/core/styles/themes/schemas/dark/_time-picker.scss, projects/igniteui-angular/src/lib/core/styles/themes/schemas/light/_index.scss, projects/igniteui-angular/src/lib/core/styles/themes/schemas/light/_time-picker.scss, projects/igniteui-angular/src/lib/core/styles/themes/schemas/shape/_time-picker.scss
=> feat(time-picker): provide time-picker styles for indigo theme

projects/igniteui-angular/src/lib/core/styles/components/input/_input-group-theme.scss, src/app/input/input.sample.html, src/app/input/input.sample.ts
=> fix(input-group): textarea has incorrect line-height

ROADMAP.md
=> (*) chore Update Milestone 12

gulpfile.js
=> fix(typedoc): gulp typedoc commands tsconfig reference

projects/igniteui-angular/src/lib/core/styles/themes/schemas/light/_highlight.scss
=> feat(highlight): fix contrast color indigo

CHANGELOG.md
=> chore(changelog): include indigo theme in the changelog

projects/igniteui-angular/src/lib/core/styles/themes/presets/igniteui-angular-dark-rtl.scss, projects/igniteui-angular/src/lib/core/styles/themes/presets/igniteui-angular-dark.scss, projects/igniteui-angular/src/lib/core/styles/themes/presets/igniteui-angular-rtl.scss, projects/igniteui-angular/src/lib/core/styles/themes/presets/igniteui-angular.scss, projects/igniteui-angular/src/lib/core/styles/themes/presets/igniteui-bootstrap-dark-rtl.scss, projects/igniteui-angular/src/lib/core/styles/themes/presets/igniteui-bootstrap-dark.scss, projects/igniteui-angular/src/lib/core/styles/themes/presets/igniteui-bootstrap-light-rtl.scss, projects/igniteui-angular/src/lib/core/styles/themes/presets/igniteui-bootstrap-light.scss, projects/igniteui-angular/src/lib/core/styles/themes/presets/igniteui-indigo-dark-rtl.scss, projects/igniteui-angular/src/lib/core/styles/themes/presets/igniteui-indigo-dark.scss, projects/igniteui-angular/src/lib/core/styles/themes/presets/igniteui-indigo-light-rtl.scss, projects/igniteui-angular/src/lib/core/styles/themes/presets/igniteui-indigo-light.scss
=> chore(presets): add theme presets

CHANGELOG.md, projects/igniteui-angular/src/lib/core/styles/components/grid-summary/_grid-summary-theme.scss, projects/igniteui-angular/src/lib/grids/cell.component.ts, projects/igniteui-angular/src/lib/grids/summaries/summary-cell.component.html
=> Add tooltip to the grid data cell and summary cell

projects/igniteui-angular/src/lib/core/styles/typography/_typography.scss
=> fix(typography): incorrectly compiled custom typography styles

CHANGELOG.md, projects/igniteui-angular/src/lib/calendar/README.md, projects/igniteui-angular/src/lib/calendar/calendar-base.ts, projects/igniteui-angular/src/lib/calendar/calendar.component.spec.ts, projects/igniteui-angular/src/lib/calendar/calendar.component.ts, projects/igniteui-angular/src/lib/calendar/month-picker/README.md, projects/igniteui-angular/src/lib/calendar/month-picker/month-picker.component.ts, src/app/calendar-views/calendar-views.sample.html, src/app/calendar-views/calendar-views.sample.ts, src/app/calendar/calendar.sample.html, src/app/calendar/calendar.sample.ts
=> Remove on prefix from calendar events

angularDocsPostDeploy.ps1
=> docs(*): Fixing the order of versions in the dropDown

CHANGELOG.md, projects/igniteui-angular/src/lib/combo/combo.component.spec.ts, projects/igniteui-angular/src/lib/combo/combo.component.ts
=> Make onSearchInput cancellable v.9.1

projects/igniteui-angular/src/lib/core/styles/themes/schemas/dark/_chip.scss, projects/igniteui-angular/src/lib/core/styles/themes/schemas/light/_chip.scss
=> fix(chip): chip ghost background has low-contrast background

projects/igniteui-angular/src/lib/core/styles/components/grid/_grid-theme.scss
=> fix(grid): header icon and text jump on focus

projects/igniteui-angular/src/lib/core/styles/themes/schemas/dark/_list.scss, projects/igniteui-angular/src/lib/core/styles/themes/schemas/light/_list.scss
=> Fix list items background transparency

projects/igniteui-angular/src/lib/core/styles/themes/schemas/dark/_carousel.scss, projects/igniteui-angular/src/lib/core/styles/themes/schemas/light/_carousel.scss
=> fix(carousel): fix carousel docs & buttons low contrast

projects/igniteui-angular/src/lib/core/styles/themes/schemas/dark/_calendar.scss, projects/igniteui-angular/src/lib/core/styles/themes/schemas/light/_calendar.scss
=> fix(calendar): fix indigo calendar disabled days

projects/igniteui-angular/src/lib/core/styles/themes/schemas/dark/_time-picker.scss, projects/igniteui-angular/src/lib/core/styles/themes/schemas/light/_time-picker.scss
=> feat(time-picker): improve dark indigo time picker

projects/igniteui-angular/src/lib/core/styles/components/navdrawer/_navdrawer-theme.scss
This fixes the glued items in fluent and bootstrap themes and padding for items without an icon in indigo theme
=> Fix navdrawer issues

angularDocsPostDeploy.ps1
=> chore(*): Fixing the script

projects/igniteui-angular/src/lib/grids/cell.component.html, projects/igniteui-angular/src/lib/grids/common/grid-pipes.module.ts, projects/igniteui-angular/src/lib/grids/common/pipes.ts, projects/igniteui-angular/src/lib/grids/grid/column-resizing.spec.ts, projects/igniteui-angular/src/lib/grids/grid/expandable-cell.component.html, projects/igniteui-angular/src/lib/grids/grid/grid.component.spec.ts, projects/igniteui-angular/src/lib/grids/tree-grid/tree-cell.component.html
=> perf(grid): Apply column formatters through a pipe

projects/igniteui-angular/src/lib/core/styles/components/grid/_grid-component.scss, projects/igniteui-angular/src/lib/core/styles/components/grid/_grid-theme.scss
=> style(grid): add styles for boolean column

projects/igniteui-angular/src/lib/core/styles/components/button-group/_button-group-theme.scss
=> fix(grid): buttons style in ExcelStyleFiltering in IE11

CHANGELOG.md, projects/igniteui-angular/src/lib/grids/cell.component.html, projects/igniteui-angular/src/lib/grids/common/grid.interface.ts, projects/igniteui-angular/src/lib/grids/filtering/advanced-filtering/advanced-filtering-dialog.component.html, projects/igniteui-angular/src/lib/grids/filtering/base/grid-filtering-row.component.html, projects/igniteui-angular/src/lib/grids/filtering/base/grid-filtering-row.component.ts, projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-date-expression.component.html, projects/igniteui-angular/src/lib/grids/grid-base.directive.ts, projects/igniteui-angular/src/lib/grids/grid/expandable-cell.component.html, projects/igniteui-angular/src/lib/grids/headers/grid-header-group.component.html, projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid-base.directive.ts, projects/igniteui-angular/src/lib/grids/toolbar/grid-toolbar.component.ts, projects/igniteui-angular/src/lib/grids/tree-grid/tree-cell.component.html, src/app/grid-column-selection/grid-column-selection.sample.ts
=> feat(grid): create a setter for grid's outlet #7379

projects/igniteui-angular/src/lib/core/styles/components/button-group/_button-group-theme.scss
Reverts IgniteUI/igniteui-angular#7860
=> Revert "fix(grid): buttons style in ExcelStyleFiltering in IE11"

projects/igniteui-angular/src/lib/grids/common/pipes.ts, projects/igniteui-angular/src/lib/grids/grid/grid-row.component.html, projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-row.component.html, projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid-row.component.html
=> fix(grid): Row editing transaction styles

projects/igniteui-angular/src/lib/core/styles/components/grid/_grid-theme.scss, projects/igniteui-angular/src/lib/core/styles/themes/schemas/dark/_grid.scss, projects/igniteui-angular/src/lib/core/styles/themes/schemas/light/_grid.scss
=> fix(grid): header active styles are not applied correctly

projects/igniteui-angular/src/lib/grids/grid-base.directive.ts, projects/igniteui-angular/src/lib/grids/grid/grid-clipboard.spec.ts
=> Fix: Copied data is not correct when grid paging is enabled - 9.1.x

projects/igniteui-angular/src/lib/grids/grid-base.directive.ts, projects/igniteui-angular/src/lib/grids/grid/grid-clipboard.spec.ts
=> Fix: Copied data is not correct when grid paging is enabled

projects/igniteui-angular/src/lib/grids/grid-base.directive.ts, projects/igniteui-angular/src/lib/grids/grid/grid-clipboard.spec.ts
=> Fix: Copied data is not correct when grid paging is enabled - 10.0.x

projects/igniteui-angular/src/lib/core/styles/components/button-group/_button-group-theme.scss
=> Fix button-group buttons margin in safari

projects/igniteui-angular/src/lib/combo/combo.component.spec.ts, projects/igniteui-angular/src/lib/directives/autocomplete/autocomplete.directive.spec.ts, projects/igniteui-angular/src/lib/directives/input/input.directive.ts, projects/igniteui-angular/src/lib/input-group/input-group.component.html, projects/igniteui-angular/src/lib/input-group/input-group.component.ts, src/app/input-group/input-group.sample.ts
This change is needed to accommodate for runtime changes to the `type` prop.
Closes #7455
=> fix(input-group): allow runtime changes to type, prefix/suffix

projects/igniteui-angular/src/lib/grids/grid/grid-row-selection.spec.ts, projects/igniteui-angular/src/lib/grids/selection/selection.service.ts, projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid-selection.spec.ts, projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid.pipes.ts, src/app/grid-row-pinning/grid-row-pinning.sample.html
=> Fix(rowSelection): header check box state when there is row pinning or transactions - 9.1.x

projects/igniteui-angular/src/lib/grids/grid/grid-row-selection.spec.ts, projects/igniteui-angular/src/lib/grids/selection/selection.service.ts, projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid-selection.spec.ts, projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid.pipes.ts, src/app/grid-row-pinning/grid-row-pinning.sample.html
=> Fix(rowSelection): header check box state when there is row pinning or transactions

projects/igniteui-angular/src/lib/grids/grid/grid-row-selection.spec.ts, projects/igniteui-angular/src/lib/grids/selection/selection.service.ts, projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid-selection.spec.ts, projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid.pipes.ts, src/app/grid-row-pinning/grid-row-pinning.sample.html
=> Fix(rowSelection): header check box state when there is row pinning or transactions -- 10.0.x

projects/igniteui-angular/src/lib/core/styles/components/grid/_excel-filtering-theme.scss
=> fix(ESF): horizontal scrollbar

CHANGELOG.md, projects/igniteui-angular/src/lib/core/styles/components/button/_button-theme.scss, src/app/button/button.sample.html
=> feat(button): add extended button solution for span

projects/igniteui-angular/src/lib/grids/headers/grid-header.component.html
=> style(grid): change the default column header icon for ESF

projects/igniteui-angular/src/lib/core/styles/components/charts/_category-chart-component.scss, projects/igniteui-angular/src/lib/core/styles/components/charts/_data-chart-component.scss, projects/igniteui-angular/src/lib/core/styles/components/charts/_doughnut-chart-component.scss, projects/igniteui-angular/src/lib/core/styles/components/charts/_financial-chart-component.scss, projects/igniteui-angular/src/lib/core/styles/components/charts/_funnel-chart-component.scss, projects/igniteui-angular/src/lib/core/styles/components/charts/_gauge-component.scss, projects/igniteui-angular/src/lib/core/styles/components/charts/_geo-map-component.scss, projects/igniteui-angular/src/lib/core/styles/components/charts/_graph-component.scss, projects/igniteui-angular/src/lib/core/styles/components/charts/_pie-chart-component.scss, projects/igniteui-angular/src/lib/core/styles/components/charts/_shape-chart-component.scss, projects/igniteui-angular/src/lib/core/styles/components/charts/_sparkline-component.scss, projects/igniteui-angular/src/lib/core/styles/themes/_core.scss
=> fix(charts): make chart themes excludable

projects/igniteui-angular/src/lib/core/styles/components/grid/_excel-filtering-theme.scss
=> fix(ESF): misaligned icon

projects/igniteui-angular/src/lib/core/styles/base/utilities/_functions.scss
=> fix(themes): don't throw error on non-color values

projects/igniteui-angular/src/lib/core/deprecateDecorators.ts, projects/igniteui-angular/src/lib/grids/hiding/column-hiding.component.ts, projects/igniteui-angular/src/lib/grids/pinning/column-pinning.component.ts
=> Add class deprecation decorator and apply it for column actions.

projects/igniteui-angular/src/lib/core/styles/components/charts/_gauge-component.scss, projects/igniteui-angular/src/lib/core/styles/components/charts/_graph-component.scss
=> fix(themes): make dv components excludable

projects/igniteui-angular/src/lib/core/styles/components/grid/_excel-filtering-theme.scss
Closes #7929
The filter icon is not visible when the column is both filtered and selected
=> fix(indigo-theme): filter icon invisible

projects/igniteui-angular/src/lib/core/styles/components/dialog/_dialog-theme.scss
=> fix(dialog): wrong sizing in IE11 (9.1.x)

projects/igniteui-angular/src/lib/core/styles/components/dialog/_dialog-theme.scss
=> fix(dialog): wrong sizing in IE11 (10.0.x)

projects/igniteui-angular/src/lib/grids/grid-base.directive.ts
=> fix(grid): mark grid's outlet property as input

package-lock.json, package.json
=> chore(*): update typedoc theme version Closes #7927

LICENSE, package-lock.json, package.json, projects/igniteui-angular/ng-package.json, projects/igniteui-angular/ng-package.prod.json, projects/igniteui-angular/package.json, projects/igniteui-angular/schematics/utils/dependency-handler.ts, projects/igniteui-angular/src/lib/core/setImmediate.ts, projects/igniteui-angular/src/lib/core/utils.ts
=> Replace setImmediate and remove core-js-pure

projects/igniteui-angular/src/lib/slider/slider.component.ts
=> fix(slider): reqression expression change er

projects/igniteui-angular/package.json
=> chore(*): update igniteui/angular-schematics

projects/igniteui-angular/src/lib/slider/slider.component.ts
=> fix(slider): reqression expression change err Closes #7683

projects/igniteui-angular/src/lib/services/overlay/position/auto-position-strategy.ts
=> fix(esf): fixed bottom and right extend in auto position strategy - 9.1.x

projects/igniteui-angular/src/lib/services/overlay/position/auto-position-strategy.ts
=> fix(esf): fixed bottom and right extend in auto position strategy - 10.0.x

projects/igniteui-angular/src/lib/core/setImmediate.ts
=> Move window references inside method

projects/igniteui-angular/src/lib/navigation-drawer/navigation-drawer.component.ts
=> fix(navDrawer): Set width on open change #6321

projects/igniteui-angular/src/lib/grids/grid-base.directive.ts, projects/igniteui-angular/src/lib/grids/grid/grid.component.ts, projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid-summaries.spec.ts, src/app/grid-column-moving/grid-column-moving.sample.css, src/app/grid-column-moving/grid-column-moving.sample.html
=> Fix issue with height auto-size when page is zoomed.

projects/igniteui-angular/src/lib/grids/grid-base.directive.ts, projects/igniteui-angular/src/lib/grids/grid/grid.component.ts, src/app/grid-column-moving/grid-column-moving.sample.css, src/app/grid-column-moving/grid-column-moving.sample.html
=> Fix issue with height auto-size when page is zoomed. 

projects/igniteui-angular/src/lib/core/styles/components/column-hiding/_column-hiding-theme.scss, projects/igniteui-angular/src/lib/grids/hiding/column-hiding.component.html, projects/igniteui-angular/src/lib/grids/pinning/column-pinning.component.html, projects/igniteui-angular/src/lib/grids/toolbar/grid-toolbar.component.html, projects/igniteui-angular/src/lib/grids/toolbar/grid-toolbar.component.ts
=> fix(grid): Add columnHiding closing handler #7569

projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.selection.spec.ts, projects/igniteui-angular/src/lib/grids/hierarchical-grid/row-island.component.ts
=> Add selection service provider to child grid so that it does not use the parent one

projects/igniteui-angular/src/lib/grids/grid-base.directive.ts
=> fix(grid): properly account for custom row edit buttons - 9.1.x

projects/igniteui-angular/src/lib/grids/grid-base.directive.ts
=> fix(grid): properly account for custom row edit buttons - 10.0.x

projects/igniteui-angular/src/lib/grids/grid-base.directive.ts
=> fix(grid): properly account for custom row edit buttons - 10.1.х

projects/igniteui-angular/src/lib/slider/slider.component.spec.ts
=> test(slider): add aditional test for slider ticks

projects/igniteui-angular/src/lib/select/select.component.spec.ts, projects/igniteui-angular/src/lib/select/select.component.ts
=> Clear required & invalid styles

.angulardoc.json, projects/igniteui-angular/src/lib/time-picker/time-picker.component.html, projects/igniteui-angular/src/lib/time-picker/time-picker.component.spec.ts, projects/igniteui-angular/src/lib/time-picker/time-picker.component.ts
=> fix(time-picker): Adding igxTimeSelection to template, #6827

projects/igniteui-angular/src/lib/core/styles/components/column-hiding/_column-hiding-theme.scss, projects/igniteui-angular/src/lib/grids/hiding/column-hiding.component.html, projects/igniteui-angular/src/lib/grids/pinning/column-pinning.component.html, projects/igniteui-angular/src/lib/grids/toolbar/grid-toolbar.component.html, projects/igniteui-angular/src/lib/grids/toolbar/grid-toolbar.component.ts
=> fix(grid): Handle onClosing hiding/pinning #7569

projects/igniteui-angular/src/lib/core/styles/components/column-actions/_column-actions-theme.scss, projects/igniteui-angular/src/lib/grids/column-actions/column-actions.component.html, projects/igniteui-angular/src/lib/grids/toolbar/grid-toolbar.component.html, projects/igniteui-angular/src/lib/grids/toolbar/grid-toolbar.component.ts
=> fix(grid): Handle onclosing for hiding/pin #7569

.github/workflows/nodejs.yml, projects/igniteui-angular/src/lib/grids/cell.component.ts, projects/igniteui-angular/src/lib/grids/columns/column.component.ts, projects/igniteui-angular/src/lib/grids/grid/column-group.spec.ts, projects/igniteui-angular/src/lib/grids/grid/column.spec.ts, projects/igniteui-angular/src/lib/grids/grid/grid.component.html, projects/igniteui-angular/src/lib/grids/headers/grid-header-group.component.html, projects/igniteui-angular/src/lib/grids/headers/grid-header-group.component.ts, projects/igniteui-angular/src/lib/grids/headers/grid-header.component.html, projects/igniteui-angular/src/lib/grids/headers/grid-header.component.ts, projects/igniteui-angular/src/lib/grids/summaries/summary-cell.component.html
=> Remove igx-grid column component elementref

projects/igniteui-angular/src/lib/grids/cell.component.ts, projects/igniteui-angular/src/lib/grids/columns/column.component.ts, projects/igniteui-angular/src/lib/grids/grid/column-group.spec.ts, projects/igniteui-angular/src/lib/grids/grid/column.spec.ts, projects/igniteui-angular/src/lib/grids/grid/grid.component.html, projects/igniteui-angular/src/lib/grids/headers/grid-header-group.component.html, projects/igniteui-angular/src/lib/grids/headers/grid-header-group.component.ts, projects/igniteui-angular/src/lib/grids/headers/grid-header.component.html, projects/igniteui-angular/src/lib/grids/headers/grid-header.component.ts
=> Remove igx-grid column component elementref 10.0.x

projects/igniteui-angular/src/lib/grids/cell.component.ts, projects/igniteui-angular/src/lib/grids/columns/column.component.ts, projects/igniteui-angular/src/lib/grids/grid/column-group.spec.ts, projects/igniteui-angular/src/lib/grids/grid/column.spec.ts, projects/igniteui-angular/src/lib/grids/grid/grid.component.html, projects/igniteui-angular/src/lib/grids/headers/grid-header-group.component.html, projects/igniteui-angular/src/lib/grids/headers/grid-header-group.component.ts, projects/igniteui-angular/src/lib/grids/headers/grid-header.component.html, projects/igniteui-angular/src/lib/grids/headers/grid-header.component.ts
=> Remove igx-grid column component elementref 9.1.x

projects/igniteui-angular/migrations/migration-collection.json, projects/igniteui-angular/migrations/update-10_2_0/changes/inputs.json, projects/igniteui-angular/migrations/update-10_2_0/index.spec.ts, projects/igniteui-angular/migrations/update-10_2_0/index.ts, projects/igniteui-angular/src/lib/combo/combo.component.html, projects/igniteui-angular/src/lib/core/styles/components/combo/_combo-theme.scss, projects/igniteui-angular/src/lib/core/styles/components/grid/_grid-theme.scss, projects/igniteui-angular/src/lib/core/styles/components/input/_input-group-component.scss, projects/igniteui-angular/src/lib/core/styles/components/input/_input-group-theme.scss, projects/igniteui-angular/src/lib/core/styles/themes/schemas/light/_input-group.scss, projects/igniteui-angular/src/lib/date-picker/date-picker.component.spec.ts, projects/igniteui-angular/src/lib/grids/filtering/advanced-filtering/advanced-filtering-dialog.component.html, projects/igniteui-angular/src/lib/input-group/input-group.component.html, projects/igniteui-angular/src/lib/input-group/input-group.component.spec.ts, projects/igniteui-angular/src/lib/input-group/input-group.component.ts, projects/igniteui-angular/src/lib/time-picker/time-picker.component.spec.ts, src/app/input-group/input-group.sample.html, src/app/input-group/input-group.sample.scss, src/app/input-group/input-group.sample.ts
Closes #  
https://github.com/IgniteUI/igniteui-angular-samples/pull/2204
https://github.com/IgniteUI/igniteui-docfx/pull/2172
=> Input Group: Change styling implicitly based on theme, not type

projects/igniteui-angular/src/lib/combo/combo.component.html, projects/igniteui-angular/src/lib/combo/combo.component.spec.ts, projects/igniteui-angular/src/lib/combo/combo.component.ts
=> fix(combo): fix error in searchvalue handling - 9.1.x

projects/igniteui-angular/src/lib/combo/combo.component.html, projects/igniteui-angular/src/lib/combo/combo.component.spec.ts, projects/igniteui-angular/src/lib/combo/combo.component.ts
=> fix(combo): fix error in searchvalue handling - 10.0.x

projects/igniteui-angular/src/lib/combo/combo.component.html, projects/igniteui-angular/src/lib/combo/combo.component.spec.ts, projects/igniteui-angular/src/lib/combo/combo.component.ts
=> fix(combo): fix error in searchvalue handling - 10.1.x

projects/igniteui-angular/src/lib/core/styles/components/grid/_grid-theme.scss
=> fix(grid): column sorting indicator wrong background color

projects/igniteui-angular/src/lib/directives/autocomplete/autocomplete.directive.spec.ts, projects/igniteui-angular/src/lib/directives/autocomplete/autocomplete.directive.ts
=> fix(autocomplete): close dropdown when list is empty - 9.1.x

projects/igniteui-angular/src/lib/directives/autocomplete/autocomplete.directive.spec.ts, projects/igniteui-angular/src/lib/directives/autocomplete/autocomplete.directive.ts
=> fix(autocomplete): close dropdown when list is empty - 10.0.x

projects/igniteui-angular/src/lib/directives/autocomplete/autocomplete.directive.spec.ts, projects/igniteui-angular/src/lib/directives/autocomplete/autocomplete.directive.ts
=> fix(autocomplete): close dropdown when list is empty - 10.1.x

projects/igniteui-angular/src/lib/directives/autocomplete/autocomplete.directive.spec.ts, projects/igniteui-angular/src/lib/directives/autocomplete/autocomplete.directive.ts
=> fix(autocomplete): close dropdown when list is empty - 10.2.x

projects/igniteui-angular/src/lib/core/styles/components/grid/_grid-theme.scss
=> fix(theme): fluent header and body misalignment

projects/igniteui-angular/src/lib/core/styles/components/grid/_grid-theme.scss
=> Fix grid cells misalignment in fluent theme

projects/igniteui-angular/src/lib/core/styles/components/input/_input-group-theme.scss
=> refactor(input-group): prefix/suffix not rendering correctly

projects/igniteui-angular/src/lib/grids/filtering/advanced-filtering/advanced-filtering-dialog.component.ts, projects/igniteui-angular/src/lib/grids/filtering/grid-filtering.service.ts, projects/igniteui-angular/src/lib/grids/grid-base.directive.ts, projects/igniteui-angular/src/lib/grids/grid/grid-keyBoardNav-headers.spec.ts, projects/igniteui-angular/src/lib/grids/grid/grid.component.html, projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.component.html, projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid.component.html
=> Remove active node when the container lose focus -- 9.1.x

projects/igniteui-angular/src/lib/grids/filtering/advanced-filtering/advanced-filtering-dialog.component.ts, projects/igniteui-angular/src/lib/grids/filtering/grid-filtering.service.ts, projects/igniteui-angular/src/lib/grids/grid-base.directive.ts, projects/igniteui-angular/src/lib/grids/grid/grid-keyBoardNav-headers.spec.ts, projects/igniteui-angular/src/lib/grids/grid/grid.component.html, projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.component.html, projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid.component.html
=> Remove active node when the container lose focus

projects/igniteui-angular/src/lib/grids/filtering/advanced-filtering/advanced-filtering-dialog.component.ts, projects/igniteui-angular/src/lib/grids/filtering/grid-filtering.service.ts, projects/igniteui-angular/src/lib/grids/grid-base.directive.ts, projects/igniteui-angular/src/lib/grids/grid/grid-keyBoardNav-headers.spec.ts, projects/igniteui-angular/src/lib/grids/grid/grid.component.html, projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.component.html, projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid.component.html
=> Remove active node when the container lose focus --master

projects/igniteui-angular/src/lib/core/styles/components/calendar/_calendar-theme.scss, projects/igniteui-angular/src/lib/core/styles/components/date-picker/_date-picker-theme.scss
=> fix(date-picker): IE11 problem with date size.

projects/igniteui-angular/src/lib/date-picker/date-picker.component.spec.ts, projects/igniteui-angular/src/lib/date-picker/date-picker.component.ts, projects/igniteui-angular/src/lib/grids/grid/grid-filtering-ui.spec.ts
=> Add validation when disabledDates in date picker is set v.9.1

projects/igniteui-angular/src/lib/date-picker/date-picker.component.spec.ts, projects/igniteui-angular/src/lib/date-picker/date-picker.component.ts, projects/igniteui-angular/src/lib/grids/grid/grid-filtering-ui.spec.ts
=> Add validation when disabledDates in date picker is set v.10.0

projects/igniteui-angular/src/lib/date-picker/date-picker.component.spec.ts, projects/igniteui-angular/src/lib/date-picker/date-picker.component.ts, projects/igniteui-angular/src/lib/grids/grid/grid-filtering-ui.spec.ts
=> Add validation when disabledDates in date picker is set v.10.1

projects/igniteui-angular/src/lib/date-picker/date-picker.component.spec.ts, projects/igniteui-angular/src/lib/date-picker/date-picker.component.ts, projects/igniteui-angular/src/lib/grids/grid/grid-filtering-ui.spec.ts
=> Add validation when disabledDates in date picker is set v.10.2 #7995 

ROADMAP.md
=> chore(*): Update Roadmap M13 v1

projects/igniteui-angular/src/lib/calendar/month-picker/month-picker.component.html, projects/igniteui-angular/src/lib/calendar/month-picker/month-picker.component.spec.ts, projects/igniteui-angular/src/lib/calendar/month-picker/month-picker.component.ts
=> igx-month-picker should emit onSelection only when the selected month is changed - 9.1.x

projects/igniteui-angular/src/lib/calendar/month-picker/month-picker.component.html, projects/igniteui-angular/src/lib/calendar/month-picker/month-picker.component.spec.ts, projects/igniteui-angular/src/lib/calendar/month-picker/month-picker.component.ts
=> igx-month-picker should emit onSelection only when the selected month is changed - 10.1.x

projects/igniteui-angular/src/lib/avatar/avatar.component.ts, projects/igniteui-angular/src/lib/badge/badge.component.ts, projects/igniteui-angular/src/lib/calendar/calendar-base.ts, projects/igniteui-angular/src/lib/card/card.component.ts, projects/igniteui-angular/src/lib/carousel/carousel.component.ts, projects/igniteui-angular/src/lib/checkbox/checkbox.component.ts, projects/igniteui-angular/src/lib/core/displayDensity.ts, projects/igniteui-angular/src/lib/core/utils.ts, projects/igniteui-angular/src/lib/data-operations/data-util.ts, projects/igniteui-angular/src/lib/date-picker/date-picker.component.ts, projects/igniteui-angular/src/lib/directives/divider/divider.directive.ts, projects/igniteui-angular/src/lib/drop-down/drop-down.common.ts, projects/igniteui-angular/src/lib/expansion-panel/expansion-panel-header.component.ts, projects/igniteui-angular/src/lib/grids/column-chooser-base.ts, projects/igniteui-angular/src/lib/grids/common/enums.ts, projects/igniteui-angular/src/lib/grids/grid-base.directive.ts, projects/igniteui-angular/src/lib/progressbar/progressbar.component.ts, projects/igniteui-angular/src/lib/radio/radio.component.ts, projects/igniteui-angular/src/lib/switch/switch.component.ts, projects/igniteui-angular/src/lib/tabs/tabs.component.ts, src/app/grid-groupby/grid-groupby.sample.ts
=> fix(inputs): use full union types on all string @Input properties - 9.1

projects/igniteui-angular/src/lib/avatar/avatar.component.ts, projects/igniteui-angular/src/lib/badge/badge.component.ts, projects/igniteui-angular/src/lib/calendar/calendar-base.ts, projects/igniteui-angular/src/lib/card/card.component.ts, projects/igniteui-angular/src/lib/carousel/carousel.component.ts, projects/igniteui-angular/src/lib/checkbox/checkbox.component.ts, projects/igniteui-angular/src/lib/core/displayDensity.ts, projects/igniteui-angular/src/lib/core/utils.ts, projects/igniteui-angular/src/lib/data-operations/data-util.ts, projects/igniteui-angular/src/lib/date-picker/date-picker.component.ts, projects/igniteui-angular/src/lib/directives/divider/divider.directive.ts, projects/igniteui-angular/src/lib/drop-down/drop-down.common.ts, projects/igniteui-angular/src/lib/expansion-panel/expansion-panel-header.component.ts, projects/igniteui-angular/src/lib/grids/column-chooser-base.ts, projects/igniteui-angular/src/lib/grids/common/enums.ts, projects/igniteui-angular/src/lib/grids/grid-base.directive.ts, projects/igniteui-angular/src/lib/progressbar/progressbar.component.ts, projects/igniteui-angular/src/lib/radio/radio.component.ts, projects/igniteui-angular/src/lib/switch/switch.component.ts, projects/igniteui-angular/src/lib/tabs/tabs.component.ts, src/app/grid-groupby/grid-groupby.sample.ts
=> fix(inputs): use full union types on all string @Input properties - 10.0.x

projects/igniteui-angular/src/lib/avatar/avatar.component.ts, projects/igniteui-angular/src/lib/badge/badge.component.ts, projects/igniteui-angular/src/lib/calendar/calendar-base.ts, projects/igniteui-angular/src/lib/card/card.component.ts, projects/igniteui-angular/src/lib/carousel/carousel.component.ts, projects/igniteui-angular/src/lib/checkbox/checkbox.component.ts, projects/igniteui-angular/src/lib/core/displayDensity.ts, projects/igniteui-angular/src/lib/core/utils.ts, projects/igniteui-angular/src/lib/data-operations/data-util.ts, projects/igniteui-angular/src/lib/date-picker/date-picker.component.ts, projects/igniteui-angular/src/lib/directives/divider/divider.directive.ts, projects/igniteui-angular/src/lib/drop-down/drop-down.common.ts, projects/igniteui-angular/src/lib/expansion-panel/expansion-panel-header.component.ts, projects/igniteui-angular/src/lib/grids/column-actions/column-actions.component.ts, projects/igniteui-angular/src/lib/grids/column-chooser-base.ts, projects/igniteui-angular/src/lib/grids/common/enums.ts, projects/igniteui-angular/src/lib/grids/grid-base.directive.ts, projects/igniteui-angular/src/lib/progressbar/progressbar.component.ts, projects/igniteui-angular/src/lib/radio/radio.component.ts, projects/igniteui-angular/src/lib/switch/switch.component.ts, projects/igniteui-angular/src/lib/tabs/tabs.component.ts, src/app/grid-groupby/grid-groupby.sample.ts
=> fix(inputs): use full union types on all string @Input properties - 10.1.x

src/app/action-strip/action-strip.sample.ts, src/app/combo/combo.sample.ts
=> fix(grid-demos): Set DisplayDensity type #6636

projects/igniteui-angular/src/lib/badge/badge.component.html, projects/igniteui-angular/src/lib/badge/badge.component.ts
=> Adding string | number type to value on igx-badge

projects/igniteui-angular/src/lib/badge/badge.component.html, projects/igniteui-angular/src/lib/badge/badge.component.ts
=> fix(badge): adding type for value #8077

projects/igniteui-angular/src/lib/core/styles/components/input/_input-group-component.scss, projects/igniteui-angular/src/lib/core/styles/components/input/_input-group-theme.scss
=> fix(input-group): fix textarea width to not overlap the suffix

src/app/action-strip/action-strip.sample.ts, src/app/combo/combo.sample.ts
=> fix(grid-demos): Set DisplayDensity type #6636 9.1.x

src/app/action-strip/action-strip.sample.ts, src/app/combo/combo.sample.ts
=> fix(grid-demos): Set DisplayDensity type #6636 10.1.x

projects/igniteui-angular/src/lib/combo/combo.component.html, projects/igniteui-angular/src/lib/combo/combo.component.spec.ts, projects/igniteui-angular/src/lib/combo/combo.component.ts, src/app/combo/combo.sample.html, src/app/combo/combo.sample.ts
=> Combo model validation fixes  10.1

projects/igniteui-angular/src/lib/combo/combo.component.html, projects/igniteui-angular/src/lib/combo/combo.component.spec.ts, projects/igniteui-angular/src/lib/combo/combo.component.ts, src/app/combo/combo.sample.html, src/app/combo/combo.sample.ts
=> Combo model validation fixes

projects/igniteui-angular/src/lib/grids/grid-base.directive.ts
=> fix(grid): fix reordering logic when MCH #8092

projects/igniteui-angular/src/lib/grids/grid-base.directive.ts
=> Fix columns reordering logic when MCH #8114

projects/igniteui-angular/src/lib/grids/grid-base.directive.ts
=> Fix columns reordering logic when MCH

projects/igniteui-angular/src/lib/grids/cell.component.ts, projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-cell.component.ts, projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid-navigation.service.ts, projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.selection.spec.ts
=> Enhance multi-cell selection in hierarchical grid -- master

projects/igniteui-angular/src/lib/grids/cell.component.ts, projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-cell.component.ts, projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid-navigation.service.ts, projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.selection.spec.ts
=> Enhance multi-cell selection in hierarchical grid -- 9.1.x

projects/igniteui-angular/src/lib/directives/scroll-inertia/scroll_inertia.directive.ts
=> fix(igxGrid): zoom in/out with ctrl + mouse scroll when the mouse lies over the igxGrid body 10.0.x

projects/igniteui-angular/src/lib/core/styles/components/grid/_grid-theme.scss, projects/igniteui-angular/src/lib/core/styles/components/icon/_icon-component.scss, projects/igniteui-angular/src/lib/core/styles/components/icon/_icon-theme.scss, projects/igniteui-angular/src/lib/grids/cell.component.html, projects/igniteui-angular/src/lib/grids/tree-grid/tree-cell.component.html
=> fix(grid): improve bool cell style templating

projects/igniteui-angular/src/lib/core/styles/base/elevations/_index.scss, projects/igniteui-angular/src/lib/core/styles/base/utilities/_functions.scss
=> fix(theming): retrofit bug fixes from newer versions

projects/igniteui-angular/src/lib/avatar/README.md, projects/igniteui-angular/src/lib/avatar/avatar.component.ts
Related issue: IgniteUI/igniteui-docfx/issues/2223
=> docs(avatar): add missing brackets

.travis.yml
=> chore(*): update dpks before install

CHANGELOG.md
=> chore(*): Update changelog with `showWeekNumbers`

CHANGELOG.md, projects/igniteui-angular/src/lib/select/select.component.html, projects/igniteui-angular/src/lib/select/select.component.spec.ts
=>  Add aria-labelledby for listbox - 9.1.x

CHANGELOG.md, projects/igniteui-angular/src/lib/select/select.component.html, projects/igniteui-angular/src/lib/select/select.component.spec.ts
=> Add aria-labelledby for listbox - 10.1.x

projects/igniteui-angular/src/lib/grids/grid/grid-cell-editing.spec.ts, projects/igniteui-angular/src/lib/grids/grid/grid-row-editing.spec.ts
=> test(grid): add some grid editing evt tests

projects/igniteui-angular/src/lib/calendar/calendar-multi-view.component.spec.ts, projects/igniteui-angular/src/lib/calendar/calendar.component.spec.ts, projects/igniteui-angular/src/lib/calendar/calendar.component.ts, projects/igniteui-angular/src/lib/calendar/month-picker/month-picker.component.spec.ts, projects/igniteui-angular/src/lib/calendar/month-picker/month-picker.component.ts
=> Month picker should not thrown an error when navigating with PgUp and PgDown - 9.1.x

CHANGELOG.md, projects/igniteui-angular/src/lib/date-picker/date-picker.component.spec.ts, projects/igniteui-angular/src/lib/date-picker/date-picker.component.ts
=> fix(datepcker): Add aria attribute #8080

CHANGELOG.md, projects/igniteui-angular/src/lib/date-picker/date-picker.component.spec.ts, projects/igniteui-angular/src/lib/date-picker/date-picker.component.ts
=> Add aria-labelledby for input field - 10.1.x

projects/igniteui-angular/src/lib/core/styles/components/grid/_grid-component.scss, projects/igniteui-angular/src/lib/grids/filtering/base/grid-filtering-cell.component.html, projects/igniteui-angular/src/lib/grids/filtering/base/grid-filtering-cell.component.ts, projects/igniteui-angular/src/lib/grids/filtering/base/grid-filtering-row.component.html, projects/igniteui-angular/src/lib/grids/filtering/base/grid-filtering-row.component.ts
=> Make filtering row respect grid's display density

projects/igniteui-angular/src/lib/input-group/input-group.component.html, projects/igniteui-angular/src/lib/input-group/input-group.component.ts
=> fix(input-group): prevent focusing input on hint click

projects/igniteui-angular/src/lib/core/styles/components/navdrawer/_navdrawer-component.scss, projects/igniteui-angular/src/lib/core/styles/components/navdrawer/_navdrawer-theme.scss
=> fix(navdrawer): disable flex shrink

projects/igniteui-angular/src/lib/date-picker/date-picker.utils.ts, projects/igniteui-angular/src/lib/directives/date-time-editor/date-time-parsing.spec.ts
=> Fix parsing of month part of typed dates

projects/igniteui-angular/src/lib/date-picker/date-picker.utils.ts, projects/igniteui-angular/src/lib/directives/date-time-editor/date-time-parsing.spec.ts
=> Fix parsing of month part of typed dates - 10.1.x

projects/igniteui-angular/src/lib/date-picker/date-picker.utils.ts, projects/igniteui-angular/src/lib/directives/date-time-editor/date-time-parsing.spec.ts
=> Fix parsing of month part of typed dates - 9.1.x

projects/igniteui-angular/src/lib/date-range-picker/date-range-picker.component.spec.ts, projects/igniteui-angular/src/lib/date-range-picker/date-range-picker.component.ts
=> Disable DateRange if disabled is true - 10.1.x

projects/igniteui-angular/src/lib/date-range-picker/date-range-picker.component.spec.ts, projects/igniteui-angular/src/lib/date-range-picker/date-range-picker.component.ts
=> Disable DateRange if disabled is true - 9.1.x

projects/igniteui-angular/src/lib/grids/grid-base.directive.ts, projects/igniteui-angular/src/lib/grids/grid-mrl-navigation.service.ts, projects/igniteui-angular/src/lib/grids/grid/grid.multi-row-layout.spec.ts
=> NavigateTo fails to scroll to targeted row in MRL context scenario - 10.0

projects/igniteui-angular/src/lib/grids/grid-base.directive.ts, projects/igniteui-angular/src/lib/grids/grid-mrl-navigation.service.ts, projects/igniteui-angular/src/lib/grids/grid/grid.multi-row-layout.spec.ts
=> NavigateTo fails to scroll to targeted row in MRL context scenario - 10.1

projects/igniteui-angular/src/lib/core/styles/components/date-picker/_date-picker-theme.scss
=> fix(datepicker): fix vertical datepicker max-width

projects/igniteui-angular/src/lib/grids/cell.component.ts, projects/igniteui-angular/src/lib/grids/grid/grid-cell-selection.spec.ts
=> Do not exit editing on RMBClick & allow copy/paste using context menu - 10.1.x

projects/igniteui-angular/src/lib/grids/cell.component.ts, projects/igniteui-angular/src/lib/grids/grid/grid-cell-selection.spec.ts
=> Do not exit editing on RMBClick & allow copy/paste using context menu - 9.1.x

projects/igniteui-angular/src/lib/directives/toggle/toggle.directive.ts, projects/igniteui-angular/src/lib/grids/grid-base.directive.ts, projects/igniteui-angular/src/lib/grids/grid.common.ts
=> fix(grid): hides editing row when scrolling horizontally

projects/igniteui-angular/src/lib/directives/toggle/toggle.directive.ts, projects/igniteui-angular/src/lib/grids/grid-base.directive.ts, projects/igniteui-angular/src/lib/grids/grid.common.ts
=> refactor(grid): do not hide editing row on scroll

projects/igniteui-angular/src/lib/expansion-panel/expansion-panel.spec.ts, projects/igniteui-angular/src/lib/grids/grid-base.directive.ts, projects/igniteui-angular/src/lib/grids/grid/grid-add-row.spec.ts, projects/igniteui-angular/src/lib/grids/grid/grid.component.html, projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.component.html, projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid.component.html, projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid.component.ts, src/app/grid-add-row/grid-add-row.sample.html
Closes #8253  
Note: Show button should behave like Search. For example, if target is on another page, should go to that page. If row is in collapsed group, should expand that group to show the row.
=> Row Adding jump to added row - Integration w/ features

projects/igniteui-angular/src/lib/grids/grid.rowEdit.directive.ts
=> docs(grid): add @internal to row edit template directives

projects/igniteui-angular/src/lib/time-picker/time-picker.component.html, projects/igniteui-angular/src/lib/time-picker/time-picker.component.spec.ts, projects/igniteui-angular/src/lib/time-picker/time-picker.component.ts
=> Set mask to TimePicker's editor on clear

projects/igniteui-angular/src/lib/core/styles/components/action-strip/_action-strip-theme.scss
=> docs(action-strip): fix sassdoc

projects/igniteui-angular/src/lib/combo/combo.component.spec.ts, projects/igniteui-angular/src/lib/combo/combo.component.ts
=> fix(combo): don't clear items when disabled #8200

projects/igniteui-angular/src/lib/toast/toast.component.ts
=> fix(toast): compatibility enum const and type

projects/igniteui-angular/src/lib/time-picker/time-picker.component.spec.ts, projects/igniteui-angular/src/lib/time-picker/time-picker.component.ts
=> Emit onValueChanged if 00:00 is cleared - 9.1.x

projects/igniteui-angular/src/lib/time-picker/time-picker.component.spec.ts, projects/igniteui-angular/src/lib/time-picker/time-picker.component.ts
=> Emit onValueChanged if 00:00 is cleared - 10.1.x

projects/igniteui-angular/src/lib/grids/row.directive.ts
=> Add class specific to grid new row.

projects/igniteui-angular/src/lib/time-picker/time-picker.component.spec.ts, projects/igniteui-angular/src/lib/time-picker/time-picker.component.ts
=> Emit onValueChanged if 00:00 is cleared

package-lock.json, package.json, projects/igniteui-angular/ng-package.json, projects/igniteui-angular/ng-package.prod.json, projects/igniteui-angular/package.json, projects/igniteui-angular/schematics/utils/dependency-handler.ts
=> build(*): adding explicit deps to uuid

projects/igniteui-angular/src/lib/grids/grid-base.directive.ts
=> fix(igxGrid): If add row is not fully in view, scroll it in view.

projects/igniteui-angular/src/lib/services/overlay/overlay.ts, projects/igniteui-angular/src/lib/services/overlay/utilities.ts, src/app/overlay/overlay-presets.sample.ts
=> Fix preset OverlaySettings enums & sample

projects/igniteui-angular/src/lib/services/overlay/overlay.spec.ts, projects/igniteui-angular/src/lib/services/overlay/overlay.ts
We are checking now it the target has contains method before call it.
Closes #8297
=> Handle correctly target as point

projects/igniteui-angular/src/lib/action-strip/grid-actions/grid-actions-base.directive.ts, projects/igniteui-angular/src/lib/action-strip/grid-actions/grid-editing-actions.component.spec.ts
=> fix(action-strip): Do not show grid actions if the row is in edit mode

projects/igniteui-angular/src/lib/core/styles/themes/schemas/light/_grid.scss
=> fix(themes): header subgroups active border

projects/igniteui-angular/migrations/update-10_2_0/changes/members.json
=> fix(grid): add members migrations for editing events

projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-conditional-filter.component.ts, projects/igniteui-angular/src/lib/grids/filtering/grid-filtering.service.ts, projects/igniteui-angular/src/lib/grids/grid/grid-filtering-ui.spec.ts, projects/igniteui-angular/src/lib/grids/headers/grid-header.component.ts, projects/igniteui-angular/src/lib/test-utils/grid-samples.spec.ts
=> fix(grid): Exec onOpening once per column #8138

projects/igniteui-angular/src/lib/grids/filtering/excel-style/grid.excel-style-filtering.component.ts, projects/igniteui-angular/src/lib/grids/grid/grid-filtering-ui.spec.ts, projects/igniteui-angular/src/lib/test-utils/grid-samples.spec.ts, projects/igniteui-angular/src/lib/test-utils/sample-test-data.spec.ts
=> Don't duplicate records in esf menu when filteringIgnoreCase is true

projects/igniteui-angular/package.json
=> chore(schematics): update to 10.2.620-beta.0

projects/igniteui-angular/src/lib/grids/filtering/excel-style/grid.excel-style-filtering.component.ts, projects/igniteui-angular/src/lib/grids/grid/grid-filtering-ui.spec.ts, projects/igniteui-angular/src/lib/test-utils/grid-samples.spec.ts, projects/igniteui-angular/src/lib/test-utils/sample-test-data.spec.ts
=> Don't duplicate records in esf menu when filteringIgnoreCase is true.

projects/igniteui-angular/src/lib/directives/for-of/for_of.directive.ts, projects/igniteui-angular/src/lib/grids/grid-base.directive.ts
=> fix(grid): async router-outlet triggers onDestroy before ngOnInit

CHANGELOG.md, projects/igniteui-angular/src/lib/date-range-picker/date-range-picker.component.spec.ts, projects/igniteui-angular/src/lib/date-range-picker/date-range-picker.component.ts, projects/igniteui-angular/src/lib/grids/cell.component.html, projects/igniteui-angular/src/lib/grids/columns/column.component.ts, projects/igniteui-angular/src/lib/grids/columns/interfaces.ts, projects/igniteui-angular/src/lib/grids/common/column.interface.ts, projects/igniteui-angular/src/lib/grids/common/grid-pipes.module.ts, projects/igniteui-angular/src/lib/grids/common/grid.interface.ts, projects/igniteui-angular/src/lib/grids/common/pipes.ts, projects/igniteui-angular/src/lib/grids/filtering/advanced-filtering/advanced-filtering-dialog.component.html, projects/igniteui-angular/src/lib/grids/filtering/advanced-filtering/advanced-filtering-dialog.component.ts, projects/igniteui-angular/src/lib/grids/filtering/base/grid-filtering-row.component.html, projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-date-expression.component.html, projects/igniteui-angular/src/lib/grids/filtering/excel-style/grid.excel-style-filtering.component.ts, projects/igniteui-angular/src/lib/grids/filtering/grid-filtering.service.ts, projects/igniteui-angular/src/lib/grids/grid-base.directive.ts, projects/igniteui-angular/src/lib/grids/grid/expandable-cell.component.html, projects/igniteui-angular/src/lib/grids/grid/grid-summary.spec.ts, projects/igniteui-angular/src/lib/grids/grid/grid.component.spec.ts, projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid-base.directive.ts, projects/igniteui-angular/src/lib/grids/hierarchical-grid/row-island.component.ts, projects/igniteui-angular/src/lib/grids/public_api.ts, projects/igniteui-angular/src/lib/grids/summaries/grid-summary.service.ts, projects/igniteui-angular/src/lib/grids/summaries/grid-summary.ts, projects/igniteui-angular/src/lib/grids/summaries/summary-cell.component.html, projects/igniteui-angular/src/lib/grids/tree-grid/tree-cell.component.html, projects/igniteui-angular/src/lib/test-utils/grid-samples.spec.ts, projects/igniteui-angular/src/lib/test-utils/tree-grid-components.spec.ts
=> IgxDatePipe handle Date strings, localize Date summaries

projects/igniteui-angular/src/lib/services/public_api.ts
=> Add overlay enums to public api

projects/igniteui-angular/migrations/common/tsLogger.ts
=> Do not log if traceToConsole is false

projects/igniteui-angular/src/lib/calendar/calendar.component.html, projects/igniteui-angular/src/lib/calendar/calendar.component.ts, projects/igniteui-angular/src/lib/calendar/days-view/days-view.component.ts
=> Changing month in the calendar should not throws an exception

projects/igniteui-angular/src/lib/calendar/public_api.ts, src/app/calendar/calendar.sample.ts
=> Expose calendar base in calendar public Api

projects/igniteui-angular/src/lib/grids/cell.component.html, projects/igniteui-angular/src/lib/grids/tree-grid/tree-cell.component.html
=> Do not include bool values in the search range

projects/igniteui-angular/migrations/common/UpdateChanges.spec.ts, projects/igniteui-angular/migrations/common/tsUtils.ts
=> chore(migrations): class rename - check properly handles both packages

projects/igniteui-angular/src/lib/grids/grid-base.directive.ts
=> Generate correct id based on data type of primary column

projects/igniteui-angular/src/lib/grids/cell.component.ts
=> Make add row use cell template if provided

projects/igniteui-angular/package.json
=> chore(schematics): put latest schematics

projects/igniteui-angular/src/lib/grids/filtering/excel-style/grid.excel-style-filtering.component.ts
=> fix(esf): convert values to string before applying toLowerCase

projects/igniteui-angular/src/lib/grids/column-actions/column-actions-base.directive.ts, projects/igniteui-angular/src/lib/grids/column-actions/column-hiding.directive.ts, projects/igniteui-angular/src/lib/grids/column-actions/column-pinning.directive.ts, src/app/grid-column-actions/custom-action-directive.ts
=> Make getters of check/uncheck labels for different actions

angular.json, package.json, projects/igniteui-angular/src/lib/date-picker/date-picker.component.ts, projects/igniteui-angular/src/lib/directives/mask/mask.directive.ts, src/tsconfig-es5.app.json
=> Prevent IE from focusing DatePicker onload - 9.1.x

angular.json, package.json, projects/igniteui-angular/src/lib/date-picker/date-picker.component.ts, projects/igniteui-angular/src/lib/directives/mask/mask.directive.ts, src/tsconfig-es5.app.json
=> Prevent IE from focusing DatePicker onload - 10.1.x

projects/igniteui-angular/src/lib/core/utils.ts, projects/igniteui-angular/src/lib/grids/grid-navigation.service.ts
=> fix(addRow): Fix keyboard combination for IE and Edge

angular.json, package.json, projects/igniteui-angular/src/lib/date-picker/date-picker.component.ts, projects/igniteui-angular/src/lib/directives/mask/mask.directive.ts, src/tsconfig-es5.app.json
=> Prevent IE from focusing DatePicker onload

projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-search.component.ts, projects/igniteui-angular/src/lib/grids/grid/grid-filtering-ui.spec.ts
=> Clear search input on ESC

projects/igniteui-angular/src/lib/grids/api.service.ts, projects/igniteui-angular/src/lib/grids/grid-base.directive.ts, projects/igniteui-angular/src/lib/grids/grid/grid.component.spec.ts, projects/igniteui-angular/src/lib/grids/grid/grid.component.ts, projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.component.ts, projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid.component.ts
=> fix(grid): loading not showing in empty filtered grids #8279 - 10.2

projects/igniteui-angular/src/lib/grids/api.service.ts, projects/igniteui-angular/src/lib/grids/grid-base.directive.ts, projects/igniteui-angular/src/lib/grids/grid/grid.component.spec.ts, projects/igniteui-angular/src/lib/grids/grid/grid.component.ts, projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.component.ts, projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid.component.ts
=> fix(grid): loading not showing in empty filtered grids #8279 - 9.1

projects/igniteui-angular/src/lib/grids/api.service.ts, projects/igniteui-angular/src/lib/grids/grid-base.directive.ts, projects/igniteui-angular/src/lib/grids/grid/grid.component.spec.ts, projects/igniteui-angular/src/lib/grids/grid/grid.component.ts, projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.component.ts, projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid.component.ts
=> fix(grid): loading not showing in empty filtered grids #8279 - 10.1

projects/igniteui-angular/src/lib/action-strip/grid-actions/grid-action-button.component.html, projects/igniteui-angular/src/lib/action-strip/grid-actions/grid-action-button.component.ts
=> fix(*): stop propagation on mousedown so that focusTbody is not called on Safari

angular.json, package.json, projects/igniteui-angular/src/lib/grids/row.directive.ts, src/polyfills.ts, src/styles/igniteui-theme.scss, src/tsconfig-es5.app.json
Closes #8408   
Note: Also adding config and command for running the dev samples in IE.
=> Fix adding row editor height in IE.

projects/igniteui-angular/src/lib/grids/filtering/excel-style/grid.excel-style-filtering.component.ts, projects/igniteui-angular/src/lib/grids/grid/grid-filtering-ui.spec.ts
=> fix(grid): Do not execute done for null col #8388

projects/igniteui-angular/src/lib/grids/filtering/excel-style/grid.excel-style-filtering.component.ts, projects/igniteui-angular/src/lib/grids/grid/grid-filtering-ui.spec.ts
=> clear search criteria when selecting "Clear column filters" option

projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-search.component.ts, projects/igniteui-angular/src/lib/grids/grid/grid-filtering-ui.spec.ts
=> fix(esf): clear search criteria after closing esf menu with templates

projects/igniteui-angular/src/lib/dialog/dialog.component.spec.ts, projects/igniteui-angular/src/lib/dialog/dialog.component.ts, projects/igniteui-angular/src/lib/grids/grid/grid-cell-selection.spec.ts
=> fix(dialog): exposed opened property-10.1.x #8320

projects/igniteui-angular/src/lib/dialog/dialog.component.spec.ts, projects/igniteui-angular/src/lib/dialog/dialog.component.ts, projects/igniteui-angular/src/lib/grids/grid/grid-cell-selection.spec.ts
=> fix(dialog): exposed opened property-9.1.x#8320

projects/igniteui-angular/src/lib/core/styles/components/slider/_slider-component.scss, projects/igniteui-angular/src/lib/core/styles/components/slider/_slider-theme.scss, projects/igniteui-angular/src/lib/slider/label/thumb-label.component.ts, projects/igniteui-angular/src/lib/slider/slider.component.html, projects/igniteui-angular/src/lib/slider/slider.component.ts, projects/igniteui-angular/src/lib/slider/thumb/thumb-slider.component.ts, src/app/slider/slider.sample.html, src/app/slider/slider.sample.scss
=> fix(slider): display pressed thumb label on top

projects/igniteui-angular/src/lib/grids/grid-navigation.service.ts
=> Should be able to navigate with pageUp/Down when there is cell in edit mode - 9.1.x

projects/igniteui-angular/src/lib/grids/grid-navigation.service.ts
=> Should be able to navigate with pageUp/Down when there is cell in edit mode - 10.1

projects/igniteui-angular/src/lib/grids/grid-base.directive.ts, projects/igniteui-angular/src/lib/grids/grid/column.spec.ts, projects/igniteui-angular/src/lib/test-utils/grid-samples.spec.ts
=> fix(Grid): newly added column should be at the last position

projects/igniteui-angular/src/lib/grids/grid-base.directive.ts, projects/igniteui-angular/src/lib/grids/grid/column.spec.ts, projects/igniteui-angular/src/lib/test-utils/grid-samples.spec.ts
=> fix(Grid): newly added column should be at the last position - 9.1.x

projects/igniteui-angular/src/lib/grids/cell.component.ts, projects/igniteui-angular/src/lib/grids/grid-base.directive.ts, projects/igniteui-angular/src/lib/grids/grid/grid.component.html, projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.component.html, projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid.component.html
=> Fix error when copy data in IE11 - 9.1.x

projects/igniteui-angular/src/lib/grids/cell.component.ts, projects/igniteui-angular/src/lib/grids/grid-base.directive.ts, projects/igniteui-angular/src/lib/grids/grid/grid.component.html, projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.component.html, projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid.component.html
=> Fix error when copy data in IE11 - 10.1.x

projects/igniteui-angular/src/lib/core/utils.ts, projects/igniteui-angular/src/lib/grids/grid-navigation.service.ts
=> fix(grid): add alt+l symbol under mac 

projects/igniteui-angular/src/lib/core/utils.ts, projects/igniteui-angular/src/lib/grids/grid-navigation.service.ts
=> fix(grid): add alt+l symbol under mac

projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-search.component.ts
=> prevent excelStyleLoadingValuesTemplateDirective error

projects/igniteui-angular/src/lib/core/utils.ts, projects/igniteui-angular/src/lib/grids/grid-navigation.service.ts, src/app/grid-add-row/grid-add-row.sample.html, src/app/grid-add-row/grid-add-row.sample.ts
=> fix(grid): adding more keys for add row kbd int #8414

projects/igniteui-angular/src/lib/calendar/calendar-base.ts, projects/igniteui-angular/src/lib/calendar/calendar.component.spec.ts, projects/igniteui-angular/src/lib/calendar/month-picker/month-picker.component.spec.ts
=> fix(calendar): show right month when value is set for 9.1.x #8173

projects/igniteui-angular/src/lib/calendar/calendar-base.ts, projects/igniteui-angular/src/lib/calendar/calendar.component.spec.ts
=> fix(calendar): show right month when value is set for 10.2.x #8173

projects/igniteui-angular/src/lib/core/styles/themes/schemas/dark/_action-strip.scss
=> Fix fluent and bootstrap dark themes for action strip component

projects/igniteui-angular/src/lib/calendar/calendar-base.ts, projects/igniteui-angular/src/lib/calendar/calendar.component.spec.ts
=> fix(calendar): show right month when value is set for master #8173

projects/igniteui-angular/migrations/common/tsUtils.ts
=> Migrations fallback if source or class declarations are not resolved - 10.2.x

projects/igniteui-angular/package.json
=> chore(schematics): use schematics alpha

.github/workflows/nodejs.yml
=> chore(ci): updating node versions

projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid-base.directive.ts
=> chore(*): Add api docs for hasChildrenKey and showExpandAll.

projects/igniteui-angular/package.json
=> chore(schematics): put 11.0.700-rc.0

.github/workflows/npm-publish.yml, .travis.yml
=> build(ci): Add gh actions deploy

projects/igniteui-angular/src/lib/grids/filtering/excel-style/grid.excel-style-filtering.component.ts, projects/igniteui-angular/src/lib/grids/grid/grid-filtering-ui.spec.ts
=> ESF use date iso strings in filterValues list

CHANGELOG.md
=> docs(*): add overlay change and arrange 11.0.0 changelog

CHANGELOG.md
=> Update changelog with `filter` method changes 

CHANGELOG.md
=> Update changelog with `filter` method changes

projects/igniteui-angular/src/lib/core/styles/components/_common/_igx-display-container.scss, projects/igniteui-angular/src/lib/core/styles/components/grid/_grid-component.scss, projects/igniteui-angular/src/lib/core/styles/components/grid/_grid-theme.scss, projects/igniteui-angular/src/lib/grids/grid/grid-row.component.html, projects/igniteui-angular/src/lib/grids/grid/grid.component.html, projects/igniteui-angular/src/lib/grids/grid/groupby-row.component.html, projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.component.html, projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-row.component.html, projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-row.component.ts, projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid-row.component.html, projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid.component.html, projects/igniteui-angular/src/lib/test-utils/grid-functions.spec.ts
=> fix(gird): actions order and border

projects/igniteui-angular/package.json
=> chore(schematics): update to official IG schematics

projects/igniteui-angular/src/lib/time-picker/time-picker.component.spec.ts, projects/igniteui-angular/src/lib/time-picker/time-picker.component.ts
=> Properly parse AM/PM when typing - 9.1

projects/igniteui-angular/src/lib/time-picker/time-picker.component.spec.ts, projects/igniteui-angular/src/lib/time-picker/time-picker.component.ts
=> Properly parse AM/PM when typing - 10.2

projects/igniteui-angular/src/lib/grids/grid-base.directive.ts, projects/igniteui-angular/src/lib/grids/grid/grid.component.spec.ts, src/app/grid-auto-size/grid-auto-size.sample.html, src/app/grid-auto-size/grid-auto-size.sample.ts
… calcWidth for internal calculations.
Closes #8555
=> fix(igxGrid): Do not set calcWidth to the original width propety. Use… 

projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-search.component.html, projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-search.component.ts, projects/igniteui-angular/src/lib/grids/grid/grid-filtering-ui.spec.ts
=> fix(esf): allow only numeric symbols in numeric column

projects/igniteui-angular/src/lib/directives/drag-drop/drag-drop.directive.ts, projects/igniteui-angular/src/lib/directives/for-of/base.helper.component.ts, projects/igniteui-angular/src/lib/directives/for-of/for_of.directive.spec.ts, projects/igniteui-angular/src/lib/directives/for-of/for_of.directive.ts, projects/igniteui-angular/src/lib/directives/for-of/horizontal.virtual.helper.component.ts, projects/igniteui-angular/src/lib/directives/for-of/virtual.helper.component.ts, projects/igniteui-angular/src/lib/directives/scroll-inertia/scroll_inertia.directive.ts, projects/igniteui-angular/src/lib/grids/cell.component.ts, projects/igniteui-angular/src/lib/grids/column-actions/column-actions.component.html, projects/igniteui-angular/src/lib/grids/column-actions/column-actions.component.ts, projects/igniteui-angular/src/lib/grids/grid-base.directive.ts, projects/igniteui-angular/src/lib/grids/moving/moving.drag.directive.ts, projects/igniteui-angular/src/lib/grids/toolbar/grid-toolbar-hiding.component.html, projects/igniteui-angular/src/lib/grids/toolbar/grid-toolbar-pinning.component.html, projects/igniteui-angular/src/lib/paginator/paginator.component.ts, src/app/grid-remote-paging/grid-remote-paging.sample.html
=> Resolve some possible ssr errors

.github/workflows/npm-publish.yml, .travis.yml
=> build(ci): Add gh actions deploy - 9.1.x

.github/workflows/npm-publish.yml, .travis.yml
=> build(ci): Add gh actions deploy - 10.1.x

projects/igniteui-angular/src/lib/grids/grid-navigation.service.ts, projects/igniteui-angular/src/lib/grids/grid/grid-keyBoardNav-headers.spec.ts
=> Fix: navigation in MCH headers when grid has no data --9.1.x

projects/igniteui-angular/src/lib/core/styles/components/bottom-nav/_bottom-nav-component.scss, src/app/bottomnav/bottomnav.sample.html
=> fix(bottom-nav): disabled tab panels wrong styles

projects/igniteui-angular/src/lib/core/styles/components/bottom-nav/_bottom-nav-component.scss, src/app/bottomnav/bottomnav.sample.html
=> fix(bottom-nav): disabled tab panels wrong styles 9.1.x

projects/igniteui-angular/src/lib/core/styles/components/bottom-nav/_bottom-nav-component.scss, src/app/bottomnav/bottomnav.sample.html
=> fix(bottom-nav): disabled tab panels wrong styles 10.2.x

projects/igniteui-angular/src/lib/core/styles/components/slider/_slider-theme.scss, projects/igniteui-angular/src/lib/core/styles/themes/schemas/light/_slider.scss, projects/igniteui-angular/src/lib/slider/slider.component.ts
=> chore(slider): improve slider track steps styling

projects/igniteui-angular/src/lib/grids/grid-base.directive.ts, projects/igniteui-angular/src/lib/grids/grid/grid-add-row.spec.ts, projects/igniteui-angular/src/lib/grids/row.directive.ts
=> fix(igxGrid): Fix adding row recreates row forOf directive due to template change. 

projects/igniteui-angular/src/lib/core/styles/components/overlay/_overlay-theme.scss
=> Update overlay z-index value

projects/igniteui-angular/src/lib/grids/grid-common.module.ts, projects/igniteui-angular/src/lib/grids/grid/grid.module.ts
=> fix(grid): move components to grid common module

projects/igniteui-angular/src/lib/core/styles/components/grid/_grid-theme.scss
=> style(grid): padding for add row button in empty grid #8359 - 11.0.x

package-lock.json, package.json, projects/igniteui-angular/ng-package.json, projects/igniteui-angular/ng-package.prod.json, projects/igniteui-angular/package.json, projects/igniteui-angular/schematics/utils/dependency-handler.ts, projects/igniteui-angular/src/lib/core/utils.ts, projects/igniteui-angular/src/lib/grids/grid/grid.nested.props.spec.ts, projects/igniteui-angular/src/lib/grids/row.directive.ts, projects/igniteui-angular/src/lib/services/transaction/base-transaction.ts
=> fix(grid): editing data with nested properties 11.0.x #8343

projects/igniteui-angular/src/lib/core/styles/components/button/_button-component.scss, projects/igniteui-angular/src/lib/core/styles/components/button/_button-theme.scss, projects/igniteui-angular/src/lib/directives/button/button.directive.spec.ts, projects/igniteui-angular/src/lib/directives/button/button.directive.ts
=> fix(button): outlined button wrong size 9.1.x

projects/igniteui-angular/src/lib/core/styles/components/button/_button-component.scss, projects/igniteui-angular/src/lib/core/styles/components/button/_button-theme.scss, projects/igniteui-angular/src/lib/directives/button/button.directive.spec.ts, projects/igniteui-angular/src/lib/directives/button/button.directive.ts
=> fix(button): fix outlined button wrong size 10.2.x

projects/igniteui-angular/src/lib/core/styles/themes/schemas/dark/_column-actions.scss, projects/igniteui-angular/src/lib/core/styles/themes/schemas/light/_column-actions.scss
=> feat(themes): add indigo column actions schemas 11.0.x

ROADMAP.md
=> chore(*): Roadmap Milestone 14

projects/igniteui-angular/src/lib/grids/grid-base.directive.ts, projects/igniteui-angular/src/lib/grids/grid/grid.component.html, projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.component.html, projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid.component.html
=> fix(grid-filtering): prevent page hanging when using remote data

projects/igniteui-angular/src/lib/services/csv/csv-exporter.ts, projects/igniteui-angular/src/lib/services/excel/excel-exporter.ts
=> fix(exporter): mark properties as undefined #8616

projects/igniteui-angular/src/lib/calendar/calendar.component.ts
=> Find month element from date value

projects/igniteui-angular/src/lib/calendar/calendar.component.ts
=> Find month element from date value 

CHANGELOG.md, projects/igniteui-angular/src/lib/core/styles/components/drop-down/_drop-down-component.scss, projects/igniteui-angular/src/lib/core/styles/components/drop-down/_drop-down-theme.scss, projects/igniteui-angular/src/lib/drop-down/drop-down-item.component.html
=> refactor(dropdown): improve dropdown item layout

projects/igniteui-angular/src/lib/calendar/month-picker/month-picker.component.html, projects/igniteui-angular/src/lib/calendar/month-picker/month-picker.component.spec.ts, projects/igniteui-angular/src/lib/calendar/month-picker/month-picker.component.ts
=> fix(month-picker): rowhead attributes fix

projects/igniteui-angular/src/lib/core/styles/components/slider/_slider-theme.scss, projects/igniteui-angular/src/lib/core/styles/themes/schemas/light/_slider.scss
=> Add slider focus styles

package.json, projects/igniteui-angular/src/lib/combo/combo.component.ts, projects/igniteui-angular/src/lib/core/styles/components/input/_input-group-component.scss, projects/igniteui-angular/src/lib/core/styles/components/input/_input-group-theme.scss, projects/igniteui-angular/src/lib/directives/input/input.directive.spec.ts, projects/igniteui-angular/src/lib/directives/input/input.directive.ts, projects/igniteui-angular/src/lib/select/select.component.ts, src/app/combo/combo.sample.html, src/app/combo/combo.sample.ts, src/app/input-group/input-group.sample.html, src/app/input-group/input-group.sample.ts, src/app/select/select.sample.html, src/app/select/select.sample.ts
=> Updating validity states on disabled change master

package.json, projects/igniteui-angular/src/lib/combo/combo.component.ts, projects/igniteui-angular/src/lib/core/styles/components/input/_input-group-component.scss, projects/igniteui-angular/src/lib/core/styles/components/input/_input-group-theme.scss, projects/igniteui-angular/src/lib/directives/input/input.directive.spec.ts, projects/igniteui-angular/src/lib/directives/input/input.directive.ts, projects/igniteui-angular/src/lib/select/select.component.ts, src/app/combo/combo.sample.html, src/app/combo/combo.sample.ts, src/app/input-group/input-group.sample.html, src/app/input-group/input-group.sample.ts, src/app/select/select.sample.html, src/app/select/select.sample.ts
=> Updating validity states on disabled change 10.2.x

package.json, projects/igniteui-angular/src/lib/combo/combo.component.ts, projects/igniteui-angular/src/lib/core/styles/components/input/_input-group-component.scss, projects/igniteui-angular/src/lib/core/styles/components/input/_input-group-theme.scss, projects/igniteui-angular/src/lib/directives/input/input.directive.spec.ts, projects/igniteui-angular/src/lib/directives/input/input.directive.ts, projects/igniteui-angular/src/lib/select/select.component.ts, src/app/combo/combo.sample.html, src/app/combo/combo.sample.ts, src/app/input-group/input-group.sample.html, src/app/input-group/input-group.sample.ts, src/app/select/select.sample.html, src/app/select/select.sample.ts
=> Updating validity states on disabled change 9.1.x

package.json, projects/igniteui-angular/src/lib/combo/combo.component.ts, projects/igniteui-angular/src/lib/core/styles/components/input/_input-group-component.scss, projects/igniteui-angular/src/lib/core/styles/components/input/_input-group-theme.scss, projects/igniteui-angular/src/lib/directives/input/input.directive.spec.ts, projects/igniteui-angular/src/lib/directives/input/input.directive.ts, projects/igniteui-angular/src/lib/select/select.component.ts, src/app/combo/combo.sample.html, src/app/combo/combo.sample.ts, src/app/input-group/input-group.sample.html, src/app/input-group/input-group.sample.ts, src/app/select/select.sample.html, src/app/select/select.sample.ts
=> Updating validity states on disabled change 11.0.x

projects/igniteui-angular/src/lib/grids/grid/grid-filtering-ui.spec.ts, projects/igniteui-angular/src/lib/grids/grid/grid-filtering.spec.ts, projects/igniteui-angular/src/lib/grids/grid/grid.sorting.spec.ts
=> Add filtering and sorting tests for date values

src/app/grid-finjs/controllers.component.html, src/app/grid-finjs/controllers.component.ts, src/app/grid-finjs/grid-finjs.component.html, src/app/grid-finjs/grid-finjs.component.ts, src/app/grid-finjs/main.component.html, src/app/grid-finjs/main.component.ts, src/app/shared/financialData.ts
=> FinJS dev demo enhacements - master

CHANGELOG.md, projects/igniteui-angular/src/lib/action-strip/grid-actions/grid-editing-actions.component.ts, projects/igniteui-angular/src/lib/grids/api.service.ts, projects/igniteui-angular/src/lib/grids/cell.component.ts, projects/igniteui-angular/src/lib/grids/filtering/advanced-filtering/advanced-filtering-dialog.component.html, projects/igniteui-angular/src/lib/grids/filtering/advanced-filtering/advanced-filtering-dialog.component.ts, projects/igniteui-angular/src/lib/grids/grid-base.directive.ts, projects/igniteui-angular/src/lib/grids/grid-navigation.service.ts, projects/igniteui-angular/src/lib/grids/grid/expandable-cell.component.html, projects/igniteui-angular/src/lib/grids/grid/expandable-cell.component.ts, projects/igniteui-angular/src/lib/grids/grid/grid-cell-editing.spec.ts, projects/igniteui-angular/src/lib/grids/grid/grid-row-editing.spec.ts, projects/igniteui-angular/src/lib/grids/grid/grid.component.html, projects/igniteui-angular/src/lib/grids/grid/grid.crud.spec.ts, projects/igniteui-angular/src/lib/grids/grid/grid.nested.props.spec.ts, projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.component.html, projects/igniteui-angular/src/lib/grids/selection/selection.service.ts, projects/igniteui-angular/src/lib/grids/tree-grid/tree-cell.component.html, projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid-crud.spec.ts, projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid.component.html
=> feat(grid): passing the dom event through editing events Closes #8354 --master

src/app/grid-finjs/controllers.component.html, src/app/grid-finjs/controllers.component.ts, src/app/grid-finjs/grid-finjs.component.html, src/app/grid-finjs/grid-finjs.component.ts, src/app/grid-finjs/main.component.html, src/app/grid-finjs/main.component.ts, src/app/shared/financialData.ts
=> FinJS dev demo enhacements 11x

projects/igniteui-angular/src/lib/grids/grid-base.directive.ts, projects/igniteui-angular/src/lib/grids/grid/column-pinning.spec.ts
=> fix(grid): column unpining order #8194 9.1.x

projects/igniteui-angular/src/lib/grids/grid-base.directive.ts, projects/igniteui-angular/src/lib/grids/grid/column-pinning.spec.ts
=> fix(grid): column unpining order #8194 master

projects/igniteui-angular/src/lib/buttonGroup/buttonGroup.component.ts, src/app/buttonGroup/buttonGroup.sample.html
=> fix(button-group): pass string to alignment prop

projects/igniteui-angular/src/lib/core/styles/components/calendar/_calendar-component.scss
=> Adding hover/focus styles for weekend days in calendar

projects/igniteui-angular/src/lib/core/enums.ts, projects/igniteui-angular/src/lib/date-picker/date-picker.component.ts, projects/igniteui-angular/src/lib/time-picker/time-picker.component.ts
=> fix(inputs): use full union types on igxDatePicker's InteractionMode - master

projects/igniteui-angular/src/lib/core/enums.ts, projects/igniteui-angular/src/lib/date-picker/date-picker.component.ts, projects/igniteui-angular/src/lib/time-picker/time-picker.component.ts
=> fix(inputs): use full union types on igxDatePicker's InteractionMode - 11.0.x

projects/igniteui-angular/src/lib/core/enums.ts, projects/igniteui-angular/src/lib/date-picker/date-picker.component.ts, projects/igniteui-angular/src/lib/time-picker/time-picker.component.ts
=> fix(inputs): use full union types on igxDatePicker's InteractionMode - 10.2.x

CHANGELOG.md, projects/igniteui-angular/src/lib/grids/grid-base.directive.ts, projects/igniteui-angular/src/lib/grids/grid-navigation.service.ts, projects/igniteui-angular/src/lib/grids/grid/grid-filtering-ui.spec.ts, projects/igniteui-angular/src/lib/grids/grid/grid-keyBoardNav-headers.spec.ts, projects/igniteui-angular/src/lib/grids/grid/grid-keyBoardNav.spec.ts
=> Active node doesn't resets horizontal/vertical scroll positions when page lost focus and regain again

CHANGELOG.md, projects/igniteui-angular/src/lib/grids/grid-base.directive.ts, projects/igniteui-angular/src/lib/grids/grid-navigation.service.ts, projects/igniteui-angular/src/lib/grids/grid/grid-filtering-ui.spec.ts, projects/igniteui-angular/src/lib/grids/grid/grid-keyBoardNav-headers.spec.ts, projects/igniteui-angular/src/lib/grids/grid/grid-keyBoardNav.spec.ts
=> Active node doesn't resets horizontal/vertical scroll positions when page lost focus and regain again - 10.2.x

CHANGELOG.md, projects/igniteui-angular/src/lib/core/styles/components/radio/_radio-component.scss, projects/igniteui-angular/src/lib/directives/radio/radio-group.directive.ts, src/app/radio/radio.sample.html, src/app/radio/radio.sample.ts
=> feat(radio-group): add vertical alignment

projects/igniteui-angular/src/lib/grids/filtering/grid-filtering.service.ts, projects/igniteui-angular/src/lib/grids/grid/grid-filtering.spec.ts
=> Always emit onFilteringDone with proper event arguments

projects/igniteui-angular/src/lib/animations/README.md
=> fix(readme): broken links in animations README

projects/igniteui-angular/src/lib/data-operations/filtering-condition.ts, projects/igniteui-angular/src/lib/grids/grid/grid-filtering.spec.ts, projects/igniteui-angular/src/lib/test-utils/grid-samples.spec.ts
=> fix(filter): exclude blank and null values

projects/igniteui-angular/src/lib/data-operations/filtering-condition.ts
=> Use nullish coalescing operator

projects/igniteui-angular/src/lib/date-range-picker/date-range-picker.component.spec.ts, projects/igniteui-angular/src/lib/date-range-picker/date-range-picker.component.ts
=> Fix IgxDateRangePicker default dropdown positioning - 10.2.x

projects/igniteui-angular/src/lib/date-range-picker/date-range-picker.component.spec.ts, projects/igniteui-angular/src/lib/date-range-picker/date-range-picker.component.ts
=> Fix IgxDateRangePicker default dropdown positioning 

projects/igniteui-angular/src/lib/date-range-picker/date-range-picker.component.spec.ts, projects/igniteui-angular/src/lib/date-range-picker/date-range-picker.component.ts
=> Fix IgxDateRangePicker default dropdown positioning - 11.0.x

projects/igniteui-angular/src/lib/directives/radio/radio-group.directive.spec.ts, projects/igniteui-angular/src/lib/directives/radio/radio-group.directive.ts
=> fix(radio-group): set group value to checked button

projects/igniteui-angular/src/lib/calendar/calendar-base.ts, projects/igniteui-angular/src/lib/calendar/months-view/months-view.component.ts, projects/igniteui-angular/src/lib/calendar/years-view/years-view.component.ts, projects/igniteui-angular/src/lib/slider/slider.component.ts
=> Calendar bug fix -- 11.0.x

projects/igniteui-angular/src/lib/calendar/calendar-base.ts, projects/igniteui-angular/src/lib/calendar/months-view/months-view.component.ts, projects/igniteui-angular/src/lib/calendar/years-view/years-view.component.ts, projects/igniteui-angular/src/lib/slider/slider.component.ts
=> Calendar bug fix --master

projects/igniteui-angular/src/lib/calendar/calendar-base.ts, projects/igniteui-angular/src/lib/calendar/months-view/months-view.component.ts, projects/igniteui-angular/src/lib/calendar/years-view/years-view.component.ts, projects/igniteui-angular/src/lib/slider/slider.component.ts
=> Calendar bug fix --- 10.2.x

.github/workflows/nodejs.yml, .travis.yml, azure-pipelines.yml
=> Code coverage with gh actions - 11.0.x

.github/workflows/nodejs.yml, .travis.yml, azure-pipelines.yml
=> Code coverage with gh actions - master

.github/workflows/nodejs.yml, .travis.yml, azure-pipelines.yml
=> Code coverage with gh actions - 10.2.x

CHANGELOG.md, projects/igniteui-angular/src/lib/dialog/dialog.component.spec.ts, projects/igniteui-angular/src/lib/dialog/dialog.component.ts, projects/igniteui-angular/src/lib/directives/toggle/toggle.directive.ts, projects/igniteui-angular/src/lib/services/overlay/overlay.spec.ts, projects/igniteui-angular/src/lib/services/overlay/overlay.ts, projects/igniteui-angular/src/lib/services/overlay/utilities.ts
=> fix(dialog): two way data binding fix #8320

projects/igniteui-angular/src/lib/select/select-navigation.directive.ts, projects/igniteui-angular/src/lib/select/select.component.spec.ts
=> Handle keydown and iterate items by first character, if no item matched typed input - 10.2.x

projects/igniteui-angular/src/lib/select/select-navigation.directive.ts, projects/igniteui-angular/src/lib/select/select.component.spec.ts
=> Handle keydown and iterate items by first character, if no item matched typed input - 11.0.x

projects/igniteui-angular/src/lib/dialog/dialog.component.spec.ts, projects/igniteui-angular/src/lib/dialog/dialog.component.ts, projects/igniteui-angular/src/lib/directives/toggle/toggle.directive.ts, projects/igniteui-angular/src/lib/services/overlay/overlay.spec.ts, projects/igniteui-angular/src/lib/services/overlay/overlay.ts, projects/igniteui-angular/src/lib/services/overlay/utilities.ts
=> fix(dialog): two way data binding #8320 - 11.0

projects/igniteui-angular/src/lib/dialog/dialog.component.spec.ts, projects/igniteui-angular/src/lib/dialog/dialog.component.ts, projects/igniteui-angular/src/lib/directives/toggle/toggle.directive.ts, projects/igniteui-angular/src/lib/services/overlay/overlay.spec.ts, projects/igniteui-angular/src/lib/services/overlay/overlay.ts, projects/igniteui-angular/src/lib/services/overlay/utilities.ts
=> fix(dialog): two way data binding #8320 - 10.2.x

projects/igniteui-angular/src/lib/grids/filtering/advanced-filtering/advanced-filtering-dialog.component.html, projects/igniteui-angular/src/lib/grids/filtering/advanced-filtering/advanced-filtering-dialog.component.ts, projects/igniteui-angular/src/lib/grids/filtering/base/grid-filtering-row.component.html, projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-date-expression.component.html, projects/igniteui-angular/src/lib/grids/filtering/grid-filtering.service.ts, projects/igniteui-angular/src/lib/grids/grid/grid-filtering-ui.spec.ts
=> Inputs respect column formatter

projects/igniteui-angular/src/lib/directives/drag-drop/drag-drop.directive.ts
=> fix(drop): resolving @input declaration error #8761 - 11.0

projects/igniteui-angular/src/lib/directives/drag-drop/drag-drop.directive.ts
=> fix(drop): resolving @input declaration error #8761 - master

CHANGELOG.md, projects/igniteui-angular/src/lib/dialog/dialog-content.component.html, projects/igniteui-angular/src/lib/dialog/dialog.component.spec.ts, src/app/dialog/dialog.sample.css, src/app/drag-drop/drag-drop.sample.html, src/app/grid-multi-row-layout-config/grid-mrl-config.sample.css, src/app/grid-multi-row-layout-config/grid-mrl-config.sample.html, src/app/list/list.sample.html, src/app/list/list.sample.scss
=> Dialog component refactoring

projects/igniteui-angular/src/lib/slider/slider.common.ts, projects/igniteui-angular/src/lib/slider/slider.component.html, projects/igniteui-angular/src/lib/slider/slider.component.spec.ts, projects/igniteui-angular/src/lib/slider/slider.component.ts, src/app/slider/slider.sample.html
=> feat(slider): update slider enums as a string union types

README.md
=> chore(*): Update demo apps section of the readme

projects/igniteui-angular/src/lib/card/card.component.ts
=> docs(card): update typedoc for type

projects/igniteui-angular/src/lib/slider/label/thumb-label.component.ts, projects/igniteui-angular/src/lib/slider/ticks/tick.pipe.ts
=> chore(slider): comment slider tick pipes and labels component

CHANGELOG.md, projects/igniteui-angular/src/lib/input-group/README.md, projects/igniteui-angular/src/lib/input-group/input-group.component.ts, src/app/input-group/input-group.sample.html
=> refactor(input-group): allow setting theme at runtime

projects/igniteui-angular/src/lib/radio/radio.component.html, projects/igniteui-angular/src/lib/radio/radio.component.spec.ts, projects/igniteui-angular/src/lib/radio/radio.component.ts
=> fix(radio): doesn't work with OnPush

projects/igniteui-angular/src/lib/directives/scroll-inertia/scroll_inertia.directive.spec.ts, projects/igniteui-angular/src/lib/directives/scroll-inertia/scroll_inertia.directive.ts, projects/igniteui-angular/src/lib/grids/grid/grid.component.spec.ts, projects/igniteui-angular/src/lib/test-utils/ui-interactions.spec.ts
=> ShiftKey + mouse wheel for horizontal scroll -- 11.1.x

projects/igniteui-angular/src/lib/core/styles/README.md
=> fix(readme): spelling mistakes in styling readme

CHANGELOG.md, projects/igniteui-angular/src/lib/grids/README.md, projects/igniteui-angular/src/lib/grids/grid-base.directive.ts, projects/igniteui-angular/src/lib/snackbar/snackbar.component.spec.ts, projects/igniteui-angular/src/lib/snackbar/snackbar.component.ts, src/app/grid/grid.sample.ts, src/app/snackbar/snackbar.sample.ts
=> refactor(snackbar): deprecate methods - master

projects/igniteui-angular/src/lib/grids/grid/grid-filtering-ui.spec.ts
=> Fix failing filtering tests master

projects/igniteui-angular/src/lib/grids/grid/grid-filtering-ui.spec.ts
=> Fix failing filtering tests 10.2.x

projects/igniteui-angular/src/lib/grids/grid/grid-filtering-ui.spec.ts
=> Fix failing filtering tests 11.0.x

.github/workflows/nodejs.yml
=> chore(coverage): Let istanbul generate combined coverage report

projects/igniteui-angular/src/lib/grids/toolbar/grid-toolbar-hiding.component.html, projects/igniteui-angular/src/lib/grids/toolbar/grid-toolbar-hiding.component.ts, projects/igniteui-angular/src/lib/grids/toolbar/grid-toolbar-pinning.component.html, projects/igniteui-angular/src/lib/grids/toolbar/grid-toolbar-pinning.component.ts, projects/igniteui-angular/src/lib/grids/toolbar/grid-toolbar.base.ts
=> feat(toolbar): expose toggle evts and select/deselect functionality

projects/igniteui-angular/src/lib/combo/combo.pipes.ts
=> fix(combo): Forcing e[displayKey] to be string - 10.2.x #8816

src/app/list/list.sample.html, src/app/radio/radio.sample.html, src/app/radio/radio.sample.ts, src/app/tooltip/tooltip.sample.html
=> fix(demos): not working after eslint refactor

projects/igniteui-angular/src/lib/core/styles/base/utilities/_functions.scss, projects/igniteui-angular/src/lib/core/styles/themes/schemas/light/_button.scss
=> refactor(functions): modify igx-color function to work with CSS vars

projects/igniteui-angular/src/lib/core/styles/base/utilities/_functions.scss
=> refactor(functions): modify igx-contrast-color function

projects/igniteui-angular/src/lib/expansion-panel/expansion-panel.component.ts
=> fix(expansion-panel): Adding markForCheck() - 10.2.x #8501

projects/igniteui-angular/src/lib/expansion-panel/expansion-panel.component.ts
=> fix(expansion-panel): Fixing collapsing - master #8501

projects/igniteui-angular/migrations/migration-collection.json, projects/igniteui-angular/migrations/update-11_1_0/changes/outputs.json, projects/igniteui-angular/migrations/update-11_1_0/index.spec.ts, projects/igniteui-angular/migrations/update-11_1_0/index.ts, projects/igniteui-angular/src/lib/action-strip/action-strip.component.spec.ts, projects/igniteui-angular/src/lib/action-strip/action-strip.component.ts, projects/igniteui-angular/src/lib/action-strip/grid-actions/grid-action-button.component.ts, projects/igniteui-angular/src/lib/action-strip/grid-actions/grid-actions-base.directive.ts, projects/igniteui-angular/src/lib/action-strip/grid-actions/grid-editing-actions.component.html, projects/igniteui-angular/src/lib/action-strip/grid-actions/grid-editing-actions.component.spec.ts, projects/igniteui-angular/src/lib/action-strip/grid-actions/grid-editing-actions.component.ts, projects/igniteui-angular/src/lib/action-strip/grid-actions/grid-pinning-actions.component.html, projects/igniteui-angular/src/lib/action-strip/grid-actions/grid-pinning-actions.component.spec.ts, projects/igniteui-angular/src/lib/action-strip/grid-actions/grid-pinning-actions.component.ts, projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid-add-row-ui.spec.ts, projects/igniteui-angular/src/lib/splitter/splitter-bar/splitter-bar.component.ts, projects/igniteui-angular/src/lib/splitter/splitter-pane/splitter-pane.component.ts
Resolves eslint warnings for Action-Strip and Splitter 
The igx-action-strip-button event is renamed without deprecation as it's not exposed for external use.
=> refactor(*): eslint errors, migrations

projects/igniteui-angular/src/lib/core/styles/components/expansion-panel/_expansion-panel-theme.scss
=> docs(themes): fix expansion panel typography

projects/igniteui-angular/src/lib/directives/radio/radio-group.directive.ts
Closes #8869 
Related to #8882
=> lint(radio-group): fix warnings

projects/igniteui-angular/src/lib/directives/radio/radio-group.directive.ts
=> docs(radio-group): hide ngAfterContentInit in typedoc

projects/igniteui-angular/migrations/update-7_2_0/index.spec.ts, projects/igniteui-angular/migrations/update-7_2_0/index.ts, projects/igniteui-angular/schematics/ng-add/add-normalize.ts, projects/igniteui-angular/schematics/ng-add/index.spec.ts, projects/igniteui-angular/schematics/ng-add/index.ts, projects/igniteui-angular/schematics/utils/dependency-handler.ts, projects/igniteui-angular/schematics/utils/util.ts
=> Use new schematics API - 11.0.x

projects/igniteui-angular/migrations/update-7_2_0/index.spec.ts, projects/igniteui-angular/migrations/update-7_2_0/index.ts, projects/igniteui-angular/schematics/ng-add/add-normalize.ts, projects/igniteui-angular/schematics/ng-add/index.spec.ts, projects/igniteui-angular/schematics/ng-add/index.ts, projects/igniteui-angular/schematics/utils/dependency-handler.ts, projects/igniteui-angular/schematics/utils/util.ts
=> Use new schematics API

projects/igniteui-angular/src/lib/core/styles/components/input/_input-group-component.scss, projects/igniteui-angular/src/lib/core/styles/components/input/_input-group-theme.scss
=> Fix styles for hint position

projects/igniteui-angular/src/lib/avatar/avatar.component.ts, projects/igniteui-angular/src/lib/badge/badge.component.ts, projects/igniteui-angular/src/lib/card/card.component.ts, projects/igniteui-angular/src/lib/directives/button/button.directive.ts, projects/igniteui-angular/src/lib/directives/layout/layout.directive.ts, projects/igniteui-angular/src/lib/directives/ripple/ripple.directive.ts
=> fix(*): lint warnings

projects/igniteui-angular/src/lib/core/styles/components/input/_input-group-component.scss, projects/igniteui-angular/src/lib/core/styles/components/input/_input-group-theme.scss
=> Fix styles for hint position 

src/app/app.component.ts, src/app/calendar/calendar.sample.html, src/app/combo/combo.sample.ts, src/app/grid-row-edit/grid-row-edit-sample.component.ts
=> chore(*): Fix demos dev master

projects/igniteui-angular/migrations/common/ServerHost.ts, projects/igniteui-angular/migrations/common/tsPlugin/TSLanguageService.ts, projects/igniteui-angular/migrations/common/tsPlugin/index.ts, projects/igniteui-angular/migrations/common/tsUtils.ts
=> Implement a typescript plugin that preserves the TSLS - 11.0

projects/igniteui-angular/src/lib/services/exporter-common/base-export-service.ts
=> fix(excel-export): use field if header is undefined or empty

.vscode/launch.json, CHANGELOG.md, projects/igniteui-angular/migrations/update-11_1_0/index.ts
Thanks to @jackofdiamond5 we can cover the following migrations
Related to #8809
=> Add GridPagingMode migration

projects/igniteui-angular/src/lib/core/styles/components/grid/_grid-theme.scss
=> fix(grid): style select component in cell editing mode

projects/igniteui-angular/src/lib/input-group/input-group.component.ts
=> fix(input-group): don't initialize _variant with material theme

.angulardoc.json, projects/igniteui-angular/src/lib/date-picker/date-picker.component.html, projects/igniteui-angular/src/lib/date-picker/date-picker.component.ts
=> fix(date-picker): Deprecation warning for the label property. #8917

src/app/button/button.sample.html, src/app/grid-auto-size/grid-auto-size.sample.html, src/app/grid-cellEditing/grid-cellEditing.component.html, src/app/grid-column-moving/grid-column-moving.sample.html, src/app/grid-column-selection/grid-column-selection.sample.html, src/app/grid-esf-load-on-demand/grid-esf-load-on-demand.component.html, src/app/grid-external-filtering/grid-external-filtering.sample.html, src/app/grid-filtering/grid-filtering.sample.html, src/app/grid-finjs/controllers.component.html, src/app/grid-groupby/grid-groupby.sample.html, src/app/grid-mrl-custom-navigation/grid-mrl-custom-navigation.sample.html, src/app/grid-multi-row-layout/grid-mrl.sample.html, src/app/grid-row-draggable/grid-row-draggable.sample.html, src/app/grid-search/grid-search.sample.html, src/app/hierarchical-grid/hierarchical-grid.sample.html, src/app/list/list.sample.html, src/app/mask/mask.sample.html, src/app/select/select.sample.html, src/app/snackbar/snackbar.sample.html, src/app/tree-grid-flat-data/tree-grid-flat-data.sample.html, src/app/tree-grid-load-on-demand/tree-grid-load-on-demand.sample.html, src/app/tree-grid/tree-grid.sample.html
=> refactor(demos): fix event names after refactoring

projects/igniteui-angular/src/lib/services/csv/csv-exporter-grid.spec.ts, projects/igniteui-angular/src/lib/services/excel/excel-exporter-grid.spec.ts, projects/igniteui-angular/src/lib/services/exporter-common/base-export-service.ts
=> fix(Exporters): Fixed hidden column's export index

projects/igniteui-angular/schematics/ng-add/index.spec.ts, projects/igniteui-angular/schematics/ng-add/index.ts, projects/igniteui-angular/schematics/utils/dependency-handler.ts
=> Add hammerjs to Angular options - 11.0.x

projects/igniteui-angular/schematics/ng-add/index.spec.ts, projects/igniteui-angular/schematics/ng-add/index.ts, projects/igniteui-angular/schematics/utils/dependency-handler.ts
=> Add hammerjs to Angular options - 10.2.x

projects/igniteui-angular/src/lib/grids/filtering/excel-style/grid.excel-style-filtering.component.ts, projects/igniteui-angular/src/lib/grids/grid/grid-filtering-ui.spec.ts, projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.spec.ts, projects/igniteui-angular/src/lib/test-utils/grid-functions.spec.ts
=> fix(hierarchical-grid): fix excel style filtering in row-island

projects/igniteui-angular/src/lib/core/styles/base/elevations/_index.scss, projects/igniteui-angular/src/lib/core/styles/base/utilities/_mixins.scss, projects/igniteui-angular/src/lib/core/styles/components/badge/_badge-theme.scss, projects/igniteui-angular/src/lib/core/styles/components/bottom-nav/_bottom-nav-theme.scss, projects/igniteui-angular/src/lib/core/styles/components/button-group/_button-group-theme.scss, projects/igniteui-angular/src/lib/core/styles/components/button/_button-theme.scss, projects/igniteui-angular/src/lib/core/styles/components/card/_card-theme.scss, projects/igniteui-angular/src/lib/core/styles/components/carousel/_carousel-theme.scss, projects/igniteui-angular/src/lib/core/styles/components/chip/_chip-theme.scss, projects/igniteui-angular/src/lib/core/styles/components/column-actions/_column-actions-theme.scss, projects/igniteui-angular/src/lib/core/styles/components/date-picker/_date-picker-theme.scss, projects/igniteui-angular/src/lib/core/styles/components/dialog/_dialog-theme.scss, projects/igniteui-angular/src/lib/core/styles/components/drop-down/_drop-down-theme.scss, projects/igniteui-angular/src/lib/core/styles/components/grid-toolbar/_grid-toolbar-theme.scss, projects/igniteui-angular/src/lib/core/styles/components/grid/_advanced-filtering-theme.scss, projects/igniteui-angular/src/lib/core/styles/components/grid/_excel-filtering-theme.scss, projects/igniteui-angular/src/lib/core/styles/components/grid/_grid-theme.scss, projects/igniteui-angular/src/lib/core/styles/components/input/_input-group-theme.scss, projects/igniteui-angular/src/lib/core/styles/components/navbar/_navbar-theme.scss, projects/igniteui-angular/src/lib/core/styles/components/navdrawer/_navdrawer-theme.scss, projects/igniteui-angular/src/lib/core/styles/components/snackbar/_snackbar-theme.scss, projects/igniteui-angular/src/lib/core/styles/components/splitter/_splitter-theme.scss, projects/igniteui-angular/src/lib/core/styles/components/switch/_switch-theme.scss, projects/igniteui-angular/src/lib/core/styles/components/tabs/_tabs-theme.scss, projects/igniteui-angular/src/lib/core/styles/components/time-picker/_time-picker-theme.scss, projects/igniteui-angular/src/lib/core/styles/components/toast/_toast-theme.scss, projects/igniteui-angular/src/lib/core/styles/spec/_index.scss, projects/igniteui-angular/src/lib/core/styles/spec/_mixins.spec.scss, projects/igniteui-angular/src/lib/core/styles/themes/_index.scss, src/styles/_variables.scss
=> refactor(themes): add and use elevations as css vars

projects/igniteui-angular/src/lib/input-group/input-group.component.ts, src/app/date-time-editor/date-time-editor.sample.html
=> fix(input): remove deprecated property

projects/igniteui-angular/migrations/update-11_1_0/changes/members.json
=> fix(Exporters): Added missing classes in migration

projects/igniteui-angular/package.json
=> chore(*): update product packages

projects/igniteui-angular/src/lib/paginator/public_api.ts, projects/igniteui-angular/src/public_api.ts, src/app/grid-events/grid-events.component.ts
=> expose paginator intefaces in public api

projects/igniteui-angular/src/lib/core/deprecateDecorators.ts
=> Fix: deprecate method decorator function

projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid-base.directive.ts, projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.spec.ts
=> fix(hierarchical-grid): emit column events for child grid #8644

projects/igniteui-angular/src/lib/core/styles/components/action-strip/_action-strip-theme.scss, projects/igniteui-angular/src/lib/core/styles/components/grid-toolbar/_grid-toolbar-component.scss, projects/igniteui-angular/src/lib/core/styles/components/grid-toolbar/_grid-toolbar-theme.scss, projects/igniteui-angular/src/lib/core/styles/components/grid/_excel-filtering-theme.scss, projects/igniteui-angular/src/lib/core/styles/components/grid/_grid-theme.scss, projects/igniteui-angular/src/lib/core/styles/components/icon/_icon-theme.scss, projects/igniteui-angular/src/lib/grids/filtering/base/grid-filtering-row.component.html, projects/igniteui-angular/src/lib/grids/toolbar/grid-toolbar-advanced-filtering.component.html, projects/igniteui-angular/src/lib/grids/toolbar/grid-toolbar-exporter.component.html, projects/igniteui-angular/src/lib/grids/toolbar/grid-toolbar-hiding.component.html, projects/igniteui-angular/src/lib/grids/toolbar/grid-toolbar-pinning.component.html, src/app/buttonGroup/buttonGroup.sample.html, src/app/grid-column-selection/grid-column-selection.sample.html, src/app/grid-events/grid-events.component.html, src/app/grid-toolbar/grid-toolbar-custom.sample.html
=> refactor(themes): remove unnecessary icon margins

projects/igniteui-angular/package.json
=> chore(schematics): put schematics beta

projects/igniteui-angular/src/lib/directives/autocomplete/autocomplete.directive.ts
=> fix(autocomplete): Incorrect toggling of _shouldBeOpen - master - #8899

projects/igniteui-angular/src/lib/directives/autocomplete/autocomplete.directive.ts
=> fix(autocomplete): Incorrect toggling of _shouldBeOpen - 11.0.x #8899

projects/igniteui-angular/schematics/ng-add/index.spec.ts, projects/igniteui-angular/schematics/ng-add/index.ts
=> Enable IE support trough the .browserslistrc file - 10.2.x

projects/igniteui-angular/schematics/ng-add/index.spec.ts, projects/igniteui-angular/schematics/ng-add/index.ts
=> Enable IE support trough the .browserslistrc file - 11.0.x

projects/igniteui-angular/src/lib/directives/autocomplete/autocomplete.directive.ts
=> fix(autocomplete): Incorrect toggling of _shouldBeOpen 10.2.x #8899

CHANGELOG.md, projects/igniteui-angular/src/lib/splitter/splitter.component.spec.ts, projects/igniteui-angular/src/lib/splitter/splitter.component.ts
=> feat(igxSplitter): Add resizeStart/resizing/resizeEnd events.

projects/igniteui-angular/src/lib/paginator/public_api.ts, projects/igniteui-angular/src/public_api.ts, src/app/grid-events/grid-events.component.ts
Reverts IgniteUI/igniteui-angular#9005
=> Revert "expose paginator intefaces in public api"

projects/igniteui-angular/src/lib/grids/grid-base.directive.ts
Reverts IgniteUI/igniteui-angular#8976
=> Revert "handle deprecation messages for paging"

projects/igniteui-angular/src/lib/carousel/carousel.component.html
=> fix(*): replacing anchor with span elements

projects/igniteui-angular/package.json
=> chore(schematics): update with 11.1.710.

CHANGELOG.md, projects/igniteui-angular/src/lib/directives/autocomplete/autocomplete.directive.spec.ts, projects/igniteui-angular/src/lib/directives/autocomplete/autocomplete.directive.ts
=> fix(autocomplete): Using _shouldBeOpen for state changes coming from outside the component and adding exportAs - 11.1.x - #8899

CHANGELOG.md, projects/igniteui-angular/src/lib/directives/autocomplete/autocomplete.directive.spec.ts, projects/igniteui-angular/src/lib/directives/autocomplete/autocomplete.directive.ts
=> fix(autocomplete): Using _shouldBeOpen for state changes coming from outside the component and adding exportAs - 11.0.x - #8899

CHANGELOG.md, projects/igniteui-angular/src/lib/directives/autocomplete/autocomplete.directive.spec.ts, projects/igniteui-angular/src/lib/directives/autocomplete/autocomplete.directive.ts
=> fix(autocomplete): Using _shouldBeOpen for state changes coming from outside the compoenent and adding exportAs - 10.2.x - #8899

projects/igniteui-angular/src/lib/date-range-picker/date-range-picker.component.spec.ts, projects/igniteui-angular/src/lib/date-range-picker/date-range-picker.component.ts
=> Range picker does not expand on Alt + ArrowDown when in dialog mode - 11.1.x

projects/igniteui-angular/src/lib/date-range-picker/date-range-picker.component.spec.ts, projects/igniteui-angular/src/lib/date-range-picker/date-range-picker.component.ts
=> Range picker does not expand on Alt + ArrowDown when in dialog mode - 11.0.x

projects/igniteui-angular/src/lib/date-range-picker/date-range-picker.component.spec.ts, projects/igniteui-angular/src/lib/date-range-picker/date-range-picker.component.ts
=> Range picker keyboard navigation - 10.2.x

src/app/grid-auto-size/grid-auto-size.sample.html, src/app/grid-column-actions/grid-column-actions.sample.html, src/app/grid-column-groups/grid-column-groups.sample.html, src/app/grid-column-moving/grid-column-moving.sample.html, src/app/grid-column-selection/grid-column-selection.sample.html, src/app/grid-esf-load-on-demand/grid-esf-load-on-demand.component.html, src/app/grid-external-filtering/grid-external-filtering.sample.html, src/app/grid-filtering/grid-filtering.sample.html, src/app/grid-flex-layout/grid-flex.sample.html, src/app/grid-mrl-custom-navigation/grid-mrl-custom-navigation.sample.html, src/app/grid-multi-row-layout/grid-mrl.sample.html, src/app/grid-nested-props/grid-nested-props.sample.html, src/app/grid-performance/grid-performance.sample.html, src/app/grid-row-pinning/grid-row-pinning.sample.html, src/app/grid-search-box/grid-search-box.component.html, src/app/grid-search/grid-search.sample.html, src/app/grid-state/grid-state.component.html, src/app/grid-summaries/grid-summaries.sample.html, src/app/grid-summaries/grid-summaries.sample.ts, src/app/grid-toolbar/grid-toolbar-custom.sample.html, src/app/grid-toolbar/grid-toolbar-custom.sample.ts, src/app/tree-grid-flat-data/tree-grid-flat-data.sample.html, src/app/tree-grid-load-on-demand/tree-grid-load-on-demand.sample.html, src/app/tree-grid/tree-grid.sample.html
=> fix(Toolbar): Fixed toolbars in dev demos after the component's refactoring.

projects/igniteui-angular/src/lib/core/i18n/resources.ts
=> Return all resource strings-10.2

projects/igniteui-angular/src/lib/core/i18n/resources.ts
=> Return all resource strings-11.0.x

projects/igniteui-angular/src/lib/core/i18n/resources.ts
=> Return all resource strings-11.1.x

.github/workflows/nodejs.yml
github actions will now install Node JS version - either 12.x, 14,x, 15,x, while it was always installing 10.x on each one of the environments.
=> ci(*): use matrix node version

projects/igniteui-angular/src/lib/core/styles/components/dialog/_dialog-component.scss, projects/igniteui-angular/src/lib/core/styles/components/dialog/_dialog-theme.scss, projects/igniteui-angular/src/lib/dialog/dialog-content.component.html, src/app/dialog/dialog.sample.html
fix: (igx-dialog) make sure that if the dialog content is templated we don't set max-width on the window content.
Closes #9038
=> fix(igx-dialog): max width

projects/igniteui-angular/src/lib/grids/grid-navigation.service.ts, projects/igniteui-angular/src/lib/grids/grid/grid-filtering-ui.spec.ts
=> fix(Grid Navigation): Adding a null check in focusTBody() after filtering out all grid records.

projects/igniteui-angular/src/lib/grids/grid-navigation.service.ts, projects/igniteui-angular/src/lib/grids/grid/grid-filtering-ui.spec.ts
=> fix(Navigation): activeNode null check in focusTBody()

projects/igniteui-angular/src/lib/grids/grid-navigation.service.ts, projects/igniteui-angular/src/lib/grids/grid/grid-filtering-ui.spec.ts
=> fix column hiding when column is hidden from ESF

projects/igniteui-angular/src/lib/grids/filtering/advanced-filtering/advanced-filtering-dialog.component.ts, projects/igniteui-angular/src/lib/grids/grid/grid-filtering-advanced.spec.ts, projects/igniteui-angular/src/lib/test-utils/hierarchical-grid-components.spec.ts
=> fix(AdvancedFilter): Initialize lastActiveNode.

projects/igniteui-angular/src/lib/grids/grid-navigation.service.ts, projects/igniteui-angular/src/lib/grids/grid/grid-filtering-ui.spec.ts
=> fix(grid): fix column hiding from esf

projects/igniteui-angular/src/lib/core/styles/components/navbar/_navbar-theme.scss
=> fix:(igx-navbar) nested elements icon color

projects/igniteui-angular/migrations/common/UpdateChanges.ts
=> refactor(migrations): do not duplicate theme props

projects/igniteui-angular/migrations/common/UpdateChanges.spec.ts, projects/igniteui-angular/migrations/common/util.ts
=> fix(migrations): don't skip library projects, don't append prefix

projects/igniteui-angular/src/lib/core/i18n/resources.ts
=> Extend IResourceStrings with all available component interfaces

projects/igniteui-angular/src/lib/core/i18n/calendar-resources.ts, projects/igniteui-angular/src/lib/core/i18n/resources.ts
=> Extend IResourceStrings with all available component interfaces - 11.0.x

projects/igniteui-angular/src/lib/core/i18n/calendar-resources.ts, projects/igniteui-angular/src/lib/core/i18n/resources.ts
=> Extend IResourceStrings with all available component interfaces - 11.1.x

projects/igniteui-angular/src/lib/core/styles/components/grid/_grid-theme.scss, projects/igniteui-angular/src/lib/core/styles/components/icon/_icon-component.scss
=> refactor(grid, icon): reduce compiled CSS size

projects/igniteui-angular/src/lib/core/styles/components/grid-toolbar/_grid-toolbar-theme.scss
=> refactor(grid-toolbar): reduce compiled CSS size

projects/igniteui-angular/src/lib/core/styles/components/grid-summary/_grid-summary-component.scss
=> refactor(grid-summaries): reduce compiled CSS size

projects/igniteui-angular/src/lib/core/styles/components/list/_list-component.scss, projects/igniteui-angular/src/lib/core/styles/components/list/_list-theme.scss, projects/igniteui-angular/src/lib/list/list.component.html, projects/igniteui-angular/src/lib/list/list.component.spec.ts, projects/igniteui-angular/src/lib/list/list.component.ts, src/app/list/list.sample.html, src/app/list/list.sample.scss
=> refactor(list): reduce compiled CSS

projects/igniteui-angular/src/lib/tree/common.ts, projects/igniteui-angular/src/lib/tree/tree-functions.spec.ts, projects/igniteui-angular/src/lib/tree/tree-node/tree-node.component.html, projects/igniteui-angular/src/lib/tree/tree-node/tree-node.component.ts, projects/igniteui-angular/src/lib/tree/tree-selection.service.spec.ts, projects/igniteui-angular/src/lib/tree/tree-selection.service.ts, projects/igniteui-angular/src/lib/tree/tree-selection.spec.ts, projects/igniteui-angular/src/lib/tree/tree.component.ts, src/app/tree/tree.sample.html, src/app/tree/tree.sample.ts
=> igxTree BiState selection

projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid-filtering.spec.ts, projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid.filtering.pipe.ts, projects/igniteui-angular/src/lib/test-utils/grid-functions.spec.ts
=> Change treeGrid filtering pipe #9014

projects/igniteui-angular/src/lib/services/overlay/overlay.spec.ts, projects/igniteui-angular/src/lib/services/overlay/overlay.ts
=> fix(overlay): remove escape keydown listener when outlet is used - master

projects/igniteui-angular/src/lib/grids/filtering/excel-style/grid.excel-style-filtering.component.ts, projects/igniteui-angular/src/lib/grids/grid/grid-filtering-ui.spec.ts
=> fix(ESF): Made search component's boolean values localizable.

projects/igniteui-angular/src/lib/core/styles/components/grid/_grid-theme.scss
=> fix(grid): remove redundant button transition

projects/igniteui-angular/src/lib/toast/toast.component.ts
=> fix(toast): improve accessibility

projects/igniteui-angular/src/lib/checkbox/checkbox.component.html, projects/igniteui-angular/src/lib/checkbox/checkbox.component.ts, projects/igniteui-angular/src/lib/grids/grid/grid.groupby.spec.ts
=> fix(checkbox): improve accessibility

projects/igniteui-angular/src/lib/radio/radio.component.html, projects/igniteui-angular/src/lib/radio/radio.component.ts, src/app/input/input.sample.html, src/app/input/input.sample.ts
=> fix(radio): can't select radio on click

projects/igniteui-angular/src/lib/snackbar/snackbar.component.html, projects/igniteui-angular/src/lib/snackbar/snackbar.component.ts, src/app/snackbar/snackbar.sample.html
=> fix: (igx-snackbar) Add aria-live attr to the message container.

projects/igniteui-angular/src/lib/grids/grid-base.directive.ts, projects/igniteui-angular/src/lib/grids/grid/grid.component.html, projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.component.html, projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid.component.html
=> fix(column-selection): handle mac column copy -master #8819

projects/igniteui-angular/src/lib/grids/grid-base.directive.ts, projects/igniteui-angular/src/lib/grids/grid/grid-clipboard.spec.ts, projects/igniteui-angular/src/lib/grids/grid/grid.component.html, projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.component.html, projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid.component.html, projects/igniteui-angular/src/lib/services/csv/char-separated-value-data.ts
=> fix(column-selection): allow to copy column values-11.1.x #8819

azure-pipelines.yml, projects/igniteui-angular/src/lib/core/setImmediate.ts
=> fix(excel-export): workaround an issue in codesandbox

projects/igniteui-angular/src/lib/core/styles/components/action-strip/_action-strip-theme.scss
=> fix(action-strip): icon buttons wrong color

projects/igniteui-angular/src/lib/radio/radio.component.html, projects/igniteui-angular/src/lib/radio/radio.component.ts, src/app/input/input.sample.html, src/app/input/input.sample.ts
=> fix(radio): do not emit event on deselect

projects/igniteui-angular/src/lib/tabs/bottom-nav/bottom-nav.component.html, projects/igniteui-angular/src/lib/tabs/bottom-nav/bottom-nav.component.ts, projects/igniteui-angular/src/lib/tabs/tab-header.directive.ts, projects/igniteui-angular/src/lib/tabs/tab-panel.directive.ts, projects/igniteui-angular/src/lib/tabs/tabs.directive.ts, projects/igniteui-angular/src/lib/tabs/tabs/tabs.component.html, projects/igniteui-angular/src/lib/tabs/tabs/tabs.component.ts
=> feat(tabs): ARIA support #8912

projects/igniteui-angular/src/lib/radio/radio.component.ts
=> fix(radio): ngModelChange fires multiple times

projects/igniteui-angular/karma.azure.non-grid.conf.js, projects/igniteui-angular/src/lib/tree/common.ts, projects/igniteui-angular/src/lib/tree/tree-functions.spec.ts, projects/igniteui-angular/src/lib/tree/tree-node/tree-node.component.html, projects/igniteui-angular/src/lib/tree/tree-node/tree-node.component.ts, projects/igniteui-angular/src/lib/tree/tree-selection.service.spec.ts, projects/igniteui-angular/src/lib/tree/tree-selection.service.ts, projects/igniteui-angular/src/lib/tree/tree-selection.spec.ts, projects/igniteui-angular/src/lib/tree/tree.component.ts, src/app/tree/tree.sample.html, src/app/tree/tree.sample.ts
=> chore(tree): cascade selection initial implementation

projects/igniteui-angular/src/lib/chips/chip.component.html, projects/igniteui-angular/src/lib/chips/chip.component.ts, projects/igniteui-angular/src/lib/chips/chips-area.component.ts, projects/igniteui-angular/src/lib/core/i18n/chip-resources.ts, projects/igniteui-angular/src/lib/core/i18n/resources.ts
=> fix(chip): improve accessibility

CHANGELOG.md, projects/igniteui-angular/src/lib/directives/for-of/display.container.ts, projects/igniteui-angular/src/lib/directives/for-of/for_of.directive.spec.ts, projects/igniteui-angular/src/lib/directives/scroll-inertia/scroll_inertia.directive.spec.ts, projects/igniteui-angular/src/lib/directives/scroll-inertia/scroll_inertia.directive.ts, projects/igniteui-angular/src/lib/grids/grid/grid.component.spec.ts
=> Implement mouse wheel smoothing.

projects/igniteui-angular/src/lib/grids/common/pipes.ts, src/app/grid-events/grid-events.component.ts
=> fix(lint): cell styling and pipes warnings

projects/igniteui-angular/src/lib/grids/grid-base.directive.ts, src/app/hierarchical-grid-remote/hierarchical-grid-remote.sample.html, src/app/hierarchical-grid-remote/hierarchical-grid-remote.sample.ts
Closes #9073 
Fixes both sample and library issues.
=> Fixes isLoading on a not yet loaded row island

projects/igniteui-angular/src/lib/directives/radio/radio-group.directive.ts
=> fix(radio-group): missing setDisabledState

projects/igniteui-angular/src/lib/core/styles/base/utilities/_functions.scss, projects/igniteui-angular/src/lib/core/styles/base/utilities/_mixins.scss, projects/igniteui-angular/src/lib/core/styles/spec/_mixins.spec.scss, projects/igniteui-angular/src/lib/core/styles/themes/_palettes.scss, projects/igniteui-angular/src/lib/core/styles/themes/presets/igniteui-angular-dark-rtl.scss, projects/igniteui-angular/src/lib/core/styles/themes/presets/igniteui-angular-dark.scss, projects/igniteui-angular/src/lib/core/styles/themes/presets/igniteui-angular-rtl.scss, projects/igniteui-angular/src/lib/core/styles/themes/presets/igniteui-angular.scss, projects/igniteui-angular/src/lib/core/styles/themes/presets/igniteui-bootstrap-dark-rtl.scss, projects/igniteui-angular/src/lib/core/styles/themes/presets/igniteui-bootstrap-dark.scss, projects/igniteui-angular/src/lib/core/styles/themes/presets/igniteui-bootstrap-light-rtl.scss, projects/igniteui-angular/src/lib/core/styles/themes/presets/igniteui-bootstrap-light.scss, projects/igniteui-angular/src/lib/core/styles/themes/presets/igniteui-dark-green-rtl.scss, projects/igniteui-angular/src/lib/core/styles/themes/presets/igniteui-dark-green.scss, projects/igniteui-angular/src/lib/core/styles/themes/presets/igniteui-fluent-dark-excel-rtl.scss, projects/igniteui-angular/src/lib/core/styles/themes/presets/igniteui-fluent-dark-excel.scss, projects/igniteui-angular/src/lib/core/styles/themes/presets/igniteui-fluent-dark-word-rtl.scss, projects/igniteui-angular/src/lib/core/styles/themes/presets/igniteui-fluent-dark-word.scss, projects/igniteui-angular/src/lib/core/styles/themes/presets/igniteui-fluent-light-excel-rtl.scss, projects/igniteui-angular/src/lib/core/styles/themes/presets/igniteui-fluent-light-excel.scss, projects/igniteui-angular/src/lib/core/styles/themes/presets/igniteui-fluent-light-word-rtl.scss, projects/igniteui-angular/src/lib/core/styles/themes/presets/igniteui-fluent-light-word.scss, projects/igniteui-angular/src/lib/core/styles/themes/presets/igniteui-indigo-dark-rtl.scss, projects/igniteui-angular/src/lib/core/styles/themes/presets/igniteui-indigo-dark.scss, projects/igniteui-angular/src/lib/core/styles/themes/presets/igniteui-indigo-light-rtl.scss, projects/igniteui-angular/src/lib/core/styles/themes/presets/igniteui-indigo-light.scss, src/app/styleguide/colors/color.sample.html, src/app/styleguide/colors/color.sample.scss, src/styles/_demo-theme.scss, src/styles/_variables.scss
=> feat(themes): CSS variable palettes use HSL colors

CHANGELOG.md, projects/igniteui-angular/src/lib/grids/grid-base.directive.ts, projects/igniteui-angular/src/lib/grids/grid-common.module.ts, projects/igniteui-angular/src/lib/grids/grid.rowEdit.directive.ts, projects/igniteui-angular/src/lib/grids/grid/grid-add-row.spec.ts, projects/igniteui-angular/src/lib/grids/grid/grid.component.html, projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.component.html, projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid.component.html, projects/igniteui-angular/src/lib/test-utils/grid-samples.spec.ts
=> Add igxRowAddText directive for templating add row banner

projects/igniteui-angular/src/lib/core/styles/components/bottom-nav/_bottom-nav-component.scss, projects/igniteui-angular/src/lib/core/styles/components/bottom-nav/_bottom-nav-theme.scss, projects/igniteui-angular/src/lib/tabs/bottom-nav/bottom-nav-panel.component.ts, projects/igniteui-angular/src/lib/tabs/bottom-nav/bottom-nav.component.html, src/app/app.module.ts, src/app/bottomnav/bottomnav.sample.css, src/app/bottomnav/bottomnav.sample.html
=> feat(bottom-nav): provide styling after component refactoring

projects/igniteui-angular/src/lib/core/styles/components/drop-down/_drop-down-theme.scss, projects/igniteui-angular/src/lib/core/styles/components/scrollbar/scrollbar-theme.scss
=> fix(scrollbar): shows empty space in iOS Safari

projects/igniteui-angular/src/lib/grids/state.directive.spec.ts, projects/igniteui-angular/src/lib/grids/state.directive.ts
=> Clear current selection when setting new selection state

projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid-api.service.ts
=> fix(tree-grid): added check for grid - 11.1.x

projects/igniteui-angular/src/lib/grids/grid-base.directive.ts
=> fix(GRID): expose end edit facade Closes #8330

projects/igniteui-angular/migrations/update-12_0_0/changes/theme-props.json, projects/igniteui-angular/src/lib/core/styles/themes/_index.scss
=> migrations(themes): update button migration

src/app/app.component.ts, src/app/app.module.ts, src/app/app.routing.ts, src/app/grid-finjs/controllers.component.html, src/app/grid-finjs/controllers.component.ts, src/app/grid-finjs/grid-finjs.component.html, src/app/grid-finjs/grid-finjs.component.ts, src/app/grid-finjs/main.component.html, src/app/grid-finjs/main.component.scss, src/app/grid-finjs/main.component.ts, src/app/grid-updates-test/aminoData.ts, src/app/grid-updates-test/grid-updates.component.html, src/app/grid-updates-test/grid-updates.component.ts, src/app/routing.ts, src/app/shared/local.service.ts
=> Dev demos update - add sample to test nested props update

projects/igniteui-angular/src/lib/grids/grid-base.directive.ts
=> fix(grid): Consider min/max width when setting defaultWidth property

projects/igniteui-angular/src/lib/core/styles/base/utilities/_mixins.scss, src/styles/_demo-theme.scss, src/styles/_variables.scss
=> fix(themes): handmade palettes don't work

projects/igniteui-angular/src/lib/grids/grid-base.directive.ts, projects/igniteui-angular/src/lib/grids/grid-navigation.service.ts
=> fix(kb-nav): clear active node when leaving summary section

projects/igniteui-angular/migrations/common/UpdateChanges.spec.ts, projects/igniteui-angular/migrations/common/UpdateChanges.ts
=> Migrations rename fixes

projects/igniteui-angular/src/lib/test-utils/configure-suite.ts
=> test(Filtering): Clear svgContainer. (#9222)

projects/igniteui-angular/src/lib/core/styles/components/tree/_tree-component.scss, projects/igniteui-angular/src/lib/core/styles/components/tree/_tree-theme.scss, projects/igniteui-angular/src/lib/core/styles/themes/schemas/dark/_tree.scss, projects/igniteui-angular/src/lib/core/styles/themes/schemas/light/_tree.scss, projects/igniteui-angular/src/lib/tree/tree-node/tree-node.component.html, src/app/tree/tree.sample.html, src/app/tree/tree.sample.scss
=> Tree themes styling

projects/igniteui-angular/src/lib/core/styles/components/grid/_grid-theme.scss, projects/igniteui-angular/src/lib/grids/grid-base.directive.ts, projects/igniteui-angular/src/lib/grids/grid/column-hiding.spec.ts, projects/igniteui-angular/src/lib/grids/grid/grid-summary.spec.ts, projects/igniteui-angular/src/lib/grids/grid/grid.component.html, projects/igniteui-angular/src/lib/grids/grid/grid.component.ts, projects/igniteui-angular/src/lib/grids/grid/grid.groupby.spec.ts, projects/igniteui-angular/src/lib/grids/headers/grid-header-group.component.ts, projects/igniteui-angular/src/lib/grids/headers/grid-header.component.ts, projects/igniteui-angular/src/lib/grids/hierarchical-grid/child-grid-row.component.ts, projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.component.html, projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.component.ts, projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.navigation.spec.ts, projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid.component.html, projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid.component.ts, projects/igniteui-angular/src/lib/test-utils/grid-functions.spec.ts
=> Grid accessibility 11.1.x

projects/igniteui-angular/src/lib/core/styles/typography/_base.scss
=> fix(typography): add missing font-style

projects/igniteui-angular/src/lib/core/styles/base/utilities/_mixins.scss, projects/igniteui-angular/src/lib/core/styles/components/badge/_badge-theme.scss, projects/igniteui-angular/src/lib/core/styles/components/bottom-nav/_bottom-nav-theme.scss, projects/igniteui-angular/src/lib/core/styles/components/button-group/_button-group-theme.scss, projects/igniteui-angular/src/lib/core/styles/components/button/_button-theme.scss, projects/igniteui-angular/src/lib/core/styles/components/card/_card-theme.scss, projects/igniteui-angular/src/lib/core/styles/components/carousel/_carousel-theme.scss, projects/igniteui-angular/src/lib/core/styles/components/column-actions/_column-actions-theme.scss, projects/igniteui-angular/src/lib/core/styles/components/date-picker/_date-picker-theme.scss, projects/igniteui-angular/src/lib/core/styles/components/dialog/_dialog-theme.scss, projects/igniteui-angular/src/lib/core/styles/components/drop-down/_drop-down-theme.scss, projects/igniteui-angular/src/lib/core/styles/components/grid-toolbar/_grid-toolbar-theme.scss, projects/igniteui-angular/src/lib/core/styles/components/grid/_grid-theme.scss, projects/igniteui-angular/src/lib/core/styles/components/input/_input-group-theme.scss, projects/igniteui-angular/src/lib/core/styles/components/list/_list-theme.scss, projects/igniteui-angular/src/lib/core/styles/components/navbar/_navbar-theme.scss, projects/igniteui-angular/src/lib/core/styles/components/navdrawer/_navdrawer-theme.scss, projects/igniteui-angular/src/lib/core/styles/components/snackbar/_snackbar-theme.scss, projects/igniteui-angular/src/lib/core/styles/themes/schemas/light/_avatar.scss, projects/igniteui-angular/src/lib/core/styles/themes/schemas/light/_grid.scss
=> docs(themes): fix warnings

projects/igniteui-angular/src/lib/core/styles/components/button/_button-theme.scss, src/app/button/button.sample.html
=> fix(button): Update the FAB button to support multiple icons from both sides

projects/igniteui-angular/src/lib/core/styles/components/tabs/_tabs-theme.scss
=> fix(tabs): Remove tabs height #9258

projects/igniteui-angular/src/lib/combo/combo.component.spec.ts, projects/igniteui-angular/src/lib/icon/icon.service.spec.ts, projects/igniteui-angular/src/lib/icon/icon.service.ts, src/app/app.module.ts, src/app/icon/LazyModule/LazyComponent/lazyIcon.sample.ts, src/app/icon/icon.sample.ts, src/app/interceptor.service.ts
=> fix(icon-service): destroy parent container on HMR

projects/igniteui-angular/src/lib/action-strip/grid-actions/grid-editing-actions.component.spec.ts, projects/igniteui-angular/src/lib/action-strip/grid-actions/grid-editing-actions.component.ts
=> fix(action-strip): Activate first editable through grid editing actions #9240

projects/igniteui-angular/src/lib/core/styles/components/bottom-nav/_bottom-nav-theme.scss, src/app/bottomnav/bottomnav.sample.css, src/app/bottomnav/bottomnav.sample.html
=> Display set to none when panel is empty

projects/igniteui-angular/src/lib/core/styles/components/bottom-nav/_bottom-nav-theme.scss
=> remove content padding overlap on other elements  #9272

projects/igniteui-angular/src/lib/grids/api.service.ts, projects/igniteui-angular/src/lib/grids/filtering/grid-filtering.service.ts, projects/igniteui-angular/src/lib/grids/grid-base.directive.ts, projects/igniteui-angular/src/lib/grids/grid/grid-cell-editing.spec.ts, projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.spec.ts, projects/igniteui-angular/src/lib/grids/hierarchical-grid/row-island.component.ts
=> fix(hierarchical-grid): fixed row island filtering - 11.1.x

projects/igniteui-angular/src/lib/grids/api.service.ts, projects/igniteui-angular/src/lib/grids/filtering/grid-filtering.service.ts, projects/igniteui-angular/src/lib/grids/grid-base.directive.ts, projects/igniteui-angular/src/lib/grids/grid/grid-cell-editing.spec.ts, projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.spec.ts, projects/igniteui-angular/src/lib/grids/hierarchical-grid/row-island.component.ts
=> fix(hierarchical-grid): fixed row island filtering - master

projects/igniteui-angular/src/lib/carousel/carousel.component.ts
=> fix(carousel): wrapping RAF init call in isBrowser

projects/igniteui-angular/src/lib/grids/api.service.ts, projects/igniteui-angular/src/lib/grids/filtering/grid-filtering.service.ts, projects/igniteui-angular/src/lib/grids/grid-base.directive.ts, projects/igniteui-angular/src/lib/grids/grid/grid-cell-editing.spec.ts, projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.spec.ts, projects/igniteui-angular/src/lib/grids/hierarchical-grid/row-island.component.ts
=> fix(hierarchical-grid): fixed row island filtering - 10.2.x

projects/igniteui-angular/src/lib/grids/grid/grid.component.ts
=> Recalculate grid sizes if group area is shown/hidden

projects/igniteui-angular/src/lib/grids/row.directive.ts
=> fix(row-selection): preserve row selection when holding cmd on cell

projects/igniteui-angular/src/lib/core/styles/base/utilities/_mixins.scss, projects/igniteui-angular/src/lib/core/styles/components/dock-manager/_dock-manager-component.scss, projects/igniteui-angular/src/lib/core/styles/components/dock-manager/_dock-manager-theme.scss, projects/igniteui-angular/src/lib/core/styles/spec/_index.scss, projects/igniteui-angular/src/lib/core/styles/spec/_mixins.spec.scss, projects/igniteui-angular/src/lib/core/styles/themes/_core.scss, projects/igniteui-angular/src/lib/core/styles/themes/_index.scss, projects/igniteui-angular/src/lib/core/styles/themes/schemas/dark/_index.scss, projects/igniteui-angular/src/lib/core/styles/themes/schemas/light/_index.scss, src/styles/_demo-theme.scss
=> fix(themes): make theme excludable and add fixes for master

projects/igniteui-angular/src/lib/core/styles/components/charts/_category-chart-theme.scss, projects/igniteui-angular/src/lib/core/styles/components/charts/_data-chart-theme.scss, projects/igniteui-angular/src/lib/core/styles/components/charts/_doughnut-chart-theme.scss, projects/igniteui-angular/src/lib/core/styles/components/charts/_financial-chart-theme.scss, projects/igniteui-angular/src/lib/core/styles/components/charts/_funnel-chart-theme.scss, projects/igniteui-angular/src/lib/core/styles/components/charts/_gauge-theme.scss, projects/igniteui-angular/src/lib/core/styles/components/charts/_geo-map-theme.scss, projects/igniteui-angular/src/lib/core/styles/components/charts/_graph-theme.scss, projects/igniteui-angular/src/lib/core/styles/components/charts/_pie-chart-theme.scss, projects/igniteui-angular/src/lib/core/styles/components/charts/_shape-chart-theme.scss, projects/igniteui-angular/src/lib/core/styles/components/charts/_sparkline-theme.scss
=> fix(themes): dv themes not working

projects/igniteui-angular/src/lib/tree/tree-functions.spec.ts, projects/igniteui-angular/src/lib/tree/tree-navigation.service.ts, projects/igniteui-angular/src/lib/tree/tree-navigation.spec.ts, projects/igniteui-angular/src/lib/tree/tree-node/tree-node.component.html, projects/igniteui-angular/src/lib/tree/tree-node/tree-node.component.ts, projects/igniteui-angular/src/lib/tree/tree-samples.spec.ts, projects/igniteui-angular/src/lib/tree/tree-selection.service.spec.ts, projects/igniteui-angular/src/lib/tree/tree-selection.spec.ts, projects/igniteui-angular/src/lib/tree/tree.component.ts, projects/igniteui-angular/src/lib/tree/tree.spec.ts
=> igxTree navigation tests

projects/igniteui-angular/src/lib/core/styles/components/scrollbar/scrollbar-theme.scss
=> Fix scrollbar theme def docs

projects/igniteui-angular/migrations/update-12_0_0/changes/members.json, projects/igniteui-angular/migrations/update-12_0_0/changes/outputs.json
=> Migrate for-of events as members

projects/igniteui-angular/src/lib/tabs/bottom-nav/bottom-nav.component.ts, projects/igniteui-angular/src/lib/tabs/tabs/tabs.component.ts
=> Fix Tabs and Bottom Navigation API docs indentation

projects/igniteui-angular/src/lib/core/styles/components/grid/_grid-theme.scss
=> fix(theme): size date and time pickers in cell-editing mode

projects/igniteui-angular/src/lib/core/styles/base/utilities/_mixins.scss, projects/igniteui-angular/src/lib/core/styles/components/button/_button-theme.scss, projects/igniteui-angular/src/lib/core/styles/themes/schemas/light/_button.scss
=> fix(button): themes not working correctly

projects/igniteui-angular/src/lib/date-picker/date-picker.component.spec.ts, projects/igniteui-angular/src/lib/date-picker/date-picker.component.ts
=> fix(date-picker): emit proper event args on open/close events

projects/igniteui-angular/src/lib/directives/date-time-editor/date-time-editor.common.ts, projects/igniteui-angular/src/lib/directives/date-time-editor/date-time-editor.directive.spec.ts, projects/igniteui-angular/src/lib/directives/date-time-editor/date-time-editor.directive.ts, projects/igniteui-angular/src/lib/time-picker/time-picker.common.ts, projects/igniteui-angular/src/lib/time-picker/time-picker.component.spec.ts, projects/igniteui-angular/src/lib/time-picker/time-picker.component.ts, projects/igniteui-angular/src/lib/time-picker/time-picker.directives.ts
=> Make DatePart & DatePartDeltas hour, minute, second plural

projects/igniteui-angular/src/lib/date-picker/date-picker.component.spec.ts
=> test(date-picker): basic unit test coverage

projects/igniteui-angular/src/lib/grids/filtering/base/grid-filtering-row.component.ts, projects/igniteui-angular/src/lib/grids/grid/grid-filtering-ui.spec.ts
=> Astaev/issue9333 10.2.x

projects/igniteui-angular/src/lib/grids/column-actions/column-actions.component.html, projects/igniteui-angular/src/lib/grids/column-actions/column-actions.component.ts, projects/igniteui-angular/src/lib/grids/toolbar/grid-toolbar.base.ts, src/app/time-picker/time-picker.sample.html, src/app/time-picker/time-picker.sample.ts
=> fix(toolbar): replace column-actions change event

projects/igniteui-angular/src/lib/grids/column-actions/column-actions.component.html, projects/igniteui-angular/src/lib/grids/column-actions/column-actions.component.ts, projects/igniteui-angular/src/lib/grids/grid/column-hiding.spec.ts, projects/igniteui-angular/src/lib/grids/toolbar/grid-toolbar.base.ts
=> fix(toolbar): Fixed columnToggle emitter -11.1.x

projects/igniteui-angular/src/lib/grids/filtering/base/grid-filtering-row.component.ts, projects/igniteui-angular/src/lib/grids/grid/grid-filtering-ui.spec.ts
=> fix(filtering): Refine elem class search #9333

src/app/grid-events/grid-events.component.html, src/app/grid-row-api/grid-row-api.sample.html, src/app/tree-grid/tree-grid.sample.html
=> fix(demos): fixing issues with demos after event rename

projects/igniteui-angular/src/lib/date-range-picker/date-range-picker.component.spec.ts
=> test(date-range-picker): run disable test

package-lock.json, package.json, projects/igniteui-angular/ng-package.json, projects/igniteui-angular/ng-package.prod.json, projects/igniteui-angular/package.json, projects/igniteui-angular/schematics/utils/dependency-handler.ts, projects/igniteui-angular/src/lib/core/utils.ts, projects/igniteui-angular/src/lib/directives/for-of/for_of.directive.ts, projects/igniteui-angular/src/lib/grids/grid-base.directive.ts, projects/igniteui-angular/src/lib/tabs/tabs/tab-header.component.ts
Closes #9427
This might be the fix for the failing [builds](https://github.com/IgniteUI/igniteui-angular/pull/9061/checks?check_run_id=2390282555)
This is the new [package](https://www.npmjs.com/package/@juggle/resize-observer)
=> Switch resize observer

projects/igniteui-angular/src/lib/core/i18n/resources.ts
Tree i18n resource strings were not properly being exposed
=> fix(tree): expose i18n resource strings

projects/igniteui-angular/src/lib/date-range-picker/date-range-picker.component.spec.ts
=> test(date-picker): fix range selection UI tests

CHANGELOG.md, projects/igniteui-angular/src/lib/date-common/calendar-container/calendar-container.component.html, projects/igniteui-angular/src/lib/date-common/calendar-container/calendar-container.component.spec.ts, src/app/date-picker/date-picker.sample.html, src/app/date-picker/date-picker.sample.scss, src/app/date-picker/date-picker.sample.ts
=> feat(date-picker,date-range): add calendar as implicit actions context

projects/igniteui-angular/src/public_api.ts
=> fix(tree): export resource string in public API

CHANGELOG.md
=> docs(changelog): Remove duplicate general header

CHANGELOG.md, projects/igniteui-angular/migrations/update-12_0_0/changes/members.json, projects/igniteui-angular/migrations/update-12_0_0/changes/outputs.json
=> Apply migrations for onCellClick to cellClick

projects/igniteui-angular/src/lib/grids/state.directive.ts, projects/igniteui-angular/src/lib/grids/state.hierarchicalgrid.spec.ts
=> Pipe the columnList changes to take effect once

projects/igniteui-angular/src/lib/time-picker/time-picker.component.ts
=> Fix outside click

projects/igniteui-angular/src/lib/grids/filtering/excel-style/grid.excel-style-filtering.component.ts, projects/igniteui-angular/src/lib/grids/grid/grid-filtering-ui.spec.ts
=> fix(esf): using column sort strategy for esf search - 10.2.x

projects/igniteui-angular/src/lib/grids/grid/grid.component.ts
=> fix(grid): Restore groupby state - 10.2.x

projects/igniteui-angular/src/lib/grids/grid/grid.component.ts
=> fix(grid): Restore groupby state - 11.1.x

projects/igniteui-angular/src/lib/grids/grid-base.directive.ts, projects/igniteui-angular/src/lib/grids/hierarchical-grid/row-island.component.ts, projects/igniteui-angular/src/lib/grids/row-drag.directive.ts
=> Explicitly trigger grid pipes on markForCheck call

src/app/grid-filter-template/grid-filter-template.sample.html, src/app/grid-filter-template/grid-filter-template.sample.ts
=> Fixed number and date input values in Filter template demo.

projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid-summaries.spec.ts, projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid.component.ts
Closes #9465
Related to #5673
Please, verify the original scenario as well.
=> fix(TreeGrid): Fixed deselectChildren() logic so it deselects records not in view

projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid-summaries.spec.ts, projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid.component.ts
Closes #9465
Related to #5673
Please, verify the original scenario as well.
=> Fixed deselectChildren() logic so it deselects records not in view

projects/igniteui-angular/src/lib/date-range-picker/date-range-picker.component.spec.ts
=> Done button test does not verify selection

projects/igniteui-angular/src/lib/core/styles/components/avatar/_avatar-theme.scss
=> fix(avatar): new themes always apply square border radius

projects/igniteui-angular/src/lib/core/styles/components/calendar/_calendar-theme.scss
=> fix(calendar) range selection colors

CHANGELOG.md, projects/igniteui-angular/src/lib/directives/toggle/toggle.directive.ts, projects/igniteui-angular/src/lib/snackbar/README.md, projects/igniteui-angular/src/lib/snackbar/snackbar.component.ts, projects/igniteui-angular/src/lib/toast/toast.component.spec.ts, projects/igniteui-angular/src/lib/toast/toast.component.ts, src/app/toast/toast.sample.html
=> chore(snackbar, toast): removing deprecated properties and outputs

ROADMAP.md
=> chore(*): m16final

projects/igniteui-angular/src/lib/core/styles/components/grid/_grid-theme.scss
=> fix(hierarchical-grid): expander indicator not inheriting the background from the row.

projects/igniteui-angular/src/lib/grids/selection/selection.service.ts
=> fix(grid): Prevent drag selection from outside clicks

projects/igniteui-angular/package.json
=> chore(*): update package.json & igniteui/angular-schematics

src/app/list-panning/list-panning.sample.css, src/app/list-panning/list-panning.sample.html, src/app/list-panning/list-panning.sample.ts, src/app/list-performance/list-performance.sample.css, src/app/list-performance/list-performance.sample.html, src/app/list/list.sample.html, src/app/list/list.sample.ts
Fixed the issue with favorite icon not changing because of the refactored igx-icon. Updated a few event names. Fixed an issue with disabling filtering in one of the demos. Removed some no longer necessary styles.
=> fix(List): Fixed broken dev demos.

projects/igniteui-angular/src/lib/core/utils.ts, projects/igniteui-angular/src/lib/directives/for-of/for_of.directive.ts, projects/igniteui-angular/src/lib/grids/grid-base.directive.ts, projects/igniteui-angular/src/lib/tabs/tabs/tab-header.component.ts, projects/igniteui-angular/src/lib/tabs/tabs/tabs.component.ts
=> chore(*): fix resize observer import

projects/igniteui-angular/src/lib/core/styles/components/column-actions/_column-actions-theme.scss, projects/igniteui-angular/src/lib/grids/grid/column-hiding.spec.ts
=> fix(grid): reduce space between items in column actions -11.1.x

CHANGELOG.md, projects/igniteui-angular/src/lib/date-picker/README.md, projects/igniteui-angular/src/lib/directives/date-time-editor/README.md
=> Updating changelog and readme

projects/igniteui-angular/src/lib/date-common/picker-base.directive.ts
=> fix(pickers): use any on base property due to strict compile errors

projects/igniteui-angular/src/lib/date-range-picker/date-range-picker.component.html, projects/igniteui-angular/src/lib/date-range-picker/date-range-picker.component.spec.ts
=> Set range picker's default toggle icon to be date_range

projects/igniteui-angular/src/lib/date-common/util/date-time.util.spec.ts, projects/igniteui-angular/src/lib/date-common/util/date-time.util.ts
=> Treat all year formats that are not "yy" as "yyyy"

projects/igniteui-angular/package.json
=> chore(*): update product package

projects/igniteui-angular/src/lib/core/styles/components/calendar/_calendar-theme.scss, projects/igniteui-angular/src/lib/core/styles/components/date-picker/_date-picker-theme.scss
=> feat(calendar): update calendar min width.

projects/igniteui-angular/package.json
=> chore(schematics): use rc.0 for cli

projects/igniteui-angular/package.json
=> chore(schematics): put igniteui/angular-schematics 12

projects/igniteui-angular/src/lib/action-strip/grid-actions/grid-action-button.component.html, projects/igniteui-angular/src/lib/action-strip/grid-actions/grid-action-button.component.ts
=> refactor(grid-action-buttons): Improve contradicting conditions in template

projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid.component.ts
=> Add a null check of filteredSortedData in getRowByKey method

projects/igniteui-angular/src/lib/services/excel/excel-exporter.ts
=> feat(excel-exporter): add excel limitations

projects/igniteui-angular/src/lib/grids/grid-base.directive.ts, projects/igniteui-angular/src/lib/grids/grid/grid.component.html, projects/igniteui-angular/src/lib/grids/grid/grid.component.spec.ts
=> fix(grid): aria-children-tests#9318-10.2.x

ROADMAP.md
=> chore(*):roadmap-m17-initial-update

projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid-crud.spec.ts, projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid.component.ts
=> Fix and test for #9510.

projects/igniteui-angular/src/lib/services/excel/excel-exporter.ts
=> fix(excel-exporter): fix null checks in excel exporter

CHANGELOG.md, projects/igniteui-angular/migrations/update-12_1_0/changes/members.json, projects/igniteui-angular/migrations/update-12_1_0/changes/outputs.json, projects/igniteui-angular/migrations/update-12_1_0/index.spec.ts, projects/igniteui-angular/src/lib/banner/README.md, projects/igniteui-angular/src/lib/banner/banner.component.html, projects/igniteui-angular/src/lib/banner/banner.component.spec.ts, projects/igniteui-angular/src/lib/banner/banner.component.ts, projects/igniteui-angular/src/lib/expansion-panel/README.md, projects/igniteui-angular/src/lib/expansion-panel/expansion-panel-header.component.ts, projects/igniteui-angular/src/lib/expansion-panel/expansion-panel.common.ts, projects/igniteui-angular/src/lib/expansion-panel/expansion-panel.component.ts, projects/igniteui-angular/src/lib/expansion-panel/expansion-panel.spec.ts, src/app/expansion-panel/expansion-panel-sample.html
Update expansion panel and banner API to conform to linting rules - removed 'on' from all public outputs.
Added migrations.
=> chore(banner, panel): update panel and banner API

projects/igniteui-angular/src/lib/date-picker/date-picker.component.ts
=> Fix build error in "strictTemplates" mode v.11.1

projects/igniteui-angular/src/lib/date-picker/date-picker.component.ts
=> Fix build error in "strictTemplates" mode

projects/igniteui-angular/src/lib/combo/combo.component.spec.ts, projects/igniteui-angular/src/lib/combo/combo.component.ts, projects/igniteui-angular/src/lib/date-picker/date-picker.component.spec.ts, projects/igniteui-angular/src/lib/date-picker/date-picker.component.ts, projects/igniteui-angular/src/lib/date-range-picker/date-range-picker.component.ts, projects/igniteui-angular/src/lib/select/select.component.spec.ts, projects/igniteui-angular/src/lib/select/select.component.ts, projects/igniteui-angular/src/lib/time-picker/time-picker.component.spec.ts, projects/igniteui-angular/src/lib/time-picker/time-picker.component.ts
=> Editors properly update their validity state on resetForm - 11.1.x

projects/igniteui-angular/schematics/ng-add/schema.json
Closes #  
To test, run `ng add` locally, the following message should not appear in the console:
=> Update ng-add schema id to $id

projects/igniteui-angular/src/lib/combo/combo.component.spec.ts, projects/igniteui-angular/src/lib/combo/combo.component.ts, projects/igniteui-angular/src/lib/date-picker/date-picker.component.spec.ts, projects/igniteui-angular/src/lib/date-picker/date-picker.component.ts, projects/igniteui-angular/src/lib/date-range-picker/date-range-picker.component.ts, projects/igniteui-angular/src/lib/select/select.component.spec.ts, projects/igniteui-angular/src/lib/select/select.component.ts, projects/igniteui-angular/src/lib/time-picker/time-picker.component.spec.ts, projects/igniteui-angular/src/lib/time-picker/time-picker.component.ts
=> Editors properly update their validity state on resetForm - 10.2.x

projects/igniteui-angular/src/lib/combo/combo.common.ts, projects/igniteui-angular/src/lib/combo/combo.component.ts, projects/igniteui-angular/src/lib/grids/common/grid.interface.ts, projects/igniteui-angular/src/lib/grids/grid-base.directive.ts, projects/igniteui-angular/src/lib/grids/grid/grid.component.ts, projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.component.ts, projects/igniteui-angular/src/lib/grids/hierarchical-grid/row-island.component.ts, projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid.component.ts
=> Update "data" input property type definitions - 11.1.x

projects/igniteui-angular/src/lib/combo/combo.common.ts, projects/igniteui-angular/src/lib/combo/combo.component.ts, projects/igniteui-angular/src/lib/grids/common/grid.interface.ts, projects/igniteui-angular/src/lib/grids/grid-base.directive.ts, projects/igniteui-angular/src/lib/grids/grid/grid.component.ts, projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.component.ts, projects/igniteui-angular/src/lib/grids/hierarchical-grid/row-island.component.ts, projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid.component.ts
=> Update "data" input property type definitions - 12.0.x

projects/igniteui-angular/src/lib/combo/combo.common.ts, projects/igniteui-angular/src/lib/combo/combo.component.ts, projects/igniteui-angular/src/lib/grids/common/grid.interface.ts, projects/igniteui-angular/src/lib/grids/grid-base.directive.ts, projects/igniteui-angular/src/lib/grids/grid/grid.component.ts, projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.component.ts, projects/igniteui-angular/src/lib/grids/hierarchical-grid/row-island.component.ts, projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid.component.ts
=> Update "data" input property type definitions - 10.2.x

projects/igniteui-angular/src/lib/grids/filtering/base/grid-filtering-row.component.ts
=> fix(FilterRow): Changed chips scrolling logic.

projects/igniteui-angular/src/lib/grids/filtering/base/grid-filtering-row.component.ts
=>  fix(FilterRow): Changed chips scrolling logic.

CHANGELOG.md, projects/igniteui-angular/src/lib/expansion-panel/expansion-panel-header.component.html, projects/igniteui-angular/src/lib/expansion-panel/expansion-panel-header.component.ts, projects/igniteui-angular/src/lib/expansion-panel/expansion-panel.spec.ts
=> fix(expansion-panel): ensure disabled header is not tabbable - 10.2.x

CHANGELOG.md, projects/igniteui-angular/src/lib/expansion-panel/expansion-panel-header.component.html, projects/igniteui-angular/src/lib/expansion-panel/expansion-panel-header.component.ts, projects/igniteui-angular/src/lib/expansion-panel/expansion-panel.spec.ts
=> fix(expansion-panel): ensure disabled header is not tabbable - 11.1.x

CHANGELOG.md, projects/igniteui-angular/src/lib/expansion-panel/expansion-panel-header.component.html, projects/igniteui-angular/src/lib/expansion-panel/expansion-panel-header.component.ts, projects/igniteui-angular/src/lib/expansion-panel/expansion-panel.spec.ts
=> fix(expansion-panel): ensure disabled header is not tabbable - 12.0.x

CHANGELOG.md, projects/igniteui-angular/src/lib/expansion-panel/expansion-panel-header.component.html, projects/igniteui-angular/src/lib/expansion-panel/expansion-panel-header.component.ts, projects/igniteui-angular/src/lib/expansion-panel/expansion-panel.spec.ts
=> fix(expansion-panel): ensure disabled header is not tabbable

projects/igniteui-angular/src/lib/grids/api.service.ts, projects/igniteui-angular/src/lib/grids/grid/grid.component.ts
=> fix(grid): groupby sorting indicator

projects/igniteui-angular/src/lib/combo/combo.component.ts
=> Adding markForCheck in writeValue() - 10.2.x

projects/igniteui-angular/src/lib/combo/combo.component.ts
=> Adding markForCheck in writeValue() - 11.1.x

projects/igniteui-angular/src/lib/combo/combo.component.ts
=> fix(combo): Adding markForCheck in writeValue() - master

projects/igniteui-angular/src/lib/combo/combo.component.ts
=> fix(combo): Adding markForCheck in writeValue() - 12.0.x

projects/igniteui-angular/src/lib/dialog/dialog.component.ts
=> Update dialog dev docs - 10.2.x

projects/igniteui-angular/src/lib/dialog/dialog.component.ts
=> Update dialog dev docs - 11.2.x

projects/igniteui-angular/src/lib/dialog/dialog.component.ts
=> Update dialog dev docs - 12.0.x

projects/igniteui-angular/src/lib/dialog/dialog.component.ts
=> Update dialog dev docs

projects/igniteui-angular/migrations/common/ServerHost.ts, projects/igniteui-angular/migrations/common/UpdateChanges.spec.ts, projects/igniteui-angular/migrations/common/UpdateChanges.ts, projects/igniteui-angular/migrations/common/tsUtils.ts, projects/igniteui-angular/migrations/common/util.ts, projects/igniteui-angular/migrations/update-11_1_0/index.ts
Closes #9572
Ensure TSLS server host always provides absolute paths to file
Ensure all files are assigned to a `ts.tss.ConfiguredProjected` when getting the project service
Ensure `tsconfig.json` has `AngularCompilerOptions.strictTemplates` when trying to use Angular's Ivy LS for template manipulation
=> fix(migration): ensure abs paths in tsLS host, configured project, tsconfig

CHANGELOG.md
=> docs(*): changelog updates

package-lock.json, package.json, projects/igniteui-angular/src/lib/grids/filtering/base/grid-filtering-row.component.ts, projects/igniteui-angular/src/lib/grids/grid-base.directive.ts, src/app/app.component.ts, src/app/app.module.ts, src/app/app.routing.ts, src/app/grid-localization/grid-localization.sample.css, src/app/grid-localization/grid-localization.sample.html, src/app/grid-localization/grid-localization.sample.ts, src/app/routing.ts
=> Update filter row localization when the locale is changed #9590 - 10.2.x

package-lock.json, package.json, projects/igniteui-angular/src/lib/grids/filtering/base/grid-filtering-row.component.ts, projects/igniteui-angular/src/lib/grids/grid-base.directive.ts, src/app/app.component.ts, src/app/app.module.ts, src/app/app.routing.ts, src/app/grid-localization/grid-localization.sample.css, src/app/grid-localization/grid-localization.sample.html, src/app/grid-localization/grid-localization.sample.ts, src/app/routing.ts
=> Update filter row localization when the locale is changed #9590 - 11.1.x

package-lock.json, package.json, projects/igniteui-angular/src/lib/grids/filtering/base/grid-filtering-row.component.ts, projects/igniteui-angular/src/lib/grids/grid-base.directive.ts, src/app/app.component.ts, src/app/app.module.ts, src/app/app.routing.ts, src/app/grid-localization/grid-localization.sample.css, src/app/grid-localization/grid-localization.sample.html, src/app/grid-localization/grid-localization.sample.ts, src/app/routing.ts
=> Update filter row localization when the locale is changed - master

projects/igniteui-angular/src/lib/grids/grid-base.directive.ts
=> fix(grid): adjust overlay hiding logic

CHANGELOG.md, projects/igniteui-angular/src/lib/expansion-panel/README.md, projects/igniteui-angular/src/lib/expansion-panel/expansion-panel.common.ts, projects/igniteui-angular/src/lib/expansion-panel/expansion-panel.component.ts, projects/igniteui-angular/src/lib/expansion-panel/expansion-panel.spec.ts
=> feat(expansion-panel): add contentExpanding/Collapsing event

projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.component.html, projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.spec.ts
=> fix(hgrid): removing faulty isExpanded check from template - 11.1

projects/igniteui-angular/src/lib/core/i18n/grid-resources.ts, projects/igniteui-angular/src/lib/drop-down/drop-down-item.base.ts, projects/igniteui-angular/src/lib/drop-down/drop-down.component.html, projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-conditional-filter.component.html, projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-header.component.html
=> fix(esf): Adding some aria props #9287

projects/igniteui-angular/src/lib/select/select.component.spec.ts, projects/igniteui-angular/src/lib/select/select.component.ts
=> Еmit onSelection event when expected - 10.2.x

projects/igniteui-angular/src/lib/select/select.component.spec.ts, projects/igniteui-angular/src/lib/select/select.component.ts
=> Еmit onSelection event when expected - 11.1.x

projects/igniteui-angular/src/lib/select/select.component.spec.ts, projects/igniteui-angular/src/lib/select/select.component.ts
=> Еmit onSelection event when expected - 12.0.x

projects/igniteui-angular/src/lib/select/select.component.spec.ts, projects/igniteui-angular/src/lib/select/select.component.ts
=>  Еmit onSelection event when expected - master

projects/igniteui-angular/src/lib/icon/icon.service.spec.ts, projects/igniteui-angular/src/lib/icon/icon.service.ts
=> fix(icons): igx-svg-container should be inside the body

projects/igniteui-angular/src/lib/core/styles/components/grid/_grid-theme.scss
=> feat(grid): Add visual difference for non-editable cells in edit row mode.

projects/igniteui-angular/src/lib/core/styles/components/grid/_grid-theme.scss, projects/igniteui-angular/src/lib/core/styles/themes/schemas/light/_grid.scss
=> feat(grid): update add row cell color.

projects/igniteui-angular/src/lib/drop-down/drop-down.component.html, projects/igniteui-angular/src/lib/drop-down/drop-down.component.ts, projects/igniteui-angular/src/lib/select/select-item.component.ts, projects/igniteui-angular/src/lib/select/select-positioning-strategy.ts, projects/igniteui-angular/src/lib/select/select.component.html, projects/igniteui-angular/src/lib/select/select.component.spec.ts, projects/igniteui-angular/src/lib/select/select.component.ts, projects/igniteui-angular/src/lib/services/overlay/overlay.spec.ts
other than SelectPositioningStrategy
Closes #9171
=> Selected item scroll position based on position strategy - 12.0.x

projects/igniteui-angular/src/lib/drop-down/drop-down.component.html, projects/igniteui-angular/src/lib/drop-down/drop-down.component.ts, projects/igniteui-angular/src/lib/select/select-item.component.ts, projects/igniteui-angular/src/lib/select/select-positioning-strategy.ts, projects/igniteui-angular/src/lib/select/select.component.html, projects/igniteui-angular/src/lib/select/select.component.spec.ts, projects/igniteui-angular/src/lib/select/select.component.ts, projects/igniteui-angular/src/lib/services/overlay/overlay.spec.ts
other than SelectPositioningStrategy
Closes ##9171
=> Selected item scroll position based on position strategy - 12.1.x

projects/igniteui-angular/src/lib/services/excel/excel-exporter.ts
Closes [#2672](https://github.com/IgniteUI/igniteui-angular-samples/issues/2672)  
Adding a check is necessary for the samples to work properly in Codesandbox and StackBlitz.
=> Fix JSZip excel export error for codesandbox

projects/igniteui-angular/src/lib/drop-down/drop-down.component.html, projects/igniteui-angular/src/lib/drop-down/drop-down.component.ts, projects/igniteui-angular/src/lib/select/select-item.component.ts, projects/igniteui-angular/src/lib/select/select-navigation.directive.ts, projects/igniteui-angular/src/lib/select/select-positioning-strategy.ts, projects/igniteui-angular/src/lib/select/select.component.html, projects/igniteui-angular/src/lib/select/select.component.spec.ts, projects/igniteui-angular/src/lib/select/select.component.ts, projects/igniteui-angular/src/lib/services/overlay/overlay.spec.ts
=> Selected item scroll position based on position strategy - 10.2.x

projects/igniteui-angular/src/lib/services/excel/excel-exporter.ts
Closes [#2672](https://github.com/IgniteUI/igniteui-angular-samples/issues/2672) 
Adding a check is necessary for the samples to work properly in Codesandbox and StackBlitz.
=> Fix JSZip excel export error for codesandbox 

projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-search.component.ts, projects/igniteui-angular/src/lib/grids/filtering/excel-style/grid.excel-style-filtering.component.ts, projects/igniteui-angular/src/lib/grids/filtering/grid-filtering.service.ts, projects/igniteui-angular/src/lib/grids/grid-navigation.service.ts, projects/igniteui-angular/src/lib/grids/grid/grid-filtering-ui.spec.ts, projects/igniteui-angular/src/lib/grids/headers/grid-header.component.ts
=> Fix Excel-style filtering template throwing an error - 12.0.x

projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-search.component.ts, projects/igniteui-angular/src/lib/grids/filtering/excel-style/grid.excel-style-filtering.component.ts, projects/igniteui-angular/src/lib/grids/filtering/grid-filtering.service.ts, projects/igniteui-angular/src/lib/grids/grid-navigation.service.ts, projects/igniteui-angular/src/lib/grids/grid/grid-filtering-ui.spec.ts, projects/igniteui-angular/src/lib/grids/headers/grid-header.component.ts
=> Fix Excel-style filtering template throwing an error

projects/igniteui-angular/src/lib/slider/slider.component.ts
=> fix(slider): hide lower and upper val setters

projects/igniteui-angular/src/lib/calendar/calendar-base.ts, projects/igniteui-angular/src/lib/calendar/calendar.component.spec.ts
=> fix(calendar): null value

projects/igniteui-angular/src/lib/grids/cell.component.ts
=> fix(grid): range selection does not trigger in firefox

projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.component.html, projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.spec.ts, projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid.component.html, projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid.component.spec.ts, projects/igniteui-angular/src/lib/test-utils/tree-grid-components.spec.ts
=> Ttonev/fix 8194 10.2.x grids
