- projects/igniteui-angular/src/lib/grids/cell.component.ts
> fix(grid): trigger range selection in mozilla

- projects/igniteui-angular/src/lib/dialog/dialog.component.ts
> Update dialog dev docs - 11.1.x

- projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-search.component.html
- projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-search.component.ts
- projects/igniteui-angular/src/lib/grids/grid/grid-filtering-ui.spec.ts
> fix(excel-style-search): allow to insert commas in the input field when column dataType is Number, Currency or Percent

- projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-search.component.html
- projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-search.component.ts
- projects/igniteui-angular/src/lib/grids/grid/grid-filtering-ui.spec.ts
> fix(excel-style-search): allow to insert commas in the input field when column dataType is Number

- projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.component.html
- projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.spec.ts
- projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid.component.html
- projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid.component.spec.ts
- projects/igniteui-angular/src/lib/test-utils/tree-grid-components.spec.ts
> fix(grids): aria-children9418

- projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.component.html
- projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.spec.ts
- projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid.component.html
- projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid.component.spec.ts
- projects/igniteui-angular/src/lib/test-utils/tree-grid-components.spec.ts
> Ttonev/fix 8194 12.x grids

- projects/igniteui-angular/src/lib/tabs/tabs/tab-header.component.ts
> fix(igx-tabs): check for undefined _resizeObserver in ngOnDestroy

- projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid.pipes.ts
> Excluding the ADD transactions in TGrid Hierarchizing pipe - 10.2.x

- projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid.pipes.ts
> Excluding the ADD transactions in TGrid Hierarchizing pipe 11.1.x

- projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid.pipes.ts
> Excluding the ADD transactions in TGrid Hierarchizing pipe - master

- projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid.component.ts
- projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid.pipes.ts
> Excluding the ADD transactions in TGrid Hierarchizing pipe

- projects/igniteui-angular/src/lib/grids/cell.component.ts
> fix(rowadding): removing left-over faulty double click hndlr #9637 - 11.1

- projects/igniteui-angular/src/lib/grids/cell.component.ts
> fix(rowadding): removing left-over faulty double click hndlr #9637 - 12.0

- CHANGELOG.md
- projects/igniteui-angular/src/lib/grids/column-actions/column-actions.component.ts
- projects/igniteui-angular/src/lib/grids/grid-base.directive.ts
- projects/igniteui-angular/src/lib/grids/grid/grid-toolbar.spec.ts
- projects/igniteui-angular/src/lib/grids/toolbar/grid-toolbar-advanced-filtering.component.html
- projects/igniteui-angular/src/lib/grids/toolbar/grid-toolbar-advanced-filtering.component.ts
- projects/igniteui-angular/src/lib/grids/toolbar/grid-toolbar.base.ts
> feat(toolbar): allow passing overlaySettings through every action

- projects/igniteui-angular/src/lib/directives/date-time-editor/date-time-editor.directive.spec.ts
- projects/igniteui-angular/src/lib/directives/date-time-editor/date-time-editor.directive.ts
- projects/igniteui-angular/src/lib/directives/mask/mask.directive.spec.ts
- projects/igniteui-angular/src/lib/directives/mask/mask.directive.ts
> Update IgxMask's placeholder when mask property is updated - 10.2.x

- projects/igniteui-angular/src/lib/directives/date-time-editor/date-time-editor.directive.spec.ts
- projects/igniteui-angular/src/lib/directives/date-time-editor/date-time-editor.directive.ts
- projects/igniteui-angular/src/lib/directives/mask/mask.directive.spec.ts
- projects/igniteui-angular/src/lib/directives/mask/mask.directive.ts
> Update IgxMask's placeholder when mask property is updated - 11.1.x

- projects/igniteui-angular/src/lib/directives/date-time-editor/date-time-editor.directive.spec.ts
- projects/igniteui-angular/src/lib/directives/date-time-editor/date-time-editor.directive.ts
- projects/igniteui-angular/src/lib/directives/mask/mask.directive.spec.ts
- projects/igniteui-angular/src/lib/directives/mask/mask.directive.ts
> Update IgxMask's placeholder when mask property is updated - 12.0.x

- projects/igniteui-angular/src/lib/directives/for-of/for_of.directive.ts
> Allow IgxForOf directive input to be null

- projects/igniteui-angular/src/lib/grids/api.service.ts
- projects/igniteui-angular/src/lib/grids/cell.component.ts
> fix(row-adding): changing how crud value is updated in row add end process - 11.1

- projects/igniteui-angular/src/lib/grids/api.service.ts
- projects/igniteui-angular/src/lib/grids/cell.component.ts
> fix(row-adding): changing how crud value is updated in row add end process - 12.0

- CHANGELOG.md
- projects/igniteui-angular/migrations/update-12_1_0/changes/theme-props.json
- projects/igniteui-angular/src/lib/core/styles/components/action-strip/_action-strip-theme.scss
- projects/igniteui-angular/src/lib/core/styles/themes/schemas/light/_action-strip.scss
> fix(action-strip): icon color override

- CHANGELOG.md
- projects/igniteui-angular/src/lib/grids/cell.component.ts
- projects/igniteui-angular/src/lib/grids/columns/column.component.ts
- projects/igniteui-angular/src/lib/grids/common/column.interface.ts
- projects/igniteui-angular/src/lib/grids/grid/column.spec.ts
- src/app/grid-row-edit/grid-row-edit-sample.component.ts
> feat(grid): expose column input for template context

- projects/igniteui-angular/src/lib/core/utils.ts
- projects/igniteui-angular/src/lib/grids/grid-base.directive.ts
- projects/igniteui-angular/src/lib/grids/selection/selection.service.ts
> Fix scrollbar jump in FireFox when grid needs to autosize (100% height of container that has no size).

- ROADMAP.md
> Milestone 17 Roadmap Update

- projects/igniteui-angular/src/lib/grids/common/row.interface.ts
- projects/igniteui-angular/src/lib/grids/grid-public-row.ts
- projects/igniteui-angular/src/lib/grids/grid/grid.component.spec.ts
- projects/igniteui-angular/src/lib/grids/grid/grid.component.ts
- projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid-summaries.spec.ts
- projects/igniteui-angular/src/lib/test-utils/tree-grid-components.spec.ts
- src/app/grid-row-api/grid-row-api.sample.html
- src/app/grid-row-api/grid-row-api.sample.ts
> Calculate viewIndex properly for each type of row

- projects/igniteui-angular/src/lib/date-picker/date-picker.component.spec.ts
- projects/igniteui-angular/src/lib/date-picker/date-picker.component.ts
Closes https://github.com/IgniteUI/igniteui-angular/issues/9711
> Date picker does not throw if double bound to invalid date 12.0

- projects/igniteui-angular/src/lib/core/styles/components/tabs/_tabs-component.scss
- projects/igniteui-angular/src/lib/core/styles/components/tabs/_tabs-theme.scss
- projects/igniteui-angular/src/lib/tabs/tabs/tabs.component.html
- projects/igniteui-angular/src/lib/tabs/tabs/tabs.component.spec.ts
- projects/igniteui-angular/src/lib/tabs/tabs/tabs.component.ts
- src/app/tabs/tabs.sample.html
> fix(tabs): add third div to wrap the tab headers

- projects/igniteui-angular/src/lib/tabs/tabs/tabs.component.ts
Follow up to #9828
Closes #9765
> Fix 9765 igx tabs patch release

- projects/igniteui-angular/src/lib/grids/grouping/group-by-area.component.html
> fix(grouparea): regressed connector styling

- projects/igniteui-angular/src/lib/grids/grid-base.directive.ts
Throttle resizing on rAF
Closes #9798
> fix(toolbar): Listen to window resize events

- projects/igniteui-angular/src/lib/directives/for-of/for_of.directive.ts
- projects/igniteui-angular/src/lib/grids/grid/grid.groupby.spec.ts
> Reset sync service if column collection has changes. 

- projects/igniteui-angular/src/lib/date-range-picker/date-range-picker.component.html
- projects/igniteui-angular/src/lib/date-range-picker/date-range-picker.component.spec.ts
- projects/igniteui-angular/src/lib/date-range-picker/date-range-picker.component.ts
Closes https://github.com/IgniteUI/igniteui-angular/issues/9776
> Update disabled with CD strategy OnPush - 12.0.x

- projects/igniteui-angular/src/lib/directives/for-of/for_of.directive.ts
- projects/igniteui-angular/src/lib/grids/grid/grid.groupby.spec.ts
> Reset sync service if column collection has changes.

- projects/igniteui-angular/src/lib/combo/combo.component.ts
Closes https://github.com/IgniteUI/igniteui-angular/issues/9815
> Add component description to IgxCombo

- projects/igniteui-angular/src/lib/grids/common/enums.ts
- projects/igniteui-angular/src/lib/grids/grid-public-row.ts
- projects/igniteui-angular/src/lib/grids/grid/grid.component.ts
- projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid.component.ts
> fix(grid): Resolve circular dependencies #9849

- projects/igniteui-angular-i18n/src/i18n/BG/grid-resources.ts
- projects/igniteui-angular-i18n/src/i18n/CS/grid-resources.ts
- projects/igniteui-angular-i18n/src/i18n/DA/grid-resources.ts
- projects/igniteui-angular-i18n/src/i18n/ES/grid-resources.ts
- projects/igniteui-angular-i18n/src/i18n/HU/grid-resources.ts
- projects/igniteui-angular-i18n/src/i18n/IT/grid-resources.ts
- projects/igniteui-angular-i18n/src/i18n/JA/grid-resources.ts
- projects/igniteui-angular-i18n/src/i18n/KO/grid-resources.ts
- projects/igniteui-angular-i18n/src/i18n/NL/grid-resources.ts
- projects/igniteui-angular-i18n/src/i18n/PL/grid-resources.ts
- projects/igniteui-angular-i18n/src/i18n/PT/grid-resources.ts
- projects/igniteui-angular-i18n/src/i18n/RO/grid-resources.ts
- projects/igniteui-angular-i18n/src/i18n/SV/grid-resources.ts
- projects/igniteui-angular-i18n/src/i18n/TR/grid-resources.ts
- projects/igniteui-angular-i18n/src/i18n/ZH-HANS/grid-resources.ts
- projects/igniteui-angular-i18n/src/i18n/ZH-HANT/grid-resources.ts
- projects/igniteui-angular/src/lib/core/i18n/grid-resources.ts
- projects/igniteui-angular/src/lib/grids/grid/grid.component.html
- projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.component.html
- projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid.component.html
* Update for grid, hierarchical grid, and tree grid
Closes #9830
> Add i18n for row edit done and cancel buttons - 10.2.x

- projects/igniteui-angular-i18n/src/i18n/BG/grid-resources.ts
- projects/igniteui-angular-i18n/src/i18n/CS/grid-resources.ts
- projects/igniteui-angular-i18n/src/i18n/DA/grid-resources.ts
- projects/igniteui-angular-i18n/src/i18n/DE/grid-resources.ts
- projects/igniteui-angular-i18n/src/i18n/ES/grid-resources.ts
- projects/igniteui-angular-i18n/src/i18n/FR/grid-resources.ts
- projects/igniteui-angular-i18n/src/i18n/HU/grid-resources.ts
- projects/igniteui-angular-i18n/src/i18n/IT/grid-resources.ts
- projects/igniteui-angular-i18n/src/i18n/JA/grid-resources.ts
- projects/igniteui-angular-i18n/src/i18n/KO/grid-resources.ts
- projects/igniteui-angular-i18n/src/i18n/NL/grid-resources.ts
- projects/igniteui-angular-i18n/src/i18n/PL/grid-resources.ts
- projects/igniteui-angular-i18n/src/i18n/PT/grid-resources.ts
- projects/igniteui-angular-i18n/src/i18n/RO/grid-resources.ts
- projects/igniteui-angular-i18n/src/i18n/SV/grid-resources.ts
- projects/igniteui-angular-i18n/src/i18n/TR/grid-resources.ts
- projects/igniteui-angular-i18n/src/i18n/ZH-HANS/grid-resources.ts
- projects/igniteui-angular-i18n/src/i18n/ZH-HANT/grid-resources.ts
- projects/igniteui-angular/src/lib/core/i18n/grid-resources.ts
- projects/igniteui-angular/src/lib/grids/grid/grid.component.html
- projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.component.html
- projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid.component.html
* Update for grid, hierarchical grid, and tree grid
Closes #9830
> Add i18n for row edit done and cancel buttons - 11.1.x

- projects/igniteui-angular-i18n/src/i18n/BG/grid-resources.ts
- projects/igniteui-angular-i18n/src/i18n/CS/grid-resources.ts
- projects/igniteui-angular-i18n/src/i18n/DA/grid-resources.ts
- projects/igniteui-angular-i18n/src/i18n/DE/grid-resources.ts
- projects/igniteui-angular-i18n/src/i18n/ES/grid-resources.ts
- projects/igniteui-angular-i18n/src/i18n/FR/grid-resources.ts
- projects/igniteui-angular-i18n/src/i18n/HU/grid-resources.ts
- projects/igniteui-angular-i18n/src/i18n/IT/grid-resources.ts
- projects/igniteui-angular-i18n/src/i18n/JA/grid-resources.ts
- projects/igniteui-angular-i18n/src/i18n/KO/grid-resources.ts
- projects/igniteui-angular-i18n/src/i18n/NL/grid-resources.ts
- projects/igniteui-angular-i18n/src/i18n/PL/grid-resources.ts
- projects/igniteui-angular-i18n/src/i18n/PT/grid-resources.ts
- projects/igniteui-angular-i18n/src/i18n/RO/grid-resources.ts
- projects/igniteui-angular-i18n/src/i18n/SV/grid-resources.ts
- projects/igniteui-angular-i18n/src/i18n/TR/grid-resources.ts
- projects/igniteui-angular-i18n/src/i18n/ZH-HANS/grid-resources.ts
- projects/igniteui-angular-i18n/src/i18n/ZH-HANT/grid-resources.ts
- projects/igniteui-angular/src/lib/core/i18n/grid-resources.ts
- projects/igniteui-angular/src/lib/grids/grid/grid.component.html
- projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.component.html
- projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid.component.html
* Update for grid, hierarchical grid, and tree grid
Closes #9830
> Add i18n for row edit done and cancel buttons - 12.0.x

- projects/igniteui-angular-i18n/src/i18n/DE/grid-resources.ts
> fix(i18n): Fix German resource string - 11.1.x

- projects/igniteui-angular-i18n/src/i18n/DE/grid-resources.ts
> fix(i18n): Fix German resource string - 12.0.x

- projects/igniteui-angular-i18n/src/i18n/DE/grid-resources.ts
> fix(i18n): Fix German resource string - master

- projects/igniteui-angular/src/lib/splitter/splitter.component.ts
> fix(*): Add a min/max size splitter check when ending movement

- package-lock.json
- package.json
> fix(typedoc): Update to version 0.21.0

- projects/igniteui-angular/src/lib/core/styles/components/chip/_chip-theme.scss
> fix(chip-theme): add missing selectors to component $selector list.

- projects/igniteui-angular/src/lib/core/styles/base/utilities/_functions.scss
- projects/igniteui-angular/src/lib/core/styles/components/calendar/_calendar-theme.scss
- projects/igniteui-angular/src/lib/core/styles/components/checkbox/_checkbox-theme.scss
- projects/igniteui-angular/src/lib/core/styles/components/grid/_grid-theme.scss
- projects/igniteui-angular/src/lib/core/styles/components/radio/_radio-theme.scss
- projects/igniteui-angular/src/lib/core/styles/components/slider/_slider-theme.scss
- projects/igniteui-angular/src/lib/core/styles/components/switch/_switch-theme.scss
> refactor(themes): add optional math.div

- projects/igniteui-angular/migrations/common/tsUtils.ts
> Fix migrations for chained members

- projects/igniteui-angular/migrations/update-12_1_0/index.ts
- projects/igniteui-angular/src/lib/directives/date-time-editor/date-time-editor.directive.spec.ts
- projects/igniteui-angular/src/lib/time-picker/time-picker.component.spec.ts
> chore(*): fix some ESLint warnings

- projects/igniteui-angular/src/lib/grids/grid-base.directive.ts
- projects/igniteui-angular/src/lib/grids/grid/grid.component.html
- projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.component.html
- projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid.component.html
> fix(*): Use localization strings for snackbar label and action text

- projects/igniteui-angular/migrations/update-12_0_0/changes/members.json
> fix(migrations): fix IgxDateRangePickerComponent migrations #9904

- projects/igniteui-angular/migrations/update-12_1_0/changes/classes.json
- projects/igniteui-angular/migrations/update-12_1_0/index.spec.ts
> chore(migrations): add event renaming for combo and autocomplete

- projects/igniteui-angular/migrations/update-12_1_0/index.spec.ts
- projects/igniteui-angular/migrations/update-12_1_0/index.ts
Related #9672 
This PR contains migrations for the deprecations introduced in https://github.com/IgniteUI/igniteui-angular/pull/9836
> feat(grids): add migrations for deprecated IgxGridTransaction token

- projects/igniteui-angular/src/lib/grids/README.md
- projects/igniteui-angular/src/lib/grids/common/cell.interface.ts
- projects/igniteui-angular/src/lib/grids/common/crud.service.ts
- projects/igniteui-angular/src/lib/grids/grid-public-cell.ts
- projects/igniteui-angular/src/lib/grids/grid/grid-cell-editing.spec.ts
- projects/igniteui-angular/src/lib/grids/grid/grid-row-editing.spec.ts
- projects/igniteui-angular/src/lib/grids/grid/grid.nested.props.spec.ts
- projects/igniteui-angular/src/lib/grids/grid/grid.pinning.spec.ts
- projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.navigation.spec.ts
- projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid-selection.spec.ts
- src/app/grid-cell-api/grid-cell-api.sample.ts
- src/app/grid-cellEditing/grid-cellEditing.component.html
- src/app/grid-row-edit/grid-row-edit-sample.component.html
- src/app/grid-row-pinning/grid-row-pinning.sample.html
> fix(grid): change cellID to id in CellType interface

- projects/igniteui-angular/src/lib/date-range-picker/date-range-picker.module.ts
> IgxDateRangePicker exports IgxPickersCommonModule

- projects/igniteui-angular/src/lib/date-range-picker/date-range-picker.module.ts
> IgxDateRangePicker exports IgxPickersCommonModule - 12.0.x

- projects/igniteui-angular/src/lib/checkbox/checkbox.component.ts
- projects/igniteui-angular/src/lib/grids/cell.component.ts
- projects/igniteui-angular/src/lib/grids/grid-public-cell.ts
- projects/igniteui-angular/src/lib/grids/grid/grid-keyBoardNav.spec.ts
- projects/igniteui-angular/src/lib/grids/grid/grid-row-selection.spec.ts
- projects/igniteui-angular/src/lib/grids/grid/grid.component.ts
- projects/igniteui-angular/src/lib/grids/grid/grid.groupby.spec.ts
- projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid-selection.spec.ts
- projects/igniteui-angular/src/lib/services/overlay/overlay.spec.ts
- projects/igniteui-angular/src/lib/test-utils/grid-samples.spec.ts
- projects/igniteui-angular/src/lib/test-utils/tree-grid-components.spec.ts
> Type checkbox click event to MouseEvent | Pointer event

- projects/igniteui-angular/src/lib/grids/cell.component.ts
`cell` property is now lazy-evaluated
> perf(grid): Cell template context

- projects/igniteui-angular/package.json
> chore(schematics): update with 12.1.810

- projects/igniteui-angular/src/lib/grids/cell.component.ts
- projects/igniteui-angular/src/lib/grids/grid/cell.spec.ts
- projects/igniteui-angular/src/lib/test-utils/grid-samples.spec.ts
> Use formatted value in cell tooltip 

- projects/igniteui-angular/src/lib/grids/cell.component.ts
- projects/igniteui-angular/src/lib/grids/grid/cell.spec.ts
- projects/igniteui-angular/src/lib/test-utils/grid-samples.spec.ts
> Use formatted value in cell tooltip --- 11.1.x

- projects/igniteui-angular/src/lib/grids/cell.component.ts
- projects/igniteui-angular/src/lib/grids/grid/cell.spec.ts
- projects/igniteui-angular/src/lib/test-utils/grid-samples.spec.ts
> Use formatted value in cell tooltip -- 10.2.x

- projects/igniteui-angular/src/lib/directives/radio/radio-group.directive.ts
> refactor(radio-group): deprecate disabled and labelPosition

- projects/igniteui-angular/src/lib/grids/grid-base.directive.ts
> fix(hierarchical-grid): copy selected cell properly #9782

- projects/igniteui-angular/migrations/common/UpdateChanges.ts
> fix(migrations): support setup with tsconfig not in project root #9927

- CHANGELOG.md
- projects/igniteui-angular/src/lib/grids/cell.component.html
- projects/igniteui-angular/src/lib/grids/cell.component.ts
- projects/igniteui-angular/src/lib/grids/columns/column.component.ts
- projects/igniteui-angular/src/lib/grids/common/pipes.ts
- projects/igniteui-angular/src/lib/grids/filtering/advanced-filtering/advanced-filtering-dialog.component.html
- projects/igniteui-angular/src/lib/grids/filtering/base/grid-filtering-row.component.html
- projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-date-expression.component.html
- projects/igniteui-angular/src/lib/grids/filtering/excel-style/grid.excel-style-filtering.component.ts
- projects/igniteui-angular/src/lib/grids/filtering/grid-filtering.service.ts
- projects/igniteui-angular/src/lib/grids/grid-base.directive.ts
- projects/igniteui-angular/src/lib/grids/grid/column.spec.ts
- projects/igniteui-angular/src/lib/grids/grid/expandable-cell.component.html
- projects/igniteui-angular/src/lib/grids/tree-grid/tree-cell.component.html
- projects/igniteui-angular/src/lib/test-utils/grid-samples.spec.ts
> feat(grid): Provide row data as argument to column formatter

- projects/igniteui-angular/src/lib/checkbox/checkbox.component.ts
- projects/igniteui-angular/src/lib/switch/switch.component.ts
> fix(checkbox, switch): implement setDisabledState

- projects/igniteui-angular/src/lib/directives/input/input.directive.spec.ts
- projects/igniteui-angular/src/lib/directives/input/input.directive.ts
- projects/igniteui-angular/src/lib/input-group/input-group.component.spec.ts
> Update styles and asterisk on dynamically added/removed validator - 10.2.x

- projects/igniteui-angular/src/lib/directives/input/input.directive.spec.ts
- projects/igniteui-angular/src/lib/directives/input/input.directive.ts
- projects/igniteui-angular/src/lib/input-group/input-group.component.spec.ts
> Update styles and asterisk on dynamically added/removed validator - 11.1.x

- projects/igniteui-angular/src/lib/directives/input/input.directive.spec.ts
- projects/igniteui-angular/src/lib/directives/input/input.directive.ts
- projects/igniteui-angular/src/lib/grids/filtering/advanced-filtering/advanced-filtering-dialog.component.html
> Setting input disabled state in reactive form 11.1.x

- projects/igniteui-angular/src/lib/directives/text-highlight/text-highlight.directive.spec.ts
- projects/igniteui-angular/src/lib/directives/text-highlight/text-highlight.directive.ts
> fix(highlight): skip active highlight if index is -1

- projects/igniteui-angular/src/lib/grids/grid-base.directive.ts
- projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.component.html
- projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.component.ts
- projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.spec.ts
> Enable row editing overlay customization for child-level records - 11.1

- projects/igniteui-angular/src/lib/directives/input/input.directive.spec.ts
> Update input validator-test-10.2.x

- projects/igniteui-angular/src/lib/directives/input/input.directive.spec.ts
> Update input validator-test-11.1.x

- projects/igniteui-angular/src/lib/directives/input/input.directive.spec.ts
> Update input validator-test-12.1.x

- projects/igniteui-angular/src/lib/directives/radio/radio-group.directive.ts
> fix(radio-group): modify selection logic

- .eslintrc.json
- projects/igniteui-angular/src/lib/data-operations/filtering-expressions-tree.ts
- projects/igniteui-angular/src/lib/directives/button/button.directive.spec.ts
- projects/igniteui-angular/src/lib/directives/divider/divider.directive.ts
- projects/igniteui-angular/src/lib/directives/divider/divider.spec.ts
- projects/igniteui-angular/src/lib/directives/filter/filter.directive.spec.ts
- projects/igniteui-angular/src/lib/directives/focus/focus.directive.spec.ts
- projects/igniteui-angular/src/lib/directives/radio/radio-group.directive.spec.ts
- projects/igniteui-angular/src/lib/directives/text-selection/text-selection.directive.ts
- projects/igniteui-angular/src/lib/grids/grid-mrl-navigation.service.ts
- projects/igniteui-angular/src/lib/grids/grid-navigation.service.ts
- projects/igniteui-angular/src/lib/grids/grid.common.ts
- projects/igniteui-angular/src/lib/grids/grid/grid-toolbar.spec.ts
- projects/igniteui-angular/src/lib/grids/grid/row-drag.directive.spec.ts
- projects/igniteui-angular/src/lib/grids/headers/sorting-index.pipe.ts
- projects/igniteui-angular/src/lib/grids/row.directive.ts
- src/app/grid-cell-api/grid-cell-api.sample.ts
- src/app/grid-row-api/grid-row-api.sample.html
- src/app/grid-row-api/grid-row-api.sample.ts
- src/app/tree-grid-groupby/tree-grid-groupby.sample.html
- src/app/tree-grid-groupby/tree-grid-groupby.sample.ts
- src/app/tree/tree.sample.html
- src/app/tree/tree.sample.ts
> chore(*): fixing lint with accs modifiers

- projects/igniteui-angular/src/lib/date-picker/date-picker.component.spec.ts
- projects/igniteui-angular/src/lib/date-picker/date-picker.component.ts
Closes https://github.com/IgniteUI/igniteui-angular/issues/10057
> Update picker's input value after content is checked

- projects/igniteui-angular/src/lib/grids/filtering/base/grid-filtering-row.component.ts
> fix(grid): Boolean column filter fix #10048

- README.md
> docs(readme): Update readme with marketing

- projects/igniteui-angular/src/lib/grids/filtering/base/grid-filtering-row.component.ts
> fix(grid): Focus input inside rAF #10048

- projects/igniteui-angular/src/lib/grids/grid/groupby-row.component.ts
- src/app/grid-groupby/grid-groupby.sample.html
- src/app/grid-groupby/grid-groupby.sample.ts
> perf(grid): reduce delay on larger group row selection

- projects/igniteui-angular/src/lib/grids/grid-base.directive.ts
> Expose columnsCollection property --11.1.x

- projects/igniteui-angular/src/lib/grids/grid-base.directive.ts
> Expose columnsCollection property -- master

- projects/igniteui-angular/src/lib/grids/grid-base.directive.ts
> Expose columnsCollection property --12.1.x

- ROADMAP.md
> chore(*): Roadmap update M18 10Sep21

- projects/igniteui-angular/src/lib/grids/grid/grid-cell-selection.spec.ts
> Fix failing tests due change in error msg

- projects/igniteui-angular/src/lib/grids/grid/grid-cell-selection.spec.ts
> test(*): Fix failing tests due change in error msg

- projects/igniteui-angular/src/lib/directives/drag-drop/drag-drop.directive.ts
> fix(grid): Add check for shadowRoot

- projects/igniteui-angular/src/lib/core/styles/components/grid/_grid-theme.scss
- projects/igniteui-angular/src/lib/grids/common/pipes.ts
- projects/igniteui-angular/src/lib/grids/grid-base.directive.ts
- projects/igniteui-angular/src/lib/grids/grid/grid.component.ts
- projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-grid.component.html
- projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-grid.component.ts
- projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-grid.interface.ts
- projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-grid.module.ts
- projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-grid.pipes.ts
- projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-header-row.component.html
- projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-header-row.component.ts
- projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-row.component.html
- projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-row.component.ts
- projects/igniteui-angular/src/lib/grids/pivot-grid/public_api.ts
- projects/igniteui-angular/src/public_api.ts
- src/app/app.component.ts
- src/app/app.module.ts
- src/app/app.routing.ts
- src/app/pivot-grid/pivot-grid.sample.css
- src/app/pivot-grid/pivot-grid.sample.html
- src/app/pivot-grid/pivot-grid.sample.ts
- src/app/routing.ts
Initial Pivot Grid Skeleton (with no pipes and no features)
> Pivot grid skeleton

- projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-clear-filters.component.html
- projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-conditional-filter.component.html
- projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-hiding.component.html
- projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-pinning.component.html
- projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-selecting.component.html
> fix(esf): added missing aria related attributes - 12.1.x

- projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-clear-filters.component.html
- projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-conditional-filter.component.html
- projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-hiding.component.html
- projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-pinning.component.html
- projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-selecting.component.html
> fix(esf): added missing aria related attributes - 11.1.x

- projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-clear-filters.component.html
- projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-conditional-filter.component.html
- projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-hiding.component.html
- projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-pinning.component.html
- projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-selecting.component.html
> fix(esf): added missing aria related attributes - 10.2.x

- projects/igniteui-angular/src/lib/core/styles/components/_common/_igx-display-container.scss
> fix(for-of): inheriting flex-flow for display container #10037

- src/app/app.module.ts
- src/app/drag-drop/drag-drop.sample.html
- src/app/drag-drop/drag-drop.sample.ts
- src/app/drag-drop/shadow-dom-grid/shadow-grid-sample.html
- src/app/drag-drop/shadow-dom-grid/shadow-grid-sample.scss
- src/app/drag-drop/shadow-dom-grid/shadow-grid-sample.ts
> chore(dev-demos): Add drag and drop sample overlapping shadow dom

- projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-grid.component.ts
- projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-header-row.component.html
- projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-header-row.component.ts
- projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-row.component.html
- projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-row.component.ts
- src/app/pivot-grid/pivot-grid.sample.html
- src/app/pivot-grid/pivot-grid.sample.ts
> Add support for members defined via custom function for rows/columns.

- ROADMAP.md
> chore(*): update or roadamap for m18 17-sep-21

- projects/igniteui-angular/src/lib/tabs/tabs.directive.ts
> fix(tabs): remove role with invalid value #10122 - 12.1.x

- projects/igniteui-angular/src/lib/tabs/tabs.directive.ts
> fix(tabs): remove role with invalid value #10122 - master

- projects/igniteui-angular/src/lib/core/utils.ts
- projects/igniteui-angular/src/lib/grids/columns/column.component.ts
> fix(grid): Check summary reference

- projects/igniteui-angular/src/lib/date-picker/date-picker.component.spec.ts
- projects/igniteui-angular/src/lib/date-picker/date-picker.component.ts
> IgxDatePicker - apply asterisk when reactive form required validator is set - v.12.1.x

- projects/igniteui-angular/src/lib/date-picker/date-picker.component.spec.ts
- projects/igniteui-angular/src/lib/date-picker/date-picker.component.ts
> IgxDatePicker - apply asterix when reactive form required validator is set

- CHANGELOG.md
> chore(*): fixing changelog after wrong merge

- ROADMAP.md
> chore(*): update-roadmap-m18-27sep21

- projects/igniteui-angular/src/lib/data-operations/data-util.spec.ts
- projects/igniteui-angular/src/lib/grids/cell.component.html
- projects/igniteui-angular/src/lib/grids/grid/column.spec.ts
- projects/igniteui-angular/src/lib/grids/grid/expandable-cell.component.html
- projects/igniteui-angular/src/lib/grids/tree-grid/tree-cell.component.html
- projects/igniteui-angular/src/lib/test-utils/grid-samples.spec.ts
- projects/igniteui-angular/src/lib/test-utils/sample-test-data.spec.ts
- projects/igniteui-angular/src/lib/test-utils/template-strings.spec.ts
- src/app/grid-formatting/grid-formatting.component.html
> fix(grid): use formattter function for boolean columns-12.1.x #8978

- projects/igniteui-angular/src/lib/core/utils.ts
- projects/igniteui-angular/src/lib/grids/columns/column.component.ts
> fix(grid): Check summary reference #10189

- projects/igniteui-angular/src/lib/data-operations/data-util.spec.ts
- projects/igniteui-angular/src/lib/grids/cell.component.html
- projects/igniteui-angular/src/lib/grids/grid/column.spec.ts
- projects/igniteui-angular/src/lib/grids/grid/expandable-cell.component.html
- projects/igniteui-angular/src/lib/grids/tree-grid/tree-cell.component.html
- projects/igniteui-angular/src/lib/test-utils/grid-samples.spec.ts
- projects/igniteui-angular/src/lib/test-utils/sample-test-data.spec.ts
- projects/igniteui-angular/src/lib/test-utils/template-strings.spec.ts
> fix(grid): use formattter function for boolean columns-10.2.x #8978

- projects/igniteui-angular/src/lib/data-operations/data-util.spec.ts
- projects/igniteui-angular/src/lib/grids/cell.component.html
- projects/igniteui-angular/src/lib/grids/grid/column.spec.ts
- projects/igniteui-angular/src/lib/grids/grid/expandable-cell.component.html
- projects/igniteui-angular/src/lib/grids/tree-grid/tree-cell.component.html
- projects/igniteui-angular/src/lib/test-utils/grid-samples.spec.ts
- projects/igniteui-angular/src/lib/test-utils/sample-test-data.spec.ts
- projects/igniteui-angular/src/lib/test-utils/template-strings.spec.ts
> fix(grid): use formattter function for boolean columns-11.1.x #8978

- projects/igniteui-angular/src/lib/data-operations/filtering-strategy.ts
- projects/igniteui-angular/src/lib/grids/grid/grid-filtering-advanced.spec.ts
- projects/igniteui-angular/src/lib/grids/grid/grid-filtering-ui.spec.ts
> fix(filtering): add row data param to formatter - 12.1.x

- projects/igniteui-angular/src/lib/data-operations/filtering-strategy.ts
- projects/igniteui-angular/src/lib/grids/grid/grid-filtering-advanced.spec.ts
- projects/igniteui-angular/src/lib/grids/grid/grid-filtering-ui.spec.ts
> fix(filtering): add row data param to formatter - master

- projects/igniteui-angular/package.json
> chore(schematics): update ignite ui schematics

- projects/igniteui-angular/src/lib/core/styles/components/navbar/_navbar-theme.scss
> Use flex display for navbar title content

- projects/igniteui-angular/src/lib/grids/common/crud.service.ts
> fix(row-add): resolve targetting correct unpinned row #10117 - master

- projects/igniteui-angular/src/lib/grids/common/crud.service.ts
> fix(row-add): resolve targetting correct unpinned row #10117 - 12.1

- CHANGELOG.md
> docs(changelog): combining post 12.1 feats into 12.2

- projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-grid.component.html
- projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-grid.component.ts
- projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-grid.pipes.spec.ts
- projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-grid.pipes.ts
- projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-row.component.html
- projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-row.component.ts
- projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-util.ts
> Handle expansion states for pivot rows.

- projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-search.component.ts
(cherry picked from commit 5cdedd3a3797f0ec682c2d3d724616700dcb9b1b)
Closes #10355
> fix(ESF): Return a numeric value for containerSize

- projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-grid.pipes.spec.ts
- projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-grid.spec.ts
- projects/igniteui-angular/src/lib/test-utils/pivot-grid-samples.spec.ts
> test(pivot): clean the state of the pivot tests

- projects/igniteui-angular/src/lib/stepper/stepper.component.ts
> Fix wrong api comment for activeStepChanging event

- projects/igniteui-angular-i18n/src/i18n/BG/action-strip-resources.ts
- projects/igniteui-angular-i18n/src/i18n/CS/action-strip-resources.ts
- projects/igniteui-angular-i18n/src/i18n/DA/action-strip-resources.ts
- projects/igniteui-angular-i18n/src/i18n/DE/action-strip-resources.ts
- projects/igniteui-angular-i18n/src/i18n/ES/action-strip-resources.ts
- projects/igniteui-angular-i18n/src/i18n/FR/action-strip-resources.ts
- projects/igniteui-angular-i18n/src/i18n/HU/action-strip-resources.ts
- projects/igniteui-angular-i18n/src/i18n/IT/action-strip-resources.ts
- projects/igniteui-angular-i18n/src/i18n/JA/action-strip-resources.ts
- projects/igniteui-angular-i18n/src/i18n/KO/action-strip-resources.ts
- projects/igniteui-angular-i18n/src/i18n/NB/action-strip-resources.ts
- projects/igniteui-angular-i18n/src/i18n/NL/action-strip-resources.ts
- projects/igniteui-angular-i18n/src/i18n/PL/action-strip-resources.ts
- projects/igniteui-angular-i18n/src/i18n/PT/action-strip-resources.ts
- projects/igniteui-angular-i18n/src/i18n/RO/action-strip-resources.ts
- projects/igniteui-angular-i18n/src/i18n/SV/action-strip-resources.ts
- projects/igniteui-angular-i18n/src/i18n/TR/action-strip-resources.ts
- projects/igniteui-angular-i18n/src/i18n/ZH-HANS/action-strip-resources.ts
- projects/igniteui-angular-i18n/src/i18n/ZH-HANT/action-strip-resources.ts
- projects/igniteui-angular/src/lib/action-strip/action-strip.component.html
- projects/igniteui-angular/src/lib/action-strip/action-strip.component.ts
- projects/igniteui-angular/src/lib/action-strip/grid-actions/grid-action-button.component.html
- projects/igniteui-angular/src/lib/action-strip/grid-actions/grid-editing-actions.component.ts
- projects/igniteui-angular/src/lib/action-strip/grid-actions/grid-pinning-actions.component.ts
- projects/igniteui-angular/src/lib/core/i18n/action-strip-resources.ts
- projects/igniteui-angular/src/lib/core/i18n/resources.ts
- projects/igniteui-angular/src/public_api.ts
> feat(action-strip): titles and localization for buttons in action strip - 12.2

- projects/igniteui-angular/src/lib/directives/scroll-inertia/scroll_inertia.directive.spec.ts
- projects/igniteui-angular/src/lib/directives/scroll-inertia/scroll_inertia.directive.ts
> feat(scroll): Remove support for IE11 and old Edge from scroll inertia directive.

- projects/igniteui-angular/package.json
> chore(schematics): update to schematics beta

- projects/igniteui-angular/src/lib/grids/grid-base.directive.ts
- projects/igniteui-angular/src/lib/grids/grid/grid-clipboard.spec.ts
> feat(IgxGridBaseDirective):  Remove newline character when single cell value is copied

- ROADMAP.md
> chore(*): roadmap-update-m19-08nov21

- CHANGELOG.md
- README.md
- projects/igniteui-angular/migrations/update-13_0_0/changes/members.json
- projects/igniteui-angular/migrations/update-13_0_0/index.spec.ts
- projects/igniteui-angular/src/lib/combo/README.md
- projects/igniteui-angular/src/lib/combo/combo-dropdown.component.ts
- projects/igniteui-angular/src/lib/combo/combo-item.component.html
- projects/igniteui-angular/src/lib/combo/combo-item.component.ts
- projects/igniteui-angular/src/lib/combo/combo.api.ts
- projects/igniteui-angular/src/lib/combo/combo.common.ts
- projects/igniteui-angular/src/lib/combo/combo.component.html
- projects/igniteui-angular/src/lib/combo/combo.component.spec.ts
- projects/igniteui-angular/src/lib/combo/combo.component.ts
- projects/igniteui-angular/src/lib/combo/combo.pipes.ts
- projects/igniteui-angular/src/lib/grids/grid/grid.nested.props.spec.ts
- projects/igniteui-angular/src/lib/simple-combo/README.md
- projects/igniteui-angular/src/lib/simple-combo/public_api.ts
- projects/igniteui-angular/src/lib/simple-combo/simple-combo.component.html
- projects/igniteui-angular/src/lib/simple-combo/simple-combo.component.spec.ts
- projects/igniteui-angular/src/lib/simple-combo/simple-combo.component.ts
- projects/igniteui-angular/src/public_api.ts
- src/app/shared/shared.module.ts
> Single selection combo implementation

- CHANGELOG.md
- README.md
- projects/igniteui-angular/migrations/update-13_0_0/changes/members.json
- projects/igniteui-angular/src/lib/combo/README.md
- projects/igniteui-angular/src/lib/combo/combo-dropdown.component.ts
- projects/igniteui-angular/src/lib/combo/combo-item.component.html
- projects/igniteui-angular/src/lib/combo/combo-item.component.ts
- projects/igniteui-angular/src/lib/combo/combo.api.ts
- projects/igniteui-angular/src/lib/combo/combo.common.ts
- projects/igniteui-angular/src/lib/combo/combo.component.html
- projects/igniteui-angular/src/lib/combo/combo.component.spec.ts
- projects/igniteui-angular/src/lib/combo/combo.component.ts
- projects/igniteui-angular/src/lib/combo/combo.pipes.ts
- projects/igniteui-angular/src/lib/grids/grid/grid.nested.props.spec.ts
- projects/igniteui-angular/src/lib/simple-combo/README.md
- projects/igniteui-angular/src/lib/simple-combo/public_api.ts
- projects/igniteui-angular/src/lib/simple-combo/simple-combo.component.html
- projects/igniteui-angular/src/lib/simple-combo/simple-combo.component.spec.ts
- projects/igniteui-angular/src/lib/simple-combo/simple-combo.component.ts
- projects/igniteui-angular/src/public_api.ts
- src/app/shared/shared.module.ts
> Single selection combo implementation - 12.3

- projects/igniteui-angular/src/lib/grids/headers/grid-header-row.component.html
> V dyulgerov/fix aria activedescendant 12.2.x

- projects/igniteui-angular/src/lib/grids/common/crud.service.ts
> fix(grid): add row on top if not specified

- projects/igniteui-angular/src/lib/data-operations/pivot-strategy.ts
- projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-util.ts
> Fix issues with merging to same level.

- projects/igniteui-angular/src/lib/combo/combo.common.ts
- projects/igniteui-angular/src/lib/combo/combo.component.ts
- projects/igniteui-angular/src/lib/simple-combo/simple-combo.component.html
- projects/igniteui-angular/src/lib/simple-combo/simple-combo.component.spec.ts
- projects/igniteui-angular/src/lib/simple-combo/simple-combo.component.ts
Cherrypicked from https://github.com/IgniteUI/igniteui-angular/pull/10467
> Clear selection on blur when accessing non-existent item - 12.3

- projects/igniteui-angular/src/lib/combo/combo.common.ts
- projects/igniteui-angular/src/lib/combo/combo.component.ts
- projects/igniteui-angular/src/lib/simple-combo/simple-combo.component.html
- projects/igniteui-angular/src/lib/simple-combo/simple-combo.component.spec.ts
- projects/igniteui-angular/src/lib/simple-combo/simple-combo.component.ts
>  Clear selection on blur when accessing non-existent item

- projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid-selection.spec.ts
- projects/igniteui-angular/src/lib/test-utils/sample-test-data.spec.ts
- projects/igniteui-angular/src/lib/test-utils/tree-grid-components.spec.ts
> Tree-Grid with flat data and cascade selection tests

- projects/igniteui-angular/src/lib/simple-combo/simple-combo.component.ts
> Combo clean up - 12.3

- projects/igniteui-angular/src/lib/navigation-drawer/navigation-drawer.component.spec.ts
- projects/igniteui-angular/src/lib/services/overlay/overlay.ts
> test(nav-drawer): fix failing test

- projects/igniteui-angular/src/lib/data-operations/sorting-strategy.ts
> fix(grid): Groupby stack error on a single group

- projects/igniteui-angular/src/lib/simple-combo/simple-combo.component.spec.ts
- projects/igniteui-angular/src/lib/simple-combo/simple-combo.component.ts
> Handle clear w/o valueKey

- projects/igniteui-angular/src/lib/simple-combo/simple-combo.component.spec.ts
- projects/igniteui-angular/src/lib/simple-combo/simple-combo.component.ts
Related to https://github.com/IgniteUI/igniteui-angular/pull/10500
> Handle clear w/o valueKey - 12.3

- CHANGELOG.md
- projects/igniteui-angular/migrations/update-13_0_0/changes/members.json
- projects/igniteui-angular/migrations/update-13_0_0/changes/outputs.json
- projects/igniteui-angular/src/lib/grids/README.md
- projects/igniteui-angular/src/lib/grids/common/events.ts
- projects/igniteui-angular/src/lib/grids/grid-base.directive.ts
- projects/igniteui-angular/src/lib/grids/grid/column-selection.spec.ts
- projects/igniteui-angular/src/lib/grids/grid/grid-filtering-ui.spec.ts
- projects/igniteui-angular/src/lib/grids/grid/grid-keyBoardNav-headers.spec.ts
- projects/igniteui-angular/src/lib/grids/selection/selection.service.ts
- src/app/grid-column-selection/grid-column-selection.sample.html
- src/app/grid-events/grid-events.component.html
- src/app/grid-events/grid-events.component.ts
> Rename columnSelected Grid event to columnSelectionChanging

- projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid-selection.spec.ts
- projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid.component.ts
- projects/igniteui-angular/src/lib/test-utils/sample-test-data.spec.ts
- projects/igniteui-angular/src/lib/test-utils/tree-grid-components.spec.ts
> Tree-Grid update cascade selection when filtering is applied 12.3.x

- projects/igniteui-angular/src/lib/accordion/accordion.component.spec.ts
- projects/igniteui-angular/src/lib/accordion/accordion.component.ts
> expand only one panel when SingleBranchExpand is true - 12.3.x

- projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-row.component.ts
Should improve performance.
Closes #
> Clear old columns from view when data has changed.

- projects/igniteui-angular/package.json
> chore(schematics): update schematics with new RC

- projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-date-expression.component.html
> Fix ESF displaying extra text in date column - 12.3.x

- projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-date-expression.component.html
> Fix ESF displaying extra text in date column 

- CHANGELOG.md
> chore(changelog): add theming section for v13

- src/app/hierarchical-grid-remote-virtualization/hierarchical-remote.service.ts
> chore(hgrid): Avoid circular deps in hgrid remote sample

- projects/igniteui-angular/src/lib/grids/filtering/excel-style/grid.excel-style-filtering.component.ts
Closes https://github.com/IgniteUI/igniteui-angular/issues/10556) ](https://github.com/IgniteUI/igniteui-angular/issues/10556)](https://github.com/IgniteUI/igniteui-angular/issues/10556
> Change how the default currency code is retrieved

- projects/igniteui-angular/src/lib/core/styles/themes/schemas/light/_chip.scss
> refactor(chip): update light color schema

- projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-header-row.component.ts
Fixes issue when removing row dimension.
Before the fix after removing the second row dimension:
Closes #
> Fix issue with changes not fully reflected when removing row chip.

- CHANGELOG.md
> docs(changelog): move grid groupStrategy to new features section

- projects/igniteui-angular/src/lib/grids/grid-base.directive.ts
- projects/igniteui-angular/src/lib/grids/grid/grid.component.ts
Closes (https://github.com/IgniteUI/igniteui-angular/issues/10582)
> fix(grid): safe guard against grid.addRow(undefined)

- projects/igniteui-angular/src/lib/grids/filtering/excel-style/grid.excel-style-filtering.component.html
> fix(esf): added role=menu to esf article - 12.3.x

- projects/igniteui-angular/src/lib/grids/filtering/excel-style/grid.excel-style-filtering.component.html
> fix(esf): added role=menu to esf article - 11.1.x

- projects/igniteui-angular/migrations/migration-collection.json
- projects/igniteui-angular/package.json
> chore(schematics): official version of schema

- projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-filtering.service.ts
> fix(pivot): Assigns `dim` a default value #10565

- projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-grid.component.html
- projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-grid.component.ts
- projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-grid.pipes.spec.ts
- projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-grid.pipes.ts
- projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-util.ts
- projects/igniteui-angular/src/lib/test-utils/pivot-grid-samples.spec.ts
- src/app/pivot-grid/pivot-grid.sample.html
> Set default expand state to be collapsed for pivot. Allow changing via prop.

- projects/igniteui-angular/src/lib/data-operations/pivot-strategy.ts
- projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-grid.pipes.spec.ts
> fix(pivot): Extract hierarchy from original leaf records.

- src/app/pivot-grid/pivot-grid.sample.html
- src/app/pivot-grid/pivot-grid.sample.scss
- src/app/pivot-grid/pivot-grid.sample.ts
> chore(pivot): Add display density to pivot sample

- projects/igniteui-angular/src/lib/data-operations/pivot-strategy.ts
- projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-filtering.service.ts
- projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-grid.component.ts
- projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-grid.pipes.ts
- projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-grid.spec.ts
> feat(pivot): Add some more pivot grid tests and apply a minor fix

- CHANGELOG.md
> Add simple combo to features in 12.3

- projects/igniteui-angular/src/lib/time-picker/time-picker.component.html
- projects/igniteui-angular/src/lib/time-picker/time-picker.component.spec.ts
> Time picker toggle in dialog mode 11.1.x

- projects/igniteui-angular/src/lib/time-picker/time-picker.component.html
- projects/igniteui-angular/src/lib/time-picker/time-picker.component.spec.ts
> Time picker toggle in dialog mode 12.3.x

- projects/igniteui-angular/src/lib/combo/combo.component.spec.ts
- projects/igniteui-angular/src/lib/icon/icon.service.ts
> fix(icon-service): don't initialize DOMParser in SSR mode

- projects/igniteui-angular/src/lib/simple-combo/simple-combo.component.spec.ts
- projects/igniteui-angular/src/lib/simple-combo/simple-combo.component.ts
- src/app/combo/combo.sample.html
- src/app/combo/combo.sample.ts
> Simple combo - increase coverage - 12.3

- projects/igniteui-angular/src/lib/simple-combo/simple-combo.component.spec.ts
- projects/igniteui-angular/src/lib/simple-combo/simple-combo.component.ts
- src/app/combo/combo.sample.html
- src/app/combo/combo.sample.ts
> Simple combo - increase coverage

- projects/igniteui-angular/src/lib/grids/filtering/base/grid-filtering-row.component.ts
- projects/igniteui-angular/src/lib/grids/grid/grid-filtering-ui.spec.ts
> Fix condition changing when erasing the value - 12.3.x

- projects/igniteui-angular/src/lib/grids/filtering/base/grid-filtering-row.component.ts
- projects/igniteui-angular/src/lib/grids/grid/grid-filtering-ui.spec.ts
> Fix condition changing when erasing the value - 13.0.x

- projects/igniteui-angular/src/lib/data-operations/pivot-strategy.ts
- projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-grid.pipes.ts
- projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-util.ts
> [igxPivot] Ensure that bottom level dimensions get populated regardless of expansion.

- projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-grid.component.html
- projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-grid.component.ts
> Add additional summary column for columns with children, that is always visible and shows the parent's aggregates.

- projects/igniteui-angular/src/lib/accordion/accordion.component.spec.ts
- projects/igniteui-angular/src/lib/accordion/accordion.component.ts
- projects/igniteui-angular/src/lib/expansion-panel/expansion-panel.component.ts
> Collapse expanded panels when setting singleBranchExpand to true 12.3.x

- projects/igniteui-angular/src/lib/accordion/accordion.component.spec.ts
- projects/igniteui-angular/src/lib/accordion/accordion.component.ts
- projects/igniteui-angular/src/lib/expansion-panel/expansion-panel.component.ts
> Collapse expanded panels when setting singleBranchExpand to true 13.0.x

- projects/igniteui-angular/src/lib/data-operations/pivot-strategy.ts
- projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-grid.component.ts
- projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-grid.interface.ts
- projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-grid.pipes.ts
- projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-row.component.ts
- projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-util.ts
- src/app/pivot-grid-noop/pivot-grid-noop.sample.html
- src/app/pivot-grid-noop/pivot-grid-noop.sample.ts
> Add additional settable pivot keys: columnDimensionSeparator, rowDimensionSeparator.

- projects/igniteui-angular/src/lib/combo/combo.common.ts
> fix(combo): Changing selectedItems() to selection in the comments

- projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-grid.component.ts
> [igxPivot] Do not split ESF values by pivot separators

- projects/igniteui-angular/src/lib/core/styles/themes/schemas/dark/_input-group.scss
> fix(themes): bootstrap input theme doesn't work

- projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-header-row.component.html
> Fix for row header area size.

- projects/igniteui-angular/src/lib/combo/combo.common.ts
> V dyulgerov/fix combo undefined error 12.3.x

- projects/igniteui-angular/src/lib/combo/combo.component.ts
> V dyulgerov/fix combo undefined error 12.1.x

- projects/igniteui-angular/src/lib/carousel/carousel-base.ts
- projects/igniteui-angular/src/lib/carousel/carousel.component.ts
- projects/igniteui-angular/src/lib/stepper/stepper.component.spec.ts
- projects/igniteui-angular/src/lib/stepper/stepper.component.ts
- projects/igniteui-angular/src/lib/tabs/tabs.directive.ts
- projects/igniteui-angular/src/lib/tabs/tabs/tabs.component.ts
> fix(tabs): change detection after animation - 13.0.x

- projects/igniteui-angular/src/lib/carousel/carousel-base.ts
- projects/igniteui-angular/src/lib/carousel/carousel.component.ts
- projects/igniteui-angular/src/lib/tabs/tabs.directive.ts
- projects/igniteui-angular/src/lib/tabs/tabs/tabs.component.ts
> fix(tabs): change detection after animation - 12.3.x

- projects/igniteui-angular/src/lib/expansion-panel/expansion-panel.component.ts
- projects/igniteui-angular/src/lib/expansion-panel/expansion-panel.spec.ts
> Emit panelCollapsing event once when a panel starts collapsing 12.3.x

- projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-grid.pipes.spec.ts
- projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-util.ts
- projects/igniteui-angular/src/lib/test-utils/pivot-grid-functions.spec.ts
> chore(*): Add more complex row dimension scenarios for tests.

- projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-grid.spec.ts
- projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-header-row.component.html
- projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-header-row.component.ts
> fix(pivot): Fix reordering of value dimension chips

- projects/igniteui-angular/src/lib/core/styles/components/tabs/_tabs-theme.scss
- projects/igniteui-angular/src/lib/tabs/tabs/tab-header.component.ts
- projects/igniteui-angular/src/lib/tabs/tabs/tabs.component.ts
> fix(tabs): fix scrolling issue

- projects/igniteui-angular/src/lib/core/styles/themes/_index.scss
> fix(themes): theme mixins don't work correctly

- projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-grid-navigation.service.ts
> fix(igxPivot): Remove selection when refocusing the grid

- projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-grid.pipes.ts
- projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-util.ts
> Fix for sorting large data in pivot.

- projects/igniteui-angular/src/lib/services/overlay/overlay.ts
> fix(tooltip):  set newly created div to display none

- projects/igniteui-angular/src/lib/services/overlay/overlay.ts
> V dyulgerov/fix tooltip is moving 12.2.x

- projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid-selection.service.ts
> Tree Grid Selection Optimization 13.0.x

- projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid-selection.service.ts
> Tree Grid Selection Optimization 12.3.x

- azure-pipelines.yml
- projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid-selection.service.ts
> Tree Grid Selection Optimization 11.1.x

- projects/igniteui-angular-i18n/src/i18n/BG/grid-resources.ts
- projects/igniteui-angular-i18n/src/i18n/CS/grid-resources.ts
- projects/igniteui-angular-i18n/src/i18n/DA/grid-resources.ts
- projects/igniteui-angular-i18n/src/i18n/DE/grid-resources.ts
- projects/igniteui-angular-i18n/src/i18n/ES/grid-resources.ts
- projects/igniteui-angular-i18n/src/i18n/FR/grid-resources.ts
- projects/igniteui-angular-i18n/src/i18n/HU/grid-resources.ts
- projects/igniteui-angular-i18n/src/i18n/IT/grid-resources.ts
- projects/igniteui-angular-i18n/src/i18n/JA/grid-resources.ts
- projects/igniteui-angular-i18n/src/i18n/KO/grid-resources.ts
- projects/igniteui-angular-i18n/src/i18n/NB/grid-resources.ts
- projects/igniteui-angular-i18n/src/i18n/NL/grid-resources.ts
- projects/igniteui-angular-i18n/src/i18n/PL/grid-resources.ts
- projects/igniteui-angular-i18n/src/i18n/PT/grid-resources.ts
- projects/igniteui-angular-i18n/src/i18n/RO/grid-resources.ts
- projects/igniteui-angular-i18n/src/i18n/SV/grid-resources.ts
- projects/igniteui-angular-i18n/src/i18n/TR/grid-resources.ts
- projects/igniteui-angular-i18n/src/i18n/ZH-HANS/grid-resources.ts
- projects/igniteui-angular-i18n/src/i18n/ZH-HANT/grid-resources.ts
- projects/igniteui-angular/src/lib/core/i18n/grid-resources.ts
- projects/igniteui-angular/src/lib/core/styles/components/grid/_grid-component.scss
- projects/igniteui-angular/src/lib/core/styles/components/grid/_grid-theme.scss
- projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-grid.spec.ts
- projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-header-row.component.html
- projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-header-row.component.ts
- src/styles/_variables.scss
> Implement drop area for the chips UI in the pivot dimensions

- projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-grid.pipes.spec.ts
- projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-util.ts
> fix(pivot): Ensure nested sibling dimensions are also processed. 

- projects/igniteui-angular/src/lib/grids/headers/grid-header.component.ts
- projects/igniteui-angular/src/lib/grids/headers/headers.module.ts
- projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-grid.module.ts
- projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-grid.spec.ts
- projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-row-dimension-content.component.ts
- projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-row-dimension-header-group.component.html
- projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-row-dimension-header-group.component.ts
- projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-row-dimension-header.component.ts
- projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-row.component.html
- projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-row.component.ts
- projects/igniteui-angular/src/lib/grids/pivot-grid/public_api.ts
> fix(pivot): Fix wrongly selected column when selecting rows

- projects/igniteui-angular/src/lib/services/excel/excel-exporter-grid.spec.ts
- projects/igniteui-angular/src/lib/services/excel/excel-files.ts
- projects/igniteui-angular/src/lib/services/excel/test-data.service.spec.ts
- projects/igniteui-angular/src/lib/services/excel/worksheet-data.ts
- projects/igniteui-angular/src/lib/test-utils/hierarchical-grid-components.spec.ts
- src/app/shared/sample-data.ts
> fix(exporter): correctly export hgrid with multi col headers only in island

- projects/igniteui-angular/src/lib/grids/common/row.interface.ts
- projects/igniteui-angular/src/lib/grids/grid-public-row.ts
> feat(rowtype): add implementation for addRowUI #10771 - 12.3

- projects/igniteui-angular/src/lib/grids/grid/grid-mrl-keyboard-nav.spec.ts
- projects/igniteui-angular/src/lib/grids/summaries/grid-summary.service.ts
> Fix - Toggling the summaries of all columns does not resize the grid correctly - 11.1

- projects/igniteui-angular/src/lib/core/styles/components/input/_input-group-theme.scss
- projects/igniteui-angular/src/lib/core/styles/typography/_typography.scss
- projects/igniteui-angular/src/lib/core/styles/typography/scale-presets/_fluent.scss
> Update fluent typography

- src/app/list-panning/list-panning.sample.html
- src/app/list-performance/list-performance.sample.html
- src/app/list/list.sample.html
- src/app/tooltip/tooltip.sample.html
> chore(icon): set color properly #10571 - 13.0.x

- src/app/list-panning/list-panning.sample.html
- src/app/list-performance/list-performance.sample.html
- src/app/list/list.sample.html
- src/app/tooltip/tooltip.sample.html
> chore(icon): set color properly #10571 - 12.3.x

- projects/igniteui-angular/src/lib/grids/common/row.interface.ts
- projects/igniteui-angular/src/lib/grids/grid-public-row.ts
* feat(rowtype): add implementation for addRowUI #10771
Co-authored-by: Radoslav Karaivanov <rkaraivanov@infragistics.com>
Closes #
> feat(rowtype): add implementation for addRowUI #10771 - 12.3 (#10789)

- projects/igniteui-angular/src/lib/grids/README.md
- projects/igniteui-angular/src/lib/grids/grid-base.directive.ts
- projects/igniteui-angular/src/lib/grids/grid/grid.component.html
- projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.component.html
- projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid.component.html
> feat(grid): reemiting changing/ed events #10780 - 12.3

- projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-row-dimension-content.component.html
- src/app/pivot-grid/pivot-grid.sample.ts
> chore(*): Fix issue with widths mismatch in row dimension content.

- projects/igniteui-angular/src/lib/core/styles/components/calendar/_calendar-theme.scss
- projects/igniteui-angular/src/lib/core/styles/typography/_typography.scss
- projects/igniteui-angular/src/lib/core/styles/typography/scale-presets/_indigo.scss
> feat(typography): Update indigo typography to match the UI kit

- projects/igniteui-angular/src/lib/core/styles/components/grid/_grid-theme.scss
> fix(grid): pinned-containers-issue

- projects/igniteui-angular/src/lib/core/styles/typography/_typography.scss
- projects/igniteui-angular/src/lib/core/styles/typography/scale-presets/_bootstrap.scss
> Update bootstrap typography

- projects/igniteui-angular/src/lib/core/styles/components/input/_input-group-theme.scss
> fix(textarea): style misplacement of resizer

- projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-grid.component.html
> chore(pivot): Remove wrong @Input pivotRowWidths of igx-pivot-row

- projects/igniteui-angular/src/lib/grids/filtering/excel-style/grid.excel-style-filtering.component.ts
- projects/igniteui-angular/src/lib/grids/grid/grid-filtering-ui.spec.ts
> fix(ESF): Update items on 1st filter column

- package-lock.json
- package.json
> chore(*): remove @types/eslint, leave only @types/estree

- projects/igniteui-angular/src/lib/grids/filtering/excel-style/grid.excel-style-filtering.component.ts
- projects/igniteui-angular/src/lib/grids/grid/grid-filtering-ui.spec.ts
Reverts IgniteUI/igniteui-angular#10928
We need some deeper investigation as there are more aspects to the issue.
> Revert "fix(ESF): Update items on 1st filter column"

- projects/igniteui-angular/src/lib/grids/grid-base.directive.ts
> V dyulgerov/fix cell selection for remote paging 12.3.x

- projects/igniteui-angular/src/lib/directives/text-selection/text-selection.directive.spec.ts
- projects/igniteui-angular/src/lib/directives/text-selection/text-selection.directive.ts
> Number Support for TextSelectionDirective

- projects/igniteui-angular/src/lib/directives/text-selection/text-selection.directive.spec.ts
- projects/igniteui-angular/src/lib/directives/text-selection/text-selection.directive.ts
> fix10806 12.3 - added number selection

- projects/igniteui-angular/src/lib/data-operations/pivot-strategy.ts
- projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-grid.component.ts
> [Pivot] Apply DataUtil sorting when sorting column dimensions and add value field to fieldsHierarchy when column  strategy is noop

- projects/igniteui-angular/migrations/update-13_1_0/index.spec.ts
- projects/igniteui-angular/migrations/update-13_1_0/index.ts
> Fix the grid's column movable migration

- projects/igniteui-angular/src/lib/combo/combo.common.ts
- projects/igniteui-angular/src/lib/grids/grid-base.directive.ts
- projects/igniteui-angular/src/lib/simple-combo/simple-combo.component.spec.ts
- projects/igniteui-angular/src/lib/simple-combo/simple-combo.component.ts
> Simple combo clears partial custom values - 12.3

- projects/igniteui-angular/src/lib/combo/combo.common.ts
- projects/igniteui-angular/src/lib/simple-combo/simple-combo.component.spec.ts
- projects/igniteui-angular/src/lib/simple-combo/simple-combo.component.ts
Closes #10886
The PR also fixes a small flickering issue.
Before the change:
After the change:
> Simple combo clears partial custom values

- projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-grid.component.html
- src/app/pivot-grid/pivot-grid.sample.html
> fix(igxPivot): Fix content and dimension content height mismatch.

- CHANGELOG.md
- projects/igniteui-angular/migrations/update-13_1_0/changes/inputs.json
- projects/igniteui-angular/migrations/update-13_1_0/index.ts
> fix(toast): missing property migration

- projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-header-row.component.ts
> fix(pivotGrid): Fix default header row for of not rendered for empty column dimensions or data.

- projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-search.component.ts
- projects/igniteui-angular/src/lib/grids/filtering/excel-style/grid.excel-style-filtering.component.ts
- projects/igniteui-angular/src/lib/grids/filtering/grid-filtering.service.ts
- projects/igniteui-angular/src/lib/grids/grid/grid-filtering-ui.spec.ts
> fix(ESF): Fixed cascading filtering

- projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-search.component.ts
- projects/igniteui-angular/src/lib/grids/filtering/excel-style/grid.excel-style-filtering.component.ts
- projects/igniteui-angular/src/lib/grids/filtering/grid-filtering.service.ts
- projects/igniteui-angular/src/lib/grids/grid/grid-filtering-ui.spec.ts
> Fixed cascading Excel-style filtering

- projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-search.component.ts
- projects/igniteui-angular/src/lib/grids/filtering/excel-style/grid.excel-style-filtering.component.ts
- projects/igniteui-angular/src/lib/grids/filtering/grid-filtering.service.ts
- projects/igniteui-angular/src/lib/grids/grid/grid-filtering-ui.spec.ts
> Fixed cascading ESF.

- projects/igniteui-angular/src/lib/directives/scroll-inertia/scroll_inertia.directive.ts
> fix(scroll): adding overflow check for inner scorlls #10949 - 13.0

- projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-data-selector.component.html
- projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-data-selector.component.ts
> fix(igxPivotSelector): Show display name if one is set for values.

- projects/igniteui-angular/src/lib/core/styles/themes/schemas/dark/_input-group.scss
> fix(input-group): broken layout in fluent theme

- projects/igniteui-angular/migrations/update-13_1_0/index.ts
> fix(migrations): fix hGrid errors in migration-23

- projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-grid.module.ts
> chore(cd): swapping places for prod build linting

- projects/igniteui-angular/src/lib/core/styles/base/utilities/_functions.scss
- projects/igniteui-angular/src/lib/core/styles/base/utilities/_mixins.scss
- projects/igniteui-angular/src/lib/core/styles/spec/_mixins.spec.scss
> feat(themes): map igx grays to igc gray colors

- projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-grid.component.ts
- src/app/pivot-grid-hierarchy/pivot-grid-hierarchy.sample.html
> fix(igxPivot): Do just one detection cycle for all for-ofs.

- projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-grid.module.ts
> chore(cd): fixing issue in build from missing module

- projects/igniteui-angular/migrations/common/UpdateChanges.ts
- projects/igniteui-angular/migrations/update-13_1_0/changes/theme-changes.json
> Fixing migration logic master #11066

- projects/igniteui-angular/package.json
> chore(schematics): update schematics

- projects/igniteui-angular/src/lib/grids/common/grid.interface.ts
- projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-data-selector.component.ts
- projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-grid.component.html
- projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-grid.component.ts
- projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-grid.pipes.ts
- projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-grid.spec.ts
- projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-header-row.component.ts
- projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-util.ts
> Add dimension's sort event that can be used for remote sorting.

- projects/igniteui-angular/src/lib/core/styles/components/grid/_pivot-data-selector-theme.scss
> Fix minor styling issue with list height in pivot selector.

- projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-grid.component.ts
> chore(*): Fix hidden property value.

- projects/igniteui-angular/src/lib/core/styles/components/grid/_pivot-data-selector-theme.scss
> style(data-selector): Remove the margin between panels

- src/app/icon/LazyModule/LazyComponent/lazyIcon.sample.ts
> fix(lazy-icon-sample): httpClient-response-error

- projects/igniteui-angular/package.json
> chore(schematics): update with schematics rc.1

- projects/igniteui-angular/src/lib/grids/grid/grid.component.html
> fix(grid): Add type to Cancel/Done buttons on 13.0.x version

- projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-grid.component.ts
- projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-grid.spec.ts
Closes #11124  
- [ x All relevant tags have been applied to this PR
> fix(pivot): Set correct default strategy for pivot.

- ROADMAP.md
> chore(*): update Roadmap Milestone 21

- ROADMAP.md
> Roadmap update m21 04 mar 22v2

- tsconfig.json
- tsconfig.typedoc.json
> fix(cd): moving the config so that it can be properly applied

- projects/igniteui-angular/src/lib/data-operations/filtering-expressions-tree.ts
- projects/igniteui-angular/src/lib/grids/filtering/grid-filtering.service.ts
- projects/igniteui-angular/src/lib/grids/grid/grid-filtering-ui.spec.ts
> fix(filtering): fix empty expr error

- projects/igniteui-angular/src/lib/core/styles/components/radio/_radio-theme.scss
- projects/igniteui-angular/src/lib/core/styles/themes/schemas/light/_radio.scss
> refactor(radio): refactor radio button bootstrap styles

- projects/igniteui-angular/src/lib/core/styles/components/list/_list-theme.scss
- src/app/list/list.sample.html
> style(list): fix border styles in bootstrap

- projects/igniteui-angular/src/lib/core/styles/themes/schemas/light/_button.scss
Closes #11095 
NOTE: Keep in mind that here, the palette colors are not updated. This is part of [another issue](https://github.com/IgniteUI/igniteui-angular/issues/11105).
> fix:(button) disabled colors in bootstrap theme.

- projects/igniteui-angular/src/lib/core/styles/themes/schemas/dark/_chip.scss
- projects/igniteui-angular/src/lib/core/styles/themes/schemas/light/_chip.scss
> style(chip): update chips styles for selected/hover/focus states

- projects/igniteui-angular/src/lib/core/styles/themes/schemas/light/_button.scss
> fix:(button) bootstrap theme disabled colors.

- projects/igniteui-angular/src/lib/core/styles/components/input/_input-group-component.scss
- projects/igniteui-angular/src/lib/core/styles/components/input/_input-group-theme.scss
- projects/igniteui-angular/src/lib/core/styles/themes/schemas/light/_input-group.scss
> fix:(input-group) fluent theme styles

- projects/igniteui-angular/src/lib/core/styles/components/input/_input-group-theme.scss
- projects/igniteui-angular/src/lib/input-group/input-group.component.html
- make sure that all inputs are the same height.
- remove unwanted shadow inside the input on focus.
Closes #11092
> fix(input-group): fluent input height.

- projects/igniteui-angular/src/lib/core/styles/components/checkbox/_checkbox-theme.scss
> theme(checkbox): change tick stroke width

- projects/igniteui-angular/src/lib/core/styles/components/checkbox/_checkbox-theme.scss
- projects/igniteui-angular/src/lib/core/styles/components/radio/_radio-theme.scss
- projects/igniteui-angular/src/lib/core/styles/components/switch/_switch-component.scss
- projects/igniteui-angular/src/lib/core/styles/components/switch/_switch-theme.scss
- projects/igniteui-angular/src/lib/core/styles/themes/schemas/light/_switch.scss
- projects/igniteui-angular/src/lib/core/styles/themes/schemas/shape/_switch.scss
> refactor(switch): update component to match latest boostrap spec

- projects/igniteui-angular/src/lib/simple-combo/simple-combo.component.spec.ts
- projects/igniteui-angular/src/lib/simple-combo/simple-combo.component.ts
> Simple combo retains selection on blur - 12.3.x

- projects/igniteui-angular/src/lib/grids/columns/column.component.ts
- projects/igniteui-angular/src/lib/grids/grid/grid.component.ts
- projects/igniteui-angular/src/lib/grids/grid/grid.pagination.spec.ts
> fix(grid): fix row indexes in remote virtualization scenario 13.0.x

- projects/igniteui-angular/src/lib/grids/columns/column.component.ts
- projects/igniteui-angular/src/lib/grids/grid/grid.component.ts
- projects/igniteui-angular/src/lib/grids/grid/grid.pagination.spec.ts
> fix(grid): fix row indexes in remote virtualization scenario 12.3.x

- projects/igniteui-angular/src/lib/core/styles/components/checkbox/_checkbox-theme.scss
- projects/igniteui-angular/src/lib/core/styles/themes/schemas/dark/_checkbox.scss
- projects/igniteui-angular/src/lib/core/styles/themes/schemas/light/_checkbox.scss
> refactor(checkbox): refactor checkbox bootstrap styles

- projects/igniteui-angular/src/lib/grids/toolbar/grid-toolbar.base.ts
> fix(grid): put actions as parameter

- projects/igniteui-angular/src/lib/core/styles/components/input/_input-group-theme.scss
Closes [#14265  ](https://infragistics.visualstudio.com/Indigo_AppBuilder/_workitems/edit/14265/)
> fix(textarea): position correctly resizer for cosy and compact for 13.0.x

- projects/igniteui-angular/src/lib/grids/grid/grid-toolbar.spec.ts
- projects/igniteui-angular/src/lib/grids/toolbar/grid-toolbar.base.ts
> fix(gridToolbarHiding): fix columnsAreaMaxHeight input property

- projects/igniteui-angular/src/lib/grids/state.directive.ts
> fix(grid): add case for dateTime

- projects/igniteui-angular/src/lib/core/styles/components/input/_input-group-theme.scss
Closes [#14265  ](https://infragistics.visualstudio.com/Indigo_AppBuilder/_workitems/edit/14265/)
> fix(textarea): style misplacement of resizer 12.3.x

- projects/igniteui-angular/src/lib/core/styles/themes/_palettes.scss
> theme(bootstrap): change bootstrap surface color in dark theme

- projects/igniteui-angular/src/lib/grids/filtering/advanced-filtering/advanced-filtering-dialog.component.html
- projects/igniteui-angular/src/lib/grids/grid/grid-filtering-advanced.spec.ts
- projects/igniteui-angular/src/lib/grids/grid/grid-toolbar.spec.ts
- projects/igniteui-angular/src/lib/grids/toolbar/grid-toolbar-advanced-filtering.component.html
- projects/igniteui-angular/src/lib/grids/toolbar/grid-toolbar-exporter.component.html
- projects/igniteui-angular/src/lib/grids/toolbar/grid-toolbar-hiding.component.html
- projects/igniteui-angular/src/lib/grids/toolbar/grid-toolbar-pinning.component.html
> Fix toolbar & advanced-filtering buttons types

- projects/igniteui-angular/src/lib/card/card.component.ts
> fix(card): actions don't render vertically

- projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-grid-aggregate.ts
- projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-grid.pipes.spec.ts
> chore(*): Add coverage for different pivot aggregates.

- projects/igniteui-angular/src/lib/grids/grid/grid.component.html
- projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.component.html
- projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid.component.html
> fix(grids): Fix rowStyles pipe to pass correct data

- projects/igniteui-angular/src/lib/core/styles/components/calendar/_calendar-theme.scss
- projects/igniteui-angular/src/lib/core/styles/components/expansion-panel/_expansion-panel-theme.scss
> build(*): fix warnings

- projects/igniteui-angular/src/lib/grids/grid/column-group.spec.ts
- projects/igniteui-angular/src/lib/grids/grid/grid.component.ts
- projects/igniteui-angular/src/lib/grids/grouping/group-by-area.directive.ts
- projects/igniteui-angular/src/lib/test-utils/grid-mch-sample.spec.ts
> fix(grid): Fix errors thrown when grid is grouped by a column that isn't defined - 12.3.x

- projects/igniteui-angular/src/lib/core/styles/components/grid/_grid-theme.scss
> style(grid): fix sort icon opacity so it shows

- projects/igniteui-angular/src/lib/grids/common/crud.service.ts
- projects/igniteui-angular/src/lib/grids/grid/grid-row-editing.spec.ts
> fix(add-row): Do not emit rowAdded event when switching between rows in edit mode

- projects/igniteui-angular/src/lib/grids/common/crud.service.ts
- projects/igniteui-angular/src/lib/grids/grid/grid-row-editing.spec.ts
> fix(add-row): Do not emit rowAdded event when switching between rows

- projects/igniteui-angular/src/lib/core/styles/base/utilities/_functions.scss
- projects/igniteui-angular/src/lib/core/styles/base/utilities/_mixins.scss
> refactor(themes): measure surface luminance when generating gray shades

- projects/igniteui-angular/src/lib/simple-combo/simple-combo.component.html
- projects/igniteui-angular/src/lib/simple-combo/simple-combo.component.ts
Closes https://github.com/IgniteUI/igniteui-angular/issues/11111
> Update the combo filter when focusing - 13.1.x

- projects/igniteui-angular/src/lib/core/styles/components/dialog/_dialog-theme.scss
> feat:(dialog) adding z-index to the content holder

- projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-grid.component.ts
Closes #11313   
Do not generate columns when using remote data and the data is not yet present
> fix(Pivot): Do not generate columns when there is no data

- projects/igniteui-angular/src/lib/core/styles/typography/_typography.scss
> fix:(typography) Remove hardcoded type-scale from the public typography mixin.

- projects/igniteui-angular/src/lib/core/styles/components/button/_button-component.scss
- projects/igniteui-angular/src/lib/core/styles/components/button/_button-theme.scss
Closes #11285 #11232 #11231 #11233
> fix(button): height discrepancy

- projects/igniteui-angular/src/lib/grids/state.directive.spec.ts
- projects/igniteui-angular/src/lib/grids/state.directive.ts
Closes #11327
Related to #11139
> fix(grid): add check for dateTime too

- projects/igniteui-angular/src/lib/directives/for-of/for_of.directive.spec.ts
- projects/igniteui-angular/src/lib/directives/for-of/for_of.directive.ts
- src/app/virtual-for-directive/virtual-for.sample.css
- src/index.html
- src/styles/_variables.scss
> igxForOf RTL support.

- projects/igniteui-angular/src/lib/core/styles/components/button/_button-theme.scss
> fix(button): wrong icon button size

- CHANGELOG.md
- projects/igniteui-angular/src/lib/core/styles/themes/_palettes.scss
- projects/igniteui-angular/src/lib/core/styles/themes/presets/igniteui-fluent-dark-rtl.scss
- projects/igniteui-angular/src/lib/core/styles/themes/presets/igniteui-fluent-dark.scss
- projects/igniteui-angular/src/lib/core/styles/themes/presets/igniteui-fluent-light-rtl.scss
- projects/igniteui-angular/src/lib/core/styles/themes/presets/igniteui-fluent-light.scss
- projects/igniteui-angular/src/lib/core/styles/themes/schemas/dark/_button.scss
> New Fluent theme, fix Fluent Word colors and change Bootstrap gray color.

- projects/igniteui-angular/src/lib/grids/grid-navigation.service.ts
- projects/igniteui-angular/src/lib/grids/grid/grid-keyBoardNav-headers.spec.ts
- projects/igniteui-angular/src/lib/grids/grid/grid.groupby.spec.ts
- projects/igniteui-angular/src/lib/grids/grouping/group-by-area.directive.ts
> Group records correctly via keyboard navigation when ignoreCase is set to true 12.3.x

- projects/igniteui-angular/src/lib/core/styles/components/button/_button-theme.scss
> fix(Button): border-radius for the after element on the FAB button

- projects/igniteui-angular/src/lib/core/styles/components/banner/_banner-theme.scss
- projects/igniteui-angular/src/lib/core/styles/components/bottom-nav/_bottom-nav-theme.scss
- projects/igniteui-angular/src/lib/core/styles/components/button-group/_button-group-theme.scss
> refactor(themes): use logical CSS properties in theme

- projects/igniteui-angular/src/lib/core/styles/components/date-range-picker/_date-range-picker-theme.scss
- projects/igniteui-angular/src/lib/core/styles/components/dialog/_dialog-theme.scss
- projects/igniteui-angular/src/lib/core/styles/components/drop-down/_drop-down-theme.scss
- projects/igniteui-angular/src/lib/core/styles/components/tabs/_tabs-theme.scss
> refactor(date-range/dialog/dropdown): use logical properties

- projects/igniteui-angular/src/lib/core/styles/components/date-range-picker/_date-range-picker-theme.scss
- projects/igniteui-angular/src/lib/core/styles/components/dialog/_dialog-theme.scss
- projects/igniteui-angular/src/lib/core/styles/components/drop-down/_drop-down-theme.scss
- projects/igniteui-angular/src/lib/core/styles/components/tabs/_tabs-theme.scss
Reverts IgniteUI/igniteui-angular#11385
> Revert "refactor(date-range/dialog/dropdown/tabs): use logical properties"

- projects/igniteui-angular/src/lib/core/styles/components/splitter/_splitter-component.scss
- projects/igniteui-angular/src/lib/core/styles/components/splitter/_splitter-theme.scss
- projects/igniteui-angular/src/lib/splitter/splitter.component.ts
> refactor(splitter): add RTL support

- projects/igniteui-angular/src/lib/core/styles/components/tabs/_tabs-theme.scss
> refactor(tabs): use logical properties

- projects/igniteui-angular/src/lib/core/styles/components/expansion-panel/_expansion-panel-theme.scss
> refactor(expansion-panel): use logical css props

- projects/igniteui-angular/src/lib/core/styles/components/grid-summary/_grid-summary-theme.scss
- projects/igniteui-angular/src/lib/core/styles/components/grid-toolbar/_grid-toolbar-theme.scss
- projects/igniteui-angular/src/lib/core/styles/components/grid/_advanced-filtering-theme.scss
- projects/igniteui-angular/src/lib/core/styles/components/grid/_excel-filtering-theme.scss
- projects/igniteui-angular/src/lib/core/styles/components/grid/_grid-theme.scss
- projects/igniteui-angular/src/lib/core/styles/components/grid/_pivot-data-selector-theme.scss
> refactor(grid): use logical CSS properties

- projects/igniteui-angular/src/lib/core/styles/components/calendar/_calendar-theme.scss
- projects/igniteui-angular/src/lib/core/styles/components/card/_card-theme.scss
- projects/igniteui-angular/src/lib/core/styles/components/carousel/_carousel-theme.scss
- projects/igniteui-angular/src/lib/core/styles/components/checkbox/_checkbox-theme.scss
- projects/igniteui-angular/src/lib/core/styles/components/chip/_chip-theme.scss
- projects/igniteui-angular/src/lib/core/styles/components/combo/_combo-theme.scss
- projects/igniteui-angular/src/lib/core/styles/components/radio/_radio-theme.scss
- projects/igniteui-angular/src/lib/core/styles/components/slider/_slider-theme.scss
- projects/igniteui-angular/src/lib/core/styles/components/snackbar/_snackbar-theme.scss
- projects/igniteui-angular/src/lib/core/styles/components/splitter/_splitter-component.scss
- projects/igniteui-angular/src/lib/core/styles/components/splitter/_splitter-theme.scss
- projects/igniteui-angular/src/lib/core/styles/components/stepper/_stepper-theme.scss
- projects/igniteui-angular/src/lib/core/styles/components/switch/_switch-theme.scss
- projects/igniteui-angular/src/lib/core/styles/components/watermark/_watermark-theme.scss
- projects/igniteui-angular/src/lib/splitter/splitter.component.ts
> refactor(component themes): use logical CSS properties

- projects/igniteui-angular/src/lib/grids/filtering/excel-style/grid.excel-style-filtering.component.ts
- projects/igniteui-angular/src/lib/grids/grid/grid-filtering-ui.spec.ts
- projects/igniteui-angular/src/lib/test-utils/grid-samples.spec.ts
> fix(esf): define all properties of "(Blanks)" items when no records meet specified filter criteria - 12.3.x

- projects/igniteui-angular/src/lib/core/styles/components/list/_list-theme.scss
- projects/igniteui-angular/src/lib/core/styles/components/time-picker/_time-picker-theme.scss
- projects/igniteui-angular/src/lib/core/styles/components/tree/_tree-theme.scss
> refactor(themes): use logical properties

- projects/igniteui-angular/src/lib/core/styles/components/input/_input-group-theme.scss
> refactor(input): use logical css properties

- projects/igniteui-angular/src/lib/grids/filtering/excel-style/grid.excel-style-filtering.component.ts
- projects/igniteui-angular/src/lib/grids/grid/grid-filtering-ui.spec.ts
- projects/igniteui-angular/src/lib/test-utils/grid-samples.spec.ts
> fix(esf): define all properties of "(Blanks)" items when no records meet specified filter criteria - 11.1.x

- projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-grid.component.ts
> fix(pivot): Regenerate columns when changing data in pivot

- projects/igniteui-angular/src/lib/core/styles/components/grid/_grid-component.scss
- projects/igniteui-angular/src/lib/core/styles/components/grid/_grid-theme.scss
- projects/igniteui-angular/src/lib/grids/cell.component.ts
> fix(grid): fix cell navigation and column selection on 12.3.x

- projects/igniteui-angular/src/lib/core/styles/components/grid/_grid-component.scss
- projects/igniteui-angular/src/lib/core/styles/components/grid/_grid-theme.scss
- projects/igniteui-angular/src/lib/grids/cell.component.ts
> fix(grid): fix cell navigation and column selection on 11.1.x

- projects/igniteui-angular/src/lib/core/styles/components/grid/_grid-component.scss
- projects/igniteui-angular/src/lib/core/styles/components/grid/_grid-theme.scss
- projects/igniteui-angular/src/lib/grids/cell.component.ts
> fix(grid): fix cell navigation and column selection on 13.1.x

- projects/igniteui-angular/src/lib/grids/moving/moving.drop.directive.ts
- src/app/grid-column-moving/grid-column-moving.sample.html
> fix(grid): changing moving drop icon #10313 #10690

- gulpfile.js
> fix(cd): resolving an issue with typedoc erros being swallowed - 12.3

- projects/igniteui-angular/src/lib/core/styles/themes/_index.scss
> fix(themes): pass roundness to custom mixins

- projects/igniteui-angular/src/lib/directives/for-of/for_of.directive.spec.ts
- projects/igniteui-angular/src/lib/directives/for-of/for_of.directive.ts
> fix(Pivot): Remove a check if scrollComponent is already in the dom

- projects/igniteui-angular/src/lib/grids/cell.component.ts
- projects/igniteui-angular/src/lib/grids/grid-navigation.service.ts
> Prevent tab navigation when cellEdit is canceled - 12.3.x

- projects/igniteui-angular/src/lib/core/styles/components/date-picker/_date-picker-theme.scss
- projects/igniteui-angular/src/lib/core/styles/components/dialog/_dialog-theme.scss
- projects/igniteui-angular/src/lib/core/styles/components/drop-down/_drop-down-theme.scss
> refactor(date-picker/dialog/dropdown): use css spacing vars

- projects/igniteui-angular/src/lib/core/styles/components/list/_list-theme.scss
- projects/igniteui-angular/src/lib/core/styles/components/tabs/_tabs-theme.scss
- projects/igniteui-angular/src/lib/core/styles/components/time-picker/_time-picker-theme.scss
> refactor(list/tabs/time-picker): use css spacing vars

- projects/igniteui-angular/src/lib/core/styles/components/date-range-picker/_date-range-picker-theme.scss
> refactor(date-range): use spacing vars

- projects/igniteui-angular/src/lib/core/styles/components/toast/_toast-theme.scss
- projects/igniteui-angular/src/lib/core/styles/components/tooltip/_tooltip-theme.scss
- projects/igniteui-angular/src/lib/core/styles/components/tree/_tree-theme.scss
> refactor(toast/tooltip/tree): use css spacing vars

- projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-custom-dialog.component.ts
> fix(esf): assigning the correct overlay id for custom dialog #11404 - 12.3

- projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-custom-dialog.component.ts
> fix(esf): assigning the correct overlay id for custom dialog #11404 - 13.1

- projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-custom-dialog.component.ts
> fix(esf): assigning the correct overlay id for custom dialog #11404

- projects/igniteui-angular/src/lib/core/styles/components/expansion-panel/_expansion-panel-theme.scss
> refactor(expansion-panel): use spacing

- projects/igniteui-angular/src/lib/core/styles/components/input/_input-group-component.scss
- projects/igniteui-angular/src/lib/core/styles/components/input/_input-group-theme.scss
> refactor(input-group): use spacing for padding and margin

- projects/igniteui-angular/src/lib/core/styles/components/grid-summary/_grid-summary-theme.scss
- projects/igniteui-angular/src/lib/core/styles/components/grid-toolbar/_grid-toolbar-theme.scss
- projects/igniteui-angular/src/lib/core/styles/components/grid/_advanced-filtering-theme.scss
- projects/igniteui-angular/src/lib/core/styles/components/grid/_excel-filtering-theme.scss
- projects/igniteui-angular/src/lib/core/styles/components/grid/_grid-theme.scss
- projects/igniteui-angular/src/lib/core/styles/components/grid/_pivot-data-selector-theme.scss
- projects/igniteui-angular/src/lib/core/styles/components/paginator/_paginator-theme.scss
> refactor(grid): use spacing for padding and margin

- projects/igniteui-angular/src/lib/core/styles/base/utilities/_mixins.scss
- projects/igniteui-angular/src/lib/core/styles/components/_index.scss
- projects/igniteui-angular/src/lib/core/styles/components/rating/_rating-component.scss
- projects/igniteui-angular/src/lib/core/styles/components/rating/_rating-theme.scss
- projects/igniteui-angular/src/lib/core/styles/themes/_core.scss
- projects/igniteui-angular/src/lib/core/styles/themes/_index.scss
- projects/igniteui-angular/src/lib/core/styles/themes/schemas/dark/_index.scss
- projects/igniteui-angular/src/lib/core/styles/themes/schemas/dark/_rating.scss
- projects/igniteui-angular/src/lib/core/styles/themes/schemas/light/_index.scss
- projects/igniteui-angular/src/lib/core/styles/themes/schemas/light/_rating.scss
> feat(rating): adding theming for the rating component

- projects/igniteui-angular/src/lib/core/styles/components/calendar/_calendar-theme.scss
> refactor(calendar): use spacing for margin and padding

- package-lock.json
- package.json
- projects/igniteui-angular/src/lib/grids/grid-public-cell.ts
- tsconfig.typedoc.json
Related to https://github.com/IgniteUI/typedoc-plugin-localization/issues/61
> feat(deps): Update typedoc plugin versions

- package-lock.json
- package.json
- tsconfig.json
Related to https://github.com/IgniteUI/typedoc-plugin-localization/issues/61
> feat(deps): Update typedoc plugin versions - 12.3.x

- projects/igniteui-angular/src/lib/grids/grid-base.directive.ts
- projects/igniteui-angular/src/lib/grids/grid-navigation.service.ts
- projects/igniteui-angular/src/lib/grids/grid/grid.component.ts
- projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.component.ts
- projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid.component.ts
- src/app/grid-remote-virtualization-with-scroll/grid-remote-virtualization-scroll.sample.html
- src/app/grid-remote-virtualization-with-scroll/grid-remote-virtualization-scroll.sample.ts
> fix(igxGrid): Add handling for remote virtualization navigation.

- projects/igniteui-angular/src/lib/grids/grid-base.directive.ts
- projects/igniteui-angular/src/lib/grids/grid-navigation.service.ts
- projects/igniteui-angular/src/lib/grids/grid/grid.component.ts
- projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.component.ts
- projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid.component.ts
- src/app/grid-remote-virtualization-with-scroll/grid-remote-virtualization-scroll.sample.html
- src/app/grid-remote-virtualization-with-scroll/grid-remote-virtualization-scroll.sample.ts
> fix(igxGrid): Add handling for remote virtualization navigation. 

- projects/igniteui-angular/src/lib/core/styles/themes/_index.scss
> fix(themes): roundness and elevation scoping

- projects/igniteui-angular/src/lib/directives/drag-drop/drag-drop.directive.ts
> fix(dragDrop): Improve safety check for when shadrowRoot is not available.

- projects/igniteui-angular/src/lib/chips/chip.component.ts
> fix(chip): Safe check chip event handlers.

- projects/igniteui-angular/src/lib/grids/cell.component.ts
> fix(editing): Update active element before updating crud status

- CHANGELOG.md
- projects/igniteui-angular/src/lib/core/styles/components/action-strip/_action-strip-theme.scss
- projects/igniteui-angular/src/lib/core/styles/components/badge/_badge-theme.scss
- projects/igniteui-angular/src/lib/core/styles/components/button/_button-theme.scss
- projects/igniteui-angular/src/lib/core/styles/components/chip/_chip-theme.scss
- projects/igniteui-angular/src/lib/core/styles/components/grid/_advanced-filtering-theme.scss
- projects/igniteui-angular/src/lib/core/styles/components/grid/_excel-filtering-theme.scss
- projects/igniteui-angular/src/lib/core/styles/components/grid/_grid-theme.scss
- projects/igniteui-angular/src/lib/core/styles/components/grid/_pivot-data-selector-theme.scss
- projects/igniteui-angular/src/lib/core/styles/components/icon/_icon-theme.scss
- projects/igniteui-angular/src/lib/core/styles/components/input/_input-group-theme.scss
- projects/igniteui-angular/src/lib/core/styles/components/navdrawer/_navdrawer-theme.scss
- projects/igniteui-angular/src/lib/core/styles/components/stepper/_stepper-theme.scss
- projects/igniteui-angular/src/lib/core/styles/components/tree/_tree-theme.scss
- src/app/grid-finjs/grid-finjs.component.scss
> Allow changing the icon size through CSS custom propertie.

- CHANGELOG.md
- projects/igniteui-angular/src/lib/core/styles/components/action-strip/_action-strip-theme.scss
- projects/igniteui-angular/src/lib/core/styles/components/badge/_badge-theme.scss
- projects/igniteui-angular/src/lib/core/styles/components/button/_button-theme.scss
- projects/igniteui-angular/src/lib/core/styles/components/chip/_chip-theme.scss
- projects/igniteui-angular/src/lib/core/styles/components/grid/_advanced-filtering-theme.scss
- projects/igniteui-angular/src/lib/core/styles/components/grid/_excel-filtering-theme.scss
- projects/igniteui-angular/src/lib/core/styles/components/grid/_grid-theme.scss
- projects/igniteui-angular/src/lib/core/styles/components/grid/_pivot-data-selector-theme.scss
- projects/igniteui-angular/src/lib/core/styles/components/input/_input-group-theme.scss
- projects/igniteui-angular/src/lib/core/styles/components/navdrawer/_navdrawer-theme.scss
- projects/igniteui-angular/src/lib/core/styles/components/stepper/_stepper-theme.scss
- projects/igniteui-angular/src/lib/core/styles/components/tree/_tree-theme.scss
- src/app/grid-finjs/grid-finjs.component.scss
> Allow changing the icon size through CSS custom properties

- projects/igniteui-angular/src/lib/core/styles/components/grid/_grid-component.scss
- projects/igniteui-angular/src/lib/core/styles/components/grid/_grid-theme.scss
- projects/igniteui-angular/src/lib/grids/tree-grid/tree-cell.component.html
> fix(tree-grid): make the tree indentation work with an infinite amount of levels

- projects/igniteui-angular/src/lib/core/styles/components/tabs/_tabs-theme.scss
> fix(tabs): unable to scroll content

- projects/igniteui-angular/src/lib/combo/combo.common.ts
> fix(combo): findMatch to return false when no item - 13.1.x

- projects/igniteui-angular/src/lib/core/styles/components/list/_list-theme.scss
> refactor(list): allow the list to scroll

- projects/igniteui-angular/src/lib/grids/grid-base.directive.ts
- projects/igniteui-angular/src/lib/grids/state.directive.ts
> fix(grid): add an if-else check to avoid error throw

- projects/igniteui-angular/src/lib/time-picker/time-picker.component.ts
Closes #11216 
- [] All relevant tags have been applied to this PR
> fix(time-picker): fix host binding with input group

- README.md
Also adding an "Overview" heading so that paragraph hierarchy makes more sense with the browser support section
> docs(readme): adding supported browsers

- projects/igniteui-angular/src/lib/grids/grid/grid.component.ts
- src/app/grid-column-moving/grid-column-moving.sample.ts
> fix(igxGrid): Add a bit more complex check for groupby records.

- projects/igniteui-angular/src/lib/grids/grid-base.directive.ts
- projects/igniteui-angular/src/lib/grids/grid/grid-filtering.spec.ts
> fix(grid): add empty check for advancedFilteringExpressionsTree

- projects/igniteui-angular/migrations/common/ServerHost.ts
Closes https://github.com/IgniteUI/igniteui-angular/issues/11512
> Implement all interface methods in the ServerHost - 13.1.x

- projects/igniteui-angular/migrations/common/ServerHost.ts
> Implement all interface methods in the ServerHost

- projects/igniteui-angular/src/lib/core/styles/themes/schemas/light/_pie-chart.scss
> fix(pie-chart): label color in dark themes

- projects/igniteui-angular/src/lib/core/styles/components/button/_button-theme.scss
- projects/igniteui-angular/src/lib/core/styles/themes/schemas/elevation/_button.scss
- projects/igniteui-angular/src/lib/core/styles/themes/schemas/light/_button.scss
Closes https://github.com/IgniteUI/igniteui-webcomponents/issues/352
> Aligning IGX Button of type icon with WC icon-button

- projects/igniteui-angular/migrations/common/UpdateChanges.ts
- projects/igniteui-angular/migrations/update-13_1_0/index.spec.ts
- projects/igniteui-angular/migrations/update-13_1_0/index.ts
Closes https://github.com/IgniteUI/igniteui-angular/issues/11511
> Update migrating of theme imports

- projects/igniteui-angular/migrations/update-13_1_0/index.ts
Related to https://github.com/IgniteUI/igniteui-angular/pull/11581
> Change import rule to use rule 13.1

- projects/igniteui-angular/migrations/update-13_1_0/index.ts
Related to https://github.com/IgniteUI/igniteui-angular/pull/11577
> Change import rule to use rule 

- projects/igniteui-angular/src/lib/directives/for-of/for_of.directive.ts
- projects/igniteui-angular/src/lib/grids/grid-base.directive.ts
- projects/igniteui-angular/src/lib/grids/grid/grid-row-pinning.spec.ts
- projects/igniteui-angular/src/lib/grids/grid/grid.component.spec.ts
update sizes when scrolling
Closes #11476
> fix(grid): Do detect changes when content in the display container changes but do not

- CHANGELOG.md
- projects/igniteui-angular/src/lib/directives/drag-drop/drag-drop.directive.ts
- src/app/drag-drop/drag-drop.sample.css
- src/app/drag-drop/drag-drop.sample.html
- src/app/drag-drop/drag-drop.sample.ts
> feat(igxDrag): Add support for window scroll or custom container element.

- projects/igniteui-angular/src/lib/combo/combo.common.ts
- projects/igniteui-angular/src/lib/combo/combo.component.spec.ts
> IgxCombo: fix asterisk not removed when removing required validator dynamically in reactive form - v.12.3

- projects/igniteui-angular/src/lib/combo/combo.common.ts
- projects/igniteui-angular/src/lib/combo/combo.component.spec.ts
> IgxCombo: fix asterisk not removed when removing required validator dynamically in reactive form - v.13.1

- projects/igniteui-angular/src/lib/directives/date-time-editor/date-time-editor.directive.spec.ts
- projects/igniteui-angular/src/lib/directives/date-time-editor/date-time-editor.directive.ts
> fix(date-time-editor): increment/decrement date portions with arrow up/down keys in shadow DOM - 11.1.x

- projects/igniteui-angular/src/lib/directives/date-time-editor/date-time-editor.directive.spec.ts
- projects/igniteui-angular/src/lib/directives/date-time-editor/date-time-editor.directive.ts
> fix(date-time-editor): increment/decrement date portions with arrow up/down keys in shadow DOM - 12.3.x

- projects/igniteui-angular/src/lib/combo/combo.common.ts
> docs(combo): Fix igxComboItem api template

- projects/igniteui-angular/src/lib/directives/radio/radio-group.directive.ts
- projects/igniteui-angular/src/lib/radio/radio.component.ts
- src/app/radio/radio.sample.html
- src/app/radio/radio.sample.ts
> fix(radio-group): propritize some radio props

- projects/igniteui-angular/package.json
> chore(schematics): update with latest

- projects/igniteui-angular/src/lib/core/styles/components/action-strip/_action-strip-theme.scss
- projects/igniteui-angular/src/lib/core/styles/components/avatar/_avatar-theme.scss
- projects/igniteui-angular/src/lib/core/styles/components/badge/_badge-theme.scss
- projects/igniteui-angular/src/lib/core/styles/components/button-group/_button-group-theme.scss
- projects/igniteui-angular/src/lib/core/styles/components/button/_button-theme.scss
- projects/igniteui-angular/src/lib/core/styles/components/calendar/_calendar-theme.scss
- projects/igniteui-angular/src/lib/core/styles/components/card/_card-theme.scss
- projects/igniteui-angular/src/lib/core/styles/components/carousel/_carousel-theme.scss
- projects/igniteui-angular/src/lib/core/styles/components/checkbox/_checkbox-theme.scss
- projects/igniteui-angular/src/lib/core/styles/components/chip/_chip-theme.scss
- projects/igniteui-angular/src/lib/core/styles/components/dialog/_dialog-theme.scss
- projects/igniteui-angular/src/lib/core/styles/components/drop-down/_drop-down-theme.scss
- projects/igniteui-angular/src/lib/core/styles/components/grid/_grid-theme.scss
- projects/igniteui-angular/src/lib/core/styles/components/input/_input-group-theme.scss
- projects/igniteui-angular/src/lib/core/styles/components/list/_list-theme.scss
- projects/igniteui-angular/src/lib/core/styles/components/navdrawer/_navdrawer-theme.scss
- projects/igniteui-angular/src/lib/core/styles/components/snackbar/_snackbar-theme.scss
- projects/igniteui-angular/src/lib/core/styles/components/splitter/_splitter-theme.scss
- projects/igniteui-angular/src/lib/core/styles/components/stepper/_stepper-theme.scss
- projects/igniteui-angular/src/lib/core/styles/components/switch/_switch-theme.scss
- projects/igniteui-angular/src/lib/core/styles/components/tabs/_tabs-theme.scss
- projects/igniteui-angular/src/lib/core/styles/components/time-picker/_time-picker-theme.scss
- projects/igniteui-angular/src/lib/core/styles/components/toast/_toast-theme.scss
- projects/igniteui-angular/src/lib/core/styles/components/tooltip/_tooltip-theme.scss
- projects/igniteui-angular/src/lib/core/styles/components/watermark/_watermark-theme.scss
> fix(border-radius): move the use of border-radius function to theme scope

- projects/igniteui-angular/src/lib/core/styles/themes/schemas/light/_expansion-panel.scss
- projects/igniteui-angular/src/lib/core/styles/typography/_typography.scss
> fix(expansion-panel): update typography

- projects/igniteui-angular/src/lib/directives/input/input.directive.spec.ts
- projects/igniteui-angular/src/lib/directives/input/input.directive.ts
> fix(input-group): properly clear file input model

- projects/igniteui-angular/src/lib/core/styles/components/navbar/_navbar-theme.scss
> feat(navbar): remove block padding

- projects/igniteui-angular/src/lib/core/styles/components/avatar/_avatar-theme.scss
- projects/igniteui-angular/src/lib/core/styles/components/button/_button-theme.scss
> fix(themes): border radius for FAB and round avatar

- projects/igniteui-angular/src/lib/core/styles/components/avatar/_avatar-theme.scss
- projects/igniteui-angular/src/lib/core/styles/components/button/_button-theme.scss
> fix(themes): border-radius for FAB and round avatar

- projects/igniteui-angular/src/lib/data-operations/filtering-strategy.ts
> fix(esf): solving a date juggling error - 13.2

- projects/igniteui-angular/src/lib/data-operations/filtering-strategy.ts
> fix(esf): solving a date juggling error - 13.1

- projects/igniteui-angular/src/lib/dialog/dialog.component.ts
> fix(dialog): Change onOpened event name to opened in the comments

- projects/igniteui-angular/src/lib/dialog/dialog.component.ts
> fix(dialog): Change onOpened event name to opened in the comments - 12.3.x

- projects/igniteui-angular/src/lib/simple-combo/simple-combo.component.spec.ts
- projects/igniteui-angular/src/lib/simple-combo/simple-combo.component.ts
> fix(simple-combo): display addItem button for partial matches - 12.3.x

- projects/igniteui-angular/src/lib/simple-combo/simple-combo.component.spec.ts
- projects/igniteui-angular/src/lib/simple-combo/simple-combo.component.ts
Closes https://github.com/IgniteUI/igniteui-angular/issues/10920
> fix(simple-combo): display addItem button for partial matches

- projects/igniteui-angular/migrations/common/UpdateChanges.spec.ts
- projects/igniteui-angular/migrations/common/UpdateChanges.ts
> fix(migrations): match only config component selector for input/output replace

- projects/igniteui-angular/migrations/common/UpdateChanges.spec.ts
- projects/igniteui-angular/migrations/common/UpdateChanges.ts
> fix(migrations): match only config comp selector for out/input replace

- projects/igniteui-angular/src/lib/directives/drag-drop/drag-drop.directive.ts
> fix(igxDrag): Check for nested shadow dom elements.

- projects/igniteui-angular/src/lib/combo/combo.component.spec.ts
- projects/igniteui-angular/src/lib/combo/combo.component.ts
- projects/igniteui-angular/src/lib/simple-combo/simple-combo.component.spec.ts
- projects/igniteui-angular/src/lib/simple-combo/simple-combo.component.ts
> fix(combos): prevent remote selection when selectionChanging is cancelled - 12.3.x

- projects/igniteui-angular/package.json
> chore(schematics): update schematics official

- projects/igniteui-angular/src/lib/core/styles/components/tabs/_tabs-theme.scss
> fix(tabs): header-item style overrides user layout

- projects/igniteui-angular/src/lib/core/styles/themes/schemas/light/_category-chart.scss
> fix(charts): negative brushes color

- projects/igniteui-angular/src/lib/core/styles/themes/schemas/dark/_stepper.scss
> fix(stepper): indigo dark theme indicator color

- projects/igniteui-angular/src/lib/core/styles/themes/schemas/light/_category-chart.scss
> docs(themes): update category chart schema docs

- projects/igniteui-angular/src/lib/core/styles/components/charts/_category-chart-theme.scss
- projects/igniteui-angular/src/lib/core/styles/components/charts/_data-chart-theme.scss
- projects/igniteui-angular/src/lib/core/styles/components/charts/_financial-chart-theme.scss
- projects/igniteui-angular/src/lib/core/styles/components/charts/_pie-chart-theme.scss
- projects/igniteui-angular/src/lib/core/styles/components/charts/_shape-chart-theme.scss
- projects/igniteui-angular/src/lib/core/styles/typography/_base.scss
- projects/igniteui-angular/src/lib/core/styles/typography/_typography.scss
> fix(charts): wrong typography styles

- .github/ISSUE_TEMPLATE/question.md
> chore(*): updating question issue template

- projects/igniteui-angular/src/lib/tree/tree.component.ts
> Add Tree component API documentation

- projects/igniteui-angular/src/lib/tree/tree.component.ts
> fix(tree): add component description

- projects/igniteui-angular/src/lib/simple-combo/simple-combo.component.spec.ts
- projects/igniteui-angular/src/lib/simple-combo/simple-combo.component.ts
> Fix cleared selection when combo loses focus - v.14.1

- projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.component.ts
- projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.spec.ts
- src/app/hierarchical-grid/hierarchical-grid.sample.html
> fix(igxHierarchicalGrid): Add hgrid getter to consider parent row island defined template.

- projects/igniteui-angular/src/lib/simple-combo/simple-combo.component.spec.ts
- projects/igniteui-angular/src/lib/simple-combo/simple-combo.component.ts
> Fix cleared selection when combo loses focus - v.12.3.x

- projects/igniteui-angular/src/lib/banner/banner.component.ts
- projects/igniteui-angular/src/lib/core/styles/components/banner/_banner-component.scss
- projects/igniteui-angular/src/lib/core/styles/components/banner/_banner-theme.scss
- projects/igniteui-angular/src/lib/tree/tree.component.ts
- src/app/banner/banner.sample.css
- src/app/banner/banner.sample.html
> fix(banner): remove the padding from the expansion panel only in context of banner

- projects/igniteui-angular/src/lib/simple-combo/simple-combo.component.spec.ts
- projects/igniteui-angular/src/lib/simple-combo/simple-combo.component.ts
> Fix cleared selection when combo loses focus - v.14.0x

- projects/igniteui-angular/src/lib/core/styles/components/grid-toolbar/_grid-toolbar-theme.scss
> fix(toolbar): reverse side padding

- projects/igniteui-angular/src/lib/grids/grid/grid.sorting.spec.ts
- projects/igniteui-angular/src/lib/time-picker/time-picker.component.spec.ts
> chore(*): remove 2 debuggers

- projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-grid.component.ts
- projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-grid.interface.ts
- projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-grid.spec.ts
- projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-util.ts
- src/app/pivot-grid/pivot-grid.sample.html
- src/app/pivot-grid/pivot-grid.sample.ts
> feat(igxPivot): Add a filterDimension method.

- projects/igniteui-angular/src/lib/combo/combo.api.ts
- projects/igniteui-angular/src/lib/combo/combo.common.ts
- projects/igniteui-angular/src/lib/combo/combo.component.spec.ts
- projects/igniteui-angular/src/lib/combo/combo.component.ts
- projects/igniteui-angular/src/lib/combo/combo.pipes.ts
- projects/igniteui-angular/src/lib/core/selection.spec.ts
- projects/igniteui-angular/src/lib/core/selection.ts
- projects/igniteui-angular/src/lib/core/utils.ts
- projects/igniteui-angular/src/lib/simple-combo/simple-combo.component.html
- projects/igniteui-angular/src/lib/simple-combo/simple-combo.component.spec.ts
- projects/igniteui-angular/src/lib/simple-combo/simple-combo.component.ts
- src/app/combo/combo.sample.html
- src/app/combo/combo.sample.ts
Closes #11610   
Related #10952 
** NOTE FOR TESTING **: Please verify that the scenario in [this conversation](https://github.com/IgniteUI/igniteui-angular/issues/10952) is also covered by the fix!
> fix(combo): selectable unique falsy values #11610

- projects/igniteui-angular/src/lib/core/styles/components/slider/_slider-component.scss
- projects/igniteui-angular/src/lib/core/styles/components/slider/_slider-theme.scss
- projects/igniteui-angular/src/lib/core/styles/themes/schemas/dark/_slider.scss
- projects/igniteui-angular/src/lib/core/styles/themes/schemas/light/_slider.scss
- projects/igniteui-angular/src/lib/slider/slider.component.html
- projects/igniteui-angular/src/lib/slider/slider.component.spec.ts
- projects/igniteui-angular/src/lib/slider/slider.component.ts
> refactor(slider): update theme to match WC

- projects/igniteui-angular/src/lib/core/styles/components/input/_input-group-theme.scss
> fix(input): firefox shows number spinners

- projects/igniteui-angular/src/lib/grids/grid-base.directive.ts
- projects/igniteui-angular/src/lib/grids/grid/grid-clipboard.spec.ts
- projects/igniteui-angular/src/lib/test-utils/grid-samples.spec.ts
> fix(grid): Allow copiyng from quick filtering input

- projects/igniteui-angular/src/lib/grids/grid-base.directive.ts
- projects/igniteui-angular/src/lib/grids/grid/grid-clipboard.spec.ts
- projects/igniteui-angular/src/lib/test-utils/grid-samples.spec.ts
> fix(grid): Allow copiyng from quick filtering input - 14.0.x

- projects/igniteui-angular/src/lib/grids/grid-base.directive.ts
- projects/igniteui-angular/src/lib/grids/grid/grid-clipboard.spec.ts
- projects/igniteui-angular/src/lib/test-utils/grid-samples.spec.ts
> fix(grid): Allow copiyng from quick filtering input - 13.2.x

- projects/igniteui-angular/src/lib/core/styles/components/tree/_tree-theme.scss
- src/app/tree/tree.sample.scss
> fix(tree): Make the tree scroll automatically when it reaches its parent height.

- projects/igniteui-angular/src/lib/grids/cell.component.html
- projects/igniteui-angular/src/lib/grids/grid/expandable-cell.component.html
- projects/igniteui-angular/src/lib/grids/tree-grid/tree-cell.component.html
> FIX - In Chrome on mac, when I enter double-byte characters in a cell, it becomes empty --13.2

- projects/igniteui-angular/src/lib/grids/grid-base.directive.ts
- projects/igniteui-angular/src/lib/grids/grid/grid-clipboard.spec.ts
- projects/igniteui-angular/src/lib/test-utils/grid-samples.spec.ts
> fix(grid): Allow copiyng from quick filtering input - 12.3.x

- projects/igniteui-angular/src/lib/core/styles/components/tree/_tree-theme.scss
> fix(tree): remove the height

- ROADMAP.md
> chore(*): roadmap-update-28-jul-2022

- projects/igniteui-angular/src/lib/grids/cell.component.html
- projects/igniteui-angular/src/lib/grids/grid/expandable-cell.component.html
- projects/igniteui-angular/src/lib/grids/tree-grid/tree-cell.component.html
> FIX - In Chrome on mac, when I enter double-byte characters in a cell, it becomes empty -14.0.x

- projects/igniteui-angular/src/lib/grids/cell.component.html
- projects/igniteui-angular/src/lib/grids/grid/expandable-cell.component.html
- projects/igniteui-angular/src/lib/grids/tree-grid/tree-cell.component.html
> FIX - In Chrome on mac, when I enter double-byte characters in a cell, it becomes empty

- projects/igniteui-angular/src/lib/core/styles/components/rating/_rating-theme.scss
- projects/igniteui-angular/src/lib/core/styles/themes/schemas/light/_rating.scss
> refactor(rating): update rating theme and schema

- projects/igniteui-angular/src/lib/core/styles/themes/schemas/light/_slider.scss
> theme(slider): update slider steps color

- projects/igniteui-angular/src/lib/directives/drag-drop/drag-drop.directive.ts
> fix(drag): Filter out parent dom elements from shadow elements when gеtting elements from point.

- projects/igniteui-angular/src/lib/directives/drag-drop/drag-drop.directive.ts
> fix(drag): Filter out parent dom elements from shadow elements when gеtting elements from point

- projects/igniteui-angular/src/lib/tree/tree-node/tree-node.component.ts
- projects/igniteui-angular/src/lib/tree/tree.spec.ts
> fix(tree): expand/collapse methods 13.2.x

- projects/igniteui-angular/src/lib/tree/tree-node/tree-node.component.ts
- projects/igniteui-angular/src/lib/tree/tree.spec.ts
> fix(tree): expand/collapse methods 14.0.x

- projects/igniteui-angular/src/lib/core/utils.ts
> fix(utils): check for empty string in formatDate

- projects/igniteui-angular/src/lib/paginator/pager.component.html
> Add type to paginator's navigation buttons - 13.2.x

- projects/igniteui-angular/src/lib/paginator/pager.component.html
> Add type to paginator's navigation buttons - 12.3.x

- projects/igniteui-angular/src/lib/paginator/pager.component.html
> Add type to paginator's navigation buttons - 14.0.x

- projects/igniteui-angular/src/lib/paginator/pager.component.html
> Add type to paginator's navigation buttons

- projects/igniteui-angular/src/lib/grids/grid/grid-cell-selection.spec.ts
- projects/igniteui-angular/src/lib/grids/selection/selection.service.ts
> fix(grid): Emit the rangeSelected event when pointerup is fired outside the Grid's cells - 14.0.x

- projects/igniteui-angular/src/lib/grids/grid/grid-cell-selection.spec.ts
- projects/igniteui-angular/src/lib/grids/selection/selection.service.ts
> fix(grid): Emit the rangeSelected event when pointerup is fired outside the Grid's cells - 12.3.x

- projects/igniteui-angular/src/lib/grids/grid/grid-cell-selection.spec.ts
- projects/igniteui-angular/src/lib/grids/selection/selection.service.ts
> fix(grid): Emit the rangeSelected event when pointerup is fired outside the Grid's cells - 13.2.x

- projects/igniteui-angular/src/lib/grids/grid/grid-cell-selection.spec.ts
- projects/igniteui-angular/src/lib/grids/selection/selection.service.ts
> fix(grid): Prevent drag selection when is initiated outside the grid - 14.0.x

- projects/igniteui-angular/src/lib/grids/grid/grid-cell-selection.spec.ts
- projects/igniteui-angular/src/lib/grids/selection/selection.service.ts
> fix(grid): Prevent drag selection when is initiated outside the grid

- projects/igniteui-angular/src/lib/directives/radio/radio-group.directive.spec.ts
- projects/igniteui-angular/src/lib/directives/radio/radio-group.directive.ts
- projects/igniteui-angular/src/lib/radio/radio.component.ts
Closes https://github.com/IgniteUI/igniteui-angular/issues/11849, https://github.com/IgniteUI/igniteui-angular/issues/11942
> fix(radio): allowing radio group to pick dynamically added radios - 13.2

- projects/igniteui-angular/src/lib/directives/radio/radio-group.directive.spec.ts
- projects/igniteui-angular/src/lib/directives/radio/radio-group.directive.ts
- projects/igniteui-angular/src/lib/radio/radio.component.ts
> fix(radio): allowing radio group to pick dynamically added radios - 12.3

- CHANGELOG.md
> docs(changelog): restoring changelog

- projects/igniteui-angular/src/lib/date-picker/date-picker.component.spec.ts
- projects/igniteui-angular/src/lib/date-picker/date-picker.component.ts
- projects/igniteui-angular/src/lib/date-range-picker/date-range-picker.component.spec.ts
- projects/igniteui-angular/src/lib/date-range-picker/date-range-picker.component.ts
- projects/igniteui-angular/src/lib/time-picker/time-picker.component.spec.ts
- projects/igniteui-angular/src/lib/time-picker/time-picker.component.ts
> fix(pickers): Set correct valid state when the form group is disabled - 12.3.x

- projects/igniteui-angular/src/lib/date-picker/date-picker.component.spec.ts
- projects/igniteui-angular/src/lib/date-picker/date-picker.component.ts
- projects/igniteui-angular/src/lib/date-range-picker/date-range-picker.component.spec.ts
- projects/igniteui-angular/src/lib/date-range-picker/date-range-picker.component.ts
- projects/igniteui-angular/src/lib/grids/grid-navigation.service.ts
- projects/igniteui-angular/src/lib/time-picker/time-picker.component.spec.ts
- projects/igniteui-angular/src/lib/time-picker/time-picker.component.ts
> fix(pickers): Set correct valid state when the form group is disabled - 13.2.x

- projects/igniteui-angular/src/lib/date-picker/date-picker.component.spec.ts
- projects/igniteui-angular/src/lib/date-picker/date-picker.component.ts
- projects/igniteui-angular/src/lib/date-range-picker/date-range-picker.component.spec.ts
- projects/igniteui-angular/src/lib/date-range-picker/date-range-picker.component.ts
- projects/igniteui-angular/src/lib/time-picker/time-picker.component.spec.ts
- projects/igniteui-angular/src/lib/time-picker/time-picker.component.ts
> fix(pickers): Set correct valid state when the form group is disabled - 14.0.x

- projects/igniteui-angular/src/lib/grids/columns/column.component.ts
- projects/igniteui-angular/src/lib/grids/grid-base.directive.ts
- projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.component.ts
- projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.spec.ts
- projects/igniteui-angular/src/lib/grids/watch-changes.ts
> fix(hgrid):fix autosize err with header calc

- projects/igniteui-angular/src/lib/directives/drag-drop/drag-drop.directive.ts
- projects/igniteui-angular/src/lib/directives/drag-drop/drag-drop.spec.ts
> fix(igxDrag): Fix initial top ghost position when the ghost host has position altered.

- projects/igniteui-angular/src/lib/simple-combo/simple-combo.component.ts
- src/app/combo/combo.sample.html
- src/app/combo/combo.sample.ts
- src/app/combo/remote-nwind.service.ts
Related to https://github.com/IgniteUI/igniteui-angular/issues/11885
> Combo filtering enhancements 12.3

- projects/igniteui-angular/src/lib/simple-combo/simple-combo.component.ts
- src/app/combo/combo.sample.html
- src/app/combo/combo.sample.ts
- src/app/combo/remote-nwind.service.ts
Related to https://github.com/IgniteUI/igniteui-angular/issues/11885
> Combo filtering enhancements 13.2

- projects/igniteui-angular/src/lib/simple-combo/simple-combo.component.ts
- src/app/combo/combo.sample.html
- src/app/combo/combo.sample.ts
- src/app/combo/remote-nwind.service.ts
Related to https://github.com/IgniteUI/igniteui-angular/issues/11885
> Combo filtering enhancements 14.0

- projects/igniteui-angular/src/lib/combo/public_api.ts
> fix(combo): expose IComboFilteringOptions

- projects/igniteui-angular/src/lib/grids/grid/grid-validation.spec.ts
- projects/igniteui-angular/src/lib/test-utils/grid-functions.spec.ts
- projects/igniteui-angular/src/lib/test-utils/grid-validation-samples.spec.ts
> test(validator): Some fixes to the validator tests and add a few more.

- CHANGELOG.md
- projects/igniteui-angular/migrations/migration-collection.json
- projects/igniteui-angular/migrations/update-14_1_0/changes/theme-changes.json
- projects/igniteui-angular/migrations/update-14_1_0/index.spec.ts
- projects/igniteui-angular/migrations/update-14_1_0/index.ts
- projects/igniteui-angular/src/lib/core/styles/components/tabs/_tabs-theme.scss
> fix(tabs): remove shadow property

- projects/igniteui-angular/src/lib/directives/for-of/for_of.directive.ts
- projects/igniteui-angular/src/lib/grids/grid-base.directive.ts
- projects/igniteui-angular/src/lib/grids/grid/column-group.spec.ts
- projects/igniteui-angular/src/lib/grids/grid/grid.component.spec.ts
Closes #11239
Closes #11751 
Closes #11996
> FIX- when column groups are hidden the grid layout is broken --master

- projects/igniteui-angular/src/lib/grids/api.service.ts
- projects/igniteui-angular/src/lib/grids/columns/column.component.ts
- projects/igniteui-angular/src/lib/grids/common/grid.interface.ts
- projects/igniteui-angular/src/lib/grids/grid-base.directive.ts
- projects/igniteui-angular/src/lib/grids/grid-public-cell.ts
- projects/igniteui-angular/src/lib/grids/grid-public-row.ts
- projects/igniteui-angular/src/lib/grids/grid/grid-validation.service.ts
- projects/igniteui-angular/src/lib/grids/grid/grid-validation.spec.ts
- projects/igniteui-angular/src/lib/grids/public_api.ts
- projects/igniteui-angular/src/lib/test-utils/grid-validation-samples.spec.ts
- src/app/grid-cellEditing/grid-cellEditing.component.ts
- src/app/grid-validation/grid-validation.sample.component.html
- src/app/grid-validation/grid-validation.sample.component.ts
> refactor(grids): row,cell - move errors to validation object, add status

- projects/igniteui-angular/src/lib/core/styles/components/navbar/_navbar-theme.scss
- projects/igniteui-angular/src/lib/core/styles/themes/schemas/light/_navbar.scss
- src/app/navbar/navbar.sample.html
> refactor(navbar): update icons and icon buttons

- projects/igniteui-angular/src/lib/combo/combo.common.ts
- projects/igniteui-angular/src/lib/combo/combo.component.spec.ts
- projects/igniteui-angular/src/lib/simple-combo/simple-combo.component.spec.ts
- projects/igniteui-angular/src/lib/simple-combo/simple-combo.component.ts
> Preserve selection on blur when having a match and a partial match - 13.2

- projects/igniteui-angular/src/lib/combo/combo.common.ts
- projects/igniteui-angular/src/lib/combo/combo.component.spec.ts
- projects/igniteui-angular/src/lib/simple-combo/simple-combo.component.spec.ts
- projects/igniteui-angular/src/lib/simple-combo/simple-combo.component.ts
> Preserve selection on blur when having a match and a partial match - 12.3

- projects/igniteui-angular/src/lib/grids/grid/grid-toolbar.spec.ts
- projects/igniteui-angular/src/lib/grids/toolbar/grid-toolbar.base.ts
> fix(toolbar-hiding): properly emit columnToggle - 12.3.x

- projects/igniteui-angular/src/lib/grids/grid/grid-toolbar.spec.ts
- projects/igniteui-angular/src/lib/grids/toolbar/grid-toolbar.base.ts
> fix(toolbar-hiding): properly emit columnToggle - 13.2.x

- projects/igniteui-angular/src/lib/core/styles/components/navbar/_navbar-theme.scss
> fix(navbar): fix igx-icon selector to be direct child only

- ROADMAP.md
> chore(*): roadmap-update-16-sep-22

- projects/igniteui-angular/src/lib/combo/combo.common.ts
- projects/igniteui-angular/src/lib/combo/combo.component.spec.ts
- projects/igniteui-angular/src/lib/simple-combo/simple-combo.component.spec.ts
> fix(combos): Add predefined selection to the input when the data is bound after the initialization - 12.3.x

- projects/igniteui-angular/src/lib/grids/common/grid.interface.ts
- projects/igniteui-angular/src/lib/grids/grid-base.directive.ts
- projects/igniteui-angular/src/lib/grids/grid.rowEdit.directive.ts
- projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-grid.component.ts
- projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-grid.directives.ts
- projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-grid.interface.ts
- projects/igniteui-angular/src/lib/grids/row-drag.directive.ts
Added template guards for:
- IgxRowEditTemplateDirective
- IgxRowEditTextDirective
- IgxRowAddTextDirective
- IgxRowEditActionsDirective
- IgxDragIndicatorIconDirective
- IgxRowDragGhostDirective
- IgxPivotValueChipTemplateDirective
> Add some more template guard types.

- projects/igniteui-angular/src/lib/grids/common/grid.interface.ts
- projects/igniteui-angular/src/lib/grids/filtering/excel-style/excel-style-search.component.ts
- projects/igniteui-angular/src/lib/grids/grid/grid.component.ts
- projects/igniteui-angular/src/lib/grids/grid/grid.directives.ts
> Add template context guards for ES Loading, MDV and GroupBy row

- projects/igniteui-angular/src/lib/grids/columns/column-group.component.ts
- projects/igniteui-angular/src/lib/grids/columns/column.component.ts
- projects/igniteui-angular/src/lib/grids/columns/templates.directive.ts
- projects/igniteui-angular/src/lib/grids/common/grid.interface.ts
- projects/igniteui-angular/src/lib/grids/filtering/base/grid-filtering-cell.component.ts
- projects/igniteui-angular/src/lib/grids/grid-base.directive.ts
- projects/igniteui-angular/src/lib/grids/grid.rowEdit.directive.ts
- projects/igniteui-angular/src/lib/grids/grid/expandable-cell.component.html
- projects/igniteui-angular/src/lib/grids/grid/grid.component.ts
- projects/igniteui-angular/src/lib/grids/grid/grid.directives.ts
- projects/igniteui-angular/src/lib/grids/headers/grid-header-row.component.html
- projects/igniteui-angular/src/lib/grids/headers/grid-header-row.component.ts
- projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-grid.component.ts
- projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-grid.directives.ts
- projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-grid.interface.ts
- projects/igniteui-angular/src/lib/grids/row-drag.directive.ts
- projects/igniteui-angular/src/lib/grids/selection/row-selectors.ts
Reverts IgniteUI/igniteui-angular#12081
> Revert "Add template context guards for some directives"

- projects/igniteui-angular/src/lib/grids/toolbar/common.ts
Reverts IgniteUI/igniteui-angular#12085
> Revert "chore(toolbar): add ngTemplateContextGuard for the toolbar"

- projects/igniteui-angular/src/lib/radio/radio.component.ts
> fix(radio): focus nativeElement

- projects/igniteui-angular/src/lib/core/styles/components/input/_input-group-component.scss
- projects/igniteui-angular/src/lib/core/styles/components/input/_input-group-theme.scss
> fix(input-group): prefix & suffix wrong colors

- projects/igniteui-angular/src/lib/combo/combo-dropdown.component.ts
- projects/igniteui-angular/src/lib/combo/combo.api.ts
- projects/igniteui-angular/src/lib/combo/combo.common.ts
- projects/igniteui-angular/src/lib/combo/combo.component.html
- projects/igniteui-angular/src/lib/combo/combo.component.spec.ts
- projects/igniteui-angular/src/lib/combo/combo.component.ts
- projects/igniteui-angular/src/lib/combo/combo.pipes.ts
- projects/igniteui-angular/src/lib/core/selection.spec.ts
- projects/igniteui-angular/src/lib/core/selection.ts
- projects/igniteui-angular/src/lib/simple-combo/simple-combo.component.html
- projects/igniteui-angular/src/lib/simple-combo/simple-combo.component.spec.ts
- projects/igniteui-angular/src/lib/simple-combo/simple-combo.component.ts
Closes #12048   
**NOTE FOR TESTING** : 
* Should be able to select all falsy values except 'undefined', i.e., **false, '', 0, NaN, null**. 
* For complex data, if there is an item with valueKey=undefined it should be displayed in the dropdown, but cannot be selected.
* When testing **NaN** use an additional variable in the ts file 
```
public selectNaN: any = NaN;
<igx-simple-combo [data]="data" [(ngModel)]="selectedValue"></igx-simple-combo>
<button igxButton (click)="selectedValue = selectNaN"> NaN </button>
```
Assigning it directly in the html file shows an error "Property 'NaN' does not exist on type 'ComboSampleComponent'.ngtsc(2339)" and the variable bound to the ngModel is assumed as 'undefined'.
* Test IgxSimpleCombo when bound to the `ngModel` with `required` attribute set:
- …
> Select falsy values via ngModel - 12.3.x

- ROADMAP.md
> chore(*): raodmap-update-14.2-07-oct-22

- projects/igniteui-angular/src/lib/core/styles/components/action-strip/_action-strip-theme.scss
- projects/igniteui-angular/src/lib/core/styles/themes/schemas/dark/_action-strip.scss
- projects/igniteui-angular/src/lib/core/styles/themes/schemas/light/_action-strip.scss
> style(action-strip): fix wrong colors and roundness.

- projects/igniteui-angular/src/lib/core/styles/components/progress/_progress-theme.scss
- projects/igniteui-angular/src/lib/progressbar/circularbar.component.spec.ts
- projects/igniteui-angular/src/lib/progressbar/templates/circular-bar.component.html
- src/app/progressbar/progressbar.sample.html
- src/app/progressbar/progressbar.sample.scss
- src/styles/_variables.scss
> fix(circular-progress): brakes on zoom in Safari

- projects/igniteui-angular/src/lib/core/styles/components/dialog/_dialog-theme.scss
> style(dialog): change igx-calendar width to min-width in the context of igx-dialog.

- projects/igniteui-angular/src/lib/core/styles/components/dock-manager/_dock-manager-component.scss
- projects/igniteui-angular/src/lib/core/styles/components/stepper/_stepper-component.scss
> fix(themes): unable to exclude theme mixins

- projects/igniteui-angular/src/lib/core/styles/themes/schemas/light/_button.scss
> fix(button): fluent theme border

- projects/igniteui-angular/src/lib/core/styles/components/query-builder/_query-builder-theme.scss
> fix(query-builder): add time-picker margin

- projects/igniteui-angular/migrations/update-15_0_0/changes/inputs.json
- projects/igniteui-angular/migrations/update-15_0_0/index.spec.ts
- projects/igniteui-angular/src/lib/directives/radio/radio-group.directive.spec.ts
- projects/igniteui-angular/src/lib/directives/radio/radio-group.directive.ts
> refactor(radio-group): remove deprecated properties

- projects/igniteui-angular/src/lib/simple-combo/simple-combo.component.spec.ts
- projects/igniteui-angular/src/lib/simple-combo/simple-combo.component.ts
> fix(simple-combo): preserve selection on blur/tab when filtering the items - 12.3.x

- projects/igniteui-angular/src/lib/simple-combo/simple-combo.component.spec.ts
- projects/igniteui-angular/src/lib/simple-combo/simple-combo.component.ts
> fix(simple-combo): preserve selection on blur/tab when filtering the items - 13.2.x

- projects/igniteui-angular/src/lib/simple-combo/simple-combo.component.spec.ts
- projects/igniteui-angular/src/lib/simple-combo/simple-combo.component.ts
> fix(simple-combo): preserve selection on blur/tab when filtering the items - 14.2.x

- projects/igniteui-angular/src/lib/simple-combo/simple-combo.component.spec.ts
- projects/igniteui-angular/src/lib/simple-combo/simple-combo.component.ts
> fix(simple-combo): preserve selection on blur/tab when filtering the items - master

- projects/igniteui-angular/src/lib/select/select.component.spec.ts
- projects/igniteui-angular/src/lib/select/select.component.ts
> fix(select): Fix oldSelection when the value is undefined on 13.2.x

- projects/igniteui-angular/src/lib/core/styles/components/paginator/_paginator-theme.scss
> style(paginator): Remove grid-row from paginator theme.

- projects/igniteui-angular/src/lib/select/select.component.spec.ts
- projects/igniteui-angular/src/lib/select/select.component.ts
> fix(select): Fix oldSelection when the value is undefined on 12.3.x

- projects/igniteui-angular/src/lib/simple-combo/simple-combo.component.spec.ts
- projects/igniteui-angular/src/lib/simple-combo/simple-combo.component.ts
Closes https://github.com/IgniteUI/igniteui-angular/issues/12269
> Create display text only if there is bound data 12.3x

- projects/igniteui-angular/src/lib/simple-combo/simple-combo.component.spec.ts
- projects/igniteui-angular/src/lib/simple-combo/simple-combo.component.ts
Closes https://github.com/IgniteUI/igniteui-angular/issues/12269
> Create display text only if there is bound data 13.2x

- projects/igniteui-angular/src/lib/simple-combo/simple-combo.component.spec.ts
- projects/igniteui-angular/src/lib/simple-combo/simple-combo.component.ts
Closes https://github.com/IgniteUI/igniteui-angular/issues/12269
> Create display text only if there is bound data 14.2x

- projects/igniteui-angular/src/lib/grids/filtering/advanced-filtering/advanced-filtering-dialog.component.ts
- projects/igniteui-angular/src/lib/grids/grid/grid-filtering-advanced.spec.ts
> fix(advanced-filtering): commit changes on applying - 14.2.x

- .github/workflows/nodejs.yml
- package-lock.json
- package.json
- projects/igniteui-angular/src/lib/combo/combo-add-item.component.ts
- projects/igniteui-angular/src/lib/combo/combo-item.component.ts
- projects/igniteui-angular/src/lib/drop-down/drop-down-item.component.ts
- projects/igniteui-angular/src/lib/grids/common/crud.service.ts
- projects/igniteui-angular/src/lib/grids/grid/grid.component.ts
- projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-grid.pipes.ts
- projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid.component.ts
- projects/igniteui-angular/src/lib/select/select-positioning-strategy.ts
- projects/igniteui-angular/src/lib/services/overlay/position/auto-position-strategy.ts
- projects/igniteui-angular/src/lib/services/overlay/position/base-fit-position-strategy.ts
- projects/igniteui-angular/src/lib/services/overlay/position/connected-positioning-strategy.ts
- projects/igniteui-angular/src/lib/services/overlay/position/container-position-strategy.ts
- projects/igniteui-angular/src/lib/services/overlay/position/elastic-position-strategy.ts
- projects/igniteui-angular/src/lib/services/overlay/position/global-position-strategy.ts
- projects/igniteui-angular/src/lib/services/overlay/scroll/NoOpScrollStrategy.ts
- projects/igniteui-angular/src/lib/services/overlay/scroll/absolute-scroll-strategy.ts
- projects/igniteui-angular/src/lib/services/overlay/scroll/block-scroll-strategy.ts
- projects/igniteui-angular/src/lib/services/overlay/scroll/close-scroll-strategy.ts
- projects/igniteui-angular/src/lib/services/overlay/scroll/scroll-strategy.ts
- projects/igniteui-angular/src/lib/services/transaction/base-transaction.ts
- projects/igniteui-angular/src/lib/services/transaction/igx-transaction.ts
- src/app/pivot-grid-state/pivot-grid-state.sample.ts
- src/app/pivot-grid/pivot-grid.sample.ts
> chore(deps): update typedoc, typescript and plugin deps

- projects/igniteui-angular/src/lib/core/styles/themes/schemas/dark/_scrollbar.scss
> fix(scrollbar): thumb not visible in dark bootstrap theme

- projects/igniteui-angular/src/lib/grids/columns/column-group.component.ts
- projects/igniteui-angular/src/lib/grids/grid/column-group.spec.ts
- projects/igniteui-angular/src/lib/test-utils/grid-mch-sample.spec.ts
> Fix dynamic column-group child column

- projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid-integration.spec.ts
- projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid-row.component.ts
> Fix error when deleting a pinned row - 12.3

- projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid-integration.spec.ts
- projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid-row.component.ts
> Fix error when deleting a pinned row - 14.2

- ROADMAP.md
> chore(*): roadmap-update-16-nov-2022

- projects/igniteui-angular/src/lib/core/styles/components/button/_button-theme.scss
- projects/igniteui-angular/src/lib/grids/filtering/base/grid-filtering-row.component.html
> fix(grid): filtering row buttons outline problem

- projects/igniteui-angular/src/lib/core/styles/components/calendar/_calendar-theme.scss
- projects/igniteui-angular/src/lib/core/styles/components/checkbox/_checkbox-theme.scss
- projects/igniteui-angular/src/lib/core/styles/components/grid-toolbar/_grid-toolbar-theme.scss
- projects/igniteui-angular/src/lib/core/styles/components/progress/_progress-theme.scss
- projects/igniteui-angular/src/lib/core/styles/components/radio/_radio-theme.scss
- projects/igniteui-angular/src/lib/core/styles/components/switch/_switch-theme.scss
- src/styles/_variables.scss
> refactor(themes): replace em with rem

- package-lock.json
> ci(*): resolving issue with package lock

- .angulardoc.json
- projects/igniteui-angular/src/lib/directives/autocomplete/autocomplete.directive.spec.ts
- projects/igniteui-angular/src/lib/directives/autocomplete/autocomplete.directive.ts
> Autocomplete Japanese input support for Chrome on Mac - 14.2

- projects/igniteui-angular/src/lib/action-strip/action-strip.component.ts
- projects/igniteui-angular/src/lib/action-strip/grid-actions/grid-editing-actions.component.spec.ts
- projects/igniteui-angular/src/lib/grids/row.directive.ts
> fix(action-strip): Hide action strip on mouse leave event of row 13.2.x

- projects/igniteui-angular/src/lib/directives/mask/mask-parsing.service.ts
- projects/igniteui-angular/src/lib/directives/mask/mask.directive.spec.ts
- projects/igniteui-angular/src/lib/directives/mask/mask.directive.ts
Closes https://github.com/IgniteUI/igniteui-angular/issues/11852
> Deleting items with the igxMask works as expected - 14.2

- projects/igniteui-angular/src/lib/directives/mask/mask-parsing.service.ts
- projects/igniteui-angular/src/lib/directives/mask/mask.directive.spec.ts
- projects/igniteui-angular/src/lib/directives/mask/mask.directive.ts
Closes https://github.com/IgniteUI/igniteui-angular/issues/11852
> Deleting items with the igxMask works as expected - 13.2 

- projects/igniteui-angular/src/lib/directives/mask/mask-parsing.service.ts
- projects/igniteui-angular/src/lib/directives/mask/mask.directive.spec.ts
- projects/igniteui-angular/src/lib/directives/mask/mask.directive.ts
Closes https://github.com/IgniteUI/igniteui-angular/issues/11852
> Deleting items with the igxMask works as expected - 12.3

- projects/igniteui-angular/package.json
- projects/igniteui-angular/schematics/ng-add/add-normalize.ts
- projects/igniteui-angular/schematics/utils/dependency-handler.ts
> chore(schematics): adapt schematics to 15.0.0 updates

- projects/igniteui-angular/src/lib/simple-combo/simple-combo.component.html
- projects/igniteui-angular/src/lib/simple-combo/simple-combo.component.spec.ts
> fix(simple-combo): Toggle combo on templated icon click - 14.2.x

- projects/igniteui-angular/src/lib/simple-combo/simple-combo.component.html
- projects/igniteui-angular/src/lib/simple-combo/simple-combo.component.spec.ts
> fix(simple-combo): Toggle combo on templated icon click - 13.2.x

- projects/igniteui-angular/src/lib/core/utils.ts
- projects/igniteui-angular/src/lib/grids/grid/column-resizing.spec.ts
- src/app/grid-column-resizing/grid-column-resizing.sample.css
- src/app/grid-column-resizing/grid-column-resizing.sample.html
- src/app/grid-column-resizing/grid-column-resizing.sample.ts
> fix(igxGrid): Include scale in calculations for column autosize api.

- projects/igniteui-angular/src/lib/grids/filtering/base/grid-filtering-row.component.html
> fix(grid-filtering): prevent form submit on filter buttons click - 14.2.x

- projects/igniteui-angular/src/lib/combo/combo.common.ts
- projects/igniteui-angular/src/lib/combo/combo.component.spec.ts
- projects/igniteui-angular/src/lib/simple-combo/simple-combo.component.html
- projects/igniteui-angular/src/lib/simple-combo/simple-combo.component.spec.ts
- projects/igniteui-angular/src/lib/simple-combo/simple-combo.component.ts
- src/app/combo/combo.sample.html
- src/app/combo/combo.sample.ts
> fix(simple-combo): preserve selection when bound to remote data - 14.2.x 

- projects/igniteui-angular/src/lib/core/styles/components/button/_button-theme.scss
> feat(button): fix material raised button height when there is an icon inside.

- projects/igniteui-angular/src/lib/core/styles/components/calendar/_calendar-theme.scss
Closes https://github.com/IgniteUI/igniteui-angular-samples/issues/3172
> feat(calendar): Add content-text-color to all views that can be decoupled from the calendar.

- projects/igniteui-angular/src/lib/core/styles/components/calendar/_calendar-theme.scss
Closes https://github.com/IgniteUI/igniteui-angular-samples/issues/3172
> feat(calendar): Add content-text-color to all views that can be decoupled from the calendar

- projects/igniteui-angular/src/lib/core/styles/components/grid-toolbar/_grid-toolbar-theme.scss
> refactor(toolbar): to use absolute position so the buttons are allaysin the view

- projects/igniteui-angular/src/lib/core/styles/themes/schemas/dark/_dialog.scss
- projects/igniteui-angular/src/lib/core/styles/themes/schemas/light/_dialog.scss
> style(dialog): Change message color in fluent light and dark themes.

- package-lock.json
- package.json
- projects/igniteui-angular/package.json
- projects/igniteui-angular/src/lib/core/styles/components/dock-manager/_dock-manager-theme.scss
> fix(themes): prefix dock manager CSS variables

- projects/igniteui-angular/src/lib/grids/common/crud.service.ts
- projects/igniteui-angular/src/lib/grids/grid/grid-add-row.spec.ts
> fix(grid): Add check whether the row editing has already started - 14.2.x

- projects/igniteui-angular/src/lib/grids/pivot-grid/pivot-grid-dimensions.ts
> fix(pivotDate): Cache month formatter for pivot date dimension.

- projects/igniteui-angular-i18n/src/i18n/KO/grid-resources.ts
> fix(i18n): Updating Grid localization for Korean - 14.2.x

- projects/igniteui-angular/src/lib/grids/common/crud.service.ts
- projects/igniteui-angular/src/lib/grids/grid/grid-add-row.spec.ts
> fix(grid): Add check whether the row editing has already started - 15.0.x

- projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid.component.spec.ts
- projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid.pipes.ts
- projects/igniteui-angular/src/lib/test-utils/tree-grid-components.spec.ts
> fix(tree-grid): Enable displaying flat data when foreignKey is not set - 15.0.x

- projects/igniteui-angular/src/lib/core/styles/typography/_typography.scss
> refactor(typography): remove font size and line height

- projects/igniteui-angular/src/lib/core/styles/components/button-group/_button-group-theme.scss
> fix(button-group): remove margin from boostrap button

- projects/igniteui-angular/src/lib/grids/grid/grid.summary.pipe.ts
- projects/igniteui-angular/src/lib/grids/summaries/grid-summary.service.ts
- projects/igniteui-angular/src/lib/grids/summaries/grid-summary.ts
> Expose groupRecord property in grid summaries on 14.2.x

- CHANGELOG.md
- projects/igniteui-angular/src/lib/grids/summaries/grid-summary.ts
> chore(changelog): Add short description for groupRecord in changelog

- projects/igniteui-angular/src/lib/grids/grid-base.directive.ts
> fix(hgrid-copy): correctly calculate expanded rows

- projects/igniteui-angular/src/lib/grids/grid-base.directive.ts
> fix(hgrid-copy): correctly calculate expanded rows - 15.0.x

- projects/igniteui-angular/src/lib/grids/grid-base.directive.ts
> fix(hgrid-copy): correctly calculate expanded rows - 14.2.x

- projects/igniteui-angular/src/lib/chips/chips-area.component.ts
- projects/igniteui-angular/src/lib/combo/combo-item.component.ts
- projects/igniteui-angular/src/lib/combo/combo.common.ts
- projects/igniteui-angular/src/lib/combo/combo.component.html
- projects/igniteui-angular/src/lib/core/utils.ts
- projects/igniteui-angular/src/lib/list/list-item.component.html
- projects/igniteui-angular/src/lib/list/list-item.component.ts
- projects/igniteui-angular/src/lib/simple-combo/simple-combo.component.html
> refactor(*): replace px with rem for bound styles

- projects/igniteui-angular/src/lib/core/styles/components/grid-toolbar/_grid-toolbar-theme.scss
> fix(toolbar): Reflect group by area styles when toolbar is enabled.

- projects/igniteui-angular/src/lib/grids/grid-base.directive.ts
> Do not close the dropdown menu if the Grid is scrolled horizontally and a column is being hidden through the UI --14.2

- projects/igniteui-angular/src/lib/grids/grid-base.directive.ts
> Do not close the dropdown menu if the Grid is scrolled horizontally and a column is being hidden through the UI --15.0

- projects/igniteui-angular/src/lib/grids/grid-base.directive.ts
> Do not close the dropdown menu if the Grid is scrolled horizontally and a column is being hidden through the UI

- projects/igniteui-angular/src/lib/core/styles/components/chip/_chip-theme.scss
> fix(chip): icons alignment in prefix/suffix containers

- projects/igniteui-angular/src/lib/paginator/pager.component.html
- projects/igniteui-angular/src/lib/paginator/paginator.component.spec.ts
- projects/igniteui-angular/src/lib/paginator/paginator.component.ts
> fix(paginator): Display '1 of 1' when there are no records to show - 14.2.x

- projects/igniteui-angular/src/lib/paginator/pager.component.html
- projects/igniteui-angular/src/lib/paginator/paginator.component.spec.ts
> fix(paginator): Display '1 of 1' when there are no records to show

- projects/igniteui-angular/src/lib/paginator/pager.component.html
- projects/igniteui-angular/src/lib/paginator/paginator.component.spec.ts
- projects/igniteui-angular/src/lib/paginator/paginator.component.ts
> fix(paginator): Display '1 of 1' when there are no records to show - 15.0.x

- projects/igniteui-angular/migrations/update-15_0_4/index.spec.ts
- projects/igniteui-angular/schematics/utils/dependency-handler.ts
> fix(migrations): do not migrate for libs & migrate for server #12508

- projects/igniteui-angular/src/lib/grids/common/crud.service.ts
> fix(grid): add explicit date comparison in crud service

- projects/igniteui-angular/src/lib/core/styles/components/chip/_chip-theme.scss
> fix(chip): icons alignment in prefix/suffix containers - 15.0.x

- projects/igniteui-angular/src/lib/core/styles/components/chip/_chip-theme.scss
> fix(chip): icons alignment in prefix/suffix containers - 14.2.x

- projects/igniteui-angular/src/lib/grids/common/crud.service.ts
> fix(grid): add explicit date comparison in crud service - 15.0.x

- projects/igniteui-angular/src/lib/grids/common/crud.service.ts
> fix(grid): add explicit date comparison in crud service - 14.2.x

- projects/igniteui-angular/src/lib/core/styles/components/grid-toolbar/_grid-toolbar-theme.scss
- projects/igniteui-angular/src/lib/core/styles/components/grid/_grid-theme.scss
Closes https://github.com/IgniteUI/igniteui-angular/issues/12518
This PR also fixes https://github.com/IgniteUI/igniteui-angular/pull/12349 in a way that does not require [this fix](https://github.com/IgniteUI/igniteui-angular/pull/12492/files)
> fix(grid-toolbar): toolbar doesn't fit content

- projects/igniteui-angular/src/lib/core/styles/components/card/_card-theme.scss
> fix(card): actions typography overrides p styles

- projects/igniteui-angular/src/lib/grids/grid/grid.component.spec.ts
> test(tab): Fix timing issue related to tabs test.

- projects/igniteui-angular/src/lib/grids/cell.component.ts
- projects/igniteui-angular/src/lib/grids/grid/grid.component.spec.ts
> Running grid (selected) event in  the angular zone

- projects/igniteui-angular/src/lib/grids/cell.component.ts
- projects/igniteui-angular/src/lib/grids/grid/grid.component.spec.ts
> Running grid (selected) event in the angular zone 14.2

- projects/igniteui-angular/src/lib/grids/cell.component.ts
- projects/igniteui-angular/src/lib/grids/grid/grid.component.spec.ts
> Running grid (selected) event in the angular zone 15.0

- projects/igniteui-angular/src/lib/core/styles/components/button/_button-theme.scss
- projects/igniteui-angular/src/lib/core/styles/components/grid/_grid-theme.scss
- projects/igniteui-angular/src/lib/core/styles/components/list/_list-theme.scss
> fix(themes): passing css variables breaks build

- projects/igniteui-angular/src/lib/core/styles/components/banner/_banner-theme.scss
> fix(banner): actions not alligned vertically

- projects/igniteui-angular/src/lib/core/styles/components/card/_card-theme.scss
> feat(card): correctly size when height changes

- projects/igniteui-angular/src/lib/grids/grid/grid.component.html
- projects/igniteui-angular/src/lib/list/list-item.component.html
- projects/igniteui-angular/src/lib/list/list.component.spec.ts
Also fixing quotes in `grid.component.html` template.
> refactor(list): spec file refactoring

- projects/igniteui-angular/src/lib/grids/cell.component.ts
- projects/igniteui-angular/src/lib/grids/common/grid.interface.ts
> fix(grid): make the cell required in cell template context

- projects/igniteui-angular/src/lib/directives/mask/mask-parsing.service.ts
> fix(igxMask): Correct cursor position when typing - 14.2.x

- projects/igniteui-angular/src/lib/directives/mask/mask-parsing.service.ts
> fix(igxMask): Correct cursor position when typing - 15.0.x

- projects/igniteui-angular/src/lib/core/styles/themes/generators/_base.scss
- projects/igniteui-angular/src/lib/core/styles/themes/generators/_bootstrap.scss
- projects/igniteui-angular/src/lib/core/styles/themes/generators/_fluent.scss
- projects/igniteui-angular/src/lib/core/styles/themes/generators/_indigo.scss
> docs(themes): add missing docs around theme mixins

- CHANGELOG.md
- projects/igniteui-angular/src/lib/simple-combo/simple-combo.component.html
- projects/igniteui-angular/src/lib/simple-combo/simple-combo.component.spec.ts
- projects/igniteui-angular/src/lib/simple-combo/simple-combo.component.ts
> Simple-combo: Opening the combo on input click - master

- projects/igniteui-angular/src/lib/grids/common/strategy.ts
- projects/igniteui-angular/src/lib/grids/grid/grid.groupby.spec.ts
- projects/igniteui-angular/src/lib/grids/grid/grid.sorting.spec.ts
- projects/igniteui-angular/src/lib/grids/grid/groupby-row.component.html
- projects/igniteui-angular/src/lib/test-utils/sample-test-data.spec.ts
> fix(grid): Grouping for columns of dataType date, time and dateTime - 14.2.x

- projects/igniteui-angular/src/lib/grids/common/strategy.ts
- projects/igniteui-angular/src/lib/grids/grid/grid.groupby.spec.ts
- projects/igniteui-angular/src/lib/grids/grid/grid.sorting.spec.ts
- projects/igniteui-angular/src/lib/grids/grid/groupby-row.component.html
- projects/igniteui-angular/src/lib/test-utils/sample-test-data.spec.ts
> fix(grid): Grouping for columns of dataType date, time and dateTime - 15.0.x

- projects/igniteui-angular/migrations/migration-collection.json
- projects/igniteui-angular/migrations/update-15_0_0/index.spec.ts
- projects/igniteui-angular/migrations/update-15_0_0/index.ts
- projects/igniteui-angular/migrations/update-15_0_11/index.spec.ts
- projects/igniteui-angular/migrations/update-15_0_11/index.ts
- projects/igniteui-angular/schematics/utils/dependency-handler.ts
> Apply expected changes on update to v15

- projects/igniteui-angular/src/lib/core/styles/base/_variables.scss
- projects/igniteui-angular/src/lib/core/styles/components/combo/_combo-component.scss
- projects/igniteui-angular/src/lib/core/styles/components/dialog/_dialog-component.scss
- projects/igniteui-angular/src/lib/core/styles/components/drop-down/_drop-down-component.scss
- projects/igniteui-angular/src/lib/core/styles/components/grid-toolbar/_grid-toolbar-component.scss
- projects/igniteui-angular/src/lib/core/styles/components/snackbar/_snackbar-component.scss
- projects/igniteui-angular/src/lib/core/styles/components/toast/_toast-component.scss
> fix(theme): igx-overlay not registered as theme dependency

- projects/igniteui-angular/migrations/migration-collection.json
- projects/igniteui-angular/migrations/update-15_0_11/index.spec.ts
- projects/igniteui-angular/migrations/update-15_0_11/index.ts
Related to https://github.com/IgniteUI/igniteui-angular/pull/12607
> Update typography, scrollbar & grays

- projects/igniteui-angular/src/lib/grids/columns/column.component.ts
- projects/igniteui-angular/src/lib/grids/grid-base.directive.ts
> fix(grid, mrl): ensure column is available when invoking index prop

- projects/igniteui-angular/src/lib/directives/text-selection/text-selection.directive.spec.ts
- projects/igniteui-angular/src/lib/directives/text-selection/text-selection.directive.ts
Closes https://github.com/IgniteUI/igniteui-angular/issues/12566
> Wrap nativeElement.select in a raf call - 14.2.x

- projects/igniteui-angular/src/lib/directives/text-selection/text-selection.directive.spec.ts
- projects/igniteui-angular/src/lib/directives/text-selection/text-selection.directive.ts
Closes https://github.com/IgniteUI/igniteui-angular/issues/12566
> Wrap nativeElement.select in a raf call - 15.0.x

- projects/igniteui-angular/src/lib/core/styles/components/grid/_excel-filtering-theme.scss
> fix(filtering): tree in filtering menu displays scrollbar

- src/app/action-strip/action-strip.sample.html
- src/app/action-strip/action-strip.sample.scss
- src/app/action-strip/action-strip.sample.ts
> fix(button styling): add style properties to toggle button

- projects/igniteui-angular/src/lib/core/styles/components/tabs/_tabs-theme.scss
> feat(tabs scrolling): Add min-width to parent container on 15.0.x

- projects/igniteui-angular/src/lib/core/styles/components/tabs/_tabs-theme.scss
> feat(tabs scrolling): Add min-width to parent container on 14.2.x

- projects/igniteui-angular/src/lib/core/styles/components/tabs/_tabs-theme.scss
- src/app/date-range/date-range.sample.html
- src/app/date-range/date-range.sample.scss
> fix(title change): section title changed to reactive forms

- projects/igniteui-angular/src/lib/grids/grid-base.directive.ts
- projects/igniteui-angular/src/lib/grids/grid/grid-summary.spec.ts
> fix(grid): update group summaries when new row is added via UI

- projects/igniteui-angular/src/lib/grids/grid-base.directive.ts
- projects/igniteui-angular/src/lib/grids/grid/grid-summary.spec.ts
> fix(grid): update group summaries when new row is added via UI - 15.0.x

- projects/igniteui-angular/src/lib/grids/grid-base.directive.ts
- projects/igniteui-angular/src/lib/grids/grid/grid-summary.spec.ts
> fix(grid): update group summaries when new row is added via UI - 14.2.x

- projects/igniteui-angular/src/lib/badge/badge.component.ts
- projects/igniteui-angular/src/lib/core/styles/components/badge/_badge-component.scss
- projects/igniteui-angular/src/lib/core/styles/components/badge/_badge-theme.scss
- src/app/badge/badge.sample.html
> feat(badge): implement square shape

- projects/igniteui-angular/src/lib/directives/radio/radio-group.directive.spec.ts
- projects/igniteui-angular/src/lib/directives/radio/radio-group.directive.ts
- projects/igniteui-angular/src/lib/radio/radio.component.ts
> fix(radio-group): focus checked radio

- CHANGELOG.md
- projects/igniteui-angular/src/lib/data-operations/grouping-expression.interface.ts
- projects/igniteui-angular/src/lib/grids/columns/column.component.ts
- projects/igniteui-angular/src/lib/grids/common/strategy.ts
- projects/igniteui-angular/src/lib/grids/grid/grid.sorting.spec.ts
- projects/igniteui-angular/src/lib/test-utils/grid-samples.spec.ts
> fix(grid): Allow using custom sorting strategy when sorting mode is multiple

- projects/igniteui-angular/src/lib/data-operations/grouping-expression.interface.ts
- projects/igniteui-angular/src/lib/grids/columns/column.component.ts
- projects/igniteui-angular/src/lib/grids/common/strategy.ts
- projects/igniteui-angular/src/lib/grids/grid/grid.sorting.spec.ts
- projects/igniteui-angular/src/lib/test-utils/grid-samples.spec.ts
> fix(grid): Allow using custom sorting strategy when sorting mode is multiple - 14.2.x

- CHANGELOG.md
- projects/igniteui-angular/migrations/update-15_1_0/index.spec.ts
- projects/igniteui-angular/migrations/update-15_1_0/index.ts
- projects/igniteui-angular/src/lib/avatar/avatar.component.spec.ts
- projects/igniteui-angular/src/lib/avatar/avatar.component.ts
- projects/igniteui-angular/src/lib/core/styles/components/avatar/_avatar-component.scss
- projects/igniteui-angular/src/lib/core/styles/components/avatar/_avatar-theme.scss
- src/app/avatar/avatar.sample.html
> feat(avatar): add rounded shape

- README.md
- fix MD table structure (for compatibility with MD parsers tables should have `|` at both the beginning and the and of the line
- accessibility add `alt` text to the images
- minor formatting
Closes #
> [readme]: browser support section cleanup

- projects/igniteui-angular/src/lib/simple-combo/simple-combo.component.spec.ts
- projects/igniteui-angular/src/lib/simple-combo/simple-combo.component.ts
> fix(simple-combo): display all list items when clearing the input by Space - 15.0.x

- projects/igniteui-angular/src/lib/simple-combo/simple-combo.component.spec.ts
- projects/igniteui-angular/src/lib/simple-combo/simple-combo.component.ts
> fix(simple-combo): display all list items when clearing the input by Space - 14.2.x

- projects/igniteui-angular/src/lib/core/styles/base/_functions.scss
- projects/igniteui-angular/src/lib/core/styles/base/_mixins.scss
- projects/igniteui-angular/src/lib/core/styles/spec/_functions.spec.scss
- projects/igniteui-angular/src/lib/core/styles/themes/_core.scss
This PR adds support for registering theme dependencies by extension.
> refactor(themes): change how the dependency tree is built and checked

- projects/igniteui-angular/src/lib/core/styles/themes/generators/_base.scss
> fix(rating): size doesn't work

- projects/igniteui-angular/src/lib/grids/grid/grid-filtering-advanced.spec.ts
- projects/igniteui-angular/src/lib/query-builder/query-builder.component.ts
Closes #12570 
Note for testing: check all options in the context menu, including `Ungroup` and `Delete`
> fix(advanced-filtering): Commit operand edits made via the context menu - 14.2.x

- projects/igniteui-angular/src/lib/grids/grid/grid-filtering-advanced.spec.ts
- projects/igniteui-angular/src/lib/query-builder/query-builder.component.ts
Closes #12570 
Note for testing: check all options in the context menu, including `Ungroup` and `Delete`
> fix(advanced-filtering): Commit operand edits made via the context menu - 15.0.x

- projects/igniteui-angular/src/lib/combo/combo.common.ts
- projects/igniteui-angular/src/lib/simple-combo/simple-combo.component.spec.ts
- projects/igniteui-angular/src/lib/simple-combo/simple-combo.component.ts
> fix(IgxComboBase,IgxSimpleCombo): open the simple combo dropdown in the correct vertical direction - 14.2.x

- projects/igniteui-angular/src/lib/combo/combo.common.ts
- projects/igniteui-angular/src/lib/simple-combo/simple-combo.component.spec.ts
- projects/igniteui-angular/src/lib/simple-combo/simple-combo.component.ts
> fix(IgxComboBase,IgxSimpleCombo): open the simple combo dropdown in the correct vertical direction - 15.0.x

- CHANGELOG.md
> chore(changelog): Update changelog with primaryKey exposed argument

- projects/igniteui-angular/src/lib/grids/tree-grid/tree-cell.component.html
- projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid-integration.spec.ts
> fix(tree-grid-cell): igxTextSelection directive on target cell editors - 15.0.x

- projects/igniteui-angular/src/lib/grids/tree-grid/tree-cell.component.html
- projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid-integration.spec.ts
> fix(tree-grid-cell): igxTextSelection directive on target cell editors

- CHANGELOG.md
- projects/igniteui-angular/src/lib/core/styles/components/switch/_switch-component.scss
- projects/igniteui-angular/src/lib/core/styles/components/switch/_switch-theme.scss
- projects/igniteui-angular/src/lib/core/styles/themes/schemas/dark/_switch.scss
- projects/igniteui-angular/src/lib/core/styles/themes/schemas/light/_switch.scss
- projects/igniteui-angular/src/lib/directives/focus/focus.directive.spec.ts
- projects/igniteui-angular/src/lib/switch/switch.component.html
- projects/igniteui-angular/src/lib/switch/switch.component.spec.ts
- projects/igniteui-angular/src/lib/switch/switch.component.ts
> feat(switch): implement component validation

- projects/igniteui-angular/src/lib/grids/grid-base.directive.ts
> fix -Pivot grid does not report value of cell in selectedData 15.0

- projects/igniteui-angular/src/lib/services/excel/excel-exporter-grid.spec.ts
- projects/igniteui-angular/src/lib/services/excel/excel-files.ts
- projects/igniteui-angular/src/lib/services/excel/test-data.service.spec.ts
- projects/igniteui-angular/src/lib/services/excel/worksheet-data-dictionary.ts
- projects/igniteui-angular/src/lib/services/exporter-common/base-export-service.ts
- projects/igniteui-angular/src/lib/services/exporter-common/export-utilities.ts
> Escape special chars in column headers - 14.2.x

- projects/igniteui-angular/src/lib/services/excel/excel-exporter-grid.spec.ts
- projects/igniteui-angular/src/lib/services/excel/excel-files.ts
- projects/igniteui-angular/src/lib/services/excel/test-data.service.spec.ts
- projects/igniteui-angular/src/lib/services/excel/worksheet-data-dictionary.ts
- projects/igniteui-angular/src/lib/services/exporter-common/base-export-service.ts
- projects/igniteui-angular/src/lib/services/exporter-common/export-utilities.ts
> Escape special chars in column headers - 15.0.x

- projects/igniteui-angular/src/lib/services/excel/excel-exporter-grid.spec.ts
- projects/igniteui-angular/src/lib/services/excel/excel-files.ts
- projects/igniteui-angular/src/lib/services/excel/test-data.service.spec.ts
- projects/igniteui-angular/src/lib/services/excel/worksheet-data-dictionary.ts
- projects/igniteui-angular/src/lib/services/exporter-common/base-export-service.ts
- projects/igniteui-angular/src/lib/services/exporter-common/export-utilities.ts
> Escape special chars in column headers

- projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid-api.service.ts
- projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid-filtering.spec.ts
- projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid.component.spec.ts
- projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid.pipes.ts
> Display empty grid message when data is set and then cleared - 15.0

- projects/igniteui-angular/src/lib/card/README.md
- projects/igniteui-angular/src/lib/card/card.component.ts
- projects/igniteui-angular/src/lib/card/card.spec.ts
> fix(card): removing card header role #12792

- projects/igniteui-angular/src/lib/core/styles/components/input/_input-group-theme.scss
> fix(input-group) filtering icon is not showing if it's not from the original material icon set.

- projects/igniteui-angular/src/lib/core/styles/components/paginator/_paginator-theme.scss
- projects/igniteui-angular/src/lib/paginator/paginator.component.ts
- make the select inside the paginator to always be in compact density.
- change the width of the select to be a bit wider in order to show at least four digits before showing an ellipsis.
Closes #12805
> fix(select) Update the select size inside the context of the paginator.

- projects/igniteui-angular/src/lib/core/styles/components/input/_input-group-theme.scss
> fix(input-group) label cut off and broken ellipsis.

- projects/igniteui-angular/src/lib/directives/radio/radio-group.directive.ts
> fix(radio-group): keyboard navigation issues in dialog

- projects/igniteui-angular/package.json
Merge just before 15.1.0 release
> chore(schematics): official ingiteui schematics

- projects/igniteui-angular/src/lib/grids/filtering/base/grid-filtering-row.component.ts
- projects/igniteui-angular/src/lib/grids/grid/grid-filtering-ui.spec.ts
> fix(filtering): reset expression to selected unary condition - 14.2.x

- projects/igniteui-angular/src/lib/grids/grid/grid-filtering-ui.spec.ts
> fix(filtering): set correct expected result for selected unary condition test - 14.2.x

- projects/igniteui-angular/src/lib/grids/grid/grid-filtering-ui.spec.ts
> fix(filtering-ui): set correct expected result for selected unary condition test - 15.1.x

- src/app/grid-column-moving/grid-column-moving.sample.html
Closes [#3286](https://github.com/IgniteUI/igniteui-angular-samples/issues/3286)
> Remove selectionService from Grid Column Sample on 15.1.x

- src/app/grid-column-moving/grid-column-moving.sample.html
Closes [#3286](https://github.com/IgniteUI/igniteui-angular-samples/issues/3286)
> Remove selectionService from Grid Column Sample

- projects/igniteui-angular/src/lib/grids/grid/grid-filtering-advanced.spec.ts
- projects/igniteui-angular/src/lib/query-builder/query-builder.component.ts
> Update expression tree after new group is added - 14.2.x

- projects/igniteui-angular/src/lib/grids/grid/grid-filtering-advanced.spec.ts
- projects/igniteui-angular/src/lib/query-builder/query-builder.component.ts
> Update expr tree after new group is added - 15.1.x

- projects/igniteui-angular/src/lib/core/styles/README.md
> chore(*): update-schems-link

- projects/igniteui-angular/src/lib/chips/chip.component.ts
- projects/igniteui-angular/src/lib/chips/chips-area.component.ts
> fix(chip): add and use destroy subject - 14.2.x

- projects/igniteui-angular/src/lib/chips/chip.component.ts
- projects/igniteui-angular/src/lib/chips/chips-area.component.ts
> fix(chip): add and use destroy subject - 15.1.x

- projects/igniteui-angular/src/lib/core/styles/components/grid/_grid-theme.scss
> fix(grid): count badge doesn't respect colors

- projects/igniteui-angular/src/lib/input-group/input-group.component.html
- projects/igniteui-angular/src/lib/input-group/input-group.component.spec.ts
> fix(input-group): add type for upload file button - 14.2.x

- projects/igniteui-angular/src/lib/core/styles/components/grid-toolbar/_grid-toolbar-theme.scss
- src/app/grid-export/grid-export.sample.scss
> fix(toolbar): showProgress doesn't show progressbar

- projects/igniteui-angular/src/lib/date-range-picker/date-range-picker-inputs.common.ts
Closes https://github.com/IgniteUI/igniteui-angular/issues/12919
> Update IgxDateRangePicker's directives' comments - 14.2.x

- projects/igniteui-angular/src/lib/date-range-picker/date-range-picker-inputs.common.ts
Closes https://github.com/IgniteUI/igniteui-angular/issues/12919
> Update IgxDateRangePicker's directives' comments - 15.1.x

- projects/igniteui-angular/src/lib/directives/input/input.directive.spec.ts
- projects/igniteui-angular/src/lib/directives/input/input.directive.ts
> fix(IgxInputDirective): Calculate required value when input is bound via formControl 

- projects/igniteui-angular/src/lib/combo/combo.directives.ts
> Update combo directives' public api - 14.2.x

- projects/igniteui-angular/src/lib/combo/combo.directives.ts
> Update combo directives' public api - 15.1.x

- projects/igniteui-angular/src/lib/directives/input/input.directive.spec.ts
- projects/igniteui-angular/src/lib/directives/input/input.directive.ts
> fix(IgxInputDirective): Calculate required value when input is bound via formControl

- projects/igniteui-angular/src/lib/input-group/input-group.component.html
> fix(input-group): Remove the string from the clear icon.

- projects/igniteui-angular/src/lib/date-picker/date-picker.module.ts
Closes https://github.com/IgniteUI/igniteui-angular/issues/10964
> Export IgxInputGroupModule in the IgxDatePickerModule - 14.2.x

- projects/igniteui-angular/src/lib/stepper/stepper.component.spec.ts
- projects/igniteui-angular/src/lib/stepper/stepper.component.ts
> Fix(stepper): Calculate disabled steps when linear mode is set initially
